### ISSUE TITLE
[Excel] Can't use keyboard shortcut when opening taskpane

### ISSUE THREAD

**Issue by knight-baron** [OfficeDev/office-js#3630] opened 2023-08-31 07:25 UTC
Hi Team,
Now I'm facing a bit weird behavior, when I open the taskpane or mouse click on taskpane, I can't use any keyboard shortcuts, is this a bug? Or is it a design about the functionality of Excel?

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2307 (Build 16626.20170)
* Operating System: Windows 10

 
## Expected behavior

Shortcuts can be used after opening the taskpane without clicking on the Ribbon or Workbook.

## Current behavior

When opening an app with the taskpane or mouse clicking on the taskpane, the user cannot use keyboard shortcuts. 

To use a keyboard shortcut when opening a taskpane, you'll need to click on the Ribbon or Workbook before you can use the keyboard shortcut.

## Steps to reproduce

![Screenshot_27](https://github.com/OfficeDev/office-js/assets/95019420/ab6b8961-e2cb-4f1a-b4f3-8f42f9a934a6)
1. Click **Home** on the ribbon menu bar then click **Analyze Data** or any other app that opens with taskpane.
2. Once the taskpane is open try the **Ctrl + P** or **Ctrl + O** keyboard shortcut, the keyboard shortcut will not work.

**Comment by m-hellesen** [comment] 2023-09-19 17:54
Thanks for reporting. Looking into this now.

**Comment by EsterBergen** [comment] 2023-09-21 20:46
hi @knight-baron! 

Thank you so much for reporting/posting and for providing such excellent repro steps.

When you launch the Analyze Pane or any panel add-in, you're making the panel active and not the sheet. For any CTRL+XYZ keystroke to work, the sheet must be active. In order for those commands to work, please select a cell on the excel workbook/sheet to make that active for the CTRL function.

Let us know if there are any other questions! Thanks again.

**Comment by knight-baron** [comment] 2023-09-25 10:03
Hi @EsterBergen 
This means that this is not a bug. It's a Microsoft design, right?

**Comment by EsterBergen** [comment] 2023-09-25 16:49
@knight-baron - Yes. I changed the label as "by design". Let us know if there are any other questions. We can close this thread otherwise.

**Closed as completed by EsterBergen** 2023-09-25 16:49 UTC
Labels: Needs: attention :wave:, Area: Excel, Status: under investigation, Resolution: by design
