### ISSUE TITLE
Outlook add-ins are not working for a Gmail account.

### ISSUE THREAD

**Issue by leonardo-vivere** [OfficeDev/office-js#4589] opened 2024-06-20 14:58 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office LTSC Standard to Mac 2024
* Operating System: macOS Sonoma Versão 14.5 (23F79)
* Browser (if using Office on the web): ______
 
## Expected behavior

Outlook add-ins are not working for a Gmail account.

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context
 Daily impact on product use

## Useful logs

- [ ] Console errors
- [X] Screenshots
- [ ] Test file (if only happens on a particular file)

https://github.com/OfficeDev/office-js/assets/172442683/056e9474-0038-4def-b0ea-4c9fab5473a4

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 

**Attached is a video of the process and the reported bug.**

My contact: leonardojacaranda@hotmail.com

**Comment by illing2005** [comment] 2024-06-25 13:59
We are facing the same issue. 
It is actually related to this one:
https://github.com/OfficeDev/office-js/issues/4583

**Comment by Swathy-Mothilal** [comment] 2024-07-02 07:09
@leonardo-vivere , We are unable to repro the issue. Could you please confirm if you have installed add-ins for this specific Gmail account, or are you trying to launch add-ins installed on other accounts from your Gmail?

Can you please generate the powerlift logs, where the issue is reproducible?

Steps to generate powerlift logs.
Help -> Collect Diagnostics
This will generate a diagnostic id, please share that id with us.

**Comment by leonardo-vivere** [comment] 2024-07-08 12:07
Hello. I was unable to generate the diagnostic id. My Outlook does not generate this option to diagnostic id.

<img width="1470" alt="Captura de Tela 2024-07-08 às 09 07 01" src="https://github.com/OfficeDev/office-js/assets/172442683/1e4d0996-a531-4b83-bf79-b2c1ec6b7c10">
<img width="1470" alt="Captura de Tela 2024-07-08 às 09 04 36" src="https://github.com/OfficeDev/office-js/assets/172442683/8eaa51c4-2f99-4201-9550-a4cb0e0d85a5">

**Comment by rkpathak** [comment] 2024-07-09 05:32
@leonardo-vivere Could you please add clear set of steps that we need to do to reproduce this issue. Starting from accounts added, addin installed, add all the details.

**Comment by leonardo-vivere** [comment] 2024-07-09 16:58
Hello.

Attached is the complete video of the process leading up to the reported problem.

https://github.com/OfficeDev/office-js/assets/172442683/9a3faf55-3a56-4de9-b1d9-842660654b3b

**Comment by rkpathak** [comment] 2024-07-11 15:56
@leonardo-vivere Do you have Addin installed for the non hotmail account? Only addins installed for respective accounts are enabled when that account is selected.
Please collect the diagnostics log following the step below and share the diagnostic id.
![image](https://github.com/OfficeDev/office-js/assets/3750499/c54753be-1fa1-4722-b06b-4f1636786fc2)

**Comment by leonardo-vivere** [comment] 2024-07-16 00:21
The option shown in the screenshot above does not appear in my outlook version. Unfortunately I will not be able to simulate and send the diagnosis. You can close the case.

**Comment by kumarshrey-msft** [comment] 2024-07-16 05:18
Hi @leonardo-vivere,
At the time of adding your Gmail account, please sync with the Microsoft Cloud instead of syncing directly with Google.  As mentioned in our public documentation [here](https://support.microsoft.com/en-us/office/sync-your-account-in-outlook-to-the-microsoft-cloud-985f9e19-d308-4e85-9d1d-0c6f32f8e981), this will enable you to use the new features of the Outlook client with your non-Microsoft account.


<img width="458" alt="Screenshot 2024-07-16 at 10 19 54 AM" src="https://github.com/user-attachments/assets/498e12b2-f55e-42ae-bb9f-b881595336ab">

If this too doesn't mitigates the issue, can you check if [Optional Connected Experiences](https://learn.microsoft.com/en-us/deployoffice/privacy/optional-connected-experiences) is enabled for you?

**Comment by leonardo-vivere** [comment] 2024-07-16 23:48
Hello  @kumarshrey-msft. The suggestion you made in the previous message worked perfectly. With synchronization through Microsoft Cloud, I can use the add-ins regardless of my email account's server. Thank you very much!

**Comment by kumarshrey-msft** [comment] 2024-07-17 09:33
Glad the solution worked for you!

**Comment by kumarshrey-msft** [comment] 2024-07-17 09:34
Closing the issue as completed

**Closed as completed by kumarshrey-msft** 2024-07-17 09:34 UTC
Labels: Area: Outlook
