### ISSUE TITLE
window.external.RegisterEvent is not a function on Mac for Word

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#97] opened 2018-04-18 06:53 UTC
## Expected Behavior
When opening a dialog in mac that contains office.js no error should be thrown.

## Current Behavior
When you open a dialog in Mac for Word that contains office.js an exception is thrown "window.external.RegisterEvent is not a function."

## Reproduction
It is hard to reproduce because it happens while loading the word-mac-16.00.debug.js in the MacRichClientHostController method. The method seems to be available in the pane but not available within the dialog.

```
MacRichClientHostController.prototype.registerEvent=function (id, targetId, handler, callback) {
  setTimeout(function () {
    window.external.RegisterEvent(id, targetId, handler, callback);
  }, 0);
};
```

## Your Environment
* Platform: Mac
* Host: Word
* Office version number: 16.12 (180410)
* Operating System: High Sierra 10.13.4

**Comment by JuaneloJuanelo** [comment] 2018-05-08 01:39
@barisbikmaz  unfortunately, this is not enough information to repro the issue. for instance, its confusing that you mention "opening a dialog" what exactly you mean by that? is this using our show Dialog API? 

I will be helpful if you can add more details and code, otherwise this is non-actionable on our end.

thanks!

**Comment by danielgwilson** [comment] 2018-09-07 18:25
Hi @barisbikmaz, I believe you're running into an issue by design; we don't allow for API calls from inside a dialog window. I'm going to close this for now, but please provide more info if you believe I'm misunderstanding.

**Closed as completed** 2018-09-07 18:25 UTC

**Comment by jandramila** [comment] 2018-09-14 17:37
I'm having the same issue, the problem here is when running a Single Page Application on our Add-In.

For instance, I'm running react and my index.html downloads the office.js script, and my main.js containing the SPA, dialogs only show a specific route but the office.js file gets downloaded eitherway.

**Comment by danielgwilson** [comment] 2018-09-14 18:12
> I'm having the same issue, the problem here is when running a Single Page Application on our Add-In.
> 
> For instance, I'm running react and my index.html downloads the office.js script, and my main.js containing the SPA, dialogs only show a specific route but the office.js file gets downloaded eitherway.

Interesting... @jandramila could you describe your setup in more detail? It's my understanding that the DialogAPI was originally developed for Auth purposes only; anything that interacts with the document is meant to exist solely in the task pane.

It sounds like you're using an SPA for the task pane and loading the same SPA in the dialog which results in office-js being loaded—is that correct? If so, what functionality are you trying to add with the dialog that cannot be accomplished with the task pane?

**Comment by jandramila** [comment] 2018-09-14 20:50
Hello @danielgwilson thank you very much for your quick response, we are currently using the Dialog to prompt the user for approval whenever an external link (that will open in an external browser tab) is opened.

The problem I just noticed is we are using `Office.context.ui.messageParent` to close the dialog using the main task pane reference to it and `dialog.close` function, so we must load the Office.js bundle.

Anyway, this message appears at first when opening dialog's console:

```
TypeError: window.external.RegisterEvent is not a function. (In 'window.external.RegisterEvent(n,t,i,r)', 'window.external.RegisterEvent' is undefined)
```

**Comment by barisbikmaz** [comment] 2018-09-20 15:33
Hi @danielgwilson, @Jua,
We've created a small app (vanilla JS) to repoduce the issue here: [https://github.com/hxltinh/office-js-bug-reproduction](https://github.com/hxltinh/office-js-bug-reproduction)

Just download the app on Mac and follow the readme to install certs, manifest and setup hosts file. (Sorry could not find an easier way)

When you click the button to open dialog in the app you will see that the window.external.RegisterEvent is called by the console, which seems not to exist on Mac but in other environments.

When you remove the override for window.external.RegisterEvent in the code you will also see the exception.

**Comment by benhoad** [comment] 2019-02-25 06:43
Any solution to this?

Currently experiencing a similar issue with auth redirect/message passing flow.
