### ISSUE TITLE
[Excel] DocumentProperties.lastSaveTime

### ISSUE THREAD

**Issue by nrueckmann** [OfficeDev/office-js#2260] opened 2021-11-19 12:54 UTC
Why is there no DocumentProperties.lastSaveTime for Excel documents like we have for Word documents?

Is there any workaround to detect if a file has been changed by a user not using the Add-In? Example: We have an Add-In which pushes data to a third party. The user should push the data whenever he finished his work. The Add-In will remind him to push the data before closing the document. But the user could also download the xlsx, editing it locally and then uploading the file via OneDrive. When someone opens the file in Excel 365 (with installed Add-In) again, how can the Add-In know if the data has been changes and that use needs to be reminded, that he needs to push the data?

**Comment by alison-mk** [comment] 2021-11-20 00:10
Hi @nrueckmann, thank you for submitting this issue! I've assigned it to @dingjin-ms who will be able to provide you with more information. 

Cheers,
Alison

**Comment by chiz-ms** [comment] 2021-11-20 09:09
Hi @nrueckmann, as you've described, currently `DocumentProperties.lastSaveTime` is not supported in Excel Add-In. A workaround would be using Graph API to get `lastModifiedDateTime`: https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0. But please note that Microsoft Graph is a separate set of REST APIs and has its own limitations.

You may also want to consider going to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) and see if this feature has already been requested or request a new feature.

**Comment by nrueckmann** [comment] 2022-01-13 10:03
Thank you for your feedback @chiz-ms 

Currently, i'm using a workaround by downloading the file `Office.context.document.getFileAsync` to get the `ModifiedDate`. Unfortunately, Excel seems to touch the file on startup, so the `ModifiedDate` will always be the date when you you open the file or newer. Is this the expected behavior?

**Comment by yuc014** [comment] 2022-01-17 08:24
Hi @nrueckmann,

About the `ModifiedDate` in `Office.context.document.getFileAsync`. It is by design.

Since `getFileAsync` is meant to generate entire document file. 

In the generated file I see `<xmp:CreatorTool>Microsoft Excel</xmp:CreatorTool><xmp:CreateDate>2022-01-16T23:53:21-08:00</xmp:CreateDate><xmp:ModifyDate>2022-01-16T23:53:21-08:00</xmp:ModifyDate></rdf:Description>` 

So the `ModifiedDate` means the time you called api to create this file.

Back to the initial issue, I suggest use Graph API as @chiz-ms  said or VBA code to save lastSaveTime to a cell (or the document property i'm not sure), and use your add-in read the value from it. But this workaround depend on your scenario.

If you still be blocked, visit https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform to request a new feature.

Thanks.

**Closed as completed** 2022-11-24 14:01 UTC
Labels: Area: Excel, Needs: author feedback, Type: product feature request, Status: no recent activity
