### ISSUE TITLE
Debugging Excel Add In with Webview2 stops after some seconds, add-in reloads

### ISSUE THREAD

**Issue by boboano** [OfficeDev/office-js#1938] opened 2021-06-18 08:15 UTC
## Environment

* Platform: PC desktop, office 365
* Host: Excel® for Microsoft 365 MSO
* Office version number: 16.0.14026.20270) 64-bit 
* Operating System: windows 10 Pro, 21H1, 19043.1055
* Browser: Microsoft Edge; Version 91.0.864.48 (Official build) (64-bit)
* Microsoft Edge WebView 2 Runtime, 91.0.864.48
* Visual Studio Code, Version 1.57.0
* Excel-custom-functions-js: 2.0.0
 
## Expected behavior

Hitting the “inspect” button (Excel-add in, context menue) I expect being able to see the Webview2 window for longer than some seconds.
## Current behavior

Webview2 window closes automatically after some seconds. Debugging not possible. Add-in reloads automatically. Workaround “edge://inspect” does not work, content disappears too, after some seconds
## Steps to reproduce

1. Command-Window, Admin rights
2. generate an Excel add-in with custom functions, run the command yo office --projectType excel-functions --name 'Excel shared runtime add-in' --host excel --js true.“
3. Visual Code Code: 
a)	Debug Terminal: npm run build, npm start
b)	Window “WebView Stop On Load” appears
c)	Microsoft Debugger for Edge extension attached, OK 
d)	Taskpane “Logo/Welcome”, Context Menu, Inspect
e)	Window Developer Tools … appears and disappears within less than 5 seconds
Reference: Debug add-ins on Windows using Microsoft Edge WebView2 (Chromium-based) - Office Add-ins | Microsoft Docs
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-desktop-using-edge-chromium
 
## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

While opening Excel and the addin, Excel reports “Error installing add-ins, One ore more add-ins failed to download a required resource”. However, it’s possible to click “Logo-Show Taskpane”, Context Menue “inspect”. Later this error message disappears, although the add-in is running, and I am able to start “inspect”.

Adding Registry key (Wef) does not solve the problem, reference: „When debugging with the Microsoft Edge DevTools, the add-in crashes or reloads“, https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins 

Same problem with standard “yeo excel custom functions project” (generated by “yo office”, Javascript)

I assume a bug, although I am not sure... Don|t know if the error messages and the webview2 behavior are connected.
Thanks for your help! bobo
## Useful logs

- [ ] Console errors

Tracking Prevention blocked access to storage for https://appsforoffice.. Taskpane.html; 
Failed to load resource: the server  responded with status of 404…:3000/favicon.ico:1 (not found), although in Edge Tracking Prevention is switched off 

![image](https://user-images.githubusercontent.com/86003744/122527281-080aba00-cfd0-11eb-82f0-bb6a8f46fe0a.png)

**Comment by alison-mk** [comment] 2021-06-18 14:59
Hi @boboano, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by wh1t3cAt1k** [comment] 2021-07-14 21:26
@sshukurov can you confirm this is also what we are experiencing with Edge?

**Comment by sshukurov** [comment] 2021-07-14 22:27
@wh1t3cAt1k yep, just verified, the issue is still there.

Looks like https://github.com/OfficeDev/office-js/issues/1965 is a duplicate.

**Comment by grangeryy** [comment] 2021-07-16 01:47
@smaremanda not custom function specifically, but also other add-ins seem encounter the issue too. Not sure if this is similar as #1965?

**Comment by HelenNeigel** [comment] 2022-02-25 01:05
Hi guys, looks like the issue is back:

Office version number: Microsoft® Excel® for Microsoft 365 MSO (16.0.14326.20782) 64-bit 
Operating System: Windows 10
Browser: Microsoft Edge Version 98.0.1108.62 (Official build) (64-bit)

**Comment by alison-mk** [comment] 2022-02-25 19:59
Hi @HelenNeigel, thanks for the information. @guliums can you take a look at this issue?

**Comment by guliums** [comment] 2022-02-28 04:51
Duplicated with https://github.com/OfficeDev/office-js/issues/1965 @Dengshan2018 could you take a look? Thanks.

**Comment by Dengshan2018** [comment] 2022-02-28 17:17
@HelenNeigel , are same repro steps or different?

**Comment by HelenNeigel** [comment] 2022-03-08 02:37
Steps are the same, uploaded video for https://github.com/OfficeDev/office-js/issues/1965

**Comment by HelenNeigel** [comment] 2022-03-11 03:47
@Dengshan2018 I tried a different machine. All work there as expected. Not sure what causes the issue on my machine. I'll try to investigate. Thank you for your help.

**Comment by Dengshan2018** [comment] 2022-03-11 05:23
@HelenNeigel thanks for the update. will see any more updates. or crash dump for msedgewebview2.exe

**Comment by Dengshan2018** [comment] 2022-05-24 16:38
Just close the issue. @HelenNeigel feel free to open new bug if you have new repo.

**Closed as completed** 2022-05-24 16:38 UTC
Labels: Type: product bug
