### ISSUE TITLE
Outlook Desktop, ribbon icons of installed add-ins disappear, no installed add-ins in the Get Add-ins dialog

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#2731] opened 2022-07-27 14:45 UTC
# Provide required information needed to triage your issue
We develop an Outlook add-in for compose mode. The add-in has a ribbon button. Sometimes our ribbon button disappears along with the buttons of other add-ins. And in this case, there are no installed add-ins in the Get Add-ins dialog.

## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: Version 2206 (Build 15330.20264) 64 bit
* Operating System: Version 21H1 (OS Build 19043.1826)
* Browser (if using Office on the web):
 
## Expected behavior
The ribbon button shall not disappear.

## Current behavior
The ribbon button disappears, there are no items in the My add-ins section of the Get Add-ins dialog.

## Steps to reproduce
Sorry, but there are no exact steps. Sometimes Outlook works normally for 3 days, and then the issue occurs. Today the issue has occurred after 1.5 hours of Outlook working.

# Provide additional details
Please have a look at the screenshots attached:
01.png – The issue itself. Note, the default Viva Insight and View Templates buttons also disappeared.
02.png – Version info.
03.png – Information from the About dialog.
04.png – Information from the Get Add-ins dialog.

The only workaround that we have so far:
- Close Outlook completely.
- Wait for 2-5 minutes.
- Open Outlook anew.

After these manipulations, both ribbon buttons and the Get Add-ins dialog start working (see 05.png). The issue is reproducible on the client's side as well.

If you need any additional information, feel free to ask me.

## Useful logs
- [ x ] Screenshots
[screenshots.zip](https://github.com/OfficeDev/office-js/files/9200116/screenshots.zip)

**Comment by DmitryKostochko** [comment] 2022-08-17 10:28
Do you have any news about the issue?

**Comment by JuaneloJuanelo** [comment] 2022-08-25 19:07
@DmitryKostochko  we have seen reports about this and we identified a root cause for this and we rolled out a fix. 
btw i wonder why you have not installed the latest update for windows?  (also are you in the Monthly Enterprise Channel(MEC)? or what licensing you have? just to make sure you are getting this fix. (might be delayed a bit in the MEC)

btw the latest update is build 16.0.15427.20210   Ver 2207

**Comment by DmitryKostochko** [comment] 2022-08-26 08:47
@JuaneloJuanelo, thank you.

I have Windows 10 Pro and don't know the exact reason why the 21H2 update has not come to my machine yet, probably it will arrive later.

> btw the latest update is build 16.0.15427.20210 Ver 2207

I already have this update installed.

Please specify - in which update did you include the fix?

**Comment by JuaneloJuanelo** [comment] 2022-08-29 21:43
@DmitryKostochko this is an Office Update, this has no dependency with the Windows build.
You should not see this problem anymore, can you please confirm?

**Comment by DmitryKostochko** [comment] 2022-08-30 08:36
@JuaneloJuanelo, Sorry, right now I can't confirm that the issue has been fixed because it was quite unexpected and reproduced sporadically. Please, give us a week, we will watch our Outlooks.

**Comment by DmitryKostochko** [comment] 2022-09-07 13:49
@JuaneloJuanelo, we haven't seen this issue so far, it seems to be fixed. Please close the case, thank you!

**Comment by JuaneloJuanelo** [comment] 2022-09-15 23:05
Happy to hear this thanks so much! I am closing this issue now :)

**Closed as completed by JuaneloJuanelo** 2022-09-15 23:05 UTC
Labels: Needs: attention :wave:, Area: Outlook

**Comment by Gigasoft** [comment] 2023-02-23 16:47
@DmitryKostochko @JuaneloJuanelo  I see this issue frequently with my Outlook add-in. It happens randomly and is very annoying - especially to my customers.  I have version >> Microsoft® Outlook® 2019 MSO (Version 2301 Build 16.0.16026.20196) 64-bit - my customers use Office 365 primarily. But this is not related to one specific version. It happens on all versions.

FYI - I have a VSTO add-in

My best guess is that it is triggered by mouseover events.
