### ISSUE TITLE
Excel: Double clicking on Ribbon item opens multiple taskpanes

### ISSUE THREAD

**Issue by ppagadala** [OfficeDev/office-js#1277] opened 2020-07-13 06:51 UTC
## Expected Behavior
One instance of the Task pane should be opened.

## Current Behavior
Two panes are opened.
Should not open two taskpanes or should give config param in manifest to disable the double click on Ribbon item.

## Steps to Reproduce, or Live Example
1. Have a plain manifest with a button in ribbon which opens a taskpane
2. Upload the manifest in Excel.
3. Double click on the Ribbon item
4. Then it opens two taskpanes.
5. if you click Ribbon item **n** number of times **n** number of taskpanes will open.

## Context
Expecting it to open only one taskpane but opens two.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
![Multiple_Taskpane_issue](https://user-images.githubusercontent.com/11500788/87278870-26844d80-c503-11ea-85b2-7423d8994a2a.gif)

- [ ] Test file (if only happens on a particular file)

**Comment by keyur32** [comment] 2020-07-29 22:53
Closing this as it appears to be a duplicate of https://github.com/OfficeDev/office-js/issues/1278.

**Closed as completed** 2020-07-29 22:55 UTC
Labels: Needs: attention :wave:, Area: Excel, Resolution: duplicate
