### ISSUE TITLE
Word CustomXmlPart is deleted 

### ISSUE THREAD

**Issue by ssoni2074** [OfficeDev/office-js#1742] opened 2021-03-23 05:18 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am using 
`Office.context.document.customXmlParts.addAsync('<someTag>${data}</someTag>',
        (result: Office.AsyncResult<Office.CustomXmlPart>) => {
        save(data)
        })`
to save customXml. On web it works I can save/retrieve  xml but when i download this document or choose `open in desktop` and then try to retrieve this xml in desktop application it fails. PFA 
Also if anyone can answer on stackoverflow  [Difference between Word.CustomXmlPart and Office.CustomXmlParts ](https://stackoverflow.com/questions/66742284/difference-between-word-customxmlpart-and-office-customxmlparts/66752289?noredirect=1#comment118008462_66752289)
## Expected Behavior
It should not delete that customXml part (as I assume it is saved on document package).

## Current Behavior
It is deleting xml

## Steps to Reproduce, or Live Example
Open WORD on web
insert xml 
save id
download docx
try to retrieve that xml on desktop application 
it will fail

## Context
it breaks functionality 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:desktop , web
* Host [Excel, Word, PowerPoint, etc.]: word
* Operating System: windows 10
* Browser (if using Office on the web): all

## Useful logs

- [ ] Screenshots

desktop 
![image](https://user-images.githubusercontent.com/66596870/112096632-abf8eb00-8bc4-11eb-8ed0-0514f45b65dc.png)

web
![image](https://user-images.githubusercontent.com/66596870/112096672-c337d880-8bc4-11eb-9052-c8b768b1d179.png)

**Comment by AbidRahman-MSFT** [comment] 2021-04-28 22:23
Thanks for reporting the issue, @ssoni2074. I can replicate the issue myself. @yihuax can you help investigate? If I'm setting it on Web, I can fetch it from Web but when I download to Windows, I can't fetch it anymore.

Repro steps:
1. Open new file on Word Web
2. Use code below to set customxml 
3. Download file to desktop
4. Use second code below to fetch customxml

Code used on Word Web to set customxml: 
```
    Office.context.document.customXmlParts.addAsync(
      '<someTag> ${ data } </someTag>',
      function(result) {
        customXmlId = result.value.id;
        console.log(customXmlId);
      }
    );
```

Take the customxml id from the console log and use to fetch it on Word Desktop with this code:

```
    Office.context.document.customXmlParts.getByIdAsync(
      `{INSERT-CUSTOMXML-ID-HERE}`,
      function(result) {
        var xmlPart = result.value;
        xmlPart.getXmlAsync({}, function (eventArgs) {
          console.log(eventArgs.value);
        });
    });
```

**Comment by yihuax-zz** [comment] 2021-04-29 06:14
Yes, I can repro it too.  Our custom XML setting and reading APIs are both working correctly. The custom XML ID is saved to file correctly too.  But when it is opened in Word win32, the custom XML part is not deleted, but its ID gets changed. I can verify it with VBA.  Looks this is a Word native behavior to change the custom XML ID when a document from internet is opened.  I am not sure whether it is by design for security, or it is a bug. We should assign it to Word team.
Thanks!
Yihua

**Closed as not planned** 2024-03-28 19:53 UTC
Labels: Needs: attention :wave:, Area: Word
