### ISSUE TITLE
Store Add in is duplicating after reopening  

### ISSUE THREAD

**Issue by A-Glazer** [OfficeDev/office-js#3793] opened 2023-10-30 15:16 UTC
Download an Add in from the Microsoft Store that opens in a panel. Open the add in, close it, open it again. The panel is duplicated and doesn't appear properly. Then close the panel and reopen it again. A message appears "Add-in Error Something went wrong and we couldn't start this add-in. Please try again later or contact your system administrator." I downloaded a couple different add ins and they all have the same issue.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web, Windows
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft 365
* Operating System: PC
* Browser (if using Office on the web): Chrome
* *Build: 16.0.17022.40519
 
## Expected behavior
The panel should be able to open and close without any issues.

**Comment by penglongzhaochina** [comment] 2023-11-02 12:02
Hi @A-Glazer I can't reproduce your issue. Could you please give me more details about this issue? Thanks.

**Comment by A-Glazer** [comment] 2023-11-02 15:09
Open Windows > Chrome > Word Web. Go to the Microsoft Add-on Store. Search for LinkrUI and click Add. The first time the add-on displays correctly.

![image](https://github.com/OfficeDev/office-js/assets/40736908/39980b4d-bb6d-45cc-ae01-4402d0adf657)

If you click the button again (or a few times), you'll see the panel is duplicating. 

![image](https://github.com/OfficeDev/office-js/assets/40736908/c93cd708-e1ea-4a21-bdaf-867ea9afd121)

If you press it another time, you get an error to contact the administrator.

![image](https://github.com/OfficeDev/office-js/assets/40736908/d3729af1-8dd6-4b2a-a0d1-bc57dde220b4)

**Comment by MicGensty** [comment] 2023-11-03 08:51
I can reproduce this issue, event with MS Script Lab.
![obraz](https://github.com/OfficeDev/office-js/assets/92395406/047f2fbe-2c10-4196-b072-1814913e8381)

This impacts our users experience with our product and make it look broken.

And the same situation is on Mac.

**Comment by penglongzhaochina** [comment] 2023-11-06 04:25
Hi all,

Thank you reporting this issue, I can reproduced this issue. I have transferred this issue to the right team. They are actively working on it. We will keep you posted. Thank you so much.

**Comment by Henryz2023** [comment] 2023-11-06 18:12
Hi, I am having a local fix and will check in soon.

**Comment by A-Glazer** [comment] 2024-01-03 12:22
Hi @Henryz2023, any update on this issue?

**Comment by xiruatms** [comment] 2024-06-04 02:08
@A-Glazer , will you please take a try whether this issue is still there?

**Comment by A-Glazer** [comment] 2024-06-04 08:55
I couldn't reproduce it anymore.

**Comment by xiruatms** [comment] 2024-06-04 09:19
Thanks for your confirmation. I'm closing this now, feel free to create new one if you encountered anything else.

**Closed as completed by xiruatms** 2024-06-04 09:19 UTC
Labels: Needs: attention :wave:, Area: Word
