### ISSUE TITLE
Add-in does not launch when configured to receive Microsoft365 pre-release programs

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#3501] opened 2023-07-11 04:48 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook on the web
* Microsoft® Outlook® for Microsoft 365 MSO (version 2306 build 16.0.16529.20100) 64-bit
* Operating System: Windows OS
* Browser (if using Office on the web):Google Chrome , Microsoft Edge
 
## Summary
We are currently experiencing problems with the Outlook Javascript add-in. 
The problem is as follows.

## Expected behavior

1. Install the Office add-in in Outlook on the web.
2. Click the "New Mail" button to open the compose mail screen.
3. Specify the recipient and click the "Send" button.
4. The Office add-in starts and the display appears (displayDialogAsync API is activated).
5. After checking each item, click the "Send" button.
6. An email will be sent.

## Current behavior

1. Install the add-in in Outlook on the web.
2. Click the "New Mail" button to open the compose mail screen.
3. Specify the recipient and click the "Send" button.
4. The Office add-in will not start and the email will be sent as is.

## Steps to reproduce

1. Open the "Organization Settings" page in the Microsoft365 Management Center.
2. Click on the "Release Settings" settings menu.
3. Select either "Targeted releases for all" or "Targeted releases for specific users.
4. Launch the command prompt and navigate to the corresponding directory.
5. Run "npm install".
6. Run "npm run dev-server".
7. Upload "manifest.xml" to Outlook on the web and install the add-in (XML file is stored in sample.zip)
8. Click the "New Mail" button to open the mail composer screen.
9. Specify the recipient and click the "Send" button.

## Remarks
* Outlook javascript add-ins are not launching in all cases.
* Closing the browser may or may not improve the problem.
* This problem does not occur when the standard release of the program is applied.
* The UI of Outlook on the web has been changed in the previous release of the program.

## Link to live example(s)

I am storing the sample add-in.
* sample add-in program
  https://drive.google.com/file/d/1Xrc-HuBLSjBAwDmU7y7Pbi7amwegbPDY/view?usp=share_link

We have received feedback from customer requesting improvements.
Please investigate and make necessary improvements.

**Comment by t-ariyoshi30907** [comment] 2023-07-12 02:13
@exextoc 

This is a problem that seriously damages your business.
Can you raise the priority and ask for a response?

**Comment by exextoc** [comment] 2023-07-12 04:10
Can you please share the network/fiddler trace for GetExtensibilityContext and Acquisitions call? Steps to capture the calls:
1. Start fiddler capturing
2. Reload OWA
3. Open any mail item
4. check in fiddler if GetExtensibilityContext and Acquisitions call has happened
5. Stop fiddler capturing if we have both the calls captured.
6. Share the fiddler trace.

Thanks.

**Comment by t-ariyoshi30907** [comment] 2023-07-12 10:42
@exextoc 
I have recorded the Fiddler Trace using Sara. 
https://drive.google.com/file/d/1oeoPclCZX-PV2UdDv3jNtqxiN8QwxZz8/view?usp=drive_link
Please review it. If it doesn't meet your requirements, please provide specific instructions for the desired task.

**Comment by exextoc** [comment] 2023-07-13 03:48
Looks like the fiddler trace provided is password protected, please share the password/decrypt the session archive and share again.

**Comment by t-ariyoshi30907** [comment] 2023-07-13 09:35
@exextoc 

I will share the file again. Since it doesn't have a password, you can review the contents right away.
https://drive.google.com/file/d/1ejLk4bA0S2ZvFQFGMDkMfywwxZaLIZ2l/view?usp=drive_link

**Comment by exextoc** [comment] 2023-07-13 12:06
The fiddler trace shared doesn't have the Acquisitions and GetExtensibilityContext call, kindly follow the steps shared int he previous comment to capture the network trace.

**Comment by t-ariyoshi30907** [comment] 2023-07-13 12:45
@exextoc 

I will share the newly recorded fiddler trace again. Since it is not password-protected, you can review the contents immediately.
https://drive.google.com/file/d/1RTh4gUGqREXPWcIchv6h8htO6Fs7N_aq/view?usp=drive_link

**Comment by t-ariyoshi30907** [comment] 2023-07-18 07:47
@exextoc 
Have you had a chance to review the Fiddler trace I shared? We've received reports from multiple users, and this is a high-priority issue. Please let me know about the status of the investigation and resolution.

**Comment by exextoc** [comment] 2023-07-26 06:13
Hi @t-ariyoshi30907, could you please confirm if you're still facing this issue? We are currently seeing a delay of up to four hours in installation and the add-in being available. Thanks!

**Comment by t-ariyoshi30907** [comment] 2023-07-28 04:35
@exextoc 
Some users experience the occurrence of this issue, while others do not.
Furthermore, there are users for whom the add-in starts working within 4 hours, and on the other hand, there are users who have been waiting for a whole day without the add-in starting.

Is it indeed expected for the add-in to become available within a maximum of 4 hours? 
Also, can you confirm if the problem does not resurface after that? 
Is there any way to prevent this issue from happening in the first place?
Since the add-in checks the content of the email in a dialog, if the send event suddenly stops working, the email will be sent without being properly reviewed. This poses a risk of information leakage. If there is any way to prevent this from happening beforehand, please let me know.

**Comment by t-ariyoshi30907** [comment] 2023-08-01 00:16
@exextoc 
Could you please inform me about the current status of this matter? As it affects a significant number of customers, approximately 20 companies and 10,000 users, I would appreciate your cooperation in resolving it.

**Comment by exextoc** [comment] 2023-08-02 07:21
@t-ariyoshi30907 Thanks for sharing more info on this. We are investigating this issue. Can you provide more details on following to help us understand your scenario: 

1. Do you see this issue for only newly deployed/installed addins or also for addins which were working earlier for the same user?
2. Can you share details of the scenario where and how it is affecting 20 companies and 10,000 users?

**Comment by exextoc** [comment] 2023-08-08 11:35
Closing this issue as it is a duplicate of https://github.com/OfficeDev/office-js/issues/3231

**Closed as not planned by exextoc** 2023-08-08 11:35 UTC
Labels: Area: Outlook, Needs: author feedback, Resolution: duplicate
