### ISSUE TITLE
Error message when displaying administrator managed Office-Add-Ins in Word

### ISSUE THREAD

**Issue by PRIVERA-IT** [OfficeDev/office-js#1759] opened 2021-03-27 15:50 UTC
Instead of displaying company-wide deployed office-add-ins in the Add-Ins dialog in Word, an error message is displayed.
## Expected Behavior

When users go to the dialog Office-Add-Ins in Word and click to "Administrator managed", they could expect to see the list of company-wide deployed add-ins.
## Current Behavior

Some users are encountering the error message (in German): "Mit dem Katalog kann keine Verbindung hergestellt werden."
Not one of the several Add-Ins are displayed. 
## Steps to Reproduce, or Live Example

These users can reproduce the problem every time when they 
1. start Word
2. select the "Insert" menu ribbon
3. select "My Add-Ins" from Add-Ins
4. click on "Administrator managed"

## Context

We have deployed an add-in from an other manufacturer. The same behavior.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Laptop HP ELITEBOOK 830 G5
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft 365 Apps for Enterprise
* Operating System: Windows 10 
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [x] Screenshots
![Bildschirmfoto 2021-03-23 um 16 58 26](https://user-images.githubusercontent.com/81476401/112725652-9d3e6b00-8f19-11eb-8727-1046a02a4a86.png)

- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment] 2021-04-05 06:27
Translating the message from the screen shot: "Unable to connect to catalog"

@PRIVERA-IT 
Can you please help to share some more details:

1.  Is the issue reproducible in both Word Desktop and Word Online? 
2.  If the issue is reproducible in both, can we check that the user has a mailbox in EXO and meets the requirements specified in the developer documentation: [https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#requirements](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#requirements)
3. If the issue is specific to Word Desktop, can we check that user meets the Office requirements:  
[https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#office-requirements](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#office-requirements)

**Comment by PRIVERA-IT** [comment] 2021-04-12 18:33
Question 1: One of the two users who doesn't see the add-ins on the desktop sees the add-ins in Word Online, the other not
Question 2: The user has a EXO mailbox. Can't run the CompatibilityCheck because my Global Admin runs only with MFA.
Question 3: Attached the office version
![image001](https://user-images.githubusercontent.com/81476401/114442071-6da38a00-9bcc-11eb-9945-c708229b547e.png)

**Comment by romanmensch** [comment] 2022-04-08 10:59
We have the same in our Office. One Person with this exactly same Error on the Screenshot . After all, it's been a long time. Are there any updates on this case
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/92531519/162425319-f4ba3af9-ac56-4138-892e-a49e6a6fa2fb.png)
?

**Comment by gordianberger** [comment] 2022-06-01 08:18
We have the same issue. The add-in is only missing in the desktop version but the user do meet the office requirements. Any updates on this?

**Comment by aba-hilpertshauserm** [comment] 2023-02-22 12:40
any updates here? we have the same issue.

**Comment by AkhileshShah-MS** [comment] 2023-02-24 09:39
Hi @aba-hilpertshauserm, Thanks for reaching out. Please share following data  over email to addin-help@outlook.com, to help debug this for you. 
- Tenant ID
- Email ID of the users facing this
- Fiddler trace of this issue

**Comment by exextoc** [comment] 2023-07-14 05:03
No action for quite some time. Closing the issue.

**Closed as completed by exextoc** 2023-07-14 05:03 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: Centralized Deployment
