### ISSUE TITLE
Create Content Control Not Working With Office 365(WOPI)

### ISSUE THREAD

**Issue by salmanansari-gep** [OfficeDev/office-js#803] opened 2019-10-25 14:58 UTC
## Expected Behavior
User should able to create content control using office.js API

## Current Behavior
I have added a button for adding content control in word document
Its is failing with below error message:
"GeneralException: Sorry, something went wrong. Check the OfficeExtension.Error.debugInfo for more information."

This is working fine in offline copy of MS Office 2016

## Code Snipets
// Run a batch operation against the Word object model.
Word.run(function (context) {
    
    // Create a proxy range object for the current selection.
    var range = context.document.getSelection();
    
    // Queue a commmand to create the content control.
    var myContentControl = range.insertContentControl();
    myContentControl.tag = 'Customer-Address';
    myContentControl.title = 'Enter Customer Address Here:';
    myContentControl.style = 'Heading 2';
    myContentControl.insertText('One Microsoft Way, Redmond, WA 98052', 'replace');
    myContentControl.cannotEdit = true;
    myContentControl.appearance = 'tags';
    
    // Queue a command to load the id property for the content control you created.
    context.load(myContentControl, 'id');
    
    // Synchronize the document state by executing the queued-up commands, 
    // and return a promise to indicate task completion.
    return context.sync().then(function () {
        console.log('Created content control with id: ' + myContentControl.id);
    });  
})
.catch(function (error) {
    console.log('Error: ' + JSON.stringify(error));
    if (error instanceof OfficeExtension.Error) {
        console.log('Debug info: ' + JSON.stringify(error.debugInfo));
    }
});

Link: https://github.com/OfficeDev/office-js-snippet-explorer/blob/master/word-snippets/contentControlCreate.js

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.12224.32656
* Operating System: Windows
* Browser (if using Office Online): Chrome

## Useful logs
Details Error Message:
Debug info: {"code":"GeneralException","message":"Sorry, something went wrong. Check the OfficeExtension.Error.debugInfo for more information. ","errorLocation":"Range.insertContentControl","statement":"var insertContentControl=selection.insertContentControl();","surroundingStatements":["var root=context.root;","var selection=root.getSelection();","// Instantiate {selection}","// >>>>>","var insertContentControl=selection.insertContentControl();","// <<<<<","// Instantiate {insertContentControl}","insertContentControl.tag=...;","insertContentControl.title=...;","insertContentControl.style=...;","var insertText=insertContentControl.insertText(...);","..."],"fullStatements":["Please enable config.extendedErrorLogging to see full statements."]}

**Comment by weshi** [comment] 2019-10-28 04:54
Could  you share a sample document with which you encountered this issue? I tried in Dropbox.com, and cannot reproduce this issue. We need more information to investigate. Thanks.

**Comment by salmanansari-gep** [comment] 2019-10-28 08:06
Kindly find the attached sample document

[493d7723-03f4-4325-b46c-b57e4655d5e7.docx](https://github.com/OfficeDev/office-js/files/3777636/493d7723-03f4-4325-b46c-b57e4655d5e7.docx)

We have implemented WOPI (https://wopi.readthedocs.io/en/latest/)
There is two environment in WOPI (Staging & Production)

You might have tested on dropbox production environment and there is a MS office version difference.(dropbox ver. 16.0.12222.32650) 

Our production environment is not yet enabled and staging environment is used for development purpose only.

**Comment by weshi** [comment] 2019-11-01 03:03
The root cause of the error is because this file has tracked changes turned on, which is a new feature that has not been enabled in Word Online yet. The content control is not supported when tracked change is on. This is a known issue for now as the tracked change is still in development stage in Word Online. Could you open this document in Word for Desktop and accept/reject all the changes, then turn the tracked change off, and reopen it in Word Online to see if the issue is gone?

**Comment by salmanansari-gep** [comment] 2019-11-01 06:54
Have tried adding content control to the documents having track changes turned off, its working as expected.
The problem is with the document having track changes turned on.
Thanks @weshi for the support and help.

**Comment by weshi** [comment] 2019-11-04 02:29
Thanks @salmanansari-gep. I'm closing this issue then.

**Closed as completed by weshi** 2019-11-04 02:29 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: Word, Area: add-ins platform

**Comment by alexandremalavasi** [comment] 2020-09-09 11:28
Is there any plan in the roadmap for Word Online to include the Tracking Changes option for Content Controls in the Office online? 

I saw this thread and the last answer was from last year with the status that was in development. Thank you.
