### ISSUE TITLE
PowerPointOnline: Content AddIn closes Presentation when showing Dialog

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/office-js#173] opened 2018-06-22 05:46 UTC
We have implemented a Powerpoint Content Addin and build an authentication flow as described here:
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md#use-the-dialog-apis-in-an-authentication-flow

In desktop presentation mode this works pretty well - in the online versions presentation mode opens fullscreen and it seems opening the dialog will close the presentation mode.
**_Is this a bug or will it not be possible to use this API in the online versions in presentation mode?_**

The authentication redirection have to be done each time because the result (cookie) is not reachable for our app and you do not offer a session context for all content add ins.
**_How could we solve this problem? We failed the store validation because of this!_**

**Comment by dorisgega** [comment] 2018-06-22 09:45
Hi, how did you try your addin in Powerpoint online ? Did you use the "Upload my add-in" feature to upload your add-in manifest from local to Powerpoint online ?  I uploaded a content add-in manifest from my local to PPT online, and then tried to open the presentation mode, but the presentation mode will not be opened successfully, it just flashed out and return to the edit mode. So I want to confirm with you about the detail. What do you mean "it seems opening the dialog will close the presentation mode " ? Do you mean you open the presentation mode successfully and then click a button in the add-in to open a dialog, then the presentation mode is closed ? Thank you !

**Comment by ndeeH** [comment] 2018-06-22 10:23
We use the O365 Admin Center to use the PPT AddIn in the online versions.
Our content add in will be refreshed by PPT online when switched to presentation mode.
The refresh will result in opening a dialog to validate the authentication (in PPT Desktop this will just be open and is immediatly closed. It is the only possibility to proper authenticate).

**Comment by dorisgega** [comment] 2018-06-22 10:46
I think you are using the window dialog in your add-in since it is for authentication scenario, right ? After your add-in refresh, is there a new window notification (like your add-in wants to display a new window. Allow Ignore) shown up ? You mean after you click the Allow button, the authentication window opened, but the presentation mode was closed ?

**Comment by ndeeH** [comment] 2018-06-22 11:07
Allow/Ignore is only displayed when not in presentation mode.
In presentation mode a fullscreen window is opened and immediatly closed.
So no chance to allow :(

**Comment by dorisgega** [comment] 2018-06-25 08:17
I have tried to insert my DialogAPI add-in from "My Organization" tab, then I can trigger the DialogAPI to show the Allow/Ignore in presentation mode. So I think this issue may not related to DialogAPI. But it still is a issue for showing add-in in ppt presentation mode. Can you give me the browser Console Errors after the presentation mode is closed ? Or can help to confirm whether there is error "SCRIPT5007: SCRIPT5007: Unable to get property '$3A' of undefined or null reference" in your browser console after the presentation mode is closed ? Thank you !

**Comment by ndeeH** [comment] 2018-06-25 10:20
Here are the errors I get when opening presentation mode in **Chrome** - which will open a Dialog:
![image](https://user-images.githubusercontent.com/11518242/41844811-b302d316-7871-11e8-8604-c282021946bd.png)
and in **Firefox**:
![image](https://user-images.githubusercontent.com/11518242/41844969-2a74823c-7872-11e8-9301-ba52135bdd06.png)

**Comment by ndeeH** [comment] 2018-06-25 10:21
The presentation mode is immediatly closed.

**Comment by dorisgega** [comment] 2018-06-26 03:12
Thank you for this information. This is an issue showing add-in in presentation mode, it is not an issue with DialogAPI. We already have a VSO bug 2403193 to track this issue. And there is an engineer now working on the fix.

**Comment by JuaneloJuanelo** [comment] 2018-07-23 22:33
@weird-dreams  this was resolved, can you please give it a try? Will be much appreciated if you can please confirm the issue is fixed.

**Comment by ndeeH** [comment] 2018-07-24 07:34
@JuaneloJuanelo 
Hallo Juan, thank you for responding on my issues.
At the moment I can not give this a try because I am not able to run my add-in in PPt Online:
see #198  (linked our manifest there)

**Comment by ndeeH** [comment] 2018-09-18 08:22
Hi @JuaneloJuanelo ,
we could test this issue with our QA version PowerPoint Add In 
where we do not get the error described in #198 .

**We could confirm: Presentation mode is no more closed by opening a dialog.**
Tested in actual versions of Internet Explorer, Edge, Firefox and Chrome,
In Chrome full screen mode is leaved when a dialog opens - but this seems as designed by Google.

**Comment by tutieu** [comment] 2019-04-08 04:14
Closed as confirmed by @weird-dreams.

**Closed as completed by tutieu** 2019-04-08 04:14 UTC
Labels: Area: PowerPoint
