### ISSUE TITLE
WorkBook level Define name is getting corrupted while reopening excel using base64

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#4772] opened 2024-08-09 12:07 UTC
My Environment
Platform : PC desktop
Host: Excel
Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2407 Build 16.0.17830.20056) 64-bit 
Operating System: Windows 11 pro

Hi team,
I am Opening excel using base64 using this snippet.
```
var options = {
            sheetNamesToInsert: [], // Insert all the worksheets from the source workbook.
            positionType: Excel.WorksheetPositionType.end
        };
        // Insert the new worksheets into the current workbook.
        workbook.insertWorksheetsFromBase64(replaceexcelconfirmdialog.Base64Data, options);  //replaceexcelconfirmdialog.Base64Data in that I get my file bytes
        context.load(workbook.worksheets);
        await context.sync();
```
First time loading this sheet my workbook level name range is showing properly like this
<img width="696" alt="image" src="https://github.com/user-attachments/assets/0b61d70b-592a-4742-ae95-0e08d743e63f">

But after Reopening same excel is getting corrupted that's why it's also causing error in counting formulas because formula is base on define name.
After reopen same I'm getting this

<img width="695" alt="image" src="https://github.com/user-attachments/assets/76e3e035-4c7a-4f22-b3fd-5ec80f9cc824">

As you can see sheet 2 A1 cell is show "#REF" due to Corrupted define name.

While reopening  sheet First I'm removeing old worksheet for that I'm using this code:
```
//remove all sheet except first
for (var i = 0; i < workbook.worksheets.items.length; i++) {
    if (workbook.worksheets.items[i].visibility == Excel.SheetVisibility.hidden || workbook.worksheets.items[i].visibility == Excel.SheetVisibility.veryHidden) {
        workbook.worksheets.items[i].visibility = Excel.SheetVisibility.visible;
    }
    if (workbook.worksheets.items[i].name == "NA") {
        isNAExist = true;
    }
}
await context.sync();
if (!isNAExist) {
    workbook.worksheets.add("NA");
    context.load(workbook.worksheets);
    await context.sync();
}
for (var i = 0; i < workbook.worksheets.items.length - 1; i++) {

    workbook.worksheets.items[i].delete();
}
context.load(workbook.worksheets);
await context.sync();
```

After that I try to remove Define name s before reopening excel so it's clearing old define name but After loading new worksheet it's does not loading that excel define name so my Name Manger is showing empty but formula is retaining and I can also use that define name.
(If I open other sheet than previous sheet define name also showing in Name Manger.)

here is code snippest which I use to remove Define name
    
   ```
const names = context.workbook.names;
        names.load();
       context.load(workbook.worksheets);
       await context.sync();

       // Iterate over each named item and delete it
        for (let i = names.items.length - 1; i >= 0; i--) {
            workbook.names.items[i].delete();
         }

        //Synchronize the changes to Excel
        await context.sync();
```

Here is my Excel File for reference 
[Book1.xlsx](https://github.com/user-attachments/files/16560929/Book1.xlsx)

**Comment by shanshanzheng-dev** [comment] 2024-08-12 05:33
Hi @Jayshiv1408Dev Thanks for reaching us. We're trying to repro your problems from your description. 
For your first problem, when I insert a new sheet2 using base64, and inset two formulas and reopening it again, I can't find "#REF" error. This is my Excel version, you can update a new version to see if still happens this error.
![image](https://github.com/user-attachments/assets/309ab505-5993-4bbf-a48f-8201fc3bb52f)
For your second problem, could you describe the problem scenario again? Because I run your code to remove all old sheets and reopen it again, there is only a "NA" empty sheet, no formula and Name Manager is empty.

**Comment by Jayshiv-IRIS** [comment] 2024-08-12 08:32
@shanshanzheng-dev  
My excel version is showing up to date.
<img width="792" alt="image" src="https://github.com/user-attachments/assets/172579a9-e920-46cb-8f1c-23f0ddf2a769">

Here I'm sharing screen recording for further help.
As you can See first time I'm loading excel at time my range is showing properly after re-opening same excel in same instance(For that I'm removing my old sheet) my range is getting corrupted. As you can see when I close and open Excel App then again opening my workbook then it's showing properly.

here is my Video
https://github.com/user-attachments/assets/0ff88f24-d705-4809-bf02-0cd63529c45f

here is my code for video 1
[video1code.txt](https://github.com/user-attachments/files/16578740/video1code.txt)


As per my observation define name is still there in name manger after removing worksheet so after reopening it's getting corrupted.
For that I'm removing define name before deleting worksheets but after reopening workbook existing define name is not showing in name manger here is my video with code of removing define name.

Here is my video 2

https://github.com/user-attachments/assets/174c5c51-6d8f-4d7c-8094-97b512f4ff68

here is my video code
[video2code.txt](https://github.com/user-attachments/files/16579225/video2code.txt)

In both there is only few line changes in  removeLoadedWorkBook() function.

```
 for (let i = names.items.length - 1; i >= 0; i--) {
    workbook.names.items[i].delete();
  }
  //Synchronize the changes to Excel
  await context.sync();
```

This code is use to remove define name.

AS you can see in video after using this code define name is not visible but I can access it and my value is not corrupted.

About NA worksheet: Before reopening excel I am deleting all worksheet and I'm inserting NA worksheet  because at least one worksheet  require in Excel. After all worksheet load successfully I'm removing that NA worksheet.

I uploaded book1.xlsx in previous trail  which is not protected.
Is there anything I can share please let me know.
Thanks,

**Comment by shanshanzheng-dev** [comment] 2024-08-13 07:09
Hi @Jayshiv1408Dev Thanks for providing the detail information. We'll take a look and repot back if we have a suggestion for you. Thanks for you patience.

**Comment by Jayshiv1408Dev** [comment] 2024-08-13 07:29
[like]  ​Jayshiv Patel reacted to your message:
________________________________

**Comment by Jayshiv1408Dev** [comment] 2024-08-13 07:43
[0]     ​Jayshiv Patel reacted to your message:
________________________________

**Comment by shermaro91** [comment] 2024-08-20 06:32
Hi @shanshanzheng-dev,
We're encountering a same critical issue with our Excel add-in that is impacting our business operations. Here’s a brief overview of our scenario:
Scenario:
We have a desktop Excel add-in.
After logging in, users are presented with a list of Excel files.
When a user clicks on any Excel file, it is loaded into the Excel instance.
If the user clicks on another Excel file, we first remove the named ranges from the previous file before loading the new one.
Issues Faced:
If we don't remove the named ranges from the previous Excel file, all named ranges become corrupt.
If we do remove the named ranges, while Office.js doesn't encounter any errors, the Named Manager in the Excel instance becomes blank.
Could you please investigate this issue? Additionally, if there's an alternative approach to handling this scenario, we'd appreciate your suggestions.
Thank you for your prompt attention to this matter.

**Comment by shanshanzheng-dev** [comment] 2024-08-20 07:40
Hi @shermaro91 Thanks for reporting this issue. If possible, Could you provide us repro video or test document? We'll try to repro this problem and investigate root cause.

**Comment by SiruiSun-MSFT** [comment] 2024-08-20 07:59
Hi @shermaro91, Thanks for your reporting here! After our further investigation, we have some update here about the issue you reported several days before:
1. For the corrupted result, this is a by-design behavior. Since the NamedItem's scope is Workbook, deleting the bound sheet will not trigger the whole NamedItem to be deleted together. It will result to the corrupted behavior, and cannot be fixed by insert again(due to the unique name check, the second time insertion will not success.) The behavior is same as UI-side. To make the NamedItem work well, you can just edit the NamedItem or delete and insert again.
2. For the second scenario about the hidden NamedItem. The NamedItems are indeed deleted and insert successfully. However, their visibility is automatically set to false. To show them again, there is a workaround: 
_workbook.names.items[i].visible = true;_
After that, you will see them in the Name Manager, and also, everything will work well!
----
As the comments above, "named ranges become corrupt." is due to the NamedItem is a cross worksheet one, which cannot be deleted by deleting the bound worksheet. If you still use the same workbook, it will always exists.
And "the Named Manager in the Excel instance becomes blank." is due to all NamedItem has been hidden, you could show it again by set its visibility to true.

Hope the above information could help you out! Thanks again!

**Closed as completed** 2024-08-27 10:55 UTC
Labels: Needs: attention :wave:, Area: Excel, Needs: triage :mag:

**Comment by Jayshiv-IRIS** [comment] 2024-09-23 05:05
Hi, As per above discussion I'm removing Excel Named Range using this code snippets 
```
 // Iterate over each named item and delete it
 for (let i = names.items.length - 1; i >= 0; i--) {
     workbook.names.items[i].delete();
 }

 //Synchronize the changes to Excel
 await context.sync();
```
There is 4000-5000 named range is there and it's taking 3-5 minutes to removing is there any way I can make it faster. Or is There any way I can remove all at time instead of removing individual in loop. Here loop doesn't taking that time but context.sync() taking that much time .If I put context.sync() in Loop then it's taking 10 mintues to removing all names. 
Because it's annoying for user to wait each time while reloading excels.

I'm attaching file for reference.
[NamedItemFile.xlsx](https://github.com/user-attachments/files/17092988/NamedItemFile.xlsx)

**Comment by Jayshiv-IRIS** [comment] 2024-09-24 09:54
Hi Team , Is there Any update?

**Comment by SiruiSun-MSFT** [comment] 2024-09-24 10:11
I'm afraid there is no better way to do that. Maybe you could raise a request on the Tech Community. Thanks for your patience!
