### ISSUE TITLE
Power Point Presentation mode - not showing the add-in

### ISSUE THREAD

**Issue by robertkiri** [OfficeDev/office-js#3466] opened 2023-06-27 17:35 UTC
When switching to PowerPoint presentation mode, the add-in content pane is not showing the content. (completly blank)

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Windows 
* Windows Version:   Edition: Windows 10 Pro. Version: 22H2
Installed on: ‎5/‎24/‎2022. OS build: 19045.3086
Experience: Windows Feature Experience Pack 1000.19041.1000.0

- Host Power Point (Office Version 2305, Build 16501.20228)
- Web View2 Runtime 114.0.1823.51 (latest)
 
## Expected behavior
As in normal view, the add-in content pane should be seen in presentation mode...

## Current behavior
Our add-in is not shown and we did a cross check: we used the add-in Web Viewer,
and the behaviour was the same.

# To reproduce
- Open PowerPoint.
- In the "Insert" menu, on the "Add-ins" section select "Get Add-ins".
- Search for "Web Viewer".
- Add "Web Viewer".
- On the "Insert Web Page" view, enter the URL: https://www.wikipedia.org/, then click "Preview". The Wikipedia home page should appear.
- Enter presentation mode in PowerPoint.

**Comment by MidnightEdge** [comment] 2023-08-23 16:12
We are also experiencing the same issue, any updates on this? @ononder @wangyun-microsoft

**Comment by sebiJo** [comment] 2023-12-04 17:20
Our users also report the same issue, however we cannot reproduce it on our side. 

We observed at our users that the issue occurs when they have a specific kind of external screen. During troubleshooting, when we went to "Set up slide show" and selected the built-in laptop screen, the add-in showed up correctly in slideshow mode. It seems as if the external screen (or graphics adapter) caused some kind of incompatibility with the add-in in slide show mode. We tried to reproduce with the same resolution, color bit depth and refresh rate, but were still not able to reproduce.

The issue was observed on Windows 11 Pro with PowerPoint 2311, Build 17029.20068    and can be reproduced constantly on that machine. The add-in works correctly in editing mode but shows blank/white in presentation mode.
 
Any updates since June 2023? @ononder @JinghuiMS @wangyun-microsoft 

@robertkiri, @MidnightEdge: Did you find the root cause for this issue or any suitable workaround for the users? I assume if they switch to particular display settings, it could work.

**Comment by hoodm194** [comment] 2023-12-28 22:15
Probably a problem many people have. I usually use https://slidepeak.com/ to avoid problems with PowerPoint presentations, which has helped me many times. Thanks to the experts, the presentations have no errors whatsoever.

**Comment by sebiJo** [comment] 2023-12-29 14:51
Yes, unfortunately this PowerPoint bug leads to a lot of user complaints even though we never achieved to reproduce it on any development machine.

**Comment by mwestphal** [comment] 2024-02-20 12:59
please note user @hoodm194 is a spammer.

**Comment by EsterBergen** [comment] 2024-04-11 17:39
Hi @robertkiri  and @sebiJo - I'm unable to reproduce the issue. Can you try on the most recent build? If you're still experiencing this, try reporting a problem under the help menu in the ribbon. Thanks!

**Comment by sebiJo** [comment] 2024-04-12 07:32
@EsterBergen: The issue still occurs at our customers with the most recent build. Can you please try again with the following setup: Please run the presentation on a second screen (e.g. a screen in a meeting room) connected through HDMI. This is a very common case in meetings and presentations and it seems that add-ins are not shown during slide show mode on an external screen connected through HDMI. I am not sure if it depends on HDMI or if it is rather a specific graphics setting that causes the problems.
When switching the presentation to the internal laptop screen, it works, but it does not solve the problem for a presentation use case.

**Comment by EsterBergen** [comment] 2024-04-12 19:12
@sebiJo - I just tried running in a conference room connected to HDMI. I'll try to work on a bigger screen too.  It may be a graphics setting. If you can report a problem, that would be helpful for us to have the logs. Go to Help>report a problem.

Can you also confirm you're running the presentation in presentation mode from PowerPoint and not running it in Power Point Live from a Teams meeting?

**Comment by sebiJo** [comment] 2024-04-15 07:00
Yes, I can confirm this occurs in normal presentation mode, not PowerPoint Live.

Our issue is: We cannot reproduce the bug ourselves but many of our customers have the problem. I have seen the problem many times through screensharing.

Here is a way how you can simulate the issue. This might lead to the actual root cause:
1) Insert Web Viewer add-in (or any other Content add-in)
2) Go to the Slide Show ribbon in PowerPoint and click Set Up Slide Show. Check "Disable hardware graphics acceleration".
3) Add-ins will not be displayed anymore in slide show mode. 

Important: Customers have this problem even with "hardware graphics acceleration" activated when using certain external displays or projectors during the presentation. Is there a case where graphics acceleration is internally deactivated but appears activated for the users?
If Microsoft could solve the problem that add-ins are not shown when hardware graphics acceleration is deactivated, then there might be a good chance that the problem is solved as a whole.

**Comment by sebiJo** [comment] 2024-04-19 09:28
@EsterBergen, please remove the "needs author feedback" tag so that the ticket won't be closed automatically

**Comment by sebiJo** [comment] 2024-04-26 07:59
My customer has reported the issue through PowerPoint a few days ago.
Has has included the link to this GitHub issue.

**Comment by SPDoctor** [comment] 2024-04-30 08:24
I have been asked to continue the conversation about https://github.com/OfficeDev/office-js/issues/4410 here, as it may be a the same bug. Please refer to that closed issue for more information. 

We are getting one or two customer complaints per month about this issue, and there's nothing much we can do to help them. That is probably affecting a much larger number of users who probably just give up and do something else.

Thanks.

**Comment by sebiJo** [comment] 2024-06-03 14:20
@EsterBergen, any news on this topic? Did the report from the customer help?

**Comment by DaveShep** [comment] 2024-06-19 17:42
To replicate this bug you need a laptop with a dedicated graphics adaptor in extended display mode. If the adaptor selected for the PowerPoint app does not match the adaptor serving the main show output then a white screen is the result. WebView2 appears to be responsible.

**Comment by EsterBergen** [comment] 2024-06-19 18:12
@sebiJo - I don't see the customer feedback in our systems do you know if it was filed? Can you please report a problem again. In the text can you be specific that the display is not showing a content add-in so it will be routed appropriately?

**Comment by sebiJo** [comment] 2024-06-20 07:53
@EsterBergen: The issue has been reported by our customer between April 22nd and April 25th 2024 using the following text description: 
`I am experiencing this issue: https://github.com/OfficeDev/office-js/issues/3466`

Unfortunately, we cannot report the problem again ourselves because we have not yet reproduced it. Maybe the description of @DaveShep helps to reproduce it?

**Comment by sebiJo** [comment] 2024-06-20 08:08
@DaveShep, so you need two graphics adapters to replicate the issue? Could you post a screenshot where you have set the dedicated graphics adapter?
It's not easy to replicate then, right? Since so many users are experiencing this issue, I thought it might have been easier?

**Comment by DaveShep** [comment] 2024-06-20 15:30
I can't comment on other ways to replicate the issue. I will add detail to the way it affects us:

Laptops: Dell G15 5520, Dell G16 7630
Graphics adaptors: Intel Iris Xe & NVIDIA RTX3060, Intel Iris Xe & NVIDIA RTX4060

In the bios, Hybrid graphics is enabled. This is also known as NVIDIA Optimus. Windows sees the integrated graphics adaptor (Intel) as the default GPU and where required, an app can be set to use the dedicated graphics adaptor (NVIDIA) instead in either the NVIDIA Control Panel (3D Settings | Manage 3D settings | Program Settings) or in Windows Settings (System | Display | Graphics | Custom options for apps).

This laptop has a HDMI output provided by the dedicated GPU and a DisplayPort over USB-C output provided by the integrated GPU. By viewing the Display Information in Settings | System | Display | Advanced Display and selecting each display you can see which display is controlled by which GPU.

If no profile has been added for PowerPoint, it will launch under the integrated GPU. If a presentation is set to show on the USB-C output in extended display mode, a Web Viewer slide will correctly render as it does in edit mode. If the presentation is set to show on the HDMI output, a full white slide is displayed instead.

Conversely, if PowerPoint is set to launch under the dedicated GPU, the Web Viewer will correctly show on the HDMI output but when switching to the USB-C output it will fail.

Additionally if Hybrid graphics is turned off in the bios and Windows sees the NVIDIA GPU as default, Web Viewer will only show correctly on the HDMI output.

This leads me to believe that you should be able to replicate the issue by ensuring the GPU providing the show output is not the GPU that PowerPoint is running under.

**Comment by croicu** [comment] 2024-07-09 17:25
@DaveShep what is your Office version?

**Comment by DaveShep** [comment] 2024-07-10 10:00
> @DaveShep what is your Office version?

Version 2406 (Build 17726.20126)

**Comment by croicu** [comment] 2024-07-10 19:44
@DaveShep there was a fix for hardware acceleration in presentation mode for 2406, however it looks like it does not cover your configuration. Could you collect an TTD trace for your scenario? (it is a large file, several GB):

a.	https://learn.microsoft.com/en-us/windows-hardware/drivers/debuggercmds/time-travel-debugging-record 
b.	Install WinDbgX: https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/
c.	Start WinDbgX
d.	Start Office client and prepare the repro
e.	Switch back to WinDbgX
f.	Got to File | Start debugging | Attach to process
g.	Check "Show processes from all users"
h.	Select "Record with Time Travel Debugging"
i.	Select the Office process
j.	Click Configure and Record
k.	Select the save location (the drive should have plenty of space)
l.	Click Record
m.	Run the scenario
n.	Click Stop and Debug

**Comment by myfope** [comment] 2024-07-17 10:07
@croicu as I face the same issue - where should I upload the file or can I provide you a link to OneDrive where the file is stored?

**Comment by croicu** [comment] 2024-07-22 16:57
@myfope, please provide me a link.

Thanks,
Alex

**Comment by croicu** [comment] 2024-08-07 00:11
@myfope did you got a chance to upload the trace?

**Comment by myfope** [comment] 2024-08-07 13:19
@croicu uhm, I thought I've answered it here that I've sent a link to your MSFT address. It seems that did not work. [https://fope-my.sharepoint.com/:f:/g/personal/peter_fope_at/EoUTzyiNiMBBvdlkw5xkOwABwDoIkeOdAmfcBW8IOtF4LQ?e=dA5fX9](url)
Does this work for you?

**Comment by croicu** [comment] 2024-08-07 17:21
Thank you @myfope. Sorry for the email. I cannot find it in my mailbox.
I have downloaded the trace; you can remove it now from SharePoint.
Just to make sure, what is included in the trace:

- start the TTT trace
- go back to powerpoint
- start the presentation
- go to the slide with the ad-in
- the add-in does not show
- stop the presentation
- stop the TTT trace.

Is this correct?

**Comment by croicu** [comment] 2024-08-12 22:14
@myfope can you try to disable the hardware acceleration for the slide show and see if it still reproes:

![image](https://github.com/user-attachments/assets/d4d46197-2b68-41ef-915b-683e8f8d7878)

**Comment by DaveShep** [comment] 2024-08-19 12:49
On my setup, cannot reproduce if hardware acceleration is disabled

**Comment by DaveShep** [comment] 2024-08-19 13:25
Trace available here https://www.dropbox.com/scl/fi/8zuhsg2d6x5dvlzvslsji/POWERPNT01.zip?rlkey=1svep5xii0f084pc85201taql&dl=1 (hardware acceleration enabled, issue reproduced)

**Comment by croicu** [comment] 2024-08-19 22:37
@DaveShep thank you for the trace, I did look at it. This is the same display adapter issue. In order to provide a fix, I have to narrow down what are the conditions when this happens. Could you run dxdiag and upload the adapter information?

For now, unfortunately the only workaround I can see is to disable hardware acceleration during presentation.

**Comment by DaveShep** [comment] 2024-08-20 10:21
[DxDiag.txt](https://github.com/user-attachments/files/16674217/DxDiag.txt)

**Comment by croicu** [comment] 2024-08-20 16:27
@DaveShep can you try the xe drivers from intel https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
in order to see if the issue was fixed with the latest version (32.0.101.5971)?

**Comment by DaveShep** [comment] 2024-08-20 19:47
Intel Xe 32.0.101.5971
Can still reproduce issue

[DxDiag2.txt](https://github.com/user-attachments/files/16681065/DxDiag2.txt)

Trace https://www.dropbox.com/scl/fi/zsb4yofx4c3znx30g8b4t/POWERPNT02.zip?rlkey=7m4nkp9lpkufzsg467wt00u0x&dl=1

**Comment by EsterBergen** [comment] 2024-08-27 20:47
Hi @DaveShep , @myfope, and @sebiJo - We have a fix in place and it is available in build 16.0.18025.20000. Can you please test and let us know if the issue is resolved? thanks!

**Comment by myfope** [comment] 2024-09-02 13:05
@EsterBergen & @croicu FYI: For me the option "Disable hardware graphics acceleration" solves my problem.

**Comment by DaveShep** [comment] 2024-09-09 11:12
> Hi @DaveShep , @myfope, and @sebiJo - We have a fix in place and it is available in build 16.0.18025.20000. Can you please test and let us know if the issue is resolved? thanks!

I was seeing this issue in the WebViewer addin - I imagine this would also need to be updated?

**Comment by sebiJo** [comment] 2024-09-09 11:34
If the issue is fixed in PPT, there should be no update be required in WebViewer or any other add-in. The issue affected all content add-ins.

**Comment by DaveShep** [comment] 2024-09-09 12:39
@sebiJo where would i obtain this build?

**Comment by DaveShep** [comment] 2024-09-09 13:59
@EsterBergen unable to reproduce with build 16.18028.20004

Thanks for your help

**Comment by EsterBergen** [comment] 2024-09-09 15:31
@DaveShep - Fantastic! I'll close this now.

**Closed as completed by EsterBergen** 2024-09-09 15:31 UTC
Labels: Status: under investigation, Area: PowerPoint
