### ISSUE TITLE
Custom function : TypeError: Network request failed on Desktop, working online

### ISSUE THREAD

**Issue by marcboivin** [OfficeDev/office-js#558] opened 2019-06-14 04:11 UTC
## Expected Behavior

I would expect the Fetch request to work as it does on the online version
## Current Behavior

I get a #VALUE error, no API request go to the server, loggin the return object of the feta request yeilds : 

```
2019-06-13 23:37:29	Verbose	Runtime	[Console] [Log] Verbose CustomFunctions [Execution] [Begin] Function=GL		
2019-06-13 23:37:29	Verbose	Runtime	[Console] [Log] Error		
2019-06-13 23:37:29	Verbose	Runtime	[Console] [Log] [TypeError: Network request failed]		
2019-06-13 23:37:29	Unexpected	CustomFunctions	[Execution] [Async] [End] [Failure] 		
2019-06-13 23:37:29	Unexpected	CustomFunctions	[Execution] [Async] [End] [Failure] Function=GL, Workbook=F9 - État des ventes AME 2019-05.xlsx	

```

Functions that don't do network request work as expected. 

## Steps to Reproduce, or Live Example

Can't provide a live example, but the snippets that fetches the code is pretty run of the mill : 

```
var url = `https://distinctof9.local/odoof9/_QUERIES/account_lines/balance?where=${account_number}&year=${year}&month=${month}&centre=${division}&company=${target_cie}`;


      fetch(url)
          .then(function(response) {
            if(response.ok){
                return response.text();
                console.log(response);
            }else{
              console.log(response);
            }
          })
          .then(function(text) {
              console.log(text);
              let value = parseFloat(text.split(':')[1]);
              if(!value){
                value = 0;
              }
              invocation.setResult(value);
          })
          .catch(function(error) {
              console.log('Error');
              console.log(error);
              invocation.setResult(error);
          });

  invocation.onCanceled = () => {
      clearInterval(timer);
  };
}

```

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

* The #VALUE error is consistent, tried it on many Win10 Excel. 
* It does work on Excel for Mac. 
* I use a local DNS resolver and the certificate is self-signed. It is trusted in the windows (macOS) keychain.
* I don't get CORS error and the js, css and html file get fetched correctly
 * CORS is done by allowing https://*.officeapps.live.com

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Desktop and Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Desktop 1905
* Operating System: Windows 10, macOS
* Browser (if using Office Online): Chrome

## Useful logs

- [X] Console errors (well Office log file) 
[log.txt](https://github.com/OfficeDev/office-js/files/3288985/log.txt)

- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by keyur32** [comment] 2019-06-14 15:36
Hi sorry you are hitting this. Custom functions are executed in a JavaScript runtime on windows seperate from the taskpane, which users the browser. Currently,  Mac and online, also run the function in the context of the web browser.
More info: 
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview 

This may be one of 2 reasons:
  - a) does your server require full cors? This is not yet supported on windows.
  - b) an additional point is if you are debugging locally, and want to call that on the same machine, you will need to define a localhost exemption. (Will reply back with the link)

**Comment by marcboivin** [comment] 2019-06-14 19:41
Thank you for the fast reply. 

> a) does your server require full cors? This is not yet supported on windows.

I do not require full cors. I only set the Access-Control-Allow-Origin header. I also respect the same origin policy, my admin is loaded from domain.local/ and the api endpoint is loaded from domain.local/api/

The Access-Control-Allow-Origin value is dynamically set to the http origin of the request to prevent CORS blocking the request. 

> b) an additional point is if you are debugging locally, and want to call that on the same machine, you will need to define a localhost exemption. (Will reply back with the link)

Add-in works on remote machine when online. Even local debugging loads the ressources from the remote server. 

The function file (.html, .json, .map.js and .js) are loaded correctly. But when I call the fetch, no web request are coming from the Excel client to the web server. What would prevent Excel from even initiating the connexion? Is fetch() supported?

**Comment by keyur32** [comment] 2019-06-17 17:29
Hi @marcboivin, apologies, for delay. Can you try setting this up: https://support.microsoft.com/en-my/help/4490419/local-loopback-exemption-does-not-work  or double checking your origin config (i.e. can you access localhost from lets say Excel Online or is just Excel for windows where you are hitting this)?

**Comment by marcboivin** [comment] 2019-06-17 19:42
Got news. Might be on to something. 

So : 
* Win 10, Excel 365 (1905) still not working
* Win server 2008 R2, Excel 365 (1905) works

Same version of the code, same server endpoint (remote server). 

Can I provide more debugging info to figure that one out?

**Comment by keyur32** [comment] 2019-06-18 01:02
Can you try to access your localhost server from Edge on the same machine? Does it work?  Also can you clarify if you localhost server is on the same machine and/or same domain?

**Comment by marcboivin** [comment] 2019-06-18 21:04
So, just to make it clear : 

* Code is hosted on 192..168.1.62, running only a web server to serve the files and the API endpoint. It as a valid domain name and a self signed certificate
* Client 192.168.1.45, Office online and Desktop running Windows server 2008 R2 and working
* Client 192.168.1.52 Windows 10 machine. Working on Edge, not in Excel build 1905

So as stated, my windows 10 machine with excel build 1905 WORKS with Edge. DOESN'T with Excel.

**Comment by keyur32** [comment] 2019-06-19 01:11
Thanks. I'll reach out to you seperately, we may need to see your machine to debug what is going on.

**Comment by kbrandl** [comment] 2019-08-29 19:19
@keyur32 was this issue resolved by you connecting directly with @marcboivin to troubleshoot? If yes, can you please comment here and close this issue? Thanks!

**Comment by keyur32** [comment] 2019-09-04 04:24
@marcboivin , we never heard back from you (please feel free to ping again, sorry if something got lost in junk) but a change that will enable this is coming soon to insiders.

**Comment by benj-spectory** [comment] 2020-02-20 15:20
i have the same problem with excel on the local win 10 PC
excel version is 2001 does not work and i receive "TypeError: Network request failed" when trying to use fetch.
on Office 365 on the web it works! with the same host, and the same manifest.xml file.

did anyone manage to solve this?

**Comment by jaceaser** [comment] 2020-02-22 19:54
I'm having the same issue and I haven't found a workaround. @keyur32 can you assist?

**Comment by jaceaser** [comment] 2020-02-25 17:06
After performing some debugging, the requests are not leaving the Excel container. It seems there's a CORS pre-flight check and it never hits the server. This is extremely frustrating and I do not have any workaround.

**Comment by rocknet** [comment] 2020-02-29 20:12
@keyur32 @kbrandl It looks like at least a few of us are having this issue.  I'm happy to help pickup troubleshooting since we've lost follow-ups from OP.  My STR are slightly different, but along the same lines...

- Excel version 16.0.12430.20198
- Server running on Microsoft.AspNetCore.Mvc 2, CORS enabled from everywhere, endpoint url is http://localhost:55319 - obviously in testing and troubleshooting mode
- Updated today yo generator-office - Excel Custom Functions add-in project
- Added this function to the template
```
async function get() {
  let data = {
      outputVar: '', 
      command: 'version'
    };

  try {
    let response = await fetch('http://localhost:55319/api/v1/matlab/fetchdata/', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    });

    if (!response.ok) {
      console.log(response);
    }
    let json = await response.json();
    console.log(json.ans);
    return [[json.ans]];
  }
  catch (error) {
    console.log('Exception');
    console.log(error.message);
    console.log(error.stack);
    console.log(error);
  }
}
```

Note: For me, this is only an issue with using POST / Content-Type application/json, which leads me to believe, as @jaceaser suggested, this has to do with pre-flighting a CORS request in the implementation of fetch in in the Windows Excel implementation.  If I use a GET, which is a "simple" request, it works fine.  This also works, as other have said, in the office.com web based Excel.  Is the fetch implementation in the Windows Excel implementation out of date, or is it somehow overriding settings and making it not support CORS?

Error in the runtime log:
```
2/29/2020 14:44:49	Verbose	Runtime	[Console] [Log] Verbose CustomFunctions [Execution] [Begin] Function=GET		
2/29/2020 14:44:51	Verbose	Runtime	[Console] [Log] Exception		
2/29/2020 14:44:51	Verbose	Runtime	[Console] [Log] Network request failed		
2/29/2020 14:44:51	Verbose	Runtime	[Console] [Log] TypeError: Network request failed
   at a.onerror (foundation.win32.bundle:1:122985)
   at dispatchEvent.value (foundation.win32.bundle:1:38976)
   at value (foundation.win32.bundle:1:111590)
   at value (foundation.win32.bundle:1:108265)
   at Anonymous function (foundation.win32.bundle:1:110685)
   at value (foundation.win32.bundle:1:65313)
   at value (foundation.win32.bundle:1:53803)
   at Anonymous function (foundation.win32.bundle:1:51313)
   at value (foundation.win32.bundle:1:53072)
   at value (foundation.win32.bundle:1:51282)		
2/29/2020 14:44:51	Verbose	Runtime	[Console] [Log] [TypeError: Network request failed]		
2/29/2020 14:44:51	Verbose	Runtime	[Console] [Log] Medium CustomFunctions [Execution] [End] [Success] Function=GET		
2/29/2020 14:44:51	Unexpected	CustomFunctions	[Execution] [Async] [End] [Failure] Function=GET, Workbook=Excel add-in 1e8b196f-1261-41dd-a084-471095bc1a42.xlsx		
```

For what it's worth, if it were possible to test these add-ins with an un-minified version of foundation.win32.bundle and better understand how the whole architecture is put together, that would help us help you fix these.  Just like every other development environment, there should be a debug set and a minified set for deployment.  Would be nice if sideloading didn't use minified versions.

**Comment by jaceaser** [comment] 2020-03-01 17:44
@rocknet I was able to find work around until the issue is resolved. I had to make the request and subsequent API endpoint a simple request that will not trigger CORS pre-flight. The only header I sent was application/x-www-form-urlencoded so my function was not a JSON function. Granted this is not a solution, but is a workaround.

**Comment by rocknet** [comment] 2020-03-02 12:58
@jaceaser Good point, I guess that's possible.  The API I'm dealing with is pre-existing and called from other systems but I could potentially add another.  Kind of a hack, but you're right, it'd get around it temporarily.  Thanks

**Comment by ypraveen** [comment] 2020-03-12 01:32
@keyur32 @RuoyingLiang  Any updates on this?
Ran into the exact same issue (addin worked in excel on web and mac, but didn't work on windows excel).
I had to convert my POST request with Content-Type of "application/json" to a simple request as a work around (POST with Content-Type of "text/plain").
I am happy to share my setup details for further triaging the issue.

**Comment by benj-spectory** [comment] 2020-03-12 07:12
I have found what is the problem.
as others said, Office.js supports Simple CORS. which mean you **CANNOT** add headers to your request (Authorization or cookies) so you have a few workaround
1. use a server  that will receive your token\credentials as query param\body and then send it to the actual server for authentication.
2. send the actual server the  token\credentials as query param\body and handle the authentication process.

**Comment by mike-code** [comment] 2020-04-04 12:52
@up it was mentioned here few times already and we are NOT using such headers. OP clearly posted an example of simple GET with no headers whatsoever

Indeed there's a problem which is not limited to Office but Edge in general and MS can't get their shit straight in this regard. Just look on how many upvotes this QA has
https://stackoverflow.com/questions/32384571/why-does-microsoft-edge-open-some-local-websites-but-not-others-where-the-doma

Myself I tried fiddler (or to be precise, Charles) as a workaround and it works for taskpane and functions, but not in XHR requests from functions. Charles doesn't even capture such request.

**Comment by keyur32** [comment] 2020-04-07 04:00
Hey there, sorry for the delay, I missed the notifications here.  Currently, the custom functions runtime doesn't support cors.

Instead we recommend using a shared runtime: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview.  This supports full cors, httpOnlyCookie based auth, can call the MS Graph, etc.  It also allows you to manage and share state between your functions and global variables.  The shared runtime also contains some ability to manage ui and respond to events: https://developer.microsoft.com/en-us/office/blogs/build-contextual-ui-experiences-with-office-add-ins/.

Hope that helps. Team would love feedback on that.

**Comment by keyur32** [comment] 2020-04-07 04:01
If you are using the custom functions runtime, it does require an exemption for localhost. See the guidence here: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-troubleshooting#common-issues

**Comment by keyur32** [comment] 2020-05-11 19:55
Hi folks, closing this as we do have FULL CORS support available as part of the Shared Runtime: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview

**Closed as completed by keyur32** 2020-05-11 19:55 UTC
Labels: Type: product bug, Status: under investigation, Area: custom functions

**Comment by lucasbastianik** [comment] 2020-06-02 20:01
@keyur32 I follow and adapted my add-in like [this link](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview) to use a Shared Runtime but now I'm getting error `#N/A`.

In my logs, I got this:
```
02/06/2020 16:25:29	Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CG.BP, Workbook=Book1		
02/06/2020 16:25:32	Unexpected	CustomFunctions	[Execution] [Async] [End] [Failure] Function=BP, Workbook=Book1		
```

In Mac and Excel Online was ok but after this changes, brokes too.

**Comment by wynntee** [comment] 2021-03-10 04:34
Whilst a Shared Runtime allows Full CORS, it also forces the add-in to run in IE11, which severely limits the JS methods that I want to use, eg. WebAssembly. When will the Shared Runtime move to Edge Webview?

**Comment by sboudouk** [comment] 2022-07-29 10:02
Any news on this ?

**Comment by adammpolak** [comment] 2022-11-13 16:02
> @rocknet I was able to find work around until the issue is resolved. I had to make the request and subsequent API endpoint a simple request that will not trigger CORS pre-flight. The only header I sent was application/x-www-form-urlencoded so my function was not a JSON function. Granted this is not a solution, but is a workaround.

Can you post an example?

**Comment by adammpolak** [comment] 2022-11-13 16:05
> Hi folks, closing this as we do have FULL CORS support available as part of the Shared Runtime: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview

Reopen this issue.

There is no example online of making a POST request with an auth header online for a custom function.

No one knows if it is an excel custom function issue or something else.

**Comment by rocknet** [comment] 2022-11-13 20:18
> 
> Can you post an example?

Sorry, I don't even do it like this anymore.  It's been quite a while since I was using the JS only runtime.  I use the shared runtime and it has full CORS support, so my application/json type requests are working.  I'm not doing auth at this time though.

**Comment by adammpolak** [comment] 2022-11-13 22:54
> 

Appreciate the response!

I am also using a shared runtime but I am not able to get any auth POST requests working

**Comment by Zegoverno** [comment] 2023-03-31 12:22
me too, not able to use POST with authorization headers, anyone find a solution?

**Comment by adammpolak** [comment] 2023-04-05 17:48
@Zegoverno https://github.com/OfficeDev/Excel-Custom-Functions/issues/351#issuecomment-1396204778

**Comment by naa21m** [comment] 2023-05-09 20:41
I solved above issue by creating POST API of javascript in c# .net 6 with GET method endpoint. Luckily endpoint worked very well and then I call that GET endpoint using Javascript fetch method and it worked as expected.

Let me know if anyone wants whole demo.

**Comment by kinkoazc** [comment] 2023-10-06 10:46
@keyur32 @exextoc I'm currently getting the following error on HTTPS requests triggered by the `OnNewMessageCompose` event, in Outlook for Desktop v 2311, Win10:
```
TypeError: Cannot read properties of null (reading 'sendRequest')
Object.p [as error]
foundation.win32.bundle:17:1838
Object.<anonymous>
[...]
```
I've tried with both GET and POST methods, application/json and application/x-www-form-urlencoded, same result. It works in OWA. POST used to work in Outlook for Desktop as well, until recently. What could cause this?

**Comment by kbrandl** [comment] 2023-10-06 14:31
@kinkoazc -- sorry, but I'm no longer working with the Microsoft Office team, so I'm unable to provide any feedback on this.
