### ISSUE TITLE
onSingleClicked event is fired only when mouse doesn't move while clicking

### ISSUE THREAD

**Issue by hamouzj** [OfficeDev/office-js#1735] opened 2021-03-19 09:58 UTC
If mouse moves just a little within one cell, it is not taken as a click but just as a selection.

## Expected Behavior
There should be a little shift of mouse position allowed while clicking.

## Current Behavior
Currently if the click down and up positions are not exactly the same, the click event is not fired. 

## Context
We need to receive click events when user clicks quickly on cells. The faster he clicks from one cell to another, the more probable it is that mouse slightly moves while clicking and thus the click event is not fired. However, it also happens when clicking slowly, only less often.

## Environment
Windows, Desktop Excel (Microsoft 365), Version 2102 (build 13801.20294)

**Comment by ElizabethSamuel-MSFT** [comment] 2021-03-22 23:05
@hamouzj Thanks for raising this issue.

@lumine2008 Can you take a look or assign to an appropriate person to investigate?

Thanks.

**Comment by lumine2008** [comment] 2021-03-23 05:44
when clicking with mouse moving will be triggered as drag and drop.  therefore, it looks like a by design to me. maybe you could try a different mouse and see if it still repro?

**Comment by 4tti** [comment] 2021-03-23 07:19
@lumine2008 well then this event firing is unreliable and destroys UX cause whoever wants to use singleClick event must be focused only on the correct way of clicking.

**Comment by 4tti** [comment] 2021-03-23 08:04
@lumine2008  btw there is this issue https://github.com/OfficeDev/office-js/issues/1540

**Comment by hamouzj** [comment] 2021-03-23 08:25
@lumine2008 Please open _Single click event_ sample in Script Lab, try clicking quickly on cells and check that not all clicks are logged in the console. It's not a broken mouse issue as my colleagues can reproduce it too .

**Comment by lumine2008** [comment] 2021-03-23 09:11
Thanks, @4tti and @hamouzj, I just try it on my side, it seems no repro to me. 
I think a video would be helpful for us to do further investigation, could you please share a short repro video? thanks a lot

**Comment by 4tti** [comment] 2021-03-24 15:42
@lumine2008 attached is the video 

https://user-images.githubusercontent.com/19533927/112339452-f6ab5d80-8cbf-11eb-8390-579cf915ff11.mp4

**Comment by hamouzj** [comment] 2021-03-25 04:30
@lumine2008 Here is the video showing slow and fast clicking (together with the _selection_ event):

https://user-images.githubusercontent.com/56103045/112419072-00b67600-8d2b-11eb-9802-3010fab87154.mp4

https://gist.github.com/hamouzj/b3e000ab371fa47ad63d2758d6ae1b48

**Comment by lumine2008** [comment] 2021-03-26 07:52
Thanks, I have created a feature backlog 4984572 to track this issue.

**Comment by adrianwu8516** [comment] 2024-07-22 09:27
Hi @hamouzj, 

Thank you for bringing this up. We currently do not support such operations at the API level. If you are expecting such functionality, it would be very helpful if you could help us create a new post in our technical forum so that more people with similar request can join the discussion and upvote for this idea. 

Thanks again for your suggestion. 

**Microsoft 365 Developer Platform:** 
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Closed as completed by adrianwu8516** 2024-07-22 09:27 UTC
Labels: Area: Excel, Type: product bug, Resolution: by design, Status: in backlog
