### ISSUE TITLE
Add-in error right after update

### ISSUE THREAD

**Issue by ElizabethFerriss** [OfficeDev/office-js#2159] opened 2021-10-04 20:33 UTC
Shortly after receiving official approval of the manifest containing the latest update of our [add-in](https://appsource.microsoft.com/en-us/product/office/wa104379640?tab=overview) (Version 3.3.4.1) was approved last Friday, I uninstalled and then re-installed the add-in through Insert → My Add-ins. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft 365 Version 16.53 (21091200)
* Operating System: MacOS Big Sur Version 11.6
* Browser (if using Office on the web): 
 
## Expected behavior
I expect to see the fully updated version of the add-in.

## Current behavior
I received an Add-in Error: We can't start this add-in because it isn't set up properly. Clicking "Retry" several times did not help. The security info for the app included both versions - the old on in the URL  https://addins.knoema.com/KnoemaDataFinder/3.3.3.1/Views/Excel.html and the new one in Version 3.3.4.1

## Steps to reproduce
Refreshing the add-in after waiting several days resolved the issue, and we have not been able to reproduce it. 

# Provide additional details
Seems like there is a window of time between when the manifest is approved and when it is fully functional and ready to be updated.

## Context
We want to alert our users as soon as possible when updates and bug patches are available.

## Useful logs
<img width="256" alt="Screen Shot 2021-09-24 at 4 06 26 PM" src="https://user-images.githubusercontent.com/43617390/135920695-c4007458-4534-4e08-90f1-47752d269b32.png">

**Comment by nancy-wang** [comment] 2021-10-07 23:22
thanks for reporting this @ElizabethFerriss and sorry to hear you are no longer able to access your add-in! Connecting you with @gingerjia who may be able to help here.

**Comment by gingerjia** [comment] 2021-10-12 10:57
@chiz-ms has helped to contact the right owner and will update here if any progress. Thanks @nancy-wang and @chiz-ms !

**Comment by jargil** [comment] 2021-10-15 16:17
@ElizabethFerriss - thank you for reporting this. Looks like you're unblocked now and you don't have a repro anymore.
I just tried going through this flow (uninstall, install, after an update) but I'm not able to reproduce. I'll close this Issue for now. Please reopen again if you reproduce again, and please make sure to send us feedback so that we can get some logging to look at. You can also try Collect Diagnostics and share with us:

https://support.microsoft.com/en-us/office/how-do-i-give-feedback-on-microsoft-office-2b102d44-b43f-4dd2-9ff4-23cf144cfb11#platform=macOS

**Closed as completed by jargil** 2021-10-15 16:17 UTC
Labels: Area: Excel, Type: product bug, Area: add-ins platform, Resolution: cannot repro
