### ISSUE TITLE
[Excel] `delayForCellEdit ` is not working as expected.

### ISSUE THREAD

**Issue by kullachoke-bosuwan-rft** [OfficeDev/office-js#1393] opened 2020-09-18 09:34 UTC
Based on this page https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-delay-in-cell-edit,
I've already set `delayForCellEdit` option but the batch request has not wait for user to exits cell edit mode. The api failed to write new value to cell without any errors.

## Steps to Reproduce, or Live Example
`
Excel.run({ delayForCellEdit: true }, (ctx) => {
  const ws = ctx.workbook.worksheets.getActiveWorksheet();
  const r = ws.getRange('E5');
  r.values = [['new value']];
  return ctx.sync();
})
`
1. run above code snippet to change cell value
2. enter cell edit mode on `E5` immediately after execute the code.
3. wait for a while before exit cell edit mode.
4. observe the target cell (`E5`), its value has not changed.

Please see the video link below for the full reproduce steps.
https://drive.google.com/file/d/1_Ln0Sj3Oz7-EyBhcmkW2QMD5EnKcuFSu/view?usp=sharing

## Your Environment
I didn't have a chance to test on other platform yet. Below is environment that use to reproduce the issue in video.

* Platform: web
* Host: Excel
* Operating System: Mac
* Browser: Chrome

![Screen Recording 2563-09-18 at 15 39 52](https://user-images.githubusercontent.com/64405659/93581240-11c4aa00-f9cb-11ea-9ec1-609012eeb67d.gif)

**Comment by lumine2008** [comment] 2020-09-21 03:35
Hi @kullachokebosuwan-refinitiv , we have created a gist https://gist.github.com/jingch0109/e814fb8cf2f035ac1c3e189fb83253c6, but it seems it works fine on XLO, would you please review the gist and suggest how we can repro this issue?

**Comment by kullachoke-bosuwan-rft** [comment] 2020-09-21 06:00
Thank you @lumine2008  for take a look into this.

step to reproduce,
1.  import code from https://gist.github.com/kullachokebosuwan-refinitiv/ae25d695bbb457e6b8f1765ce772e1b8
2. open network console and set Network Throttling to `Fast 3G`
3. run the code and immediately enter cell edit mode on `E5`

or see this video for all steps: https://drive.google.com/file/d/16unitJbsSgvQZMKFpZ0oDzaTDban2-fn/view?usp=sharing

If you check on the log, after `run` function was executed and "Done!!" displayed in console. There are some delays before API write new value to cell. At that time if user enter cell edit mode, new value will not being written.

In real case, this can happen without setting network throttling depending on network speed or number of data or api call on the sheet.

**Comment by ElizabethSamuel-MSFT** [comment] 2020-09-28 23:08
@lumine2008 Any update here? Thx.

**Comment by lumine2008** [comment] 2020-10-09 14:13
Team has repro'ed this issue and a bug (4497788#) was created to track this issue. thanks for your information

**Comment by lumine2008** [comment] 2020-10-20 05:39
Update: 
based on our investigation, we learn that when the result is back, but due to the slow network, the result has not been rendered and meanwhile user is getting into edit mode. So, API result is lost, in order to resolve this issue, we need Excel online input. so we created a new bug(4497788#) for Excel online team

**Comment by kullachoke-bosuwan-rft** [comment] 2020-10-20 05:48
Thanks for the update, I really appreciate it. hope this will be solved soon.

**Comment by lumine2008** [comment] 2021-03-17 08:26
We learn from owner team that the behavior is by design. here are some advice from owner team:
a. Do virtual getrange calls to speed up the ranges retrieval
b. Display some notification the the user that the values from the script run aren't yet fetched

**Comment by lumine2008** [comment] 2021-03-23 13:23
If this is important for your add-in, feel free to submit this as a feature request to our Uservoice - https://officespdev.uservoice.com/

Closing the issue as "by design", please reactivate if you have any more questions/feedback.

**Closed as completed by lumine2008** 2021-03-23 13:23 UTC
Labels: Area: Excel, Resolution: by design
