### ISSUE TITLE
How to Close a Task Pane from Within the Task Pane UI on Button Click

### ISSUE THREAD

**Issue by waqasahmed042** [OfficeDev/office-js#4880] opened 2024-09-11 12:20 UTC
How to Close a Task Pane from Within the Task Pane UI on Button Click.

```Office.context.ui.closeContainer()``` This function is not working in word add-in

<img width="437" alt="image" src="https://github.com/user-attachments/assets/57f8be75-2d08-42d1-b053-9a622e8df854">

**Comment by junaid042** [comment] 2024-09-11 13:19
In Word add-in

**Comment by junaid042** [comment] 2024-09-11 13:19
In Word add-in

**Comment by shanshanzheng-dev** [comment] 2024-09-12 01:51
Hi @waqasahmed042 Thanks for reporting this issue. Currently, we don't support this API on Word to close a task pane. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)

**Comment by waqasahmed042** [comment] 2024-09-12 02:55
Okay 👍 Thanks for updating me.

**Comment by shanshanzheng-dev** [comment] 2024-09-12 03:01
[like]  Shanshan Zheng reacted to your message:
________________________________

**Comment by jipyua** [comment] 2024-09-12 05:53
hi @waqasahmed042, as a workaround, does hide the taskpane (Office.addin.hide();) meet your requirement? see here for details https://learn.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in

**Comment by waqasahmed042** [comment] 2024-09-12 07:17
> hi @waqasahmed042, as a workaround, does hide the taskpane (Office.addin.hide();) meet your requirement? see here for details https://learn.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in

It's only work in word ribbon button through command.js not inside from the taskpane

**Comment by junaid042** [comment] 2024-09-12 10:01
@shanshanzheng-dev what its mean can you explain:  **Called from a task pane: The task pane will close.** 

https://learn.microsoft.com/en-us/javascript/api/office/office.ui?view=common-js-preview#office-office-ui-closecontainer-member(1)


![image](https://github.com/user-attachments/assets/d91af12f-302c-447a-8449-0da60fed3aee)

**Comment by shanshanzheng-dev** [comment] 2024-09-13 01:57
Hi @junaid042, we will reach out to an expert to address your question.
@m-hellesen, could you take a look at this issue? Thanks.

**Comment by waqasahmed042** [comment] 2024-09-24 03:04
Hi @m-hellesen, @shanshanzheng-dev I hope you're doing well! I wanted to check in on the status of the issue we discussed. Is there any update or progress you can share? Thanks for your help!

**Comment by shanshanzheng-dev** [comment] 2024-09-25 04:40
Hi @waqasahmed042 could you share us your test code? Thanks.

**Comment by waqasahmed042** [comment] 2024-09-25 08:13
Hi @shanshanzheng-dev, [Here is my add-in interface](https://github.com/user-attachments/assets/59ad3132-19d0-4b15-8f4a-02f8a2407b39) I want to close the task pane when the user clicks the close button.

Here is my GitHub repository for test code https://github.com/waqasahmed042/contract-negotiator.git
Let me know if you need further refinements!

**Comment by shanshanzheng-dev** [comment] 2024-09-26 03:05
Hi @waqasahmed042 Thanks for this information, we still need some time to investigate, we'll report back if we have new updates, Thanks for you patience!
Meanwhile, we recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)

**Comment by RuizhiSunMS** [comment] 2024-11-12 09:46
Close this case since this is more like a feature request and has suggest user to submit request on developer forum.

**Closed as completed by RuizhiSunMS** 2024-11-12 09:46 UTC
Labels: Type: product feature request

**Comment by waqasahmed042** [comment] 2024-11-20 04:02
Hi @RuizhiSunMS Thank you for pointing this out. Based on the linked documentation, this appears to be a bug rather than a feature request: 
[Office UI CloseContainer](https://learn.microsoft.com/en-us/javascript/api/office/office.ui?view=common-js-preview#office-office-ui-closecontainer-member(1))

![image](https://github.com/user-attachments/assets/543c7a0a-9e95-43cd-9733-b9b6ef3be497)
We request that this issue be investigated properly to ensure the documentation is accurate. thanks

**Comment by siddhu-tri2000** [comment] 2026-08-27 05:45
Office.context.ui.closeContainer() is not implemented for Word. The reference documentation lists Word as supported, and that is our documentation error rather than anything wrong with your code. We have the correction tracked.

So the honest status is that closing the task pane from inside the pane is a capability Word does not have, not a bug we are about to fix. If you need it, saying so on this thread genuinely helps it get weighed against other platform work.
