### ISSUE TITLE
Access Storage from Dialog opened by Custom Functions

### ISSUE THREAD

**Issue by SWDevB** [OfficeDev/office-js#653] opened 2019-08-06 10:54 UTC
There is a dialog I open from task pane or custom functions runtime and this dialog has an input which's data should be stored inside the OfficeRuntime.storage to be available for task pane and custom functions run time as well.

I at first tried to directly write into the storage from the dialog itself and this worked fine while running the add-in in Excel online. But when I try to run it in Excel desktop, accessing the storage doesn't work.

It seems recent updates changed the behavior of Office, because now it seems Office seems not to be initialized at all for a this kind of dialog. So now I get the "please side load" message.

## Expected Behavior
Since it works in Excel Online I would expect it to also work in Excel Desktop. If this actually isn't supported I would at least have expected it to behave the same way in both versions. 
I am aware of the different run times used, but the differences between behavior of online and desktop excel versions are really distracting...

## Current Behavior
In Excel online the dialog is able to access the storage in Excel desktop it isn't

## Steps to Reproduce, or Live Example
  1. Open dialog via task pane: Office.context.ui.displayDialogAsync
  2. Open dialog via custom functions runtime: OfficeRuntime.displayWebDialog
  3. Access Stroage via OfficeRuntime.storage.getItem

## Context
I try to accomplish to get a URL from the user where to connect to and of course I don't want to ask the unser not several times for the same information. 

So i changed the behavior and read from the store before opening the dialog and set it via request get parameter (what find kind of ugly myself) and return the value via Office.context.ui.messageParent. That's what the article about authorization for custom functions suggests (a least in the graphing to show the connection of the different run times)

## Your Environment
Platform [PC desktop, Mac, iOS, Office Online]: PC
Host [Excel, Word, PowerPoint, etc.]: Excel
Office version number: 1906 (Build 11727.20210 Click-to-Run)
Operating System: Windows 10 Enterprise 1903 18362.239
Browser (if using Office Online): Chrome or Edge (running in both of them)

## Useful logs
**Initially** 
I got the following error: 
"name":"Internal Error", "message":"An internal error has occurred.", "code":5001
**Currently**
 I get no initialization of office and if I skip that I of course get 'OfficeRuntime' is not defined
**Stackoverflow question** 
https://stackoverflow.com/questions/56807881/accessing-officeruntime-storage-within-an-dialog-in-office-js-excel-add-in

**Comment by SWDevB** [comment] 2019-08-08 07:18
I mentioned office not being initialized for dialogs currently, at least for me - and this seems to be the bigger issue right now because that way Office.context.ui.messageParent also wont work. Can this be confirmed and also tackled within this issue or should I create another one?

**Comment by wamaina** [comment] 2019-08-08 17:33
Hi @SWDevB,

Thank you for reaching out with this issue. I've added @lliu113 to this item. @lliu113, could you look into this?

**Comment by YiJinMSFT** [comment] 2019-08-09 03:17
This tag in html header should solve your initialization problem. 
`<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>`
Where do you get the error message? is it from messageParent or displayDialog? I assume it is not from localStorage. It will be helpful if you can provide the parameter when you are calling these api.

**Comment by SWDevB** [comment] 2019-08-16 09:15
Hello, thanks for the hint but the html header is already present. The initialization of excel should call the following function, which it does if called from anything but the **custom functions** in **desktop**). 

```
/* Render application after Office initializes */
Office.initialize = () => {
    isOfficeInitialized = true;
    delete window.alert;

    render(App);
};
```

So I'm in this case still stuck on the "Please sideload your addin to see app body." and unfortunately still not able to reproduce my initial error when opening from custom functions desktop.

When I open the dialog from the excel **desktop task pane** Office is initialized, the page is shown and while trying to access the storage I get the following error: {"name":"Permission Denied","message":"You don't have sufficient permissions for this action.","code":7000}

I access the storage in the following way, and that's the missing call.
`await OfficeRuntime.storage.getItem("key");`

Everything still working in excel online

**Comment by ebortoluzzi-maualab** [comment] 2020-02-14 18:05
Any alternative for the communication between the dialog and Excel custom function while this is being solved?

**Comment by ghost** [comment] 2020-05-30 23:00
I'm interested by a solution as well !

**Comment by thunter05** [comment] 2020-07-07 20:56
Any update with this? I'm running into the same issue.

**Comment by SWei1234** [comment] 2020-09-18 03:13
Hi @exextoc 
Any idea about this?
I met the same issue on Outlook 16.0.4266.1001 ,Windows 10 1903, IE version 11.1457.17763.0

Or you think this is not related with office.js?
Thanks

**Comment by exextoc** [comment] 2020-09-19 13:19
Hey @SWei1234 ,

Are you facing an issue with messageParent for an Outlook web add-in? Is the issue only on a particular platform? (Outlook for Windows/Mac/OWA)

**Comment by SWei1234** [comment] 2020-09-21 01:45
Hi @exextoc 
    I got the error : {"name":"Permission Denied","message":"You don't have sufficient permissions for this action.","code":7000}
    Report api: 'displayDialogAsync' 
    Currently this issue only happened on: outlook on windows.

**Comment by SWei1234** [comment] 2020-09-21 06:38
> Hey @SWei1234 ,
> 
> Are you facing an issue with messageParent for an Outlook web add-in? Is the issue only on a particular platform? (Outlook for Windows/Mac/OWA)

Resolved by install update package:https://support.microsoft.com/en-us/help/4475580/september-3-2019-update-for-office-2016-kb4475580

**Comment by exextoc** [comment] 2020-09-21 14:24
@SWei1234 so we take it the issue is fixed for you?

**Comment by SWei1234** [comment] 2020-09-22 05:30
> @SWei1234 so we take it the issue is fixed for you?

Yes, Thanks for your support.

**Comment by exextoc** [comment] 2020-09-23 11:25
Reopening this since the original question was about Excel. Sorry about that.

**Comment by lliu113** [comment] 2021-06-02 19:56
@SWDevB - sorry for the very late response to this. The behaviour you're witnessing is by design, the dialog only supports a very limited range of APIs. As a workaround, we suggest passing data between the dialog and taskpane via the [messaging APIs](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#send-information-from-the-dialog-box-to-the-host-page). 

The reason this works Online is due to a quirk in the implementation, this behaviour is actually not supported on the platform. 

Hopefully the messaging APIs work for your scenario, I'll go ahead and close this for now. Please reactivate if you have any additional questions. Thanks!

**Closed as completed by lliu113** 2021-06-02 19:56 UTC
Labels: Area: Excel, Type: product bug, Area: add-ins platform, Resolution: by design
