### ISSUE TITLE
Uncaught (in promise) RichApi.Error when trying to load "creationDate" of a workbook

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#3742] opened 2023-10-11 09:11 UTC
# When trying to load the "creationDate" property of workbook, I am getting an internal error. I am able to load all the other properties except that one.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16926.20000
* Operating System: Windows 10
 
## Expected behavior
The date should load if it exists, and should return null if it doesn't exist.

## Current behavior
Breaks the application.

`
const fetchProperties = () => {

    Excel.run(async (ctx: Excel.RequestContext) => {

      let fileProperties = ctx.workbook.properties;

      fileProperties.load("creationDate");

      await ctx.sync();

      console.log(fileProperties.creationDate);

    });

  };
`
example code that breaks.

**Comment by ghost** [comment] 2023-10-11 09:16
One thing I have discovered is, the file that was open is an .xlsb file (meaning, the user forgot the saved and recovered the file). In that case this error occurs.

**Comment by SiruiSun-MSFT** [comment] 2023-10-11 12:04
Hi @BoramSpark, I tried to repro the issue you mentioned above through a newly created xlsb file, however failed. I'm afraid that the file you used has been broken. We would like to know the frequency of this issue. Whether it happen to many customers? If so, could you provide us with a test file, which enables us to debug from our side? Thanks!

**Comment by ghost** [comment] 2023-10-11 12:09
[Excel add-in 08581e28-2381-4909-becf-4e8a8bed0((Unsaved-310630902591350534)).zip](https://github.com/OfficeDev/office-js/files/12869548/Excel.add-in.08581e28-2381-4909-becf-4e8a8bed0.Unsaved-310630902591350534.zip)

This might be a very FAR edge-case since I only encountered while developing a Event Listener Management Library

**Comment by SiruiSun-MSFT** [comment] 2023-10-13 08:33
Hi @BoramSpark, we could repro the behavior on the recovery file. However, the general exception is by design. As the creation date property is only enabled on the creation file, which does not include the recovery file as you provided. Also, from UI side, you also cannot find its creation date.
![image](https://github.com/OfficeDev/office-js/assets/86719968/74d22607-80d2-4cd0-9cb2-afe527e00e06)
If you still want to run the gist on this file successfully, maybe you need to re-saved this file as another one. Hope this will help you!

**Comment by ghost** [comment] 2023-10-13 08:45
@SiruiSun-MSFT I understand! One thing that is not clear to me is that when you open a blank file in Excel, it will have a creation date. The time it was "opened" even if the user doesn't save it. But when this file is recovered, the creation date is cleared?

**Comment by SiruiSun-MSFT** [comment] 2024-04-10 09:18
I'm sorry for the current situation. On this basis, the only method we can provide is to convert this file into a non-recover file.
Considering it's by design behavior, close this issue for now. If you have more comments about the case, please feel free to re-open this again. Thanks!

**Closed as completed by SiruiSun-MSFT** 2024-04-10 09:18 UTC
Labels: Needs: attention :wave:, Area: Excel
