### ISSUE TITLE
Attachment contentType isn't properly set for XLSX file

### ISSUE THREAD

**Issue by somenathmaji** [OfficeDev/office-js#2297] opened 2021-12-09 07:49 UTC
## Client's Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.13801.21050
* Operating System: Windows 10 19043.1348
* Browser (if using Office on the web): N/A
 
## Expected behavior
ContentType should be properly set.

## Current behavior
ContentType is undefined for an attachment with `.XLSX` file type.

## Steps to reproduce
This happened on a client's PC. The file extension is in uppercase. Locally it's isn't reproducing.

# Provide additional details
We tried below code snippet to get contentType of the attachment.
`Office.context.mailbox.item.attachments[0].contentType`

## Useful logs
I will add the screenshot and console logs as soon as I get it.

**Comment by exextoc** [comment] 2021-12-13 05:22
Thanks for reporting this issue.
I can reproduce this issue so I have created a product bug for it. At the moment, we don't have any timelines to share about this bug.

Internal tracking bug : Office 5657412

**Comment by exextoc** [comment] 2021-12-14 01:36
After internal discussion, this issue won't be fixed. (this API Value will eventually be deprecated). In our current documentation: 

https://docs.microsoft.com/en-us/javascript/api/outlook/office.attachmentdetails?view=outlook-js-preview#contentType

Note the comment: 

Important: While the contentType value is a direct lookup of the attachment's extension, the internal mapping isn't actively maintained. If you require specific types, grab the attachment's extension and process accordingly.

On the Attachment Details object, you can grab the file extension off the name property, and classify your Attachment that way.  (that is all the internal code is doing anyway). That is a much more reliable solution that relying on this property (and part of the reason why it will eventually be deprecated)

**Comment by somenathmaji** [comment] 2021-12-14 05:20
@exextoc Thanks for looking into this. We will use the attachment's extension and process it for types.

**Closed as completed** 2021-12-15 20:16 UTC
Labels: Needs: triage :mag:
