### ISSUE TITLE
Content Pane Addin Not Loading in Excel Online

### ISSUE THREAD

**Issue by david-ps** [OfficeDev/office-js#707] opened 2019-09-05 06:28 UTC
## Content Pane Addins - Loading Differences
**Excel Desktop**: When an Addin is added to a Worksheet; the Addin loads on File Open even if the Addin is **not** on the Active Worksheet that was selected when the file was last Saved. 

**Excel Online**: The Addin is **not loaded** until the Worksheet containing the Addin is selected and Active, ie. when the iFrame Loads.

## Expected Behavior
A **Content Pane Addin** should load when the Workbook is opened in **Excel Online** the same as it does in **Excel Desktop**.

## Current Behavior
In **Excel Online**, the Addin is **not loaded** until the Worksheet containing the Addin is selected and Active.

## Steps to Reproduce
1. Start with a Workbook with two sheets 
2. Add a Content Pane Addin to Sheet 1 
3. Select Sheet 2
4. Save the Workbook
5. Open Workbook in Excel Online > Sheet 2 is displayed
6. Content Pane Addin on Sheet 1 is not loaded
7. Select Sheet 1
8. Content Pane Addin is loaded.

## Context & Implications
If a **Content Pane Addin** is designed to monitor and respond to events in ranges on another Sheet, it will not be enabled in Excel Online on file open, if it is not the initial Active Worksheet when opened. 

This means that synced data managed by the Addin, is **not maintained** and can be corrupted if the user makes changes to sync related data **before** selecting the sheet that contains the Addin and it is loaded.

## Environment

- Excel Office 365 Desktop and Online
- Edge or Chrome Browser
- Windows 10

**Comment by sumurthy** [comment] 2019-09-05 06:52
@lliu113 Can you please take a look at this?

**Comment by keyur32** [comment] 2019-10-10 22:07
I think this one is by design  in terms of the content add-ins on non visible sheets not being activated as we don't load that hidden sheet in the browser for performance reasons (since the add-in would need a web browser to activate).

**Comment by keyur32** [comment] 2019-10-10 22:08
For scenarios like this, we'd instead recommend a taskpane add-in.

**Comment by david-ps** [comment] 2019-10-15 09:10
@keyur32 Thanks for following up this issue.

Your suggestion of using the Task Pane Add-in is a slightly different use case and does not solve, but has a similar intrinsic issue. If the Task Pane Addin is designed to monitor and respond to events in ranges on a sheet, whereby data on different sheets is synced, it will not be enabled in Excel Online or Desktop on file open, if the Task Pane Addin is not saved as open. I get that this is by design.

However, I see not supporting a Content Pane Addin for the sync use case (described originally above) in Excel Online where it IS supported in the Desktop, as a major disconnect and issue and surely not by design, more a substantial design problem waiting to be solved.

**Comment by lindalu-MSFT** [comment] 2020-01-27 19:13
Closing this issue since it is resolved "by design." Please go to User Voice to add your suggestion for Content Pane add-in support in Excel Online. Thanks, lindalu
[Office Developer User Voice suggestion box](https://officespdev.uservoice.com/)

**Closed as completed by lindalu-MSFT** 2020-01-27 19:13 UTC
Labels: Type: product bug, Area: add-ins platform, Resolution: by design
