### ISSUE TITLE
`OnMessageCompose` LaunchEvent in manifest fails validation when uploading to admin center

### ISSUE THREAD

**Issue by alexm-plutoflume** [OfficeDev/office-js#3092] opened 2023-01-16 14:00 UTC
When trying to upload a manifest with a `OnMessageCompose` LaunchEvent, it fails validation in the M365 Admin portal when trying to upload the manifest & deploy.

Sideloading the manifest works fine in Outlook.

With the same manifest, if you use a different LaunchEvent such as `OnNewMessageCompose`, the manifest is able to be uploaded and deployed in the admin portal.

## Your Environment
*  Occurs in both Firefox & Chrome, haven't tried other browsers.
 
## Expected behavior
That a manifest with an `OnMessageCompose` LaunchEvent would be able to be uploaded and deployed through the M365 Admin portal

## Current behavior
The 'upload manifest file from device' step fails with an error "Invalid manifest file".

![image](https://user-images.githubusercontent.com/80270047/212694799-d480c623-4176-49f1-bba9-f3487bed00ed.png)

In the Chrome network tab, I can see an API call to `uploadCustomApp` is failing with a 500 response as noted below

```json
{
   "appDetail":null,
   "returnedWorkloads":null,
   "errorMessage":"[\"Autorun LaunchEvent Type is not valid. Autorun LaunchEvent Type provided in the manifest is not valid as per package validation service\"] Error Response : , Error Message : , Response Headers : {\r\n  \"X-Frame-Options\": [\r\n    \"SAMEORIGIN\"\r\n  ],\r\n  \"X-DEPLOYMENT-ID\": [\r\n    \"04d6d5e6d9234eca95487951a0e3a7c7\"\r\n  ],\r\n  \"x-ms-correlation-id\": [\r\n    \"25107915-4d65-458f-bfdd-2ebf10f18e2d\"\r\n  ],\r\n  \"X-AspNet-Version\": [\r\n    \"4.0.30319\"\r\n  ],\r\n  \"X-Powered-By\": [\r\n    \"ASP.NET\"\r\n  ],\r\n  \"X-Content-Type-Options\": [\r\n    \"nosniff\"\r\n  ],\r\n  \"X-UA-Compatible\": [\r\n    \"IE=Edge\"\r\n  ],\r\n  \"X-Cache\": [\r\n    \"CONFIG_NOCACHE\"\r\n  ],\r\n  \"X-MSEdge-Ref\": [\r\n    \"Ref A: FBC3039FC306498A8B25D2AC7055F114 Ref B: LON212050715051 Ref C: 2023-01-16T13:45:13Z\"\r\n  ]\r\n}",
   "statusCode":"WxpoFailedManifestValidationError",
   "statusCodeCategory":"WXPO"
}
```
## Steps to reproduce
1. Upload the manifest provided below that contains the `OnMessageCompose` LaunchEvent to the M365 admin portal.

## Example manifest to reproduce
This manifest fails validation in the admin portal when uploading as is, with the `OnMessageCompose` LaunchEvent, but if you switch the LaunchEvent type to `OnNewMessageCompose` it will succeed.
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xsi:type="MailApp">
  <Id>8b93e5f3-1fa3-59e4-bdc3-f1b1428432b9</Id>
  <Version>3.5</Version>
  <ProviderName>Example</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Example"/>
  <Description DefaultValue="Example"/>
  <IconUrl DefaultValue="https://localhost:3000/assets/asset.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:3000/asset.png"/>
  <SupportUrl DefaultValue="https://localhost:3000/"/>
  <AppDomains>
    <AppDomain>https://localhost:3000</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>

  <Requirements>
    <Sets>
      <Set Name="MailBox" MinVersion="1.8"/>
    </Sets>
  </Requirements>

  <FormSettings>
    <Form xsi:type="ItemEdit">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:3000/commands.html" />
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteMailbox</Permissions>

  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit"/>
    <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Edit"/>
  </Rule>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">

      <Description resid="residAppDescription" />

      <Requirements>
        <bt:Sets DefaultMinVersion="1.8">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>

      <Hosts>
        <Host xsi:type="MailHost">
          <Runtimes>
          <!-- HTML file including reference to or inline JavaScript event handlers.
               This is used by Outlook on the web and Outlook on the new Mac UI. -->
            <Runtime resid="residUILessFunctionFileUrl">
            <!-- JavaScript file containing event handlers. This is used by Outlook on Windows. -->
              <Override type="javascript" resid="JSRuntime.Url"/>
            </Runtime>
          </Runtimes>
          <DesktopFormFactor>
            <FunctionFile resid="residUILessFunctionFileUrl" />
            <ExtensionPoint xsi:type="Events">
              <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="onSendCallback" />
            </ExtensionPoint>
            <ExtensionPoint xsi:type="LaunchEvent">
              <LaunchEvents>
                <LaunchEvent Type="OnMessageCompose" FunctionName="onMessageComposeHandler"/>
              </LaunchEvents>
              <SourceLocation resid="residUILessFunctionFileUrl" />
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>

      <Resources>
        <bt:Images>
          <bt:Image id="Icon.64x64" DefaultValue="https://localhost:3000/assets/icon-64.png"/>
        </bt:Images>

        <bt:Urls>
          <bt:Url id="residUILessFunctionFileUrl" DefaultValue="https://localhost:3000/commands.html" ></bt:Url>
          <bt:Url id="JSRuntime.Url" DefaultValue="https://localhost:3000/launchevent.js" ></bt:Url>
        </bt:Urls>

        <bt:LongStrings>
          <bt:String id="residAppDescription" DefaultValue="Example manifest" />
        </bt:LongStrings>
      </Resources>

      <WebApplicationInfo>
        <Id>eae6a244-13a2-4712-8f2b-f2dfb712105b</Id>
        <Resource>api://localhost:3000eae6a244-13a2-4712-8f2b-f2dfb712105b</Resource>
        <Scopes>
          <Scope>profile</Scope>
        </Scopes>
      </WebApplicationInfo>

    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
```

# Provide additional details

## Context
Users of our manifest deploy it by uploading through the M365 admin center because we use the `ItemSend` event. We can't use this LaunchEvent in our Addin until it is able to be deployed like this through manual upload, blocking development of new features for our Addin.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ndeleuze** [comment] 2023-01-20 01:17
Does this issue repro on any other platforms? Like Outlook for Windows or Mac?

**Comment by AkhileshShah-MS** [comment] 2023-01-20 08:07
@alexm-plutoflume Thanks for reaching out! 
We are working on fixing this issue and should have an update for you by the end of the month.

**Comment by alexm-plutoflume** [comment] 2023-01-20 09:24
> Does this issue repro on any other platforms? Like Outlook for Windows or Mac?

@ndeleuze this is an issue when deploying the manifest via the M365 admin center. It is unable to be uploaded, giving a validation error.

The manifest can be sideloaded fine with no validation errors in all platforms (OWA, Mac, Windows).

@AkhileshShah-MS thanks for the update

**Comment by alexm-plutoflume** [comment] 2023-02-01 15:00
@AkhileshShah-MS any update here? Cheers

**Comment by carlosb1504** [comment] 2023-02-13 14:55
Hello, we are seeing a very similar message when using the `ItemSend` Event which we have used for some time. The relevant section of the manifest looks like this: 
![image](https://user-images.githubusercontent.com/47693383/218491004-097415de-8aeb-40d2-b282-562fb7bda1ac.png)

The error coming back from the MS Admin portal's call looks like this:
![image](https://user-images.githubusercontent.com/47693383/218491395-bc4ad779-c948-4965-9f21-83aca7cf6ac0.png)

We are implementing this in the same way described in MS [documentation here: ](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows#:~:text=In%20the%20Contoso%20Message%20Body%20Checker.xml%20manifest%20file%2C%20you%20include%20the%20function%20file%20and%20function%20name%20that%20should%20be%20called%20on%20the%20ItemSend%20event.%20The%20operation%20runs%20synchronously.)

Is this the same root issue? I'd appreciate a response on this as I can see this has been open for a while and this is blocking our customers from deploying our add-in currently.

Thanks

**Comment by stefanoslig** [comment] 2023-02-14 11:26
We have the same issue with @carlosb1504 . Nothing has changed in our manifest. @exextoc Could you please have a look? It was possible for the admins to install our add-in until recently. Now they get this validation error.

**Comment by cody-lettau** [comment] 2023-02-14 15:55
This just recently started for us (maybe past week) for our Outlook add-in that uses ```ItemSend```. Due to this, we cannot deploy our add-in for any new customers and existing customers cannot update their add-in.

This is a major issue.

@exextoc @AlexJerabek @AkhileshShah-MS can you please provide an update on this?

**Comment by AkhileshShah-MS** [comment] 2023-02-14 16:05
Hi @cody-lettau @stefanoslig @carlosb1504 - I acknowledge the issue with upload of manifests having ItemSend. This issue cropped up when fixing the issue for other events. We are already fixing the issue and i'll come back with an update within a week. 
Thank you for your patience and collaboration on this!

**Comment by cody-lettau** [comment] 2023-02-14 16:14
@AkhileshShah-MS thanks for the response. I really believe this should be a hotfix and fixed as quickly as possible. This is critical functionality that impacts the ability to deploy at a high percentage of organizations who lock down installing add-ins via side-loading.

**Comment by JuaneloJuanelo** [comment] 2023-02-14 20:00
Hello all, on behalf of the team I apologize about this issue.  There was a regression , which has been fixed and in the process to be rolled out to production. it might take a couple of weeks so everyone gets the fix. Fix is coming.

**Comment by AkhileshShah-MS** [comment] 2023-02-22 04:41
Hi @cody-lettau @stefanoslig @carlosb1504 - This fix has been released. Requesting you to validate on your end and let us know if you face any issues. Thanks for your patience on this!

**Comment by cody-lettau** [comment] 2023-02-22 14:03
@AkhileshShah-MS just tested on our test org and it worked as expected now. Thanks for fixing and letting us know it was pushed to production.

**Comment by AkhileshShah-MS** [comment] 2023-02-24 09:41
Thanks for the confirmation. Closing this issue.

**Closed as completed by AkhileshShah-MS** 2023-02-24 09:41 UTC
Labels: Status: fixed, Area: Centralized Deployment
