### ISSUE TITLE
[Word] - Word for some reason delete content control of first column in Child table

### ISSUE THREAD

**Issue by ysobol** [OfficeDev/office-js#392] opened 2019-02-18 15:02 UTC
**Main reason:**
When user add new column for this specific Parent table , In this specific case, MS Word for some reason delete first content control of Child Table. On top of that MS Word delete it in some wrong way.

**Steps:**
Create Template in Word Online
Add Parent Table with Any columns
Add new Row under Parent Table
Merge Cells in this row
Insert Child table in this row
Download document from Online
Open It using Word Desktop

Delete Header Row of Child table using standard MS word tool
Right click on Parent Table >>> Insert New Column from right side

**!!! In this case Word for some reason delete content control of first column in Child table.**

**Comment by dmahugh** [comment] 2019-02-21 00:53
Closed as duplicate of #397

**Closed as completed by dmahugh** 2019-02-21 00:53 UTC
