### ISSUE TITLE
[Outlook][Add-in Approval Process] Add-In fails to install after MS approved the last manifest change

### ISSUE THREAD

**Issue by splinter** [OfficeDev/office-js#493] opened 2019-04-29 14:14 UTC
I am posting here since this question does not seem like a valid SO question. 

Approximately two week ago we had submitted a new manifest adding pinning support to the MS store approval process. This manifest was subsequently validated and we received a mail saying that the changes were approved. We were notified that it may take a few days for these changes to propagate to our user base. However we have run into two problems:

1. A few users have been asked to install the add-in again (as expected), but the installation fails with an error saying "Something went wrong. The app could not be downloaded"
2. Most of our users have not received this notification at all

The manifest works fine when loaded via URL or file.

Who should we contact? The support link in the app dashboard does not work.

**Comment by exextoc** [comment] 2019-05-08 10:34
Kindly share the screenshot of the error and also the fiddler trace for the issue. Also share the name of the addin uploaded to store, for which the issue is happening.

**Comment by splinter** [comment] 2019-05-16 14:36
Add-In Name: CloudExtend Outlook for NetSuite
Fiddler Trace: We do not have access to the machine to obtain this trace
Screen: 
![image](https://user-images.githubusercontent.com/53738/57862481-08935e00-7816-11e9-9ae6-09b8eb0550ca.png)

**Comment by exextoc** [comment] 2019-05-16 17:47
Just to make sure, I cannot find "CloudExtend Outlook for NetSuite".  Could you provide the assetid (WA...)?  Or do you mean "CloudExtend: Integrate Your Inbox with NetSuite" https://appsource.microsoft.com/en-us/product/office/WA104381216?src=office ?  If so, is the store page showing the expected version?

Additonal questions:
- Are you expecting 'install add-in again' because the <Permissions> has changed in the manifest from the previous version?  Otherwise, update should not require user action.
- For the users who hit installation failure, do you know if they are on-premise or using O365?  If on-premise, do you know if they have the latest CU?

**Comment by splinter** [comment] 2019-07-18 05:44
Sorry about the delay.

Yes, the add-in name is `CloudExtend: Integrate You Inbox with NetSuite"

The store is showing the correct version.

> Are you expecting 'install add-in again' because the has changed in the manifest from the previous version? Otherwise, update should not require user action.

Yes

> For the users who hit installation failure, do you know if they are on-premise or using O365? If on-premise, do you know if they have the latest CU?

We do not have this information.

**Comment by exextoc** [comment] 2019-08-01 19:05
If you did not change the permission level, clients should get the updated manifest within 3 days, with no action. 

Otherwise users should try uninstalling and reinstalling the add-ins. 

Note that if you have added pinning to your manifest, if users are on older On Prem Exchange Accounts, they will not be allowed to install the add-in as the older servers cannot parse the new manifests.

**Comment by kbrandl** [comment] 2019-09-02 21:20
Closing this issue, as it seems like the information provided by @exextoc effectively addresses it. @splinter if that's not the case (and you'd like this issue to be reopened) please comment here to let us know what type of additional information / assistance you need. Thanks!

**Closed as completed by kbrandl** 2019-09-02 21:20 UTC
Labels: Area: add-ins platform, Type: product question
