### ISSUE TITLE
[Outlook] Taskpane closes unexpectedly in OWA

### ISSUE THREAD

**Issue by ShannonLCapper** [OfficeDev/office-js#478] opened 2019-04-13 01:17 UTC
In the "old" experience of OWA (the one served when `Try the new Outlook` is toggled off), the taskpane unexpectedly closes itself after varying lengths of time.

## Expected Behavior

I would expect the taskpane to remain open until the user manually closes it with the X button, or until a new mail was selected if the taskpane was not pinned open

## Current Behavior

In compose mode in "old" OWA, the taskpane will close on its own after an indeterminate amount of time. Sometimes it closes with 15 seconds of opening it, sometimes it happens after 5 minutes. As far as I can tell, this happens with any add-in (I've reproed with our own add-in as well as several others).

This can also happen while a dialog opened with `displayInFrame: true` is visible (I haven't tested with . When this happens, the page gets into a very bad state. The dialog can no longer send messages to its taskpane via `Office.context.uiu.messageParent`. Trying to close the dialog via the X button spams the console with errors, and the dialog cannot close. When in this state, the page also will not refresh by hitting `cmd + r`. The refresh button in the browser navbar turns to an `X`. Once that is clicked, it reverts back to a refresh button and you can refresh the page.

Note that this bug does not repro in the "new experience" of OWA. I have not tested to see if this repros in any other browser besides Chrome.

## Steps to Reproduce, or Live Example

* Repro 1 (no dialog):
  1. With "Try the new Outlook" toggled off, start a new mail.
  2. Open a taskpane in any JS add-in.
  3. Do nothing, and wait. Eventually, the taskpane will abruptly close. No errors will show up in the console.

* Repro 2 (with dialog):
1. With "Try the new Outlook" toggled off, start a new mail.
2. Open a taskpane for a JS add-in which uses the DialogAPI and `displayInFrame: true`.
3. Open a dialog from the taskpane. The dialog should open in a modal within the same page.
4. Do nothing, and wait. Eventually, the taskpane beneath the dialog modal will abruptly close. The modal dialog will remain open in the foreground. No errors will show up in the console. Note that the dialog is still functional for the most part - it can still render contents, make network requests, etc.
5. Try to close the dialog via the X button in the top right corner. An error will be thrown at `owa.clientNext.application.js:43` (see screenshot below), and the dialog will not close. At this point, the user must refresh the page in order to continue using OWA.

## Context

This is a pretty severe problem for us since our add-in heavily uses the Dialog API. It leads to a less-than-desirable user experience when the page frequently becomes broken while the dialog is open, especially since the user must refresh the page to get back into a good state. Our dialog includes a text editor, so refreshing the page often causes users to lose their work.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.10205.10000
* Operating System: OSX High Sierra (10.13.6)
* Browser (if using Office Online): Chrome (73.0.3683.103)

## Useful logs

<img width="466" alt="Screen Shot 2019-04-12 at 2 28 14 PM" src="https://user-images.githubusercontent.com/21230261/56072714-90d19f80-5d4e-11e9-9a83-4ec56caed1e2.png">

```
Exception in t(t){var o=e.call(this,t)||this;return o._warnDeprecations({onLayerMounted:"onLayerDidMount"}),o.props.hostId&&(u[o.props.hostId]||(u[o.props.hostId]=[]),u[o.props.hostId].push.componentWillUnmount(): TypeError: Cannot read property 'extension' of null
    at Object.o [as default] (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.extensibility.js:2:16883)
    at e.refCallback (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.extensibility.js:7:15203)
    at r (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:3330)
    at Object.a.detachRefs (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:3783)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19133)
    at Object.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:92:31463)
    at m.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:1377)
    at m.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:17896)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at Object.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:92:31463)
    at m.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:1377)
    at m.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:17896)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at Object.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:92:31463)
    at m.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:1377)
    at m.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:17896)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at d.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:3207)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at d.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:3207)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at Object.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:92:31463)
    at m.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:1377)
    at m.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:17896)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at d.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:3207)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at Object.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:92:31463)
    at m.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:1377)
    at m.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:17896)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at Object.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:92:31463)
    at m.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:1377)
    at m.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:17896)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at d.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:3207)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at Object.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:92:31463)
    at m.unmountChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:1377)
    at m.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:17896)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at d.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:3207)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at d.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:3207)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at l (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:50:17548)
    at Object.batchedUpdates (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:27829)
    at Object.i [as batchedUpdates] (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:23:29808)
    at Object.unmountComponentAtNode (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:50:20053)
    at t._removeLayerElement (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:27:17668)
    at t.componentWillUnmount (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:27:16544)
    at t.e.(anonymous function) [as componentWillUnmount] (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:43:7611)
    at d.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:3156)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at d.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:3207)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at d.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:3207)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at d.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:3207)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at d.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:3207)
    at Object.unmountComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19167)
    at Object.updateChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:92:31355)
    at m._reconcilerUpdateChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:114)
    at m._updateChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:879)
    at m.updateChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:94:777)
    at m._updateDOMChildren (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:17393)
    at m.updateComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:15773)
    at m.receiveComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:15326)
    at Object.receiveComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19326)
    at d._updateRenderedComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:6099)
    at d._performComponentUpdate (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:5856)
    at d.updateComponent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:5134)
    at d.performUpdateIfNecessary (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:4461)
    at Object.performUpdateIfNecessary (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:25:19508)
    at s (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:23:30211)
    at n.perform (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:26:16254)
    at r.perform (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:26:16254)
    at r.perform (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:23:31262)
    at Object.k [as flushBatchedUpdates] (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:23:31431)
    at n.closeAll (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:26:16848)
    at n.perform (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:26:16337)
    at Object.batchedUpdates (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:27844)
    at Object.i [as batchedUpdates] (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:23:29808)
    at dispatchEvent (https://r4.res.office365.com/owa/prem/16.2970.3.2685561/scripts/owa.clientnext.application.js:93:30456)
```

**Comment by exextoc** [comment] 2019-04-16 09:50
Thank you for reporting this bug.  We have added this to our active backlog, Shall update this thread once the fix is out.

**Comment by david-davidson** [comment] 2019-07-17 18:33
Hi @exextoc and @dmahugh, 

Has this fix rolled out? I ask because, on old OWA, I'm no longer able to reproduce this. Hoping that's exactly what we want. :)

Thanks!

**Comment by kbrandl** [comment] 2019-09-02 21:31
@ShannonLCapper @david-davidson apologies for the lack of response regarding whether or not this issue has been fixed. @exextoc can you please comment here to indicate the status of this bug fix (and if it's been deployed please also close this issue)? Thanks!

**Comment by kbrandl** [comment] 2019-09-03 17:03
Closing this issue now, per (offline) confirmation from @exextoc. Thanks!

**Closed as completed by kbrandl** 2019-09-03 17:03 UTC
Labels: Area: Outlook, Type: product bug, Status: fixed
