### ISSUE TITLE
Event based (Smart Alert) Manifest is rolled back when trying to install in MAC m/s using sideload option and not able to run the webAddin in MAC

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3990] opened 2024-01-11 04:57 UTC
We are developing office web Addin for outlook using event based (Smart Alert) .The Addin is generated using office yo generator Task Pane add-in using the React framework .

We are using OnMessageRecipientsChanged to validate

 recipient and show the error message in taskpane using notification events as an when recipients are getting added/removed . 

PFA manifest which is getting rolled back when trying to install in MAC m/s using sideload option 

[MAC_manifest_SmartAlert.docx](https://github.com/OfficeDev/office-js/files/13897505/MAC_manifest_SmartAlert.docx)

**Comment by exextoc** [comment] 2024-01-13 13:54
@geetamshukla Can you attach the manifest in XML/json format. The attachment could not open properly. Also what do you mean by rollback?
Please add, steps to repro, what is observed behaviour and what is expected.

**Comment by geetamshukla** [comment] 2024-01-16 10:23
> @geetamshukla Can you attach the manifest in XML/json format. The attachment could not open properly. Also what do you mean by rollback? Please add, steps to repro, what is observed behaviour and what is expected.

[manifest.json](https://github.com/OfficeDev/office-js/files/13948536/manifest.json)

@exextoc  PFA manifest in JSON format . 

By rolling back I meant the Addin is not shown in MAC thick client and Windows Outlook  Thick client whereas Same Addin work in OWA in MAC and Windows  . PFB screenshot for outlook version in MAC and Windows . 

![image](https://github.com/OfficeDev/office-js/assets/142812553/5657a5b6-fc4f-4b99-8e44-1d05c5268fe0)


![image](https://github.com/OfficeDev/office-js/assets/142812553/5055de7d-7929-4a14-b398-a7fdd2c114ec)

I am trying the dummy add-in developed using office yo generator Task Pane add-in using the React framework and have not modified the code  .

**Comment by ajays-msft** [comment] 2024-01-17 06:59
Duplicate of #3986

**Closed as completed by ajays-msft** 2024-01-17 06:59 UTC
Labels: Needs: attention :wave:, Area: Outlook
