### ISSUE TITLE
[Important] [P0] [Excel Add-In] F6 keypress event is not being passed to Content Add-In - Causing accessibility break

### ISSUE THREAD

**Issue by 3dot1four** [OfficeDev/office-js#415] opened 2019-03-09 22:14 UTC
## Expected Behavior
When I register for the key down event on document Add-In should get the event for all key downs. Including F6.

## Current Behavior
Excel is not propagating or filtering out the F6 key down event. 

## Steps to Reproduce, or Live Example
Create an excel content Add-In. Add below code. You will see logs for all the keys but F6.

 ```
$(document).on("keydown", function (event: JQuery.Event) {
       console.log(event.keyCode);
});
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1808(Build: 10730.20280)
* Operating System: Windows 10

**Comment by 3dot1four** [comment] 2019-04-09 10:15
any update? We are still blocked.

**Comment by JuaneloJuanelo** [comment] 2019-04-19 18:28
I was able to repro your issue and investigating internally ! thanks!

**Comment by Zlatkovsky** [comment] 2019-04-19 18:43
FYI, related issues that were filed on the Script Lab repo (but that are external to Script Lab -- i.e., they are platform issues just like this one):

- https://github.com/OfficeDev/script-lab/issues/698
- https://github.com/OfficeDev/script-lab/issues/331

**Comment by 3dot1four** [comment] 2019-04-21 20:31
@JuaneloJuanelo Since this is very important for us, any idea when we can expect a fix?

**Comment by JuaneloJuanelo** [comment] 2019-04-22 19:30
@rohitrewa turns out in this specific case (**for content add-ins**) is by design.  Add-ins must not break the accesibility of Office Applications, in this case Excel.  F6 is the way to move between windows within Office (as well as navigating to the ribbon)  and is one of the ways to navigate out of a Content add-in in the workbook.  Once in the content add-in you can  tab-navigate the internals of your add-in providing accessibility. 

Just for the record: can you please share what specific action you want to implement upon F6 key pressed?

**Comment by kbrandl** [comment] 2019-08-28 02:09
Closing this issue, per @JuaneloJuanelo's comment that this behavior is "by design".

**Closed as completed by kbrandl** 2019-08-28 02:09 UTC
Labels: Type: product bug, Area: add-ins platform, Resolution: by design
