### ISSUE TITLE
[Excel] Cache in addin

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#632] opened 2019-07-19 06:30 UTC
hi

## Expected Behavior

reload my excel addin pane . the new version of js can reload in  edge (windows 1903 )

## Current Behavior

when reload my excel addin pane the js cached

. the  old js is XXX.js?version=1,and  i modify the js ,so the new js is XXX.js?version=2.  so i 

reopen or reload excel addin. in ie( windows 1803) it's fine. it will reload new js. but in 

edge(windows 1903) i reopen excel addin or reload my addin it is still use old js. if i ctrl+F5 .

it's ok

i found windows 1903 excel addin use browser is edge.

**Comment by RuoyingLiang** [comment] 2019-07-19 06:59
Could you let us know 1) The Platform you are using PC desktop or Office Online. If using online, what's the browser version? 2) Is the add-in a published add-in or you are using sideload to load the manifest? 3) if you clear the cache, is the correct loaded?

**Comment by dinglicoding** [comment] 2019-07-19 07:06
@RuoyingLiang  thank you for quickly reply.

1) The Platform you are using PC desktop or Office Online
PC desktop

2) Is the add-in a published add-in or you are using sideload to load the manifest?
Published add-in , but i using sideload to load the manifest it's same

3) if you clear the cache, is the correct loaded?
yes.  if i use ctrl+F5  it can alse correct loaded. but i use F5 or click reload 
![image](https://user-images.githubusercontent.com/3963826/61516055-a8e44980-aa36-11e9-8832-9cb0f441c562.png)
it can not correct loaded new js  when my windows is 1903.

**Comment by RuoyingLiang** [comment] 2019-07-19 08:24
Sudhi, could you help to take a look if this is affected by web view change?

**Comment by fkranenburg** [comment] 2019-07-22 08:23
The exact same issue happens on Add-ins for Outlook too and it is caused by the web view change indeed. I already posted an stackoverflow question about [this issue here](https://stackoverflow.com/questions/57097062/outlook-web-add-in-office-1906-and-windows-10-build-1903-how-to-clear-cache) .

There is currently no reliable way to reload a new version of our add-in.

**Comment by Zlatkovsky** [comment] 2019-07-22 19:09
One common option I've seen done (including by Script Lab) is to set no-caching headers in the HTML page:

```
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
```

And also to make sure that the JS files you're injecting have filenames that are hashed (this would happen automatically for you in the production setting, if you're using webpack, or the output of create-react-app).

Does that not work for you?

**Comment by dinglicoding** [comment] 2019-07-30 03:03
@Zlatkovsky  thanks. if i use this code, each time i reload , it does not cache of my js. 

i expect  if have new js ,it reload. no new js .it still cache

**Comment by Zlatkovsky** [comment] 2019-07-30 03:13
@dinglicoding, this is really just browser behavior, not something that office add-ins can control one way or another.  An add-is is just a web page with an Office manifest...

**Comment by lindalu-MSFT** [comment] 2019-08-26 17:56
Thanks @Zlatkovsky and @sumurthy , can this issue be closed?

**Comment by kbrandl** [comment] 2019-08-28 20:59
Closing this issue, per @Zlatkovsky's most recent comment. Please feel free to comment here if you feel it should be reopened.

**Closed as completed by kbrandl** 2019-08-28 20:59 UTC
Labels: Area: add-ins platform, Resolution: not actionable
