### ISSUE TITLE
Outlook Mac Thick Client : Top Cross button of Office Modal Window not working

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3870] opened 2023-11-28 14:18 UTC
The Outlook WebAddin UI components are getting rendered inside the modal window of generated by Office JS.
The modal window has a cross button for closing it, on the right top hand corner, which comes inbuilt with the window.
If the user is clicking on the cross button on Mac outlook thick client then the particular email template is getting stuck
and Send button is getting disabled, with the message "Outlook WebAddin is running" in a loop.

Same code base is working fine for Windows Outlook Thick Client + Windows Outlook Web + MaC Outlook Web version

OnSend Event we are showing Office Js popup .In MAC Thick Client(Microsoft Outlook 16.77.1 (23091703) the office Js Popup close button is not working properly and If the user is clicking on the cross button on MAC Thick Client(Microsoft Outlook 16.77.1 (23091703) then the particular email template is getting stuck
and Send button is getting disabled, with the message "Outlook WebAddin is running" in a loop.

we are using event.completed with allowEvent argument as motioned in MS doc but its not working in thick client .

![image](https://github.com/OfficeDev/office-js/assets/142812553/0b7a9c21-8ecd-4318-97c9-71bac91cc256)

**Comment by exextoc** [comment] 2023-12-07 06:13
Hi @geetamshukla, could you please share a repro video or screenshots of the issue for us to investigate more into this?

**Comment by exextoc** [comment] 2023-12-14 06:11
Closing this bug as this is a duplicate of https://github.com/OfficeDev/office-js/issues/3661 . Please track the same for updates.

**Closed as not planned by exextoc** 2023-12-14 06:11 UTC
Labels: Area: Outlook, Resolution: duplicate
