### ISSUE TITLE
Outlook for Windows: from.emailAddress property returns LegacyExchangeDN

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#2590] opened 2022-05-17 08:59 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

The emailAddress property of From field is returned in LegacyExchangeDN value in Outlook for Windows.
This issue has been present since Outlook version 2204.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2204 (Build 15128.20224)
* Operating System: Windows 10
* Browser (if using Office on the web): -

## Expected behavior

The SMTP email address is returned.

## Current behavior

The Legacy Exchange DN is returned.

## Steps to reproduce

We have confirmed that the from.emailAddress property becomes LegacyExchangeDN in the following pattern.

* Compose mail from "Resend This Message"
* Compose mail from forwarding meeting messages
* Compose mail with FROM displayed in OWA

``` ts
$("#get-from").click(getFrom);

function getFrom() {
  Office.context.mailbox.item.from.getAsync(function(asyncResult) {
    if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
      var msgFrom = asyncResult.value;
      console.log(msgFrom);
    } else {
      console.error(asyncResult.error);
    }
  });
}
```

## Context

This issue is similar to issue #1250 which I reported previously.
If this issue occurs, our add-in will fail with an error and the user will not be able to send an email.
We have received a number of inquiries, could you please let us know what is going on?

## Useful logs

```
{
    "emailAddress": "/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=590D67CB2735454F9517D8B2F5CC0419-TEST",
    "displayName": "Test User"
}
```

Works: Version 2203 (Build 15028.20228)

https://user-images.githubusercontent.com/58804032/168772521-1d23da3e-4685-438f-b0a6-611e0b8120dc.mp4

Does not work: Version 2204 (Build 15128.20224)

https://user-images.githubusercontent.com/58804032/168772127-106ffd45-c95a-4cad-bd2f-46a3bc1b2ddf.mp4

**Comment by isabela-dominguez** [comment] 2022-05-17 20:47
Thank you for sharing this issue @clavx. Connecting you with @exextoc who may be able to help.

**Comment by clavx** [comment] 2022-05-27 08:04
Any updates on this?
This issue is still occurring with the latest version.
Current Channel: Version 2205 (Build 15225.20204)

I would appreciate it if you could share a workaround for this issue.

**Comment by JuaneloJuanelo** [comment] 2022-06-17 23:20
Thanks for reporting this issue, i am able to reproduce this condition and probably a regression. We are tracking internally with bug 6159759.  We don't have an ETA for this. 

@clavx  this seems to be edge cases for compose emails, i wonder if you can share how frequently you get issues like this. i wonder if its a common scenario for your add-in. thanks!

**Comment by clavx** [comment] 2022-06-24 12:32
Our add-in uses the On-Send event to confirm the domain part of all email addresses (Sender/From/To/Cc/Bcc).
When this issue occurs, we treat it as an error, so our add-in will not work and they will not be able to send emails.

We do not know how frequently because of this caused by customer actions.

This issue only occurs in Outlook for Windows, and it appears that OWA can be avoided, so we are advising our customers to use that instead.

Thanks.

**Comment by JuaneloJuanelo** [comment] 2022-07-06 15:53
update: we checked in a fix. you should be able to test in beta within the next 3 weeks. then will be released to production ~mid september.

**Comment by clavx** [comment] 2022-10-13 08:02
We have confirmed that this issue has been fixed.
Thank you!

- Affected (version 2204-2207)
    - Current Channel: Version 2204 (Build 15128.20178) - Version 2207 (Build 15427.20210)
    - Monthly Enterprise Channel: Version 2204 (Build 15128.20280) - Version 2207 (Build 15427.20308)
- Not affected (resolved)
    - Current Channel: Version 2208 (Build 15601.20088)
    - Monthly Enterprise Channel: Version 2208 (Build 15601.20230)
    - Semi-Annual Enterprise Channel

**Comment by antamosan** [comment] 2023-01-24 18:26
I have the exact same problem with python:

 ```
import win32com.client as win32
import pythoncom

outlook = win32.Dispatch('outlook.application', pythoncom.CoInitialize())

for store in outlook.Stores:
    if store.DisplayName == 'mail@domain.es': #I have several configured accounts, only one's inbox should be processed
        inbox = store.GetDefaultFolder(6)
        raw_mails = inbox.Items 

for item in raw_mails:
    print(item.Sender.Address)

```

In case sender belongs to my organization, wrong (unexpected) info is shown. It works well for external senders.

This is really troublesome as OLE is the only solution I found for modifying a previously working code I had with Exchangelib, but not anymore since simple authentication is no longer available. Oauth is now mandatory and I wasn't able to configure it with Exchangelib.

Any help would be appreciated.

P.S. Office 365 user; version: 2212 comp. 15928.20216

**Comment by yash888** [comment] 2023-02-09 13:22
> I have the exact same problem with python:
> 
> ```
> import win32com.client as win32
> import pythoncom
> 
> outlook = win32.Dispatch('outlook.application', pythoncom.CoInitialize())
> 
> for store in outlook.Stores:
>    if store.DisplayName == 'mail@domain.es': #I have several configured accounts, only one's inbox should be processed
>        inbox = store.GetDefaultFolder(6)
>        raw_mails = inbox.Items 
> 
> for item in raw_mails:
>    print(item.Sender.Address)
> ```
> 
> In case sender belongs to my organization, wrong (unexpected) info is shown. It works well for external senders.
> 
> This is really troublesome as OLE is the only solution I found for modifying a previously working code I had with Exchangelib, but not anymore since simple authentication is no longer available. Oauth is now mandatory and I wasn't able to configure it with Exchangelib.
> 
> Any help would be appreciated.
> 
> P.S. Office 365 user; version: 2212 comp. 15928.20216

To get only senders Address you can try (sender = message.Sender.GetExchangeUser().PrimarySmtpAddress). This works for me.

**Closed as not planned** 2024-04-11 16:45 UTC
Labels: Area: Outlook, Type: product bug
