### ISSUE TITLE
OnMessageSend and OnAppointmentSend  event based does not work on OWA

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#4231] opened 2024-03-11 05:10 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on web
* Host [Excel, Word, PowerPoint, etc.]:  Outlook
* Office version number: 365
* Operating System: Windows 11
* Browser (if using Office on the web): Edge
## Expected behavior
The onMessagesend and onAppointmentSent event with smart alert (promptuser)  should work on OWA, New Outlook and Outlook desktop classic 

## Current behavior
The onMessagesend and onAppointmentSend events is not triggering on OWA, New Outlook. However, works fine on Outlook for Desktop (classic) using the js runtime. This was working fine few weeks ago. We have made no code changes to the App, however the app event has stopped working

## Steps to reproduce

1.Create a basic onMessageSend and OnAppointmentSend event based addin
2. Send a email/event from OWA

**Comment by mmanjaree-msft** [comment] 2024-03-12 04:09
@avisheknand Could you please share a repro video and OWA Client version as we are unable to repro this issue. Also is this an intermittent issue or does it happen consistently all the time.

**Comment by avisheknand** [comment] 2024-03-13 04:10
@mmanjaree-msft ,

We did some further research and think that a recent update to either Office JS or Outlook (OWA and New Outlook) may have caused the problem by changing the way that manifests are processed.
 
This is what we found:
 
Previously the events available to New Outlook and OWA (And Classic Outlook) were controlled by the events that were declared in the DesktopFactor section of the manifest.
 
After the investigation , this seems no longer true. Now it appear that New Outlook and OWA can only see events that are declared in the Mobile factor section of the manifest.
 
In our case, the events declared for the two factors are different (mainly because many of the events are currently not available on mobile devices).
 
For us OnMessageSend did not work because it was not declared in the Mobile factor section
 
We have also recreated it by adding a Mobile factor section to manifest for  the sample code (running from GitHub).
https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-verify-sensitivity-label
 

I have added 2 manifest files, one is the original one and another one with the mobile factor.

From the looks it seems like desktopfactor events are been overwritten or ignored if mobilefactor events are declared when it comes to OWA or New Outlook.
[manifest-Original.zip](https://github.com/OfficeDev/office-js/files/14581951/manifest-Original.zip)
[manifest-mobile.zip](https://github.com/OfficeDev/office-js/files/14581952/manifest-mobile.zip)

**Comment by mmanjaree-msft** [comment] 2024-03-13 08:52
@avisheknand  Thanks for the information. Will investigate and keep you posted here.

**Comment by mmanjaree-msft** [comment] 2024-03-14 07:33
@avisheknand Thanks for reporting this issue. We are in process of fixing it. Will keep this post updated.
Internal tracking id: 262375

**Comment by avisheknand** [comment] 2024-03-19 08:23
@mmanjaree-msft , thanks for looking into this issue. Any updates on the fixes?

**Comment by ajays-msft** [comment] 2024-03-20 03:12
@avisheknand - The fix is checked in and rolling out to prod. You should get it by end of this week.

**Comment by avisheknand** [comment] 2024-03-24 21:28
@ajays-msft , i have checked and it's working  now. Thanks for the fix 🙌👌

**Comment by ajays-msft** [comment] 2024-03-25 13:44
closing as the issue is fixed.

**Closed as completed by ajays-msft** 2024-03-25 13:44 UTC
Labels: Area: Outlook, Status: fixed
