### ISSUE TITLE
getBookmarkRange throws invalid argument unless bookmark name is only a-z characters

### ISSUE THREAD

**Issue by mikerhyssmith** [OfficeDev/office-js#3702] opened 2023-09-21 13:42 UTC
When using getBookmarkRange with a bookmark that has a name that includes numbers or symbols, it throws an invalid argument error.

The bookmarks that we cant interact with are still visible inside the word UI even though the office js API throws the error.

Examples of those that fail

`12334`
`Bookmark:1234`

## Your Environment

* Platform Mac
* Host Word
* Office version number: 16.77.1
* Operating System:MacOS

 
## Expected behavior
getBookmarkRange should support getting bookmarks with alphanumeric characters or throw an error that explains the allowed format and include those limitations in the documentation

## Current behavior
getBookmarkRange throws an invalid argument error

## Steps to reproduce
Insert a bookmark into the document with some numbers in it `1234`

Call context.document.body.getBookmarkRange('1234')

See that it throws an invalid argument error

## Link to live example(s)

In any document with at least one paragraph this demonstrates the issue: 
```
    const paragraph = context.document.body.paragraphs.getFirst();

    const range = paragraph.getRange();

    await context.sync();

    range.insertBookmark("1234");

    await context.sync();

    const result = await context.document.body.getRange().getBookmarks();

    await context.sync();

    const bookmarkRange = context.document.getBookmarkRange("1234");

    await bookmarkRange.load();

    await context.sync();
  ```

## Context
We were creating Bookmarks with Numerical ids on it and were unable to access them - the error thrown wasnt clear why we couldnt access them even though the word UI shows and renders the bookmarks correctly

## Useful logs

- [X] Console errors

```
[ERROR]: Error:
{
    "message": "InvalidArgument",
    "name": "RichApi.Error",
    "code": "InvalidArgument",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "InvalidArgument",
        "message": "InvalidArgument",
        "errorLocation": "Range.insertBookmark",
        "statement": "v.insertBookmark(...);",
        "surroundingStatements": [
            "var v = context.root._getObjectByReferenceId(\"026!00000391\");",
            "// >>>>>",
            "v.insertBookmark(...);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 400,
    "line": 25,
    "column": 279164,
    "sourceURL": "https://appsforoffice.microsoft.com/lib/1/hosted/word-mac-16.00.js",
    "stack": "n@https://appsforoffice.microsoft.com/lib/1/hosted/word-mac-16.00.js:25:279164\n@https://appsforoffice.microsoft.com/lib/1/hosted/word-mac-16.00.js:25:343624\n@https://appsforoffice.microsoft.com/lib/1/hosted/word-mac-16.00.js:25:341706"
}
```

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Searion** [comment] 2023-09-22 03:41
Thanks for reporting the issue. This is by design. In this case, this error happens because insertBookmark() requires that the bookmark name is a-z characters. This is consistent with the behavior of UI.

**Comment by mikerhyssmith** [comment] 2023-09-22 08:47
@Searion Ok thats interesting - if we insert bookmarks via insertOOXML that are in that invalid format - they appear within the Word UI - you can link to them and add cross reference to them so we couldn't understand why we couldnt then access them via the Office JS ApI - but I just tried to insert via the UI and I can see that it does reject it there !


![Screenshot 2023-09-22 at 09 46 51](https://github.com/OfficeDev/office-js/assets/7879587/541c3d03-7708-4220-9b60-c6a81ebed27d)
![Screenshot 2023-09-22 at 09 46 42](https://github.com/OfficeDev/office-js/assets/7879587/c226ab6e-9bab-449d-9ecc-fb6876babc81)

**Comment by Jmuskett** [comment] 2023-09-22 08:52
@Searion there is no mention of this in the documentation of the method, just that it needs to be a string. If this is by design, would it make sense to update the documentation to make this explicit?

**Comment by Searion** [comment] 2023-09-25 05:53
@Jmuskett @mikerhyssmith  insertOOXML does not check this. we will update the documentation. By the way, the exact requirement of bookmark name is that bookmark names can be from 1 to 40 characters in length, must begin with a letter, and can only contain numbers, letters, or the underscore character — no spaces.

**Comment by ZYUN-MSFT** [comment] 2023-09-25 23:33
Hi @Rick-Kirkham , could you please assign this issue to the related doc writer to update the relevant content? For more information, please contact @Searion . Thanks.

**Comment by mikerhyssmith** [comment] 2023-09-27 10:07
Thanks @Searion  ! Shall I close this issue or will it be closed once the docs are updated ?

**Comment by ZYUN-MSFT** [comment] 2023-09-28 01:52
Hi @mikerhyssmith , please keep this issue open until the doc team updated the documents.

Thanks.

**Comment by ZYUN-MSFT** [comment] 2023-09-28 08:02
Hi @ElizabethSamuel-MSFT , could you please assign this issue to the related doc writer to update the relevant content? For more information, please contact @Searion  . Thanks.

**Comment by ElizabethSamuel-MSFT** [comment] 2023-09-28 18:23
@ZYUN-MSFT Thanks, I'll take care of this.

**Comment by ElizabethSamuel-MSFT** [comment] 2023-10-02 14:27
The doc bug fix should be published by Tuesday (October 3).

**Comment by ElizabethSamuel-MSFT** [comment] 2023-10-06 17:35
The doc bug fix was published, thx.

**Closed as completed by ElizabethSamuel-MSFT** 2023-10-06 17:35 UTC
Labels: Type: doc bug, Area: Word, Resolution: by design
