### ISSUE TITLE
Inconsistent behavior of Contextual Add-In on Outlook for Mac and Outlook for Windows

### ISSUE THREAD

**Issue by kakusharma** [OfficeDev/office-js#745] opened 2019-09-27 13:45 UTC
On Outlook for Mac 2019, the regex expression in the manifest file is not getting highlighted in the email when I wrap an anchor tag around text, even though the same is getting highlighted for Outlook 2019 on windows and on web clients.
## Expected Behavior

The Add-In behaviour should be consistent on all the supported clients. Add-In should get triggered even when I am wrapping the text with an anchor tag around it on Outlook for Mac, just like its working on other clients (Outlook 2019 Windows and web clients)
## Current Behavior

The Add-In is not getting triggered on Outlook For Mac 2019 when I wrap an anchor around the text in the email content. When I remove that anchor, its working fine.

The Add-In should get triggered on Outlook for Mac even when I am wrapping the text with an anchor tag, just like its working for other clients (Outlook 2019 windows and web)
## Steps to Reproduce, or Live Example

Manifest file:
 ```
<ExtensionPoint xsi:type="DetectedEntity">
              <Label resid="AddIn.Title" />
              <SourceLocation resid="AddIn.WebApp" />
              <Rule xsi:type="RuleCollection" Mode="And">
                <Rule xsi:type="ItemIs" ItemType="Message" />
                <Rule xsi:type="ItemHasRegularExpressionMatch" PropertyName="BodyAsPlaintext" RegExName="BodyFilter" 
                	RegExValue="CLICK TO PLAY VIDEO" Highlight="all" />
              </Rule>
 </ExtensionPoint>
```
My email content has something like:
```
<a href="http://google.com">
       <span>CLICK TO PLAY VIDEO</ span>
</ a>
```
Now, in Outlook 2019 windows and Outlook on web, the Add-In is getting triggered when I am clicking this link here (no redirection here), where as in case of Outlook For Mac 2019, the redirection is happening. Add-In window is not triggering. 

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Outlook for Mac 2019
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.29 (19090802)
* Operating System: Mac
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by kbrandl** [comment] 2019-09-29 15:00
@macOutlookExtensibility FYI, assigning to you for investigation.

**Comment by AnjanaValsan** [comment] 2019-10-03 06:59
@kakusharma , thanks for reaching out to us. We are trying to figure out the right experience here, because of the platform in-consistencies. We will keep you posted on the decision really soon.

**Comment by exextoc** [comment] 2019-10-23 15:45
@kakusharma Mac behavior is correct. We will be fixing behavior for Outlook Windows and OWA to not launch addin for URLs and email-addresses. Thanks for reporting this inconsistency.

**Comment by exextoc** [comment] 2020-03-11 13:48
@kakusharma  
The behavior for mac is correct. And is consistent throughout all the platforms now. 
We are not able to reproduce the bug anymore.
The add-in should not get triggered for URLs and email addresses, even if a regex match happens with a text wrapped in anchor tag.
Please let us know if you are facing the issue anymore.

**Closed as completed** 2020-03-30 08:00 UTC
Labels: Area: Outlook, Type: product bug, Needs: author feedback, Status: under investigation, Resolution: cannot repro, Status: no recent activity
