### ISSUE TITLE
Excel Online: tab key (for completion) doesn't work

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-js#27] opened 2017-11-08 23:09 UTC
Pressing "tab" in the IntelliSense completion list on Excel Online switches focus out of the editor and to... not sure where.

This makes it very hard to use the editor.

Coincidentally, the other shortcuts (ctrl+space, f1 for command palette, etc.) do work.

[* Only tested in Excel Online, but I assume the other Online clients will also experience the same problem]

**Comment by Zlatkovsky** [comment] 2017-11-08 23:09
Initially found via Script Lab, but is a platform issue:  https://github.com/OfficeDev/office-js/issues/27

**Comment by lindalu-MSFT** [comment] 2019-07-25 22:03
@Zlatkovsky Can you confirm this is still happening? Or has the issue been resolved? I'm trying to close out all 2017 issues, so please let me know if I can close this one or if we should open a new issue to be re-triaged. THANKS, lindalu

**Comment by Zlatkovsky** [comment] 2019-07-25 22:04
This is still an issue.  It is tracked internally by https://office.visualstudio.com/OC/_workitems/edit/3479303

**Comment by Zlatkovsky** [comment] 2019-07-25 22:04
@lindalu-MSFT :  This is still an issue. It is tracked internally by https://office.visualstudio.com/OC/_workitems/edit/3479303

**Comment by lindalu-MSFT** [comment] 2019-07-25 22:08
@Zlatkovsky Thanks for the fast response! I noticed the issue is still new/unassigned. How do we get traction on resolving this issue?

**Comment by ElizabethSamuel-MSFT** [comment] 2019-10-28 17:16
Looks like the internal bug has been fixed. Please verify if this issue can now be closed.

**Closed as completed** 2020-06-22 22:48 UTC
Labels: Area: Excel, Type: product bug
