### ISSUE TITLE
Empty context.sync is slow on mac.

### ISSUE THREAD

**Issue by peter-citeright** [OfficeDev/office-js#4812] opened 2024-08-21 14:07 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Latest
 
## Steps to reproduce

```
await Word.run(async (context) => {
                console.log({ pendingStatements: await context.debugInfo.pendingStatements });
                const t4 = performance.now();
                await context.sync();
                const t5 = performance.now();
                console.log({ timeToSync: t5 - t4 });
 });
 ```

The only pending statement is: `["var root = context.root;"]` 

yet at some points it takes up to 700ms. We do have other context syncs in other run functions in the document so not sure if that's affecting the performance, but what should we do to improve overall performance?

This 700ms overhead makes things worse especially when it comes to using `insertHtml` for content controls. Each insertion takes about 2000-3000ms.

**Comment by shanshanzheng-dev** [comment] 2024-08-22 02:18
Hi @peter-citeright  Thanks for reporting this issue. Could you tell us under what conditions might the pending duration surpass 700 milliseconds? I run this code many times, it doesn't take up to 700ms.
![image](https://github.com/user-attachments/assets/82fe0454-4515-43fd-8134-a4e01dc4c0e1)

**Comment by peter-citeright** [comment] 2024-08-30 15:14
Were you testing on mac? And we have other syncs running in parallel. For example: 

```
async function onSelectionChanged() {
        try {
            await Word.run(async (context) => {
                const document = context.document;
                const selection = document.getSelection();

                const contentControl = selection.parentContentControlOrNullObject;
                contentControl.load("id");

                document.contentControls.load("items");

                await context.sync();

                // ... do some processing
            });
        } catch (err) {
            if (process.env.NEXT_PUBLIC_APP_ENV !== "dev") {
                captureException(err);
            }
        }
    }
```

**Comment by shanshanzheng-dev** [comment] 2024-09-02 04:32
Hi @peter-citeright The issue may be caused by several reasons, such as machine config. we'll take a look and report back if we have a suggestion for you. We unfortunately have no timelines to share at this point. 
It'll be helpful if you could share us some log, Thanks.

**Comment by jipyua** [comment] 2024-10-30 01:52
hi @peter-citeright according to our discussion through mail, there should be no big perf issue on mac platform about general context.sycn loading. Please feel free to close this case. Thanks.

**Closed as completed** 2024-11-06 13:15 UTC
Labels: Needs: author feedback, Area: Word, Status: no recent activity
