### ISSUE TITLE
Cells in desktop excel will not update until I hover mouse over my taskpane, corejs v3 es.promise polyfill causing problems

### ISSUE THREAD

**Issue by paulfrench** [OfficeDev/office-js#1685] opened 2021-03-03 13:06 UTC
Everything works great in online Excel. I'm using a shared runtime since I have custom functions that make REST calls to the backend and a shared runtime is recommended by Microsoft in the docs.

## Expected Behavior
In desktop Excel (uses IE11) cells should update as soon as custom function has run

## Current Behavior
In desktop Excel cell does not update until I hover over the taskpane window

## Steps to Reproduce, or Live Example
Difficult, but if I have to I will try on request. I'll have to send you a manifest file for you to sideload and provide login details etc to the test system

## Context
Desktop behaviour is totally different to online Excel behaviour.

## Your Environment
* Windows 10 Enterprise
* Latest desktop Excel linked to Office 365 desc
* Browser Name | Internet Explorer
* Browser Version | 11.0
* Office Version | 16.0.13530.20528

I am also capturing the onSelectionChange event so that I can highligh buttons etc in the taskpane based on the context of the selected cell. This also does not work until you hover over the taskpane and it seems to then process the last event generated okay.

**Comment by AlexJerabek** [comment] 2021-03-03 17:10
Hi @paulfrench, 

Thanks for reporting this. I'll tag @grangeryy to investigate.

**Comment by AlexJerabek** [comment] 2021-03-03 17:12
Also, @paulfrench, is it possible to reproduce this issue without signing into your test environment? That would make it much easier for us to investigate what's happening.

**Comment by paulfrench** [comment] 2021-03-09 17:02
[example.zip](https://github.com/OfficeDev/office-js/files/6110110/example.zip)

I've uploaded an example. Sorry it has taken a lot of time to narrow down the issue. It seems to be due to the es.promise polyfill.

To get up and running...

npm install
npm run build
npm run dist

You do require http-server installed globally I think. Also I cheated a bit and re-use the certificate generated by another addin project ("npm run start:web") which creates you a signed SSL certificate in  %HOMEPATH%/.office-addin-dev-certs/ so yo may need to do this first.

The project holds a manifest-localhost.xml file which you can side load.

Start the addin and simply click cells, you will see if you are using online Excel in IE11 the cell clicked is reported in the taskpane. If you do the same in desktop Excel (embedded IE11) a few clicks might work and then the taskpane stops responding to cell clicks. If you hover over the taskpane the on change event is then received and processed.

To fix the code I have to remove the es.promise polyfill. To do this edit the .devolutionrc.js file and comment IN the es.promise polyfill at the bottom of the file so it get's excluded in the build. Perform the build steps again

npm run build

I use typescript to compile to ES2015 and then the devolution tool to transpile down to ES5 as well as polyfill.

**Comment by AlexJerabek** [comment] 2021-03-09 17:40
Thanks @paulfrench. We really appreciate the streamlined version.

Let me tag @keyur32 to help investigate or triage this polyfill issue.

**Comment by paulfrench** [comment] 2021-03-10 17:27
What is interesting, is my application will not render in IE11 browser (just the addin, not Excel online), I get the error 'Promise'is undefined. This is what I expect since I have no es.promise polyfill.
However the add in runs fine in IE11 when run as part of Excel online. It suggests a polyfill has been added by Microsoft? Again the addin runs fine in desktop Excel, but in this case, if I do include the es.promise polyfill then I get the issues stated above.

**Comment by grangeryy** [comment] 2021-03-17 06:32
@AlexJerabek more like IE issue for add-in, not only impact Custom Functions but also other APIs.

**Comment by keyur32** [comment] 2021-03-17 21:51
hi @paulfrench,  @lumine2008  can confirm our API behavior but I wonder if there is some part of the polyfill code that is still running, which is preventing Excel from knowing the operation is done.  Likewise, I'd suggest looking at suspend screen updating section here (and ensure if you are calling that, you are avoiding calling that in a loop): 
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/performance#suspend-screen-updating

**Comment by paulfrench** [comment] 2021-03-19 09:22
I do not suspend screen updating. The key for me is the fact that I do not require a promise polyfill when I run the addin in an Excel environment. If I try to view my addin in a browser (just as a webapp) it will not load due to Promise not being defined.

If I include es6.promise polyfill everything works fine in all environments apart from desktop Excel. If I do not include it, everything works fine in all environments but I can no longer test the addin standalone (as a simple pure webapp, no Excel environment)

Have you looked at my example? It has very little code and demos the issue? Cheers

**Comment by gingerjia** [comment] 2021-03-19 14:24
@paulfrench, let me clarify your issue first:
1.	Exclude ‘es.promise’ polyfill in his Add-in code:
a.	Add-in cannot render as a simple pure webapp in IE11 -> it’s expected since exclude the ‘es.promise’ polyfill;
b.	Add-in can render and work as expected in Excel environment (start the Add-in and click cells, you will see the cell clicked is reported in the taskpane) -> do it mean a polyfill has been added by Microsoft?

2.	Include ‘es.promise’ polyfill in his Add-in:
a.	Add-in has issue at Desktop Excel: start the Add-in and click cells, you won’t see the cell clicked is reported in the taskpane until you hover over the taskpane then the onChange event is received and processed
b.	Excel online and run as a simple pure webapp all works: start the Add-in and click cells, you will see the cell clicked is reported in the taskpane

Your paint is that the 2.a cannot trigger the on change event just after click, but need to until hover over the taskpane, am I right? 
I'm working on the local repro and will reply to you after getting reproed. And your confirmation about the issue is also very important to us to make sure get your right pain point! Thanks!

**Comment by paulfrench** [comment] 2021-03-19 17:18
You are correct.

It's worth noting that for "2.a" a few clicks may work, but then the taskpane stops responding to the clicks until you hover over it.

**Comment by gingerjia** [comment] 2021-03-20 02:21
Thanks @paulfrench for your confirm! I will let you know when have progress!

**Comment by gingerjia** [comment] 2021-03-26 05:30
@paulfrench, I tried your add-in locally and cannot repro the issue, no matter include/exclude es.promise polyfill, on Desktop Excel (IE11), the cell address can be updated correspond at Taskpane. 
You mentioned "a few clicks might work and then the taskpane stops responding to cell clicks" above, have you measured about how long will it stop work? And if you can share any repro video to us, that would be also helpful. Thanks!

**Comment by paulfrench** [comment] 2021-03-26 09:34
I'll share a video with you when I get a chance. Cheers

**Comment by MrP** [comment] 2021-03-26 11:30
I could reproduce this issue with my add in.  When including the core-js Promise polyfill I had the same issue of the task pane not responding to selection events until I hovered over the panel with the mouse.  It was doing my head in until I found this thread (Thanks @paulfrench!).  Removing the Promise polyfill fixes the issue for me as well.

I'll see if I can produce a minimal add in with the issue.

**Comment by MrP** [comment] 2021-03-26 13:39
Ah, did I say I could fix it? Not so!  Turns out removing that Promise polyfill only appears to fix it if you open the dev tools!  Before opening the dev tools it still fails to register the events.

**Comment by MrP** [comment] 2021-03-26 14:27
Right, I take it all back, what I see now is just the dev tools behaviour: With dev tools closed events don't "take", and with dev tools open they do.

**Comment by paulfrench** [comment] 2021-03-26 15:57
@MrP - I only had an issue in desktop Excel, online Excel was fine. Everything is working for me in online and desktop without the es6.promise polyfill. I would not be surprised you are seeing the same issue but a slight variation?

@gingerjia - yes only a few clicks in desktop Excel and then I saw an issue. It seems to reset itself sometimes and mostly resets itself if you hover over the taskpane. I'll sort out a video at some point

**Comment by paulfrench** [comment] 2021-03-26 16:00
It's worth adding I transpile down to two lots of code, one for modern browsers and one for IE11. So no polyfills are included for the modern browsers. I had to remove es6.promise polyfill for IE11

**Comment by MrP** [comment] 2021-03-26 16:58
I got it to work by adding `setInterval(30000, () => {})` to my `onReady`.

I found that workaround here: 

https://github.com/OfficeDev/office-js/issues/521#issuecomment-502944107

Note that for me `setInterval(()=>{}, 30000)` does not help, only the "wrong" argument order helps.

I have no idea what's going on!

**Comment by paulfrench** [comment] 2021-03-26 17:57
> I got it to work by adding `setInterval(30000, () => {})` to my `onReady`.
> 
> I found that workaround here:
> 
> [#521 (comment)](https://github.com/OfficeDev/office-js/issues/521#issuecomment-502944107)
> 
> Note that for me `setInterval(()=>{}, 30000)` does not help, only the "wrong" argument order helps.
> 
> I have no idea what's going on!

Yeah that makes no sense, that will throw a javascript error. Maybe just try and throw an error. It's looking like some horrible race condition and timing issue. Don't know, very strange. Why promises exist in IE11 Desktop Excel without me adding the polyfill is a mystery to me. I know that is the case since my taskpane will start in a browser and does not require office.js to run and display. Yet if I do this in IE11 I get an error saying Promise is not defined. So something in IE11 desktop Excel is defining "Promise" somewhere!

**Comment by MrP** [comment] 2021-03-26 18:25
The promise polyfill comes from office.js itself.  Apparently, it uses MutationObserver internally if available.  Which in IE11 it is, but apparently it's buggy and sometimes it gets "stuck".  I think that's where the weird hovering behaviour comes from.

That could also explain why opening F12 fixes it for me.  It must do something that "unsticks" that MutationObserver.  Or something.

What I can't explain is why setInterval(30000, ()=>{}) would also have that "unsticking" effect for MutationObserver.  It doesn't throw an error or anything.  Yes, I tried causing an error there, by calling 30000 as a function even.  Nothing.

The better workaround is to set MutationObserver=null before the proise polyfill has a chance to see it, so it doesn't use it.  But my app actually uses it, so I can't just ditch it.

I learned all that from the other issues linked, but it took me a while to find them, so I'm saying all of that here in case other people with the same problem find this issue.

**Comment by gingerjia** [comment] 2021-03-29 06:33
Thanks @MrP  and @paulfrench!

@paulfrench may I know the workaround [setInterval(30000, ()=>{})] or [set MutationObserver=null] also work for you?
![image](https://user-images.githubusercontent.com/62282034/112794383-62fbd780-9099-11eb-99d8-f437cb3bc972.png)

For @MrP 's question that 'why setInterval(30000, ()=>{}) would also have that "unsticking" effect for MutationObserver.', when we debug, we found the events are not lost. They are just held in the web view or JS side and are triggered when user hovers on task pane. We just suspect this issue is caused by your Promise polyfill, and due to some reasons they didn’t schedule the task and caused the Promise is not resolved. Add `setInterval(3000, () => {})` in the initialization function that the web view or your Promise polyfill may be somehow active.

**Comment by paulfrench** [comment] 2021-04-13 10:11
I cannot add...

`setInterval(3000, () => {})` since it gives a TypeScript error (obviously)

I've added back in the es.promise polyfill

I've added `setInterval(() => {},3000)` to my code so it reads....

Office.onReady(() => {
  setInterval(() => {},3000)
  if (typeof Excel !== 'undefined') {
    Excel.run(async (context) => {
      await registerSelectionChangeHandler(context)
    }).catch(errorHandlerFunction);
  }
});

Now it sort of works but the events only get processed every 3 seconds. If I click cells, it depends when setInterval fires before the event is processed. So I can either reduce the interval or leave out the es.promise polyfill. I've chosen to leave out the es.promise polyfill and remove the setInterval since it performs better.

It would be nice this was fixed properly so I could include the es.promise polyfill and so can test the UI outside of Excel.

**Comment by gingerjia** [comment] 2021-04-14 03:49
hi @paulfrench, thanks for your confirm! 
Have you also confirmed '[set MutationObserver=null]' works or not?

This is IE’s problem and IE’s bug unlikely gets fix since it’s in deprecating stage. Once our add-in platforms migrates to webView2, such problem should be resolved.

If has any other concern, please let us know!

**Comment by lliu113** [comment] 2021-05-10 22:01
@paulfrench - it seems like you're unblocked, so I'll go ahead and close this issue. Please feel free to reactivate if you have any additional questions/concerns. Thanks!

**Closed as completed by lliu113** 2021-05-10 22:01 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: add-in UI, Resolution: has workaround, Area: custom functions

**Comment by paulfrench** [comment] 2021-05-11 08:11
Yes I'm unblocked but set MutationObserver=null did not work for me. other things went wrong. I did not have time to dig further. I simply do not include the promise polyfill for IE11 or Old Edge and all is okay for me.
