### ISSUE TITLE
After create new dialog, it contains event handlers from previous dialog which was closed by dialog.close() call on Mac for outlook

### ISSUE THREAD

**Issue by alexnb11** [OfficeDev/office-js#297] opened 2018-11-12 20:19 UTC
If we creates new dialog window with event handler for it and then close it (call dialog.close()), second created dialog window will contains event handlers from previous dialog. The bug reproduces only in outlook client, mac os.

## Expected Behavior
1. Call Office.context.ui.displayDialogAsync for create new dialog window and set event handler function for this dialog window. 
2. On the dialog window call Office.context.ui.messageParent function and send message. 
3. Parent window handles message and close dialog, calls dialog.close(). 
4. Open new dialog again, call Office.context.ui.displayDialogAsync and set event handler function for this dialog window. 
5. On the dialog window call Office.context.ui.messageParent function
6. Parent window will handle this message **ONCE**.

## Current Behavior
1. Call Office.context.ui.displayDialogAsync for create new dialog window and set event handler function for this dialog window. 
2. On the dialog window call Office.context.ui.messageParent function and send message. 
3. Parent window handles message and close dialog, calls dialog.close(). 
4. Open new dialog again, call Office.context.ui.displayDialogAsync and set event handler function for this dialog window. 
5. On the dialog window call Office.context.ui.messageParent function
6. Parent window will handle this message **TWICE**.
Dialog contains more than one event handlers.

## Steps to Reproduce, or Live Example
I created small outlook plugin for demonstrate this bug. Plugin called 'dialogBug'. [dialogBug link to github](https://github.com/alexnb11/office-js-dialog-handler-bug-mac-os)

* Additional details:
  [Video](https://www.youtube.com/watch?v=O-Xskhwaenw&feature=youtu.be)  which demonstrates this bug via my 'dialogBug' plugin.

## Context
This bug restricts people who use office.js library. Developers can not handle messages from dialog correctly in mac os. As temporary solution, I just create global variable (var mutex) and use it for avoid race condition in my code.
I'm working with outlook plugin for our corporative application. And this bug makes problem for my code.

## Your Environment
* Platform Mac
* Host Outlook client
* Outlook version number: 16.18 (181014)
* Operating System: Mac

**Comment by hengchengfei** [comment] 2018-11-13 01:13
`clickEvent.completed();`

**Comment by alexnb11** [comment] 2018-11-13 09:24
Hi, **hengchengfei**. What is it? What do you mean? I can not find any mentioning about it in documentation.

**Comment by hengchengfei** [comment] 2018-11-14 07:54
<img width="588" alt="1" src="https://user-images.githubusercontent.com/3182964/48468214-31667680-e826-11e8-9afd-01e8e966cd55.png">

**Comment by alexnb11** [comment] 2018-11-14 11:29
No, @hengchengfei , in our case we don't use 'ExtensionPoint' for open dialog window. We don't have instance of event. We just transfer event handler function in Office.context.ui.displayDialogAsync call. And make this call not from 'OfficeTab' panel, we do it from index.html page. (There is our manifest file https://github.com/alexnb11/office-js-dialog-handler-bug-mac-os/blob/master/manifest.xml#L113)

**Comment by dmahugh** [comment] 2018-11-26 22:47
Thanks for reporting this issue, @alexnb11. @macOutlookExtensibility, can you take a look?

**Comment by alexnb11** [comment] 2018-11-27 08:14
@dmahugh Thank you for supporting. I'm waiting a resolution, it is important for my work.

**Comment by kbrandl** [comment] 2018-12-05 18:36
@macOutlookExtensibility are you able to provide an update on this issue?

**Comment by heydanhey** [comment] 2019-02-24 14:27
I'm having the exact same issue using the dialog in Word.

**Comment by alexnb11** [comment] 2019-08-09 12:35
@kbrandl @macOutlookExtensibility Any updates about this bug???

**Comment by alexnb11** [comment] 2019-09-18 11:37
@kbrandl  Any updates?

**Comment by kbrandl** [comment] 2019-09-18 13:55
@alexnb11 apologies for the delay on this -- @macOutlookExtensibility is the one who'll need to investigate and provide feedback on this (as it's not my area of expertise.) 

@macOutlookExtensibility can you please provide an update on this issue?

**Comment by alexnb11** [comment] 2020-05-20 13:44
@kbrandl @macOutlookExtensibility Can we use additional resources for fix this problem? It is continuing more then 1 year. It looks strange for me, employees of Microsoft can not fix official bug for 1 year.

**Comment by exextoc** [comment] 2020-08-04 17:38
Sorry for the delay in response. We are not able to reproduce the bug. The add-in provided seems to have stopped working. Please let us know if the issue is still persistent.

**Comment by alexnb11** [comment] 2020-08-10 08:15
@exextoc Hi, I checker, it is still persistent.

**Comment by alexnb11** [comment] 2020-08-10 08:16
@exextoc you can see this bug on macbook only.

**Comment by exextoc** [comment] 2020-08-12 11:48
@alexnb11 Apologies for delay in response. We tested this again on our end with Outlook Mac (version: 16.41 (20081001), we are not able to reproduce this issue. We used your addin from GitHub for this testing. 

Thanks for uploading repro addin on GitHub for this purpose.

Are you testing with latest version of Outlook? What version you are using?

**Comment by alexnb11** [comment] 2020-08-12 12:35
@exextoc I just have checked it again. It works well. So looks like it was fixed. I think we can close this bug. Thank you.

**Comment by exextoc** [comment] 2020-08-12 12:40
Thanks @alexnb11 for confirming. Closing this issue.

**Closed as completed by exextoc** 2020-08-12 12:40 UTC
Labels: Area: Outlook, Type: product bug, Status: fixed
