### ISSUE TITLE
Cannot sideload Outlook web add-ins in current Outlook on the Web - interface has changed again

### ISSUE THREAD

**Issue by neville-jones** [OfficeDev/office-js#3675] opened 2023-09-04 23:42 UTC
Outlook on the Web seems to have changed overnight (early September 2023) in how Apps are managed and there does not seem to be a way to sideload an add-in anymore.

The new interface only shows apps "Built for your organisation" and ones from the store. I can't find a button or any means to sideload an add-in (load 'custom add-in').

Subsequently, the instructions on this page are no longer correct and require assistance on how to side-load Outlook add-ins into Outlook on the Web.

![2023-09-05_9-36-23](https://github.com/OfficeDev/office-js-docs-pr/assets/62081302/eafb5a7f-e0f6-4c6a-b5af-2f44e925e41b)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f364ae0-b7dd-edb3-b51b-8f6d0d99afbe
* Version Independent ID: 7dd1ce8f-16e7-88f8-f291-4afbe76baba7
* Content: [Sideload Outlook add-ins for testing - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=web)
* Content Source: [docs/outlook/sideload-outlook-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/sideload-outlook-add-ins-for-testing.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2023-09-05 16:59
Hi @neville-jones,

Can you please try [this link](https://aka.ms/olksideload)? It's mentioned in the "Important" box on the sideloading page, but those can be easy to overlook.

That link should open a familiar looking window.  Go to "My add-ins", then select the "Add a custom add-in" option.

Please let me know if that unblocks you.

**Comment by neville-jones** [comment] 2023-09-13 02:12
I have had mixed success with the use of the link - https://aka.ms/olksideload

The add-in certainly appears then under My add-ins > Custom Addins in the traditional Add-Ins for Outlook UI, but if I return to the Outlook on the Web UI and create a new message the add-in is not always visible or operational. Sometimes it has worked, sometimes it has worked after clicking the browser's Reload/Refresh button, sometimes I have had to sign out, close browser and sign back in, and sometimes I cannot get it working at all. I am yet to have a reliable sequence which ensures the add-in has been sideloaded in Outlook. This is despite it being listed under "Custom Addins" of the traditional UI if I open it again; if I use the new add-ins UI it is not visible there:

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/62081302/6401e7d4-29f6-426d-a173-246968094a36)

**Comment by AlexJerabek** [comment] 2023-09-13 15:46
Thanks for the response @neville-jones. I'm going to transfer this to the office-js repo and have it investigated as a product issue.

**Comment by exextoc** [comment] 2023-09-13 16:38
@neville-jones 
Due to caching, it may take up to four hours for the sideloaded add-in to appear in your Outlook client on the web.


https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=web

We are aware of the issue and actively working in resolving it.

**Comment by bas-eenhoorn** [comment] 2023-09-26 15:43
For me this works best to install an add-in:

Open Outlook Desktop and press this:
![image](https://github.com/OfficeDev/office-js/assets/98084438/c2ffe001-549b-459f-9732-0c8c0828783f)

Then a browser will be opened, and it will open the 'unopenable' original upload screen :)
![image](https://github.com/OfficeDev/office-js/assets/98084438/08a685e4-72ae-4d9e-b78c-98db61bf61fb)

**Comment by mlbyas458** [comment] 2023-10-03 16:26
@exextoc loading the add-in from the admin console is also not showing up for us. Is that related to the caching issue?

**Comment by exextoc** [comment] 2023-10-05 11:00
Get-Addins button has been removed, and we are recommending to sideload addins by going to this URL directly.  https://aka.ms/olksideload

More details are available in the documentation here:  https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=web#sideload-manually

Please note, Due to caching, it may take up to four hours for the sideloaded add-in to appear in your Outlook client on the web.

**Closed as completed** 2023-10-12 13:53 UTC
Labels: Area: Outlook, Needs: author feedback, Resolution: question answered

**Comment by mlbyas458** [comment] 2023-10-13 14:32
Add from URL... is disabled on in my tenant when using https://aka.ms/olksideload Is this on purpose? Could this be a setting that changed in the admin center that causes this?
![UrlDisabled](https://github.com/OfficeDev/office-js/assets/58475700/d8e39940-28b4-43d2-810d-ab9d212a033a)

**Comment by omar-pk** [comment] 2023-10-13 14:47
@mlbyas458 This was confirmed this morning as intentionally disabled. See https://github.com/OfficeDev/office-js/issues/3745#issuecomment-1761194542.
