### ISSUE TITLE
Calling `body.getHtml()` twice results in RichAPI.Error on Web

### ISSUE THREAD

**Issue by nickolasfisher** [OfficeDev/office-js#2967] opened 2022-11-11 15:01 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: N/A
* Operating System: Windows 10 and Windows 11
* Browser (if using Office on the web): Tested in Chrome, Firefox, and Edge.  All Failing
 
## Expected behavior

There is functionality in our app that reads the HTML of the word doc and does some processing.  There is functionality that allows the user to refresh our app by reading that HTML again.  When `context.sync()` is called after calling `context.document.body.getHtml()` we should receive the HTML of the document back. 

## Current behavior

This refresh is when we see the error.    If the app called `context.document.body.getHtml();  context.sync();` twice there is a `RichApi.Error`.

## Steps to reproduce

I have put up a minimal app [on github here](https://github.com/nickolasfisher/WordAddinFailing)

1. Start the application with `npm start:web`
2. Open the document `richapi-error.docx` found in the gitrepo under the `sampledocs` directory
3. Click the **Run** Button.  Note that `Hello World` is added to the end and there is no error
4. Click the **Run** Button again and note the RichAPI error in the console.

## Link to live example(s)

1. Github repo linked above

# Provide additional details

N/A

## Context

There is refresh functionality that currently doesn't work.  At this time it is not critical however we are developing a new feature that will make greater use of the Refresh functionality and this will become blocking shortly.  

## Useful logs

- [ x ] Console errors
- [ x ] Screenshots
- [ x ] Test file (if only happens on a particular file)

```
RichApi.Error: Sorry, something went wrong. Check the OfficeExtension.Error.debugInfo for more information. 
    at new n (word-web-16.00.js:25:324761)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:388927)
    at word-web-16.00.js:25:386990
```
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'message')
    at Object.n [as Error] (word-web-16.00.js:25:324794)
    at taskpane.js:44:37
n @ word-web-16.00.js:25
(anonymous) @ taskpane.js:44
```

![image](https://user-images.githubusercontent.com/56088064/201366636-00ed5cdb-eb56-43e5-aaf6-dd6b742f2444.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment] 2022-11-14 09:46
@nickolasfisher 
Our colleague reproduced this issue successfully. Now we have an ADO #7126082 to track this. 
We will update here if progress is made.
Thanks for reporting this issue.

**Comment by xiruatms** [comment] 2024-03-07 08:35
@nickolasfisher , are you still encounter this please? Seems I can't repro it now.

**Comment by nickolasfisher** [comment] 2024-03-07 13:54
@xiruatms  i don't work on this project anymore so I cannot say.  Apologies

**Comment by RuizhiSunMS** [comment] 2024-04-18 09:09
Close this bug since the owner doesn't focus on this anymore as well as our colleagues can't reproduce it. For anyone who get trouble in this, please feel free to reopen it and reach out to us.

**Closed as completed by RuizhiSunMS** 2024-04-18 09:09 UTC
Labels: Area: Word, Resolution: cannot repro
