### ISSUE TITLE
Cannot deploy Outlook add-in via Admin Panel due to Itemsend in manifest?

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#3151] opened 2023-02-14 15:41 UTC
# Provide required information needed to triage your issue
Just recently, it seems something has changed in the validation of the manifest when deploying an add-in via Admin Panel. I use to be able to upload our manifest, which contains an ItemSend configuration, without any issues (which I should be able to -- that's the recommended approach since we can't deploy to the Store).

**This is an urgent bug that needs to be fixed.**

![image](https://user-images.githubusercontent.com/7740624/218784383-0d74777a-44cf-4cc5-a53c-1220c8397be4.png)

## Expected behavior
I can upload an add-in manifest that contains ItemSend configuration via the Admin Panel.

## Current behavior
I receive an "Invalid manifest" error (see screenshot) when uploading our manifest that has worked as recently as a week or two ago.

## Steps to reproduce
1. Attempt to install an add-in manifest that has an itemSend configuration defined  via the Admin Console "Integrated Apps" page (as recommended in the documentation) (ex. https://cdn.virtru.com/outlookjs/manifest/VirtruForOutlook.xml)
2. See error about Invalid manifest.

## Context
We just deployed an update to our add-in today and it requires our customers to update the manifest via the Admin Panel in order to get the latest manifest with Shared Mailbox support. They cannot do this now because of the invalid error.

We tested this same manifest 1-2 weeks ago and it worked fine. Something has changed in the validation process that is breaking this on Microsoft's side. This is absolutely urgent!

**Comment by cody-lettau** [comment] 2023-02-14 15:43
@exextoc @AlexJerabek can we please escalate this?

**Comment by cody-lettau** [comment] 2023-02-14 15:50
You can see here that I deployed the same or similar (always have had the ItemSend in it) many times:
![image](https://user-images.githubusercontent.com/7740624/218788316-89e76c3e-5963-47ac-9c63-a37c077fa7de.png)

**Comment by cody-lettau** [comment] 2023-02-14 15:53
Seems like a potential duplicate of https://github.com/OfficeDev/office-js/issues/3092

**Comment by t-miyake** [comment] 2023-02-14 15:58
I have the same problem.
I have confirmed that multiple tenants are experiencing the same problem.

Also, some tenants were still able to deploy from Add-ins in the Microsoft 365 admin center.

Add-ins in the Microsoft 365 admin center
https://admin.microsoft.com/?source=applauncher#/Settings/AddIns

We are also very troubled by the sudden inability to do what we have been able to do in the past.

**Comment by JuaneloJuanelo** [comment] 2023-02-14 22:46
its a dupe.. fix is in, lets wait for rollout.

**Comment by exextoc** [comment] 2023-02-15 05:38
Removing @exextoc from assignees since @AkhileshShah-MS is the assignee on the dupe bug. Do tag us back if we need to follow up.

**Comment by JuaneloJuanelo** [comment] 2023-02-16 22:13
The fix was approved, and we expect it to be available in production within the next 4 days.

**Comment by jp-ayyappan** [comment] 2023-02-21 20:49
Is this fix released?

**Comment by AkhileshShah-MS** [comment] 2023-02-22 04:40
Hi @jp-ayyappan - This fix has been released. Requesting you to validate on your end and let us know if you face any issues. Thanks for your patience on this!

**Comment by cody-lettau** [comment] 2023-02-22 14:04
This looks to be fixed in our test organization. Thanks for notifying us that it was released @AkhileshShah-MS

**Comment by AkhileshShah-MS** [comment] 2023-02-24 09:40
Thanks for the confirmation. Closing this issue.

**Closed as completed by AkhileshShah-MS** 2023-02-24 09:40 UTC
Labels: Status: fixed, Area: Centralized Deployment
