### ISSUE TITLE
Creating 10000 names in a worksheet cause Excel online to throw an exception

### ISSUE THREAD

**Issue by GeorgeHung** [OfficeDev/office-js#726] opened 2019-09-13 16:04 UTC
Creating 10000 names in a worksheet cause Excel online to throw an exception
## Expected Behavior

According https://support.office.com/en-us/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3, the limitation of names in a workbook depends on available memory.  I can create 1000 names in ten different worksheets in Excel online.  Therefore, I except that I should be able to create 10000 names in a worksheet.

## Current Behavior

When I tried creating 10000 names in a worksheet, an exception was thrown in Excel online..  However, when I tried creating 1000 names in ten different worksheets, I didn't see any exception.

## Steps to Reproduce, or Live Example
1.  Open a new workbook in Excel online.
2.  Open Script lab
3.  Import sample from https://gist.github.com/GeorgeHung/bc99c1bdd0a5ef14ac11e38faad040d1
4.  In the input box, enter "10000" and then hit "Run"
5.  An exception will show in the console

* Link to live example: https://gist.github.com/GeorgeHung/bc99c1bdd0a5ef14ac11e38faad040d1

## Context

We tried to store trackable metadata in cells.  Before range.id is supposed, we are using comments in a named range to store those data.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Oline
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Browser (if using Office Online): Safari

## Useful logs

Start Creating Names at Fri Sep 13 2019 09:04:25 GMT-0700 (PDT)

[ERROR]: Error:
{
    "message": "An internal error has occurred.",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "An internal error has occurred."
    },
    "line": 24,
    "column": 279886,
    "sourceURL": "https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js",
    "stack": "c@https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:279886\nprocessRequestExecutorResponseMessage@https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:337777\nhttps://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:336172\npromiseReactionJob@[native code]"
}

**Comment by catchingyu** [comment] 2019-09-17 03:26
@lumine2008  to take a look

**Comment by lumine2008** [comment] 2019-09-17 03:28
This is expected behavior, as the excel online payload size is 5MB for each call, so please try to separate into 2 calls.

**Comment by kbrandl** [comment] 2019-09-17 16:58
Closing this as "by design" per @lumine2008's feedback above. @GeorgeHung please let us know if you have any follow-up questions re @lumine2008's suggestion. Thanks!

**Closed as completed by kbrandl** 2019-09-17 16:58 UTC
Labels: Area: Excel, Resolution: by design
