### ISSUE TITLE
[Reliability] Office.ready and Office.initialize not being triggered on Add-in reload. Culprit: Office.context.document.settings.set

### ISSUE THREAD

**Issue by 3dot1four** [OfficeDev/office-js#724] opened 2019-09-12 06:27 UTC
## Expected Behavior

On reload Add-in after saving value stored in below file via 'Office.context.document.settings.set' Add-in should trigger Office.ready or Office.initialize 
## Current Behavior

Office.ready or Office.initialize not being triggered.

## Steps to Reproduce, or Live Example

It's very easy to repro. 

1. Create a content Add-in from Visual studio template
2. Store content in the below file using Office.context.document.settings.set
[Content file URL](https://microsoft-my.sharepoint-df.com/:t:/p/rohgupta/Ecoi38v99-RPjCkp-GETTd4Bpnlgmri5EsOKkNDb4sZbWg?e=GdDiah)
3. Call Office.context.document.settings.saveAsync
4. Reload Add-in

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 12111.20000
* Operating System: Windows 10
* Browser (if using Office Online): NA

**Comment by AlexJerabek** [comment] 2019-09-12 16:22
Thanks for reporting this @rohitrewa and thank you @mandyt-Git for investigating.

**Comment by MandytMSFT** [comment] 2019-09-17 10:13
@rohitrewa  I tried the scenario you show me last week, seems it can be saved successfully in my side. So I suspect there happen to have some special characters in your string, could you help try again and send me the string you are using then I can help identify from API side to see what the cause is.

I have attached repro video in our email thread for your reference

**Comment by 3dot1four** [comment] 2019-09-21 17:03
Had an offline discussion with @mandyt-Git and she has to come back with her investigation.

**Comment by MandytMSFT** [comment] 2019-09-27 03:39
Root cause has been figured out.  it's related to edge webview, switching back to IE webview works. Log BUG 3670903 for internal track and assign this issue to @jargil

**Comment by jargil** [comment] 2019-10-11 19:41
@rohitrewa - this is unfortunately a bug in how Edge is parsing your string. The same can be reproduced directly on the Edge browser if you simply try to assign your sample data to a random variable. There's not much that can be done from Office's side.
It does not seem to be related to the length of the string, but simply that Edge complains that the constant is unterminated. I'm not sure how you get into storing this kind of data for your add-in scenarios, but my only suggestion is figuring a way to cleanup your data so that Edge works.

Note that the same string problem can be reproduced with IE, however you don't experience this problem when Office uses IE because the way IE and Office communicate is different. Check bug 3670903 for more details.

Closing as there's not more we can do from our side. Feel free to ping me if you need more information.

**Comment by MandytMSFT** [comment] 2019-10-12 10:55
@jargil i think there are some misconception on the issue. The real problem is Office.ready or Office.initialize will not be triggered after switching to Edge webview even with normal string. I have reactivated the bug, pls help take a look

**Closed as completed** 2019-10-12 15:41 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: add-ins platform
