### ISSUE TITLE
saveCustomPropertiesAsync on Event Occurrence raises error when sending a series master update Windows Desktop Only

### ISSUE THREAD

**Issue by gummybuns** [OfficeDev/office-js#1566] opened 2020-12-23 19:49 UTC
**In Windows Outlook Desktop Only**
1. Create a recurring event
2. Open an occurrence -> save a custom property on the occurrence
3. Open series master -> edit the title -> send

## Expected Behavior
It sends and updates the series

## Current Behavior

It shows an error suggesting the event failed to update, although the update does actually get sent.

![Screenshot 2020-12-22 at 14 36 16](https://user-images.githubusercontent.com/47437711/103031857-83a11800-4513-11eb-8185-72603528b614.png)

We have tested this in the Webapp and Mac Desktop. This problem only occurs in the Windows Desktop
## Steps to Reproduce, or Live Example

1. Create a recurring event
2. Open a occurrence. Open an add-in that calls `saveCustomPropertiesAsync`
3. Close the occurrence
4. Open the seriesMaster. Edit the subject. Click Send
5. See the alert dialog
 
## Context

The alert makes it seem as if the event failed to update and send, confusing users. ideally changing custom properties on occurrences does not throw any errors when updating the series master

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 365 MSO (16.0.13426.20330)
* Operating System: Windows 10 + Windows 8.1
* Browser (if using Office on the web): ______

**Comment by exextoc** [comment] 2020-12-24 00:08
We are unfortunately unable to reproduce the issue. Is there maybe a step missing in between the repro steps? Once you open the occurrence of a recurring meeting and set customProperty, do you save the item or send an update or simply hit 'x' to close the item without hitting save/send? Also, could you try using ScriptLab for Outlook from App Store (hit Get Add-ins and search for ScriptLab. Within this addin there is already a sample snippet for Custom Properties that you can use) to set the custom property and confirm if you can still reproduce the issue?

**Comment by gummybuns** [comment] 2020-12-24 00:55
Thanks for responding, I tried to create a very basic application that only sets custom properties. I agree that it is not reproducible under normal circumstances. There is something that our application is doing or some sort of race condition that is causing this problem for us

**Comment by gummybuns** [comment] 2020-12-24 01:55
It seems to happen when `Office.context.mailbox.item.saveAsync` and `customProperties.saveAsync` are called in parallel

![Kapture 2020-12-23 at 17 20 28](https://user-images.githubusercontent.com/47437711/103048405-61bf8980-4543-11eb-8233-e5aea9958857.gif)

I will work on trying to include the source code into a single file

**Comment by gummybuns** [comment] 2020-12-24 02:13
```jsx
import 'core-js/stable';
import * as React from 'react';
import { render as reactDOMRender } from 'react-dom';


const Content = () => {
  const [isCustomPropertySet, setIsCustomPropertySet] = React.useState(false);

  React.useEffect(() => {
    Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {
      const customProperties = result.value;
      if (customProperties.get('testProperty')) {
        setIsCustomPropertySet(true);
      }
    });
  });

  const handleClick = async () => {
    Office.context.mailbox.item.saveAsync((result) => {
      console.log(result.value);
    });
    Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {
      const customProperties = result.value;
      customProperties.set('testProperty', 'hello');
      customProperties.saveAsync((res) => {
        if (res.status === Office.AsyncResultStatus.Succeeded) {
          setIsCustomPropertySet(true);
        }
      });
    });
  };

  return (
    <div>
      <p>
        Custom Property Set:
        {isCustomPropertySet ? ' yes' : ' no'}
      </p>
      <button
        type="button"
        onClick={handleClick}
      >
        Set CustomProperty
      </button>
    </div>
  );
};

const run = async () => {
  await Office.onReady();

  const rootElement = document.getElementById('container');
  reactDOMRender(<Content />, rootElement);
};

run();
```

i will also try to follow the instructions for ScriptLab, this was just easier to show

**Comment by gummybuns** [comment] 2020-12-28 19:38
To take it one step further, i am also noticing that when calling `item.saveAsync` and `customProperties.saveAsync` sequentially is reproducing this issue. Here is a different `handleClick` that causes the same problem for me:

```javascript
  const handleClick = async () => {                                              
    Office.context.mailbox.item.saveAsync((saveAsyncResult) => {                 
      if (saveAsyncResult.status === Office.AsyncResultStatus.Succeeded) {       
        Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {      
          const customProperties = result.value;                                 
          customProperties.set('testProperty', 'hello');                         
          customProperties.saveAsync((res) => {                                  
            if (res.status === Office.AsyncResultStatus.Succeeded) {             
              setIsCustomPropertySet(true);                                      
            }                                                                    
          });                                                                    
        });                                                                      
      }                                                                          
    });                                                                          
  };
```

**Comment by exextoc** [comment] 2020-12-28 21:54
Thank you for reporting this issue. This has been put in our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: Office:4742730

**Comment by gummybuns** [comment] 2020-12-29 00:50
One of the reasons we are using `item.saveAsync` is old versions of Outlook Clients prior to requirement set 1.8 do not have a `Office.context.mailbox.item.getItemIdAsync` method in the Calendar

My understanding is the workaround to getting the item id in these old versions is to call `saveAsync` and get the id in the callback. Is there a different way to get the itemId for these older versions?

**Comment by JuaneloJuanelo** [comment] 2021-04-09 20:26
Unfortunately that the only workaround we have at this point. The workaround is to create a custom property before calling save you you can get the item id. Btw we followed up offline and it seems that you moved away from this approach, still given that there is a workaround for this issue we are closing it now.

**Closed as completed by JuaneloJuanelo** 2021-04-09 20:26 UTC
Labels: Area: Outlook, Status: in backlog
