### ISSUE TITLE
toJSON always returns empty object when called on Collection object

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js#178] opened 2018-06-26 20:53 UTC
## Expected Behavior: 

SOME-OFFICE-OBJECT`Collection.toJSON` should return an object with an `items `property which is an array of SOME-OFFICE-OBJECT`Data` objects. 

## Current Behavior:

The object returned is empty. It has no `items `property.

## Steps to Reproduce, or Live Example:

Use this code:

```
    await Excel.run(async (context) => {
        const sheets = context.workbook.worksheets;
        sheets.getLast().tabColor = "yellow";
        sheets.load("name, tabColor");
        var s = sheets.toJSON();

        await context.sync()
        console.log(sheets.items[0].name); // "Sheet1"
        console.log(s.items);                        // undefined
        console.log(s);                                 // empty object
        console.log(JSON.stringify(s));        // "{}"
    });
```

## Your Environment:

* Platform: PC
* Host: Excel
* Office version number: 1807 10320.20003
* Operating System: Windows

**Comment by JuaneloJuanelo** [comment] 2018-06-29 20:55
@Zlatkovsky  can you please take a look?

**Comment by Zlatkovsky** [comment] 2018-07-11 16:12
This is by design.  We wanted to have the object only return it's own properties, and the properties of objects closely-related to it.  Otherwise, if you do a `toJSON` on a workbook where you've loaded both `name` and something on the `worksheet` collection, you would get this giant list of properties, that are a step removed from you.

Another way of looking at it:  we wanted ".set" and ".toJSON" to be symmetrical.  Since we wouldn't have "set" apply to child objects, we didn't want "toJSON" to return them either.

**Comment by Rick-Kirkham** [comment] 2018-07-19 23:45
@Zlatkovsky 
This is what the toJSON signature in d.ts looks like for Collection objects (in this case WorksheetCollection. 
` toJSON(): Excel.Interfaces.WorksheetCollectionData;`
The interface declaration is:
```
/** An interface describing the data returned by calling "worksheetCollection.toJSON()". */
        interface WorksheetCollectionData {
            items?: Excel.Interfaces.WorksheetData[];
```
From what you've said, these seem to be completely wrong. Can you confirm that?
Also, does the WorksheetCollectionData interface even need to exist? 
Also, should toJSON even be defined for Collection classes?

**Comment by JuaneloJuanelo** [comment] 2018-07-23 22:17
closing again.. this sounds like a discussion we can have internally.
by design.

**Closed as completed by JuaneloJuanelo** 2018-07-23 22:17 UTC
Labels: Area: add-ins platform

**Comment by Zlatkovsky** [comment] 2018-08-01 22:53
Just tested it out.  It looks like the issue was that you were calling "toJSON()" too early.
"toJson" will only reflect the currently-loaded state of the object.  As such, you need to do it after `await context.sync()`.

This example will work:

    await Excel.run(async (context) => {
        const sheets = context.workbook.worksheets;
        sheets.getLast().tabColor = "yellow";
        sheets.load("name, tabColor");

        await context.sync()
        console.log(sheets.items[0].name); // "Sheet1"
        console.log(sheets.toJSON());
        console.log(JSON.stringify(sheets, null, 4));
    });
