### ISSUE TITLE
"Admin Managed" add-ins not usable when third-party cookies are blocked

### ISSUE THREAD

**Issue by christian-sap** [OfficeDev/office-js#1958] opened 2021-06-25 05:38 UTC
# Provide required information needed to triage your issue
If you block the third-party cookies in your browser (for example in Chrome or Edge) then the "Admin Managed" Add-ins can not be used anymore.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows
* Browser (if using Office on the web): Chrome, Edge
 
## Expected behavior
Admin Managed Add-ins should work in Excel Online even if third-party cookies are blocked in the browser.

## Current behavior
Admin Managed Add-ins do not work.

## Steps to reproduce
1. Block third party cookies in your browser (e.g. Chrome, Edge)
2. Launch Excel Online
3. Go to "Insert" -> "Office Add-ins" -> "Admin Managed"

When third party cookies are blocked the admin managed add-ins are not shown in the dialog (see attached video). 

## Link to live example(s)
See attached screen cams. One is where third party cookies are allowed and one is with blocked third party cookies.

## Useful logs
I see the following error in the console which could be the root cause of the issue:
"Refused to display 'https://login.microsoftonline.com/' in a frame because it set 'X-Frame-Options' to 'deny'."

**Comment by christian-sap** [comment] 2021-06-25 05:39
https://user-images.githubusercontent.com/79985386/123375049-6b748900-d588-11eb-9b42-a2d3eba96e9f.mp4


https://user-images.githubusercontent.com/79985386/123375060-70393d00-d588-11eb-8106-d63952809ce6.mp4

**Comment by lindalu-MSFT** [comment] 2021-06-25 17:12
Thanks for the useful videos showing how to repro. I've assigned to @keyur32 to help triage this!

**Comment by christian-sap** [comment] 2021-07-23 12:50
Hi @keyur32  and @lumine2008 , did you have time to check this issue? It is a complete blocker of using admin managed add-ins when customers have blocked third-party cookies in the browser.

**Comment by keyur32** [comment] 2021-07-23 19:53
Thank you for the report and apologies for the inconvenience. We can repro and team is investigating this limitation. Internal tracking #: 4774608

**Comment by christian-sap** [comment] 2021-09-30 14:13
Hi @keyur32 , is there any update? Add-ins are not working if 3rd party cookies are disabled. This will be a blocker for some of our customers.

**Comment by christian-sap** [comment] 2021-10-06 14:32
Hi @keyur32 , is there any result of the investigation?

**Comment by RuoyingLiang** [comment] 2021-10-08 03:14
Hi @christian-sap Feature team is working on a possible solution and don't have a timeline yet.  Will update this thread with any news.

**Comment by christian-sap** [comment] 2022-02-08 06:23
Hi @RuoyingLiang , no update since 4 months now. Are you planning to fix this?

**Comment by christian-sap** [comment] 2022-09-29 05:37
Hi @keyur32 any plans to fix this? There are no updates since almost 1 year.

**Comment by keyur32** [comment] 2022-12-19 17:57
Assigned to @AkhileshShah-MS  and @RuoyingLiang for updates.

**Comment by stevebeauge** [comment] 2024-02-05 15:45
In 2024 3rd part cookies are going to be disabled by chromium browsers (long time ago also by Firefox).

Can you share update regarding this ticket ?

Maybe related:
* https://github.com/SharePoint/sp-dev-docs/issues/5966#issuecomment-1926454703
* https://github.com/SharePoint/sp-dev-docs/issues/9423
* ...

**Comment by 4tti** [comment] 2024-03-20 15:08
I am interested too, how is it going to be with Office add-ins and excel/word/ppt online within the chrome?

**Comment by mailchecktool-admin** [comment] 2024-04-22 07:45
@keyur32  @exextoc 
 I'm also interested in what @stevebeauge is saying. Even after third-party cookies are disabled, can Office add-ins still be used as usual?

For reference, here is the information based on my findings. After disabling third-party cookies in the Chrome browser settings and conducting tests, it appears that the add-ins can still be used normally. Since the add-in was built using the local storage API, I anticipated there might be an impact, but no issues arose.

However, when the same test was conducted before 2023, there were issues. (The loading icon remained in the header section of the email composition screen, and the add-in did not execute.)

**Comment by mailchecktool-admin** [comment] 2024-05-11 23:42
@keyur32 @exextoc 
Multiple developers have been inquiring, but why aren't they responding? We'd like to understand how the discontinuation of third-party cookies will impact Office Add-ins. Could we please get the latest information?

**Comment by LuyiH** [comment] 2024-05-14 03:20
Hi Developers,
Thank you for your questions. 
For now, we recommend using MSAL, which should help solve most of the problems caused by third-party cookies being disabled. Detail progress [here](https://github.com/SharePoint/sp-dev-docs/issues/5966#issuecomment-1926454703). 
If you have any other specific questions, please feel free to open a new ticket.

**Comment by LuyiH** [comment] 2024-05-14 03:22
Close with fix.

**Closed as completed by LuyiH** 2024-05-14 03:22 UTC
Labels: Needs: attention :wave:, Area: Excel, Status: in backlog, Type: product question

**Comment by suuunly** [comment] 2024-05-26 18:51
This is not a good solution. Because the Office Dialog Api alone is non-responsive, because of third party cookies.
Why do you utilise third-party cookies for a plain dialog window anyways?
