### ISSUE TITLE
setSelectedDataAsync cursor position not updated reliably

### ISSUE THREAD

**Issue by TheCymaera** [OfficeDev/office-js#3541] opened 2023-07-26 23:53 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform: PC Desktop (and Web)
* Host: Microsoft Outlook
* Microsoft Outlook Version: 1.2023.719.200 (Production)
* Operating System: Windows 11 Pro
* Browser: Chrome
 
## Expected behavior
`setSelectedDataAsync` should insert the provided text and place the cursor after the inserted text.

## Current behavior
For HTML emails on desktop, the cursor moves as expected.
For plain text emails on desktop, the cursor position does not update.
For HTML emails on the web, the cursor position only moves sometimes, and never for plain text.

## Steps to reproduce

1. Open taskpane for "My Templates" (pre-installed addin).
2. Select email type (HTML/plain text).
3. Insert a template

## Context

This makes the built-in template feature awkward to use, as I need to manually fix my cursor position after each insertion. Additionally, I am developing a add-in for my client who uses plain-text emails.

### Before insertion:
![Screenshot 2023-07-27 at 7 47 34 AM](https://github.com/OfficeDev/office-js/assets/69355340/f01cf5b3-9f78-4d16-b0ae-b52c9dc32097)

### After insertion:
![Screenshot 2023-07-27 at 7 47 50 AM](https://github.com/OfficeDev/office-js/assets/69355340/f4890b59-abd8-4670-b97d-11995336b07d)

**Comment by millerds** [comment] 2023-08-03 21:49
I'm not able to reproduce this in Win32 Outlook.  Switching to a plain text email and using the taskpane puts the cursor after the inserted text as expected.

Where did you get that Outlook version number (doesn't look like what I would expect)?

**Comment by TheCymaera** [comment] 2023-08-10 11:03
> I'm not able to reproduce this in Win32 Outlook. Switching to a plain text email and using the taskpane puts the cursor after the inserted text as expected.
> 
> Where did you get that Outlook version number (doesn't look like what I would expect)?

That version is the opt-in "New Outlook" available via the toggle-switch on the top right corner.

I switched back to the old version, and verified that it is affected as well.
```
Microsoft® Outlook® for Microsoft 365 MSO (Version 2307 Build 16.0.16626.20086) 64-bit 
```

**Comment by millerds** [comment] 2023-08-31 23:20
The only point at which I see the cursor moving to the beginning of the text is at the point of switching from and HTML email to a plain text email.  For example (In desktop Outlook).

1. Create a new mail 
2. Put it into HTML mode ("Format Text" tab => "Html" button)
3. Open the "My Template" task pane ("Message" tab => "View Templates" button)
4. Use the task pane to insert some text 
5. Switch to plain text mode ("Format Text" tab => "Plain text" button => approve the warning)

As of step 4 the cursor is after the inserted text, but after step 6 it has switch to the beginning after the text of the email has had its behind-the-scenes HTML stripped.

**Closed as completed** 2023-09-26 19:02 UTC
Labels: Needs: attention :wave:, Area: Outlook
