### ISSUE TITLE
Interaction between Excel JS API and Excel RtdServer leads to the application crash on Windows. System.AccessViolationException: Attempted to read or write protected memory.

### ISSUE THREAD

**Issue by leybal** [OfficeDev/office-js#1782] opened 2021-04-07 09:44 UTC
Hi. We installed the add-in developed via C# with custom functions. We'll use [Seo Tools for Excel](https://seotoolsforexcel.com/documentation/) as an example. On this step we can easily use custom functions like `=HtmlTitle()`. 
The problem comes when we try to set a custom formula for a range via Excel JS API. The following line of code result in Excel crash:
`range.formulas = [['=HtmlTitle("https://www.google.com")']]`
Please take a look at [the video](https://drive.google.com/file/d/1o0QTJA7vGVzBsbsxDJ5c-Fjj6CU_WGhM/view?usp=sharing).
We have done some research and debugged custom functions in C#. When we run any operations with the RtdServer the following error occurs: "System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt".
It looks like the Excel JS API does not release memory and RtdServer can't handle the process. Adding `range.untrack()` before `context.sync()` doesn't help. Does Excel JS API have methods for memory release?

## Expected Behavior
Interaction between Excel JS API and Excel RtdServer will not leads to the application crash. So a user can set C# custom functions to a range via Excel JS API by pressing a button on task pane.

## Current Behavior
Inserting a custom function via Excel JS API and following operations with RtdServer crash Excel.

## Steps to Reproduce, or Live Example
1. Install [Seo Tools for Excel](https://seotoolsforexcel.com/documentation/) on Windows
2. Install and open Script Lab
3. Add following code
`const range = context.workbook.getSelectedRange();`
`range.formulas = [['=HtmlTitle("https://www.google.com")']];`
`await context.sync();`
4. Run adding formula to cell via Script Lab
5. The application crash should happen

## Context
Users can't use C# add-in custom functions in add-ins built using the Excel JS API.

## Your Environment

* Platform: PC desktop
* Host: Excel
* Office version number: Version 2103 (Build 13901.20336)
* Operating System: Windows 10 x64

**Comment by gingerjia** [comment] 2021-04-08 15:31
Thanks for reporting the issue @leybal ! We can repro the issue locally and created a bug #5014373 to track it. 
We will reply to this thread when have progress!

**Comment by grangeryy** [comment] 2021-04-12 07:05
Seems like an RichAPI. Add @lumine2008 for JS API.

**Comment by 2020Mar** [comment] 2021-04-15 02:31
@leybal  Excel RichAPI team has fixed this issue and will tell Current Chanel version which contains this fix later. Please wait patiently, thanks!

**Comment by shaowan-msft** [comment] 2021-04-15 02:35
@leybal Excel RichAPI team has fixed this issue and will tell Current Chanel which contains this fix later. Please wait patiently, thanks!

**Comment by leybal** [comment] 2021-04-15 10:28
@shaowan-msft could you share estimation with us? Will the fix be released in a couple of weeks or months? Thanks.

**Comment by shaowan-msft** [comment] 2021-04-16 02:26
@leybal It may needs 1-2 months before you have this fix in your local side, I will keep eyes on the deployment process and update in this thread ASAP. Thanks!

**Comment by 2020Mar** [comment] 2021-05-12 07:07
@leybal If you are in Excel CC chanel and update to the latest version, the issue will disappear. I have validated in my side the issue is resolved, my Excel version is 
![image](https://user-images.githubusercontent.com/63632212/117933085-c7b27f00-b333-11eb-928d-e18d891ef3f2.png)

**Comment by lumine2008** [comment] 2021-05-20 11:08
Thanks for your validation, i am closing this issue for now, please re-open if you still observe the issue. thanks

**Closed as completed by lumine2008** 2021-05-20 11:08 UTC
Labels: Type: product bug, Status: fixed, Area: custom functions
