### ISSUE TITLE
Fatal Memory Issue - Excel Content Pane updating a Table

### ISSUE THREAD

**Issue by david-ps** [OfficeDev/office-js#1415] opened 2020-09-30 09:53 UTC
## Expected Behavior
We add Rows to a Table from an Excel Content Pane Add-in and expect that any increase in the user's memory will be consistent with the size of the added data and any other memory consumed for the add process, will be minimal and/or reduce after the process is complete.

## Current Behavior
Adding a Row to a Table from a Content Pane Add-in permanently increases the memory by ~3mb+ in that session and does not reduce. As additional rows are added, the memory is consumed to a point where Excel crashes.

## Steps to Reproduce, or Live Example
To demonstrate the issue we are using the sample code from **Scriptlab** used to demo "Add rows and columns"
We have created two standalone apps using the identical Scriptlab code:
1. Task Pane Add-in (attached manifest ExcelMemberIssueHtml - TaskPane.xml)
2. Content Pane Add-in (attached manifest ExcelMemberIssueHtml - ContentPane.xml)

### Steps
1. Sideload the two attached manifests
2. Open Excel 
3. Insert the **Task Pane Add-in** and open the Task Pane from the ribbon
4. Click Create Table (**Sample** worksheet created and table added)
5. Insert the **Content Pane Add-in** (Content Pane Add-in is displayed on Sample worksheet)
6. Both Add-ins are connected to the same **ExpensesTable** (do not click Create Table on Content Pane)
7. Open **Windows Task Manager** and note the memory MB used by Excel
8. Click **Add Rows** in **Task Pane** _five times_ to add a series of rows
9. Wait for a few moments and **note the memory MB** used by Excel from the Task Pane source
10. Click **Add Rows** in **Content Pane** _five times_ to add a series of rows
11. Wait for a few moments and **note the memory MB** used by Excel from the Content Pane source
12. Compare the memory MB usage between the Task Pane and Content Pane Apps

## Context
This is a critical issue for our project where a Content Pane add-in has been developed that adds rows and interacts with an Excel Table.

## Environment
* Platform: Microsoft 365
* Host: Excel Desktop
* Excel Version 2008 (Build 13127.20408)
* Excel for Microsoft 365 MSO (16.0.13127.20266) 32-bit | Semi-Annual Enterprise Channel (Preview)
* Operating System: Windows 10 Pro 10.0.19041 Build 19041
* Browser: Edge

Screenshot and Manifests and attached

![ExcelMemoryTestSetup](https://user-images.githubusercontent.com/47418828/94669659-e049c800-0354-11eb-8995-2e68032beabf.png)

[ExcelMemberIssueHtml - Manifests.zip](https://github.com/OfficeDev/office-js/files/5304564/ExcelMemberIssueHtml.-.Manifests.zip)

**Comment by david-ps** [comment] 2020-09-30 23:30
@lumine2008 Could this bug have been introduced when #391 was resolved? 
We've been working on this app for months and never noticed this issue. Now all development has come to a stop because we cannot proceed with any UAT so this is critical for us. FYI @jamilnawaz @chartnado-brian-haas

**Comment by david-ps** [comment] 2020-10-02 01:38
@tutieu @ElizabethSamuel-MSFT Can you please give us an estimated timing on when this bug will be investigated and the likely solution and/or workaround?

**Comment by david-ps** [comment] 2020-10-08 02:27
We see this error using:
Windows 10 Pro 10.0.19041 Build 19041
Excel for Microsoft 365 MSO (16.0.13127.20266) 32-bit
Semi-Annual Enterprise Channel (Preview)
On that basis, I believe the browser being used is WebView (EdgeHTML) based on [documentation​​​​​​​](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
_NB: The issue environment details are updated_

**Comment by david-ps** [comment] 2020-10-08 08:13
@keyur32 We have NOT installed [Microsoft Edge WebView2 (Preview)](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)

**Comment by lumine2008** [comment] 2020-10-10 02:17
it looks like UX related issue, looping Lillian as well

**Comment by david-ps** [comment] 2020-10-10 10:42
@lumine2008 Thanks for getting involved. What does UX related issue mean?

**Comment by lumine2008** [comment] 2020-10-10 12:37
it's an internal team:) 
> @lumine2008 Thanks for getting involved. What does UX related issue mean?

**Comment by david-ps** [comment] 2020-10-13 19:37
@lliu113 Can you please provide an update?

**Comment by david-ps** [comment] 2020-10-21 08:57
@keyur32 @lumine2008 Any news or ETA on this **critical issue**? Our development has been stopped now for 3 weeks awaiting the outcome!

**Comment by keyur32** [comment] 2020-10-28 18:59
Still under investigation and @lumine2008  will comment when updated. Thanks.

**Comment by lumine2008** [comment] 2020-10-29 01:38
Thanks for your patient, @david-ps , yes, our team is still doing the investigation, we found this issue is not related to any specific API, it may relate to the EdgeHTML webview, we are working with the related team to do further investigation.

**Comment by david-ps** [comment] 2020-10-29 09:29
Thanks for keeping us updated @lumine2008 Great to hear it's not related to the API.

**Comment by david-ps** [comment] 2020-11-20 08:34
51 days - any news about this fatal bug investigation?
@lliu113 @keyur32 @lumine2008

**Comment by david-ps** [comment] 2020-12-09 05:09
Hey Guys, any news?
@lliu113 @keyur32 @lumine2008

**Comment by MandytMSFT** [comment] 2020-12-09 06:25
@david-ps  Sorry for the delay. We are actively working on that. I just assigned the thread to right person in order we can track better on that.

**Comment by david-ps** [comment] 2020-12-10 07:11
@mandytmsft That's great, thank you!

**Comment by Dengshan2018** [comment] 2020-12-11 18:43
@david-ps , the root cause is located. The fix is on the way.

And please confirm there is no issue if update table just from the taskpane.

**Comment by david-ps** [comment] 2020-12-25 08:11
@Dengshan2018 No, we have not discovered any issue with updating tables/sync data from the taskpane only the contentpane. 
Can you please advise as to the implications of the fix ie. will it require the use of an updated API Requirement Set? What exactly being fixed?

**Comment by Dengshan2018** [comment] 2020-12-25 18:31
@david-ps Thanks for the confirmation. This is memory leak issue. The fix will be available in future release 16.0.13530.20252+. The fix might be back ported to old version. But no promise. There is no change required in your end. Thanks again for reporting the issue.

**Comment by david-ps** [comment] 2020-12-25 19:08
@Dengshan2018 Thanks for the update. We have been developing for target **ExcelApi 1.9** | Version 1903 (Build 11425.20204) or later | 16.0 or later | 16.24 or later | May 2019. Can you please port fix back to that version so that we can engage our researched target audience.

_Updated: Changed from Excel API 1.11 to 1.9 that is required_

**Comment by Dengshan2018** [comment] 2021-01-04 18:29
@david-ps Oldest version we can port back is 16.0.13127.*(semiannual version which is released on July 2020). New Excel version should support ExcelApi 1.9. Can those Office users update their version to 16.0.13127+?

**Comment by david-ps** [comment] 2021-01-09 09:09
@Dengshan2018  Is 16.0.13127.*(semiannual version which is released on July 2020) M365 Version 2002 and Excel API Requirement Set 1.11? 

What is the link between [Requirements Sets](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets) and [M365 Version Semi Annual](https://docs.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date). Please clarify.

And, when do you expect this fix to be applied?

**Comment by david-ps** [comment] 2021-01-12 05:14
@Dengshan2018 @MandytMSFT We are unable to continue development or testing until we have a fixed version and can confirm backwards porting and minimum Excel version and Requirement Set. Please advise asap re previous post questions.

**Comment by Dengshan2018** [comment] 2021-01-12 05:30
@david-ps the fix is already in Current Channel from [M365 Version Semi Annual](https://docs.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date). Please verify. Latest office version should support all API set by default.

**Comment by david-ps** [comment] 2021-01-12 06:02
@Dengshan2018 @AlexJerabek @alison-mk Sorry, I am not clear on what "[Current Channel from M365 Version Semi Annual](https://docs.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date)" means. 

Can you please be specfic and advise **Release Date**, **Version** and **Build** in which the fix has been deployed and when it will be released to the Monthly and Semi Annual Enterprise Channels?

**Comment by Dengshan2018** [comment] 2021-01-12 06:23
@david-ps The fix is in 2012 | 13530.20316 | January 5, 2021
![image](https://user-images.githubusercontent.com/45212981/104277033-f1799900-545a-11eb-9dc6-26eeb8c073ff.png)
Need more justification and time to port back to Semi Annual Enterprise Channels.

**Comment by david-ps** [comment] 2021-01-12 06:33
@Dengshan2018 Thanks. What more justification do you need and how much time would it take to port back to below?

![image](https://user-images.githubusercontent.com/47418828/104278024-a8c1ee80-54f3-11eb-80b3-c602ca6e8a77.png)

**Comment by Dengshan2018** [comment] 2021-01-12 07:02
@david-ps I've created the bug for customer support. You might be contacted for more information once the supporting engineering is acknowledged. Before that, feel free to verify the fix.

**Comment by david-ps** [comment] 2021-01-12 07:30
@Dengshan2018 ok thanks! Will get back to you with results soon.

**Comment by david-ps** [comment] 2021-01-12 07:48
@Dengshan2018 Yes, the problem is fixed. Thanks you :) 

@AlexJerabek @alison-mk Can you please help with the questions below and any documentation where these are described?
1. Which version of Excel does M365 Version 2002 (Build 12527.20988) released in the Semi-Annual 14 July 2020 channel contain?
2. We know that you can check [Requirement Set availability at Runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets#checking-for-requirement-set-support-at-runtime) but how can we check for Excel Version?

**Comment by Dengshan2018** [comment] 2021-05-18 20:52
The fix should be in Semi-Annual 2008 for a few months.
![image](https://user-images.githubusercontent.com/45212981/118721689-076be180-b7e0-11eb-8488-a1ec41e82510.png)

**Closed as completed by Dengshan2018** 2021-05-18 20:52 UTC
Labels: Area: Excel, Type: product bug, Status: under investigation
