### ISSUE TITLE
RibbonApi is no longer working

### ISSUE THREAD

**Issue by zpfaltersack** [OfficeDev/office-js#4495] opened 2024-05-22 19:16 UTC
# Provide required information needed to triage your issue

We use RibbonApi 1.2 to create ribbons/groups/controls in Excel (online and desktop). We are now seeing that it does not work in any dev/test/prod environment internally for ourselves or any of our customers. When we look in our logging we see a dramatic uptick in this error. Usually we might see 10s of incidences in a week and they're resolved with a refresh of the addin (or trying again the next day).
In the last 7 days, we've seen that number jump into the 1000s. Our addin is severely hamstrung and all but the most basic of use-cases are inaccessible.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: desktop/web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Browser (if using Office on the web): all
 
## Expected behavior

Creating ribbons/controls works consistently.

## Current behavior

No error occurs, the request to create controls is received, but no ribbons/controls are ever created. We usually will create a few hidden contextual tabs when the addin is initialized and then toggle visibility depending on what the user is doing. The typical failure is an error saying a ribbon/control with the given ID is not found. In a dev environment we modified the behavior to default the ribbons to be created and visible so that we don't need to reference them by ID, and they still just never get created. The documentation is clear that it can take a moment for these to get created, but we've done this experiment many times and waited 10s of minutes and never seen anything show up.

## Steps to reproduce

1. Follow this doc: https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/design/contextual-tabs.md
2. Note that it doesn't work.

## Context

This is affecting every environment and every customer we have at this point. It's ramped up over the last several days. It is not uncommon that this API randomly stops working for a day or two and we typically chalk it up to bad deployments on the Microsoft side because it happens outside of any changes we've made to the addin. Usually only a few customers are impacted, but this time it's pretty much everyone, which makes us look bad and it's become a massive support headache.

**Comment by harishbhaskaruni** [comment] 2024-05-23 07:48
Hi, We are also facing this issue. Can you please get us an update on this as soon as possible. This is a showstopper bug for us.

**Comment by shanshanzheng-dev** [comment] 2024-05-23 08:02
Hi @harishbhaskaruni  @zpfaltersack Thanks for reporting this issue. We'll be looking into this problem, will report back here if we have a suggestion for you. Thanks.

**Comment by harishbhaskaruni** [comment] 2024-05-23 11:08
Dear Microsoft Team, can you please confirm  know if you can replicate the issue on your side ? @shanshanzheng-dev  @yinaa @NT-D

**Comment by wh1t3cAt1k** [comment] 2024-05-23 11:56
Showstopper for us as well, our ribbon suddenly stopped showing in Excel Online with the following error:

<img width="338" alt="image" src="https://github.com/OfficeDev/office-js/assets/5159662/dcda3c1f-3d3c-43e1-8991-757e4c50fc51">

It used to work until yesterday.

[Velixo internal tracking item](https://3.basecamp.com/3496385/buckets/16689259/card_tables/cards/7430915192)

Steps to replicate:

- Use Excel Online
- Install Velixo NX add-in from AppSource
- Click the Velixo button on the Home tab, wait for the side panel to open
- Actual result: above error in the console, the ribbon does not show
- Expected result: the ribbon appears

**Comment by shanshanzheng-dev** [comment] 2024-05-23 13:31
Hi @wh1t3cAt1k @harishbhaskaruni Thanks for the detail info. We have confirmed this problem and it's under root cause investigation now. Sorry for inconvenience.

**Comment by zpfaltersack** [comment] 2024-05-23 15:51
Thank you for confirming you can reproduce the bug. 

While the current issue is affecting all customers, I am also curious to understand why we see this so regularly albeit at an admittedly much smaller volume. Is anyone else seeing that? As I mentioned in my original message, we do see this pretty often but only at the rate of a handful of times a day and it can usually be resolved by waiting a day or sometimes even just refreshing the browser (when using Excel Online).

I'd like to understand why the Ribbon API seems to be particularly unreliable while this issue is getting some attention.

**Comment by trigurl** [comment] 2024-05-23 21:39
Hi I'm here to give you an update, a couple weeks ago a change was made by another team and it caused a regression.  The fix has been submitted and we are waiting for it to deploy out.  Sorry for the inconvenience it has caused you and your customers.  I will come back and update you on where it is in the deployment pipeline.

**Comment by zpfaltersack** [comment] 2024-05-23 22:42
Thanks @trigurl, that's great to hear. Do you have any thoughts on the occurrences of this issue prior to two weeks ago? We see it pretty often, just not with the volume we've seen the last 7-14 days.

**Comment by trigurl** [comment] 2024-05-24 00:00
Looking at the notes, the change that caused the regression went in at the start of May.  When we deploy through our rings, they start off small then the volume of users will grow.

**Comment by 4tti** [comment] 2024-05-24 11:27
We are facing it too... good to hear it is going to be fixed soon.

**Comment by shanshanzheng-dev** [comment] 2024-05-28 08:51
Hi @zpfaltersack @wh1t3cAt1k @4tti , I have checked this issue from my side and found this issue can not repro on Wac and win32 now, could you please confirm if you still have this issue? We value your feedback, Thanks.

**Comment by wh1t3cAt1k** [comment] 2024-05-28 13:33
@shanshanzheng-dev can you please try on Excel for the Web? On our side it doesn't replicate on Excel for Windows, but ribbon completely stopped appearing on Excel Online.

**Comment by wh1t3cAt1k** [comment] 2024-05-28 13:35
@shanshanzheng-dev https://github.com/OfficeDev/office-js/issues/4495#issuecomment-2126927595 - see my replication steps above.

**Comment by zpfaltersack** [comment] 2024-05-28 14:40
@shanshanzheng-dev The error is still occurring for me in Excel for the Web but it does look like things are now working in Excel Desktop.

**Comment by wh1t3cAt1k** [comment] 2024-05-28 14:49
This completely blocks our E2E tests... Please prioritise if possible!

**Comment by trigurl** [comment] 2024-05-28 18:20
@shanshanzheng-dev for internal to Microsoft we should see the issue fixed.  We need to wait until the Excel online client deploys through the rings to Prod for customers to start seeing improvements.

**Comment by trigurl** [comment] 2024-05-29 05:11
Excel Online is going to fast track this, but just waiting for automation to finish.   Could be soon.

**Comment by zpfaltersack** [comment] 2024-05-29 14:35
Thank you @trigurl!

**Comment by zpfaltersack** [comment] 2024-05-30 14:24
@trigurl @shanshanzheng-dev It looks like the ribbon started working this morning. We're still waiting for confirmation to roll in from our customers but I've verified it works for me in all our environments. Thank you for getting this resolved!

**Comment by trigurl** [comment] 2024-05-30 17:06
I'm trying it out now but it's not working for me :(  It's working for some of my coworkers.  Still investigating. 
Update - we are only 50% rolled out.

**Comment by trigurl** [comment] 2024-06-03 20:53
Hi folks, I tried this with the Velixo add-in and my colleages as well.  The Contextual Tab should be appearing now.

**Comment by 4tti** [comment] 2024-06-04 13:26
Confirmed, it seems to work again.

**Closed as completed** 2024-06-12 02:05 UTC
Labels: Needs: attention :wave:, Area: Excel, Needs: author feedback, Status: no recent activity
