### ISSUE TITLE
Range.insertHtml() doesn't work as expected on Word online

### ISSUE THREAD

**Issue by Simplici** [OfficeDev/office-js#1208] opened 2020-06-09 07:35 UTC
Range.insertHtml() doesn't work as expected on Word online

## Expected Behavior

the styles in html should be retained in docx
## Current Behavior

we have a Word addin which use Range.insertHtml() to insert a table with styles into document.

it works well with Mac Word: 
![image](https://user-images.githubusercontent.com/8101111/84224901-527d6f00-ab10-11ea-9064-49123dcdc37c.png)

But not so good when on Word Online: 
![image](https://user-images.githubusercontent.com/8101111/84224914-5a3d1380-ab10-11ea-9ae8-6c54e911e4be.png)

it seems that with Word online, Range.insertHtml() has a poor support on html styles(table width, background colour, border colour, etc).

here is the code:

```
html = "
<table border=0 cellspacing=0 cellpadding=0 style='width:450pt;margin-left:0pt;border-collapse:collapse'>
    <tr>
	<td style='width:50pt;height:22pt;text-align:center;background:#FFC585;border:1px solid #FFC585;border-right:none;word-break:break-all;'>
            &#32;<a href='https://google.com' style='color:#333333;'>Q</a>&#32;</td>
	<td style='width:400pt;text-align:left;background:white;padding:0 10pt;border:1px solid #CCCCCC;word-break:normal;'>
            <span style='color: #000000;'>questioning</span>
	</td>
    </tr>
</table>
"

function insertHtml(html) {
  return Word.run(async context => {
    const range = context.document.getSelection();
    range.insertHtml(html, 'Replace');
    await context.sync();
  });
};

insertHtml(html)

```

**Comment by MandytMSFT** [comment] 2020-06-09 14:00
@Simplici  thanks for reporting. Could you share your code or html style to help reproduce the issue ?

**Comment by Simplici** [comment] 2020-06-10 03:57
@MandytMSFT i have updated the issue with code.

**Comment by MandytMSFT** [comment] 2020-06-12 07:16
@Simplici i just tried on Word online with https://gist.github.com/MandytMSFT/03b867f2eb50c8cbf49287451534d787 , it works well on my side. Could you try my gist to see if it works ? 

![image](https://user-images.githubusercontent.com/52641972/84475644-7e8b2280-acbf-11ea-9293-2aab0dc3f129.png)

**Comment by Simplici** [comment] 2020-06-12 09:26
@MandytMSFT it doesn't work. May the result be different based on account?
below is the version of Word online:
![image](https://user-images.githubusercontent.com/8101111/84489606-84d7c980-acd4-11ea-83c1-24c46f2e68c8.png)

**Comment by MandytMSFT** [comment] 2020-06-13 14:35
@Simplici  you are right. I just tried on your build, the behavior is the same as yours. I used to test on 16.0.13011.41006 which ideally will be rolled out to your env early next week , it worked as expected. Though i don't know the difference of these 2 builds , given  it works in newer build, i'd suggest you waiting to see if it works for you next week. Feel free to let me know if the issue is still here

**Comment by Simplici** [comment] 2020-06-15 02:52
@MandytMSFT tks. I will come back to you later.

do you have anything like developper program which allows to try the latest dev version?

**Comment by Simplici** [comment] 2020-06-16 06:23
@MandytMSFT 
I have seen a new build for Word Online:
![image](https://user-images.githubusercontent.com/8101111/84738607-cde19380-afdc-11ea-932c-3a7b0cb1ac2a.png)

from the build no., it seems more recent than 16.0.13011.41006, but still doesn't work.

**Comment by MandytMSFT** [comment] 2020-06-22 02:48
@Simplici that may because it's new feature of word online which has not been ON in your env. Seems your scenario will be supported in near future.

**Comment by Simplici** [comment] 2020-07-23 07:24
> @Simplici that may because it's new feature of word online which has not been ON in your env. Seems your scenario will be supported in near future.

it just tried, it works now

**Comment by MandytMSFT** [comment] 2020-07-23 07:29
@Simplici thanks for your confirmation. Then i'd like to close this thread.

**Closed as completed by MandytMSFT** 2020-07-23 07:29 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: Word
