### ISSUE TITLE
Office.context.mailbox.item is 'undefined' when addin is loaded in "Preview" view. 

### ISSUE THREAD

**Issue by sandeepmshetty** [OfficeDev/office-js#4365] opened 2024-04-16 07:00 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform: PC desktop
* Host: Outlook
* Office version number: 16.0.17231.20290
* Operating System: Windows 11
 
## Expected behavior
Office.context.mailbox.item should have selected item values in "Preview" view.

## Current behavior
Office.context.mailbox.item is undefined in "Preview" view.

## Steps to reproduce
When switching to "Preview" we are unable to get Office.context.mailbox.item value
![image](https://github.com/OfficeDev/office-js/assets/3336342/95db4be2-0294-443d-9840-42e8dd542c1d)

Please let me know if there is any alternative steps to get the selected email value in  Office.context.mailbox.item

Thanks

**Comment by Oleg-O** [comment] 2024-04-23 00:23
I couldn't immediately reproduce this. It's quite unlikely that just switching to "preview" would break that API this way. I suspect there is something else going on. Is this email just a regular email for a regular user, or there is some delegate or shared mailbox or folder configuration used in this case? If this just a one user issue or there anyone else has seen this too? Are you saying that switching off of preview works and switching back to preview breaks it consistently and for the same user and folder and email?

**Comment by KamilaSieczkowska** [comment] 2024-04-26 15:00
Hi,I have the same issue. When addin is open from "compact" or "single" view it's fine, but in "preview" Office.context.mailbox.item is 'undefined'. 
It's a standard mailbox, more than one users, no specific configuration. And yes, switching off of preview works and switching back to preview breaks it consistently and for the same user and folder and email.
The problem occurs with selection of single email item and multiple items as well.

**Comment by Oleg-O** [comment] 2024-04-26 16:19
@KamilaSieczkowska what's your outlook version number? When you switch to compact view, is your reading pane on or off?

@sandeepmshetty I highly suspect that what you're seeing is happening because in the preview mode you have reading pane turned off. Can you confirm please? If that's the case, this is by design - item is expected to be undefined when reading pane is turned off.

**Comment by KamilaSieczkowska** [comment] 2024-05-06 08:10
@Oleg-O , I have version 2402, build 16.0.17328.20282, 64-bit

**Comment by sandeepchatgpt** [comment] 2024-05-06 11:11
> @KamilaSieczkowska what's your outlook version number? When you switch to compact view, is your reading pane on or off?
> 
> @sandeepmshetty I highly suspect that what you're seeing is happening because in the preview mode you have reading pane turned off. Can you confirm please? If that's the case, this is by design - item is expected to be undefined when reading pane is turned off.

Hi @Oleg-O : Yes, your are right. Without Reading Pane , we are not able to fetch the item details. Closing the issue. Thank you :)

**Closed as completed** 2024-05-06 21:49 UTC
Labels: Area: Outlook, Resolution: by design
