### ISSUE TITLE
Same TaskpaneId in web addin throw an error msg

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#2918] opened 2022-10-26 07:06 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

when we use same TaskpaneId  for different Action, in office online web excel it throw an error. but use differenet TaskpaneId for 

different Action it's ok.

but in excel client in windows it's ok ,no matter same or different TaskpaneId .

we want use same TaskpaneId then our Panel only one.

![image](https://user-images.githubusercontent.com/3963826/197956625-9d6dc6bf-f3e5-4a33-90f8-00c482348865.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __office on the web____
* Host [Excel, Word, PowerPoint, etc.]: __excel____
* Office version number: ___office online___
* Operating System: ___windows___
* Browser (if using Office on the web): __chrome____

**Comment by RuizhiSunMS** [comment] 2022-10-28 07:55
Thanks for reporting. This issue should be TaskPane related, I'm reaching out to related colleagues.

**Comment by ElizabethSamuel-MSFT** [comment] 2022-10-28 16:10
@RuizhiSunMS Is there someone this issue can be assigned to? Thx.

**Comment by RuizhiSunMS** [comment] 2022-11-01 07:39
@ElizabethSamuel-MSFT  , I think Heidi should know but I don't know his github account. I sent an email but got no reply

**Comment by ElizabethSamuel-MSFT** [comment] 2022-11-03 16:03
@RuizhiSunMS Ok, understood.

**Comment by madhavagrawal17** [comment] 2022-11-03 22:48
@dinglicoding, Can you please share the manifest file in order for us to investigate the issue?

**Comment by dinglicoding** [comment] 2022-11-04 07:57
@madhavagrawal17  can you give me an email, then i send it to you ,thanks

**Comment by madhavagrawal17** [comment] 2022-11-07 21:40
@dinglicoding, Please send it to madhavagrawal17@outlook.com

**Comment by dinglicoding** [comment] 2022-11-08 13:33
@madhavagrawal17  I have send an email, thanks

**Comment by madhavagrawal17** [comment] 2022-11-09 21:20
Thanks, @dinglicoding. We received the manifest files and we are looking into the issue.

**Comment by dinglicoding** [comment] 2022-11-17 02:38
Hi @madhavagrawal17    We look forward to your reply ，Thanks

**Comment by madhavagrawal17** [comment] 2022-11-17 18:19
@dinglicoding, Sorry for the delay. After an investigation by the SharedRuntime expert for Office online, we found that currently it is expected behavior because of some technical limitations on Office online. I am afraid you might have to use different Taskpanes Ids if you are using the same SharedRuntime Id.

**Comment by dinglicoding** [comment] 2022-11-18 05:36
@madhavagrawal17  thanks for your quick reply.  you said SharedRuntime Id is the Taskpanes Id? where set ShareRuntime Id ，thanks

**Comment by madhavagrawal17** [comment] 2022-11-18 16:39
So SharedRuntime Id is the Id set on the Runtime element in the manifest:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/48529581/202756404-5f05e054-9b95-42a6-8377-d722ffd8fcb5.png">

**Comment by dinglicoding** [comment] 2022-11-22 04:07
@madhavagrawal17  thanks it ok

**Closed as not planned** 2024-04-01 15:19 UTC
Labels: Needs: attention :wave:, Area: add-in UI
