### ISSUE TITLE
SearchOptions Wildcards doesn't capture certain strings

### ISSUE THREAD

**Issue by nunocv** [OfficeDev/office-js#74] opened 2018-03-07 13:57 UTC
## Expected Behavior
this WildCard [!$#@]*[}][\r][\t] should capture !{sdfgdfhf}, \r and \t being actual line breaks and tabs.

## Current Behavior
[!] not being captured, even by itself on [].
[\t] not being captured
[@] not being captured
The rest is all captured correctly.

## Steps to Reproduce, or Live Example
Example doc with various expressions 
[TestDoc.docx](https://github.com/OfficeDev/office-js/files/1789346/TestDoc.docx)

## Context
Developing a validation feature for a word add in, that validates a certain type of document. If this isn't fixed, I can't improve my validation tool.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC, Mac, Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Most recent
* Operating System: Windows and MacOS
* Browser (if using Office Online): Chrome

**Comment by JuaneloJuanelo** [comment] 2018-03-07 15:11
Thanks for sharing this, we'll try to repro and investigate. Can you please indicate in what platforms you are having this issue. (Windows? Online?) .

**Comment by nunocv** [comment] 2018-03-07 15:16
Windows Platform, while developing a Word Add-In on Visual Studio. Tested via "Start" from Visual Studio that open Microsoft Word, in this case 365 2016.

**Comment by nunocv** [comment] 2018-04-11 12:36
Hello!
Any news regarding this topic?
This limitation is really impacting some features in our add-in.

**Comment by rmrodrigues** [comment] 2018-04-17 13:56
Hi @JuaneloJuanelo ,
We are blocked by this. We can't publish our application without the main feature that depends on this.
Could you share us any news about this?
We'll appreciate that.
Thank you.

**Comment by JuaneloJuanelo** [comment] 2018-04-17 22:01
Thanks for following up,  can you please share the specific build and platforms you are experiencing this issue? (file -> Account  check the about section and send version and build number). please provide as much details as possible otherwise we cannot investigate in detail and its probably why there is not prompter follow up.
thanks!

**Comment by nunocv** [comment] 2018-04-20 16:36
Hello @JuaneloJuanelo,
There are some updates/better description to this issue, that were tested today on the version 1708 (Build 8431.2242) of Word:

- Regarding the parsing with \t and \r, unfortunately, it is still not done correctly! So, in a Word Document if I have the following text: 
![image](https://user-images.githubusercontent.com/26458114/39057318-cc57d81a-44b0-11e8-8d2f-9676a640ab07.png)
And a searchoption wildcard like '[$#&][{]*[\r\t]', it will find all the fields that start with '${' and end with '\r' without a problem but if it ends with '\t' it wont be found, because  it will have a '\t' or '\r' between the text in the Body.text property string from the document.

- Regarding the parsing with '@' and '!', using the same example as before, a searchoption wildcard like '[$#&@!][{]*[\r\t]', it won't find the fields that start with '@{' and '!{'.

**Comment by JuaneloJuanelo** [comment] 2019-07-25 23:39
dupe of https://github.com/OfficeDev/office-js/issues/313#issuecomment-361564673

**Closed as completed by JuaneloJuanelo** 2019-07-25 23:39 UTC
Labels: Status: under investigation, Area: Word
