### ISSUE TITLE
Office.onReady() issue on different method usage

### ISSUE THREAD

**Issue by ATrogolo** [OfficeDev/office-js#304] opened 2018-11-22 16:47 UTC
## Expected Behavior
Referring to this [docs](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/understanding-the-javascript-api-for-office#initialize-with-officeonready) I was expecting that `Office.onReady()` method works exactly the same if called with Promise behaviour or with function as first parameter. 
But it is not. 

## Current Behavior
If I type: 
```javascript
const render = (Component, props) => {
  ReactDOM.render(
    <AppContainer>
      <Component {...props} />
    </AppContainer>,
    document.getElementById("container")
  )
}
Office.initialize = () => {}
Office.onReady(function(info) {
    console.log(`Office.js is now ready in ${info.host} on ${info.platform}`)
    render(App, { hasUpdatedApi: true })
  })
render(Progress, {
    logo: "/assets/logo-filled.png",
    message: "Loading ...",
  })
```
It renders only the Progress component and never triggers the `onReady` callback . 

----
This instead works as expected:
```javascript
const render = (Component, props) => {
  ReactDOM.render(
    <AppContainer>
      <Component {...props} />
    </AppContainer>,
    document.getElementById("container")
  )
}
Office.initialize = () => {}
Office.onReady().then(() => {
    render(App, { hasUpdatedApi: true })
})
render(Progress, {
    logo: "/assets/logo-filled.png",
    message: "Loading ...",
})
```

## Your Environment

* Platform: PC desktop, Office Online
* Host: Excel
* Office version number: 1803 (Build 9126.2295)
* Operating System: Windows 10
* Browser: Chrome 70

**Comment by dmahugh** [comment] 2019-04-17 11:55
This is a duplicate of issue #301 and the fix has been deployed. Thanks for reporting it.

**Closed as completed by dmahugh** 2019-04-17 11:55 UTC
