### ISSUE TITLE
Word: Range.select for tracked ranges crashes the add-in

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#2436] opened 2022-02-17 15:53 UTC
I have the following gist: https://gist.github.com/JensMadsen/40f5f58b1921eabef90d49fbc129ad9f

This works in Word Online using Chrome, but fails on Word Windows Desktop. The error message is: 
```
RichApi.Error: GeneralException
    at new n (appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:242451)
    at n.i.processRequestExecutorResponseMessage (appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:306195)
    at appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:304300
```

Are we doing it wrong or is it a bug? This bug makes a central feature in our add-in break :-(

**Comment by yihuax-msft** [comment] 2022-02-25 01:41
The cause of the problem is that, if a tracked object is from a collection item, then the collection must also be tracked.
The following code works on my machine:

async function run() {
  let foundRange: Word.Range;
  let foundRangeCollection;
  await Word.run(async (context) => {
    const body = context.document.body;
    const insertString = "heste";
    body.insertText(insertString, "Start");
    console.log("Your code goes here");

    await context.sync();

    foundRangeCollection = body.search(insertString);
    foundRangeCollection.load("items");
    await context.sync();
    foundRange = foundRangeCollection.items[0];
    foundRange.track();
    foundRangeCollection.track();
  });

  console.log("going into second context");
  await Word.run(foundRange, async (context) => {
    foundRange.select();
    await context.sync();
  });
}

**Comment by JensMadsen** [comment] 2022-02-25 16:39
Thank you @yihuax-msft. A bit surprising since it works in Word Online. Nonetheless It also works without tracking the range. Tracking the RangeCollection is enough. Perhaps it would be an idea to add some information (if possible) to the error message in this case, and describe it in the docs if not already there?

**Comment by yihuax-msft** [comment] 2022-02-25 17:29
Thank you @JensMadsen for your patience. Glad to know it works. We certainly should keep improving our documentation. Good suggestion! I will let our documentation engineers know.

**Comment by JensMadsen** [comment] 2022-05-17 10:16
@yihuax-msft I would like to close this issue. Therefore, I would ask if the documentation and/or the error message has been altered?

**Comment by yihuax-msft** [comment] 2022-05-17 17:34
Thank you @JensMadsen for reminding me. We have had an internal bug (6059458) to track this issue. I will make its priority higher.

**Comment by JensMadsen** [comment] 2022-05-18 06:51
@yihuax-msft What do you suggest then? Should I close the issue or keep it open ?

**Comment by yihuax-msft** [comment] 2022-05-18 07:10
@JensMadsen , Go ahead to close it. I have asked another engineer to improve the documentation to mention that, if a collection item is tracked in Word, the collection should also be tracked. Thanks!

**Closed as completed** 2022-05-18 10:59 UTC
Labels: Type: product bug, Area: Word
