### ISSUE TITLE
range.copyFrom() can duplicate the copied content N times in the range where it is copied to

### ISSUE THREAD

**Issue by timbeese** [OfficeDev/office-js#2674] opened 2022-06-29 19:05 UTC
I am working on an add-in that reads in a worksheet and then copies the content from that worksheet into a different range of cells on another worksheet.  In certain circumstances the content is duplicated.  I have reproduced the issue with ScriptLab.  In general, it appears that if the rows or columns in the destination range are an exact multiple of the rows/column in the source range, the available space is filled up.

## Your Environment
I reproduced this on my desktop PC using the Excel desktop client.
Excel version: 2108 (build 14326.21018) Semi-Annual Enterprise Channel
Desktop is Windows 10 versino 21H2 (OS Build 19044.1706)
 
## Expected behavior
I expected the copyFrom() function to only copy one instance of the data, which is does in MOST cases.  It's only when the destination range is an exact multiple greater in either rows or columns that the content is replicated again.

## Current behavior
If I have a 3x3 range of cells that I want to copy, and I use the copyFrom function to copy this into a 6x3 or 3x6 range of cells, I get 2 copies of the 3x3 data.  If I have a 6x6 range of cells, I get 4 copies (essentially a 2x2 grid of the same content).

## Steps to reproduce
1. Create a blank snippet in ScriptLab and set it up to run the following code: 
```
async function run() {
     await Excel.run(async (context) => {
            const sheet = context.workbook.worksheets.getActiveWorksheet();
            const dataRange = sheet.getRangeByIndexes(1, 6, 3, 3);
            const selectedRange = context.workbook.getSelectedRange();
            selectedRange.copyFrom(dataRange);
            await context.sync();
          });
        }

```

3. Put some content in cells G2:I4, since those are the cells that are referenced with the getRangeByIndexes() function.
4. Select A1:C3 and run the snippet, the content comes over fine.
5. Select A1:C6 and run the snippet, the content comes over twice.  This is exactly twice the height of the source.
6. Select A1:C7 and run the snippet, the content comes over fine.

You can continue this pattern, but any time the rows and the columns are BOTH a multiple of 3 (which is the size of my data), the content is replicated such that it fills the entire selected region.  If either one of the dimensions is not a multiple of 3 in this case, then the content is only brought over once.

## Context
My add-in creates data tables in xlsx format, which I insert into the workbook using base64 and then copy the data from the new worksheet into the worksheet where the user specified they want it.  If they update the data, I delete the old data and replace it with new data.  We found that if they created 2 of the exact same table, and then updated their code to only create one table, when they update the worksheet, the first table was still coming over twice because we selected the range to clear out first, which happened to be exactly twice the height of the data we were copying over.

**Comment by preethikakiru** [comment] 2022-06-30 06:04
Thanks for submitting this issue @timbeese. I will do some investigation and get back to you.

**Comment by SiruiSun-MSFT** [comment] 2022-07-04 08:42
Hi @timbeese, 

Thanks for letting us know this issue. However, regarding the question you raised, now the behavior of the API and the native feature (UI) is consistent, and we will fill in the form as much as possible when they are under integer multiple, which is by design.

Thanks, Microsoft 365 Developer Platform team

**Comment by jayrathi** [comment] 2022-07-06 23:34
@timbeese, as Sirui said, the api behavior is same as what happens in Excel UI, so this behavior is as designed. My recommendation for your problem is to have slightly tweak your code like this 
`selectedRange.getCell(0,0).copyFrom(dataRange)`

By selecting just the first cell, you will only end up creating one copy of the data.

**Comment by timbeese** [comment] 2022-07-11 18:20
I didn't realize that it behaved that way with normal copy and paste, but indeed it does.  So yes, this is working as designed.  I've implemented the suggested workaround to move data into the top left cell and that is working nicely.  Thanks!

**Comment by wandyezj** [comment] 2022-07-11 19:24
@AlexJerabek While the behavior is consistent with the UI, there is no mention of this behavior in the [range.copyFrom API documentation](https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-copyfrom-member(2))

Would it make sense to update the documentation with this information?

**Comment by AlexJerabek** [comment] 2022-07-11 19:56
@wandyezj, sure we can expand that documentation. @alison-mk, could you please draft the update and track this in our internal spreadsheet?

I believe we can close this issue in the meantime.

**Comment by alison-mk** [comment] 2022-07-12 18:06
I've recorded a request to update to this API description in our internal tracking spreadsheet, and the change will be included in our next batch of reference documentation updates. I will close this issue in the interim. Thanks for the contribution, @timbeese! 

Cheers, 
Alison

**Closed as completed by alison-mk** 2022-07-12 18:06 UTC
Labels: Area: Excel, Status: in backlog, Type: doc request
