### ISSUE TITLE
displayDialogAsync results in erroneous Display Dialog Error 

### ISSUE THREAD

**Issue by parlato-vooma** [OfficeDev/office-js#4105] opened 2024-02-06 18:23 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: https://outlook.office365.com/
* Browser (if using Office on the web): Chrome
 
## Expected behavior
When I use displayDialogAsync with a valid URL, the URL is opened in a dialog window.

## Current behavior
Currently, attempting to open a valid URL results in an error. This does not occur at https://outlook.live.com; it only occurs when using 365. 

Here is the relevant code snippet, with logs added for debugging:
```typescript
  Office.context.ui.displayDialogAsync(loginUrl, dialogOptions, (result) => {
    console.log('URL', loginUrl);
    console.log('RESULT:', result);
    const dialog = result.value;

```

And here is the console when I invoke the above:
<img width="1239" alt="Screenshot 2024-02-06 at 10 14 19 AM" src="https://github.com/OfficeDev/office-js/assets/150725007/c67f1449-7370-4b58-95e0-3982e5162700">

Here is the result of inspecting the task pane, proving that the URL of the taskpane (https://localhost:3033) is supported, and therefore https://localhost:3033/login (the URL the dialog is attempting to open as shown in the console logs) should also be supported. 

Finally, I'll note that the manifest includes the following code snippets:
```xml
  <AppDomains>
    <AppDomain>https://localhost:3033</AppDomain>
  </AppDomains>
```

``` xml
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:3033"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
```

**Comment by neprasad-microsoft** [comment] 2024-02-16 11:15
Hi @parlato-vooma 
As a workaround, could you try adding https://localhost:3033/login also in your AppDomain and test?

**Comment by parlato-vooma** [comment] 2024-02-21 21:42
@neprasad-microsoft that does seem to have worked, though my understanding was that this would not be necessary based on the documentation [here](https://learn.microsoft.com/en-us/javascript/api/manifest/appdomain?view=common-js-preview).

I've already specified https://localhost:3033 in `<SourceLocation />`. Also, the below docs seem to directly contradict the solution:

```
Specifying a domain in an <AppDomain> isn't necessary for Office on the web or to open a resource in an IFrame, nor it is necessary for opening a resource in a dialog opened with the [Dialog API](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins).
```

```
* Listing the same domain as the one specified in the [SourceLocation element](https://learn.microsoft.com/en-us/javascript/api/manifest/sourcelocation?view=common-js-preview) has no effect and may be misleading. In particular, when you are developing on localhost, you don't need to create an <AppDomain> element for localhost.
* Don't include any segments of a URL past the domain. For example, don't include the full URL of a page.
```

**Comment by DivyaPatidar** [comment] 2024-03-05 09:06
@parlato-vooma The issue regarding localhost needed in AppDomain is duplicate of #3926 . Closing this issue, you can follow issue #3926 for updates.

**Closed as completed by DivyaPatidar** 2024-03-05 09:06 UTC
Labels: Area: Outlook, Resolution: duplicate
