### ISSUE TITLE
Custom function in angular not working in excel desktop

### ISSUE THREAD

**Issue by shyambhiogade** [OfficeDev/office-js#1043] opened 2020-03-14 05:44 UTC
I have a task pane application which i have modified it to also have custom function. Its developed in angular, My test application works in the online version of excel but it does not work in excel desktop, when addin is loaded it says there is a problem with the custom function 

## Expected Behavior
Custom function should work with angular application, if there is any example of using custom function in angular, please point me to it.

## Current Behavior
custom function developed in angular is not working

**Comment by shyambhiogade** [comment] 2020-03-14 23:30
@bdentino @RuoyingLiang @sumurthy can you please reply, the example provided in documentations are very basic and does not cover real life scenario, what is the best practice on reusing the code when you have taskpane and custom function which does similar thing.

**Comment by keyur32** [comment] 2020-03-16 19:46
Hi there, I think this is a duplicate of #1044 . I responded on there. Closing this issue out as a dup

**Closed as completed by keyur32** 2020-03-16 19:46 UTC
Labels: Resolution: duplicate
