### ISSUE TITLE
Web add-in not loading in old Outlook windows version

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#4705] opened 2024-07-23 01:46 UTC
We are writing to report an issue with our Office Add-in that utilizes the ItemSend event. The add-in was deployed centrally via the Microsoft Admin Center approximately one month ago and was functioning properly for some time. However, since last week, the add-in has ceased to function. This issue has persisted since the initial occurrence, rendering the add-in unusable.It is noteworthy that this issue is only affecting a subset of users within the organization.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows OS
* Browser (if using Office on the web): -

## Expected behavior
The ItemSend event should execute whenever an email is sent.

## Current behavior
The ItemSend event does not trigger when sending emails.

## Steps to reproduce
1. Access the "Link to live example(s)" (Provide the link here)
2. Download "Office-addin-sample" and place it in the desired location.
3. Access the Microsoft Admin Center.
4. Deploy the custom add-in using the manifest.xml file.
5. Wait for at least 24 hours.
6. Open a command prompt and navigate to the corresponding directory.
7. Run "npm install".
8. Run "npm run dev-server".
9. open Outlook.

## Link to live example(s)
[URL](https://github.com/mailchecktool-admin/Office-addin-sample)

We have received feedback from customer requesting improvements.
Please investigate and make necessary improvements.

**Comment by neprasad-microsoft** [comment] 2024-07-23 06:46
Hi @mailchecktool-admin 
Since this is only occurring for a subset of users, we will need some more information to debug -

- Please collect logs and share with us. Steps to collect logs - https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues
- Does this happen only on Legacy Outlook or New Outlook, Outlook on the Web and Mac also?
- How many users are impacted?
- What do you mean the add-in has ceased to function? If possible, attach a working and a non-working video.
- For the accounts where it is not working, does sideloading work? 

For sharing files, you can create a private repo and give access to exextoc.

**Comment by mailchecktool-admin** [comment] 2024-07-25 06:31
We will share logs and screen recordings of any glitches that occur.
▷https://github.com/mailchecktool-admin/addinError

We have created an add-in that displays a pop-up when sending an email, but when the email is sent, the extension does not work and goes through.
Additionally, the icon that used to appear in the extension list is no longer displayed.
Please check the screen recording you have made for detailed operation.

I have confirmed that this occurs in the new Outlook, Outlook on the Web as well as the traditional Outlook.
I have not been able to confirm this for Mac as I do not have the media.

We are currently receiving similar inquiries from three companies that are deploying add-ins.

We have confirmed that this event does not occur when the add-in is installed individually as a custom add-in, but occurs when the add-in is deployed from the Microsoft Management Center.

Please review the contents and investigate.

**Comment by neprasad-microsoft** [comment] 2024-07-25 07:32
Hi @mailchecktool-admin 
The logs you shared do not have all the data. Please start collecting the logs before you launch Outlook on the Web . 
Also, if possible, share the manifest of your add-in so that we can repro and debug locally.
"We have confirmed that this event does not occur when the add-in is installed individually as a custom add-in, but occurs when the add-in is deployed from the Microsoft Management Center."
Do you mean that the issue is only on locally installed add-ins?

**Comment by mailchecktool-admin** [comment] 2024-07-25 07:53
New log information was obtained and the repository was updated.
The problem occurs “when deployed from Microsoft Management Center”.

Since this is a private program and I cannot share it here, I would like to know a reliable email address to send it to so that I can share it via email if necessary for the investigation.

**Comment by neprasad-microsoft** [comment] 2024-07-26 11:42
Hi @mailchecktool-admin 
The new HAR file attached is corrupted. We are unable to open the file and it gives "Invalid File" error. Could you please attach the logs again?
Also, you can share the manifest in the same private GitHub repo and we can let you know once we download it. After that you can delete it.

**Comment by mailchecktool-admin** [comment] 2024-07-29 00:49
My apologies. I have re-submitted the corrupted HAR file as “outlook.office.com.zip”.

**Comment by mailchecktool-admin** [comment] 2024-07-29 04:29
I have shared the manifest file with you.
▷https://github.com/mailchecktool-admin/addinError/blob/main/manifest.xml

**Comment by mailchecktool-admin** [comment] 2024-07-31 02:42
We will share additional information with you.
[On the screen I checked from [https://aka.ms/olksideload], I see an add-in both in “Personal Add-Ins” and in “Admin Management” (the name of the add-in is Mail Checker). 
![addinImage](https://github.com/user-attachments/assets/cd4d016b-b497-4b01-8136-ed9043267252)

However, the add-in is not displayed on the Microsoft365 application screen that is displayed from the □ Add-in button > [Add App].
![addinImage2](https://github.com/user-attachments/assets/81f74621-95b0-4ab7-8812-c9da53b6e567)

When sending an email, the email is sent without the startup message being displayed, so I suspect that the ItemSend event is still not being executed.

**Comment by mailchecktool-admin** [comment] 2024-08-06 04:03
@exextoc 　@neprasad-microsoft 
Have you made any progress in your investigation based on the information I shared?
Please let me know if you have made any progress.

Also, please let me know if there is any additional information you would like me to share.

**Comment by mailchecktool-admin** [comment] 2024-08-16 01:12
@neprasad-microsoft @exextoc 
I have repeatedly provided information and posted comments to inquire about the situation, but I have not received a response. Multiple customers who have subscribed to our add-in are complaining that they cannot use it. Could you please provide me with an update on the current investigation status?

**Comment by siduraisamy** [comment] 2024-08-16 11:04
Hi @mailchecktool-admin, the HAR file shared is still having issues to open. Please check the below snapshot: 
![image](https://github.com/user-attachments/assets/c18b40c7-68ff-434c-919c-b1619fe4a55b)

We could see from the recording, that the "Mail Checker" is not getting displayed in the applist in the compose and hence it make sense that it is not getting executing while sending. The HAR file will give more information for the cause. Please sharing working file. Before uploading it again, please try to open the har file and check for proper working.

**Comment by sivachandran-msft** [comment] 2024-08-16 11:06
Hi @mailchecktool-admin, the HAR file shared is still having issues to open. Please check the below snapshot: 
![image](https://github.com/user-attachments/assets/c18b40c7-68ff-434c-919c-b1619fe4a55b)

We could see from the recording, that the "Mail Checker" is not getting displayed in the applist in the compose and hence it make sense that it is not getting executing while sending. The HAR file will give more information for the cause. Please sharing working file. Before uploading it again, please try to open the har file and check for proper working.

**Comment by mailchecktool-admin** [comment] 2024-08-19 03:29
@sivachandran-msft @exextoc 
Sorry. I copied the contents of the har file, which I could not confirm, into a text file.
https://github.com/mailchecktool-admin/addinError/blob/main/outlook.office.com.zip
You can check it from.
Thank you in advance.

**Comment by rajjha-msft** [comment] 2024-08-20 09:14
Hey @mailchecktool-admin 

Can you please share the add-in as well as the logs, I cannot access any of those?
You can create a private GH repo with the files and share with @exextoc.

What I understood is it is not showing up when its deployed, and shows up when side loaded?
Also, when did the add-in stopped working? Is there a new deployment post which it happend ?

**Comment by mailchecktool-admin** [comment] 2024-08-21 09:04
@rajjha-msft @sivachandran-msft @exextoc 
I have added “exextoc” to the collaborator,
Does this mean that you cannot see the private repository?
![スクリーンショット 2024-08-21 175503](https://github.com/user-attachments/assets/21b05570-15f2-4f66-bd69-b17bba95d9e8)

not showing up when its deployed, and shows up when side loaded?
→We have confirmed that the event occurs when the add-in is deployed from the administration center.
As for whether the event occurs when the add-in is side-loaded, basically the add-in works, but there may be some users for whom it does not work. (We have not confirmed all users.)

The add-ins stopped working around the beginning of June, but the add-ins seem to be working fine now.
Have you done any updates related to extensions between June and now?
I would like to know why the event was resolved.

**Comment by rajjha-msft** [comment] 2024-08-27 05:58
Hey @mailchecktool-admin 

We have received the logs as well as the manifest.
We are looking into it. 

Quick question, is this an intermittent issue?
Also, how many people are impacted and when did it start?

**Comment by mailchecktool-admin** [comment] 2024-08-28 00:54
@rajjha-msft 
This problem has been occurring for several users since early June.
A few of these users have been resolved, but some continue to experience the problem.
Why was the event that was occurring in a few users resolved?
Are there any possible factors? (e.g., cache effects, etc.)

**Comment by rajjha-msft** [comment] 2024-08-28 09:51
The issue might be happening due to data propagation delay (probably due to middle tier cache). 
Please let us know if you see the issue is happening more frequently and consistently.

**Comment by mailchecktool-admin** [comment] 2024-08-29 03:42
@rajjha-msft 
Is data propagation delay (intermediate layer cache) something that resolves automatically over time?
If there is a manual procedure to clear it, please let me know.
If it resolves over time, how long does it typically take to be resolved?

Why is an intermediate layer cache occurring? Is this due to an add-in related update at Microsoft?

**Comment by rajjha-msft** [comment] 2024-08-30 06:03
We are working to make the system more efficient. 
It should not happen again, and no action is required from your side.

**Comment by mailchecktool-admin** [comment] 2024-09-02 00:23
@rajjha-msft 
What caused this cache?
Is it due to an update?

We need an answer because we need to explain the user cause of the event.

**Comment by mailchecktool-admin** [comment] 2024-09-10 08:17
@rajjha-msft 
I would like a response to the question.
I am obligated to provide an answer to the customer regarding their inquiry.

**Comment by mailchecktool-admin** [comment] 2024-09-12 00:29
@rajjha-msft  @exextoc 
Why haven't you responded yet?
This issue has been occurring continuously since August 24.
If additional information is required, please let me know, and I will cooperate.

Regarding the statement, "We are working to make the system more efficient. It should not happen again, and no action is required from your side."
Does this mean:

・The investigation and recovery process on Microsoft's side has already been completed, and it will be resolved once applied,
or
・The investigation and recovery process on Microsoft's side has not yet been completed and is planned to be carried out in the future?
Which one is it?

**Comment by t-ariyoshi30907** [comment] 2024-09-21 02:28
@rajjha-msft @exextoc 
I'm facing the same issue. I've been unable to use Office Add-ins in my older Outlook interface for over a month now.

Many developers are struggling with this issue. Could you please explain what you're doing to address it?

**Comment by mailchecktool-admin** [comment] 2024-09-27 02:37
@rajjha-msft @exextoc 
I would like a response to the question.
I am obligated to provide an answer to the customer regarding their inquiry.

**Comment by mailchecktool-admin** [comment] 2024-10-21 00:35
@exextoc @neprasad-microsoft @sivachandran-msft 
"I have conducted an investigation into this issue and found something noteworthy. Re-deploying the add-in seems to improve the issue for users who experience the malfunction. Specifically, executing the following commands in PowerShell improves the situation for all users:
- Set-OrganizationAddInAssignments -ProductId "Add-in's ProductId" -Remove -Members "email address of the user to remove"
- Set-OrganizationAddInAssignments -ProductId "Add-in's ProductId" -Add -Members "email address of the user to add"

**Comment by mailchecktool-admin** [comment] 2024-10-21 00:47
For nearly a month now, I have not received any response, and it is causing significant distress. The companies that have contracts for our add-in are demanding explanations as to why this issue occurs and whether it could happen again in the future. However, we have been unable to provide a satisfactory explanation. Several companies are affected by this issue.
If we continue to be unable to provide any answers, we risk losing customers, which would be a major problem for our business.
Previously, @rajjha-msft mentioned that this might be due to the influence of the 'middle tier cache'. Is it possible that other users will suffer the same issue in the future? As the providers of the JavaScript add-in API, you have a responsibility to answer this question.

**Comment by DivyaPatidar** [comment] 2024-10-30 15:43
@mailchecktool-admin This issue occurs because there is a middle tier service that causes a delay in the add-ins showing up. Please note that this design exists because we have multiple services working in the background to ensure that deployed add-ins are accurately reflected in the client. Since it has been fixed now, we will do our best to ensure it does not happen in the future. If you do see any other issues with our APIs, please let us know.

**Comment by mailchecktool-admin** [comment] 2024-10-31 02:29
@DivyaPatidar 
Thank you for sharing that this issue has already been fixed.
We will report the problem when it occurs again.

**Closed as completed** 2024-11-01 10:21 UTC
Labels: Area: Outlook, Resolution: question answered
