### ISSUE TITLE
Can't Load Two Tabs in Add-In - Excel

### ISSUE THREAD

**Issue by FreeSoftwareServers** [OfficeDev/office-js#2521] opened 2022-04-10 17:25 UTC
# Provide required information needed to triage your issue
I'm trying to use 2 Custom Tabs in my add-in but it won't work.
https://stackoverflow.com/questions/71701547/two-custom-ribbon-tabs-in-same-office-add-in-excel-javascript

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2021 and O365
* Operating System: Win10
* Browser (if using Office on the web): ______
 
## Expected behavior

2x Custom Tabs load from same manifest

## Current behavior

Both tabs work, but whichever is defined first works.

## Steps to reproduce

1. Create basic Excel Add-In Template in VS 2022
2. Use my Manifest
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

As Add-Ins can't share Custom Tabs, I decided I'll make one Add-In for everything, but that isn't working. I can make a manifest per tab, but maintaining multiple manifests has become cumbersome and I prefer end users only install one item.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 
[ExcelWebAddIn1.zip](https://github.com/OfficeDev/office-js/files/8459556/ExcelWebAddIn1.zip)

**Comment by gingerjia** [comment] 2022-04-13 06:04
@FreeSoftwareServers, thanks very much for reporting the issue! After confirmed with feature owner, current behavior is by design that we didn't support two custom tabs for one add-in. Not sure whether multiple groups under one tab can meet your requirements or not. And another option is considering contextual tabs.  
[Create custom contextual tabs in Office Add-ins - Office Add-ins | Microsoft Docs ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice%2Fdev%2Fadd-ins%2Fdesign%2Fcontextual-tabs&data=05%7C01%7Cgingjia%40microsoft.com%7C8d3ba7dc816348949b4408da1d1fc79c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637854319606520290%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Xp0FEcCgbUk1hDyDy%2FyyI%2Fy5lK3wYMjV%2F4lp3DXjieI%3D&reserved=0)

If these all cannot unblock your side, could you help to submit a new feature request under  https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform.

Thanks!

**Comment by keyur32** [comment] 2022-04-13 15:02
Thanks @gingerjia for replying. Am closing this issue as workaround provided.

**Closed as completed by keyur32** 2022-04-13 15:02 UTC
Labels: Area: Excel, Needs: triage :mag:

**Comment by FreeSoftwareServers** [comment] 2022-04-13 16:25
> Thanks @gingerjia for replying. Am closing this issue as workaround provided.

To be clear, the workaround isnt a workaround at all. I WILL need multiple manifests for the same Add In on a per tab basis. But I appreciate the solid answer so I don't waste time trying to debug.
