### ISSUE TITLE
Dialog Freezing on Outlook Desktop when trigger with On-Send event

### ISSUE THREAD

**Issue by moshikonachmias** [OfficeDev/office-js#2089] opened 2021-08-31 05:03 UTC
Our Add-In is using the On-Send functionality and it used to work for both OWB and Desktop without any problems.
On send, we popup a dialog and the user needs to select `adding an attendee and send` or `only send` via 2 buttons.
Now, when using on Desktop, the dialog freezing without any option to click on the buttons.

## Your Environment
The issue occurs on Outlook Desktop.
Version number is below:
![image](https://user-images.githubusercontent.com/60843583/131443388-d5988d88-0004-41ba-981e-6cfedfd5ebd6.png)
![image](https://user-images.githubusercontent.com/60843583/131443512-0b433540-68b6-49ad-bb95-652a22b933be.png)
![image](https://user-images.githubusercontent.com/60843583/131443471-a0d40367-f4dd-4acc-965a-21da0b96936e.png)

## Expected behavior
Dialog not freezing, letting me choose one of the options, send the event or add an attendee and send it.

## Current behavior
Dialog is freezing, 
Once the user clicks away from the dialog the invite sends to the customer without adding an attendee.

## Steps to reproduce
Open a Dialog with on-send event.

## Context
Cann't use the add-in probably.

**Comment by exextoc** [comment] 2021-08-31 21:50
Does this issue only repro in Outlook desktop version 2108 and on appointments? How are you opening the dialog?

 Does your Office add-in dialog use cross-domain communication? If so, it will [need to be updated as per this documentation](https://developer.microsoft.com/en-us/office/blogs/action-required-update-your-office-add-in-dialog-for-cross-domain-communication/?_cache_bypass=1630098590).

If that does not work, your issue also sounds similar to issue #2055. Could you please try to use the [OnSend sample add-in](https://github.com/OfficeDev/Outlook-Add-in-On-Send) and see if the issue still repros? #2055 has repro steps for using the sample add-in as well.

**Comment by moshikonachmias** [comment] 2021-09-02 08:38
> Does this issue only repro in Outlook desktop version 2108 and on appointments? How are you opening the dialog?
- The issue only reproduced in Outlook desktop version 2108 and on appointments. It’s working fine for me on Outlook desktop for Mac and on Outlook web.
![image](https://user-images.githubusercontent.com/60843583/131787536-c2a4bed9-5fe6-4088-8421-7be12f6537ca.png)

- I'm opening the dialog with `Office.context.ui.displayDialogAsync`

> Does your Office add-in dialog use cross-domain communication? If so, it will need to be updated as per this documentation.
- That is not the case

> If that does not work, your issue also sounds similar to issue #2055. Could you please try to use the OnSend sample add-in and see if the issue still repros? #2055 has repro steps for using the sample add-in as well.
- I don't think it is similar because as I mentioned - once the user clicks away from the dialog the invite sends to the customer without adding an attendee.

**Comment by moshikonachmias** [comment] 2021-09-02 08:43
I found the bug. I sent a boolean and not a string to messageParent.

Office.context.ui.messageParent(true);
instead of
Office.context.ui.messageParent('true');

It was working for more than a year with the boolean value, it this change intended?
it's of course still working on the web and on Mac.

As well there is no error on the console when doing it.

**Comment by exextoc** [comment] 2021-09-02 21:36
Yes, this change was intended. The value in the parameter to Office.context.ui.messageParent must be a string due to compatibility problems. Office can use different browser controls, which can handle types differently. Some browsers can pass a string, integer and boolean and it will always convert the data to string, while some browsers may throw exception when it hits non-string data. To avoid this issue, the documentation for Office.context.ui.messageParent was updated to require a string.

**Comment by Tomer-Priel** [comment] 2021-09-03 08:20
How is this OK???
You guys are literally changing an API without any announcement!!
It's not a documentation change but an actual API change that caused developers add-ins to break.

**Comment by exextoc** [comment] 2021-09-03 23:20
We are following up with the product team about this issue and will update once we have more information.

**Comment by pkkj** [comment] 2021-09-04 03:28
We are also wondering how will your code handle this boolean value when it is picked up by the parent taskpane. Thanks.

**Comment by JuaneloJuanelo** [comment] 2021-09-08 01:26
@Tomer-Priel Sorry about this. this was effectively a breaking change, the team is working with high priority  on a fix (that only requires a change on the JS library) that will still allow the Boolean parameter to avoid breaking, however at some point we will deprecate it so we recommend you to pass a string, that's the best solution long term.

**Comment by exextoc** [comment] 2021-09-15 05:30
The fix for this has been deployed. The updated JS should be available as caches clear.

**Comment by Tomer-Priel** [comment] 2021-09-15 12:31
Thank you @JuaneloJuanelo @pkkj much appreciated!

**Comment by IvanFranic** [comment] 2021-09-21 03:54
We are impacted by this issue and our users are unable to send email from OWA
They are getting the following error “Janusseal App is working on your request.

**Comment by AlexJerabek** [comment] 2021-09-21 16:13
Pinging @exextoc to look at @IvanFranic's latest comment.

**Comment by IvanFranic** [comment] 2021-09-21 23:57
> Pinging @exextoc to look at @IvanFranic's latest comment.

Thank you for the ping. We use JanusSeal Web App and in OWA. We are unable to send any emails. Outlook only shows a notification in the upper area of the message bar saying "Janusseal App is working on your request", without ever showing its classification dialog to the sender.

**Comment by exextoc** [comment] 2021-09-23 01:55
@IvanFranic A fix for this original issue with the dialog freezing was deployed last week. However, there's similar issue in OWA (#2129) that was just recently fixed.

Could you check the description of #2129 and also check whether your issue still reproes (since the OWA issue was fixed after your original comment)? If it still reproes and #2129 doesn't describe your issue, please open a new issue for it. Thank you!

**Comment by exextoc** [comment] 2021-09-23 01:59
Closing this issue to reflect that a fix was deployed to Production (as of September 14th).

**Closed as completed by exextoc** 2021-09-23 01:59 UTC
Labels: Area: Outlook, Status: fixed

**Comment by moshikonachmias** [comment] 2021-09-29 13:23
Thank you @exextoc for the fix.
Can you please advise how long, and when, the caches on Outlook Desktop clear? 
Attempting to uninstall and reinstall the add-in seems to have no effect.
