### ISSUE TITLE
executeRichApiRequestAsync undefined in Word online

### ISSUE THREAD

**Issue by mihao2002** [OfficeDev/office-js#404] opened 2019-02-22 16:45 UTC
## Expected Behavior
I created an Office js app which runs well in Word win32, and I assume that it can run well in Word online as well because all Office js APIs I use are supported.

## Current Behavior
but when I hook it up with Word online (by using "upload my Add-in"), the app throws the following error:

> Object doesn't support property or method 'executeRichApiRequestAsync'

## Steps to Reproduce, or Live Example
The error happens at "return context.sync()" in the following code:

```
... 

Word.run(function (context) {
   var range = context.document.getSelection();
   context.load(range.paragraphs);

   var firstParagraph = range.paragraphs.getFirstOrNullObject();

   if (firstParagraph != null) {
        firstParagraph.insertText(result, Word.InsertLocation.end);
   }

   return context.sync();
}).catch(function (err) {
    $('#td_0').text(err.code + "\r\n" + err.message);
});

...
```

## Your Environment
The Word online environment is https://microsoft-my.sharepoint-df.com/personal/michaem_microsoft_com. Both IE and chrome can repro this issue.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by Zlatkovsky** [comment] 2019-02-22 18:30
The problem isn't in your JavaScript code.  Instead, it looks like the wrong internal Office.js files are getting loaded, or you are calling the method before it's ready.

What is your HTML page like, with the script reference to Office.js?
And, are you using `Office.onReady/Office.initialize`?

**Comment by mihao2002** [comment] 2019-02-22 18:39
The Office.js reference is as bellow
`<script src="https://appsforoffice.microsoft.com/lib/beta/hosted/office.js"></script>`

And my HTML page has the following script in the end to do the initialization:
```
    <script>
        Office.onReady(function (info) {
            $('#searchForm').show();
            if (info.host === Office.HostType.Word) {
                $('#message').text('Office Word');
                inOfficeWord = true;
            }
        });
    </script>
```

And the method is called after the above script executes for sure. 
Question: will that be a problem to invoke that method inside an iframe? or the iframe also needs to do the Office.onReady thing by itself?

**Comment by mihao2002** [comment] 2019-02-22 18:40
BTW, same error happens if I use the production script as below:
`<script src="https://appsforoffice.microsoft.com/lib/beta/hosted/office.js"></script>`

**Comment by Zlatkovsky** [comment] 2019-02-22 18:53
Ah.  Are you inside an iframe?  That would explain it.

Office.js was designed to operate at the top-level of the page (that is, it assumes that its parent frame, if any, is Office Online).  So if you have it inside of an iframe, it won't work.

If your iframe happens to be on the same domain as your outer page, you might be able to "share" variables by doing "iframe.contentWindow.Office = window.Office"; "iframe.contentWindow.Excel= window.Excel"; etc.  (and note, only doing this after you've waited for an Office.onReady at the outer layer)  But if you're on the same domain, it begs the question of whether you need the iframe in the first place.

**Comment by mihao2002** [comment] 2019-02-23 05:59
I tried to share "Office" between t he top-level window and the iframe, but it doesn't work. Below is my sample code:

The top-level:

```
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
</head>
<body>
    <div id="msgPanel" style="max-width:400px;">This is Office JS test</div>
    <iframe src="/iframesample.html" id="frame1" style="margin-bottom:10px;width:450px;height:350px;" scrolling='no' frameborder=1></iframe>    
    <script>
        Office.onReady(function (info) {
            let frameLocator = '#frame1';
            let myFrame = $(frameLocator)[0];
            let cw = myFrame.contentWindow;

            cw.Office = window.Office;
            cw.Word = window.Word;

            $('#msgPanel').text("ready");
        });
    </script>
</body>
</html>

```
The iframe Html (iframesample.html):

```
<!DOCTYPE html>
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
    <script>
        function insertText() {
            Word.run(function (context) {
                var body = context.document.body;
                context.load(body, 'text');
                body.insertText('This is text inserted after loading the body.text property',
                    Word.InsertLocation.end);
                return context.sync();
            }).catch(function (err) {
                $('#msgPanel').text(err.code + "\r\n" + err.message);
            });
        }
    </script>
</head>
<body style="background-color:lightgray;">
    <div id="msgPanel" style="max-width:400px;">This is Office JS insertion test in iframe.</div>
    <a href="javascript:insertText();">test</a>
</body>
</html>
```

Clicking the hyperlink in the iframe will end up with the following error message showing up:

> undefined
>  OSF.DDA.RichApi.executeRichApiRequestAsync is not a function

While the same page runs well in Word win32.

Thanks
Michael

**Comment by Zlatkovsky** [comment] 2019-02-23 21:27
I think the part you're missing (or rather, over-including) is the script reference to office.js in the iframe.  You do **not** want to have one inside the iframe.  Instead, the `Office`/`Word`/etc variables must all come from the parent, just like you're doing.

FWIW, if you want to see a live version of this working, Script Lab uses this same mechanism for the runner.  Search for `officeNamespacesForIframe` within the <https://github.com/OfficeDev/script-lab> codebase.

Wrt. to your question (or implied question) about why it would work in win32 vs Online -- the two use completely different mechanisms for communication.  The win32 one appears to be effectively less constrained (able to talk with Office even if it's inside an iframe) whereas the Office Online one is definitely more constrained.

**Comment by mihao2002** [comment] 2019-02-24 01:27
It works after removing the reference in the iframe page! Thanks!

**Comment by Zlatkovsky** [comment] 2019-02-24 03:11
Glad it helped.  Marking the issue as a a resolved question, then, and closing it.

**Closed as completed by Zlatkovsky** 2019-02-24 03:11 UTC
Labels: Needs: attention :wave:, Status: fixed
