### ISSUE TITLE
smart alerts -onmessagesend event 

### ISSUE THREAD

**Issue by benkridamira1** [OfficeDev/office-js#2970] opened 2022-11-14 15:52 UTC
When trying to use onmessagesend event to create smart alert in my desktop outlook , i couldn't have the expected behavior such described in the documentation .
i think the problem is in the SendMode attribut in the manifest but a not sure about that .

**Comment by timwan10** [comment] 2022-11-14 21:58
Could you provide more details on your build version, manifest, JS code, what you expect to happen, and what is happening?

**Comment by benkridamira1** [comment] 2022-11-15 10:10
i used this documentation for smart alerts :  https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest 
i changed the manifest.xml , and created the launchevent.js file exactly as described  .
i supposed to have a popup before sending the mail like this 
![smartAlerts](https://user-images.githubusercontent.com/77399009/201891953-9e884354-f33c-42ba-80ec-b652d6f2c35b.PNG)
 but i got nothing , the mail is send like if i didn't implement onmessagesend event 
PS: it doesn't work on desktop and on web .
In web version i got this result (shown in the video)

https://user-images.githubusercontent.com/77399009/201892327-ab453987-6d48-41f4-beba-344425e120cf.mp4

**Comment by exextoc** [comment] 2022-11-15 20:16
What version AND build of Outlook win32 are you on? 

Also just doing a sanity check, but the Javascript in the example you linked is checking for the words "send", "Picture", "document" and "attachment". I don't see those words in your video that you are testing? 

i.e. in the video, it looks like it is working as intended. You sent an email, but did not contain any of the check words, so it did not check attachments. A message popped up that said it was working, it sees that you did not forget any attachments, and sends the mail for you. 

You could also adjust the JS to always return allowEvent: false, to see if it is working.  

Another thing to check is to enable runtime logging: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging

And check the outputs of the log to see if there are any obvious errors. (note that I believe you have to create the log.txt file that the registry points to)

![image](https://user-images.githubusercontent.com/28549921/202016922-ddc65787-c3c9-47af-9bc8-622edf8e749c.png)
 
In Win32 you can also check to see if the javascript file has indeed been downloaded by Outlook: 

It will be in: 

`C:\Users\[user data]\AppData\Local\microsoft\office\16.0\wef\{A98BE375-791E-4897-A0DB-B890ACCD00C6}\Nq80fH5b+wP8w5IPlMbxcg==\Javascript`

Note that the GUID and + Encoding directory names will vary for you. If you have multiple GUID/Encoding directories, it is due to multiple Profiles or Exchange accounts. It is ok to delete the WEF folder then reboot outlook, and outlook will recreate those.

**Closed as completed** 2022-11-25 05:01 UTC
Labels: Area: Outlook, Needs: author feedback, Type: product question, Status: no recent activity
