### ISSUE TITLE
Excel undo stack is cleared when adding/refreshing a custom function exposed through an Excel add-in that uses shared runtime

### ISSUE THREAD

**Issue by adim1973** [OfficeDev/office-js#3317] opened 2022-10-11 15:03 UTC
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

Excel undo stack should not be cleared.

# Current behavior

The Excel undo stack is cleared once a custom function exposed through an Excel add-in that uses shared runtime is entered or refreshed.

## Steps to Reproduce

1. Follow the [Microsoft tutorial](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows) on creating custom functions.
2. [Upgrade the project to use a shared runtime](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime).
3. Enter any of the prebuilt custom functions (I used CONTOSO.ADD).
4. Excel undo stack is cleared whenever the function is entered or refreshed.

LATER EDIT:
- I just figured out (and tested) that the undo issue appears only if "shared runtime" is used. A simple custom functions project created through Yeoman generator will not present the undo bug. Once the project is upgraded to use the shared runtime (by using [these steps](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime)) will start clear the undo stack when a custom function is entered/refreshed.

## Context

Updated due to shared runtime vs JavaScript only runtime findings.

* Operating System: Windows, MAC

## Failure Logs

![2022-10-11_17h42_15](https://user-images.githubusercontent.com/5249431/195126692-1f4dea9d-5f24-4b86-913d-21d0adf1a642.gif)

**Comment by adim1973** [comment] 2022-10-12 16:03
Another finding, maybe it helps: even in a JavaScript-only runtime, where there is no problem with the undo when typing in a cell a custom function or refreshing the existing ones, when a custom function is written in a sheet by using a taskpane button, the undo stack is cleared.

**Comment by rundongmsft** [comment] 2022-10-13 07:05
Hi @adim1973, it is glad to see you researched this issue and provided a detailed description! We're working on this important feature, and in fact have made good progress.
So far, "let CF support undo" has supported first-party add-ins. This is the reason why you observed that the CFs in Script Lab does not clear undo stack. As for third-party add-ins, this feature is not ready, clearing the undo stack is still the expected behavior. Because this feature may bring some unsafe factors, we are still troubleshooting and fixing bugs on it. For example, you sometimes encounter that CF does not clear undo stack in third-party add-ins, which is actually a bug. :) Thanks for the important information to reproduce this bug! This bug and workaround are under discussion, I will update if there is progress.

**Comment by celluj34** [comment] 2022-11-22 20:12
FYI my team has also been struggling with this. As far as we can tell, this has been the expected result since VBA add-in days. Any time you write to the sheet, the undo stack is cleared.

**Comment by adim1973** [comment] 2022-11-22 20:14
It's not happening in a JavaScript only runtime though, so it can be solved. It also doesn't happen in VSTO.

**Comment by AlexJerabek** [comment] 2023-04-25 18:16
Transferring this issue to the [office-js repo](https://github.com/OfficeDev/office-js), where product issues can be better tracked.

**Comment by gmichaud** [comment] 2023-10-23 12:53
We are struggling with this as well, customers moving from our XLL/COM-based add-on are complaining about this. @rundongmsft has there been any progress since last year? Thanks!

Note that there are 3 GitHub issues tracking this: #2543 #3317 and #2802 -- there's a considerable number of comments from users requesting this, hopefully the total volume of feedback is taken into account while prioritizing this enhancement!)

**Comment by gmichaud** [comment] 2023-10-23 12:56
(There are 3 GitHub issues tracking this: #2543 #3317 and #2802 -- there's a considerable number of comments from users requesting this, hopefully the total volume of feedback is taken into account while prioritizing this enhancement!)

**Comment by AlexJerabek** [comment] 2023-10-23 14:26
@cproscia, can you speak to this?

**Comment by gmichaud** [comment] 2023-12-14 14:09
Good morning. I'm on Excel 16.81, and just noticed that undo started working for me. We use the shared runtime and it previously completely broke the undo stack. Recording: https://www.loom.com/share/df6326db94934884b15e641a2c46df3a

Is that a Christmas miracle?

**Comment by M00d5** [comment] 2023-12-14 14:16
I received a message from Microsoft saying it would be fixed in the october fork - this could be it. Need to confirm - however it is not shown in their updates @gmichaud

**Comment by M00d5** [comment] 2023-12-14 14:17
![image](https://github.com/OfficeDev/office-js/assets/34275194/6fdf9960-3d1f-42b7-aa85-7435ec45ad33)](https://learn.microsoft.com/en-us/officeupdates/current-channel?redirectSourcePath=%252farticle%252f95c8d81d-08ba-42c1-914f-bca4603e1426)[ @gmichaud

**Comment by M00d5** [comment] 2023-12-14 14:17
@gmichaud https://learn.microsoft.com/en-us/officeupdates/current-channel?redirectSourcePath=%252farticle%252f95c8d81d-08ba-42c1-914f-bca4603e1426

**Comment by gmichaud** [comment] 2023-12-14 14:17
@M00d5 this is so good it's almost worthy of a press release and an onstage demo with Satya Nadella.

**Comment by M00d5** [comment] 2023-12-14 14:27
I see youre using a mac, im on windows, still not working sadly.

**Comment by gmichaud** [comment] 2023-12-14 14:32
@M00d5 for once Mac users get something first!

**Comment by adim1973** [comment] 2023-12-14 15:02
Seems to be working fine for me.

- Windows 11, Excel Version 2311 Build 16.0.17029.20028)
- Mac Sonoma, Excel Version 16.80 (23121017)

It's a miracle!

**Comment by paco-sparta** [comment] 2023-12-15 02:11
Same windows and macos version and I cannot repro in either. The Undo stack is still destroyed whenever our addin does an operation.

I'll experiment more next week!

**Comment by Kernelkun** [comment] 2023-12-15 14:39
Same here as @paco-sparta. We are using shared time, but is not working still :(

**Comment by paco-sparta** [comment] 2023-12-18 12:17
@gmichaud @adim1973 were you using streaming functions, or just modifications through `Excel.run`?

**Comment by wh1t3cAt1k** [comment] 2023-12-19 01:36
@paco-sparta we did not experiment specifically with Excel.run in this context (though our add-in contains logic that does invoke it). Mostly, though, our add-in just returns values from non-streaming custom functions. Shared runtime. 

Even in that scenario the Undo used not to work, however. Therefore, it would be great to hear some sort of confirmation from the Microsoft team that it is now supported, and if yes, to what extent and with which limitations.

**Comment by 4tti** [comment] 2024-01-17 16:05
Not working on my end, not with excel.run nor with just custom functions calculation and I am on 16.0.17029.20140 😭

**Comment by wh1t3cAt1k** [comment] 2024-01-19 12:34
I also received a report internally that it doesn't work. Has there been a regression?

**Comment by prasadhpshenoy** [comment] 2024-01-29 23:32
I am on Version 2312 Build 16.0.17126.20132 and the Undo functionality is still not working. Is there any update??

**Comment by zhenhuangMSFT** [comment] 2024-02-04 05:51
Thanks for all the patience! We will get back to you soon.

**Comment by zhenhuangMSFT** [comment] 2024-02-05 09:04
Hi All, unfortunately we still don't support the undo. It is still in our backlog. For add-ins that have this working, please note that this support is not official. Thanks for your understanding!

**Comment by grangeryy** [comment] 2024-03-05 07:56
@wh1t3cAt1k, there might be incorrect information here. JS APIs undo is not supported but Custom Function undo stack should be already supported. Custom Function for undo for Windows/Mac was recently 100% supported on Current Channel starting from build 17003.15021. And for Monthly Enterprise Channel, it will be supported starting from build 17231.20236 (expected available in March). This improvement works for normal custom functions and streaming functions. 

But please note that undo supports for Excel JavaScript APIs and custom functions that call Excel writing JavaScript APIs are not included, as we don't encourage this type of use pattern, details see [Limitations of calling Excel JavaScript APIs through a custom function] (https://learn.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function#limitations-of-calling-excel-javascript-apis-through-a-custom-function).

Let us know if it doesn't work for you:)

**Closed as completed** 2024-03-12 12:40 UTC
Labels: Type: product bug, Needs: author feedback, Status: fixed

**Comment by wh1t3cAt1k** [comment] 2024-03-13 16:52
Thank you @Wenjun-Gong for all your effort here, great job guys! We confirm it's working for us now.

**Comment by M00d5** [comment] 2024-03-13 16:55
Thank you all !! Would like to confirm it works too!

**Comment by iambacon** [comment] 2024-10-24 09:39
@grangeryy Can anyone confirm if the Undo functionality is expected to work with streaming custom functions?

I am using the latest Yeoman (React) template, configured to use both the shared runtime and custom functions. While simple, non-streaming custom functions like `add` work as expected without affecting the Undo stack, I am encountering an issue with streaming functions. For instance, when using a streaming function like `clock`, the Undo functionality no longer works.

Is this a known limitation, or is there a workaround for enabling Undo in the context of streaming custom functions?
