### ISSUE TITLE
This problem still exists, I set the line spacing to 30 points through code, but it shows up as multi-block 2.5 on word. In fact, the fixed value of 30 points and multi-line spacing 2.5 do not look consistent.

### ISSUE THREAD

**Issue by Axios1027** [OfficeDev/office-js#3203] opened 2023-03-08 08:51 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

              This problem still exists, I set the line spacing to 30 points through code, but it shows up as multi-block 2.5 on word. In fact, the fixed value of 30 points and multi-line spacing 2.5 do not look consistent.
![image](https://user-images.githubusercontent.com/45395511/223665014-cda07878-6415-4d11-9adc-dc8ff11d1fc6.png)
![image](https://user-images.githubusercontent.com/45395511/223665550-f2a89bb1-1827-45b3-b3f9-f1571a638a86.png)

_Originally posted by @Axios1027 in https://github.com/OfficeDev/office-js/issues/2296#issuecomment-1459757117_

**Comment by alison-mk** [comment] 2023-03-10 00:25
Hi @Axios1027, thank you for submitting an issue. So that we can help resolve this issue, can you use our bug report template and provide the following information? 


# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Axios1027** [comment] 2023-03-10 00:49
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: MAC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: _Microsoft 365 16.70（23021201）_
* Operating System: macos 13.2.1 (22D68)
* Browser (if using Office on the web): _/_
 
## Expected behavior
![image](https://user-images.githubusercontent.com/45395511/224193847-2f772a2a-48ec-4ed4-a8f3-8fa81428b6fd.png)
## Current behavior
![image](https://user-images.githubusercontent.com/45395511/224193909-f17adfa1-6b2a-4293-8e72-ffeba28e25b5.png)
## Steps to reproduce
1. follow this tutorial：https://learn.microsoft.com/zh-cn/office/dev/add-ins/tutorials/word-tutorial?view=word-js-preview
2. run this code：
`async function applyHeaderStyle() {
  await Word.run(async (context) => {

    const doc = context.document;
    const selecttext = doc.getSelection();
    selecttext.font.name = "FZXiaoBiaoSong-B05S";
    selecttext.font.size = 22;
    const selectparagraph = selecttext.paragraphs.getFirst()
    selectparagraph.alignment = "Centered"
    selectparagraph.spaceBefore = 0
    selectparagraph.spaceAfter = 0
    selectparagraph.lineSpacing = 30

    await context.sync();
  })
    .catch(function (error) {
      console.log("Error: " + error);
      if (error instanceof OfficeExtension.Error) {
        console.log("Debug info: " + JSON.stringify(error.debugInfo));
      }
    });
}`
 
## Link to live example(s)
1. 
2. 
3. 
 
# Provide additional details
1. I tested the same situation on Windows

## Context
## Useful logs
* [ ]  Console errors
* [x]  Screenshots
* [ ]  Test file (if only happens on a particular file)

**Comment by alison-mk** [comment] 2023-03-10 02:17
Hi @Axios1027, thank you for for the information. I've assigned this issue to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by wangyun-microsoft** [comment] 2023-03-10 02:24
@jipyua Can you please take a look at this one? Thanks.

**Comment by jipyua** [comment] 2023-04-20 07:38
hi @Axios1027 for the paragraph.lineSpacing api, the documentation says: "Gets or sets the line spacing, in points, for the specified paragraph. In the Word UI, this value is divided by 12." So setting it to 30 points means what UI shows 30/12= 2.5 lines. 

You can try from UI to set the same formatting text/paragraph to 2.5 lines or 30 pts, you will find they are the same.

**Comment by Axios1027** [comment] 2023-04-20 07:46
> hi @Axios1027 for the paragraph.lineSpacing api, the documentation says: "Gets or sets the line spacing, in points, for the specified paragraph. In the Word UI, this value is divided by 12." So setting it to 30 points means what UI shows 30/12= 2.5 lines.
> 
> You can try from UI to set the same formatting text/paragraph to 2.5 lines or 30 pts, you will find they are the same.

Hello, I understand the conversion rules for this line spacing, but as can be clearly seen from the screenshot above me, the styles of multiple line spacing 2.5 and fixed value 30 pounds are completely different. The fixed value set through API will always be automatically converted to multiple line spacing in the UI, which is not feasible for documents with specific requirements for line spacing.

**Comment by jipyua** [comment] 2023-04-20 09:07
I am using an English version Word and from UI no matter whether I set it to 2.5 lines or 30 pts, the paragraph spacing looks the same. BTW, the "line spacing" means the spacing between lines, would you please try some paragraphs with multiple lines and confirm whether the line spacing are the same? Also would you please prepare a document in your environment and share it to me so that I can confirm what's the cause?

**Comment by Axios1027** [comment] 2023-04-21 02:27
> multiple line spacing 2.5
It should be very obvious from the screenshot that the display of the two types of line spacing in Word UI is different, while the js-api always automatically converts line spacing to multiple line spacing. I searched for information and found that it can be done with vba's api.
![image](https://user-images.githubusercontent.com/45395511/233517651-f65a379b-a529-4c0a-bd2a-24b3bac76678.png)

**Comment by jipyua** [comment] 2023-04-24 01:52
thanks for reporting this, I can reproduce it now, if the font is larger then it's more obvious. we have opened an internal item 7826968 to track this, but unfortunately, I have no detailed timeline for when this can be fixed. thanks.

**Closed as not planned** 2024-04-18 18:57 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: Word
