### ISSUE TITLE
Office.context.mailbox.removeHandlerAsync is not working with documented steps.

### ISSUE THREAD

**Issue by anilreddyr7** [OfficeDev/office-js#346] opened 2018-12-29 05:37 UTC
Hello,

I am trying to run below code.

```
Office.context.mailbox.removeHandlerAsync(Office.EventType.ItemChanged, loadNewItem, function (result) {
      if (result.status === Office.AsyncResultStatus.Failed) {
        console.log("event failed");
      }
    });

function loadNewItem(eventArgs) {
  // Load the properties of the newly selected item
  console.log("event changed");
}
```

But it is failing with below exception. removeHandlerAsync it self is not getting invoked. I just followed the steps that are documented in Office API docs.

Sys.ParameterCountException: multiple optional functions in parameter list
    at Function.Error.create (MicrosoftAjax.js:5)
    at Function.Error.parameterCount (MicrosoftAjax.js:5)
    at c (outlook-web-16.01.js:9)
    at OSF.DDA.AsyncMethodCall.verifyAndExtractCall (outlook-web-16.01.js:9)
    at f.(lab5228.lab.pega.com/prweb/OutlookAddIn/aDksxW2FqLyskV_TGzmXXSRT2XjlmHkP*/anonymous function) (https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:9:73976)
    at window.OSF.DDA.OutlookAppOm.u.DDA.OutlookAppOm.value [as removeHandlerAsync] (outlook-web-16.01.js:9)
    at revokeAsyncHandler (outlookaddin_11459508741.js!sfaoutlookaddin_13410501646.js!crm_ui_harnessactions_13285258855.js!!.js:1339)
    at <anonymous>:1:1

Can some one let me know what is the reason for this exception?

**Comment by kbrandl** [comment] 2019-01-03 20:08
Closing as duplicate of: https://github.com/OfficeDev/office-js-docs-reference/issues/277.

**Closed as completed by kbrandl** 2019-01-03 20:08 UTC
