### ISSUE TITLE
AutoFill of Promise Causes Excel to Crash

### ISSUE THREAD

**Issue by GregReddick** [OfficeDev/office-js#2263] opened 2021-11-22 22:22 UTC
Trying to do an autoFill method on a promised value causes Excel to crash. I have simplified the code below as much as possible. The actual code does a fetch of the promised value from a remote server, hence the promise, but that isn't necessary to show the problem.

## Your Environment

Windows 11, Microsoft® Excel® for Microsoft 365 MSO (Version 2110 Build 16.0.14527.20270) 64-bit 
 
## Expected behavior
Excel doesn't crash!

## Steps to reproduce
1. Create a project with Yo Office, Excel Custom Functions Add-in project, TypeScript.
2. Perform installs and updates to get the sample code to run.
3. Add the following custom function to the bottom of /src/functions/functions.ts
```
/**
 * @PromiseZero
 * @customfunction
 * @returns a promise of a zero
 */
export function PromiseZero(): Promise<number> {
  // eslint-disable-next-line no-unused-vars
  return new Promise<number>(function (resolve, reject) {
    resolve(0);
  });
}
```
4. Replace the run function in /src/taskpane/taskpane.ts with this code:
```
export async function run() {
  try {
    await Excel.run(async (context) => {
      let wks: Excel.Worksheet = context.workbook.worksheets.add("Excel formula crashing bug");
      wks.activate();

      wks.getRange("B6").formulas = [["=Contoso.PROMISEZERO()"]];

      await context.sync();

      wks.getRange("B6").autoFill("B6:B11");

      await context.sync();
    });
  } catch (error) {
    console.error(error);
  }
}
```
5. Start the code. Open the task pane. Click the "run" button at the bottom.

result: Excel exits completely. On restart and recovery of the worksheet, the values have not autoFilled, so it crashed on executing the autoFill.

I have tried this with the shared runtime with the exact same result.

**Comment by preethikakiru** [comment] 2021-11-22 22:53
Hi @GregReddick, thank you for submitting this issue! I've assigned it to @dingjin-ms who will be able to provide you with more information or help resolve this issue. 
Best, 
Preethika

**Comment by GregReddick** [comment] 2021-11-23 00:54
Well, I thought the Promise was important. But if I change the function to just return a zero, instead of a Promise of a zero, it does the same crash on the autoFill. So it appears that doing the autoFill on any custom function causes the crash.
```
/**
 * @PromiseZero
 * @customfunction
 * @returns a zero
 */
export function PromiseZero(): number {
  return 0;
}
```

**Comment by chiz-ms** [comment] 2021-11-24 05:37
Thank you @GregReddick for reporting this issue regarding `Range.autoFill` API. The issue has been confirmed and tracked as ADO#5609110 in our backlog.

**Comment by dingjin-ms** [comment] 2021-11-29 03:03
Thank you @GregReddick for your reporting, we would try to fix the bug as soon as possible.

If you are using 'range.autofill' to copy the values, I'm wondering if using 'range.values' instead could unblock you first. 

```
export async function run() {
  try {
    await Excel.run(async (context) => {
      let wks: Excel.Worksheet = context.workbook.worksheets.add("Excel formula crashing bug");
      wks.activate();

      wks.getRange("B6:B11").values= [["=Contoso.PROMISEZERO()"], ["=Contoso.PROMISEZERO()"], ["=Contoso.PROMISEZERO()"], ["=Contoso.PROMISEZERO()"], ["=Contoso.PROMISEZERO()"], ["=Contoso.PROMISEZERO()"]];

      await context.sync();
    });
  } catch (error) {
    console.error(error);
  }
}
```

**Comment by GregReddick** [comment] 2021-11-29 18:43
I found that instead of performing
```
wks.getRange("B6").autoFill("B6:B11");
```
that if I did
```
wks.getRange("B7:E11").copyFrom("B6");
```
that it worked. However, this does not have all of the power of autoFill. The autoFill can copy other things besides formulas. The copyFrom, however, did solve the problem in my particular worksheet where the only thing I was interested in was copying the formulas. The autoFill should not be crashing Excel, but the workaround has me unblocked.

**Comment by dingjin-ms** [comment] 2021-11-30 02:11
@GregReddick Thank you for your information! We have found root cause of this problem and would fix it soon, will let you know when we check in the code.

**Comment by dingjin-ms** [comment] 2022-02-10 03:09
Hi @GregReddick Thank you again for reporting! We have finally checked in our fix, and the fix would be in CC in about 1 month.

**Comment by donlvMSFT** [comment] 2022-11-17 06:29
I'd like to close this thread, as the fix already released. Thanks for discussion!

**Closed as completed by donlvMSFT** 2022-11-17 06:29 UTC
Labels: Area: Excel, Type: product bug, Needs: author feedback, Status: in backlog
