### ISSUE TITLE
Unable to access shared mailbox item with REST API with token granted from admin installed add-in

### ISSUE THREAD

**Issue by jlevenssfdc** [OfficeDev/office-js#1292] opened 2020-07-22 14:12 UTC
We are working with OfficeJS in an Outlook add-in.

We're attempting to access an item in a shared mailbox using the prescribed method of getting the shared properties of an item and a rest token, handing those off to our application server where we are performing REST request from.

When we generate the token from a user installed add-in we can do this without issue using the above method.  However, when we use a token generated from an admin installed add-in we receive an error _"Access is denied. Check credentials and try again."_ .

## Expected Behavior
We can use the prescribed method for accessing shared items in the REST API regardless of installation method of add-in.

## Current Behavior
We cannot access the shared items in the REST API for admin installed add-in's.

## Steps to Reproduce, or Live Example
1) Using an admin installed add-in, get shared properties, get a token, and attempt to make a REST request with a REST client (i.e Postman).

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: All
* Host [Excel, Word, PowerPoint, etc.]: Outlook/Office365
* Office version number: anything supporting shared properties
* Operating System: any
* Browser (if using Office on the web): Chrome

**Comment by exextoc** [comment] 2020-07-22 15:05
@jlevenssfdc This appears to be duplicate of issue #1140 which we have in our backlog. Please track the same for updates. Unfortunately, we don't have any timelines to share regarding this fix.

**Comment by JuaneloJuanelo** [comment] 2020-07-22 16:32
tracked internally with bug 1496409 (BLR)

**Closed as completed** 2020-07-23 11:32 UTC
Labels: Area: Outlook, Type: product bug, Needs: triage :mag:, Resolution: duplicate
