### ISSUE TITLE
Currently, the OnSend event fires twice.

### ISSUE THREAD

**Issue by t-miyake** [OfficeDev/office-js#3562] opened 2023-08-03 03:39 UTC
# Provide required information needed to triage your issue

Currently, the OnSend event fires twice.
I have confirmed that this issue is occurring in the standard release environment.

## Your Environment

* Platform [Office on the web]:Office on the web
* Browser (if using Office on the web): Edge / Chrome
 
## Expected behavior

The expected behavior is for the OnSend add-in to run once (per add-in).

## Current behavior

The OnSend add-in runs twice. I suspect that this is because the OnSend event is firing twice.

## Steps to reproduce

Apply the OnSend add-in and send the email.

## Link to live example(s)

I have created a very simple sample. 
https://outlook.addin.app/onsend/manifest.xml

Here's the code:
```javascript
'use strict';

Office.onReady().then(function () {
    console.log('onReady');
});

function messageOnSent(event) {
    console.log('messageOnSent');
    console.log('Platform: ' + Office.context.diagnostics.platform);
    console.log('HostName: ' + Office.context.mailbox.diagnostics.hostName);
    console.log('HostVersion: ' + Office.context.mailbox.diagnostics.hostVersion);

    event.completed({
        allowEvent: true
    });
}
```

Here's the manifest file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">

  <Id>E2654AB1-1352-4DB4-ABA8-5ABDEC9B9174</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Noraneko Inc.</ProviderName>
  <DefaultLocale>ja-JP</DefaultLocale>
  <DisplayName DefaultValue="Onsend" />
  <Description DefaultValue="Onsend" />
  <IconUrl DefaultValue="https://outlook.addin.app/onsend/images/icon64.png" />
  <HighResolutionIconUrl DefaultValue="https://outlook.addin.app/onsend/images/icon128.png" />
  <SupportUrl DefaultValue="https://www.noraneko.co.jp/" />

  <AppDomains>
    <AppDomain>https://outlook.addin.app</AppDomain>
  </AppDomains>

  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.3" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemEdit">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://outlook.addin.app/onsend/function.tml" />
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteMailbox</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.8">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">
          <DesktopFormFactor>
            <FunctionFile resid="function" />
            <ExtensionPoint xsi:type="Events">
              <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="messageOnSent" />
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>
      <Resources>
        <bt:Images>
          <bt:Image id="icon16" DefaultValue="https://outlook.addin.app/onsend/images/icon16.png" />
          <bt:Image id="icon32" DefaultValue="https://outlook.addin.app/onsend/images/icon32.png" />
          <bt:Image id="icon64" DefaultValue="https://outlook.addin.app/onsend/images/icon64.png" />
          <bt:Image id="icon80" DefaultValue="https://outlook.addin.app/onsend/images/icon80.png" />
        </bt:Images>
        <bt:Urls>
          <bt:Url id="function" DefaultValue="https://outlook.addin.app/onsend/function.html" />
        </bt:Urls>
      </Resources>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
```

# Provide additional details

When the above add-in is run, the console log is output twice as shown below.
(The add-in is being executed twice.)

![image](https://github.com/OfficeDev/office-js/assets/9583126/1716ff7c-cd3d-4d01-992f-ea7d40ee64f2)

**Comment by exextoc** [comment] 2023-08-03 06:17
Thanks for reporting this issue regarding on-send event on OWA. It has been put on our backlog. We unfortunately have no timelines to share at this point 
Internal tracking id: Office: 3833425

**Comment by t-miyake** [comment] 2023-08-03 06:30
@exextoc Thanks. This issue is a major problem for our customers who use the OnSend add-in.
We request an urgent fix to this issue.

**Comment by clavx** [comment] 2023-08-03 09:21
We were able to reproduce this issue in our environment.
We are using a dialog screen in our add-in, and if it is displayed twice, it will have a significant impact on the user experience for our customers, so please respond quickly.

https://github.com/OfficeDev/office-js/assets/58804032/f62431a1-a2db-47a8-b648-55468d810698

**Comment by carlosb1504** [comment] 2023-08-03 10:05
We are also seeing this in production which is causing issues, going to need to be a priority fix!

**Comment by elemen7s** [comment] 2023-08-03 10:07
We are having this issue aswell, the ItemSend is being called twice. This should be fixed as soon as possible as it's a major issue.

**Comment by teejay001** [comment] 2023-08-03 10:08
Hi @exextoc,

This is not something that can wait as customers are starting to call in to demand explanation. Please, help resolve ASAP.

**Comment by manaunl** [comment] 2023-08-03 11:21
Our customers are experienced the same issue. Could you please resolve this ASAP

**Comment by exextoc** [comment] 2023-08-03 17:13
Apologies for inconvenience caused. We have taken this up on priority and actively working on it. This should be fixed in few hours.

**Comment by t-miyake** [comment] 2023-08-04 03:28
@exextoc Thank you for your hard work.
It's been 10 hours now, do you have an estimate on when the issue will be fixed?
We are awaiting the fix for this critical issue.

**Comment by t-ariyoshi30907** [comment] 2023-08-04 05:58
@exextoc 
The same issue is occurring with my product, and it is affecting many customers.
Is there any way for the users to resolve it themselves?
Example: Uninstall and reinstall it again.

**Comment by MehakFatima24** [comment] 2023-08-04 07:23
Hi, we are having the same issue with our add-in that breaks the functionality in production, can you please fix this on urgent basis @exextoc

**Comment by manaunl** [comment] 2023-08-04 10:21
@exextoc When do you except this to be solved? Do you mind to update us on the progress?
The last comment from you was 16 hours ago.

**Comment by t-miyake** [comment] 2023-08-05 03:38
@exextoc  This issue no longer occurs in my environment.
Have you already fixed this issue?

![image](https://github.com/OfficeDev/office-js/assets/9583126/4d9b89e8-1650-4f54-b4de-50a03d701b81)

**Comment by exextoc** [comment] 2023-08-05 13:56
We apologize for the delay in our response and any inconvenience this may have caused. 
The issue has been fixed and deployed to production. It should not be reproducible anymore.

**Comment by t-miyake** [comment] 2023-08-07 00:18
@exextoc 
In the case of add-ins deployed within the tenant from the Integrated apps or Add-ins in the Microsoft 365 admin center, it seems that the issue has not been fixed. As of now, we have confirmed that the add-in is executed twice in multiple tenants.

Even with the exact same add-in, if a user individually adds it from Custom Addins, this issue does not occur. (In this case, the issue has been fixed.)

Could you please check this issue again? 
Most of our customers are deploying add-ins within the tenant from the Microsoft 365 admin center. Therefore, the issue remains unfixed at present.

If there is a workaround, I would appreciate it if you could let me know.
Or will this issue be fixed just by waiting?

**Comment by t-ariyoshi30907** [comment] 2023-08-07 05:08
@exextoc 
The issue has not been improved in my environment either. In order to report to my clients, could you please let me know your current progress?

**Comment by manaunl** [comment] 2023-08-07 08:14
@exextoc, Our customers experienced the same issue as @t-miyake described. Could you please provide any details? When do you expect this to be resolved?

**Comment by clavx** [comment] 2023-08-07 09:27
Still facing this issue.
It has been resolved in the side-loaded add-in, but not in the Centralized Deployment add-in.

Our customers continue to be affected by this issue because they deployed add-ins in Centralized Deployment.

This issue affects Outlook on the web and new Outlook for Windows (One Outlook).
A quick fix would be appreciated.

**Comment by MehakFatima24** [comment] 2023-08-07 14:50
@exextoc Hi can you please provide an update on the fix for the case of add-ins deployed within the tenant from the Microsoft 365 admin center?

**Comment by avisheknand** [comment] 2023-08-08 00:44
Hello, any update on this @exextoc , our customers are also impacted by this as they have deployed the addin from the Admin center. Hoping to get this fixed ASAP please

**Comment by exextoc** [comment] 2023-08-08 04:25
We understand your concern and we are actively working on the fix. We will update this thread once the fix is deployed.

**Comment by t-ariyoshi30907** [comment] 2023-08-08 08:46
@exextoc 
Thank you.
Additionally, could you please provide another piece of information?
Where might the underlying cause of this issue lie?
For instance, if it's related to a program update in Microsoft 365, kindly share the specifics of that update.
It's crucial that I can accurately explain to my clients why this issue is occurring.

**Comment by t-ariyoshi30907** [comment] 2023-08-09 00:33
@exextoc 
I apologize for the repeated inquiries.
Regarding the centralized deployed add-in, it seems that the issue no longer occurs at the moment.
Is it possible that the program's corrective work has been implemented?

**Comment by exextoc** [comment] 2023-08-09 03:27
This issue has been fixed and rolled out 100%.

**Comment by t-miyake** [comment] 2023-08-09 04:11
@exextoc Thanks!
I have confirmed that the issue has been fixed in all the tenants that I can directly access.
If we receive any reports of problems from our customers, I will notify you again here.

**Comment by avisheknand** [comment] 2023-08-09 04:21
Thank you @exextoc . I have confirmed it works now

**Closed as completed** 2023-08-09 05:19 UTC
Labels: Area: Outlook, Status: fixed
