### ISSUE TITLE
Forwarding / Cancelling event javascript callback

### ISSUE THREAD

**Issue by mkondadg** [OfficeDev/office-js#3588] opened 2023-08-15 23:33 UTC
We are trying to develop a outlook addin for new outlook and testing using Outlook 16.75.2 on Mac desktop app.

We have "OnMessageSend" / "OnAppointmentSend" working to get javascript callbacks when a mail is sent/replied/forwarded and appointment is created.

But when we forward the meeting invite or cancel the meeting, we dont have a Event type to receive javascript callback.
I tried all the event types listed here
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest

Sample events from manifest.xml

`<LaunchEvent Type="OnNewMessageCompose" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnNewAppointmentOrganizer" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnMessageAttachmentsChanged" FunctionName="handleAttachMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnAppointmentAttachmentsChanged" FunctionName="handleAttachMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnMessageRecipientsChanged" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnAppointmentAttendeesChanged" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnAppointmentTimeChanged" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnAppointmentRecurrenceChanged" FunctionName="handleSendMail"  SendMode="SoftBlock"/>

                <LaunchEvent Type="OnInfoBarDismissClicked" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnMessageSend" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnAppointmentSend" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnMessageCompose" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnAppointmentOrganizer" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnMessageFromChanged" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnAppointmentFromChanged" FunctionName="handleSendMail" SendMode="SoftBlock"/>

                <LaunchEvent Type="OnSensitivityLabelChanged" FunctionName="handleSendMail" SendMode="SoftBlock"/>`

Any help if I am missing something or the functionality is not supported at all ?

**Comment by exextoc** [comment] 2023-09-06 11:19
@mkondadg - Can you confirm if you are able to get the event in Outlook web or Outlook Desktop?

**Comment by mkondadg** [comment] 2023-09-07 02:58
Is the issue fixed recently or you wanted just to verify ?

**Comment by exextoc** [comment] 2023-09-07 03:45
@mkondadg Wanted to check if you are seeing this only in Outlook Mac, or is it something you are seeing in other platforms as well.

**Comment by mkondadg** [comment] 2023-09-07 16:22
This doesnt work on any platform.

Windows Outlook App / Windows browser
Mac Outlook App / Mac browser

**Comment by exextoc** [comment] 2023-09-18 09:30
@mkondadg - Currently there is no event for forwarding/cancelling. If you think this is useful, please submit your request in tech community page.

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by exextoc** [comment] 2023-09-18 09:30
Resolving as by design.

**Closed as completed by exextoc** 2023-09-18 09:30 UTC
Labels: Area: Outlook, Resolution: by design
