### ISSUE TITLE
The reply url specified in the request does not match the reply urls configured for the application

### ISSUE THREAD

**Issue by nyn3x** [OfficeDev/office-js#770] opened 2019-10-11 03:09 UTC
I just created a simple POC using Excel. I used side-loading to upload my addin to excel on the web.

However: when the `getAccessTokenAsync` is invoked I get an error like this:

> AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '57fb890c-0dab-4253-a5e0-7188c88b2bb4'.

I followed the steps at [Create a Node.js Office Add-in that uses single sign-on (preview)](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs#register-the-add-in-with-azure-ad-v20-endpoint) to actually registered my addin in AAD and to update the `manifest.xml`.

Looking at the give app-id `57fb890c-0dab-4253-a5e0-7188c88b2bb4`, this it the id for *Office on the web*. Also, the redirect-uri given at the authorization is: `https://[tenant]-my.sharepoint.com/_forms/singlesignon.aspx`. This seems obvious, that this URL is not within the configuration of the App `57fb890c-0dab-4253-a5e0-7188c88b2bb4`.

But how am I supposed to acquire an access-token?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins#feedback)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/sso-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment] 2019-10-11 04:03
The Redirect URI that you specify in the registration cannot be a sharepoint.com URI. You should specify the URI where you want Azure Active Directory (AAD) to send the access token. This would be a URI in your add-in's web app. When you are developing, this is a localhost:nnnn domain URI. If you have moved the add-in to staging or production, then the domain will be the domain where you are hosting the add-in. It must be a domain that is not recognized by AAD as being owned by someone else. sharepoint.com, of course, is owned by Microsoft, not you; so you can't use that as a place to host your add-in's web app. As for the error message, `57fb890c-0dab-4253-a5e0-7188c88b2bb4` is the GUID of both Office on the Web and SharePoint Online. So it is, in effect, a synonym for sharepoint.com.

**Comment by nyn3x** [comment] 2019-10-11 06:03
I think I didn't express this correct.

*I* did not specify sharepoint as being the redirect URI, instead I specified `https://localhost:3000` (which is the default from the yeoman generator).

I then added the `getAccessTokenAsync` to my code. When I call my addin I'm being redirected (by the `getAccessTokenAsync`). This redirect is not done by either me nor my application, but `57fb890c-0dab-4253-a5e0-7188c88b2bb4`.

When you look again at the error-message:

> AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '57fb890c-0dab-4253-a5e0-7188c88b2bb4'.

So it's not my-applications redirect uri being misconfigured, but the redirect that is send by `getAccessTokenAsync` is not recognized by the app `57fb890c-0dab-4253-a5e0-7188c88b2bb4`.

**Comment by Rick-Kirkham** [comment] 2019-10-11 17:49
In that case, I don't understand what you meant by "the redirect-uri given at the authorization is: https://[tenant]-my.sharepoint.com/_forms/singlesignon.aspx". Could you please explain?

Please open the add-in's registration page in the Azure portal. Open the **Authentication** blade and report to us what is the value of **REDIRECT URI**.

Also, could you share the entire call to `getAccessTokenAsync` from your code?

**Comment by nyn3x** [comment] 2019-10-11 19:11
This is my redirect configuration:
![image](https://user-images.githubusercontent.com/581049/66677155-58f9d500-ec69-11e9-8c50-d8cc4d9e880b.png)

and this is the code in my addin's `app.tsx`:

```typescript
Office.context.auth.getAccessTokenAsync(function(result) {
  debugger;
  if (result.status.toString() === "succeeded") {
    // Use this token to call Web API
    var ssoToken = result.value;
    console.log("token:" + ssoToken);
  } else {
    if (result.error.code === 13003) {
      // SSO is not supported for domain user accounts, only
      // work or school (Office 365) or Microsoft Account IDs.
    } else {
      // Handle error
      console.log("cannot get token:" + result.error.message);
    }
  }
});
```

and this is part of my `manifest.xml`:
```xml
<WebApplicationInfo>
  <Id>1447a5d7-bb7a-4b88-a226-e400342b2202</Id>
  <Resource>api://localhost:3000/1447a5d7-bb7a-4b88-a226-e400342b2202</Resource>
  <Scopes>
      <Scope>profile</Scope>
  </Scopes>
</WebApplicationInfo>
```
The resource of the `manifest.xml` is take from the "Expose an API" section from the azure portal.

When I execute my addin my browser redirects to the following url:

`https://login.microsoftonline.com/[aad-tenant-id]/oauth2/authorize?response_type=token&client_id=[client-id]&resource=api%3A%2F%2Flocalhost%3A3000%2F1447a5d7-bb7a-4b88-a226-e400342b2202&redirect_uri=https%3A%2F%2Fbusitec-my.sharepoint.com%2F_forms%2Fsinglesignon.aspx&state=8a1c79c5-3849-4157-941f-e12627720420%7Capi%3A%2F%2Flocalhost%3A3000%2F1447a5d7-bb7a-4b88-a226-e400342b2202&client-request-id=59ba0ace-774d-4c94-bb7a-2fd1a09e8437&x-client-SKU=Js&x-client-Ver=1.0.16&prompt=none&login_hint=eiben%40busitec.de&domain_hint=busitec.de&iframe-request-id=f185be5b-ef00-4e77-be67-781900603e00`

When you look at the url, you see the redirect-url passed to the is `https://busitec-my.sharepoint.com/_forms/singlesignon.aspx`. This must be passed by the SSO-login from my excel-file (which is stored in my personal onedrive in O365, that's probably why the redirect is pointing to `busitec-my.sharepoint.com`).

**Comment by Rick-Kirkham** [comment] 2019-10-11 20:31
Where are you seeing the call to login.microsoft.com? It doesn't show up in Fiddler on my computer?

**Comment by nyn3x** [comment] 2019-10-11 21:07
Interessting - my addin has a button, and in the click-event I actually call `Office.context.auth.getAccessTokenAsync`. As soon as this is called my browser is redirected to `login.microsoft.com`.

BTW: are you using Excel Desktop App or Excel Web App? I'm using the later one ...

**Comment by Rick-Kirkham** [comment] 2019-10-12 00:16
Are you saying that a dialog opens and redirects to login.microsoft.com or that  your task pane does?

**Comment by nyn3x** [comment] 2019-10-12 07:09
When I click the button on the task pane then I'm being redirected; correct. I would guess that I'm redirected because of the error and in case of success this would not happen and instead this would just take place in the background.

**Comment by nyn3x** [comment] 2019-10-12 08:15
Maybe this helps ...
![excel-addin](https://user-images.githubusercontent.com/581049/66697749-cabd3780-ecd8-11e9-9a8a-c6e38c05c6a5.gif)

As you can see, the file is in my one-drive and Excel recognizes me as being myself ... so I should be authenticated already 😊

**Comment by Rick-Kirkham** [comment] 2019-10-13 18:20
Something's wrong here. getAccessTokenAsync should not open a new browser window in any case. I'm reassigning this to the PM for the API.

**Comment by niteshgolchha85** [comment] 2019-10-17 05:09
Hi @nyn3x,

Have you consented to the add-in scopes before? If not, can you reproduce this issue after consenting to the add-in?

**Comment by nyn3x** [comment] 2019-10-17 09:02
Yes - I did. Actually a granted admin-consent (for ease of testing)

**Comment by niteshgolchha85** [comment] 2019-10-18 21:21
@nyn3x Can you try granting consent by following the steps on this link and let me know if you can repro the issue? 
https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment

**Comment by tiagordc** [comment] 2019-11-12 14:10
Tried using https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/tree/master/SSOAutoSetup, uploaded the manifest.xml to Excel Web and got the same issue

**Comment by TCourtneyOwen** [comment] 2019-11-21 00:29
@tiagordc https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/tree/master/SSOAutoSetup will not currently set the reply urls for your tenant.  To do so manually do the following:

- Open Powershell as as admin
- Run 'Install-Module MSOnline'
- Run 'Connect-MsolService' and enter your dev tenant account
- Run 'Remove-MsolServicePrincipal -ServicePrincipalName 57fb890c-0dab-4253-a5e0-7188c88b2bb4'
- Run 'New-MsolServicePrincipal -ServicePrincipalNames 57fb890c-0dab-4253-a5e0-7188c88b2bb4 -AppPrincipalId 57fb890c-0dab-4253-a5e0-7188c88b2bb4 -DisplayName "SharePoint Online Client" -AccountEnabled $true'
- Grab the **ObjectId** of the newly added service principal from the output
- Update the following command, replacing the <tenant_name> and <sp_objectid> with your tenant name and the sp object id you grabbed in the previous step:

az rest --method patch --uri https://graph.microsoft.com/beta/servicePrincipals/**<sp_objectid>** --headers "Content-Type=application/json" --body "{\"replyUrls\": [\"https:\/\/**<tenant_name**>-my.sharepoint.com\/_forms\/singlesignon.aspx\", \"https:\/\/**<tenant_name>**.sharepoint.com\/_forms\/singlesignon.aspx\"]}

- Open the command prompt and run 'az login --allow-no-subscriptions' and login through the browser with tenant.
- Return to the command prompt where you performed the az login and run the updated az rest command.

This is painful, yes, and I have just finished automating this today, but it's not yet checked into https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/tree/master/SSOAutoSetup 

Hope this helps.

Courtney

**Comment by Greg-Hitchon** [comment] 2020-01-17 21:45
Also getting this issue. Have not tried the @TCourtneyOwen  fix.

**Comment by tjcrowder** [comment] 2020-01-29 18:38
@TCourtneyOwen - My colleague and I are getting the same error, having followed the steps [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs) for the "Before" (or "Begin", it varies) project.

We tried to follow the instructions in [the comment above](https://github.com/OfficeDev/office-js/issues/770#issuecomment-556621990), but unfortunately when trying to do the `az rest` command, we got:

> error: unrecognized arguments: replyUrls:[https://ourtenantname-my.sharepoint.com/_forms/singlesignon.aspx,https://ourtenantname.sharepoint.com/_forms/singlesignon.aspx]}

What we sent:

```
az rest --method patch --uri https://graph.microsoft.com/beta/servicePrincipals/${our_object_id} --headers "{\"Content-Type\":\"application/json\"}" --body "{\"replyUrls\":[\"https://ourtenantname-my.sharepoint.com/_forms/singlesignon.aspx\",\"https://ourtenantname.sharepoint.com/_forms/singlesignon.aspx\"]}"
```

Also tried `--headers "Content-Type=application/json"`, same result (looks like the docs for `az rest` say either is fine).

(We removed the whitespace from the JSON because of [this](https://github.com/Azure/azure-cli/issues/10562).)

Or is there a way to do this through the UI?

TIA. :-)

**Comment by TCourtneyOwen** [comment] 2020-01-29 18:59
@tjcrowder are youseeing this on Mac or Windows?

**Comment by TCourtneyOwen** [comment] 2020-01-29 19:05
I see in the command you sent that you aren't escaping "/" characters.  Please replace this command with your relevant SP Object-ID and tenant names:

az rest --method patch --uri https://graph.microsoft.com/beta/servicePrincipals/<SP-OBJECTID> --headers "Content-Type=application/json" --body "{\"replyUrls\": [\"https:\/\/<TENANT-NAME>-my.sharepoint.com\/_forms\/singlesignon.aspx\", \"https:\/\/<TENANT-NAME>.sharepoint.com\/_forms\/singlesignon.aspx\"]}"

**Comment by tjcrowder** [comment] 2020-01-30 16:06
Thanks @TCourtneyOwen! While I was out of the office my colleague installed the Azure CLI for Windows (we had been trying to do the command in CloudShell) and put the JSON of the body in a separate file, which worked. We couldn't get the body JSON to work -- not by copying and pasting from the comment above, nor with escaping `"` with `\`, it just didn't like it. But putting the JSON in a file and using `@` worked.

For anyone else, here's what worked for us:

1. If you don't have [Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest) installed, install it
2. Open Powershell as Administrator
3. Run `Install-Module MSOnline`
4. Run `Connect-MsolService` and enter your dev tenant account
5. Run `Remove-MsolServicePrincipal -ServicePrincipalName 57fb890c-0dab-4253-a5e0-7188c88b2bb4` *(we got an error saying we didn't have permission to run this cmdlet, but trying a second time worked)*
6. Run `New-MsolServicePrincipal -ServicePrincipalNames 57fb890c-0dab-4253-a5e0-7188c88b2bb4 -AppPrincipalId 57fb890c-0dab-4253-a5e0-7188c88b2bb4 -DisplayName "SharePoint Online Client" -AccountEnabled $true`
7. Grab the ObjectId of the newly-added service principal from the output
8. Run `az login --allow-no-subscriptions` and login through the browser with tenant
9. Copy the following to a file (for instance, `body.json`), replacing `[tenant_name]` with your tenant name (without any `[]`):
`{"replyUrls": ["https://[tenant_name]-my.sharepoint.com/_forms/singlesignon.aspx", "https://[tenant_name].sharepoint.com/_forms/singlesignon.aspx"]}`
For example, if your tenant name were `example`, it would be:
`{"replyUrls": ["https://example-my.sharepoint.com/_forms/singlesignon.aspx", "https://example.sharepoint.com/_forms/singlesignon.aspx"]}`
10. Run the following command, replacing `[sp_objectid]` with the ObjectId of the newly-added service principal from earlier (without `[]`), and adjusting the filename if you didn't use `body.json` above: `az rest --method patch --uri https://graph.microsoft.com/beta/servicePrincipals/[sp_objectid] --headers "Content-Type=application/json" --body @body.json`

**Comment by TCourtneyOwen** [comment] 2020-01-30 17:48
@tjcrowder Yes, the steps you outline above match what I recommend for manually configuring the replyUrls. We actually do this automatically as part of of SSO configuration process now.  Have you tried using our SSO project template yet? If not, you can find instructions on how to use the SSO template at https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart

**Comment by tjcrowder** [comment] 2020-01-31 10:54
Thanks @TCourtneyOwen, I'll have to look into that! I'd assumed since the most recent commit to https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/tree/master/SSOAutoSetup was two days before [your comment above](https://github.com/OfficeDev/office-js/issues/770#issuecomment-556621990) that for some reason you'd been unable to add those changes...

**Closed as completed** 2020-06-22 22:42 UTC
Labels: Needs: attention :wave:, Area: authentication, Type: product question
