### ISSUE TITLE
In Office Online, `Office.onReady()` is resolving the promise even before the Office.Initialize event is triggered

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-js#200] opened 2018-07-23 23:15 UTC
Copying from https://github.com/OfficeDev/office-js/issues/5.

We need to repro this and see what's going on.

**Comment by JuaneloJuanelo** [comment] 2018-07-24 20:49
tracking internally with 2453651

**Comment by shreedhart** [comment] 2018-07-25 21:32
@raulgg, I am not able to reproduce the Office.OnReady() API issue in Excel online. Office.initialize is fired before Office.onReady. Office.context is initialized by the time the events fire.

Can you provide some more details about your add-in? Which office online app are you using? Which context API are you trying to access when Office.onReady fires?

**Comment by raulgg** [comment] 2018-07-28 00:28
@shreedhart I was trying to write an example in script-lab but seems that Office.initialize isn't triggering there. So I'll give you the details here and see if I can help.

The apps where I'm having this issue are Word Online and Powerpoint Online. In the entry point of the add-in one of the first things I'm doing is checking if the Office APIs I need in the add-in are supported, so I can show the right UI. 

```
# Render application after Office initializes
onReady = () => {
    if isOfficeAPISupported() {
        return render(App);
    }
    render(UnsupportedApp);
}
Office.initialize = onReady;
Office.onReady()
    .then(onReady)
    .catch(console.error);
```

My intention was to null Office.initialize, so it would work only with the onReady promise, but I cannot do this as in Office online the onReady promise resolves immediately after the add-in loads. 

In the '_isOfficeAPISupported_' function in my code I'm just using '_isSetSupported_' to check if _DialogApi_ and _ImageCoercion_ are supported by the host.

I hope this helps. If you need more details I'm happy to provide them.

**Comment by Zlatkovsky** [comment] 2018-07-28 00:48
@raulgg , several things that come to mind:

1. Re Script Lab:  yeah, with respect to initialization, you can't do Office.initialize there.  We do custom loading of the snippets so our usage of Office.js and esp the initialization pipeline is a bit different in Script Lab.

2. Re. "My intention was to null Office.initialize, so it would work only with the onReady promise":  this is very unclear to me.  Why do you want to null it out?  In general, the idea is that `Office.onReady` covers a superset of the Office.initialize scenarios, but there is no reason to null out one vs. the other.

It feels like you should be able to write something as simple as

```
Office.onReady(() => {
    if (isOfficeAPISupported()) {
        return render(App);
    }
    render(UnsupportedApp);
})

function isOfficeAPISupported() {
    return Office.context.requirements.isSetSupported('ImageCoercion') && 
        Office.context.requirements.isSetSupported('DialogApi');
````

Is there any issues you run into when writing this?

**Comment by raulgg** [comment] 2018-07-28 07:06
@Zlatkovsky you're right, what I said about nulling it out doesn't make sense. I meant that I was going to assign it to an empty function as in some hosts I noticed it's expecting a function there. Correct me if I'm wrong.

I just tried simplifying the code and running what you wrote there but I'm still having the same issue. The callback will run when the context API hasn't been loaded yet. If I log on each of them I see how the log from Office.onReady is showing before the log coming from Office.initialize. While in the other hosts is just the opposite.

**Comment by Zlatkovsky** [comment] 2018-07-30 05:09
@raulgg , what is the minimal repro for this?  Is there a single simple HTML page with an inlined script tag (nothing fancy) that you could show that repros the issue?

I just tried it myself, both with Excel desktop and Online, and it's working correctly for me.  Here is my file:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
        <script src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js" type="text/javascript"></script>
        <script type="text/javascript">
            Office.onReady(function() {
                var text;
                try {
                    text = Office.context.requirements.isSetSupported("ExcelApi")
                        ? "ExcelApi is supported"
                        : "ExcelApi NOT supported";
                } catch (e) {
                    text = "Error: " + e;
                }
                
                document.getElementById("status").innerHTML = text;
            });
        </script>
    </head>
    <body>
        <div id="status">
            ... Not yet ready ...
        </div>
    </body>
</html>
```

A corresponding manifest (when this file is called "text.html" and is running on "https://localhost:3000" is also attached)

[test-manifest.txt](https://github.com/OfficeDev/office-js/files/2239738/test-manifest.txt)

Could you please try this, and let me know if our two experiences diverge?

Thanks!
~ Michael

**Comment by raulgg** [comment] 2018-08-05 02:59
Sorry for the delay @Zlatkovsky, I just tried creating a basic example like yours and it works as properly. I will try a few things in my add-in within the next week and I'll post here whatever I find. Could it be caused by one of the polyfills I'm using? I just find it strange that it works in every other host.

**Comment by Zlatkovsky** [comment] 2018-08-05 06:51
I can't think of why polyfills would be causing it.  But if you can narrow down a repro, I'm happy to take a look.

**Comment by JuaneloJuanelo** [comment] 2019-02-15 22:18
@raulgg  since August we dont hear back. will close the issue, if it persists please create a new and link to this issue. thanks!

**Closed as completed by JuaneloJuanelo** 2019-02-15 22:18 UTC
Labels: Needs: author feedback
