### ISSUE TITLE
Office.context.mailbox.item.getItemIdAsync has error with not saved appointment compose

### ISSUE THREAD

**Issue by keizo-furukawa** [OfficeDev/office-js#1310] opened 2020-08-04 14:18 UTC
I'm developing outlook addin and using item id of appointment by getting with following api.
`Office.context.mailbox.item.getItemIdAsync`
I'm using this api from January 2020 and have no problem until last week.
However now I have error when I call this api with not saved appointment compose screen on web browser(Google chrome).

## Expected Behavior

As far as following this document, we should have this result
`Until the item is synced, the itemId is not recognized and using it returns an error.`
https://docs.microsoft.com/ja-jp/javascript/api/outlook/office.appointmentcompose?view=outlook-js-1.8#getitemidasync-callback-

## Current Behavior

When I try to run `Office.context.mailbox.item.getItemIdAsync` on web browser(google chrome), having following error on developer console.
```
outlook-web-16.01.js:19 Uncaught TypeError: Cannot read property 'replace' of undefined
    at T (outlook-web-16.01.js:19)
    at R (outlook-web-16.01.js:19)
    at outlook-web-16.01.js:19
    at Object.a [as callback] (outlook-web-16.01.js:19)
    at L (outlook-web-16.01.js:19)
```

## Steps to Reproduce, or Live Example

1. On google chrome, access outlook web browser version
2. Move to calendar view and open new appointment
3. Open addin view and call `Office.context.mailbox.item.getItemIdAsync`

## Context

I need to get item id for registered item, so need to call this api.
However we have no way to know if it is saved appointment or not from addin side, so always calling `Office.context.mailbox.item.getItemIdAsync` and not possible to avoid this error

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: latest of office on the web on August 4th 2020
* Operating System: MacOS
* Browser (if using Office on the web): Google chrome

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)
![image](https://user-images.githubusercontent.com/63782142/89304647-a3d95300-d6a8-11ea-8207-798bc50f0850.png)

**Comment by exextoc** [comment] 2020-08-04 16:09
We are able to reproduce this issue on our side. Thanks for reporting this issue regarding getItemIdAsync API.
We are actively working on this issue as it is high priority. We unfortunately have no timelines to share at this point

**Comment by agelenava** [comment] 2020-08-04 19:11
we just faced the same issue

**Comment by onestep** [comment] 2020-08-04 19:11
We have the same error in compose mode for email as well.

**Comment by abdulkareemnalband** [comment] 2020-08-06 12:02
looks like duplicate of #1309

**Comment by exextoc** [comment] 2020-08-07 10:58
We have pushed the fix to production.
It may take at max 24 hours for the changes to get reflected (cache may have older copies) .

**Comment by ElizabethSamuel-MSFT** [comment] 2020-10-02 17:26
@keizo-furukawa Looks like this issue has been fixed so I'll close it now. If that's not the case, let us know by creating a new issue.

Thanks.

**Closed as completed by ElizabethSamuel-MSFT** 2020-10-02 17:26 UTC
Labels: Status: fixed
