### ISSUE TITLE
Streaming functions in Excel desktop(Windows10/Mac) won't recalculate after execute `range.calculate()`

### ISSUE THREAD

**Issue by thanakrid-kunghair-rft** [OfficeDev/office-js#1734] opened 2021-03-19 09:26 UTC
Hi!
Currently, I'm working on changing my project's custom functions in to streaming, but I found that when I use a refresh button, which my team implement with `range.calculate()`, the streaming function at the giving range won't show #BUSY. However, I tried using `range.calculate()` against a normal custom function, and it recalculated.
Another thing is I can use `range.calculate()` to recalculate streaming functions in Chrome.
## Expected Behavior

Streaming functions recalculate when using `range.calculate()` in Excel desktop(Windows10/Mac).

## Current Behavior
Streaming functions will not recalculate when using `range.calculate()` in Excel desktop(Windows10/Mac).

## Steps to Reproduce, or Live Example

You can clone from this repo https://github.com/thanakrid-kunghair-rft/test-add-in. It's a simple test add-in project that I create from this tutorial. 
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows
There will be a refresh button in the taskpane that you can use it to run `range.calculate()`.
You can use `=CONTOSO.STREAMING` and `=CONTOSO.LOG` to see the differences.
1. After you run the add-in, open the taskpane.
2. set `=CONTOSO.STREAMING` and `=CONTOSO.LOG` to different cells
3. click at the first function's cell then click at refresh button in the taskpane.
4. click at another function's cell then click at refresh button in the taskpane.

## Context
Currently, I have a refresh button feature that use range.calculate() to refresh formulas, and it was working fine until I changed custom functions to Streaming.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Win10
![image](https://user-images.githubusercontent.com/73512008/111758859-8cfe0e80-88cf-11eb-8ff4-a6a51c352b67.png)
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Mac
![image](https://user-images.githubusercontent.com/73512008/111759015-bae35300-88cf-11eb-9781-1984d0bd1d4f.png)

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by ElizabethSamuel-MSFT** [comment] 2021-03-22 23:08
@thanakrid-kunghair-rft Thanks for raising this issue.

@grangeryy Can you take a look or assign to an appropriate person to investigate?

Thanks.

**Comment by grangeryy** [comment] 2021-03-23 02:11
@thanakrid-kunghair-rft Thanks for reporting this. We'll investigate and update the status later. Thx!

**Comment by grangeryy** [comment] 2021-03-23 02:29
Bug 4975234 is created to track this.

**Comment by thanakrid-kunghair-rft** [comment] 2021-03-23 08:29
Hi!
I would like to add that this issue also happen on Safari as well.
Thanks.

**Comment by grangeryy** [comment] 2021-04-07 06:20
The bug is currently fix. Pls check if the issue is gone:)

**Closed as completed by grangeryy** 2021-04-07 06:20 UTC
Labels: Needs: attention :wave:, Area: Excel, Type: product bug, Status: fixed, Area: custom functions

**Comment by thanakrid-kunghair-rft** [comment] 2021-04-09 04:54
Hi @grangeryy

Streaming functions are still not recalculated on both Excel Win10 and Excel Mac.

**Comment by thanakrid-kunghair-rft** [comment] 2021-04-09 05:14
Do I need to update anything?
I've tried both https://appsforoffice.microsoft.com/lib/1/hosted/office.js and https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js, and it's still not working.

**Comment by grangeryy** [comment] 2021-04-12 02:31
You don't need to update anything and the fix will work automatically. I notice you're using Mac, and it may take a while for the fix to deploy in Mac.

**Comment by thanakrid-kunghair-rft** [comment] 2021-04-12 05:09
I've tested in Windows 10 as well, and it's still not working.
Is Windows 10's fix deployed yet? Or it will be deployed at the same time as Mac?

**Comment by grangeryy** [comment] 2021-04-12 05:25
Just checked and the fix is already reached in 16.0.14002.20000 for Windows. It mat also take some time for Windows to have the fix in place.

**Comment by thanakrid-kunghair-rft** [comment] 2021-04-12 06:03
Thank you.
![image](https://user-images.githubusercontent.com/73512008/114347552-4ed2d280-9b8f-11eb-8764-268406abe7a0.png)
Here's my Excel version. I will check the fix again on Friday.

**Comment by thanakrid-kunghair-rft** [comment] 2021-04-16 03:59
Hi @grangeryy ,
I still can't recalculate streaming function with `range.calculate` in Excel Windows 10. Has the fix reached my version yet?

**Comment by thanakrid-kunghair-rft** [comment] 2021-06-16 08:35
Hi @grangeryy @ElizabethSamuel-MSFT  
I've still got this issue in Excel on Windows 10.
Here's my Excel's version.
![image](https://user-images.githubusercontent.com/73512008/122186685-7a887680-ceb8-11eb-9171-64d0bd4f509e.png)
![image](https://user-images.githubusercontent.com/73512008/122189445-2206a880-cebb-11eb-8db4-7d4e3a8a3d72.png)

For Mac version, it's working fine; streaming functions will recalculate after I use range.calculate().

**Comment by grangeryy** [comment] 2021-06-16 08:49
Are you using O365 subscription? Notice the version of your Excel is Version 2008 (Build 13127.21668 Click-to-Run), is it one-time purchase version?

**Comment by thanakrid-kunghair-rft** [comment] 2021-06-16 08:57
Yes, I'm using O365 subscription.

**Comment by grangeryy** [comment] 2021-06-16 09:03
Could you check by clicking into the "About Excel" to see what the detailed version, starting with 16.XXX?
![image](https://user-images.githubusercontent.com/50093161/122190676-9e51b980-cec4-11eb-8966-e0adf59c90e7.png)

**Comment by thanakrid-kunghair-rft** [comment] 2021-06-16 09:04
![image](https://user-images.githubusercontent.com/73512008/122190947-7d856600-cebc-11eb-976d-770acd3adc84.png)

**Comment by thanakrid-kunghair-rft** [comment] 2021-06-16 09:05
![image](https://user-images.githubusercontent.com/73512008/122191083-9c83f800-cebc-11eb-8e55-d8be52f09701.png)

**Comment by grangeryy** [comment] 2021-06-16 09:35
Seems the version hasn't been updated in your case. Maybe you can try update the version using (usually monthly/beta/dogfood version update is faster):
![image](https://user-images.githubusercontent.com/50093161/122195528-073b3080-cec9-11eb-8388-a7ea43e8b114.png)

**Comment by thanakrid-kunghair-rft** [comment] 2021-06-16 09:51
I can't change my update channel because it's managed by admins. I think my update channel is semi-annual enterprise.

**Comment by thanakrid-kunghair-rft** [comment] 2021-06-16 09:57
So, the function should work when updates are applied, right? Could you specify on which version that this will work? Maybe I can check with my colleagues' Excel.

**Comment by grangeryy** [comment] 2021-06-16 10:29
You're right:) it should be available starting from 16.0.14002.20000 for Windows

**Comment by grangeryy** [comment] 2021-06-16 10:30
Semi-annual usually takes several months to be updated to the latest version :( 
Guess that's why you don't see the change in recent two months.

**Comment by thanakrid-kunghair-rft** [comment] 2021-06-16 11:43
Thank you @grangeryy . I will check with my colleagues, if they have updated version.
