### ISSUE TITLE
Office.context.mailbox.item.itemId returns empty string (Outlook for Mac - New UI)

### ISSUE THREAD

**Issue by GrumpyAL** [OfficeDev/office-js#2381] opened 2022-01-21 20:25 UTC
There may be an environmental cause to this, but so far we have been unable to find it. We have an Outlook add-in that our customers use.  Part of it's process is to pull the itemID for the email it was invoked on.  One of our customers is seeing that this is coming back as an empty string, only when using the new UI.  We tried the following:

Things that don't work:
-  a new profile
- deleting the Outlook cache (https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-mac)
- clearing parts of the Outlook folder in the containers directory, including the plist file.

Things that work:
- Outlook on the Web via Safari (this works fine)
- The old Outlook for Mac UI (this works fine
- Remove the app and reinstalling.  (This worked, because it lowered the version to 16.50 but once we updated to 16.57 it no longer worked).

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.54 and 16.57
* Operating System: macOS Monterey 12.1 (so far)
* Browser (if using Office on the web): n/a

Note: We are attempting to gather more Office and macOS version numbers from impacted users at this time.  It is currently believed to impact more than just macOS Monterey.
 
## Expected behavior
Office.context.mailbox.item.itemId is not null/empty when using the new UI.

## Current behavior
Office.context.mailbox.item.itemId is empty when using the new UI

## Steps to reproduce
Unfortunately, we have been unable to reproduce on our Macs.  We suspect there's a root cause (setting, cache, etc). That we are missing.  However, the customer can reproduce by:

1. Load Outlook for Mac in the new UI
2. Load the add-in on a message (read mode).
3. Observe the error.
4. Open the dev tools and in the console try: Office.context.mailbox.item.itemId
5. The return value is ""
6. Note: the value for Office.context.mailbox.restUrl returns as expected and we are still able to get a REST callback token.

If you switch back to the old UI or remove and downgrade to 16.50, it works as expected.

It is also observed that trying to get an EWS callback token fails, but this also works on the old UI.

## Link to live example(s)
None available.

# Provide additional details

## Context

Without the itemID we cannot get the message on our backend.

## Useful logs

None available

**Comment by GrumpyAL** [comment] 2022-01-21 20:36
Additionally, please let me know if there any additional steps I can take on the client to try to determine if this is an Outlook or add-ins bug or if this is a configuration or client issue.  Thanks!

**Comment by exextoc** [comment] 2022-01-22 04:26
@GrumpyAL Unfortunately we are not able to reproduce this issue. Can you please share your hosted manifest so that we can repro it and debug better? If you don't feel free to share it in public, please send it to 
OutlookAddins@M365x693897.onmicrosoft.com

**Comment by GrumpyAL** [comment] 2022-01-24 14:18
Hi, @exextoc

Thanks for the fast response.  Unfortunately, we can't reproduce it in our environment either.  So we believe it's some kind of compound issue and there's a factor we're missing.  Is there anything more we can do to try to figure out why the Outlook for Mac client would not return an item ID?

When we had reverted to 16.50 we checked the OAI JavaScript that was loading and it was the same script that loaded for 16.57. (outlook-mac-16.00.js) which appears to be the only version available anyway, so no surprise there.  Just not sure why 16.50 would work and not 16.57 without there being some kind of compound issue.

**Comment by exextoc** [comment] 2022-01-27 14:06
@GrumpyAL Thanks for the update. Would it be possible for you to share manifest with us which may help us in the repro?

**Comment by GrumpyAL** [comment] 2022-01-27 14:11
Our add-in is actually self-hosted so I don't have a manifest I can send you for that.  I'll see if I can get the customer to load a test add-in I have (a modified version of the token-viewer demo) and if it will reproduce there.  Then I can provide a copy of a manifest for that.

Also, small update here: We have seen this for a 2nd customer now but we still don't have a root cause.  Still working to collect more data.  It appears that MacOS version does not have impact.  It seems to require 1) the New UI and 2) ~16.54 and above and 3) Some unknown factor that may be environmental.

**Comment by exextoc** [comment] 2022-01-31 15:13
We are not able to repro the issue at our end with the configuration mentioned by you. It will be good if you can share the manifest or the test account with us where the issue is reproable. Also you can share the Diagnostics ID with us to look at the logs.
How to get Diagnostic ID:
Repro the issue, then click on help->Collect Diagnostics . You will see a popout with Incident ID
![6aa172df-7e4d-41bf-99f7-240f5d08e84d](https://user-images.githubusercontent.com/28549921/151818891-c67c5f96-40ed-4ae8-b8ef-22823a19b663.jpg)

**Comment by GrumpyAL** [comment] 2022-02-02 21:15
Hello,

We now have 3 customers reporting this issue (I still haven't been able to reproduce myself).  I have sent some details to the address provided above regarding a repro one of the customers did.  

Something else of note in this, when we see this issue (Where ItemID is empty) we also are unable to get an EWS token.  That is visible in the test results as well.  For visibility's sake I'll post that result here as well:

EWS Callback Token

{
  "name": "AccessRestricted",
  "message": "Internal protocol error: '-2147467259'.",
  "code": 9017
}

The "AccessRestricted" would make me think it's a mailbox setting except that it works ok in OWA and with new UI off.  I'm also not sure if this is related to the itemId being blank or just a coincidence but so far we've seen these two things happening together.

I provided a link to the manifest we are using to test with.  It's a modified tokenviewer app that logs some additional information into the frame.

The Diagnostic ID for this is also included.

**Comment by exextoc** [comment] 2022-02-03 05:55
Have you sent a mail on OutlookAddins@M365x693897.onmicrosoft.com, we have not received any details.

**Comment by GrumpyAL** [comment] 2022-02-03 13:09
Yes, I sent it from a dev account (so another onmicrosoft.com domain).

![image](https://user-images.githubusercontent.com/28786762/152348847-31558532-8032-4187-90f8-595d821739c1.png)

**Comment by GrumpyAL** [comment] 2022-02-08 15:31
Hello,

Just following up on this.  Did that message come through? Do I need to resend?  I have a 2nd diagnostic ID to share but wanted to confirm receipt of the above first.  Thanks.

**Comment by exextoc** [comment] 2022-02-09 07:22
We could confirm with the logs that the item id is empty. However, we are unable to repro this in our environment with version 16.57. Could you please share a test account with us on the admin@a830edad9050849405e20081103.onmicrosoft.com if it is a consistent repro for you?

**Comment by GrumpyAL** [comment] 2022-02-09 16:50
Thank you.  We ourselves are unable to reproduce the issue as well. But we are seeing it happen to 3 different customers on their Macs.  It is a consistently reproduceable issue for them.  We will inquire about the possibility of a test account and if anyone is able have it sent to the above.

In the meantime, is there any other data gathering we can assist with?  We understand it's very difficult to fix or triage an issue that you can't reproduce for yourself.  So we are trying whatever we can to find the common thread here.

Thanks!

**Comment by exextoc** [comment] 2022-02-17 07:28
@GrumpyAL, there is no repro for us. In the logs we could see that the item-Id is empty but there is not sufficient information to proceed further. We will wait for test account or repro steps.

**Comment by GrumpyAL** [comment] 2022-02-22 14:25
Hello,

We are still trying to gather more information or find someone who is able to share a test account.  I have had reports of this from ~3-4 different organizations at this point but we're still looking for the missing repro step.

**Comment by m-pd** [comment] 2022-03-02 10:05
Hi. This issue was reported in another issue and I have supplied new diagnostics - https://github.com/OfficeDev/office-js/issues/1400

**Comment by m-pd** [comment] 2022-03-03 09:27
Hi @exextoc This has become a huge problem for us since New Outlook was released recently. Could you please fix it?

**Comment by exextoc** [comment] 2022-03-12 16:18
Hey @m-pd , 

I am closing this thread and we can follow up on #1400

**Closed as completed** 2022-03-12 16:19 UTC
Labels: Needs: attention :wave:, Area: Outlook, Type: product bug
