### ISSUE TITLE
getSelection doesnt work correct on comment replies

### ISSUE THREAD

**Issue by mstransky** [OfficeDev/office-js#2563] opened 2022-05-04 05:09 UTC
When use ``context.document.getSelection().paragraphs`` on comments, it return paragraph of main comments, but on reply it return again main comment.

Environment
PC desktop, Windows 11, Office 365, Word version 2204 build 15128.20178
Office-js-preview, used on React (but tested also with )
 
## Expected behavior
When selecting some words in the comment reply, and use ``context.document.getSelection().paragraphs`` it should return selected paragraph, as it works several weeks (o months) ago.

## Current behavior
When selecting some words in the comment reply, and use ``context.document.getSelection().paragraphs`` - it return not selected paragraph, but main comment paragraph.

## Steps to reproduce
1. prepare a document where is enough one paragraph("PARAGRAPH"), one comment("MAIN COMMENT") on paragraph, and one reply ("THE REPLY") on MAIN COMMENT.
2. select PARAGRAPH in Word and use ``context.document.getSelection().paragraphs`` -> it return correct paragraph object
3. select MAIN COMMENT in Word and use ``context.document.getSelection().paragraphs`` -> it return correct paragraph object
4. select THE REPLY in Word and use ``context.document.getSelection().paragraphs`` -> it return incorrect paragraph object -> the MAIN COMMENT paragraph

## Link to live example(s)
here is Scriptalb code to reproduce issue:
```
$("#run").click(() => tryCatch(run));

async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;

    const paragraphs = context.document.getSelection().paragraphs;
    paragraphs.load();
    await context.sync();
    console.log("Paragraph ->>>", paragraphs);

  });
}

async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    console.error(error);
  }
}
```
scriptlab libraries tested
``https://appsforoffice.microsoft.com/lib/1/hosted/office.js``, ``https://appsforoffice.microsoft.com/lib/beta/hosted/office.js``,
``https://unpkg.com/@microsoft/office-js@1.1.74-custom.26/dist/office.js``, ``https://unpkg.com/@microsoft/office-js@1.1.74-custom.0/dist/office.js``

## Context
I am trying to interact with paragraph using taskpane

**Comment by AlexJerabek** [comment] 2022-05-05 16:54
Thank you for reporting this issue @mstransky.

@grangeryy, could you please investigate?

**Comment by GavinGu07** [comment] 2022-05-06 05:03
Thanks for reporting @mstransky. We have reproduced your issue and created a work item on it. We will keep track on this issue and let you know if there are any updates.

**Comment by jipyua** [comment] 2023-02-09 05:16
@mstransky before this bug is fixed, if you are trying to get the content of a comment or its reply, you can try to leverage the comment related apis to do this, for more information, please see here: https://learn.microsoft.com/en-us/javascript/api/word/word.comment?view=word-js-preview

**Comment by mstransky** [comment] 2023-11-28 06:04
Hello, any progress on this issue?

**Comment by mstransky** [comment] 2023-11-28 06:11
> @mstransky before this bug is fixed, if you are trying to get the content of a comment or its reply, you can try to leverage the comment related apis to do this, for more information, please see here: https://learn.microsoft.com/en-us/javascript/api/word/word.comment?view=word-js-preview

Hi, thanks, I have no issue reading the comment object and replies, based on getSelection(), but I need to identify what comment or reply was selected. But now I can only identify parent comments, no longer able to get a selection of replies even if I put bookmarks around each comment and each reply.

**Comment by wangyun-microsoft** [comment] 2024-05-24 09:15
@mstransky We currently don't have plan to fix this issue due to priority. We will close this issue. Please open a new issue if you think this is highly impacting your business. 

Thanks.

**Closed as not planned** 2024-05-24 09:16 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: Word
