### ISSUE TITLE
[Excel for Mac] Excel crashes when `context.workbook.close(Excel.CloseBehavior.skipSave)` gets called

### ISSUE THREAD

**Issue by leticiabecker** [OfficeDev/office-js#1833] opened 2021-04-29 17:24 UTC
In our add-in, we want to allow the user to close the current workbook by calling `context.workbook.close(Excel.CloseBehavior.skipSave)` on a button click. It works fine on Windows, but it crashes Excel when it's called from Excel for Mac.

## Expected Behavior
`context.workbook.close(Excel.CloseBehavior.skipSave)` should close the Excel file without crashing Excel.

## Current Behavior
`context.workbook.close(Excel.CloseBehavior.skipSave)` crashes Excel when it gets called from the add-in on a Mac (Excel for Mac).
It works fine on Windows.

## Steps to Reproduce, or Live Example
- Link to Script Lab Gist: https://gist.github.com/leticiabecker/9e841b341abebb06bebb209dbd945129

## Context
We want to allow our users to close the Excel file they are currently working on when they are done by clicking on a button in the add-in.

## Your Environment
* Platform: Mac desktop
* Host: Excel
* Office version number: 16.48
* Operating System:  Mac
* Browser (if using Office on the web): N/A

## Useful logs
![image](https://user-images.githubusercontent.com/23156388/116592408-f79e6300-a8ed-11eb-8c54-dd605540a6ab.png)

```
Microsoft Error Reporting log version: 2.0

Error Signature:
Exception: EXC_BAD_ACCESS
ExceptionEnumString: 1
Exception Code: KERN_NAME_EXISTS (0x000000010edd026a)
Date/Time: 2021-04-29 17:22:21 +0000
Application Name: Microsoft Excel
Application Bundle ID: com.microsoft.Excel
Application Signature: XCEL
Application Bitness: x64
Application Version: 16.48.0.21041102
Crashed Module Name: Microsoft Excel
Crashed Module Version: 16.48.21041102
Crashed Module Offset: 0x0000000000d9244c
Blame Module Name: Microsoft Excel
Blame Module Version: 16.48.21041102
UnsymbolicatedChecksum: 88CA6C308474BB2F948CF0B1CBE867AE
Blame Module Offset: 0x0000000000d9244c
StackHash: da277aab0cb2cc75-dm_1_main
Application LCID: 1033
Extra app info: Reg=en Loc=0x0409
Build Type: Release
Crashed thread Stack Pointer: 0x_00007ffee3c027e0
Crashed thread: 0


Thread 0 crashed (0xabdc38):

#  1  0x000000010cd8b44c in  (Microsoft Excel + 0x0000000000d9244c) 0x0000000000000000
#  2  0x000000010dca6fab in  (Microsoft Excel + 0x0000000001cadfab) 0x0000000000000000
#  3  0x000000010dca4400 in  (Microsoft Excel + 0x0000000001cab400) 0x00007ffee3c03540
#  4  0x000000010dc9ffac in  (Microsoft Excel + 0x0000000001ca6fac) 0x00007ffee3c04230
#  5  0x000000010c241a1d in  (Microsoft Excel + 0x0000000000248a1d) 0x00007ffee3c04270
#  6  0x000000010c2418b4 in  (Microsoft Excel + 0x00000000002488b4) 0x00007ffee3c04340
#  7  0x000000010c2417f4 in  (Microsoft Excel + 0x00000000002487f4) 0x00007ffee3c04370
#  8  0x00007fff213adadb in ___NSFireDelayedPerform + 0x0000019F (Foundation + 0x0000000000080adb) 0x00007ffee3c04390
#  9  0x00007fff2061a90d in ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 0x00000014 (CoreFoundation + 0x000000000009a90d) 0x00007ffee3c04420
# 10  0x00007fff2061a3e8 in ___CFRunLoopDoTimer + 0x0000039A (CoreFoundation + 0x000000000009a3e8) 0x00007ffee3c04430
# 11  0x00007fff20619f42 in ___CFRunLoopDoTimers + 0x00000133 (CoreFoundation + 0x0000000000099f42) 0x00007ffee3c054e0
# 12  0x00007fff2060057f in ___CFRunLoopRun + 0x000007D8 (CoreFoundation + 0x000000000008057f) 0x00007ffee3c05530
# 13  0x00007fff205ff6ce in _CFRunLoopRunSpecific + 0x00000233 (CoreFoundation + 0x000000000007f6ce) 0x00007ffee3c06270
# 14  0x00007fff28887630 in _RunCurrentEventLoopInMode + 0x00000124 (HIToolbox + 0x0000000000031630) 0x00007ffee3c06310
# 15  0x00007fff2888742c in _ReceiveNextEventCommon + 0x000002C5 (HIToolbox + 0x000000000003142c) 0x00007ffee3c06360
# 16  0x00007fff2888714f in __BlockUntilNextEventMatchingListInModeWithFilter + 0x00000040 (HIToolbox + 0x000000000003114f) 0x00007ffee3c063e0
# 17  0x00007fff22e1f9b1 in __DPSNextEvent + 0x00000373 (AppKit + 0x000000000003e9b1) 0x00007ffee3c06400
# 18  0x00007fff22e1e177 in -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 0x00000556 (AppKit + 0x000000000003d177) 0x00007ffee3c067f0
# 19  0x00007fff22e1068a in -[NSApplication run] + 0x0000024A (AppKit + 0x000000000002f68a) 0x00007ffee3c06a60
# 20  0x00007fff22de496f in _NSApplicationMain + 0x00000330 (AppKit + 0x000000000000396f) 0x00007ffee3c06af0
# 21  0x00007fff20524621 in _start + 0x00000001 (libdyld.dylib + 0x0000000000015621) 0x00007ffee3c06b40
```

**Comment by mscharlock** [comment] 2021-04-29 22:21
Hi @lumine2008 - Can you have a look at this issue? Thank you!

**Comment by lumine2008** [comment] 2021-04-30 08:17
Thanks, we can repro this issue, a bug(5074894) is created to track this issue.

**Comment by jipinshi** [comment] 2021-05-10 01:38
@mscharlock , can you have a try whether the issue still repro, suppose it cannot repro now.

**Comment by lumine2008** [comment] 2021-06-01 01:05
@mscharlock, the issue is fixed, so I am closing this issue now, please reactive if you still observe the issue

**Closed as completed by lumine2008** 2021-06-01 01:05 UTC
Labels: Area: Excel, Type: product bug, Status: fixed
