### ISSUE TITLE
Add-In cannot communicate to local hosted windows service with Word version of 1301.XXX..

### ISSUE THREAD

**Issue by syun-dymo** [OfficeDev/office-js#660] opened 2019-08-08 16:55 UTC
I have a sample word Add-In that send message to local windows service which is Self Hosted Web API. The communication was working until test with version of Word  1301.XXX.
While I am debugging the API,  API did not receive any requests.

Is there anyone have any solution for this issue?

**Comment by weshi** [comment] 2019-08-12 02:20
To help us understand the exact root cause of this issue, could you please provide us with below information:
1) Platform information: are you using Office on the web, or Office on Windows? (From the description above, it seems that you are using Office on Windows. This is to double confirm).
2) Office Build information (you can find this from File->Account->About Word, there is a Version information there, such as Version 1907 (Build 11901.20176 Click-to-Run) in my case.
3) Windows Build (if you are using Windows 10, you can find this by searching System Information of the Windows search), something like Microsoft Windows 10 Enterprise, Version 10.0.xxxxx Build xxxxx.

**Comment by smaremanda** [comment] 2019-08-13 22:55
hi there - I am guessing this is on Windows 10? If yes, we started using the Edge Webview control to host the add-in in newer versions of Office. Please see this blogpost here: https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins/
Can you try the localhost loopback exemption mentioned in the blogpost and let us know if that fixes the issue?

**Comment by syun-dymo** [comment] 2019-08-16 12:25
That solved issue, Thank you.
________________________________

**Comment by kbrandl** [comment] 2019-08-26 22:19
Closing this issue, per @syun-dymo's most recent comment.

**Closed as completed by kbrandl** 2019-08-26 22:19 UTC
Labels: Type: product bug, Area: Word, Area: add-ins platform
