### ISSUE TITLE
Cannot insert a content control

### ISSUE THREAD

**Issue by yingyingchoi** [OfficeDev/office-js#4344] opened 2024-04-09 00:24 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform: Office on the web
* Host: Word
* Office version number: 20240404.2 (build number)
* Operating System: Mac
* Browser (if using Office on the web): Chrome
 
## Expected behavior
I am able to insert content control.

## Current behavior
I am not able to insert a content control programatically using the Word API.

## Steps to reproduce
1. Go to the Script Lab add-in, and try the "on adding content controls demo"
2. I simplified the logic to add a content control: `context.document.getSelection().insertContentControl();`

```
[ERROR]: Error:
{
    "stack": "RichApi.Error: Cannot read properties of null (reading 'length')\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:336110)\n    at o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:400557)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:398620",
    "message": "Cannot read properties of null (reading 'length')",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "Cannot read properties of null (reading 'length')",
        "errorLocation": "Range.insertContentControl",
        "statement": "var insertContentControl = selection.insertContentControl();",
        "surroundingStatements": [
            "var root = context.root;",
            "var selection = root.getSelection();",
            "// Instantiate {selection}",
            "// >>>>>",
            "var insertContentControl = selection.insertContentControl();",
            "// <<<<<",
            "// Instantiate {insertContentControl}"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}
```

## Context
It's breaking our word add-in 

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by zhenhuangMSFT** [comment] 2024-04-09 03:00
Hi @yingyingchoi, thanks for reporting the issue! May I ask if this is a recent regression?

**Comment by docu-bill** [comment] 2024-04-09 04:31
I am having this problem too. We deployed our app in February and it has run without problems until today. Can you please prioritize this. @zhenhuangMSFT

**Comment by vincentgggg12** [comment] 2024-04-09 06:50
Dear @YijunMS and @zhenhuangMSFT ,

We are having the same issue. Our customers rely on the add-in that we have built and published in the appsource marketplace. We have not changed anything and yesterday everything worked fine, but today we get the same error as reported by @yingyingchoi .

Please action this ASAP, our business depends on you.

Regards
V

**Comment by docu-bill** [comment] 2024-04-09 07:27
@zhenhuangMSFT @YijunMS , one thing that may help is that the problem is document dependent. We have one or two documents that do NOT trigger the problem. In our app we insertContentControls at several places.  If I create a new document, with text content and insert a content control we get this error.  However, we do have a more complicated document that has other more advance features (although only word online features) that we are able to insert the ContentControl into.  
I thought this might help as it is normally the other way around.

**Comment by richardfeynman1** [comment] 2024-04-09 08:04
Facing the same issue.
We face this issue periodically every couple of weeks and it resolves on its own after some time.

If a document has at least one content control present, we can add more content controls programmatically.

But if a document doesn't have any content control, we  are not able to add any content control.

The below error is visible in the browser console:

**RichApi.Error: Cannot read properties of null (reading 'length')
    at new n (word-web-16.00.js:25:336110)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:400557)
    at word-web-16.00.js:25:398620 'error occured'**

**Comment by YijunMS** [comment] 2024-04-09 09:04
@yingyingchoi @docu-bill @richardfeynman1 @vincentgggg12  Thanks for reaching us. We did some investigation and are finding ways to do a quick fix. I will make the update at once.

**Comment by YijunMS** [comment] 2024-04-09 12:23
It should be fixed. Please let know if the problem still exists.

**Comment by abhishekg1991** [comment] 2024-04-09 12:50
Yes working for us now. Thank you

**Comment by vincentgggg12** [comment] 2024-04-10 01:26
Hi @YijunMS and @zhenhuangMSFT ,

Our add-in is for the pharmaceutical industry and business continuity is critical in the manufacturing of pharmaceutical drugs. Our Word add-in stop working completely because of this update. How can we prevent that in the future? Could you please let us know how can we get informed before a Word Online release that we can test before?

Is there anyone we can talk to about this issue? 

Kind Regards,
V

**Comment by JessieChenMS** [comment] 2024-04-10 03:37
Hi @vincentgggg12 thanks for reaching out and sorry for any inconvenience here. Let me add @xiruatms and @wangyun-microsoft to talk about this issue.

**Comment by wangyun-microsoft** [comment] 2024-04-10 16:44
@vincentgggg12, I've already scheduled a meeting with you. Let's chat then.

**Comment by yingyingchoi** [comment] 2024-04-10 18:04
Hi @YijunMS, thanks for the quick fix. Is there a changelog that we can reference for new releases for the Word platform?

**Comment by wangyun-microsoft** [comment] 2024-04-11 07:59
We have ways for you to test the new updates earlier before they go into production. 

For Windows and Mac, you could try insider programs. The link is here: https://insider.microsoft365.com/en-us/join/windows

For Online, you could refer to this link for a targeted release option: https://learn.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?view=o365-worldwide

**Closed as completed** 2024-04-12 17:11 UTC
Labels: Area: Word, Status: fixed
