### ISSUE TITLE
[Outlook] Add-ins are not added to the ribbon when the first custom add-in is unreachable

### ISSUE THREAD

**Issue by ambachtelijk** [OfficeDev/office-js#589] opened 2019-06-30 15:50 UTC
When multiple custom add-ins are added to Outlook, Outlook will only show the the Buttons that are defined in `<ExtensionPoint xsi:type="MessageReadCommandSurface">` when the first add-in in the list of custom add-ins is reachable. 

## Expected Behavior
Each add-in is queried separately by Outlook when it tries to determine if it should load the ribbon buttons that are defined in the add-in manifests, instead of taking the availability of the first add-in as leading for all add-ins.

## Current Behavior
When add-ins have buttons defined in its manifest.xml that are supposed to show in the ribbon, it will only show the buttons when the first add-in that is listed under 'Custom add-ins' in the Add-ins dialog is available.

## Steps to Reproduce, or Live Example
  1. Follow the instructions of https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/manifests.md  to create 2 add-in manifest XML files. Make sure that both manifest XML files have a unique ID. Both manifest XML files should add a single Button to the ribbon under `<ExtensionPoint xsi:type="MessageReadCommandSurface">`. Let the `<Action xsi:type="ShowTaskpane">` SourceLocation of the first manifest file's Button point to a non-existing URL and the SourceLocation of the second manifest to an existing URL.
  1. Go to `Get Add-ins` > `My add-ins` > `Custom add-ins` 
  2. Make sure that the list of custom add-ins is empty.
  3. Add the manifest XML with the **non-existing** SourceLocation URL first.
  4. Add the manifest XML with the **existing** SourceLocation URL second.
  5. Restart Outlook and verify that the Buttons of both add-ins are not added to the ribbon.
  6. Remove the add-in with the non-existing SourceLocation URL, and verify that now the Button of the manifest XML with the exisiting SourceLocation URL is added to the ribbon.

## Context
My add-ins stopped showing in the ribbon because the first add-in in my Custom add-ins list was only available when connected to a VPN, and as such, I could only use my other add-ins when I was connected to said VPN.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop Windows 10 - 1903
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1152.18.1903.0
* Operating System: Windows 10 - Build 1903
* Browser (if using Office Online): n/a

## Example manifest
Please make sure that ADDIN_URL is replaced with an existing URL and that all URL's resolve to existing locations. Replace the value in the <Id> tag for a valid UUID. 
In order to create a manifest with a non-existing URL, only the URL in `<bt:Url id="messageReadTaskPaneUrl" DefaultValue="https://ADDIN_URL"/>` has to be replaced with a non-existing location.

```
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp
        xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
        xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides"
        xsi:type="MailApp">

    <!-- Begin Basic Settings: Add-in metadata, used for all versions of Office unless override provided. -->

    <!-- IMPORTANT! Id must be unique for your add-in, if you reuse this manifest ensure that you change this id to a new GUID. -->
    <Id>UUID</Id>

    <!--Version. Updates from the store only get triggered if there is a version change. -->
    <Version>1.0.0.0</Version>
    <ProviderName>Contoso</ProviderName>
    <DefaultLocale>en-US</DefaultLocale>
    <!-- The display name of your add-in. Used on the store and various places of the Office UI such as the add-ins dialog. -->
    <DisplayName DefaultValue="Manifest test" />
    <Description DefaultValue="Manifest test"/>

    <!-- Icon for your add-in. Used on installation screens and the add-ins dialog. -->
    <IconUrl DefaultValue="https://ADDIN_URL/assets/icon-32.png" />
    <HighResolutionIconUrl DefaultValue="https://ADDIN_URL/assets/hi-res-icon.png"/>

    <!--If you plan to submit this add-in to the Office Store, uncomment the SupportUrl element below-->
    <SupportUrl DefaultValue="https://microsoft.com" />

    <!-- Domains that will be allowed when navigating. For example, if you use ShowTaskpane and then have an href link, navigation will only be allowed if the domain is on this list. -->
    <AppDomains>
        <AppDomain>ADDIN_URL</AppDomain>
    </AppDomains>
    <!--End Basic Settings. -->

    <Hosts>
        <Host Name="Mailbox" />
    </Hosts>
    <Requirements>
        <Sets>
            <Set Name="Mailbox" MinVersion="1.7" />
        </Sets>
    </Requirements>
    <FormSettings>
        <Form xsi:type="ItemRead">
            <DesktopSettings>
                <SourceLocation DefaultValue="https://ADDIN_URL"/>
                <RequestedHeight>450</RequestedHeight>
            </DesktopSettings>
        </Form>
    </FormSettings>

    <Permissions>ReadWriteMailbox</Permissions>
    <Rule xsi:type="RuleCollection" Mode="Or">
        <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
    </Rule>
    <DisableEntityHighlighting>false</DisableEntityHighlighting>

    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
        <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
            <Requirements>
                <bt:Sets DefaultMinVersion="1.7">
                    <bt:Set Name="Mailbox" />
                </bt:Sets>
            </Requirements>
            <Hosts>
                <Host xsi:type="MailHost">

                    <DesktopFormFactor>
                        <!-- Location of the Functions that UI-less buttons can trigger (ExecuteFunction Actions). -->
                        <FunctionFile resid="functionFile" />

                        <!-- Message Read -->
                        <ExtensionPoint xsi:type="MessageReadCommandSurface">
                            <!-- Use the default tab of the ExtensionPoint or create your own with <CustomTab id="myTab"> -->
                            <OfficeTab id="TabDefault">
                                <!-- Up to 6 Groups added per Tab -->
                                <Group id="msgReadGroup">
                                    <Label resid="groupLabel" />
                                    <!-- Launch the add-in : task pane button -->
                                    <Control xsi:type="Button" id="msgReadOpenPaneButton">
                                        <Label resid="paneReadButtonLabel" />
                                        <Supertip>
                                            <Title resid="paneReadSuperTipTitle" />
                                            <Description resid="paneReadSuperTipDescription" />
                                        </Supertip>
                                        <Icon>
                                            <bt:Image size="16" resid="icon16" />
                                            <bt:Image size="32" resid="icon32" />
                                            <bt:Image size="80" resid="icon80" />
                                        </Icon>
                                        <Action xsi:type="ShowTaskpane">
                                            <SourceLocation resid="messageReadTaskPaneUrl" />
                                            <SupportsPinning>true</SupportsPinning>
                                        </Action>
                                    </Control>
                                    <!-- Go to http://aka.ms/ButtonCommands to learn how to add more Controls: ExecuteFunction and Menu -->
                                </Group>
                            </OfficeTab>
                        </ExtensionPoint>

                        <!-- Go to http://aka.ms/ExtensionPointsCommands to learn how to add more Extension Points: MessageRead, AppointmentOrganizer, AppointmentAttendee -->
                    </DesktopFormFactor>
                </Host>
            </Hosts>

            <Resources>
                <bt:Images>
                    <bt:Image id="icon16" DefaultValue="https://ADDIN_URL/assets/icon-16.png"/>
                    <bt:Image id="icon32" DefaultValue="https://ADDIN_URL/assets/icon-32.png"/>
                    <bt:Image id="icon80" DefaultValue="https://ADDIN_URL/assets/icon-80.png"/>
                </bt:Images>
                <bt:Urls>
                    <bt:Url id="functionFile" DefaultValue="https://ADDIN_URL/function-file/function-file.html"/>
                    <bt:Url id="messageReadTaskPaneUrl" DefaultValue="https://ADDIN_URL"/>
                </bt:Urls>
                <bt:ShortStrings>
                    <bt:String id="groupLabel" DefaultValue="Manifest test"/>
                    <bt:String id="customTabLabel"  DefaultValue="Manifest test"/>
                    <bt:String id="paneReadButtonLabel" DefaultValue="Manifest test"/>
                    <bt:String id="paneReadSuperTipTitle" DefaultValue="Manifest test"/>
                    <bt:String id="paneTitle" DefaultValue="Manifest test"/>
                </bt:ShortStrings>
                <bt:LongStrings>
                    <bt:String id="paneReadSuperTipDescription" DefaultValue="Manifest test."/>
                </bt:LongStrings>
            </Resources>
        </VersionOverrides>
    </VersionOverrides>
</OfficeApp>
```

**Comment by kbrandl** [comment] 2019-07-01 20:06
@ehmPlankje thanks for reporting this issue; we'll look into it.

@exextoc FYI, assigning this issue to you for investigation (since it's Outlook-related).

**Comment by exextoc** [comment] 2019-07-22 21:01
We aren't able to repro this in house. I used your dummy manifest and replaced the dummy url with "contoso.com", and that add-in didn't load but it didn't prevent other add-ins (even those installed afterward) from loading. 

There may be something else in your faulty manifest that is causing the issue? Do you have a sample of your manifest that is causing the issue that doesn't have URLs replaced? 

Some other things: 

- Rebooting Outlook may help. Installing a new add-in is supposed to contact Exchange to get new manifests, but if there is an error in the server request new Manifests may not be retrieved, rebooting will force it to update. 

- The messageReadTaskPaneUrl shouldn't affect loading in the ribbon, (and shouldn't affect other add-ins). Though it will affect it AFTER you click the button. Unless there is a parsing error in the manifest there, (which is why obtaining the actual manifest may help debugging) 

- What may affect ribbon display is the icon that is displayed in the url. 

```
                <bt:Images>
                    <bt:Image id="icon16" DefaultValue="https://ADDIN_URL/assets/icon-16.png"/>
                    <bt:Image id="icon32" DefaultValue="https://ADDIN_URL/assets/icon-32.png"/>
                    <bt:Image id="icon80" DefaultValue="https://ADDIN_URL/assets/icon-80.png"/>
                </bt:Images>
```

If those are unreachable, then the add-in should still show but with a placeholder icon. (it may take sometime before Office gives up on downloading those icons though), so you may not see your add-in immediately.

**Closed as completed** 2019-08-13 23:57 UTC
Labels: Area: Outlook

**Comment by RA-Davies** [comment] 2024-02-20 15:32
Anyone have an update on this? I have the same issue.

Simplest way to reproduce it: follow the tutorial instructions here: https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator 

Now try changing the ExtensionPoint node in the manifest.xml (e.g. from "MessageComposeCommandSurface" to  "MessageReadCommandSurface", nothing you do will have any impact on the location/ribbon this button is shown on from what I can see
