### ISSUE TITLE
getSelectedRange leads to error when chart is selected

### ISSUE THREAD

**Issue by Alex0cean** [OfficeDev/office-js#2268] opened 2021-11-23 12:09 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Calling 
Workbook.getSelectedRange
Workbook.getSelectedRanges
leads to error when a chart is selected. 

## Your Environment
Excel Mac desktop 16.55 (but also current MS channels are afftected)
 
## Expected behavior
Don't throw error, but return object with isNullObject.

## Current behavior
Error 

## Steps to reproduce
Standard ScriptLab Sample ‚Selected Range’
See attached video

## Link to live example(s)
See attached video

https://user-images.githubusercontent.com/80747078/143021064-08c51d63-c850-442f-8227-b3b32f04bbc8.mov

**Comment by preethikakiru** [comment] 2021-11-23 20:41
Hi @Alex0cean thank you for submitting this issue! I've assigned this issue to @dingjin-ms who will be able to further help you resolve this issue and provide you with more information!
Best,
Preethika

**Comment by xuxife** [comment] 2021-11-24 06:55
Hi @Alex0cean, 
throwing `InvalidSelectionException` from '`Workbook.getSelectedRange`' when a chart is selected is **by-design** according to our API contract.
There're indeed a set of [*OrNullObject APIs]() satisfying your description

> Don't throw error, but return object with isNullObject.

**Comment by chiz-ms** [comment] 2021-11-24 08:26
Thank you @Alex0cean for reporting this issue. According to the team, the behavior of `Workbook.getSelectedRange` and `Workbook.getSelectedRanges` is by design. It aligns with other APIs where we provide `*OrNullObject` variations for the purpose of not throwing exceptions. In this case, you may want to ask for new APIs `Workbook.getSelectedRangeOrNullObject` and `Workbook.getSelectedRangesOrNullObject`. @RuoyingLiang on this feature request.

**Comment by RuoyingLiang** [comment] 2021-11-24 08:43
Hi @Alex0cean , You may consider to catch the exception when Workbook.getSelectedRange and Workbook.getSelectedRanges. Currently, we don't have Workbook.getSelectedRangeOrNullObject and Workbook.getSelectedRangesOrNullObject. You could go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) to submit a request.

**Closed as not planned** 2024-03-25 20:12 UTC
Labels: Area: Excel, Type: product feature request
