### ISSUE TITLE
insertFileFromBase64() Method Not Working Properly on Office for the Web

### ISSUE THREAD

**Issue by Piyush-IT** [OfficeDev/office-js#4682] opened 2024-07-15 10:36 UTC
We are developing an Office Add-in product that uses the insertFileFromBase64() method to load Word documents. This functionality works fine on the Windows Desktop version of Word but does not work properly on Office for the Web. The process appears to get stuck or goes into an infinite loop.
Code : 
 context.document.insertFileFromBase64(PrecheckResult.base64Response.docxAsBase64, "Replace", {
     importTheme: true,
     importStyles: true,
     importParagraphSpacing: true,
     importPageColor: true,
     importChangeTrackingMode: true,
     importCustomProperties: true,
     importCustomXmlParts: true,
     importDifferentOddEvenPages: true
 });

Platform: Office for the Web
Host: Word
Office Version Number: Office 365
Operating System: Windows 10 (for testing purposes)
## Expected behavior
The Word document should load successfully using the insertFileFromBase64() method on both the Windows Desktop version and Office for the Web.

## Current behavior
The Word document loads successfully on the Windows Desktop version but does not load properly on Office for the Web. The process gets stuck or appears to enter an infinite loop

## Steps to reproduce
1.Create an Office Add-in that uses the insertFileFromBase64() method to load a Word document.
2.Test the add-in on the Windows Desktop version of Word and Office for the Web.
3.Observe that the document loads successfully on the Windows Desktop version but not on Office for the Web like stuck in between or goes to infinite loop.

**Comment by AlexJerabek** [comment] 2024-07-15 18:49
Hi @Piyush-IT,

Thanks for reporting this. @shanshanzheng-dev, could you please investigate?

**Comment by shanshanzheng-dev** [comment] 2024-07-16 03:40
Hi @Piyush-IT Do you test this API using script lab? could you share us the whole code, we're trying to repro your problem? Thanks.

**Comment by KishanVaishnani** [comment] 2024-07-16 07:39
Hi @Piyush-IT I had similar issues with my Word add-in. To fix it, I removed the 'importDifferentOddEvenPages: true' option. Please give it a try.

**Comment by Piyush-IT** [comment] 2024-07-16 11:55
Thanks for response...Let me check

**Comment by shanshanzheng-dev** [comment] 2024-07-18 02:48
Thanks @KishanVaishnani. Hi @Piyush-IT, I'd like to check with you if that way is working? Are you still hit this issue? Thanks.

**Comment by Piyush-IT** [comment] 2024-07-18 04:03
Thanks for the quick reply but same things are not working... I will share the code

**Comment by knopmickael** [comment] 2024-07-23 18:53
The same behavior is happening to my code, it starts importing, imports (you can see the document changing) but the modal never dismiss, and if it does, it throws an exception to refresh the word page (web)

In my case @Piyush-IT @shanshanzheng-dev @KishanVaishnani @AlexJerabek, im trying to import a docx as base64 and the problem I detected is about the number of pages of the docx... if it has only 1 page, it starts the infinity import, otherwise, if it has at least 2 or more, it imports properly

**Comment by shanshanzheng-dev** [comment] 2024-07-24 02:19
Hi @Piyush-IT @knopmickael Thanks for reporting this issue. Could you share us the repro code, manifest or some detail message? We'll try to look into the root cause. Thanks.

**Comment by knopmickael** [comment] 2024-07-30 13:48
@shanshanzheng-dev @Piyush-IT, just invited you guys to the repro code right now

https://github.com/knopmickael/office-importFileAsBase64-bug-demo

It's a pretty simple example, the base64 reffered files are those docxs on the root
I did not wrote any server script to convert the docx files into base64 strings, but anyway I dont really think the point could be around it

**Comment by Piyush-IT** [comment] 2024-07-30 13:52
Facing hanging issue while opening the document..

If any problem in 'insertFileFromBase64' method?

**Comment by shanshanzheng-dev** [comment] 2024-07-31 07:03
Hi @knopmickael Thanks for provide this information, seem I can repro this issue,  if it insert only 1 page, it'll refresh and loop. We'll be looking into this issue and report back if we have a suggestion for you. Thanks.

**Comment by knopmickael** [comment] 2024-08-22 14:39
Hi @shanshanzheng-dev, how you going?
Got any news about the issue?

**Comment by xiruatms** [comment] 2024-08-23 01:18
@knopmickael , thanks for your patience. We've identified potential root cause, and are working on a fix. Will push to production soon if no other concerns found.

**Comment by Piyush-IT** [comment] 2024-09-18 04:59
@knopmickael  Is there any update?

May I know, if the issue is resolved then when will it be rolled out to production?

**Comment by shanshanzheng-dev** [comment] 2024-09-18 05:51
Hi @knopmickael @Piyush-IT We have fixed this issue about one Page, you can try if this issue still happened. Thanks.

**Comment by knopmickael** [comment] 2024-09-20 22:11
Hello @shanshanzheng-dev, I tried it now and it is working properly, really thank you!

**Comment by Piyush-IT** [comment] 2024-09-23 06:48
@knopmickael  :I have a Base64 string and I'm using the importCustomXmlParts and content, but they aren't set correctly in the document, which prevents me from saving it properly or saved not  properly with full content. 

Here’s the code I'm using:
context.document.insertFileFromBase64(PrecheckResult.base64Response.docxAsBase64, "Replace", {
importTheme: true,
importStyles: true,
importParagraphSpacing: true,
importPageColor: true,
importChangeTrackingMode: true,
importCustomProperties: true,
importCustomXmlParts: true,
importDifferentOddEvenPages: true
});

Is there a solution or an alternative method to set the Base64 string in the document?


This is a blocker for our addin so please provide a solution

**Comment by knopmickael** [comment] 2024-09-23 19:16
@Piyush-IT, I dont really think that your call to the insertFile fn is wrong, imo the problem is probably around your B64 string. And unfortunately idk any other method to "import" it

**Comment by knopmickael** [comment] 2024-09-23 19:55
@Piyush-IT
I'm sharing our successful usage case here:

- We have a Java backend script which talks to the Graph Api and retrieve a Site's docx file stream then turn it into the base64 string we are using into the add-in

- I'm also attaching a docx used minutes ago that worked properly, it has only 1 paragraph on it - attached the outputed b64 too, take a look:

![java1](https://github.com/user-attachments/assets/77acb42b-9220-43cf-bbd6-3713f240aaad)
![java2](https://github.com/user-attachments/assets/c68a70a7-dd3a-4eee-b3ff-f28c0e3b0de3)

Hope it helps!
[base64.txt](https://github.com/user-attachments/files/17103468/base64.txt)
[original.docx](https://github.com/user-attachments/files/17103469/original.docx)

**Comment by Piyush-IT** [comment] 2024-09-24 14:40
@knopmickael  : Thanks for quick update and let me try above code in my project.

**Comment by RuizhiSunMS** [comment] 2024-11-14 16:09
Close this case since the fix has been released. Please feel free to reopen it if wrong.

**Closed as completed by RuizhiSunMS** 2024-11-14 16:09 UTC
Labels: Type: product bug, Area: Word
