### ISSUE TITLE
Outlook for Windows: "Resources" behavior in Calendar view

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#2944] opened 2022-10-31 09:42 UTC
Outlook for Windows: "Resources" behavior in Calendar view

I have a question about the return value of the `enhancedLocation.getAsync` method.

I have confirmed the following behavior in Outlook for Windows:
* The "Rooms" box and the "Resources" box are the same.
* (1) When an Equipment or User is specified in the "Resources" box (= "Rooms" box), it will be displayed in the "Required" field.
* (2) When a Room or Workspace is specified in the "Rooms" box (= "Resources" box), it will appear in the "Location" field.

* (3) When a Room or Workspace is specified in the "Required" box, it will appear in the "Required" and "Location" fields.
  * (4) Remains in the "Required" field even if removed from the "Location" field.

For each case at this time:

> * (1) When an Equipment or User is specified in the "Resources" box (= "Rooms" box), it will be displayed in the "Required" field.
> * (2) When a Room or Workspace is specified in the "Rooms" box (= "Resources" box), it will appear in the "Location" field.
> * (3) When a Room or Workspace is specified in the "Required" box, it will appear in the "Required" and "Location" fields.

You can get the value with the `enhancedLocation.getAsync` method.

I think it is incorrect to have type=Room in the return value of the `enhancedLocation.getAsync` method when specifying equipment or user. Is there an internal reason why equipment and users cannot be retrieved by the `requiredAttendees.getAsync` method as per the creation screen?

>   * (4) Remains in the "Required" field even if removed from the "Location" field.

You can get the value with the `requiredAttendees.getAsync` method.

Here is the video reproducing the above. Outlook for Windows: Version 2210 (Build 15726.20174)

https://user-images.githubusercontent.com/58804032/198968663-b9985e68-0706-423b-b8f9-0f693b72685e.mp4

![equipment](https://user-images.githubusercontent.com/58804032/198968704-08635768-f7d7-461f-a0a0-2e3c3500f8bd.png)

``` ts
function get() {
  Office.context.mailbox.item.requiredAttendees.getAsync(v => console.log(v));
  Office.context.mailbox.item.enhancedLocation.getAsync(v => console.log(v));
}
```

``` json
{
    "value": [
        {
            "locationIdentifier": {
                "id": "cequip@example.com",
                "type": "room"
            },
            "displayName": "cequip",
            "emailAddress": "cequip@example.com"
        }
    ],
    "status": "succeeded"
}
```

Please let me know about the expected behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8922b63d-51bd-5f4a-0c33-63e9715103c2
* Version Independent ID: 9add94e6-3658-b586-4906-3ff07dd10bf7
* Content: [Get or set the location of an appointment in an add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/get-or-set-the-location-of-an-appointment)
* Content Source: [docs/outlook/get-or-set-the-location-of-an-appointment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/get-or-set-the-location-of-an-appointment.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2022-10-31 16:16
Thanks for reporting this @clavx.

@samantharamon, can you please investigate?

**Comment by samantharamon** [comment] 2022-11-02 21:47
Hi @clavx,

Thank you for providing details about your test scenarios. The video of the behavior you're getting is much appreciated. I'll look into this further to determine the expected behavior and get back to you.

**Comment by samantharamon** [comment] 2022-11-04 00:48
Thanks for your patience, @clavx. I've confirmed that the behavior you're experiencing is expected when running `enhancedLocation.getAsync`. 

`enhancedLocation.getAsync` gets the locations specified in the Location field of the invite, then determines if each location also appears in the Required > Resources field. This determines the [location type](https://learn.microsoft.com/javascript/api/outlook/office.mailboxenums.locationtype). If the location is only found in the Locations field and doesn't have an SMTP address, it is of type `Custom`. However, if the location is also found in the Resources field, has an SMTP address, and isn't a distribution list, it is of type `Room`. Because locations only have these two types, equipment and users in the Resources field are identified as `Room`. I've created a work item to further clarify our location type docs with this information (internal work number: 7075921).

Equipment or users added to the Required > Resources field aren't returned when running `requiredAttendees.getAsync` as this method only returns values in the Required > Required field. This also explains why a room you remove from the Location field, but not from the Required field, is returned by `requiredAttendees.getAsync`.

Please don't hesitate to reach out if you have additional questions.

**Comment by clavx** [comment] 2022-11-04 11:25
@samantharamon 
Thank you for your detailed explanation.

> However, if the location is also found in the Resources field, has an SMTP address, and isn't **a distribution list**, it is of type Room.

Is the distribution list a group created by using the [New-DistributionGroup](https://learn.microsoft.com/en-us/powershell/module/exchange/new-distributiongroup?view=exchange-ps#-roomlist) cmdlet with the `RoomList` parameter?
Distribution lists (distribution groups, security groups, etc.) also returned `Room` type.

As far as I can see, each API seems to be mapped as follows:

![apis](https://user-images.githubusercontent.com/58804032/199943668-b39342a3-7931-4bbe-be33-6dd502e22ddd.png)

I think you can tell if it's a Room type by the presence of `DT_ROOM`, but does the `enhancedLocation` method not refer to the value of [PidTagDisplayTypeEx](https://learn.microsoft.com/en-us/office/client-developer/outlook/mapi/pidtagdisplaytypeex-canonical-property)?

![PidTagDisplayTypeEx](https://user-images.githubusercontent.com/58804032/199943718-1a4e8b78-07e6-4bd5-badd-d4f7999a5d55.png)

In our scenario, when a user accidentally adds a regular user to the Resources field, we want our add-in to treat it as a required attendee, similar to Outlook's Compose screen, but we are having trouble distinguishing it because it is a `Room` type.
In the Microsoft 365 admin center (and the Exchange admin center), there are two resources, Equipment and Room, and I think you should be able to distinguish between Room and other when it has an SMTP address.

**Comment by samantharamon** [comment] 2022-11-04 23:09
Thanks for providing the scenario you're trying to address, @clavx. Regarding the distribution list condition, I verified that it only applies to [personal contact groups](https://support.microsoft.com/office/create-a-contact-group-or-distribution-list-in-outlook-for-pc-88ff6c60-0a1d-4b54-8c9d-9e1a71bc3023) and not Exchange distribution lists. Exchange distribution lists added via the Location field (which are then displayed in the Resources field) are returned by `enhancedLocation.getAsync` with type `Room`.

Currently, `enhancedLocation` doesn't refer to the PidTagDisplayTypeEx's DT_Room value. Because adding another location type to account for non-room resources with SMTP addresses and referring to PidTagDisplayTypeEx in the `enhancedLocation` API logic would count as feature requests, may I request you to submit your request via the [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions)? This will allow the team to further review your scenario. Thank you.

**Comment by clavx** [comment] 2022-11-07 09:07
@samantharamon , thank you for your response and the information on where to submit our feature request.

I had overlooked the existence of contact groups. I have checked the behavior when specifying a contact group, and its existence itself does not appear to be detectable by the Office.js API. There is no change depending on whether or not a contact group is specified.

Is the specification that if a contact group is specified in the Resources field, the value cannot be retrieved from the Office.js API?

**Comment by samantharamon** [comment] 2022-11-07 18:56
That's correct. Identifying a contact group in the Resources field would also be a feature request. The contact group value can only be retrieved from the Required and Optional fields at this time.

**Comment by clavx** [comment] 2022-11-08 09:27
Thank you for your confirmation.

We have submitted our request.
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/retrieving-information-specified-in-the-resources-field-in/idi-p/3671521

Thank you.

**Comment by samantharamon** [comment] 2022-11-12 00:45
Thank you, @clavx.

**Comment by samantharamon** [comment] 2023-05-06 01:43
Hi, @clavx. Thank you again for submitting a feature request. I'll go ahead and close this issue. Please continue to check on your request for any updates. If you require further assistance, please do not hesitate to create a new GitHub issue.

**Closed as completed by samantharamon** 2023-05-06 01:43 UTC
Labels: Area: Outlook, Type: product feature request, Type: discussion
