### ISSUE TITLE
[Outlook Desktop Windows] Double pinning freezes 'all' add-in's

### ISSUE THREAD

**Issue by wsoccorsi-yw** [OfficeDev/office-js#1626] opened 2021-02-01 20:13 UTC
Pinning Outlook add-ins, which are "cached" in Outlook Desktop freezes or changes the mouse detection of the second opened add-in. 

## Expected Behavior
Click on an email, open and then pin my add-in in read mode. Reply to an email and open add-in in compose mode. This second opened add-in should be clickable and interactive.

## Current Behavior
Click on an email, open and then pin my add-in in read mode. Reply to an email and open add-in in compose mode. This add-in is no longer interactive. It registers no mouse events such as hover and click.

## Steps to Reproduce, or Live Example

Pinning read and then going to an inline compose. I'm constantly clicking the add-in here even those my mouse is not shown. This happens for every add-in I try but salesforce seems to be a simple example.
https://user-images.githubusercontent.com/61157542/106512315-6ca0fe80-649f-11eb-9413-48ce265f132b.mp4

Not pinning read and then going to an inline compose. 
https://user-images.githubusercontent.com/61157542/106512526-bab60200-649f-11eb-8ab1-0cb150e46d9f.mp4

## Context
Users are coming to our support complaining that their add-in is frozen. They can only compose messages in a pop out window. This pop out window is rarely used however because it is clunkier and slower.

## Your Environment
Windows: Version 2102 Build 13714.20000 
Outlook 2012 (13530.20440)

Please let me know if you need more examples or anything else. 
Thanks in advance!

Edit: Note - Webview 2 does not have this issue only Webview 1, hopefully this helps.

**Comment by exextoc** [comment] 2021-02-04 03:30
Thank you for reporting this issue regarding pinning causing add-ins to freeze. We have forwarded this issue along to the appropriate team, and it has been added to their backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: [29713794]

**Comment by exextoc** [comment] 2021-04-27 01:00
The issue is fixed in all windows builds 21340 and later. Status on backports to older versions of Windows is still being decided.

**Comment by exextoc** [comment] 2021-10-29 20:02
This issue was fixed, and the fix should be available in Windows build 19043.1266 or later. Note that it is the Windows Build that matters, not the Office build.

**Closed as completed by exextoc** 2021-10-29 20:02 UTC
Labels: Area: Outlook, Type: product bug
