### ISSUE TITLE
Text stuck in status bar after call add-in command from ribbon button

### ISSUE THREAD

**Issue by Biktop** [OfficeDev/office-js#2877] opened 2022-09-30 03:00 UTC
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.65 (22091101) (Mac)
* Operating System: MacOS 12.6
 
## Current behavior
I use [Office-Add-in-samples](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/excel-shared-runtime-scenario) and slightly modified the source code in [commands.js](https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/excel-shared-runtime-scenario/src/commands/commands.js)
```
async function btnOpenTaskpane(event) {
 console.log("Open task pane button pressed");
 // Your code goes here
 await SetRuntimeVisibleHelper(true);
 g.state.isTaskpaneOpen = true;
 updateRibbon();
 event.completed();
}
```

So now Office.addin.showAsTaskpane() is called synchronously before event.completed() that leads to strange behaviour when the text in the status bar always displays **Contoso Data Importer is working on your Open task pane** and it continues to display even after pressing any other buttons in the ribbon. With the original code it works correctly. Also it works in Office on the web.

![Screenshot 2022-09-30 at 04 49 42](https://user-images.githubusercontent.com/742501/193180216-574c1b4c-4a8b-4d5c-9ae2-0b4ac8879eb6.jpg)

**Comment by gingerjia** [comment] 2022-09-30 08:32
@madhavagrawal17 could you help to take a look at it seems it's shared runtime related? Thanks very much!

**Comment by madhavagrawal17** [comment] 2022-10-07 18:58
Thanks for reporting this issue. I tried to reproduce the problem locally, but it seems it is not SharedRuntime-related. The appropriate team is working on this issue. We will provide an update once we find the root cause of this issue.

**Comment by wh1t3cAt1k** [comment] 2023-02-20 17:06
Dear Microsoft team, is there any news on this issue? It's been 4 months since the last update, and to the best of our knowledge, the issue still replicates on both the PC desktop and Mac. This negatively impacts the user perception of the add-in for ribbon-oriented user interfaces.

**Comment by wh1t3cAt1k** [comment] 2023-03-22 14:10
@Wenjun-Gong @RuizhiSunMS I would like to follow up on this again...

For now, when user initiates any operation from the Ribbon, because the message in the status bar gets "stuck", the user may mistakenly think that the add-in has frozen working on an operation.

We have to pop a side panel with operation progress messages, which is suboptimal UX. (and the stuck status bar is misleading anyway). We would like to avoid having to pop the side panel just for UI feedback on the operation.

**Comment by pkkj** [comment] 2023-03-23 02:26
Hi wh1t3cAt1k,

If possible, you may try to call event.complete() without waiting the taskpane showing up.

Thanks.

**Comment by wh1t3cAt1k** [comment] 2023-03-24 14:24
@pkkj some of our operations are long. When we call `event.completed()` the user loses **all** visual indication of what's going on because the status bar is cleared immediately.

So either we have to:
- Open the side panel for indication, instead of using the status bar
- Or make user live without any visual indication of the progress of our long-running operation (neither the status bar, nor the side panel)

We would prefer the status bar to work properly. Opening side panel on every operation feels intrusive and unnecessary.
(cc @gmichaud)

**Comment by pkkj** [comment] 2023-03-24 22:49
Hi wh1t3cAt1k,

Due to there is a bug in the status bar (it's related to App Command action and showing taskpane), there is no better work around. If possible, you could put showingtakepane at the end of the action function, and call event.complete() before it.

A fix will be made to mitigate this issue but it will take some time to reach the production.

Thanks.

**Comment by wh1t3cAt1k** [comment] 2023-03-27 00:11
Hi @pkkj - is this bug (https://github.com/OfficeDev/office-js/issues/3250) I filed related? You mentioned "showing taskpane".

I understand it can take some time to reach production, can you advise on the following?

- Will the fix be in Office.js or on the host app?
- Expected fix version on Windows and Mac.

Thank you.

**Comment by Biktop** [comment] 2023-03-29 01:25
Hi,

I played with 16.0.16227.20212 because of #2716 and I have managed to repeat this bug again.

**Comment by wh1t3cAt1k** [comment] 2023-07-06 15:33
@pkkj @Wenjun-Gong please give us an update if possible since we're forced to take poor UX workarounds due to this bug... Thanks

**Comment by pkkj** [comment] 2023-07-06 19:59
This bug should have been fixed in the newest Office build.

Thanks

**Comment by wh1t3cAt1k** [comment] 2023-07-12 14:57
@pkkj can you provide more detailed version information (Mac and Windows) on which the issue should be fixed?

**Comment by wh1t3cAt1k** [comment] 2024-01-08 21:06
@madhavagrawal17 @JinghuiMS @zhaoliu-MSFT 

This is definitely not fixed in the latest Mac OS build, it was just observed by @gmichaud:

![image](https://github.com/OfficeDev/office-js/assets/5159662/5a450e36-37ff-453a-bc4c-3432a93153c7)

Can we please revisit this bug and investigate whether there's another possibility for the text to get stuck?

Note that we call `event.completed()` **immediately** in the handler before starting any async work.

**Comment by zhenhuangMSFT** [comment] 2024-01-10 02:35
Thanks for reporting this issue. Since the setup and issue repro takes some time, our response may be delayed. Thanks for your patience.

**Comment by pkkj** [comment] 2024-02-07 02:55
I try this scenario again butI am not able to repro it. I also tried to call event.complete() before any async work but I am not able to hit this problem.

I have a very simple test add-in to play with this scenario: [Manifest](https://kepengtestapp.azurewebsites.net/manifest/OpenCloseTaskpaneDemo.xml) . It only has two buttons (show and hide a taskpane) and its coding pattern is very similar to the sample test add-ins. The status bar text dismiss correctly after the ui-less action completes.

**Comment by wh1t3cAt1k** [comment] 2024-02-07 15:24
@pkkj what platform did you try to replicate? Mac or Windows? Our latest replication scenarios all happened on Excel Desktop for Mac.

**Comment by pkkj** [comment] 2024-02-07 18:27
@wh1t3cAt1k I verify this scenario in both Win32 and Mac and didn't see this problem. If possible, you may try to sideload the test add-in mentioned in previous reply, after you read the source code. You could play with that in your environment to figure out whether the bug can repro. If the source of my test add-in is not able to demonstrate the your scenario, feel free to share a minimum code sample that can repro this bug. Thanks.

**Closed as completed** 2024-03-05 05:50 UTC
Labels: Status: under investigation
