### ISSUE TITLE
Office Add-ins - Admin Managed - MacOS desktop client - Error: Cannot connect to catalog

### ISSUE THREAD

**Issue by ivebeenchosen** [OfficeDev/office-js#3221] opened 2023-03-15 09:44 UTC
## Your Environment
* Platform: Mac
* Host: Word, Excel..
* Office version number: 16.71
* Operating System: macOS Ventura, 13.2.1
 
## Expected behavior
We have deployed a few Word-apps via the Microsoft 365 admin center -> Integrated apps.

These should be able to be seen when opening "Get Add-ins" in an Office-application -> Admin Managed.

## Current behavior
We have an issue with seeing Add-ins in the MacOS Word-desktop client. It shows the error "Cannot connect to catalog" when opening "Add-ins" in Office-apps like Word, Excel, etc. Issue also occurs in other Office-apps when you open"Add-ins".

This error is seen for all users in the tenant.

# Provide additional details
 
We have both functions enabled inside Org settings -> Services -> User owned apps and services: "Let users access the Office Store" and "Let users auto-claim licenses the first time they sign in".

We have "Turn on optional connected experiences" enabled on the Mac-clients.

We have allowed full disk access to Word, Outlook etc.
 
We can see the Admin Managed-pane in Add-ins, and the deployed Add-ins, in the web-browser on both PC and Mac. We can also see the it on the PC Desktop client of the Office-apps.

But when we try to open Office Add-ins Admin Managed via an Office-app (like Word) on a Mac we get following error: Cannot connect to catalog. 

![image](https://user-images.githubusercontent.com/123166622/225270598-70de9a38-f021-4d7b-a343-241543ee1ee4.png)

In Outlook for the Macs, the "Get Add-ins"-button is also greyed out.

**Comment by preethikakiru** [comment] 2023-03-16 18:38
Hello @ivebeenchosen , thank you for submitting this issue! 
I've assigned it to @AkhileshShah-MS who will be able to provide you with more information or help resolve the issue.
Best,
Preethika

**Comment by zeoc** [comment] 2023-03-17 17:06
Any news on this ? 
We have the same thing here Office365 Word 16.71 and Ventura 13.2.1 
The same Addin works on windows and office365 Word Web.
Thanks for any update

**Comment by wh1t3cAt1k** [comment] 2023-03-17 23:20
@Wenjun-Gong this is a blocker issue that completely prevents us from deploying centrally at least to Mac users on M1 / Ventura.

Please give this some attention if possible...

**Comment by melaniejayde** [comment] 2023-03-18 02:01
My organisation is also encountering this issue. We so far have not found a way around it. Also using Mac and Ventura. Windows and Chrome are fine

**Comment by Wenjun-Gong** [comment] 2023-03-18 02:05
@AkhileshShah-MS , would you please take a look at this issue? Thanks.

**Comment by AkhileshShah-MS** [comment] 2023-03-20 05:15
Hi @ivebeenchosen , @wh1t3cAt1k , @zeoc , @melaniejayde! Thanks for reaching out. 
To help us debug the issue, can you please share following information on email to addin-help@outlook.com. 
- Impacted Tenant ID
- Impacted User Email ID
- Fiddler trace for launching in-client store/error repro
Thank you!

**Comment by ivebeenchosen** [comment] 2023-03-20 11:52
Hello again.

From this thread: https://techcommunity.microsoft.com/t5/word/office-add-ins-error-cannot-connect-to-catalog/m-p/2702496

![image](https://user-images.githubusercontent.com/123166622/226331418-507945b1-f066-41b5-a4b6-c135522907d4.png)

So issue seems to be with the newer versions. I am downgrading and testing if it works with older version from january 13th. 16.69 (23010700)


### Edit: Confirms Admin Managed Add-ins works with downgrading to [Office 365 16.69 (23010700)](https://learn.microsoft.com/en-us/officeupdates/update-history-office-for-mac#release-history-for-office-for-mac) on Mac.

**Comment by zeoc** [comment] 2023-03-22 09:14
I confirm that downgrading to 16.69 resolve the problem.

**Comment by exextoc** [comment] 2023-03-24 09:28
@zeoc @melaniejayde 
Tried to repro the issue with the latest version in Mac word/excel but it is working fine.
To help us debug the issue, can you please share following information on email to [addin-help@outlook.com](mailto:addin-help@outlook.com).


- Impacted Tenant ID
- Impacted User Email ID
- Fiddler trace for launching in-client store/error repro

Thank you!

**Comment by pvsleeper** [comment] 2023-03-28 21:27
@exextoc - any feedback regarding this issue yet? Our team also confirmed that rolling back to 16.69 allows us to work around the issue.

**Comment by wh1t3cAt1k** [comment] 2023-03-29 00:07
This kind of blocker issues should not take days to resolve...

**Comment by melaniejayde** [comment] 2023-03-29 23:11
@exextoc unfortunately I cannot provide Fiddler trace as I do not have access within my organisation. I can confirm this morning that the issue seems to have resolved itself for me. Was there a change that has happened recently? I just want to be sure that we do not run into this again as it's been a major blocker for work for at least a month...

**Comment by wh1t3cAt1k** [comment] 2023-07-05 13:38
This issue seems resolved for me. @ivebeenchosen @melaniejayde do you observe the same?

**Comment by exextoc** [comment] 2023-07-14 05:11
@ivebeenchosen @melaniejayde can you confirm if the issue is resolved for you? This appears to be transient issue from client while connecting to the backend service. If you're still facing this, can you please share a fiddler trace if possible. If not, can you please share these details with us:
1. Tenant ID
2. Affected user.
3. Time duration of the error (in the last 30 days)

**Comment by kornect** [comment] 2023-07-24 08:08
Getting the same issue, even with a downgrade to 16.69. The office store doesn't load as well. Looking at the web version, it seems an invalid or expired certificate is being loaded

**Comment by exextoc** [comment] 2023-08-17 12:29
@ivebeenchosen  @melaniejayde  @kornect Please share the below information:
1. Tenant ID
2. Affected user email alias.
3. Time duration of the error (in the last 30 days)

**Comment by exextoc** [comment] 2023-08-21 06:39
Gentle ping @ivebeenchosen @melaniejayde @kornect

**Comment by ivebeenchosen** [comment] 2023-08-21 08:12
> Gentle ping @ivebeenchosen @melaniejayde @kornect

Sorry, I no longer have access to our Mac-Environment, so I am unable to confirm.

Best,

**Comment by exextoc** [comment] 2023-08-25 05:16
Closing this incident because of missing details.

**Closed as completed by exextoc** 2023-08-25 05:16 UTC
Labels: Needs: attention :wave:, Area: Centralized Deployment
