### ISSUE TITLE
[Excel] Shortcut not working

### ISSUE THREAD

**Issue by lordbenz** [OfficeDev/office-js#2270] opened 2021-11-24 05:29 UTC
## Environment
Web: Chrome, Safari, Excel IDV, Excel for Mac
 
## Expected behavior
Able to use shortcut keyboard.

## Current behavior
The shortcut is not working.

## Steps to reproduce
1. Download manifest.xml file from https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/excel-keyboard-shortcuts.
2. Open Office on the web.
3. Choose Excel, and then open a new document.
4. Open the Insert tab on the ribbon and choose Office Add-ins.
5. On the Office Add-ins dialog, select the MY ADD-INS tab, choose Manage My Add-ins, and then Upload My Add-in.
6. Browse to the add-in manifest file, and then select Upload. The upload add-in dialog with buttons for browse, upload, and cancel. 
7. Verify that the add-in loaded successfully. You will see a PnP keyboard shortcuts button on the Home tab on the ribbon.

** Once the add-in is loaded use the following steps to try out the functionality.**
8. Press "Ctrl+Alt+1" on the keyboard to trigger the Show Taskpane action.
9. In the task pane, you will see the additional shortcuts available to try in the sample.

# Provide additional details
We use manifest from the sample project on Microsoft Docs [https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/excel-keyboard-shortcuts](https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/excel-keyboard-shortcuts)

**Comment by preethikakiru** [comment] 2021-11-24 18:30
Hi @benzdechapon, thank you for submitting this issue! I've assigned this issue to @dingjin-ms who will be able to further help you resolve this issue and provide you with more information!
Best,
Preethika

**Comment by davidchesnut** [comment] 2021-11-24 18:45
Hi @benzdechapon, Just for more information, I tested this out and the sample will work in Excel on Windows. Looks like the issue is only happening on Excel on web. In case you need to work around the issue while we look into this more.

Cheers,
David

**Comment by lliu113** [comment] 2021-11-26 18:32
@benzdechapon - thanks for reporting this! Can also confirm that this is working for Excel on Windows but not for Excel on WAC. Considering this is impacting your production add-in, I have opened a Sev 1 incident to help resolve (internal incident id: 274530087). 

We will look into this as quickly as possible, but as it is currently thanksgiving holidays in the USA the majority of the team will be away so traction may be slow. Most people will be back in the office on 11/29 so we will most likely provide an update then. As a workaround, as David mentioned, you can direct your customers to using your add-in on Excel on Windows while we resolve this issue. 

Thanks!
Lillian

**Comment by AbidRahman-MSFT** [comment] 2021-11-29 18:10
The issue has been resolved, and the fix is currently rolling out. Please let us know if you continue to run into issues for shortcuts on Excel on Web.

**Closed as completed** 2022-08-02 18:08 UTC
Labels: Needs: attention :wave:, Area: Excel, Type: product bug, Area: add-in UI

**Comment by lordbenz** [comment] 2022-08-03 05:52
Thanks all
