### ISSUE TITLE
Automatica open of excel add-in

### ISSUE THREAD

**Issue by mseth-intuit** [OfficeDev/office-js#3626] opened 2023-08-30 12:52 UTC
Hello Team,

We are from Intuit and we have developed a product (Excel add-in) that connects with Quickbooks. It is our customer's primary tool for high-volume import and export that financial data from Quickbooks to Excel. This product will be used by 200k customers.
Currently, our users are facing issues while installing the add-in. Excel does not automatically open the add-in after installation. The user has to manually navigate to the ribbon and search for the add-on to open the same. This will reduce the adoption of the add-on significantly.
Could you help us with the existing options available to mitigate this issue? We are open for a quick call as well.

Regards
Intuit Product Development Team

**Comment by Rick-Kirkham** [comment] 2023-08-30 18:50
Duplicate of [3625](https://github.com/OfficeDev/office-js/issues/3625)

**Closed as completed by Rick-Kirkham** 2023-08-30 18:50 UTC
Labels: Resolution: duplicate
