### ISSUE TITLE
ensureUnchanged should lock the object state like `Right click ->lock functionality` of PowerPoint?(preview APIs)

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2514] opened 2022-04-05 13:53 UTC
I tried to do the following:
``` 
PowerPoint.run(async (context) => {
  const selShape = context.presentation.getSelectedShapes();
  selShape.load('items');
  await context.sync();
  context.presentation.ensureUnchanged(selShape.items[0]);
  await context.sync();
});
```

But the shape that was selected does not get locked, I haven't found any documentation on `ensureUnchanged`, but I've see it is an a lot of objects available.

How ca I use it properly?

Thanks

**Comment by Rick-Kirkham** [comment] 2022-04-05 20:00
I suspect that the reason we don't document that method is that it isn't supported for external add-in developers. I have assigned this to LuyiH and I will investigate internally as well.

**Comment by wandyezj** [comment] 2022-04-05 20:51
Hello @danielpdev

How did you discover `ensureUnchanged`?

**Comment by Rick-Kirkham** [comment] 2022-04-05 21:05
@danielpdev I have confirmed that `ensureUnchanged` is for internal use only and is not supported for external add-ins. I'll close this issue; but we'd still like to know how you discovered `enureUnchanged`.

**Closed as completed by Rick-Kirkham** 2022-04-05 21:05 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: PowerPoint

**Comment by danielpdev** [comment] 2022-04-06 08:50
I'm struggling to find ways of making the development of the PowerPoint add-in a bit easy and while searching for what functions and capabilities are exposed on the preview API I found that `ensureUnchanged` was present on the kind of item that I need, which is a `Shape` and the usecase that I was testing was to lock the object for further changes.

Do you know if there is some other ways of doing so? Locking the shape for further changes of the contents inside of it.

**Comment by wandyezj** [comment] 2022-04-06 19:39
@danielpdev

What specific difficulties have you encountered developing PowerPoint Add-Ins?

Where did you search for PowerPoint functions and capabilities? I tend to look for methods on the [Official Office-JS PowerPoint API reference](https://docs.microsoft.com/en-us/javascript/api/powerpoint?view=powerpoint-js-preview)

Would you be able to explain your end to end scenario? I'd like to understand the need to lock a PowerPoint object from further changes.

**Comment by danielpdev** [comment] 2022-04-06 19:51
Hi,

It is kind of easy as a feature, but I find it really hard to implement as for lot of the APIs are not available or I’m not able to find relevant APIs usage.

One more thing is to catch the event when the user closes the PowerPoint(not the addin) and handle this situation with saving the state of the document.

Some of the APIs needed for this are in VBA already, but not in JS version. 

Maybe I should just try to contribute to the library and implement the things I need, do you think it is hard to do it? What are the underlying technologies needed to be up to speed with development?

PS: I looked over the dev apis page that you specified, but didn’t find the things I need, then I looked into the preview APIs and there are some that I find them promising like getting the selected shapes and beforeDocumentClose APIs

**Comment by wandyezj** [comment] 2022-04-06 22:00
Thank you @danielpdev that is quite helpful.

Unfortunately, it's not possible today to contribute code to the office-js API library. 

However, you can contribute by:
-  Telling us more about your scenario and pointing out the specific APIs you need and why, especially if you can point to the equivalent VBA APIs, since this helps us prioritize what APIs to implement.
- Pointing out any issues you have developing your Add-In. this helps us prioritize these problems to solve.

Please continue to reach out if there is anything we can help you with! :)

**Comment by danielpdev** [comment] 2022-04-07 14:05
Ok thing that we need for sure and could not find any solution for it is how to handle when the user closes the powerpoint document (not the addin).

Do you think it can be easy implemented in the office-js?

If I need this feature, where do I make the request for it?
Most importantly, how much time it takes for a feature to be released? Preview version is super ok
