### ISSUE TITLE
Unable to install generator-office

### ISSUE THREAD

**Issue by samarthbharti217** [OfficeDev/office-js#2519] opened 2022-04-07 00:40 UTC
# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Operating System: Windows
 
## Expected behavior
Package should install successfully

## Current behavior
Package install fails due to peer dependency. Error as below:
npm ERR! 404 'cmd-shim@^5.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

Able to explicitly download previous version of cmd-shim: i.e - 4.1.0

## Steps to reproduce

1. npm i yo generator-office --save-dev

# Provide additional details
Raised error with generator-office: https://github.com/OfficeDev/generator-office/issues/699
Raised error with cmd-shim: https://github.com/npm/cmd-shim/issues/62

## Context
Unable to download generator package

## Useful logs
npm ERR! 404 'cmd-shim@^5.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Rick-Kirkham** [comment] 2022-04-08 20:00
@samarthbharti217 I'm closing this as a duplicate of [office-generator 699](https://github.com/OfficeDev/generator-office/issues/699). As @millerds suggested in that issue, you need to raise an issue with the [yeoman generator](https://yeoman.io/learning/support.html).

**Closed as completed by Rick-Kirkham** 2022-04-08 20:00 UTC
Labels: Needs: triage :mag:
