### ISSUE TITLE
How can I add multiple requirements sets to the manifest.xml file for an Office add-in?

### ISSUE THREAD

**Issue by emmanuelpineda** [OfficeDev/office-js#4179] opened 2024-02-26 23:33 UTC
I have an Office add-in that works for Word, Excel and PowerPoint, but I want it to only be available for Office 2021 onwards (Windows Desktop)

I found that it is possible using Requirement Sets, but when I specify 3, the validator (office- addin-manifest) returns an error message:

Error 1: No Supported Office Products: There are no platforms which fulfil the requirements specified in the manifest. The most common reasons for this failure are issues in the Requirements section. Please review the manifest and try again.

The manifest is not valid.

![image](https://github.com/OfficeDev/office-js/assets/45979790/0d8f7238-9c59-41ea-8de0-2f8e73c930ee)

When I specify only one Requirement set, the file passes validation
![image](https://github.com/OfficeDev/office-js/assets/45979790/a1b7712b-3ab0-47bc-a8c2-fc74329176b8)

![image](https://github.com/OfficeDev/office-js/assets/45979790/f5478f17-aebc-480a-98f2-99189a7b8e0a)

**Comment by lindalu-MSFT** [comment] 2024-02-27 18:39
@Wenjun-Gong @Rick-Kirkham Hi, this issue is about requirement sets and manifest validation. Are the right folks to assign? If so, please review! If not, please let me know who to assign to.

**Comment by Wenjun-Gong** [comment] 2024-02-29 15:14
@zhenhuangMSFT, would you please take a look? Thanks.

**Comment by zhenhuangMSFT** [comment] 2024-03-01 02:51
Hey @emmanuelpineda, have you gone through this doc to find possible solutions? https://learn.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements#specify-which-office-versions-and-platforms-can-host-your-add-in

**Comment by Acibi** [comment] 2024-04-11 17:27
We have a similar issue. Seems like the validator is trying to find an Office applications that support **all** the sets which is impossible if we want to specify versions of requirements for specific applications.

Any update on the situation?

**Comment by emmanuelpineda** [comment] 2024-04-11 21:41
> Hey @emmanuelpineda, have you gone through this doc to find possible solutions? https://learn.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements#specify-which-office-versions-and-platforms-can-host-your-add-in

Hi @zhenhuangMSFT,
Yes, searching the Microsoft documentation I found that guide, but it didn't work in my case

**Comment by shanshanzheng-dev** [comment] 2024-04-19 09:38
@CelticCoder @Oleg-O @JuaneloJuanelo @ajacks-msft Hi, Could you please help take a look this issue? Thanks.

**Comment by shanshanzheng-dev** [comment] 2024-04-25 05:02
Hi @emmanuelpineda, Thanks for your report this issue, in order to solve this issue, could I know the validation is failing when uploading from M365 Admin Center or to partner center? Thanks again.

**Comment by Rick-Kirkham** [comment] 2024-04-26 21:03
@emmanuelpineda 

Your issue description suggests that you want to limit your add-in to being installed only on perpetual Office 2021+ on Windows. There isn’t any way to limit the installability of a web add-in to a particular combination of platform and Office version. This is by design. Web add-ins are designed to be cross platform.

Requirement Sets are not intended to limit installability to a particular combination of platform and Office version. They are used to limit Installability to platforms/version combos _that support the APIs that the add-in calls_. Anything that is supported on perpetual Office 2021 for Windows is also going to be supported on Microsoft 365 subscription Office, Office on the web, and on sufficiently recent versions of Office on Mac.

The validation error that you are seeing is expected behavior. No Office host application supports requirement sets for _other_ Office hosts. So, asking for ExcelApi, WordApi, and PowerPointApi requirement sets ensures that the add-in isn’t installable on any of them, because each host supports only one of them. But you can check for requirement set support at runtime with the [isSetSupported](https://learn.microsoft.com/javascript/api/office/office.requirementsetsupport) method. Here are the basic steps:

1. Remove the `<Requirements>` element from the manifest. Removing it will make the add-in installable on all three hosts, but in the next step you ensure that if your add-in is installed on an Office version and platform combination that can't support the APIs that it uses, your end users will only see a page that recommends that they upgrade their Office.
2. In the `Office.initialize()` or `Office.onReady()` methods (see [Initialize your Office add-in](https://learn.microsoft.com/office/dev/add-ins/develop/initialize-add-in)) add code similar to the following. 

```
Office.onReady(function(info) {
    let isSupported = false;
    switch info.host {
        case Office.HostType.Excel:
            isSupported = Office.context.requirements.isSetSupported("ExcelApi", "1.9");
            break;
       case Office.HostType.PowerPoint:
            isSupported = Office.context.requirements.isSetSupported("PowerPointApi", "1.1");
            break;
       case Office.HostType.Word:
            isSupported = Office.context.requirements.isSetSupported("WordApi", "1.4");
            break;
    }
    if (!isSupported) {
        // In here have code that hides your add-in's normal UI and replaces it with a message
        // that says something like "This add-in won't work on your version of Office. Please
        // upgrade to the latest version or to Microsoft 365."
    }
});
```

**Comment by Rick-Kirkham** [comment] 2024-04-30 21:53
@emmanuelpineda I'll close this now, but you can still make comments and we'll see them.

**Closed as completed by Rick-Kirkham** 2024-04-30 21:53 UTC
Labels: Needs: author feedback, Area: add-ins platform, Area: Centralized Deployment

**Comment by mscc-sascha** [comment] 2024-07-16 12:23
@Rick-Kirkham I also came across the same "issue". The reason why I wanted to use the `<Requirements>`-section is, that I want to limit the compatibility according the Office product version. I created a manifest.xml, including a TaskPane for **Word** and **PowerPoint**. 

We as a software vendor only want to support Office 2016 onwards and we want to publish the App to the marketplace. As Microsoft is validating the app package and tests it with all Office applications listed in the `<Requirements>`-Section ([1120.3 Functionality](https://learn.microsoft.com/en-us/legal/marketplace/certification-policies#11203-functionality)) - I wanted to limit the compatibility there. 

1. For the validation on marketplace - will it be sufficient to identify the host version in the code and show an "unsupported host message"?
2. Will MS support the `<Requirements>`-section to be used for this kind of limitation requirement in future?

Thanks!
