### ISSUE TITLE
Word: Addin is not auto-loading in Word Online with custom WOPI host

### ISSUE THREAD

**Issue by stowellt** [OfficeDev/office-js#422] opened 2019-03-13 15:17 UTC
## Expected Behavior
If an addin is inserted into a document, and `visibility=1` in taskpanes.xml in the docx file, the addin should auto install when the document is opened in Word Online.
![image](https://user-images.githubusercontent.com/19392630/54289810-6fbf3880-456f-11e9-843f-1659c8c2816d.png)

## Current Behavior
If the document is opened in OneDrive, the addin is auto loaded. If the document is opened in a Wopi Host, the addin never tries to load.

## Steps to Reproduce, or Live Example

* Additional details:
  1. Upload attached docx file to OneDrive, and edit with Word Online: [Addin Auto Load.docx](https://github.com/OfficeDev/office-js/files/2962090/Addin.Auto.Load.docx)
  2. You should see the Pickit addin (just used as an example) try to load and prompt for permission, like this:
![image](https://user-images.githubusercontent.com/19392630/54289172-536ecc00-456e-11e9-84c7-5f47cf12e792.png)
  3. Now try uploading and editing the document in Word Online connected to a custom Wopi host using the production discovery XML at  https://onenote.officeapps.live.com/hosting/discovery
  4. Result: The addin is never loaded, and there is no prompt to trust it
![image](https://user-images.githubusercontent.com/19392630/54290525-be210700-4570-11e9-8646-a709a94092bb.png)

  5. We are returning `AllowExternalMarketplace=true` in the CheckFileInfo Wopi response

## Context
We have created a custom addin and need it to auto load in users documents when editing on a custom Wopi host

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Word Online 16.0.11508.32650
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

## Useful logs

Screenshots

**Comment by weshi** [comment] 2019-11-15 04:44
@lliu113 is this related to your area?

**Comment by vinay-sattur** [comment] 2020-08-31 14:39
Is there any update on this. I am also facing the same issue. I am developing an excel add-in, it loads automatically when the file is opened fro OneDrive but not loading automatically when file is opened with WOPI.

**Comment by AndyHore** [comment] 2021-03-12 13:58
Looking for an update on this. This is a MAJOR problem and miss on functionality for WOPI that our customers require.

**Comment by lliu113** [comment] 2021-03-24 19:24
This looks like an issue with custom WOPI hosts, so looping in @keyur32 

@stowellt - have you tried the auto-open taskpane feature? You need to tag the document, and the pane should automatically open. Thinking it might suffice as a workaround. https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document

**Comment by AndyHore** [comment] 2021-03-24 19:34
Hi,

Yes, we've tried it, and No, it doesn't work!

Andy.

**Comment by keyur32** [comment] 2021-04-08 21:16
Hi there, this issue was investigated and is confirmed that this capability doesn't work for custom WOPI hosts, but only works for OneDrive enabled add-ins. We are investigating and this is in the backlog.

As a workaround, as the issue appears to be scoped to add-ins with add-in commands, you can try to have taskpane only add-ins (these were the 2013 style add-ins that do not contain a TaskPane overrides element). Those should work when embedded and auto load.

**Comment by AndyHore** [comment] 2021-04-09 00:08
Hi
Our add-in is a taskpane only and we've tried forcing it to auto-load and it didn't work. We can try again, but not sure this is going to work for us.

**Comment by keyur32** [comment] 2021-04-09 17:25
Interesting. We've seen some from others this does work.  

A few more questions:
- How/where is your add-in manifest located? Is it in the store or do you depend on deployment through centralized deployment?
- What do you get from the Insert > Store dialog. Do you have a screenshot of that?

If you have Excel, can you try embedding this: WA104379190 (XLMiner Analysis Toolpak) add-in. I also forget but you may need to also either Upper Case or Lower case "WA" in the asset id.

**Comment by AndyHore** [comment] 2021-04-09 17:35
It's in the App Store - search for "Qvidian" and you should find it. It works in Word and Excel.

Do you have a sample Excel file with that already embedded? If you send it to me, we can rule out how we've added it and just launch that from our WOPI interface to make sure it's working or not. Then I can compare with what we did to see what the difference may be.

**Comment by OanaCorinaFilip** [comment] 2021-04-20 15:05
Hello, 

I've experienced the same issue. It only happens on offline Word (Office 365 works fine). The Auto-Open feature works on documents created by the user opening the document, however, if a different user opens the document, the Auto-Open feature doesn't work. 

My suspicion is that it has to do with how this setting is saved in the OOXML of the desktop document (which is different from the OOXML of documents created in online Word). Also if you get the base64 encrypted OOXML of a document created online and you try to create a new document in desktop Word using it, the operation will fail, since the two have different formats. It works the other way around though.

Could you please look into the Auto-Open issue? It makes the feature unusable in offline Word and really goes against the idea of cross-platmform Add-Ins.

**Comment by mmoloney9966** [comment] 2021-08-30 14:20
We've used the OpenXML SDK to add the webextensions and taskpane parts to the DOCX.
All Word platforms (local desktop install, WebDAV integration, Office365.com) are able to open the modified DOCX but if issued to WOPI, Office Online just shows a "trouble opening document" message.  The browser console does show the following exception....

WordEditorDS.js:2444 Uncaught (in promise) TypeError: Cannot read property 'ic' of null
    at f.M_e (WordEditorDS.js:2444)
    at f.get value [as value] (WordEditorDS.js:2825)
    at cm.OYf (WordEditorDS.js:4687)
    at ue.LIh (WordEditorDS.js:1950)
    at WordEditorDS.box4.dll1.js:7299
    at new Promise (<anonymous>)
    at TG.oNl (WordEditorDS.box4.dll1.js:7299)
    at new TG (WordEditorDS.box4.dll1.js:7299)
    at l.Fna (WordEditorDS.box4.dll1.js:7307)
    at l.createInstance (WordEditorDS.js:686) 

Has anyone successfully modified DOCX with the webextensions and taskpane parts (per  https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document) and launched a WOPI integration Office Online edit session ??

Attached is the OpenXML modified docx file.
[Test Document.ModifiedWithOpenXML.docx](https://github.com/OfficeDev/office-js/files/7077385/Test.Document.ModifiedWithOpenXML.docx)

**Comment by keyur32** [comment] 2021-08-30 14:43
Hi there, 

Thanks for the additional details. I think we're missing an update to the automatically open a taskpane with a document article as we have a new attribute, you'll want to set storeType="wopicatalog"   (all lower case),   as specified in the file format reference article: https://docs.microsoft.com/en-us/openspecs/office_standards/ms-owexml/d4081e0b-5711-45de-b708-1dfa1b943ad1.

Can you try tagging the document with that attribute instead of using the 'omex' provider?

**Comment by keyur32** [comment] 2021-08-30 14:52
Note: for the documentation issue, filed https://github.com/OfficeDev/office-js-docs-pr/issues/2909 to update the article.

**Comment by mmoloney9966** [comment] 2021-08-30 15:18
WIll try this ASAP.
Quick question first, do the other attribute values (e.g.: app ID, store, etc...) need to be lowercase?

**Comment by keyur32** [comment] 2021-08-30 15:24
thanks. Good question.  

Here's an example:
![image](https://user-images.githubusercontent.com/3476087/131363076-2b0c6aee-15b8-4a54-b48c-fe5a9fb84732.png)

The asset id for your add-in should start an upper case "WA" string, I believe.  This is the code for you add-in you can get from app source (navigate to the listing on app source and you will see the asset id in the URL).

**Comment by mmoloney9966** [comment] 2021-08-30 15:50
Still failing with the error message in the iframe "Sorry, there was a problem.....".
Still seeing console error:

Uncaught (in promise) TypeError: Cannot read property 'jc' of null
    at f.mXe (WordEditorDS.js:2444)
    at f.get value [as value] (WordEditorDS.js:2826)
    at Hl.jUf (WordEditorDS.js:4691)
    at df.yCh (WordEditorDS.js:1950)
    at WordEditorDS.box4.dll1.js:7125
    at new Promise (<anonymous>)
    at UG.dFl (WordEditorDS.box4.dll1.js:7125)
    at new UG (WordEditorDS.box4.dll1.js:7125)
    at l.Sma (WordEditorDS.box4.dll1.js:7133)
    at l.createInstance (WordEditorDS.js:687)

Attached is the file that shows the change to "storeType="wopicatalog" but I've attached an image of the XML for the webextensions from the docx.  I used the https://github.com/OfficeDev/Office-OOXML-EmbedAddin as the model for the OpenXML SDK implementation.

We have not yet modified our WebAddIn manifest with the <TaskpaneId> yet as shown below.
MUST that be done as well or should WOPI/OfficeOnline at least be able to open the edit session and just not open/load the task pane?  Would not having our addin manifest modified cause this console exception?

<Action xsi:type="ShowTaskpane">
    <TaskpaneId>Office.AutoShowTaskpaneWithDocument</TaskpaneId>
    <SourceLocation resid="Contoso.Taskpane.Url" />
</Action>



![image](https://user-images.githubusercontent.com/87734942/131366443-c7025e90-28cf-44bf-8251-b88a804799e9.png)
[webaddin.docx](https://github.com/OfficeDev/office-js/files/7077881/webaddin.docx)

**Comment by keyur32** [comment] 2021-08-30 16:09
Ah, did you also follow these instructions here (sorry, thought I had posted that earlier in the thread but wasn't clear): 
https://wopi.readthedocs.io/en/latest/scenarios/hostinstalladdins.html

To enable this embedding you will need to register your staging and production environment domains first to allow add-ins to run in your host, and also send the same add-in ids as part of your post message as described in the FAQ of the link above.

Once you've done that, then, the add-ins should start a load.

**Comment by mmoloney9966** [comment] 2021-08-30 16:34
I did implement those changes as well for the additional form parameter "host_install_addins".  I even still have the fiddler script change in to ensure the host_install_addins is being sent.

I am unsure who to ask or how to confirm that our environment domains are "registered" for this purpose.  We have our addin officially in the Microsoft store.  We have our WOPI host domains whitelisted by WOPI Office Online servers.  Does that cover it OR is there another "registration" necessary and who do I contact for that?  CSPP claims if we have our addin up in the Microsoft store, we are good but I am suspicious there is still something outstanding but not sure who I can reach out to in order to be sure.  Do you have any contact info for someone I could reach out to?

As I mentioned, we have not yet modified our addin's manifest with the "TaskPanelId" change.  Is that also required for this to work?

**Comment by keyur32** [comment] 2021-08-30 16:40
I think you'll first need to do an additional registration to have add-ins run in be auto installed in your host. Please contact csppteam@microsoft.com to get the process started.

**Comment by mmoloney9966** [comment] 2021-08-30 17:13
I will try them again.   They didn't seem very aware when I asked this same question 3 weeks or longer ago.

Does our addin manifest need the "TaskPaneId" change as well for this to work?

**Comment by mmoloney9966** [comment] 2021-08-30 18:58
**Keyur,

Here is the response I got from CSPP.  Wanted to get your opinion on what they are stating before we go off and try to implement this trusted window/frame layer....**

WOPI hosts must now communicate to M365 applications that they are embedded in a trusted page. When the M365 app has validated that the add-in is running in a trusted page environment, the app will activate the add-in.

To perform the validation, you must make the following updates to your host:
1.	Include a query string: &sftc=1 to url of POST request sent to the M365 server url, to indicate to the Office app that the Hosts support frame trust post Message. 

IMPORTANT NOTE: sftc, is short for supportsFrameTrustedPostMessage)
2.	The host page needs to reply to the message App_IsFrameTrusted sent by the M365 app page with the message Host_IsFrameTrusted  specified in the WOPI documentation. 

IMPORTANT NOTE: The naming convention of post Message,  App_xxxx, is the message sent from the M365 app to the host; Host_xxxx is the message send from Host.

For more information, please see the WOPI help documentation.  @Sean Laberee should be able to assist you with any detailed questions beyond these resources.

Let us know when you have completed this update and we can implement your add-in to our whitelist.

**Comment by mmoloney9966** [comment] 2021-08-31 20:49
Keyur,

Not sure you saw this question in all our threads.

Does our addin manifest also need to be modified so that within the "Action" element for "ShowTaskpane", the "TaskpaneId" attribute is set to "Office.AutoShowTaskpaneWithDocument" ?

**Comment by mmoloney9966** [comment] 2022-06-16 18:30
Been a long time but I have what I hope is a simple question for you regarding this "hostInstallAddIns" mechanism....

Some of our customers use a central "admin-managed" location for webaddins instead of the Microsoft Store.
Will the "hostInstallAddIns" mechanism work for webaddin locations other than the Microsoft Store?

Thanks in advance for any insight/help.

**Comment by keyur32** [comment] 2022-12-19 17:46
Apologies for the delay, but to your question I think you are in the right hands with the CSPP support as they will have the latest. My understanding was this needs to be hosted in the store if you wish to use the host install mechanism as part of the WOPI protocol, as well as potentially being in the CSPP (plus) program.

**Comment by keyur32** [comment] 2022-12-19 17:46
Closing above out but please reopen / log a new issue if you have a WOPI question that is still not resolved. thanks.

**Closed as completed by keyur32** 2022-12-19 17:46 UTC
Labels: Type: product bug, Area: add-ins platform, Status: in backlog
