### ISSUE TITLE
Excel table creation pushes rows underneath by one cell

### ISSUE THREAD

**Issue by erharvey** [OfficeDev/office-js#1197] opened 2020-06-03 12:09 UTC
When a cell is referenced inside the range where a table will be created, the command to create a table pushes the cells under it by 1 row.

var table = sheet.tables.add(headerRange, true);

The behavior cannot be reproduced if no formula references the area of the table.
You can see in the picture below that the blue area from row 12 to 16 was pushed. (The table was created many times thus it's been pushed by more than 1 cell)

The cell J4 has a formula on column A (which is part of the table)

![image](https://user-images.githubusercontent.com/17800696/83634443-9270af00-a570-11ea-8cee-8a06d2da06e3.png)

## Expected Behavior
Cells under the table should not be affected by creating a table when the hasHeaders attribute is set to true

## Steps to Reproduce, or Live Example

1- Run the following code inside and Excel.Run statement multiple times. It will pushe the cell by one every time.
``
   var sheet = ctx.workbook.worksheets.getActiveWorksheet();
 var entitiesTable = sheet.tables.getItem("TestTable");
 var rng = entitiesTable.convertToRange();
 rng.clear();

 var selectedRowIndex = 0;
 var selectedColumnIndex = 0;

 var headerRange = sheet.getRangeByIndexes(selectedRowIndex, selectedColumnIndex, 1, 3);
        
 var table = sheet.tables.add(headerRange, true);
 table.name = "TestTable";
``

## Your Environment
Build : 2004
Windows 10

**Comment by MandytMSFT** [comment] 2020-06-04 11:05
@erharvey  thanks for the reporting. I can repro and BUG 4207829 was opened for internal track

**Comment by lumine2008** [comment] 2021-03-17 10:34
I have checked the bug status, it seems UI have the same behavior. so it looks a by design issue

**Comment by lumine2008** [comment] 2021-03-23 13:24
If this is important for your add-in, feel free to submit this as a feature request to our Uservoice - https://officespdev.uservoice.com/

Closing the issue as "by design", please reactivate if you have any more questions/feedback.

**Closed as completed by lumine2008** 2021-03-23 13:24 UTC
Labels: Area: Excel, Resolution: by design
