### ISSUE TITLE
Uncaught (in promise) RichApi.Error: ControlIdNotFound

### ISSUE THREAD

**Issue by osvath58** [OfficeDev/office-js#2348] opened 2022-01-06 15:05 UTC
Getting multiple occurrences of the following error in Office.js Excel Add-in:

Uncaught (in promise) RichApi.Error: ControlIdNotFound
at new n in (excel-win31-16.01.js:26)
at r.i.processRequestExcecutorResponseMessage (excel-win31-16.01.js:26)
at excel-win32-16.01.js:26

The add-in works fine.

**Comment by jipinshi** [comment] 2022-01-10 05:15
@osvath58, can you help add more repro info and it would be great if there is a video attached.  And how do you see the error? I see you mentioned that the addin itself can work smooth. Does other addin like script lab also can cause the same error?

**Comment by chiz-ms** [comment] 2022-01-10 06:06
This issue has been tracked as ADO#5708643 in our backlog.

**Comment by davidchesnut** [comment] 2022-01-14 20:40
Hi @osvath58 

Can you trace this error to any section of your code and share what it might be doing? Are you trying to create a contextual tab, run a command from a button, respond to an event, or anything that would involve a control id to identify something (button, menu etc...)?

Thanks!

**Comment by ryanmccall101** [comment] 2022-02-19 14:54
Hi All, I am having the same issue.  I am running a complicated program using Excel Javascript API - it works fine on desktop but when I use the excel online I got 'Error: GeneralException: An internal error has occurred.' - The error was intermittent though seemed to be around the section of code that develops pivot tables.  I removed the .catch error's to see what would happen and got the same message as the topic.  Probably wont help but when i looked at running pivot tables on excel online using 'automate' to see what was going on, I noticed a new window where excel online is suggesting pivot table layouts.  This didnt happen previously so caught my eye.  Happy to provide more information if it helps - i am at wits end now..

**Comment by ryanmccall101** [comment] 2022-02-19 15:00
[Temp File - Screen Shots Console Errors and Excel Online Error Codes.docx](https://github.com/OfficeDev/office-js/files/8102392/Temp.File.-.Screen.Shots.Console.Errors.and.Excel.Online.Error.Codes.docx)

Hi again, i have attached a file with screen shots showing the adhoc nature of the Error: GeneralException, and also at the bottom of the file is some screen shots of the excel online error codes.

**Comment by guliums** [comment] 2022-02-21 09:34
Hi @ryanmccall101 , thanks very much for reporting this. This issue has been tracked as ADO#5750426 in our backlog. I will let you know when we have update. Thanks.

**Comment by ryanmccall101** [comment] 2022-02-21 10:02
Thanks, if you need more info I am more than happy to help - also if you want to meet on teams I would be happy to demonstrate.

Regards Ryan McCall +447428089960

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davidchesnut** [comment] 2022-02-22 20:53
Hi @ryanmccall101,

I spotted a very similar issue to yours at https://stackoverflow.com/questions/47044810/generalexception-in-excel-add-in-with-excel-online. Do you think any of the suggested solutions there apply to your scenario?

**Comment by ryanmccall101** [comment] 2022-02-23 08:30
Hi David,

 

I have actually reviewed that problem previously but it did not help.

 

I checked the version number in the manifest – see below, trying to change xml version="1.0" to version 1.0.0.0 results in error, so I presume OP was talking about the second mention of version per the following:

 



 

I also checked and confirm I am not mixing the Office 2013 paradigm ("getSelectedDataAsync") with the Office 2016+ paradigm ("Excel.run(batch)").

 

I note I have had issues with pivot tables previously.  Perhaps I barking up the wrong tree but if it helps here is some further information:

 

This is my code block for calling pivotableDev within the parent function.. I used to run the pivot table code directly in the parent function but broke it out as follows to see if that would fix the issue ( to no avail..).

 

        await context.sync().then(function () {

            context.application.suspendScreenUpdatingUntilNextSync();

            return Promise.resolve()

                .then(function () {

                    console.log("run pivotTableDev2 for totalEarnedHours_1RFA");

                    context.application.suspendScreenUpdatingUntilNextSync();

                    return pivotTableDev2("detailedReg_FTC", "EarnedHrsPivot", "earnedHours_PT", "CostCode", "TotalEarnedHrsPerItem", "TotalRemainingHrsPerItem");

                })

                .then(context.sync);

        });

 

I have separate pivotTableDev functions depending on the number of data hierarchies: 

 

 

async function pivotTableDev3(tabToAnalyze, PT_S, ptName, rowHier, dataHier0, dataHier1, dataHier2 ) {

 

    await Excel.run(async (context) => {

        context.application.suspendScreenUpdatingUntilNextSync();

        context.workbook.worksheets.getItemOrNullObject(PT_S).delete();

        context.workbook.worksheets.add(PT_S);

        //#region Summ the TotalBudgetHrsPerItem per CC in new PT - xyzPivot then create table - costcodeHrsSummary

        // Create a PivotTable named "xyz_PT" on a worksheet called "xyz_Pivot" at cell A2

        //var tabToAnalyze = context.workbook.tables.getItemOrNullObject("tabToAnalyze");

        var rangeToPlacePivot = context.workbook.worksheets.getItemOrNullObject(PT_S).getRange("A2");

        context.workbook.worksheets.getItemOrNullObject(PT_S).pivotTables.add(

            ptName, tabToAnalyze, rangeToPlacePivot);

        var pivotTable = context.workbook.pivotTables.getItemOrNullObject(ptName);

 

        pivotTable.rowHierarchies.add(pivotTable.hierarchies.getItemOrNullObject(rowHier));

        pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItemOrNullObject(dataHier0));

        pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItemOrNullObject(dataHier1));

        pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItemOrNullObject(dataHier2));

 

        pivotTable.layout.layoutType = "Outline";

        pivotTable.dataHierarchies.load("no-properties-needed");

        await context.sync();

        context.application.suspendScreenUpdatingUntilNextSync();

 

        pivotTable.dataHierarchies.items[0].summarizeBy = Excel.AggregationFunction.sum;

        pivotTable.dataHierarchies.items[1].summarizeBy = Excel.AggregationFunction.sum;

        pivotTable.dataHierarchies.items[2].summarizeBy = Excel.AggregationFunction.sum;

 

        pivotTable.refresh();

 

        await context.sync();

 

    })

        .catch(function (error) {

            console.log("Error: " + error);

            document.getElementById("quick-setup-error").style.display = "inline";

            document.getElementById("quick-setup-error").innerHTML = "Error: " + error + ". Function: pivotTable3. Contact RNMProfessionals.com for assistance.";

            document.getElementById("quick-setup-error").style.color = "red";

            if (error instanceof OfficeExtension.Error) {

                console.log("Debug info: " + JSON.stringify(error.debugInfo));

                document.getElementById("quick-setup-error").style.display = "inline";

                document.getElementById("quick-setup-error").innerHTML = "Debug info: " + JSON.stringify(error.debugInfo) + ". Function: pivotTable3. Contact RNMProfessionals.com for assistance.";

                document.getElementById("quick-setup-error").style.color = "red";

            }

        });

}

 

 

The other things that I have tried is to remove hyperlinks that are inserted by the program – I think there is a connection between hyperlinks and general exception error if the linked sheet is deleted by the program while the hyperlink is active.

 

I also reverted to a previously bug free version of my .js from September last year and this resulted in the same error’s.  

 

Regards

Ryan McCall

**Comment by ryanmccall101** [comment] 2022-02-23 08:43
Hi, one other thing I forgot to mention, some pivot tables revert to ‘count’ rather than ‘sum’ – hence the reason I have added the following:

 

pivotTable.dataHierarchies.items[0].summarizeBy = Excel.AggregationFunction.sum;

        pivotTable.dataHierarchies.items[1].summarizeBy = Excel.AggregationFunction.sum;

        pivotTable.dataHierarchies.items[2].summarizeBy = Excel.AggregationFunction.sum;

 

 

I have not been able to determine why some pivot table revert to ‘count’ and some do not at this stage, but thought it prudent to stipulate the sum aggregate, in spite of the additional context.sync and performance degradation this poses..

 

Regards

Ryan McCall

From: ***@***.*** ***@***.***> 
Sent: 23 February 2022 08:30
To: 'OfficeDev/office-js' ***@***.***>; 'OfficeDev/office-js' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [OfficeDev/office-js] Uncaught (in promise) RichApi.Error: ControlIdNotFound (Issue #2348)

 

Hi David,

 

I have actually reviewed that problem previously but it did not help.

 

I checked the version number in the manifest – see below, trying to change xml version="1.0" to version 1.0.0.0 results in error, so I presume OP was talking about the second mention of version per the following:

 



 

I also checked and confirm I am not mixing the Office 2013 paradigm ("getSelectedDataAsync") with the Office 2016+ paradigm ("Excel.run(batch)").

 

I note I have had issues with pivot tables previously.  Perhaps I barking up the wrong tree but if it helps here is some further information:

 

This is my code block for calling pivotableDev within the parent function.. I used to run the pivot table code directly in the parent function but broke it out as follows to see if that would fix the issue ( to no avail..).

 

        await context.sync().then(function () {

            context.application.suspendScreenUpdatingUntilNextSync();

            return Promise.resolve()

                .then(function () {

                    console.log("run pivotTableDev2 for totalEarnedHours_1RFA");

                    context.application.suspendScreenUpdatingUntilNextSync();

                    return pivotTableDev2("detailedReg_FTC", "EarnedHrsPivot", "earnedHours_PT", "CostCode", "TotalEarnedHrsPerItem", "TotalRemainingHrsPerItem");

                })

                .then(context.sync);

        });

 

I have separate pivotTableDev functions depending on the number of data hierarchies: 

 

 

async function pivotTableDev3(tabToAnalyze, PT_S, ptName, rowHier, dataHier0, dataHier1, dataHier2 ) {

 

    await Excel.run(async (context) => {

        context.application.suspendScreenUpdatingUntilNextSync();

        context.workbook.worksheets.getItemOrNullObject(PT_S).delete();

        context.workbook.worksheets.add(PT_S);

        //#region Summ the TotalBudgetHrsPerItem per CC in new PT - xyzPivot then create table - costcodeHrsSummary

        // Create a PivotTable named "xyz_PT" on a worksheet called "xyz_Pivot" at cell A2

        //var tabToAnalyze = context.workbook.tables.getItemOrNullObject("tabToAnalyze");

        var rangeToPlacePivot = context.workbook.worksheets.getItemOrNullObject(PT_S).getRange("A2");

        context.workbook.worksheets.getItemOrNullObject(PT_S).pivotTables.add(

            ptName, tabToAnalyze, rangeToPlacePivot);

        var pivotTable = context.workbook.pivotTables.getItemOrNullObject(ptName);

 

        pivotTable.rowHierarchies.add(pivotTable.hierarchies.getItemOrNullObject(rowHier));

        pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItemOrNullObject(dataHier0));

        pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItemOrNullObject(dataHier1));

        pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItemOrNullObject(dataHier2));

 

        pivotTable.layout.layoutType = "Outline";

        pivotTable.dataHierarchies.load("no-properties-needed");

        await context.sync();

        context.application.suspendScreenUpdatingUntilNextSync();

 

        pivotTable.dataHierarchies.items[0].summarizeBy = Excel.AggregationFunction.sum;

        pivotTable.dataHierarchies.items[1].summarizeBy = Excel.AggregationFunction.sum;

        pivotTable.dataHierarchies.items[2].summarizeBy = Excel.AggregationFunction.sum;

 

        pivotTable.refresh();

 

        await context.sync();

 

    })

        .catch(function (error) {

            console.log("Error: " + error);

            document.getElementById("quick-setup-error").style.display = "inline";

            document.getElementById("quick-setup-error").innerHTML = "Error: " + error + ". Function: pivotTable3. Contact RNMProfessionals.com for assistance.";

            document.getElementById("quick-setup-error").style.color = "red";

            if (error instanceof OfficeExtension.Error) {

                console.log("Debug info: " + JSON.stringify(error.debugInfo));

                document.getElementById("quick-setup-error").style.display = "inline";

                document.getElementById("quick-setup-error").innerHTML = "Debug info: " + JSON.stringify(error.debugInfo) + ". Function: pivotTable3. Contact RNMProfessionals.com for assistance.";

                document.getElementById("quick-setup-error").style.color = "red";

            }

        });

}

 

 

The other things that I have tried is to remove hyperlinks that are inserted by the program – I think there is a connection between hyperlinks and general exception error if the linked sheet is deleted by the program while the hyperlink is active.

 

I also reverted to a previously bug free version of my .js from September last year and this resulted in the same error’s.  

 

Regards

Ryan McCall

**Comment by guliums** [comment] 2022-02-23 10:57
Hi @ryanmccall101 , thanks very much for the details. We have found the root cause that causing the Error Id in your attached file [Temp File - Screen Shots Console Errors and Excel Online Error Codes.docx](https://github.com/OfficeDev/office-js/files/8102392/Temp.File.-.Screen.Shots.Console.Errors.and.Excel.Online.Error.Codes.docx) and working on the fix, but it need some time to get deployed to production. I will let you know when the fix get deployed. Really sorry for the inconvenience.

**Comment by ryanmccall101** [comment] 2022-02-23 11:03
No problem, actually it is a big relief to hear you have found root cause so thanks for helping.  Just one more query if I may, I was looking to apply to put the App on AppSource in the near future though part of the approval process (I understand) require’s web version operability.  Is it possible to get an exemption on this requirement while the fix is pushed through?

**Comment by guliums** [comment] 2022-02-23 11:35
@ryanmccall101 what time do you plan to publish your add-in to appsource? I'm sorry that this issue blocking your web version add-in. We will treat this issue as high priority and I was hoping the fix could be deployed before the AppSource process.

**Comment by ryanmccall101** [comment] 2022-02-23 11:41
Hi, I have finished all functional requirements and performance improvements and am now focusing on testing.  I would’ve liked to start the application process in 4 to 8 weeks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guliums** [comment] 2022-03-03 05:12
Hi @ryanmccall101 , the issue has been fixed and deployed. Please let me know if you still hit the issue. Thanks!

**Comment by ryanmccall101** [comment] 2022-03-08 09:00
Hi, thanks very much for your help – I have checked and all looks good from my end.

 

Thumbs up.

 

Regards

Ryan McCall

**Comment by RuizhiSunMS** [comment] 2022-03-09 12:45
Close the issue since it has been fixed and verified by the reporter.

**Closed as completed by RuizhiSunMS** 2022-03-09 12:45 UTC
Labels: Needs: attention :wave:, Area: Excel, Type: product bug, Needs: author feedback

**Comment by osvath58** [comment] 2022-06-15 11:03
@RuizhiSunMS  This issues was not resolved by the reporter. It is fixed for @ryanmccall101, who commented on that he was also encountering the problem, but he is not the reporter of the issues, I am.

**Comment by davidchesnut** [comment] 2022-06-15 14:34
Hi @osvath58, sorry about that. Can you provide more info related to the original questions? It would help to have more specific reproduceable steps. Like does the error occur when the add-in loads, or when some other action takes place? If you can debug and find the line of code that causes the error that would be super helpful. If you have a video showing what happens that would help as well.

@guliums can you help on the first issue reported here?

Thanks,
David

**Comment by guliums** [comment] 2022-06-16 06:53
Hi @osvath58 do you still hit the issue? If yes could you provide more details using the template, thanks for your support!


# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.
