### ISSUE TITLE
Outlook Exchange Online: When Plan to GA: Enable SSO in an Office Add-in using nested app authentication (preview)

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#4595] opened 2024-06-24 08:52 UTC
we notice [Enable SSO in an Office Add-in using nested app authentication (preview)](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in) is still in preview. but exchange online is will be turned off by default for all Exchange Online tenants in October 2024. https://devblogs.microsoft.com/microsoft365dev/new-nested-app-authentication-for-office-add-ins-legacy-exchange-tokens-off-by-default-in-october-2024/?ocid=microsoft365dev_eml_tnp_autoid106_image

So, what's the plan for this issue?

**Comment by ElizabethSamuel-MSFT** [comment] 2024-06-24 18:20
@hello-chenchen Thanks for asking about this. We're closing this issue as a duplicate of your other issue https://github.com/OfficeDev/office-js-docs-pr/issues/4633.

If you're facing any further issues, please do open another one.

Thanks.

**Comment by davidchesnut** [comment] 2024-06-24 21:18
Hi @hello-chenchen, we plan to get NAA to GA very soon now. We'll also provide more information as we go on either the [Office Add-ins community](https://aka.ms/officeaddinscommunitycall) call or the [M365 developer blog](https://devblogs.microsoft.com/microsoft365dev). Also we will keep updating the sample with any changes that come along. Please take this time to try out NAA and let us know if you spot any issues. You're in the right location to let us know about any issues, or questions you have! 

Thanks!
David

**Comment by hello-chenchen** [comment] 2024-06-26 02:23
hi @davidchesnut , thank you so much. By the way, can you please take a look and give us some suggestions?

- Does all Office365 users affected? I’m not sure, but as I know Exchange Online is the only Outlook backend service for Office365 users, right? If so, I think this change will affect all office365 users.

- We notice: Exchange 2019 and other on-premises versions of Exchange won’t block legacy Exchange [user identity tokens](https://learn.microsoft.com/office/dev/add-ins/outlook/authentication#exchange-user-identity-token) and [callback tokens](https://learn.microsoft.com/office/dev/add-ins/outlook/authentication#callback-tokens). So, This is how I understand it, please correct me if there is any mistake: For these versions without blocks, we still have only the option is to keep using [user identity tokens](https://learn.microsoft.com/office/dev/add-ins/outlook/authentication#exchange-user-identity-token) and [callback tokens](https://learn.microsoft.com/office/dev/add-ins/outlook/authentication#callback-tokens), right?

**Comment by davidchesnut** [comment] 2024-08-26 21:04
Hi @hello-chenchen,

The updated timeline for Exchange token shut down is here: https://devblogs.microsoft.com/microsoft365dev/updates-on-deprecating-legacy-exchange-online-tokens-for-outlook-add-ins/

You are correct. this does not affect on-premise Exchange tokens. It does affect anyone using online Exchange tokens (issued online).

Hope this helps,
David

**Closed as completed by davidchesnut** 2024-08-26 21:04 UTC
Labels: Resolution: duplicate
