### ISSUE TITLE
auth.getAccessToken not working in dialog

### ISSUE THREAD

**Issue by Tjerkdb** [OfficeDev/office-js#1609] opened 2021-01-22 20:09 UTC
I am developing an power point office add-in where i use a dialog. I would like to generate a bootstraptoken using the office.auth.getaccestoken but it does not seem to work inside the dialog while it does work in the taskpane. Is this by design or is this a bug?

## Expected Behavior
when I call office.auth.getAccessToken I expect a bootstrap token

## Current Behavior
The code breaks without errors.

## Steps to Reproduce, or Live Example
I use the following code to generate a bootstraptoken in the taskpane while the same code does not work in a dialog
```
    let bootstrapToken = await OfficeRuntime.auth.getAccessToken({
      allowSignInPrompt: true,
      allowConsentPrompt: true,
      forMSGraphAccess: true
    });
```

## Your Environment
* Platform: Mac
* Host: Powerpoint 
* Office version number: 16.46
* Operating System: Mac os Big sur

## Useful logs
No errors are given

**Comment by lliu113** [comment] 2021-01-28 22:24
@Tjerkdb thanks for reporting this! This is by design, we have a [reduced API surface](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices#rules-and-gotchas) inside the dialog for security reasons. 

To do auth, either pass the auth token to your dialog via the [messaging API](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#use-messagechild-from-the-host-page) or see here for the [prescribed way to auth inside the dialog ](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api)

Closing as by design, please reactivate if you have any questions.

**Closed as completed by lliu113** 2021-01-28 22:24 UTC
Labels: Area: authentication, Resolution: by design

**Comment by celluj34** [comment] 2023-06-13 16:23
This is an extremely painful limitation. Because of the way I have designed the api access code in my add-in, and due to #2140 and #1868, I have to spaghetti-code how I'm loading the access token.

You say it's by design but IMO the design is reduced too far.
