### ISSUE TITLE
RichApi.Error when loading office.js script: The argument is invalid or missing or has an incorrect format

### ISSUE THREAD

**Issue by christian513** [OfficeDev/office-js#1561] opened 2020-12-23 10:23 UTC
Hi,
we load the Office.js with this script in our html app:

<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>

Every time the html file is loaded the following error occurs on the console. The error even occurs if we do not call any Office.js API in our code.

RichApi.Error: The argument is invalid or missing or has an incorrect format.

## Expected Behavior
No error when loading office.js

## Steps to Reproduce, or Live Example
You can reproduce it by opening any add-in in Excel. For example open the ScriptLab task pane. You see the same error on the console.

## Your Environment
* Platform [PC desktop, Mac]: ______
* Host [Excel]: ______

**Comment by lindalu-MSFT** [comment] 2020-12-23 17:56
Hi @sumurthy, I think this is a ScriptLab issue. Can you triage and reassign if necessary? Thanks, lindalu

**Comment by christian513** [comment] 2020-12-23 18:46
Hi, it is not an issue of ScriptLab. It occurs with every add-in.

**Comment by MandytMSFT** [comment] 2020-12-24 03:49
@christian513 Thanks for reaching us. Can I know which platform(Excel Desktop, Excel Online, Mac or iOS) you are seeing this error ? And what's the excel version ?  It's definitely not right to have this error, if you can provide a repro video, that will be helpful for us to better understand your scenario.

**Comment by christian513** [comment] 2021-01-12 07:32
Hi, as I wrote in the "Reproduction steps": you can reproduce it with every add-in, so use the ScriptLab add-in for example. Click on "Code" ribbon button and check the console. See attached screen recording.

https://user-images.githubusercontent.com/3823739/104283278-9a061800-54b0-11eb-838c-2c1c104d8694.mp4

This issue occurs with all add-ins. So it is not an issue of the ScriptLab.
The issue is not severe as the add-in still works. But it occurs every single time when any add-in loads the office.js script.

It does not depend on the Excel version. I tried it with several channels. Currently I'm using Semi-Annual Enterprise Channel Version 2002.

**Comment by swiftinitdotcom** [comment] 2021-05-11 04:13
We are having exact same issue Rich api error-
InvalidArgument: The argument is invalid or missing or has an incorrect format. Its excel addin with data coming from json.

**Comment by amanraihot** [comment] 2021-06-30 12:30
any updates on this one @lindalu-MSFT

**Comment by lindalu-MSFT** [comment] 2021-06-30 16:44
@lumine2008 @MandytMSFT Hi, the Bot closed this due to inactivity but it appears the customers are still interested in follow up. Can you please triage again and find the right SME to address?

**Comment by sdudnic** [comment] 2022-10-29 19:51
The issue occured when a ScriptLab code does the `await context.sync()` 
![image](https://user-images.githubusercontent.com/35489219/198850270-c60dc3c4-62f2-4f5a-b783-afd9e1d48c60.png)

![image](https://user-images.githubusercontent.com/35489219/198850329-7a9edb85-f4b7-4709-bbb4-95d673bdffaf.png)

![image](https://user-images.githubusercontent.com/35489219/198853460-e7dab033-ff39-4c3c-8ad0-7a2e54d9d5d6.png)

```
n {name: "RichApi.Error", code: "InvalidArgument", traceMessages: Array[0], innerError: null, debugInfo: Object…}
name: "RichApi.Error"
code: "InvalidArgument"
traceMessages: Array[0]
innerError: null
debugInfo: Object
code: "InvalidArgument"
message: "The argument is invalid or missing or has an incorrect format."
toString: function toString()
errorLocation: "Worksheet.getRange"
statement: "var range = worksheet.getRange(...);"
surroundingStatements: Array[9]
0: "var workbook = context.workbook;"
1: "var worksheets = workbook.worksheets;"
2: "var worksheet = worksheets.getItem(...) /* originally getItemOrNullObject(...) */;"
3: "// >>>>>"
4: "var range = worksheet.getRange(...);"
5: "// <<<<<"
6: "// Instantiate {range}"
7: "range.load(["text","values"]);"
8: "var itemOrNullObject = worksheets.getItemOrNullObject(...);"
```

! I would note, that the issue may come from a incorrectly named range. In my case insteaf of `K3:O3` it was named `K3:03`.

As the difference between **zero** `0` and **letter** `O` is not visible ar fist glance, I was long time confised about the error.

**Comment by dorkster100** [comment] 2022-11-10 00:10
For me it was the incorrectly named range issue, would be nice to have a proper error for this case, thank you

**Comment by donlvMSFT** [comment] 2022-11-16 11:09
Thanks for the discussion, I'd like to close this thread as the issue already closed.

**Closed as completed by donlvMSFT** 2022-11-16 11:09 UTC
Labels: Needs: attention :wave:, Area: Excel

**Comment by sdudnic** [comment] 2022-11-21 16:07
> Thanks for the discussion, I'd like to close this thread as the issue already closed.

@donlvMSFT please follow the thread logic, 

> This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

The issue was not closed because resolved, but by inactivity. So, a comment reappeared, saysing that the problem is still there. And you close it because it was closed for inactivity? :)

**Comment by AnilR-hexaware** [comment] 2023-08-18 17:52
Hi there, am getting error is console  

Description: RichApi.Error: The argument is invalid or missing or has an incorrect format. at new n (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:25:259625) at i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:25:324071) at https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:25:322134
code: "InvalidArgument"
data: undefined
debugInfo:
code: "InvalidArgument"
errorLocation: "Worksheet.getRange"
fullStatements: Array(1)
0: "Please enable config.extendedErrorLogging to see full statements."
length: 1
lastIndex: (...)
lastItem: (...)
[[Prototype]]: Array(0)
message: "The argument is invalid or missing or has an incorrect format."
statement: "var range1 = worksheet.getRange(...);"
surroundingStatements: Array(11)
0: "..."
1: "var worksheets = workbook.worksheets;"
2: "var worksheet = worksheets.getItem(...);"
3: "var range = worksheet.getRange(...);"
4: "// Instantiate {range}"
5: "range.load([\"values\",\"format\"]);"
6: "// >>>>>"
7: "var range1 = worksheet.getRange(...);"
8: "// <<<<<"
9: "// Instantiate {range1}"
10: "range1.load([\"values\"]);"
length: 11
lastIndex: (...)
lastItem: (...)
[[Prototype]]: Array(0)
toString: ƒ ()
[[Prototype]]: Object
httpStatusCode: 400
innerError: null
name: "RichApi.Error"
traceMessages: []
message: "The argument is invalid or missing or has an incorrect format."
stack: "RichApi.Error: The argument is invalid or missing or has an incorrect format.\n at new n ([https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:25:259625)\n](https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:25:259625)/n) at i.processRequestExecutorResponseMessage ([https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:25:324071)\n](https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:25:324071)/n) at [https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:25:322134"](https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:25:322134%22)
[[Prototype]]: Error


please help me on this tried lot of conditions but still i can see the error
