### ISSUE TITLE
Office Add-in MS Project Task pane : Permission denied

### ISSUE THREAD

**Issue by ragavanrajan** [OfficeDev/office-js#631] opened 2019-07-18 20:52 UTC
After a recent update yesterday (18-Jul-19) . I am getting permission denied for any Office JS method when I try to execute.
## Expected Behavior

Changing the selected task to desired text as per the below function. 

## Current Behavior

In my manifest I have checked the permission is set to: 
` <Permissions>ReadWriteDocument</Permissions>`
## Steps to Reproduce, or Live Example

Below is the sample method which use to run fine 

* Additional details:
  1. Serving via HTTPS prortocol 
## Context
```
async run() {


  var taskGuid;

// Get the GUID of the selected task
    Office.context.document.**getSelectedTaskAsync**(
        function (result) {
          if (result.status === Office.AsyncResultStatus.Succeeded) {
            taskGuid = result.value;

            // Set the specified fields for the selected task.
            var targetFields = [Office.ProjectTaskFields.Name, Office.ProjectTaskFields.Notes];
            var fieldValues = ['Tidy International Task', 'Notes for the task from Tidy.'];

            // Set the field value. If the call is successful, set the next field.
            for (var i = 0; i < targetFields.length; i++) {
              Office.context.document.setTaskFieldAsync(
                  taskGuid,
                  targetFields[i],
                  fieldValues[i],
                  function (result) {
                    if (result.status === Office.AsyncResultStatus.Succeeded) {
                      i++;
                    }
                    else {
                      var err = result.error;
                      console.log(err.name + ' ' + err.code + ' ' + err.message);
                    }
                  }
              );
            }
          } else {
            var err = result.error;
            console.log(err.name + ' ' + err.code + ' ' + err.message);
          }
        }
    );

  }
```

## Your Environment

Windows 10 64-bit
**MS Project for Office 365 MSO (16.0.11328.20362) 64-bit**
Word for Office 365 MSO (16.0.11328.20362) 64-bit
Actually for all office product the above version is applicable.
IE 11 BROWSER 

## Useful logs

- [ ] Console errors
- [x ] Screenshots
- [ ] Test file (if only happens on a particular file)
![image](https://user-images.githubusercontent.com/6369107/61491022-60129d80-aa02-11e9-8ffd-ab0e1cbb0ce6.png)

More detailed screenshot: Even though write privilleges is declared, function is falling under rejection 

![image](https://user-images.githubusercontent.com/6369107/61493068-d7e2c700-aa06-11e9-9c6c-65764f21f362.png)

Kindly help to fix this problem ASAP. Thanks

**Comment by ragavanrajan** [comment] 2019-07-18 21:23
Detailed screen shot of the error

**Comment by cyrelk** [comment] 2019-07-19 05:55
I confirm , this was the bug I closed before too soon.
In fact it's now impossible to run add-ins on Windows 7. We must migrate all our machines from Windows 7 to Windows 10 1903, at the very least, to get the applications working again. Reinstalling Office, latest version, on windows 7 machines does not correct the problem.
Apparently the move from Internet Explorer to Edge seems to be the culprit.

**Comment by ragavanrajan** [comment] 2019-07-19 06:34
So does it mean. Add-in will only work in edge without any issues? I understand browsers will be decided based on the office version on Windows 10. If that is the case how do I force add in to use edge browser?

**Comment by cyrelk** [comment] 2019-07-19 06:56
On Windows 10 1903 I see the add-ins using Edge on 1809 they use IE. Apparently this is completly automatic. Maybe the Office developers could answer.
In fact it was by trying to debug the application on my machine that I remarked I could not used the F12 IE debugger anymore but I must use the Edge DevTools. I didn't know about the switch before that.

**Comment by niteshgolchha85** [comment] 2019-07-19 20:32
Can you confirm if you are using the latest version of office.js?

**Comment by ragavanrajan** [comment] 2019-07-20 03:57
@niteshgolchha85  yes. Using the following CDN. `<script src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js" type="text/javascript"></script> `. I hope there is no update after this!!

**Comment by ragavanrajan** [comment] 2019-07-22 02:04
Even The Addins written in VSTO for MS Project is also stopped working. Producing errors on existing functionality. 
**Affecting all production users.** . Below is the MSO version for better clarity. 

![image](https://user-images.githubusercontent.com/6369107/61601427-5babe600-ac89-11e9-8673-8391fb934649.png)
![image](https://user-images.githubusercontent.com/6369107/61601433-61a1c700-ac89-11e9-8045-735615c57c59.png)

**Comment by cyrelk** [comment] 2019-07-22 07:37
Works again for me on the latest revision of the GIT version of OfficeJS. Including on Windows 7 machines.

**Comment by ragavanrajan** [comment] 2019-07-22 07:51
@cyrelk  Could you please share the CDN you are using.

**Comment by cyrelk** [comment] 2019-07-22 08:08
I'm using the GIT version , latest revision.

**Comment by ragavanrajan** [comment] 2019-07-22 08:18
@cyrelk  sorry little confused. would you mind sharing link or reference pls. I have tried the       `<script src="https://unpkg.com/@microsoft/office-js@1.1.2-alpha.0/dist/office.js"></script>` still ending up with error. What is the one you are using. Can you please be specific.

**Comment by cyrelk** [comment] 2019-07-22 08:37
That's the one you get from this very site: https://github.com/OfficeDev/office-js.git
The little green button in the upper right of code section :)

**Comment by niteshgolchha85** [comment] 2019-07-22 18:15
@ragavanrajan referencing the CDN is the best way to get the latest office.js. You can try grabbing it from the location that @cyrelk mentioned above to see if that works or check if there are no other references to office.js in your code.

**Comment by ragavanrajan** [comment] 2019-07-22 23:14
@niteshgolchha85 :  I have checked completely every where in my application. Office JS is not referenced any where else. Using the latest CDN `<script src="https://unpkg.com/@microsoft/office-js@1.1.29/dist/office.js"></script>`  - I am still getting the permission denied error. Even the samples are also having same problem. Could you please provide any alternative. Thanks

**Comment by htryggva** [comment] 2019-07-23 11:20
We are also seeing this problem suddenly occurring on our add-ins on these environments:
- MS Project versions 1902 - Windows Server version 1607 (Testing environment)
- MS Project version 1907 - Windows version 1809
- MS Project version 1907 - Windows version 1903

**Comment by cyrelk** [comment] 2019-07-23 12:54
As I have already written above the two solutions we found to correct that problem were:
 - upgrade to the latest version of Windows10, that's not always possible of course (we have Windows 7 machines that will stay as they are for a while)
 - do a git clone|pull of the latest revision of this repository and in this case that has corrected the problem on all the machines. YMMV. 
BTW I'm a user and not a member of the team of OfficeJS so I would appreciate a comment by one of them.

**Comment by niteshgolchha85** [comment] 2019-07-23 21:22
At this point, @jargil is the best person to help out. I suspect it could be Edge caching old office.js but I'd let @jargil provide his opinion.

**Comment by niteshgolchha85** [comment] 2019-07-24 20:38
Question from engineering: what is the url for this file: project-win32-16.0x?

**Comment by ragavanrajan** [comment] 2019-07-24 21:33
@niteshgolchha85  Here is the requested information : "`?_host_Info=Project$Win32$16.01$en-US"`

**Comment by htryggva** [comment] 2019-07-25 08:53
@niteshgolchha85 On my environment the url is:
https://appsforoffice.microsoft.com/lib/1/hosted/project-win32-16.00.js

Project Version 1908 (Office Insider)
Windows Version 1903

Further note: On my machine, IE is being used for the WebView on MS Project. Edge is being used on the other Office apps. Is that normal?

**Comment by jjhua-github** [comment] 2019-07-25 16:58
@htryggva Do you have the "permission denied" problem or something else? Can you double check you are not getting project-win32-16.01? What is osf.dll version? It is next to your Project product executable file. See the picture below.
![image](https://user-images.githubusercontent.com/15128617/61892922-bf205880-aec1-11e9-9bae-96c4ac9452e9.png)

 @ragavanrajan Can you confirm you are getting https://appsforoffice.microsoft.com/lib/1.1/hosted/project-win32-16.01.js or https://appsforoffice.microsoft.com/lib/1/hosted/project-win32-16.01.js? It would be great if you can tell me your osf.dll version as well.

**Comment by htryggva** [comment] 2019-07-25 19:21
@jjhua-github I'm getting the "permission denied" error when trying to opening a dialog using the DialogAPI. 

I'm getting the 16.00 version:

![image](https://user-images.githubusercontent.com/6515360/61902242-e444b380-af21-11e9-9a82-ca6fcd7600e7.png)

osf.dll:
![image](https://user-images.githubusercontent.com/6515360/61902297-03434580-af22-11e9-9593-b1537d9e7fe9.png)

Hope this helps! Let me know if you need any more info.

**Comment by ragavanrajan** [comment] 2019-07-25 20:59
@jjhua-github  sure. Here is the requested information 

`   Request URL: https://appsforoffice.microsoft.com/lib/1.1/hosted/project-win32-16.00.js`

![image](https://user-images.githubusercontent.com/6369107/61908199-4b468480-af83-11e9-95e7-e51cb9ec8d4a.png)

**OSF.DLL:**

![image](https://user-images.githubusercontent.com/6369107/61908392-ad9f8500-af83-11e9-8e94-08d0b40c57fe.png)

Please let me know if you need any further info.

**Comment by jargil** [comment] 2019-07-25 21:50
@htryggva - regarding Project not using Edge WebView, that's unexpected, I'm looking into this. As always, thanks for reporting!

**Comment by jargil** [comment] 2019-07-25 21:53
Not Edge related, so assigning to @jjhua-github.

**Comment by jjhua-github** [comment] 2019-07-26 17:56
Sorry, we have a bug in https://appsforoffice.microsoft.com/lib/1/hosted/project-win32-16.00.js and https://appsforoffice.microsoft.com/lib/1.1/hosted/project-win32-16.00.js. We are working on fix right now. ETA: next week the fix will be on dogfood CDN; a week later on public CDN.

**Comment by AllepuRajkumar** [comment] 2019-08-07 10:30
I'm also facing the same issue, while adding task pane add-in to MS Project.

![image](https://user-images.githubusercontent.com/43134772/62616163-7ab6a300-b92c-11e9-9b52-450c6a7963d3.png)

MS Project Client details: 

![image](https://user-images.githubusercontent.com/43134772/62616245-ae91c880-b92c-11e9-83bc-aed5293f6948.png)

**Comment by binarykitchen** [comment] 2019-08-13 23:32
@jjhua-github it's been 18 days ... is this fix out yet?

**Comment by ragavanrajan** [comment] 2019-08-13 23:34
@binarykitchen  I think the thread is not updated. It started working on the above reported build. Could you please check.

**Comment by binarykitchen** [comment] 2019-08-14 00:06
Right, latest version `//unpkg.com/@microsoft/office-js@1.1.29/dist/office.js` resolves this.

**Comment by jargil** [comment] 2019-08-14 00:37
This fix is getting deployed already. Thanks everyone who confirmed is working now.

**Closed as completed by jargil** 2019-08-14 00:37 UTC
Labels: Area: add-ins platform, Area: Project, Status: fixed

**Comment by htryggva** [comment] 2019-08-20 05:52
@jargil @jjhua-github I can confirm that it's working for me (Version 1908). Thanks!

**Comment by BlackStef** [comment] 2020-03-26 15:55
Hello, 

I'm having the same issue when I try to host my add-in with https. 
I get a RichApi.Error : AccessDenied, but It's working when I disable the https on my server. 
This issue happen when I try to get some data from my excel workbook with my add-in. 

For information It's hosted with an nginx container on a docker server. 
My excel version is 1902 and my office-js version is 1.0.31

Do you have some information about this issue ? 

Thank you in advance ! :)

**Comment by jargil** [comment] 2020-03-26 19:03
This issue has been long resolved, so please follow the conversation above to make sure you have all the patches/updates installed.

Otherwise please wait for your new issue to be triaged and assigned to someone to try to help you.
