### ISSUE TITLE
Sorting on tables not working after sheet is protected, even with option allowsort set!

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2135] opened 2021-09-21 17:46 UTC
We are facing a big challange. We want our users to see the data in the form of tables and allow them to sort, filter, formatting, etc on them.
But we want to prevent any changes to the data (or part of the data).

To prevent changes we want to protect the sheet. And we hopped that with the options we were able to allow them to sort, filter etc.
But once the sheet is protected, our users can not sort, nor filter, nor do any formatting. And we made sure the Options were set.

## Your Environment
* Platform: PC desktop & Office on the web
* Host : Excel
* Office version number: 14326.20404
* Operating System: Windows 10
* Browser (if using Office on the web): Edge
 
## Expected behavior
Once a sheet is protected, and the ProtectionOptions are set to allow sorting/filtering/formatting, that it also applies on tables.

## Current behavior
Currently is looks like the ProtectionOptions work only outside tables, not withing tables once the sheet is protected.

## Steps to reproduce
I have change an existing Script-lab. In that example I set allowSort. but in the table it is still not working after protecting.
name: Data protection
description: Protects data in a worksheet and the workbook structure.
host: EXCEL
api_set: {}
script:
  content: >
    $("#setup").click(() => tryCatch(setup));

    $("#protect-data-in-worksheet").click(() =>
    tryCatch(protectDataInWorksheet));

    $("#unprotect-data-in-worksheet").click(() =>
    tryCatch(unprotectDataInWorksheet));

    $("#protect-workbook-structure").click(() =>
    tryCatch(protectWorkbookStructure));

    $("#unprotect-workbook-structure").click(() =>
    tryCatch(unprotectWorkbookStructure));

    $("#password-protect-data-in-worksheet").click(() =>
    tryCatch(passwordProtectDataInWorksheet));

    $("#password-unprotect-data-in-worksheet").click(() =>
    tryCatch(passwordUnprotectDataInWorksheet));

    $("#password-protect-workbook-structure").click(() =>
    tryCatch(passwordProtectWorkbookStructure));

    $("#password-unprotect-workbook-structure").click(() =>
    tryCatch(passwordUnprotectWorkbookStructure));

    async function protectDataInWorksheet() {
      await Excel.run(async (context) => {
        let activeSheet = context.workbook.worksheets.getActiveWorksheet();
        activeSheet.load("protection/protected");

        await context.sync();

        if (!activeSheet.protection.protected) {
          activeSheet.protection.protect({ allowSort: true });
        }
      });
    }

    async function unprotectDataInWorksheet() {
      await Excel.run(async (context) => {
        let activeSheet = context.workbook.worksheets.getActiveWorksheet();
        activeSheet.protection.unprotect();
      });
    }

    async function protectWorkbookStructure() {
      await Excel.run(async (context) => {
        let workbook = context.workbook;
        workbook.load("protection/protected");

        await context.sync();

        if (!workbook.protection.protected) {
          workbook.protection.protect();
        }
      });
    }

    async function unprotectWorkbookStructure() {
      await Excel.run(async (context) => {
        let workbook = context.workbook;
        workbook.protection.unprotect();
      });
    }

    async function passwordProtectDataInWorksheet() {
      let password = await passwordHandler();
      passwordHelper(password);
      await Excel.run(async (context) => {
        let activeSheet = context.workbook.worksheets.getActiveWorksheet();
        activeSheet.load("protection/protected");

        await context.sync();

        if (!activeSheet.protection.protected) {
          activeSheet.protection.protect(null, password);
        }
      });
    }

    async function passwordUnprotectDataInWorksheet() {
      let password = await passwordHandler();
      passwordHelper(password);
      await Excel.run(async (context) => {
        let activeSheet = context.workbook.worksheets.getActiveWorksheet();
        activeSheet.protection.unprotect(password);
      });
    }

    async function passwordProtectWorkbookStructure() {
      let password = await passwordHandler();
      passwordHelper(password);
      await Excel.run(async (context) => {
        let workbook = context.workbook;
        workbook.load("protection/protected");

        await context.sync();

        if (!workbook.protection.protected) {
          workbook.protection.protect({ allowSort: true}, password);
        }
      });
    }

    async function passwordUnprotectWorkbookStructure() {
      let password = await passwordHandler();
      passwordHelper(password);
      await Excel.run(async (context) => {
        let workbook = context.workbook;
        workbook.protection.unprotect(password);
      });
    }

    function passwordHelper(password: string) {
      if (null == password || password.trim() == "") {
        let errorMessage = "Password is expected but not provided";
        console.log(errorMessage);
      }
    }

    async function passwordHandler(): Promise<string> {
      let settingName = "TheTestPasswordUsedByThisSnippet";
      let savedPassword = Office.context.document.settings.get(settingName);
      if (null == savedPassword || savedPassword.trim() == "") {
        let item = document.getElementById("test-password");
        let testPassword = item.hasAttribute("value") ? item.getAttribute("value") : null;
        if (null != testPassword && testPassword.trim() != "") {
          // store test password for retrieval upon re-opening this workbook
          Office.context.document.settings.set(settingName, testPassword);
          await Office.context.document.settings.saveAsync();

          savedPassword = testPassword;
        }
      } else {
        document.getElementById("test-password").setAttribute("value", savedPassword);
      }

      console.log("Test password is " + savedPassword);

      return savedPassword;
    }

    async function setup() {
      await Excel.run(async (context) => {
        context.workbook.worksheets.getItemOrNullObject("Sample").delete();
        const sheet = context.workbook.worksheets.add("Sample");

        let expensesTable = sheet.tables.add("A1:E1", true);
        expensesTable.name = "SalesTable";

        expensesTable.getHeaderRowRange().values = [["Product", "Qtr1", "Qtr2", "Qtr3", "Qtr4"]];

        expensesTable.rows.add(null, [
          ["Frames", 5000, 7000, 6544, 4377],
          ["Saddles", 400, 323, 276, 651],
          ["Brake levers", 12000, 8766, 8456, 9812],
          ["Chains", 1550, 1088, 692, 853],
          ["Mirrors", 225, 600, 923, 544],
          ["Spokes", 6005, 7634, 4589, 8765]
        ]);

        sheet.getUsedRange().format.autofitColumns();
        sheet.getUsedRange().format.autofitRows();

        sheet.activate();
        await context.sync();
      });
    }

    /** Default helper for invoking an action and handling errors. */

    async function tryCatch(callback) {
      try {
        await callback();
      } catch (error) {
        // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
        console.error(error);
      }
    }
  language: typescript
template:
  content: |-
    <section class="ms-font-m">
        <p>This sample shows how to protect a worksheet's data and the workbook's structure.</p>
    </section>

    <section class="setup ms-font-m">
        <h3>Set up</h3>
        <button id="setup" class="ms-Button">
                    <span class="ms-Button-label">Add sample data</span>
                </button>
    </section>

    <section class="samples ms-font-m">
        <h3>Try it out</h3>
        <h4>Protect without password</h4>
        <p>
            <p>Click the next button and then notice that you cannot edit data in the worksheet.</p>
            <button id="protect-data-in-worksheet" class="ms-Button">
                <span class="ms-Button-label">Protect data in worksheet</span>
            </button>
        </p>
        <p>
            <button id="unprotect-data-in-worksheet" class="ms-Button">
                <span class="ms-Button-label">Unprotect data in worksheet</span>
            </button>
        </p>
        <p>
            <p>Click the next button and then notice that you cannot add or delete a worksheet.</p>
            <button id="protect-workbook-structure" class="ms-Button">
                <span class="ms-Button-label">Protect workbook structure</span>
            </button>
        </p>
        <p>
            <button id="unprotect-workbook-structure" class="ms-Button">
                <span class="ms-Button-label">Unprotect workbook structure</span>
            </button>
        </p>
        <h4>Protect with password</h4>
        <label>The following password will be used for the scenarios in this section:</label>
        <input id="test-password" type="text" value="pass@word1" disabled="disabled" name="test-password">
        <p>
            <p>Click the next button and then notice that you cannot edit data in the worksheet.</p>
            <button id="password-protect-data-in-worksheet" class="ms-Button">
                <span class="ms-Button-label">Password protect data in worksheet</span>
            </button>
        </p>
        <p>
            <button id="password-unprotect-data-in-worksheet" class="ms-Button">
                <span class="ms-Button-label">Password unprotect data in worksheet</span>
            </button>
        </p>
        <p>
            <p>Click the next button and then notice that you cannot add or delete a worksheet.</p>
            <button id="password-protect-workbook-structure" class="ms-Button">
                <span class="ms-Button-label">Password protect workbook structure</span>
            </button>
        </p>
        <p>
            <button id="password-unprotect-workbook-structure" class="ms-Button">
                <span class="ms-Button-label">Password unprotect workbook structure</span>
            </button>
        </p>
    </section>
  language: html
style:
  content: |-
    section.samples {
        margin-top: 20px;
    }

    section.samples .ms-Button, section.setup .ms-Button {
        display: block;
        margin-bottom: 5px;
        margin-left: 20px;
        min-width: 80px;
    }
  language: css
libraries: |
  https://appsforoffice.microsoft.com/lib/1/hosted/office.js
  @types/office-js

  office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
  office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

  core-js@2.4.1/client/core.min.js
  @types/core-js

  jquery@3.1.1
  @types/jquery@3.3.1

## Context
We have deployed our product recently but we keep having this issue. If we protect users complain about missing sorting/filtering/formatting/etc. If we not not protect they can make changes that might hurt when they save the data.

We tried to figure out an alternative locking mechanism, based on change event and putting back 'old' values. But then we have a problem when a user changes a range and the event does not include 'old' values because it is a range in stead of a cell.

**Comment by AlexJerabek** [comment] 2021-09-21 17:48
Thanks for sharing this issue @ALDriehuis.

@lumine2008, can you please take a look?

**Comment by ghost** [comment] 2021-09-23 07:20
Hi @lumine2008,

I understand that this case is assigned to you. If I can help you in any way, please let me know. The issue is become more and more urgent every day. 
Many thanks!
Lou

**Comment by qinliuMSFT** [comment] 2021-09-24 06:32
Hi @ALDriehuis , thanks for logging this issue. The issue is reproducible from my side, it has been put on our backlog VSO#5448620, will let you know once we have any updates. 

BTW, We are doing a survey to understand the pain points of add-in’s developing experience. Would you mind to help fill this survey https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR5eAlIUFFQFHqE95qTMqQuVURVE4QkZPREoxOEk1TFEySDMyQTc0U0o0Ti4u ? It should take less than 5 minutes and will be supper helpful for us. Thank you!

**Comment by yuc014** [comment] 2021-10-19 07:58
Hi @ALDriehuis, thank you for your patience. After investigation, this issue is by design.
Please see [the reference](https://support.microsoft.com/en-us/office/protect-a-worksheet-3179efdb-1285-4d49-a9c3-f4ca36276de6?ui=en-US&rs=en-US&ad=US).
![image](https://user-images.githubusercontent.com/87364252/137864008-8246b1b8-3b26-4829-9778-4759881fbcd7.png)
"Sort" is kind of different with "Filter". Using “Sort” does not just change the order of how the cells are viewed, it actually changes the values of the cells so that they are sorted. Due to this implementation of “Sort,” this worksheet protection property does not work when the cells are locked.

We have two workarounds for you if you want to sort table in a protected worksheet, both of them could only operate by UI now.

**Option 1:**
Step 1: Make cells editable so that sorting will work.
Select the range->right click->Format Cells...->Protection->uncheck the Locked box->OK
![image](https://user-images.githubusercontent.com/87364252/137861221-9dc711d6-9fc0-4fb5-bbfa-c73a803ba7a7.png)
Then this range can apply sort in protected sheet.

Step 2: Prevent users from editing these cells
Use below code to protect the sheet.
```
async function protectDataInWorksheet() {
  await Excel.run(async (context) => {
    let activeSheet = context.workbook.worksheets.getActiveWorksheet();
    activeSheet.load("protection/protected");
    await context.sync();
    if (!activeSheet.protection.protected) {
      activeSheet.protection.protect({
        selectionMode: Excel.ProtectionSelectionMode.none,
        allowAutoFilter: true,
        allowSort: true
      });
    }
  });
}
```
That is, user cannot select cell to prevent they change the cell. User could use Autofilter to sort.

**Option 2:**
Step 1: Make cells editable so that sorting will work.
Find Review in excel ribbon->Allow Edit Ranges->New->input the information->OK->Apply->OK
Then the ranges can be sorted in protected sheet.

Step 2: Prevent users from editing these cells
Same as the code in Option 1, Step 2.

Hope the workaround would unblock you. If these can't work well within your scenario, please let me know also. Then we will discuss with our PM.
Thank you!

**Comment by donlvMSFT** [comment] 2022-11-17 06:00
I'd like to close this thread as the discussion is clear. Thanks for the discuss!

**Closed as completed by donlvMSFT** 2022-11-17 06:00 UTC
Labels: Area: Excel, Type: product bug, Status: in backlog
