### ISSUE TITLE
[Outlook] Dialog for Outlook web addin not rendering fonts in Outlook windows client

### ISSUE THREAD

**Issue by mihirsn** [OfficeDev/office-js#1330] opened 2020-08-14 12:15 UTC
We are developing Outlook Web Addin. With the help of `Office.context.ui.displayDialogAsync` we are opening dialog box where our HTML is getting rendered. This HTML is rendering perfectly for all clients such as browsers and Outlook for Mac but problem is with Outlook windows client.
Issue is with font icons which are not getting rendered. We have pre-downloaded font icons from [icomoon](https://icomoon.io/app/#/select). We have provided HTML buttons in dialog box where user can perform some actions. And we are putting icons on these buttons for conveying button functionality.

CSS we are using:
```css
@font-face {
  font-family: 'icomoon';
  src:  url('fonts/icomoon.eot?hkrva0');
  src:  url('fonts/icomoon.eot?hkrva0#iefix') format('embedded-opentype'),
    url('fonts/icomoon.ttf?hkrva0') format('truetype'),
    url('fonts/icomoon.woff?hkrva0') format('woff'),
    url('fonts/icomoon.svg?hkrva0#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
```

## Expected Behavior
Font icons should get rendered in dialog box.

## Current Behavior
In Outlook windows client font icons unable to render

## Context

Because of this issue we are not able give uniform user interface for all clients.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __PC desktop__
* Host [Excel, Word, PowerPoint, etc.]: __Outlook__
* Office version number: __Microsoft Outlook for Office 365 MSO (16.0.12527.20260) 64-bit__
* Operating System: __Window 10__

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

IE Screenshot (Working as expected)

![IE](https://user-images.githubusercontent.com/42827526/90247888-2904fa80-de55-11ea-9a9a-b558eff8e5b6.JPG)
---
Outlook windows desktop client Screenshot (Font icons not rendered)

![outlook-windows-desktop-client](https://user-images.githubusercontent.com/42827526/90247890-2a362780-de55-11ea-80dd-5702bcf35ef0.JPG)

@SanketDG

**Comment by alison-mk** [comment] 2020-08-14 18:59
Hi @mihirsn, thank you for submitting this issue! I've assigned it to the Outlook engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by exextoc** [comment] 2020-08-18 22:56
In an effort to pin down the repro, do you have a simple HTML page that we can try to load and see if we can repro the issue? Does this also repro in the *taskpane* or just the dialog? 

Do you have some screenshots of how this looks, and how you expect it to look? 

Can you also provide the Windows Build? (the Windows Build affects whether or not the add-in is rendered in Edge or IE) (https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins/ Windows 1903 and later will render in Edge)

**Comment by mihirsn** [comment] 2020-08-19 07:49
Thanks for the reply and following are the details:

> In an effort to pin down the repro, do you have a simple HTML page that we can try to load and see if we can repro the issue?

Yes, here is drive link you can use to repro - [sample code](https://drive.google.com/file/d/1TE96RanXWd0vssjAhx3tftm7hOtlj8N-/view?usp=sharing)

> Does this also repro in the _taskpane_ or just the dialog?

Yes, able to reproduce the issue on _taskpane_ as well with the same sample code

> Do you have some screenshots of how this looks, and how you expect it to look?

Current behaviour

![current-behaviour](https://user-images.githubusercontent.com/42827526/90606136-0429d200-e21d-11ea-9e73-ab321990b242.JPG)

---

Expected behaviour

<img width="1014" alt="expected-behaviour" src="https://user-images.githubusercontent.com/42827526/90606229-24599100-e21d-11ea-8354-4dea08b2cc6f.png">


> Can you also provide the Windows Build?

Windows 10 Enterprise
Version - 1803
OS build - 17134.1610

**Comment by exextoc** [comment] 2020-08-19 20:35
Before we try and repro locally the Windows Build you are on indicates that the add-in will load in IE. Could this be a CSS incompatibility issue with IE? (Does the issue repro when you use Outlook Web Access through Internet Explorer?)

**Comment by mihirsn** [comment] 2020-08-20 04:56
It is working as expected on IE, so may not be CSS incompatibility issue

**Comment by exextoc** [comment] 2020-08-20 19:38
I tried loading your HTML into Outlook in both Edge and IE, and the icons showed up for me. Is there perhaps some setting on your server or IE on that machine that is preventhing the .ico files from being donwloaded? (try using fiddler to make sure they are retrieved) Updating windows may also help? (or trying on different machines.  

![image](https://user-images.githubusercontent.com/28549921/90816872-d064b000-e2e1-11ea-92e3-1f79c3b9ae2d.png)

**Comment by mihirsn** [comment] 2020-08-21 05:10
For me also it is working fine if I use Outlook web access through IE. But somehow Outlook windows client not showing up these icons.
I am just confused a bit, are these screenshots from Outlook windows native client or IE/Edge browsers ?

**Comment by exextoc** [comment] 2020-08-21 17:15
Sorry my screenshots were from Outlook Windows Native Client. Depending on your version of Office/Windows. The Outlook Desktop Client, can use either IE or Edge underneath to render inside the native client. In both situations, I observed the icon font being loaded. 

Basically, I am currently unable to repro the bug, so I suspect there may be something else going on with your machine. (perhaps the font files are not being downloaded?)

**Comment by SanketDG** [comment] 2020-08-21 18:09
I belong to the same team as @mihirsn, the font files are indeed being downloaded from our own in-house server, we have confirmed this through the browser's (Chrome, Firefox, Edge) Devtools. Do you think the downloading is not happening specific to the Outlook Native Client?

At this point, this definitely looks like something is wrong on our end, what else do you think we should try out and test? We will wireshark/fiddler on the client but we want to know if you have any other things in mind that you want us to take a look at.

Thanks!

**Comment by exextoc** [comment] 2020-08-21 18:21
My guess is something is different between the regular Browser and the browser in the client client. My wild guess is that fiddler will hopefully reveal something different between the two? 

Are the font files on the server sent with a no-cache header?

Otherwise, you'll have to do some debugging/testing to figure out what may be the difference. Do different client machines / windows versions repro the issue? Does moving the add-in files to a different server help? (etc.)

**Comment by SanketDG** [comment] 2020-08-21 18:34
> Are the font files on the server sent with a no-cache header?

They are, we have confirmed this.

> Does moving the add-in files to a different server help?

Nope, it is still the same issue, but we would be willing to play with the server configuration to see if anything changes at this point.

We will try out the other suggestions and get back to you, thanks!

**Comment by exextoc** [comment] 2020-08-21 19:49
Sorry I realize I didn't clarify. Can you try not sending the "no-cache"  header. This has lead to problems in other issues before.

**Comment by mihirsn** [comment] 2020-08-22 18:32
Thanks, will try this and update you accordingly.

**Comment by mihirsn** [comment] 2020-08-24 13:24
We tried removing the "no-cache" header for font files and it is working now for Outlook Windows Native Client as well.

Thanks for the suggestion.

So should I close this issue ?

**Comment by exextoc** [comment] 2020-08-24 18:51
I'm glad that resolve the issue. I can go ahead and close this.

**Closed as completed by exextoc** 2020-08-24 18:51 UTC
Labels: Needs: attention :wave:, Area: Outlook
