### ISSUE TITLE
Word: paragraph.insertBreak adds break in the next paragraph, not the current one

### ISSUE THREAD

**Issue by wbecker** [OfficeDev/office-js#2792] opened 2022-08-23 19:01 UTC
When I use paragraph.insertBreak("Line", "After"), I expect it to work as it would if I clicked shift+enter. This adds a new line at the end of the current paragraph. However, when the paragraph is in a numbered list, it adds it to the next one. It is important that it adds it to the end of the current one so that I can put something before the next list item.

## Expected Behavior
When I use paragraph.insertBreak("Line", "After"), I expect it to work as it would if I clicked shift+enter. This adds a new line at the end of the current paragraph.

## Current Behavior
However, when the paragraph is in a numbered list, it adds it to the next one. It is important that it adds it to the end of the current one so that I can put something before the next list item.

Example output:
![image](https://user-images.githubusercontent.com/348044/186241160-b9c6f3ae-43ce-4f42-ad43-da6b26aedca6.png)

Example paragraph text:
![image](https://user-images.githubusercontent.com/348044/186241284-05d4c40f-13b1-49e1-91bb-d322e374d825.png)

Note the `\u000b` at the start of the 4th item

## Steps to Reproduce, or Live Example
1. Create a word document with a list
2. Add a break in a paragraph at the middle of the list
3. Notice the break is in the next paragraph, not the current one

**Comment by xuruiyao-msft** [comment] 2022-08-24 07:40
@wbecker I think it is by design and not a issue.

The paragraph.insertBreak("Line", "After") always inserts the line break after the paragraph no matter if there're list number or not.  
The  carriage return and the line feed  also belongs to the paragraph. We call it "eop" i.e. end of paragraph. The parameter "after" means that the line break is outside of the first paragraph, so the "\u000b" is  outside of the "eop" no matter if there're list number or not. This results in that it resides at the start of the second paragraph. 

But the "shift+enter" means inserting line break in the selected range, in your scenario, I think the selected range is where the cursor is pointed at and the cursor is pointed at the end of the first paragraph but before the "eop" of the first paragraph. So "shift+enter" shows that you insert the line break at the end of the first paragraph and it still belongs to the first paragraph.

Actually we have another location parameter "End", but for paragraph it is not supported. We only support "Before" and "After" now. I will introduce this issue to our PM to evaluate if we should support it or not.

**Comment by wbecker** [comment] 2022-08-24 07:54
Thanks @ahegongzhu - I don't think a user would ever want to add a line break at the start of the next paragraph, as opposed to within the current one! I understand that it doesn't necessarily fit the definition of "after". 

I have worked around this by adding a "\u000b" to the end of the paragraph instead.

**Comment by xuruiyao-msft** [comment] 2022-08-25 07:39
@wbecker There's another way to achieve your goal.
Try this piece of code:

const par = context.document.body.paragraphs.getFirst();
    let range = par.getRange('End');
    range.insertBreak("Line", "Before");

    await context.sync();

It will add the line break at the end of the first paragraph and still belongs to the first paragraph.

**Comment by JinghuiMS** [comment] 2022-08-29 10:11
If no further question, we will close this thread! Thanks for raising your question again!

**Closed as completed** 2022-09-05 14:02 UTC
Labels: Needs: author feedback, Area: Word, Status: no recent activity
