### ISSUE TITLE
Office.js displayDialogAsync not available

### ISSUE THREAD

**Issue by Githamza** [OfficeDev/office-js#3506] opened 2023-07-12 11:48 UTC
I'm using office.js to open dialogbox and login user.

When I run Office.context.ui.displayDialogAsync() I get undefined error

I have inspected the content of Office.context.ui this is what I got:

![image](https://github.com/OfficeDev/office-js/assets/11578288/4f064b1c-8161-491c-b4e3-740fabbf48b3)

It's missing displayDialogAsync() method

Some days ago it was working

I'm using this version : https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js

I have tried in mac os desktop client and web , same issue

**Comment by yjoshi-msft** [comment] 2023-07-13 11:31
Hi Githamza,

Thank you for raising the issue. Unfortunately we would require more information from your end to reporduce this issue properly at our end. 

Please share as much information as possible in the below format to help us out - 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by Githamza** [comment] 2023-07-13 11:54
Sorry I have found the cause : I was calling the displayDialogAsync method inside the dialogApi popup which is not logic

the displayDialogAsync method should be called inside the taskpane window

**Comment by samantharamon** [comment] 2023-07-17 17:58
We're glad to hear you were able to determine the cause, @Githamza. I'll go ahead and close this issue, but should you need additional assistance, please don't hesitate to open a new one.

**Closed as completed by samantharamon** 2023-07-17 17:58 UTC
Labels: Needs: attention :wave:, Resolution: by design, Area: Common APIs
