### ISSUE TITLE
Fetching document sources or bibliography with customXmlParts

### ISSUE THREAD

**Issue by NickDarvey** [OfficeDev/office-js#1645] opened 2021-02-17 01:37 UTC
We're trying to look at a documents sources (a.k.a. citations, or `http://schema.openxmlformats.org/officeDocument/2006/bibliography/Sources`) of a document, however we can't fetch it using `customXmlParts.getByNamespaceAsync`

## Expected Behavior
An array of document sources are returned.

## Current Behavior
An empty array is returned.

If we inspect the document (unzip, look at the custom parts) we can see the part and sources as expected.

If we use `getByIdAsync` (instead of `getByNamespaceAsync`) using the GUID found in the related itemProp*.xml, we get an array of document sources returned. However that GUID isn't well-known (it seems to change with each document) and we don't know how to discover that GUID without inspecting the file manually.

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/triandco/236e0432231aa4f022dc5b9f1590670c

* Additional details:
  1. Open a new Word document
  2. Insert a citation, e.g. using Word's Researcher add-in, which adds a source to the document
  3. Run the linked example (which fetches sources using `customXmlParts.getByNamespaceAsync("http://schema.openxmlformats.org/officeDocument/2006/bibliography")`)

## Context
We want to view and potentially update citations in a Word document.

## Your Environment
* Platform: PC desktop
* Host: Word
* Office version number: Version 2101 (13628.20380) x64
* Operating System: Windows 10 Pro 1909 (18363.1379)

**Comment by NickDarvey** [comment] 2021-02-23 00:15
Is there anyone on the team familiar with working with the bibliography? Are there any examples out there of this being done? 

The 'Researcher' does this, but I'm not sure it's an add-in. If it is, it would be great to share the source.

![image](https://user-images.githubusercontent.com/6076697/108786749-6991bd80-75c8-11eb-9b96-6b3b9eeb9136.png)

**Comment by NickDarvey** [comment] 2021-03-05 05:06
Any chance someone from the team can comment on this one?

**Comment by AlexJerabek** [comment] 2021-03-05 18:52
Hi @NickDarvey, 

I'll ping @AbidRahman-MSFT to confirm, but I don't believe this functionality exists for public add-ins today. I'd recommend adding or upvoting this feature request on [UserVoice](https://officespdev.uservoice.com/). That helps us prioritize new features based on community interest.

**Comment by AbidRahman-MSFT** [comment] 2021-03-06 01:15
Thanks for the ping Alex!

Hey @NickDarvey , sorry for the delay. Thanks for the question and for the sample. I had a chance to take a look at the sample you provided. It looks like there is an error in the namespace URL that you are using. You're missing an 's' in schema's'. Try changing to the following namespace:

`http://schemas.openxmlformats.org/officeDocument/2006/bibliography`

Fixing the namespace URL now gives me 1 result in the array, which includes the customXMLPart for the bibliography. You can then use something like .getXmlAsync() with that xmlpart to get the actual XML representation of the bibliography. For e.g. try this:

```
async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;

    const namespace = "http://schemas.openxmlformats.org/officeDocument/2006/bibliography";

    console.log("Bibiliography sources: ");

    Office.context.document.customXmlParts.getByNamespaceAsync(
      namespace, {}, function (result) {
        var xmlPart = result.value[0];
        xmlPart.getXmlAsync({}, function (eventArgs) {
          console.log(eventArgs.value);
        });
      }
    );

    await context.sync();

  });
}
```

**Comment by triandco** [comment] 2021-03-09 00:53
Hi @AbidRahman-MSFT,

I copied and ran the code snippet that you sent through. Unfortunately, this only works for documents that has been saved. If the document is newly created and is not saved, the result of getByNamespaceAsync is an empty array. Would there be a difference depending on the version of words I use? I'm running word on Windows:
![image](https://user-images.githubusercontent.com/61586052/110401198-40475600-80cd-11eb-86e7-8e45aef6cef3.png)

**Comment by AbidRahman-MSFT** [comment] 2021-03-09 01:06
Hey @triandco - thanks for pointing that out. That looks like a bug to me. The version of Word should not matter here as the APIs have been supported for quite a while.

We'll investigate and let you know what we find.

**Comment by AbidRahman-MSFT** [comment] 2021-03-15 17:42
Hey @triandco, we investigated this issue and the engineering team has decided that this is by-design expected behavior from CustomXMLParts. 

More context: The CustomXMLParts of a document reflects what is actually written out into XML on disk - someone cracking open the .docx themselves also wouldn't see anything until a save happens in this case. For a workaround, what you can try here is getting the entire OOXML representation of the content in the document. Using something like .getOoxml() will return to you the representation of content that lives in-memory and will return the actual XML that includes the bibliography.

I hope that makes sense. Closing the issue, feel free to reply if there are more questions.

**Closed as completed by AbidRahman-MSFT** 2021-03-15 17:42 UTC
Labels: Area: Word
