### ISSUE TITLE
Edge DevTools debugger crashes frequently

### ISSUE THREAD

**Issue by TheSamsterZA** [OfficeDev/office-js#657] opened 2019-08-07 01:26 UTC
## Expected Behavior

When debugging my OfficeJS add-in, I expect a solid, stable debugging experience.

## Current Behavior

Debugging OfficeJS add-ins using the Edge DevTools is extremely frustrating. The debugger crashes often, and reloads my add-in to boot.

This is not expected behaviour. 

## Steps to Reproduce, or Live Example

  1. Download and install the [Edge DevTools](https://www.microsoft.com/en-au/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj?activetab=pivot:overviewtab) from the Microsoft Store
  2. Create an OfficeJS add-in, run it locally and sideload your manifest
  3. Attempt to debug your add-in, using breakpoints and `debugger `statements
  4. Notice, the Edge DevTools crashes, and the add-in is reloaded with the message:

```
Sorry, we had to restart because this add-in wasn't responding.
```

## Context

While I believe this should not matter, my add-in uses Angular and thus Webpack internally, with sourcemaps enabled.

Note that the debugging in IE11 is actually better than this. There are no crashes, and while it takes a while to load the sourcemaps, debugging with this is infinitely more productive than with the Edge DevTools.

## Recommendation

**Please** seriously consider switching to **Chromium-powered Edge**, and add first-class debugging support using Chrome's debugging tools, that work seamlessly with Office hosts (Word, Outlook, Excel, etc).

I know Chromium-based Edge is in preview, but so is the Edge DevTools. :)

## Your Environment

* Platform: PC Desktop
* Host: Outlook
* Office version number: Outlook 2016 for Windows Version 1909 (Build 12001.20000 Click-to-Run), Office Insider
* Operating System: Windows 10 Version 1903 (OS Build 18362.239)
* Browser (if using Office Online): N/A

## Useful logs

- [x] Screenshots

Below is a GIF I created showing the behaviour.

![edge-devtools-office-js-debugger-crash](https://user-images.githubusercontent.com/4981594/62587541-d91c5b00-b905-11e9-94a1-b9eac3fe882e.gif)

**Comment by jargil** [comment] 2019-08-10 05:49
@TheSamsterZA - what you're observing is Office detecting a hang in your add-in and restarting it to get unblocked - the debugger is not crashing. In this case the hang is caused by your breakpoints and thus blocking your add-in UI from pumping messages.

Please read this document:
https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization

In order to disable this feature and be able to debug without the add-in restarting you can set the AlertInterval registry key to 0.

Let me know if this helped get you unblocked.

**Comment by jargil** [comment] 2019-08-20 22:12
Closing this one. Thanks for taking the time to create this report/issue.

**Closed as completed by jargil** 2019-08-20 22:12 UTC
Labels: Area: Edge WebView, Resolution: by design

**Comment by TheSamsterZA** [comment] 2019-08-27 00:17
Hello @jargil, 

Apologies for the late reply on this. Life happens. :)

> In order to disable this feature and be able to debug without the add-in restarting you can set the AlertInterval registry key to 0.

I searched high and low and could not find this registry key. Do you perhaps have more information about where I should look?

> what you're observing is Office detecting a hang in your add-in and restarting it to get unblocked...

> the hang is caused by your breakpoints and thus blocking your add-in UI from pumping messages.

Please forgive my ignorance, but why is it that this does not happen when debugging using F12 Tools with breakpoints? There is clearly a difference here, and I believe the way Office now handles debugging is flawed on a fundamental level.

At the very least, Office needs to be smart enough to ignore any resource limits or hangs if the add-in is run from a local manifest - or if the URL that is loaded in the webview literally has `localhost` in its hostname. I'd wager that production add-ins would not need to be debugged and likely would not contain sourcemaps, but during development being able to debug using breakpoints is critical to the development experience.

Please thoughtfully consider the above, coming from someone who has worked with OfficeJS and has championed the technology at my company for many years.

Thank you.

**Comment by jargil** [comment] 2019-08-27 00:42
@TheSamsterZA - thanks for your feedback.

When you're in development mode, say loading from a local manifest, you should be able to test your add-in end to end before submitting to the Office store, that includes testing for performance issues that could be flagged by Office.

Try adding the following key:
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\16.0\Wef]
"AlertInterval"=dword:00000000

Please test using one of the latest Office Insiders builds.

**Comment by TheSamsterZA** [comment] 2019-09-02 00:26
@jargil I can't speak for everyone, but at my company we have multiple environments which we use to test our add-ins. My development process goes something like this:

1. There's a bug.
2. Load up the add-in on my local machine, with a manifest pointing to localhost (**Dev Environment**).
3. Boot up the localhost web server (via Angular CLI).
4. Attempt to replicate the issue.
5. Narrow it down to a function in my code.
6. Place a few breakpoints on the lines that might be causing the issue.
7. Debug iteratively until the bug is fixed.
8. Push the fix to the **Test Environment**.
9. My QA team validate the fix, including end-to-end tests that track degradation in performance among other things.
10. A deployment containing the fix is scheduled.
11. The fix is deployed to the **Live Environment**.

Step 7 is the developer's bread and butter. If the debugging experience is sub-par, then that just causes frustration in an otherwise enjoyable development experience.

I still think Office needs to be smarter about how it handles performance issues in an add-in if that add-in is being loaded from a local place (i.e. **Dev Environment**). In all other cases, sure, flag performance issues.

While I am glad there is a way to effectively switch off this feature, I do think it needs to be in the official docs. The page you linked to earlier would be ideal - but it does need to be updated to include the exact location in the registry instead of just naming registry keys: 

https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization

Thank you for taking the time to listen to my concerns. While sometimes it might not seem like it, all Office developers including myself appreciate your work.

**Comment by jargil** [comment] 2019-09-03 18:09
@TheSamsterZA - thank you for your feedback! I've taken note and will discuss internally.

**Comment by Rick-Kirkham** [comment] 2019-09-25 23:18
@TheSamsterZA Sometime in the next week or two, you should see a new Edge webview troubleshooting section added to this article: [Browsers used by Office Web Add-ins](https://docs.microsoft.com/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins). It will describe this problem and the solution.
