### ISSUE TITLE
createWorkbook now produces an empty warning message.

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js#4031] opened 2024-01-19 19:43 UTC
When I call Excel.createWorkbook, it used to show this messagebox:

![image](https://github.com/OfficeDev/office-js/assets/27964706/ee4dc5d2-9b0a-4b17-b640-f9475e48ba30)
saying "This Add-in is about to create a new document in your default folder on your current cloud repository"

Now, it still produces a messsagebox with yes/no options, but the message is empty.
![image](https://github.com/OfficeDev/office-js/assets/27964706/0e2acf85-f1d2-4fc0-a6e0-2a42e2570fcd)

**Comment by zhenhuangMSFT** [comment] 2024-01-22 07:49
Hi @EdwinStraver, thanks for reporting this issue. Could you share how to reproduce this empty dialog? How did it happen? Thanks!

**Comment by EdwinStraver** [comment] 2024-01-22 16:11
I run this code:

Excel.run(function (context) {
    Excel.createWorkbook(workbookContents);
    return context.sync().catch(function (err) {
        common.errorHandler(err);
    });
});

where workbookContents is a base64 encoded string.

**Comment by dingjin-ms** [comment] 2024-01-23 03:04
@EdwinStraver I have tested with sample code of [Excel.createWorkbook](https://learn.microsoft.com/en-us/javascript/api/excel?view=excel-js-preview#excel-excel-createworkbook-function(1)), and all went well.
![image](https://github.com/OfficeDev/office-js/assets/80384052/d3b41c80-5187-44bc-bd95-45934f2158a4)

Could you please see your build version in 'File->About'. For example, mine is '16.0.17321.42305'.

**Comment by EdwinStraver** [comment] 2024-01-23 16:12
Hmm, using 16.0.17321.42305 as well...

**Comment by dingjin-ms** [comment] 2024-01-24 03:15
@EdwinStraver  My collegue could repro with her personal account. Opened internal ticket #8686889 to track the issue.

We will let you know when we got progress, thank you!

**Comment by dingjin-ms** [comment] 2024-01-25 06:52
Hi @EdwinStraver , we have found the root cause and got a fix checked in to the repository. It will take several days, noramally no longer than a week, to deploy to Excel Online production. Please feel free to reach us if you have more questions! Thank you again for reporting the issue!

**Closed as completed** 2024-02-01 11:20 UTC
Labels: Area: Excel, Needs: author feedback, Area: add-in UI, Status: fix pending, Status: no recent activity
