### ISSUE TITLE
An add-ins custom functions are not available after add-in installation in Excel for Mac

### ISSUE THREAD

**Issue by leybal** [OfficeDev/office-js#1900] opened 2021-06-01 13:01 UTC
# Provide required information needed to triage your issue
Hi, our team noticed some production problems after an add-in installation in Excel for Mac.
Let's consider example based on Cryptosheets add-in. After the add-in installing a user has no access to custom functions. A user can open the task pane, but can't use custom functions from this add-in. Custom functions are not available in the list of all functions (Formulas tab -> Insert Function), and there is no prompt when a user trying write a formula in a cell.
We made [the video demonstrating this issue](https://drive.google.com/file/d/1MZE9ZYTwKBeDmB2MDPvL9TWJhuDp3iEL/view?usp=sharing).
Moreover, sometimes after installing the add-in, it is not available in My add-ins list (Insert tab -> My add-ins). A user must click the "Refresh" button for the add-in to appear in My add-ins list. After that, custom formulas become available.
Sometimes a user even have to reload the add-in by clicking on the Reload button in the task pane.
This issue is reproducible when installing various add-in in Excel for Mac. It looks like some add-in functionality has not been loaded.
 
## Expected behavior
An add-in with custom functions will work correctly after installation and a user will have access to custom functions.

## Current behavior

A user does not have access to add-in custom functions after add-in installation from Microsoft AppSource. In this case a user should press Refresh button in My Add-ins list and press on the Reload button in the task pane.

## Steps to reproduce

1. Install [Cryptosheets](https://appsource.microsoft.com/en-us/product/office/wa104381695?tab=overview)
2. Press Trust this add-in button
3. Try to write a formula in a cell like `=CS.PRICE()`
4. If custom function is available try to remove the add-in and install It again. But if custom function is not available go to Insert tab, open My add-ins and press Reload button. Sometimes we have to reload the add-in by clicking on the Reload button in the task pane.

## Context

Our team and I received a message from user that he can't use our custom functions in Excel for Mac after the add-in installation. This was first installation. The user tried to remove the add-in and install it again, but it didn't help.

## Your Environment

* Platform: Mac
* Host: Excel
* Office version number: 16.49 (21050901)
* Operating System: macOS Big Sur 11.3.1

**Comment by xiaochunms** [comment] 2021-06-02 07:22
@leybal Sorry to hear the issue and thanks to report it. I tried the same at my side, the Custom Functions in the add-in works well (My Excel Mac version is 16.49 (21050201) which is a little bit earlier than yours (16.49 (21050901)) but I think there is no big difference.) From the video and the description, I think the root cause is that Custom Functions in the add-in are not registered. You may can [clear cache](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache) and re-install the add-in to have a try. And you can enable [runtime logging](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging#runtime-logging-on-mac) to see if there is any errors when the add-in is installed.

**Comment by massonj** [comment] 2021-06-08 23:45
@leybal closing this issue assuming that @xiaochunms 's suggestions resolved the issue for you. If not, feel free to re-open, and please include the information from the runtime logs.

**Closed as completed by massonj** 2021-06-08 23:45 UTC
Labels: Needs: attention :wave:, Area: Excel
