### ISSUE TITLE
Gmail account on mac allows for addins

### ISSUE THREAD

**Issue by cbishop-fv** [OfficeDev/office-js#2974] opened 2022-11-15 20:40 UTC
We have an office outlook add-in and use https://github.com/AzureAD/microsoft-authentication-library-for-js for azure auth along with https://github.com/microsoftgraph/msgraph-sdk-javascript to make calls to perform mailbox actions for users in the addin.

Outlook Desktop on Mac allows users with gmail accounts to add them as "exchange" or "supported" accounts not just POP or IMAP. I believe the user has to have a 365 sub tied to the gmail account too.  We don't have an same issue with windows becasue gmail has to be added as IMAP or POP accounts and they are not considered exchange accounts and are not allowed to use addins. but these accounts are for some reason allowed to use addins? This is causing errors / issues with mail boxes since they are not exchange accounts and the apis cant find the mail box ect.

A few question
1. should these accounts be allowed to access addins?
2. if yes why is it not the same case for windows desktop users?
3. if yes is there a way to get these accounts to work with graph API 

<img width="692" alt="image (13)" src="https://user-images.githubusercontent.com/56599161/202018715-ef8bdea3-778a-4e6a-97d9-1e3d66ff5206.png">

SS of a gmail account with an addin open

<img width="1584" alt="image (14)" src="https://user-images.githubusercontent.com/56599161/202020950-37d2a6b3-650d-4923-aa62-57cdc7de4475.png">

**Comment by samantharamon** [comment] 2022-11-17 00:45
Thank you for reaching out, @cbishop-fv.

@exextoc, could you please assist with this?

**Comment by exextoc** [comment] 2022-11-24 12:58
Hi @cbishop-fv , could you share a small addin where we can reproduce this issue with a gmail account. You could send an abridged add in which just demonstrates the issue. Our email id is - OutlookExtensibility@M365x27035562.onmicrosoft.com. This will help us in resolving this faster.

**Comment by cbishop-fv** [comment] 2022-11-28 15:57
> Hi @cbishop-fv , could you share a small addin where we can reproduce this issue with a gmail account. You could send an abridged add in which just demonstrates the issue. Our email id is - [OutlookExtensibility@M365x27035562.onmicrosoft.com](mailto:OutlookExtensibility@M365x27035562.onmicrosoft.com). This will help us in resolving this faster.

I should be able to do that I will try and get that later this week.

**Comment by exextoc** [comment] 2022-12-11 23:00
Closing the issue due to inactivity.

**Closed as completed** 2022-12-11 23:02 UTC
Labels: Area: Outlook, Needs: author feedback, Type: product question
