### ISSUE TITLE
"Add-in Error: We couldn't get the information needed to start this add-in." when adding Mentimeter add-in for PowerPoint Web

### ISSUE THREAD

**Issue by Augustalex** [OfficeDev/office-js#2921] opened 2022-10-26 15:17 UTC
# Reproduction steps:
1. Create a new presentation in PowerPoint Web.
2. Insert a new add-in, select Mentimeter from the Store tab. This will add the add-in to your first slide.
3. The add-in will try to load and show this message:
"Add-in Error: We couldn't get the information needed to start this add-in."

![Add in error](https://user-images.githubusercontent.com/5485655/198065265-f93794d6-f229-4343-9b2d-8d6b40f4dc00.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Powerpoint Web
* Operating System: Mac 12.5.1
* Browser (if using Office on the web): Chrome 106.0.5249.119
 
## Expected behavior
The app should show a green spinner and then start loading the target website (the Mentimeter app).

## Current behavior
It does not send a request to the target website, it shows the error right away.

It seems to only affect PowerPoint Web and not the desktop app.

## Context
I'm an Engineer at Mentimeter. We discovered this issue sometime last week.

**Comment by RuizhiSunMS** [comment] 2022-10-28 07:31
@ononder Please take a look.

**Comment by Augustalex** [comment] 2022-11-01 19:03
When I press "Present", the add-in successfully loads while presenting. 

It seems to only show this error when editing the presentation.

Which still makes it a very big concern for our users using it with PowerPoint Web.

**Comment by Augustalex** [comment] 2022-11-10 18:52
We are getting a lot of support tickets regarding this error from our users. Is there any news to share, or anything you suggest we look into?

From our end the issue is very much a black box - hard to find out anything at all besides from the error shown.

**Comment by gingerjia** [comment] 2022-11-14 09:54
@Augustalex thanks very much for reporting the issue! I can repro the issue from my side and found the failure is due to there is notHttps Domain URL in your add-in mainfest: "http://adfs.lu.se". This is not allowed and throw the error message.
Please let us if the issue isn't resolved by fixing the protocol. Thanks!

**Comment by Augustalex** [comment] 2022-11-14 12:43
Thanks!

I'll upload an updated manifest and see if that solves it, or if there is anything else.

**Comment by Augustalex** [comment] 2022-11-15 10:18
It's uploaded. Let's see after it goes through certification ✅

**Comment by Augustalex** [comment] 2022-11-21 08:36
It seems to be working now 👍

**Closed as completed** 2023-05-04 07:39 UTC
Labels: Needs: attention :wave:, Area: PowerPoint
