### ISSUE TITLE
Shared Mailbox on OWA - item.loadCustomPropertiesAsync() causes error 9020 GenericResponseError

### ISSUE THREAD

**Issue by carlosb1504** [OfficeDev/office-js#3822] opened 2023-11-08 11:34 UTC
When working in a shared Mailbox on OWA - item.loadCustomPropertiesAsync() causes error 9020 GenericResponseError.

![image](https://github.com/OfficeDev/office-js/assets/47693383/0d570402-72f0-4be7-b159-8e76333cf989)

`SupportsSharedFolders` manifest attribute has been set as described here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=windows%2Cxmlmanifest#configure-the-manifest

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome Version 119.0.6045.123
 
## Expected behavior
Custom props should be retrievable / updateable

## Current behavior

Custom props are not retrievable and therefore not updateable. Error 9020 is observed. See above screenshot.
## Steps to reproduce

1. Run an add-in with `SupportsSharedFolders=true` in compose mode on a shared mailbox
2. Open taskpane & inspect using dev tools
3. In immediate window run `Office.context.mailbox.item.loadCustomPropertiesAsync(function(result) { console.log(result); })`
4. Observe error described

## Context

We rely on custom properties for the proper initialization and running of our add-in.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by carlosb1504** [comment] 2023-11-10 11:12
Hi, can you advise if this ticket has been triaged / repro'd yet? @exextoc

**Comment by exextoc** [comment] 2023-11-10 12:53
In our testing we are able to get the result properly in shared mailbox.
![image](https://github.com/OfficeDev/office-js/assets/28549921/8fad22da-cfd0-473d-a6f7-e5ee9732e41e)
Can you make sure that you are running the command in the correct frame?

**Comment by carlosb1504** [comment] 2023-11-10 13:07
Hi @exextoc, yes correct tab, we're also observing the same behaviour in the running taskpane and in LaunchEvents as well.

I should have mentioned that the shared mailbox is being opened via a new tab using the button seen here: 
![image](https://github.com/OfficeDev/office-js/assets/47693383/840384ea-30c5-42c8-9a9d-dbeed3ee0796)

I see the error every time using this method. Can you repro the same?

**Comment by exextoc** [comment] 2023-11-20 02:34
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office [4092965]

**Comment by exextoc** [comment] 2023-12-06 02:48
Hi @carlosb1504 , we have checked in a fix for this issue and the same is available in OWA client version 20231124004.01 and above. Please confirm if the issue is resolved for you.

**Closed as completed** 2023-12-21 05:54 UTC
Labels: Area: Outlook, Needs: author feedback, Status: fixed, Status: no recent activity
