### ISSUE TITLE
Outlook Online : item.body.getAsync() does not work when replying, forwarding to emails

### ISSUE THREAD

**Issue by nikhil452** [OfficeDev/office-js#3182] opened 2023-02-27 08:37 UTC
# Provide required information needed to triage your issue

## Your Environment

Platform: Office on the web
Host: Outlook, outlook.com
Office version number:
Operating System: Windows 10, MacOS
Browser (if using Office on the web): Edge, Chrome, Safari

## Expected behavior
he Office.context.mailbox.item.body.getAsync() method shall return the entire body of mail including all previous mails in chain.

## Current behavior
The Office.context.mailbox.item.body.getAsync() method returns only your own HTML, i.e. the text that you wrote.

## Steps to reproduce
Sign in to Outlook Online by using for example the Chrome browser.
Make sure the Settings -> View all Outlook settings -> Layout -> "How do you want your messages to be organized" option is set to "Show email grouped by conversation".
Select an existing email in your Inbox, click the Reply All button, type something in the body.
Execute the following code:
      var output = document.getElementById("output");
      if (output) { output.value = ''; }
      Office.context.mailbox.item.body.getAsync('html', function (result) {
        console.log('Body', JSON.stringify(result));
        if (output) {
          output.value += 'Body:' + '\r\n' + JSON.stringify(result) + '\r\n';
        }
      });
As you can see, the getAsync() method does not return the entire body.

**Comment by exextoc** [comment] 2023-03-10 08:01
This issue seems to be a duplicate of the [issue](https://github.com/OfficeDev/office-js/issues/2317). We are closing this thread. Please track the original post for updates.

**Closed as not planned by exextoc** 2023-03-10 08:01 UTC
Labels: Area: Outlook, Type: product bug, Resolution: duplicate
