### ISSUE TITLE
Can we get Addin GUID value at run time through office.js? 

### ISSUE THREAD

**Issue by anilreddyr7** [OfficeDev/office-js#839] opened 2019-11-12 06:57 UTC
We want to get custom properties through EWS which are set by Office Add in. To achieve this, we need GUID of installed addin. 

Do we have any way to get GUID value for installed addin at run time?

**Comment by anilreddyr7** [comment] 2019-11-12 06:58
> We want to get custom properties through EWS which are set by Office Add in. To achieve this, we need GUID of installed addin.
> 
> Do we have any way to get GUID value for instaled addin at run time?

@exextoc  Can you let us know if there is any way.

**Comment by exextoc** [comment] 2019-11-12 10:22
Currently OfficeJS does not expose any API to get the add-in GUID. We track Outlook add-in feature requests on [our user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process

**Comment by lindalu-MSFT** [comment] 2020-01-27 19:45
@lumine2008 Hi Raymond, is this in the backlog now (tracked internally) or can this issue be closed? Thanks,linda

**Comment by lumine2008** [comment] 2020-03-12 14:51
Looks like this more like a runtime question, so i am assigning to sudheer

**Comment by sudheesh001** [comment] 2020-03-12 16:33
It looks like you've assigned it to the wrong person. 😃 Could you make the necessary corrections @lumine2008

**Comment by ElizabethSamuel-MSFT** [comment] 2020-03-31 22:20
@anilreddyr7 If you haven't already, do make feature request on User Voice per guidance in [earlier comment](https://github.com/OfficeDev/office-js/issues/839#issuecomment-552830505). I'll close this now but if you have any other feedback, let us know.

Thanks.

**Closed as completed by ElizabethSamuel-MSFT** 2020-03-31 22:20 UTC
Labels: Area: Outlook, Type: product feature request, Type: programming question, Resolution: question answered

**Comment by andreyvcita** [comment] 2021-11-25 13:29
@ElizabethSamuel-MSFT @anilreddyr7 Hi, any update?  UserVoice is no longer available

**Comment by leewisestamp** [comment] 2021-11-25 16:35
We also need this functionality. Any update or workaround? Thanks.

**Comment by exextoc** [comment] 2021-11-30 17:31
You can get the add-in guid without office.js. Since the add-in guid is a constant and known to the add-in, you can have a constant in the add-in JS to get the guid. Alternatively, the add-in can also use a parameter and include the guid in the add-in’s entry point URL to retrieve the guid.

**Comment by leewisestamp** [comment] 2021-12-01 10:11
> You can get the add-in guid without office.js. Since the add-in guid is a constant and known to the add-in, you can have a constant in the add-in JS to get the guid. Alternatively, the add-in can also use a parameter and include the guid in the add-in’s entry point URL to retrieve the guid.

Can you please share a code sample of how to do what you mentioned? We couldn't find any documentation on this.

**Comment by exextoc** [comment] 2021-12-03 21:52
In your add-in [manifest](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/manifests), you define your add-in id such as:
`  <Id>7164e750-dc86-49c0-b548-1bac57abdc7c</Id>`

This id is a constant and known to you. You can define this id in the JS of your add-in implementation for use within your add-in.

**Comment by leewisestamp** [comment] 2021-12-04 15:53
> In your add-in [manifest](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/manifests), you define your add-in id such as: ` <Id>7164e750-dc86-49c0-b548-1bac57abdc7c</Id>`
> 
> This id is a constant and known to you. You can define this id in the JS of your add-in implementation for use within your add-in.

Right. The problem is that we have 3 manifest files (1 per environment: Dev, QA, PROD) that each have a different ID. So how do we know in the JS which ID to use?

**Comment by exextoc** [comment] 2021-12-06 22:47
If you have multiple add-in ids, you will probably need to implement this using the second option: "the add-in can also use a parameter and include the guid in the add-in’s entry point URL to retrieve the guid." 

You can pass the add-in guid that is defined in the manifest as a query parameter in the add-in entry point URL (defined in the same manifest). Then, you can read the query parameter in the JS and obtain the add-in guid from there.
