### ISSUE TITLE
Inspect Element does not appear in right click menu on Mac

### ISSUE THREAD

**Issue by misaunde** [OfficeDev/office-js#506] opened 2019-05-08 20:49 UTC
I'm following this tutorial for debugging  a sideloaded Excel add-in on Mac:
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac

And using Mac OS 10.14.4 and Office 365 Excel version 16.24 (19041201). After adding:
`defaults write com.microsoft.Excel OfficeWebAddinDeveloperExtras -bool true` in the terminal, and rebooting: "Inspect Element" does not appear in right click menu inside my Office add-in, in Excel.

Is it because I have a newer OS than High Sierra? Any Ideas?

## Expected Behavior

Inspect Element should appear in right click menu so I can access the inspector on mac and be able to debug. This is for an add-in/manifest that works as expected in Windows 10.

## Current Behavior

Inspect Element does not appear in the right click menu.

## Context

Would like to be able to debug on mac (mainly view the console)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ____Mac__
* Host [Excel, Word, PowerPoint, etc.]: _____Excel_
* Office version number: ___Excel 16.24 Office 365___
* Operating System: __Mac OS 10.14.4____
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by georgiik-welldone** [comment] 2019-05-16 12:07
The same happens to me

**Comment by paulpublic** [comment] 2019-05-21 12:58
+1

**Comment by AlexJerabek** [comment] 2019-05-24 21:55
@keyur32, Can you please take a look?

**Comment by akrantz** [comment] 2019-05-24 22:22
Please see the documentation:https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac#debugging-with-safari-web-inspector-on-a-mac

**Comment by paulpublic** [comment] 2019-05-27 08:23
@akrantz This should the correct configuration right?

```
> defaults read com.microsoft.Excel OfficeWebAddinDeveloperExtras
1
```

With that setting I can't open Inspect Element. I think this issue started after a macos update (i'm on 10.14.5)

**Comment by keyur32** [comment] 2019-05-30 00:17
Yup, we are investigating this. We will respond once investigation completes. Have added a bug label to this issue. Thanks!

**Comment by keyur32** [comment] 2019-05-31 07:39
Hey folks, sorry! we haven't been able to repro this across multiple machines on 10.14.4 and 10.14.5 -- it all works, when we set it. We may need to jump on a call. + @JuaneloJuanelo / @akrantz  to help coordinate that..

**Comment by jdrzj** [comment] 2019-07-25 17:41
Hi @keyur32, any update here? I'm on macOS 10.12.6, word 16.27, and I have the same problem. I'm happy to help you with debugging if you need anything.
edit:
My mistake didn't saw High Sierra requirement, after updating macOS to 10.13.1 it works. 👍 
_At the same time, I also cleaned cache._

**Comment by fraziermork** [comment] 2019-07-31 22:04
I'm also having this problem with mac OS 10.14.5 and outlook 16.27

**Comment by keyur32** [comment] 2019-08-07 17:01
Hey folks, can you verify your writes command was set:
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac?

thanks!

**Comment by georgiik-welldone** [comment] 2019-08-12 09:55
Still doesn't work

<img width="684" alt="Screenshot 2019-08-12 at 11 54 23" src="https://user-images.githubusercontent.com/20322794/62857467-0008d180-bcf8-11e9-8421-9540daed4674.png">

## Environment
MacOS 10.14.4 (18E226)
PowerPoint 16.27 (19071500)

**Comment by keyur32** [comment] 2019-08-12 21:49
Update: We think this is specific to the Mac App Store Build of Office, which currently doesn't support these flags.  To workaround this, you will need to get a non App Store build. You can get one by signing up for the developer program and getting a tenant: https://aka.ms/o365devprogram.

**Comment by kbrandl** [comment] 2019-09-02 21:36
Closing this issue, as it seems like @keyur32's most recent comment explains root cause and identifies a work-around. If you need further assistance with this issue, please comment here and we'll re-open it. Thanks!

**Comment by jdrzj** [comment] 2019-11-06 14:55
Hi, I have the same issue this time on macOS: 10.15 and word: 16.29

**Comment by codexeon** [comment] 2019-11-06 18:36
Did you install Office from the App Store? You will need to install it from https://www.office.com to get access to debug capabilities.

**Comment by Herz3h** [comment] 2020-03-23 06:04
@keyur32 can confirm using non app-store version shows the inspect element. Would be nice to have docs updated regarding this :)

**Comment by mscharlock** [comment] 2020-03-25 18:43
Re-opening and tagging @keyur32  and @RuoyingLiang

**Comment by keyur32** [comment] 2020-05-11 19:52
Yes, (sorry didn't see this one). Non app store version should have the ability to debug.

**Closed as completed by keyur32** 2020-05-11 19:52 UTC
Labels: Type: product bug, Area: add-ins platform, Resolution: has workaround

**Comment by tim-bai** [comment] 2023-01-25 02:49
use hombew to install office, it seems solve the problem, instead of joining developer program. :) 

`brew install --cask microsoft-office`
