### ISSUE TITLE
When using insertText() footnotes are being erased

### ISSUE THREAD

**Issue by bulgariamitko** [OfficeDev/office-js#2749] opened 2022-08-03 11:56 UTC
When I am using this code `paragraphs.items[h].insertText(newText, "Replace");` for example if I have any footnotes inside this paragraph there were deleted and I get a question marks where the numbers were before that.
This is the original text
![Снимка на екрана на 2022-08-03 13-52-20](https://user-images.githubusercontent.com/7221384/182601564-7474bd62-0cc8-446a-ac72-040dc12611da.png)

And this is the result
![Снимка на екрана на 2022-08-03 13-52-25](https://user-images.githubusercontent.com/7221384/182601600-e5f842d8-e475-40b7-bef0-1a6cbf6f3e97.png)

This is the code I am using
```
var paragraphs = body.paragraphs;
    var regexMoreSpaces = /;/g;
    context.load(paragraphs, "text, styleBuiltIn");
    await context.sync();
    if (paragraphs.items.length > 0) {
      for (var h = 0; h < paragraphs.items.length; h++) {
        console.log(paragraphs.items[h]);
        let text = paragraphs.items[h].text;
        let newText = text.replace(regexMoreSpaces, "");
        console.log(newText);

        paragraphs.items[h].insertText(newText, "Replace");
      }
    }
```

## Article URL
https://docs.microsoft.com/en-us/javascript/api/word/word.paragraph?view=word-js-preview#word-word-paragraph-inserttext-member(1)

## Issue
Footnotes are deleted and instead of the numbers next to the words in the paragraphs there are question marks.

**Comment by ElizabethSamuel-MSFT** [comment] 2022-08-03 16:25
@bulgariamitko Thanks for letting us know about this issue. Can you share a little more about your environment? Thanks.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

**Comment by ElizabethSamuel-MSFT** [comment] 2022-08-03 16:49
Transferring to the product repo for triage.

@bulgariamitko Can you provide the following additional info so the product team can triage and investigate?

## Context
How has this issue affected you? What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world.

## Useful logs
Please include any of the following logs that may help us debugging your issue.

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ElizabethSamuel-MSFT** [comment] 2022-08-03 16:53
@wangyun-microsoft Can you take a look? Thanks.

**Comment by JinghuiMS** [comment] 2022-08-04 00:55
@ElizabethSamuel-MSFT I will ping feature crew to take this issue. Thanks.
@bulgariamitko Thanks for reaching us. As ElizabethSamuel said, can we know which platform(Word Desktop, Word Online, Mac or iOS) you are seeing this issue? If you can provide a repro video, that will be helpful for us to better understand your scenario. Thanks!

**Comment by bulgariamitko** [comment] 2022-08-04 06:50
## Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
Host [Excel, Word, PowerPoint, etc.]: Word
Office version number: Microsoft Office Professional Plus 2016
Operating System: Windows 11 Pro, Bulgarian language pack
Browser (if using Office on the web): not using Office on the web

## Context
So what I was trying to do is to delete all additional spaces in Word like double or more spaces to convert them to one space. Or spaces that are put at the begging or the end of a paragraph to delete them using code. I wrote a simple code at the begging of my post. When using this I expected the numbers and the footnotes to be kept, but they turned to question marks and the footnotes were deleted. 

@ElizabethSamuel-MSFT , Sorry I do not know how to include a console log, I am using Office-js since 10 days ago :dagger: I am new to this :package: 
I already provided screenshots, if you need me to give you more I can. 
It is not happening on a particular file. It is happening on all files with footnotes. 

@JinghuiMS , if you need anything else from me let me know. And thanks for taking the time and look into the issue.

**Comment by bulgariamitko** [comment] 2022-08-05 13:49
After doing some more research I think the reason for this is another code, this one

```
/* Removes more then one space and converts it to only 1 space */
            var paragraphs = body.paragraphs;
            var regexMoreSpaces = /\s+/g;
            context.load(paragraphs, "text");
            await context.sync();
            if (paragraphs.items.length > 0) {
              for (var h = 0; h < paragraphs.items.length; h++) {
                let text = paragraphs.items[h].text;
                let newText = text.replace(regexMoreSpaces, " ");

                paragraphs.items[h].insertText(newText, "Replace");
              }
            }
```
This code is converting all spaces which are more then one to only one space in a document and I believe footnote numbers are counted as a space in Word and this code is messing it with the logic, but I will wait for your answer to confirm or deny this.

**Comment by xuruiyao-msft** [comment] 2022-08-08 07:02
@bulgariamitko @JinghuiMS Thanks for your update. And I can reproduce the issue locally.
I investigate the code in windows desktop. The insert footnote process is:
1,insert the reference mark (\x2) into the paragraph, which printed as question mark
2, insert the reference mark into the footnote pane at the bottom of the current page
3, insert space after the reference in front of footnote at the bottom of the current page
4, insert the text into the footnote box

How to display the footnote number?
1, UI loops to update the current visual text
2, if UI detect the reference mark \x2 (question mark), it will calculate the footnote order as num, and fetch the number format (1,2,3 or a,b,c, or i ii iii) to show on UI
3, once there's one new inserted footnote, the UI will recalculate the shown number format in paragraph

For now, I cannot figure out the root cause. But from the investigation, I infer that the footnote is deleted, and UI cannot figure out the footnote number format, so UI only shows footnote reference mark (\x2 i.e. question mark)
I will dig into this issue, any update will sync with you.

**Comment by xuruiyao-msft** [comment] 2022-08-08 07:59
@bulgariamitko Discussed with inner colleagues, the behavior is expected.  
The paragraph.insertText  method with replace option indeed deletes the original content include the footnote. So the footnote at the bottom of the page will disappear. 
The newText you fetched from the original paragraph actually is the type of text. It only includes the text format in which the reference mark is "\x2" (i.e. question mark) . The text format cannot include footnote body. So after insert the newText back into the original paragraph, it should be shown as question mark.

I think insertText method is not suitable for your situation. There's another workaround:
Suppose you want to replace the space in original paragraph, you can search the space " " in the paragraph and fetch all the ranges which include only the space, and just delete the range objects(i.e. delete all the spaces).

Here's the sample code:
async function replaceSpace() {
  await Word.run(async (context) => {
    var paragraph = context.document.body.paragraphs.getFirst();
    paragraph.load();
    await context.sync();

    let rangeCollection = paragraph.search(" ");
    rangeCollection.load();
    await context.sync();
    console.log("range.length:"+ rangeCollection.items.length);
    
    for (let i = 0; i < rangeCollection.items.length; i++) {
      var range = rangeCollection.items[i];
      range.delete();
    }
    await context.sync();
  });
}

This is the search api doc:
https://docs.microsoft.com/en-us/javascript/api/word/word.paragraph?view=word-js-preview#word-word-paragraph-search-member(1)

If you have any other question, feel free to let me know.

**Comment by bulgariamitko** [comment] 2022-08-08 08:02
@ahegongzhu , thanks for the replay. The problem is that I can't use RegEx inside the method search, right? Because this code will delete all the spaces that are more then 1 space, but what if I have 100 spaces and want to convert them to one space?

Update: Is there a way to actually use search with RegEx or find the range using RegEx?

Update2: The code that you provide is great, but it will actually delete all existing spaces in the document :dagger:

**Comment by xuruiyao-msft** [comment] 2022-08-08 08:43
@bulgariamitko would you please try this piece of code:

async function replaceSpace() {
  await Word.run(async (context) => {
    var paragraph = context.document.body.paragraphs.getFirst();
    paragraph.load();
    await context.sync();

    let rangeCollection = paragraph.search(" {2,}", {matchWildcards: true});
    rangeCollection.load();
    await context.sync();
    console.log("range.length:"+ rangeCollection.items.length);
    
    for (let i = 0; i < rangeCollection.items.length; i++) {
      var range = rangeCollection.items[i];
      range.insertText(" ", "Replace");
    }
    await context.sync();
  });
}

" {2,}" is a wildcard, and it searchs and matches the text range which there're at least two spaces. And iterate all the expected ranges and call the insertText(" ", "Replace") to convert them to only one space.


Feel fee to let me know if you have any other concerns. Thanks.

**Comment by bulgariamitko** [comment] 2022-08-08 10:23
@ahegongzhu , that is great that search support matchWildcards, but isn't that matchWildcards is limited and it is Office/Word strict version of RegEx. For example if I want to delete spaces at the the begging of every paragraph can I do it like that?
`let rangeCollection = paragraphs.items[h].search("^\s*", {matchWildcards: true});`
Because I can do it right now with
`let newText = text.replace(/^\s*/g, "");`
and I do not think this will work with the search method.

The main problem I have is that matchWildcards limits me from using the whole RegEx ability of the syntax. Is there more officiant way to find the range and then delete it using RegEx alone and not matchWildcards. Correct me if I am wrong.

**Comment by xuruiyao-msft** [comment] 2022-08-09 02:41
@bulgariamitko The matchWildcards is indeed the Office/Word strict version of RegEx. I'm afraid that Some RegEx is not supported in our JS library.

**Comment by bulgariamitko** [comment] 2022-08-09 07:15
@ahegongzhu So in my case if I would like to remove all spaces that are more then one in the document and spaces that are in front of the paragraph and after that. I think I can't use the matchWildcards and if I have a footnotes I can't use the insertText as well as it is removing my footnotes. So what is my solution in this case?

**Comment by xuruiyao-msft** [comment] 2022-09-02 09:31
@bulgariamitko 

1. For the spaces not at the beginnings and the endings, we can still use this piece of code below to convert multiple spaces to one space:
`let rangeCollection = paragraph.search(" {2,}", {matchWildcards: true});
rangeCollection.load();
await context.sync();
console.log("range.length:"+ rangeCollection.items.length);

for (let i = 0; i < rangeCollection.items.length; i++) {
  var range = rangeCollection.items[i];
  range.insertText(" ", "Replace");
}
await context.sync();`

2. For the spaces at the beginnings, would you please try this work-around:
`let range = par.getTextRanges([" "], false).getFirst();
    range.load();
    await context.sync();
    console.log("delete spaces at beginnings:" + range.text + "end");
    range.delete();
    await context.sync();`
I find the method "paragraph.getTextRanges" could also figure the "spaces" in table. Hope there're no tables at the beginning of your paragraphs.

3. For the spaces at the ends, would you please try  this piece of code:
`let par = context.document.body.paragraphs.getFirst();
    par.load();
    await context.sync();
    let text = par.text;

    if (text.endsWith(" ")) {
      let ranges = par.getTextRanges([" "], false);
      ranges.load();
      await context.sync();
      let endSpacesRange = ranges.items[ranges.items.length - 1].search(" {2,}", { matchWildcards: true }).getFirst();
      endSpacesRange.delete();
      await context.sync();
    }`

**Closed as completed** 2022-09-12 08:01 UTC
Labels: Needs: author feedback, Area: Word, Status: no recent activity
