### ISSUE TITLE
Using the latest Edge or Chrome, Outlook on the Web does not show dialogs by displayDialogAsync when displayInIframe is true.

### ISSUE THREAD

**Issue by t-miyake** [OfficeDev/office-js#2129] opened 2021-09-18 03:05 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook on the web
* Office version number: ______
* Operating System: Windows10
* Browser (if using Office on the web): Microsoft Edge Version 93.0.961.52 and Google Chrome Version 93.0.4577.82
 
## Expected behavior

This is the behavior with Outlook add in on send.

1. Click the Send Email button in Outlook on the web.
2. Outlook add in on send is executed and the dialog is displayed by Office.context.ui.displayDialogAsync.
This is an excerpt from the Office.context.ui.displayDialogAsync part.
```
Office.context.ui.displayDialogAsync(dialogPath, { height: 60, width: 65, promptBeforeOpen: false, displayInIframe: true },
function (asyncResult) {
dialog = asyncResult.value;
```

## Current behavior

The dialog is no longer displayed when using the latest stable versions of Edge or Chrome browsers.
 - Microsoft Edge version 93.0.961.52
 - Google Chrome version 93.0.4577.82

I have confirmed that the exact same add-in works fine in one previous version of Edge, 93.0.961.47.
Therefore, it could possibly be a problem on the browser side.

## Steps to reproduce

This problem occurs when displayInIframe is true in an add-in for Outlook on the web that runs when sending.

In the above code, asyncResult.status will be "success", but Dialog will not be displayed.
I set displayInIframe and promptBeforeOpen to false, Dialog will be displayed normally in a separate window. 

## Context

The Dialog is displayed before the mail is sent, so if it is not displayed, the mail can no longer be sent.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by t-miyake** [comment] 2021-09-18 13:08
I think this issue is due to the version of Outlook on the web, not the browser version.
I was mistaken because the timing was the same as the browser's version upgrade.

This issue occurs when version=20210913004.06.
However, if version=20210419002.11, this issue does not occur.

When I set displayInIframe to false, it works fine in 20210913004.06.
(The dialog is displayed correctly in a separate window, not inline.)
Therefore, I think 20210913004.06 may be the cause of the problem.

I have checked this version from the following URL.
![20210913004 06](https://user-images.githubusercontent.com/9583126/133889407-ff49a380-fa7d-4823-a195-d6e970ac50cb.png)

I have already added the targetOrigin property to messageParent and messageChild as described in this blog post.
(When tested with 20210913004.06. )
https://developer.microsoft.com/en-us/office/blogs/action-required-update-your-office-add-in-dialog-for-cross-domain-communication/

**Comment by t-miyake** [comment] 2021-09-19 08:39
I have tried a simple add-in for Outlook on the web for this issue.
Source code
https://github.com/t-miyake/OutlookOnSendAddinSample

Test Results
Both tests were conducted with Google Chrome version 93.0.4577.82.

Outlook on the web version 20210419002.11
(Only one of my PCs still loads 20210419002.11.)
1. Create a new email
	<img width="884" alt="Screenshot 2021-09-19 155932" src="https://user-images.githubusercontent.com/9583126/133920741-980dd85c-0d44-40bb-bcb3-d412e4703910.png">
2. Edit the email and click the Send button.
3.  The dialog is displayed inline by the add-in.
	<img width="893" alt="Screenshot 2021-09-19 155954" src="https://user-images.githubusercontent.com/9583126/133920792-f9908c5e-a9cb-4a4c-9b77-4b1dea4f8423.png">

Outlook on the web version  20210913004.06
1. Create a new email
	![Screenshot 2021-09-19 165909](https://user-images.githubusercontent.com/9583126/133920854-539f1dc1-d319-459c-b82e-0d7c24ae9d97.png)
2. Edit the email and click the Send button.
3. **The dialog will not appear and nothing will happen.**
	![Screenshot 2021-09-19 165923](https://user-images.githubusercontent.com/9583126/133920891-67bacf42-3fd3-4f31-9b98-40ca0273b385.png)

I think Outlook on the web version 20210913004.06 has some problems when displayInIframe is true.
Since this is not an Issue by browser or its version, if it is more appropriate to change this title, I will do so.

**Comment by neville-jones** [comment] 2021-09-20 00:30
Observing similar problem and similar workaround but the workaround is only effective if have both
`displayInIframe: false, promptBeforeOpen: false`
So far in our testing, the workaround allows for the dialog to be shown (not in an iframe) but the ability to communicate back to the parent seems broken, even when parent and dialog are in the same domain.


The problem also occurs in Firefox 92.0 so is not browser specific.

**Comment by stefanoslig** [comment] 2021-09-20 10:44
We also have the same issue! Most of the clients are affected by this. Is there any estimation on when there will be a fix for this issue?

**Comment by adamjlow** [comment] 2021-09-20 12:01
We are having the same issue too, its having a major impact on our users!

**Comment by pinchukdiana** [comment] 2021-09-20 13:56
@exextoc The issue has a major impact on our customers, can we get some attention to it, please?

**Comment by carlosb1504** [comment] 2021-09-20 16:07
Similar issues here but not exactly the same. We are able to get dialogs to show from the taskpane but, regardless of whether `displayInIframe` is set to true or false, we can't seem to get _any_ dialogs to display from the on-send hook, which is a major part of our implementation. 

Any updates from anyone at MS regarding this?

**Comment by AlexJerabek** [comment] 2021-09-20 16:18
Thank you for reporting this issue.

Assigning @exextoc to investigate and tagging @lliu113 to assist.

**Comment by rickgoud** [comment] 2021-09-20 17:35
@exextoc ; This change really braking every functionality that has pop-ups. Is this treated as a showstopper as it should? Seems that really no dialog works anymore?

**Comment by t-miyake** [comment] 2021-09-20 22:59
@exextoc This is a big issue for my clients (over 120,000 users).
If bug in the product, please announce it to users via Microsoft 365 Message center or Service health.

**Comment by neville-jones** [comment] 2021-09-20 23:29
Minor note, as indicated by @t-miyake you can use the following links to show the `displayDialogAsync` works with `displayInIframe: true` in the previous version, but which fails in current:

- Outlook on the Web previous - https://outlook.office.com/mail/deeplink/compose?popoutv2=1&version=20210419002.11
- Outlook on the Web current - https://outlook.office.com/mail/deeplink/compose?popoutv2=1&version=20210913004.06

**Comment by albeiroespitia** [comment] 2021-09-21 00:13
![its-been-84-years](https://user-images.githubusercontent.com/21091714/134093256-3665da32-5cec-400c-9271-211d7c49c7ee.jpg)

**Comment by adamjlow** [comment] 2021-09-21 08:22
@exextoc are you able to provide any updates on this issue?

I can't express how severe the impact is on our users, is there anything we can to do raise the priority of this?

**Comment by exextoc** [comment] 2021-09-21 08:52
Apologies for the inconvenience caused.

The issue has been fixed and is being pushed out to production. 
We will update the thread once the changes are pushed to 100% worldwide.

**Comment by adamjlow** [comment] 2021-09-21 11:01
@exextoc how's the push going, has it reached 100% as we're not seeing the update ourselves?

**Comment by bdubaut** [comment] 2021-09-21 12:27
> Apologies for the inconvenience caused.
> 
> The issue has been fixed and is being pushed out to production.
> We will update the thread once the changes are pushed to 100% worldwide.

@exextoc Hi, I have a question regarding the deployment of the fix: there are multiple Office365 update channels:
- current
- Monthly
- Semi-annual
- Semi annual (preview)
- Office insider program

Is the fix being deployed across all channels at once, or our customers that are on a semi-annual channel will need to wait until their next release to get the fix? As you might imagine, this would have a significant impact on our strategy of mitigating the issue should it persist with some customers.

Thanks!

**Comment by adamjlow** [comment] 2021-09-21 14:02
@exextoc really don't wish to be pushy but any update would be much appreciated.

**Comment by jgs-dev** [comment] 2021-09-21 17:56
@exextoc 🙏🙏🙏

**Comment by neville-jones** [comment] 2021-09-21 22:35
Testing has **not** been successful, but we are not sure if our test tenancy has received the fix.

When we compose a new message, and click the icon in upper right to "Open in new window", the message is opened at URL 
 https://outlook.office.com/mail/deeplink/compose?popoutv2=1&version=20210913004.08
 which is a different version compared to yesterday (https://outlook.office.com/mail/deeplink/compose?popoutv2=1&version=20210913004.06) but same problem as previously - the dialog is not shown.
 
 @exextoc - can you provide details of the version number where we would expect to see the fix?

**Comment by t-miyake** [comment] 2021-09-21 22:55
I am in a similar situation to @neville-jones.
However, my computer 20210913004.09 is loaded and still not working properly.

Now I have found that the following version exists.
20210913004.10

And I have also confirmed that it works fine if I use this URL
https://outlook.office.com/mail/deeplink/compose?popoutv2=1&version=20210913004.10

@exextoc
I hope the problem is completely fixed in 20210913004.10 or newer.
It would be great if you could let us know the current status and the progress of the rollout.

**Comment by neville-jones** [comment] 2021-09-21 22:58
Thanks @t-miyake  ; my testing agrees.

Using URL
https://outlook.office.com/mail/deeplink/compose?popoutv2=1&version=20210913004.10
the dialog is successfully displayed in iframe mode.

**Comment by IvanFranic** [comment] 2021-09-22 00:09
> Thanks @t-miyake ; my testing agrees.
> 
> Using URL
> https://outlook.office.com/mail/deeplink/compose?popoutv2=1&version=20210913004.10
> the dialog is successfully displayed in iframe mode.

Hi Neville. The issue still exists in our tenant. We are unable to send any emails using JnausSeal App in OWA

**Comment by stefanoslig** [comment] 2021-09-22 06:15
@neville-jones, `20210913004.08` is not the new version. The problem exists also in this version.

**Comment by exextoc** [comment] 2021-09-22 06:16
The issue has been fixed in production. Please let us know if it still reproduces.
Thanks a lot for the patience and we regret any inconvenience.

**Comment by t-miyake** [comment] 2021-09-22 06:35
@exextoc Thank you for fixing the issue!

**Comment by IvanFranic** [comment] 2021-09-22 22:56
> The issue has been fixed in production. Please let us know if it still reproduces.
> Thanks a lot for the patience and we regret any inconvenience.

Thank you. I can confirm that the issue is resolved now in our Tenant :-)

**Comment by AlexJerabek** [comment] 2021-09-23 18:01
Thanks for confirming @IvanFranic. I'll close the issue now, but please ping the thread or raise a new issue if anything is still amiss.

**Closed as completed by AlexJerabek** 2021-09-23 18:01 UTC
Labels: Area: Outlook, Type: product bug, Status: fixed
