### ISSUE TITLE
Office Add-in: Saving Custom Document Properties with Office js in Windows

### ISSUE THREAD

**Issue by soorajhealthplotter** [OfficeDev/office-js#973] opened 2020-02-07 15:56 UTC
When I create the excel using Office 365 for Windows (Word desktop) and invoke my addin i have the added custom properties. When i close the excel file it will prompt for **save** or **Dont save**.If  i am selecting **Dont save** custom properties are not getting saved into the custom properties collection.if selecting **save** the custom properties are saved. However the  properties get saved when the document is created using Office Online. But if i save the workbook manually before closing i am able to retrieve the custom properties
## Expected Behavior

When i add the custom properties using add in even if i dont save the Excel file the custom properties should be saved

## Code to create custom property

 Excel.run((context) ->
      customDocProperties = context.workbook.properties.custom
      work_book = context.workbook
      d = $scope.generateUUID()
      customDocProperties.add("workbook_identifier", d)
      customProperty = customDocProperties.getItem('workbook_identifier')
      customProperty.load 'key, value'
      work_book.load 'name'
      work_sheet = context.workbook.worksheets.getActiveWorksheet()
      work_sheet.load 'id'
      work_sheet.load 'name'
      context.sync().then ->
        $scope.workbook = customProperty.value
        $scope.worksheet_id = work_sheet.id
        $scope.workbook_name = work_book.name
        $scope.worksheet_name = work_sheet.name
        return
    ).catch (error) ->
      console.log 'Error: ' + error 

## Code to read custom property

Excel.run((context) ->
      work_book = context.workbook
      customDocProperties = context.workbook.properties.custom
      customProperty = customDocProperties.getItem('workbook_identifier')
      customProperty.load 'key, value'
      work_sheet = context.workbook.worksheets.getActiveWorksheet()
      work_sheet.load 'id'
      work_sheet.load 'name'
      work_book.load 'name'
      context.sync().then ->
        $scope.workbook = customProperty.value
        $scope.worksheet_id = work_sheet.id
        $scope.workbook_name = work_book.name
        $scope.worksheet_name = work_sheet.name
        return
    ).catch (error) ->
        console.log("------------error-------")

**Comment by lumine2008** [comment] 2020-02-10 05:21
Thanks, @soorajhealthplotter for your report. The API behavior is as same as VBA and UI. Excel online autosave is on, so the workbook will be saved automatically in Excel Online, but in Windows, I think you are accessing the workbook in a local file and autosaved was turned off. and user click dont save the workbook when a save dialog is opened. so it should not save the workbook. which is by design. 
 
To save the custom property, I would suggest that you could turn the autosave on, 
another solution is that you could call workbook.save() after the custom property was added. 

Note workbook.save is  a preview API, it would be ready soon

**Comment by soorajhealthplotter** [comment] 2020-02-11 05:01
Really i got troubled i was not knowing what the issue may be.
I appreciate for your update regarding issue.
Thank you

**Comment by lliu113** [comment] 2020-02-12 01:46
@soorajhealthplotter - it sounds like the issue is resolved so I will go ahead and close this. Please resurrect if you have any additional questions - thanks!

**Closed as completed by lliu113** 2020-02-12 01:46 UTC
Labels: Area: Excel
