### ISSUE TITLE
Allow Office 2016 MSI files to load 16.01 files rather than 16.00

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-js#138] opened 2018-05-16 22:11 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

**Comment by ndreisg** [comment] 2018-06-20 08:45
@Zlatkovsky Hi, any updates on this?

Also you mentionend in #136 that we could also convince Office 2016 MSI to load 16.01 files with an update. We suggested our customer to install the following update: https://support.microsoft.com/en-us/help/4018369/may-1-2018-update-for-office-2016-kb4018369
Unfortunately that update did not have the desired effect.
Could you please find out which update we need?

**Comment by ndreisg** [comment] 2019-04-03 10:59
Hi, are there any news on this issue?
We are receiving more and more error reports from customers that turn out to be caused by this issue. We always advise them to install Office Updates, but many users state that they have installed the latest updates and still get the same errors.

**Comment by Zlatkovsky** [comment] 2019-04-09 01:10
Hi @ndreisg ,
Assigning this issue to @wandyezj , since it falls more within his ownership.  However, in terms of "many users state that they have installed the latest updates and still get the same errors", I should probably clarify that just loading the 16.01 vs 16.00 files likely wouldn't help there.  The capabilities of the host application (e.g., what APIs they expose) are still determined by the host application, not the JS file.  So if you call into an API that's part of ExcelApi 1.3, this will fail on Office 2016 MSI no matter which JS file was loaded.  The JS file has a couple of small bug-fix tweaks, which is why this work item was originally created -- but most of those should be invisible for you.

**Comment by ndreisg** [comment] 2019-04-09 04:56
Thanks for assigning.
I am aware of that and of course I always check if the required API is available. The problem most of our users have is the one from the originating issue #136.

**Comment by ndreisg** [comment] 2019-04-09 04:56
Thanks for assigning @Zlatkovsky .
I am aware of that and of course I always check if the required API is available. But the problem most of our users have is with the `Range.select` function (which is marked as API 1.1 according to https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_OpenSpec/reference/excel/range.md and also quite important for our Add-In).

```
Error at Range.select
AccessDenied: You cannot perform the requested operation.
at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.00.js:19:142076)
at yi (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.00.js:19:155894)
at st (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.00.js:19:155981)
at d (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.00.js:19:155801)
at c (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.00.js:19:154387)
```

**Comment by Zlatkovsky** [comment] 2019-04-17 00:41
@ndreisg, that's very strange about `range.select`.  I would encourage you to go ahead and open a separate issue for this, and also include info for what is the Office host version.
(Sorry for the delay in replying; I was on vacation).

**Comment by ndreisg** [comment] 2019-04-17 12:14
When I tried to reproduce this issue in a minimal sample, I found out that it only occurs when range.select is chained to the promise with `.then`
See the new issue #480

**Comment by ElizabethSamuel-MSFT** [comment] 2021-03-23 18:02
@mattgeim / @wandyezj Has this issue been resolved?

**Comment by tonykcn** [comment] 2021-12-26 03:20
@wandyezj  @Zlatkovsky , we still met this issue,  May I know how to resolve this issue?  MSI office 2016 couldn't load 16.01.

**Closed as not planned** 2024-03-25 20:13 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: add-ins platform
