### ISSUE TITLE
Formula referencing Entity's property has different format in excel web when selected using card and insert icon

### ISSUE THREAD

**Issue by didu9898** [OfficeDev/office-js#4190] opened 2024-02-28 14:14 UTC
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: build 16.0.17421.42304
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome

## Expected behavior
In excel web, the formula referencing the property is generated must be same when selected by either card or 'insert data' in both desktop or web excel.

## Current behavior
- In excel web, when property is selected using "insert data" (https://github.com/OfficeDev/office-js/assets/105494296/74f21f4f-cc15-4703-b234-feacaec6192e), in the formula referencing that property, the property key is enclosed using square brackets e.g. =A1.[prop1] and when the same property is selected using card, there are no square brackets e.g. =A1.prop1
- In excel desktop, in both scenarios, the formula referencing the property does not contains square brackets i.e. when property is selected using card or insert data, =A1.prop1 is generated

## Steps to reproduce
1. Open excel web and register the following in script lab:
/**
 * Get a dynamic array with an entity and text values.
 * @customfunction
 * @returns {any[][]} A dynamic array with multiple results.
 */
function GetEntity(): any[][] {
  const entity: Excel.EntityCellValue = {
    "type": "Entity",
    "text": "PropEntity",
    "properties": {
      "prop1": {
        "type": "String",
        "basicValue": "prop 1",
      },
      "prop2": {
        "type": "String",
        "basicValue": "prop 2",
      },
      "prop3": {
        "type": "String",
        "basicValue": "prop 3",
      },
      "prop4": {
        "type": "String",
        "basicValue": "prop4"
      }
    },
    "layouts": {
      "compact": {
        "icon": "collections"
      },
      "card": {
        "title": "Entity",
        "sections": [
          {
            "layout": "List",
            "title": "Intrinsic properties",
            "collapsible": true,
            "collapsed": false,
            "properties": [
              "prop1", "prop2", "prop3", "prop4"
            ]
          }
        ]
      }
    }
  };
  return [[entity]];
}
2. Select cell A1 and enter the above formula to render entity. 
3. Insert a property using "insert data". Select the cell containing the property and notice the formula which will be =A1.[prop1]
3. Clear B1 and insert the same property using card and in this case the formula will be =A1.prop1

**Note:** By following the same steps in excel desktop, in both scenarios, the formula referencing the property will be =A1.prop1

## Important links 
1. Web behavior: [https://github.com/OfficeDev/office-js/assets/105494296/08dcdaaf-38dd-41da-9c0a-1db6fb5af6cd](https://github.com/OfficeDev/office-js/assets/105494296/08dcdaaf-38dd-41da-9c0a-1db6fb5af6cd)
2. Desktop behavior: [https://github.com/OfficeDev/office-js/assets/105494296/6aa15266-021c-42ed-91fe-30d44049837a](https://github.com/OfficeDev/office-js/assets/105494296/6aa15266-021c-42ed-91fe-30d44049837a)
3. ScriptLab Snippet: [https://gist.github.com/didu9898/53b812900565f7a257590b426fc30223](https://gist.github.com/didu9898/53b812900565f7a257590b426fc30223)

**Comment by xai-msft** [comment] 2024-02-29 06:07
Hi @didu9898 , thank you for contacting us. The brackets are optional for field names with only letters and numbers, and are required for field names containing something like spaces " " or dot ".". This does not affect the resulting value and you can use either version.

**Comment by xai-msft** [comment] 2024-02-29 06:26
Internal track number: 8792358

**Comment by didu9898** [comment] 2024-02-29 08:13
Hi @xai-msft, I got the purpose of brackets but my concern it that bracklets are only appearing in excel web when property is selected by "insert data" icon and not in other scenarios and not even in desktop. Also I think it is not necessary when field names does not have space or dot. I expect that there must be similar behavior for same field names/property.

**Comment by xai-msft** [comment] 2024-02-29 08:40
Yes, we have added it to our backlog.

**Comment by xai-msft** [comment] 2024-06-13 02:46
Hi, after internal triage the issue is considered to have low priority and won't be fixed for now, since there is no functional impact.

**Closed as not planned by xai-msft** 2024-06-13 02:46 UTC
Labels: Needs: attention :wave:, Area: Excel
