### ISSUE TITLE
OnNewMessageCompose does not trigger on Outlook for Mobile IOS

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#3535] opened 2023-07-25 02:28 UTC
Hello, we are trying to use the OnNewMessageCompose, however we have discovered it does not work on Outlook for Mobile IOS
I have used the sample : [Link](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/mobile-event-based) 

## Expected Behavior
 From the documentation OnNewMessageCompose is supported on Outlook for Mobile for both Android and IOS, OWA, Outlook for Desktop and Outlook for MAC

## Current Behavior

**The OnNewMessageCompose does not seem to work on Outlook for Mobile IOS**. It works fine on Outlook for Mobile Android, OWA, Outlook for Desktop and Outlook for MAC

## Steps to Reproduce, or Live Example

Use the document to create a app which uses OnNewMessageCompose event, ensure that MobileFormFactor is added to the manifest. You can use the link to reproduce the issue: [https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/mobile-event-based](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/mobile-event-based)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______ IOS
* Host [Excel, Word, PowerPoint, etc.]: ______Outlook
* Office version number: ______4.2327.0 (Outlook version on IOS)
* Operating System: ______IOS 16.5.1(c)

## Useful logs
Screenshot:

Outlook for Mobile IOS (not working):
![image](https://github.com/OfficeDev/office-js/assets/80862413/bf773a06-1345-4c5c-a71d-63520fded894)

Outlook for Mobile Android (working):
![image](https://github.com/OfficeDev/office-js/assets/80862413/50b67001-fb3c-4539-a81b-8d03c5de0101)

Outlook for desktop (working):
![image](https://github.com/OfficeDev/office-js/assets/80862413/bfd024f4-06fa-454d-8463-1c6606b2a370)

Outlook for Mac (working):
![image](https://github.com/OfficeDev/office-js/assets/80862413/15256d76-185b-40c6-8ca1-b591cc04bd8f)

OWA (working):
![image](https://github.com/OfficeDev/office-js/assets/80862413/678c8dfc-9cd1-4d36-ada0-4b27cedd72df)

**Comment by exextoc** [comment] 2023-07-25 08:53
Hi @avisheknand, the issue is there because iOS is not fully rolled out yet. iOS changes for OnNewMessageCompose will be fully available latest by end of August 2023. Android is fully available as of now. Thanks!

**Comment by avisheknand** [comment] 2023-08-03 00:08
Thanks @exextoc . Will wait for the IOS rollout

**Comment by t4rzsan** [comment] 2023-08-28 17:48
Hi @avisheknand,
Any news on when iOS will be fully rolled out?  Thanks!

**Comment by avisheknand** [comment] 2023-08-29 10:01
Hello @t4rzsan, i have been waiting for this all this while. @exextoc , any updates on this would be appreciated!

**Comment by exextoc** [comment] 2023-09-18 09:24
We observed some issues during internal testing, due to which iOS changes are paused. Will update when iOS changes are rolled out fully. Currently there is no tentative timeline.

**Comment by exextoc** [comment] 2023-09-18 09:25
Closing this issue for now.

**Closed as completed by exextoc** 2023-09-18 09:25 UTC
Labels: Area: Outlook, Resolution: question answered

**Comment by bogdanst24** [comment] 2023-10-23 14:56
@exextoc is there any update on iOS?

**Comment by fedeisas** [comment] 2023-11-16 19:39
@exextoc we're also running into this. Any ETAs? Thanks 🙏🏽!

**Comment by t4rzsan** [comment] 2024-02-19 07:40
This [article](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/mobile-event-based) now says that it is working for iOS.  Am I the only one who still can't get an add-in to activate on iOS?

**Comment by Usman1104** [comment] 2025-02-05 15:08
Hi, can anyone help me as my signature addin is not working on mobile devices?

**Comment by Usman1104** [comment] 2025-02-05 15:08
@avisheknand
