### ISSUE TITLE
Outlook Add-in Pane Scroll Issue: Header is always included in scrollable content with iframe, hiding content below the fold (Mac, PC, Web)

### ISSUE THREAD

**Issue by parlato-vooma** [OfficeDev/office-js#5052] opened 2024-11-06 19:43 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Reports on Mac and PC desktops, and on both Outlook web (outlook.live.com) as well as some reports on Outlook desktop for PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Mac OS Sierra in addition to Windows (reports from our customers vary across operating systems)
* Browser (if using Office on the web): Chrome 130 and Chrome 129, at least. Edge w/ Chromium 130
 
## Expected behavior
When opening a simple add-in that fits within the height of the screen (e.g. single, un-stylized div with some text), the add-in should not be scrollable. The scrollable area should only include the iframe, and the Office provided header should be sticky.

## Current behavior
When opening a simple add-in that fits within the height of the screen, the add-in is scrollable, seemingly with the height of the header outside the iframe added to the scrollable area. The scrollable area includes the header, and the header scroll away. 

## Steps to reproduce

1. Open any add-in
2. Note the entire pane is scrollable, not just the iframe, and the user can scroll to the point the Office provided header (outside the iframe) is not visible

## Link to live example(s)
* Search for and install the "Vooma" add-in. Issue is visible on the log in page of the add-in.

# Provide additional details
### Screen recording of issue
https://github.com/user-attachments/assets/31b8abfd-451f-4c1a-8575-4c51f8ebfae8

## Context
This issue is causing users of our add-in to not be able to find actions and content that are rendered below the fold. We have no ability to scroll the container automatically as it exists outside the iframe.

**Comment by Oleg-O** [comment] 2024-11-09 00:22
I see a mention of reports on "Outlook desktop for PC". I assume this would be for new Outlook, and not the classic Outlook - can you please confirm? If so, this post is effectively a duplicate of #5051.

**Comment by parlato-vooma** [comment] 2024-11-09 00:34
> I see a mention of reports on "Outlook desktop for PC". I assume this would be for new Outlook, and not the classic Outlook - can you please confirm? If so, this post is effectively a duplicate of #5051.

I think that's right, they seem identical to me.

**Comment by Oleg-O** [comment] 2024-11-10 22:26
Thanks for confirming, let's close this as duplicate of #5051

**Closed as not planned** 2024-11-10 22:31 UTC
Labels: Area: Outlook, Resolution: duplicate
