### ISSUE TITLE
Several properties are missing from window.Office.context.mailbox on "New Outlook" for Mac

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-js#1400] opened 2020-09-21 18:29 UTC
I've enabled "New Outlook" for Mac and found that several properties are missing from `window.Office.context.mailbox`, and some of them have different values.

| Property | "Old Outlook" | "New Outlook" |
| ------------ | ------------- | ------------- |
| `window.Office.context.mailbox.userProfile.accountType` | `outlookCom` | `office365` |
| `window.Office.context.mailbox.item.itemId` | `AQMk...E0AAAA=` | `""` |
| `window.Office.context.mailbox.item.internetMessageId` | `CA+E...gmail.com` | `<CA+E...gmail.com>` |
| `window.Office.context.mailbox.restUrl` | `https://outlook.office.com/api` | `""` |
| `window.Office.context.mailbox.item.attachments[0].id` | `AQMk...VD/y9I...RA98=` | `362{00000000-0000-0000-F955-000000000000}` |
| Supported Outlook API version | 1.8 | 1.7 |

## Expected Behavior
Properties listed above to be the same for "Old" and "New Outlook"

## Current Behavior
Properties have different values in "Old" and "New Outlook"

## Steps to Reproduce, or Live Example
1. Install Outlook add-in with `ReadWriteItem` permission level.

## Context
This breaks Jira Cloud for Outlook add-in, we can't fetch attachments (mainly because there's no `restUrl`).

## Your Environment
* Platform: Mac
* Host: Outlook
* Office version number: 16.42 (20091509) with "New Outlook" enabled
* Operating System: macOS Catalina v10.15.6

## Useful logs
Same manifest as here https://github.com/OfficeDev/office-js/issues/1384#issuecomment-695010631

**Comment by exextoc** [comment] 2020-09-23 18:37
Hi @modestfake , thanks for reporting these issues.

Addressing each issue individually:

**1. mailbox.item.itemId is empty** - we have already fixed this issue for Gmail accounts. We'll let you know when the fix is in Insider Fast.
**2. mailbox.item.internetMessageId is different** - we are able to reproduce this bug. We have added it to our backlog.
**3. mailbox.restUrl is empty** - We are aware of this issue and it's already in our backlog. We'll let you know when we have fixed it.
**4. attachmentId is different** - same here, we are aware of this issue, and it is already in our backlog.
**5. userProfile.accountType is different** - we are able to reproduce this issue, and it is due to subtle changes in New Outlook. Could you explain if this is problematic for a scenario you're trying to accomplish?

**Comment by modestfake** [comment] 2020-09-23 19:43
Hi @exextoc 
Thank you for detailed reply. I forgot to mention that I was testing all of these fields on `xyz@outlook.com` email. So
1. Yeah, I recently reported that issue for Gmail but I can see the same issue on `@outlook.com` email on "New Outlook".
5. It's not a problem. We use this field for analytics, but if this gonna change, that's alright.

**Comment by exextoc** [comment] 2020-10-23 07:49
We have fixed the RestUrl bug and the fix should be available in next monthly build. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks.

**Comment by exextoc** [comment] 2020-10-30 08:54
We have  fixed the issue with userProfile.accountType. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks.

**Comment by exextoc** [comment] 2020-11-17 05:12
We have fixed the issue with attachmentId. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks.

**Comment by modestfake** [comment] 2020-11-20 10:37
Hi @exextoc 
I'm on the latest Outlook 16.44 (20111807). I can see that the issue with `attachmentId` has been resolved but `restUrl` is still empty. Can it be a regression?

**Comment by modestfake** [comment] 2020-11-25 12:49
Hey @exextoc 
Just installed the latest Outlook 16.44 (20112309). I can see `restUrl`, but now `attachmentId` is different for files in old and New Outlook 😄  
 Here's an example:
**Old Outlook**
```
AQMkADAwATNiZmYAZC0xY2YzLWZmAGMxLTAwAi0wMAoARgAAA7Kq8bcvYr5Lqh+n9WEcAJsHAOCh7CsbJAZKppYW8fssymkAAAIBDAAAAOCh7CsbJAZKppYW8fssymkAAVJWaaUAAAABEgAQAD/X1wATm2ewSLOeBnuu4V21
```

**New Outlook**
```
AAkALgAAAAAAHYQDEapmEc2byACqAC/EWg0A4KHsKxskBkqmlhbx+yzKaQABQnmoSwAAARIAEAA/19cTm2ewSLOeBnuu4V21
```

**Comment by exextoc** [comment] 2020-11-27 08:06
Apologies. It is mistake from our side to notify. Fix is rolling out slowly. We will update you once fix is available to all users world-wide. Thanks for your patience.

**Comment by exextoc** [comment] 2020-12-26 10:25
Hey @modestfake ,

The issue has been fixed and we have confirmed the fix on Outlook build 16.45 (20122006). Please do confirm that you see it working for you as well.

**Comment by modestfake** [comment] 2020-12-28 14:26
Hi @exextoc 
Thank you! I've tested it and yes, it works now.
The only difference between the "old" and "new" Outlook is the "Supported Outlook API version" (1.8 on "old" Outlook and 1.7 on "new" one) but seems like it doesn't affect our add-in, so I'm closing this issue. Thank you again for the great work!

**Comment by m-pd** [comment] 2021-07-09 09:54
Hi.

I'm seeing Office.context.mailbox.item.itemId as empty with the New Look Outlook for Mac. It is populated for the "old" Outlook for Mac.

**Comment by exextoc** [comment] 2021-07-09 10:47
@m-pd
Could you please provide the following details?
- In which version of Outlook Mac are you seeing this issue?
- On which surface is the API being invoked?
- Please repro this issue in New Outlook Mac and then generate the Diagnostics ID by navigating to Help-> Collect Diagnostics and share the same.

**Comment by m-pd** [comment] 2021-07-09 11:03
@exextoc 
- Version 15.50 (21061301)
- Office365
- Diagnostics ID - PANQ3SSR

**Comment by exextoc** [comment] 2021-07-13 07:04
Can you please share the network trace and a test account where this issue is reproducible with us to proceed further?

**Comment by m-pd** [comment] 2021-07-15 09:33
@exextoc 

There is no network trace. We are just accessing `Office.context.mailbox.item.itemId`.

Unfortunately, we cannot provide a test account at this moment.

**Comment by m-pd** [comment] 2021-07-20 14:56
@exextoc 

I have written the contents of the `Office` object to the developer console and screen grabbed the `Office.context.mailbox.item` property. As you can see, `itemId` is empty. In the background you can see that Outlook for Mac is in "New outlook" mode.

![image](https://user-images.githubusercontent.com/48472967/126347898-5dae486f-98be-4a93-9784-0f8f5fdd35ff.png)

Below is `item` in "classic" mode. `itemId` is populated with a value.

![image](https://user-images.githubusercontent.com/48472967/126347750-fbabe023-2d49-45bd-83f0-88312ca39fc5.png)

**Comment by exextoc** [comment] 2021-07-29 10:36
@m-pd Please run these commands on terminal and restart Outlook. 

defaults write com.microsoft.Outlook SuppressO365AutodiscoverOverride 0
killall cfprefsd

**Comment by m-pd** [comment] 2021-07-30 09:21
@exextoc 

Still the same.

**Comment by exextoc** [comment] 2021-08-02 10:02
@m-pd Can you please run the comand shared above and again generate Diagnostic Id like you did before and share it with us?

**Comment by m-pd** [comment] 2022-03-01 10:03
Hi @exextoc Very sorry for the late reply. The problem still exists after running the commands. This is the diagnostics id - 7XFACQRS

**Comment by exextoc** [comment] 2022-03-14 13:07
@m-pd All the issues mentioned above are already fixed. Could you please update your Outlook Mac to version 16.58 and try it again.

**Comment by exextoc** [comment] 2022-03-14 13:14
Remarks per issue as below

Property | "Old Outlook" | "New Outlook" | Remarks
-- | -- | -- | --
window.Office.context.mailbox.userProfile.accountType | outlookCom | office365 | This is as per the design
window.Office.context.mailbox.item.itemId | AQMk...E0AAAA= | "" | The item id is not available and it is present only for a read item
window.Office.context.mailbox.item.internetMessageId | CA+E...gmail.com | <CA+E...gmail.com> | The correct behavior is to encapsulate the id in the <> brackets
window.Office.context.mailbox.restUrl | https://outlook.office.com/api | "" | The restUrl is now available
window.Office.context.mailbox.item.attachments[0].id | AQMk...VD/y9I...RA98= | 362{00000000-0000-0000-F955-000000000000} | The attachment id now comes in the same format as old UI
Supported Outlook API version | 1.8 | 1.7 | The Outlook API version currently supported is 1.10 in the new UI

**Comment by GrumpyAL** [comment] 2022-03-14 13:29
Hi,

Just to clarify, are you saying that empty itemID should also be fixed in 16.58 for 365 accounts (or just Gmail accounts)?  Or is the cause of the issue reported in #2381 still unknown since we haven't been able to reproduce outside of specific environments?

**Comment by exextoc** [comment] 2022-03-15 08:18
It should be fixed for all the accounts.
Also, for issue #2381 do you have a consistent repro? If yes, would you be able to share a test account with us?

**Comment by GrumpyAL** [comment] 2022-03-16 17:59
Hi,

Unfortunately the few environments we have a consistent repro on we do not own and have been unable to find someone willing or able to give a test account.  We are also trying to see if someone will test with one of our dev accounts to help us rule out a tenant setting vs a Mac client setting.

I will follow-up to see if those who have had the issue can test on 16.58.

**Closed as completed** 2022-03-23 20:00 UTC
Labels: Needs: author feedback

**Comment by GrumpyAL** [comment] 2022-03-28 17:30
Related to the specific issue in https://github.com/OfficeDev/office-js/issues/2381 we had an impacted organization test on 16.59 and they are still reporting the issue with that build.  We  are still attempting to get a test account from an impacted organization but so far no update on that.

**Comment by DustinBrungart** [comment] 2022-03-29 14:17
We also have a customer experiencing the issue defined in #2381 on 16.59 and are in the process of getting consent to share the data we've collected now.

**Comment by cristos-codence** [comment] 2022-05-12 13:54
I'm one of the affected customers, and can reliably reproduce the issue in my environment ("New Outlook", v16.61 / O365 subscription). I've run the commands from https://github.com/OfficeDev/office-js/issues/1400#issuecomment-889005881 and submitted diagnostics (`KM7JZZUD`). Is there any other info I can provide to help get to the bottom of this?

**Comment by cristos-codence** [comment] 2022-05-20 14:13
@GrumpyAL @exextoc just following up; since I can consistently reproduce the issue, anything I can do to help?

**Comment by m-pd** [comment] 2022-06-10 15:52
@exextoc Still seeing empty `itemId` - Outlook for Mac Version 16.61.

This is only occurring on our hybrid exchange. The problem doesn't occur on our 365 exchange.

Using our diagnostics tool we see this info for the hybrid exchange:

![image](https://user-images.githubusercontent.com/48472967/173105915-ff3621f0-1080-4fec-b79d-db9b9d5a261e.png)

and for the 365 exchange we see this:

![image](https://user-images.githubusercontent.com/48472967/173314215-afeab254-b3ff-4cdb-aaa1-f8cfee5c3d66.png)

Not sure if that helps.

**Comment by GrumpyAL** [comment] 2022-06-24 18:57
Hello,

We actually just saw this again on one of our production machines.  The user restarted and the issue didn't clear.  We could see the itemID was returning empty.  We had them add a second account on a dev tenant and the issue persisted there so I don't believe it was related to any tenant mailbox settings (also I'm not aware of other user's in our production environment having this problem).

In this case, we were able to work around it by flipping back to Legacy Outlook and then flipping to "New Outlook."  This caused the itemID to start populating again and we can no longer reproduce.  This doesn't match completely with what we've seen before because we haven't been able to restore the itemID by flipping from New to Legacy and back.

This was Outlook 16.62 and was a Mac store build (no no OfficeWebAddinDeveloperExtras flag).

**Comment by jjustus** [comment] 2022-06-30 19:11
I can also confirm this behavior is still the same (i.e, missing itemId, etc...) for Mac Outlook version 16.62 when running in "New Outlook" mode.

**Comment by m-pd** [comment] 2022-07-11 13:33
> @m-pd Please run these commands on terminal and restart Outlook.
> 
> defaults write com.microsoft.Outlook SuppressO365AutodiscoverOverride 0 killall cfprefsd

Hi @exextoc This has now finally been resolved. Apparently this:
`<key>SuppressO365AutodiscoverOverride</key>`
was in our profiles and set to true.

When you asked me to run the above command apparently it couldn't override the profile setting. Also, what we discovered was that even if the value is true or false we were seeing the problem. We have had to remove the key from the profiles to remove the problem (this is valid for us and won't have any ramifications.

**Comment by GrumpyAL** [comment] 2022-07-12 13:39
@m-pd thank you!  I have been unable to reproduce this issue in my dev environment (or prod for that matter).  Until now.  Adding that key has caused the itemID (and other) properties to go missing.  I can switch Outlook for Mac back to Legacy and the issue goes away, but when I switch back to "New" it returns.  This is the same behavior we were seeing for some of our customers.

I am testing on 16.62.  So far, if I set the key to 0 it's fixing the issue for me, I'm not having to remove it completely.

**Comment by m-pd** [comment] 2022-07-13 15:39
@GrumpyAL 
The docs show the key value should be `true` (or `false`). It's possible `0` is invalidating the key and that is why it works for you.
https://docs.jamf.com/technical-papers/jamf-pro/microsoft-office/10.18.0/Microsoft_Outlook_Default_Preference_Keys.html

**Comment by cristoslc** [comment] 2022-07-14 15:09
Confirmed I had that key set to 0, and also tried removing it from the plist.  Issue persists in both cases in my environment.

**Comment by cbishop-fv** [comment] 2023-02-10 20:27
I have many users on 16.69.1 and itemId is empty using new outlook. Is something else needed to fix other than updating outlook client version?

Tested degbug on this in a test env. we check itemId to determine if the user is in read or compose mode. You can see it thinks the user is in compose mode and tried to call a function that it cant because the user is in read mode.

We could work around this by checking another value or function but we do also use itemId all over our app to interact with the email.

![image](https://user-images.githubusercontent.com/56599161/218202863-953c048c-615e-4e62-bfd7-f946749cb624.png)

![image](https://user-images.githubusercontent.com/56599161/218205774-b347967c-b936-4d96-81ac-542a020d764a.png)


![image](https://user-images.githubusercontent.com/56599161/218205801-90b6fdb4-fd7b-4296-9abb-5afadf18803f.png)


We tried to run these but that didn't work and I don't feel that's a great solution to pass on to non technical users.
```
run these commands on terminal and restart Outlook.

defaults write com.microsoft.Outlook SuppressO365AutodiscoverOverride 0
killall cfprefsd
```

**Comment by exextoc** [comment] 2023-02-16 11:01
Hey @cbishop-fv ,

This issue has been resolved and is no longer reproducible for us. If you still see this issue, please run a diagnostics log for us, and share the diagnostics ID with us on this thread. To do this, after you've reproduced this issue, click Help -> Collect Diagnostics.

**Comment by andmaz** [comment] 2023-05-11 16:17
Could you please share the version number where this issue was fixed?
Still facing an empty itemId on 16.72.3 (23043001), but it's not stable

**Comment by johnthad** [comment] 2024-05-06 20:39
> Hi @modestfake , thanks for reporting these issues.
> 
> Addressing each issue individually:
> 
> **1. mailbox.item.itemId is empty** - we have already fixed this issue for Gmail accounts. We'll let you know when the fix is in Insider Fast. **2. mailbox.item.internetMessageId is different** - we are able to reproduce this bug. We have added it to our backlog. **3. mailbox.restUrl is empty** - We are aware of this issue and it's already in our backlog. We'll let you know when we have fixed it. **4. attachmentId is different** - same here, we are aware of this issue, and it is already in our backlog. **5. userProfile.accountType is different** - we are able to reproduce this issue, and it is due to subtle changes in New Outlook. Could you explain if this is problematic for a scenario you're trying to accomplish?

Any word on fixing internetMessageId? I've tried it again today using the [Build your first Outlook add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator) demo and changing `item.subject` to `item.internetMessageId` in `src/taskpane/taskpane.js`, line 22. It is also empty when I run the demo in a browser. The value is empty. Without an internetMessageId to pass, how can an add-in tell a server side MS Graph app (in Java) which message is to be opened?
