### ISSUE TITLE
[Outlook] EWS GetAttachment returns an ErrorInvalidAttachmentId error

### ISSUE THREAD

**Issue by splinter** [OfficeDev/office-js#431] opened 2019-03-18 05:45 UTC
We randomly encounter  scenarios (at least it appears random)  where GetAttachment calls made to the EWS SOAP API
return an attachment not found error.

## Expected Behavior
The GetAttachment SOAP request should return the contents of the requested attachment.

## Current Behavior
When fetching attachments we recieve the following error for some files:

```
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <h:ServerVersionInfo MajorVersion="15" MinorVersion="20" MajorBuildNumber="1709" MinorBuildNumber="13" Version="V2018_01_08" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
    </s:Header>
    <s:Body>
        <m:GetAttachmentResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
            <m:ResponseMessages>
                <m:GetAttachmentResponseMessage ResponseClass="Error">
                    <m:MessageText>The specified attachment Id is invalid.</m:MessageText>
                    <m:ResponseCode>ErrorInvalidAttachmentId</m:ResponseCode>
                    <m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
                    <m:Attachments/>
                </m:GetAttachmentResponseMessage>
            </m:ResponseMessages>
        </m:GetAttachmentResponse>
    </s:Body>
</s:Envelope>

```

## Steps to Reproduce, or Live Example
1. Use the Office.context.mailbox.ewsUrl [1]  to obtain the EWS SOAP endpoint
2. Use the Office.context.mailbox.getCallbackTokenAsync [2] to obtain the EWS token
3. Use the Office.context.mailbox.item.attachments [3] to obtain the list of attachments
4. Make a SOAP request to EWS SOAP endpoint to fetch the attachments (using GetAttachment)

## Context
We are not able to fetch attachments for processing.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Seems to be present in various Office builds
* Operating System: Windows 10
* Browser (if using Office Online): N/A

## Reference
[1] https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.3/office.context.mailbox?view=office-js#ewsurl-string
[2] https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.3/office.context.mailbox?view=office-js#getcallbacktokenasynccallback-usercontext
[3] https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.3/office.context.mailbox.item?view=office-js#attachments-arrayattachmentdetails

**Comment by exextoc** [comment] 2019-03-19 01:11
To verify, this issue is occurring in Outlook Desktop, not Outlook Web App, correct? Do you get this error in read or compose mode? 

The issue you are observing may be related to inconsistent item state. Changes to an item via EWS/ REST (MakeEwsRequestAsync, or via a backend call), are updated directly in the exchange server. Changes made to an item using the Office.js API go to the client first and these changes, when using Outlook Desktop in Cached Mode,  are not synced to the exchange server immediately. Instead the server copy of the item gets updated when Outlook Desktop sync's with exchange. So an item can get in an inconsistent state if it is updated using office.js and REST/ EWS before Outlook client gets a chance to sync its state. And when the sync happens, sometimes, exchange resolves the conflict by overwriting the client copy so the client items changes can be lost. 
 
To avoid this problem, it is recommended that all changes to the same item be made either via REST/EWS or through the Office.Js API's. Mixing the two can result in conflicts. If this is not possible, then we have seen partners following the pattern of not making the changes via REST/EWS until they have detected the change that was made from the client.

**Comment by splinter** [comment] 2019-03-19 12:38
We get this error in read mode.

We are not manipulating the files using the EWS API or the OfficeJS API.

**Comment by exextoc** [comment] 2019-03-19 21:02
The issue you are seeing may still be related to inconsistent item state, even without using the APIs to manipulate files. For example, in read mode, this can be caused by moving the item to another folder. Due to cache mode it may take some time for the client/server to sync. If you try to get the attachment, it might not have synced to the server yet and no longer exist, resulting in an error.

**Comment by splinter** [comment] 2019-03-20 08:11
Some of the files we tested were several days old.Could this be caused by the interference of a COM add-in or even another web add-in?

**Comment by exextoc** [comment] 2019-03-21 00:22
If a COM add-in is moving the item around in the client, it is possible that the server has not synced yet and you will get this issue. Could you verify if there is any possible add-in moving items around? If this is not the case (the item has not moved recently) and since this is happening in read mode, then you are probably right that this is not a client/server syncing issue. It might be an EWS issue and we will look into what could be causing this error.

**Comment by splinter** [comment] 2019-03-28 04:58
I checked with our client and they mentioned that they are not using any COM add-ins and the Exchange server is not on premise. Is  there any support channel that they can use to escalate the issue?

**Comment by exextoc** [comment] 2019-04-10 21:47
Could you try getting the itemId and attachmentId and try comparing them. The attachmentId should have itemId built in so they start exactly the same. Can you use the itemId to do a getItem call? does this succeed? Also, what is the Outlook build number you are seeing this issue on?

**Comment by splinter** [comment] 2019-04-15 06:41
Let me compare the the two IDs and get back. I won't be able to test the getItem call since I won't have a token (the issue occurs on a client machine). I am waiting on the client to provide us their Outlook build number.

**Comment by splinter** [comment] 2019-04-16 18:34
The client is using Version 1903 (Build 11425.20204)

**Comment by exextoc** [comment] 2019-05-07 02:06
A workaround for this, if you cannot get the Attachment via EWS, you may be able to do a GetItem and get the correct Attachment Id's that way. 

In builds that are older than ~July 2017, there was a bug In the Win32 Desktop client, where Attachment EWS Id's would return incorrectly, on e-mails that were moved to another folder, or a Forwarded e-mail. This bug no longer exists, and newer builds should have the correct AttachmentID, (even if an e-mail was forwarded from an older buggy client). 

However, if the e-mails were sync'ed in Cached mode from a buggy client, then it is possible that the EWSId is still buggy. This will be fixed if the e-mails are re-sync'ed. This can be accomplished by the end user deleting their OST, or creating a new e-mail profile (to be safe). 

It's doubtful you are hitting that issue. Unless your add-in is being run on those older items. 

Otherwise, it is best to use the GetItem workaround... or at least get some Attachment EWS Id's for us to look at. There could also be a bug, but we haven't had any other reports about this recently. So any additional repro steps would be helpful.

**Comment by splinter** [comment] 2019-05-14 05:30
We have collected quite a few EWS IDs but would like to share this securely with your team without going through the ticket.

**Comment by sohailzafar** [comment] 2019-06-10 22:30
Apologies for the delay. Please share your email address and someone from the team will reach out to you. Thanks

**Comment by splinter** [comment] 2019-06-11 15:16
Can I start a dialog via Juan?

**Comment by sohailzafar** [comment] 2019-06-11 15:59
Sure

**Comment by splinter** [comment] 2019-07-18 05:50
@sohailzafar I think we can close this issue based on our offline conversation. The suggested approach was to use the following:
1. Prefer to use the client side getAttachmentAsync [1] currently in preview mode
2. If first option is not possible use the Graph API
3. If second option is not possible use SOAP API


[1] https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item?view=office-js#to-arrayemailaddressdetailsrecipients

**Closed as completed** 2019-07-18 17:30 UTC
