### ISSUE TITLE
Excel custom function: null is converted to 0 when returning an array

### ISSUE THREAD

**Issue by yowl** [OfficeDev/office-js#1503] opened 2020-11-13 17:12 UTC
When a custom function returns an array that contains null , '0' is displayed in Excel as though the number 0 was in the array.  A better result would be to leave the cell empty, so that ISBLANK returns true.

## Expected Behavior
Not 0, I would prefer to have cell blank so that ISBLANK returns true

## Current Behavior
null values in javascript are converted to 0:
![image](https://user-images.githubusercontent.com/2720041/99099461-79047200-25a8-11eb-8c3b-ecb165c0284f.png)

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/yowl/3c555550da50db4f6d987f865a186dca

Load the gist which has:
```
/**
 * Test nullk in array return value
 * @customfunction 
 * @returns {string[][]} A dynamic array with multiple results.
 */
function testNull() {
    return [
        ['apples', null, 'pounds'],
    ];
}
```
And in an cell run it
`=CONTOSO.TESTNULL()`

## Context
If this data is returned from an API call, with the intention of modifying and sending back, then converting nulls to 0 is undesired and wrong

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Win10
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
![image](https://user-images.githubusercontent.com/2720041/99100180-77877980-25a9-11eb-8032-ccd80ad7e06d.png)

* Operating System: Win10 x64

## Useful logs
![image](https://user-images.githubusercontent.com/2720041/99100216-88d08600-25a9-11eb-8dde-1d0c71a9be8e.png)

**Comment by grangeryy** [comment] 2020-11-17 03:43
Thank you, @yowl , for reporting the issue. We have some investigation on this and currently it is a by-design behavior by dynamic array, and it is consistent with VBA UDF.

**Comment by yowl** [comment] 2020-11-17 13:16
Thanks,  ok I understand that compatibility with VBA could be important.  For now I've wrapped the result in 
```
function nullToEmptyString(a){
  for (let element of a) {
    element.forEach(function (subElement, index, myArray) {
      if (subElement === null) {
        myArray[index] = '';
      }
    });
  }
  return a;
}
```
Which converts the nulls to empty strings.  It's not great either (ISBLANK returns false for '') but at least visually it looks right.

**Comment by ElizabethSamuel-MSFT** [comment] 2020-12-04 21:42
@yowl Closing this issue as it seems to be by design. If you have further questions on this, let us know so we can reopen this issue or you can create a new one.

Thanks.

**Closed as completed by ElizabethSamuel-MSFT** 2020-12-04 21:42 UTC
Labels: Resolution: by design, Area: custom functions, Type: product question
