### ISSUE TITLE
Empty attachment id in "New Outlook" on Mac

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-js#1384] opened 2020-09-12 20:11 UTC
On "New Outlook" `window.Office.context.mailbox.item.attachments` returns an array of attachments with empty ids:
```json
[
  {
    "id": "",
    "name": "image001.jpg",
    "isInline": true
  },
  {
    "id": "",
    "name": "image002.jpg",
    "isInline": false
  }
]
```

## Expected Behavior
Attachment id should be present in `window.Office.context.mailbox.item.attachments` array.

## Current Behavior
Attachment id is an empty string `""`

## Steps to Reproduce, or Live Example
Enable "Insider Fast", enable "New Outlook". Check `window.Office.context.mailbox.item.attachments` output. Attachments don't have ids.

## Context
This blocks us retrieve attachments via REST API/EWS API.

## Your Environment
* Platform: Mac
* Host: Outlook
* Office version number: 16.42 (20090901)
* Operating System: macOS Catalina v10.15.6

**Comment by exextoc** [comment] 2020-09-18 18:07
Hey @modestfake ,

Apologies for the delay. However, we are unable to reproduce this issue on our end. Can you share an add-in manifest for an add-in where you're seeing this issue? You can share the add-in at this ID:
admin@a830edad9050849405E20081103.onmicrosoft.com

**Comment by modestfake** [comment] 2020-09-19 09:50
Hey @exextoc,

Thanks! I've sent my manifest to that mailbox.

**Comment by exextoc** [comment] 2020-09-21 14:02
Hi @modestfake , this issue has been fixed by our team. Please update to the latest Insider Fast build (16.42 (20091509)) to get the fix. If you're not on the Insiders ring, it will roll out to all users by mid of October.

**Closed as completed by exextoc** 2020-09-21 14:02 UTC
Labels: Area: Outlook, Status: fixed
