### ISSUE TITLE
[Excel] List data validation source property behaves inconsistently

### ISSUE THREAD

**Issue by wattsUpJaz** [OfficeDev/office-js#972] opened 2020-02-06 23:55 UTC
When setting the list data validation source property, the case sensitivity of comparisons to the list is determined by the type of the source (string or range).

## Expected Behavior

I expect the behavior of the list data validation to behave the same regardless of whether the source property is a string or range.

## Current Behavior

When the source is a string, the data validation is case sensitive. When the source is a range, the data validation is case insensitive. This implied behavior of case sensitivity based on the type of the source property is unclear.

I suggest adding a property like `match-case` to `Excel.ListDataValidation` that will clearly define how comparisons to the list provided via the source property should be handled.

## Steps to Reproduce, or Live Example

* Link to live example: [Link Data Validation.EXCEL.yaml](https://gist.github.com/jazcar/1f6e7cd574df5ab617b90eaf963c4165)

## Context

I am trying to set the list of valid inputs for data validation by using values that come from a database/storage account, but I don't want the comparison to be case sensitive. I don't want to add the data to the file, because this would provide the end-users with access to data I don't want them to have, the opportunity for end-users to change the data validation list by altering the range that the source property points to, makes the excel file larger, and increase the time/computation it takes to set up the data validation.

**Comment by lumine2008** [comment] 2020-02-07 08:45
Thanks @jazcar , i just repro this issue, and this is a bug3943687	, we are investigating on this issue.

**Comment by lumine2008** [comment] 2020-02-07 13:19
Hi @jazcar , we had a second look on this issue, we found that API behavior is as same as UI. therefore we believe this is a by design from API perspective, therefore , i think this should be a new feature request in Excel. so i would suggest that you could submit your request in uservoice and upvote for this feature at https://officespdev.uservoice.com/. and upvote for this feature. thanks for your support

**Comment by lliu113** [comment] 2020-02-12 01:50
@jazcar - I'm going to go ahead and close this issue, please reopen if you have any further questions. Thanks!

**Closed as completed by lliu113** 2020-02-12 01:50 UTC
Labels: Area: Excel, Resolution: by design
