### ISSUE TITLE
Office.context.mailbox.displayMessageForm not working on Mac Outlook and UI less Add-In

### ISSUE THREAD

**Issue by Shepherd-rocks** [OfficeDev/office-js#747] opened 2019-09-28 20:46 UTC
I'm currently facing an issue with Outlook object model of the API in all versions from v1.1 and higher on Mac Outlook 2016 (V16.26.0 and below). **The method Office.context.mailbox.displayMessageForm is not working on Outlook for Mac as long as the Add-In is UI less** and not displaying a task pane. On Windows as well as on the online versions everything is working fine.

### Current situation
I wrote an outlook add-in which creates a new draft of an email (saved in draft folder via usage of EWS envelope) and opens the new draft by using the outlook add-in API (method: ). The add-in is working fine in Outlook on the web (old version as well as the new version in office 365) in Chrome, Firefox, IE, Edge and Safari independently of the browser versions. Outlook 2016 in the latest builds on Windows 10 is also working fine. Unfortunately, under Outlook 2016 for Mac the add-in is unable to open the message window. No error occurs. However, the draft was successfully created. The problem exists since nearly 9 months and I wasn't able to find the root cause due to the limited Outlook for Mac troubleshooting functionalities.

### Troubleshooting
With support of I made some troubleshooting some time ago and found out that Mac Outlook needs a delay to sync drafts to the draft folder. You can find a detailed explanation here:[ Office 365 Outlook REST API - Office.context.mailbox.displayMessageForm not working on Mac Outlook](https://stackoverflow.com/questions/55461837/office-365-outlook-rest-api-office-context-mailbox-displaymessageform-not-work)

Because of this, the add-in has a built in delay on mac but this didn't solve the problem as long the add-in is UI less (means the add-in functionality is directly launched via ribbon bar button). When I execute the function by a button in a Task Pane everything works smoothly, so the first "delay problem" has been solved successfully and the message is accessbile.

### Try it your own
The add-in is publicly available via [MS AppSource Reply with attachment](https://appsource.microsoft.com/de-de/product/office/WA104381616?tab=Reviews). Unfortunately, I'm because of the described issue not able to publish a new version. Microsoft support isn't helpful.

If there are further questions, just comment. Every help or hints are very much appreciated. Thanks in advance for your support! Thomas

**Comment by kbrandl** [comment] 2019-09-29 15:02
@macOutlookExtensibility FYI, assigning to you for investigation.

**Comment by macOutlookExtensibility** [comment] 2019-09-30 07:41
Bug 1242048<https://o365exchange.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_workitems/edit/1242048>: [OfficeDev/office-js] Office.context.mailbox.displayMessageForm not working on Mac Outlook and UI less Add-In (#747)



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by kbrandl** [comment] 2019-09-30 17:19
Internal work item created by @macOutlookExtensibility: # 1242048 (*o365exchange.visualstudio.com*).

**Comment by macOutlookExtensibility** [comment] 2019-10-03 06:30
Hey @Shepherd-rocks . Did you try a longer delay than the one you are using to let the item sync?

**Comment by Shepherd-rocks** [comment] 2019-10-03 07:12
@macOutlookExtensibility Yep, I tried e. g. 10 seconds and longer but nothing happend. Interestingly, everything works fine if I execute the same function from a side pane with 2000 milliseconds delay.

**Comment by exextoc** [comment] 2019-10-09 08:27
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by Shepherd-rocks** [comment] 2020-02-01 13:39
@exextoc any update or known work around about this issue?

**Comment by udit7590** [comment] 2020-03-28 07:20
@exextoc Seems I face the same issue with `Office.context.mailbox.item.getItemIdAsync` on Outlook Desktop - Mac. Is there anything we can do as a workaround for fix?

**Comment by exextoc** [comment] 2020-03-30 10:07
Can you share the repro steps for error you are getting. Also did you save the item before calling Office.context.mailbox.item.getItemIdAsync. We are not able to repro this at our end.

**Comment by baldaja-tschaefer** [comment] 2020-08-03 08:20
@exextoc is there any update or known workaround for Office.context.mailbox.displayMessageForm with UI less addins on Outlook Mac?

**Comment by Shepherd-rocks** [comment] 2020-08-08 10:12
@exextoc are there any news on this? Your question regarding further information was not related to the initial issue correct? If that's not the case please don't tag the issue as waiting for author-feedback. Thanks

**Comment by rajeshk7** [comment] 2020-08-08 17:52
We are not able to reproduce the bug 

- Can you please provide the manifest (add-in) which is failing for you ?

- Does it fail for any specific account or is general.

**Comment by exextoc** [comment] 2020-08-08 17:55
We are not able to reproduce the bug

- Can you please provide the manifest (add-in) which is failing for you ?

- Does it fail for any specific account or is general.

**Comment by exextoc** [comment] 2020-08-08 17:56
Not able to reproduce it.
Have attached the add-in I have been trying with.
The bug seems to be more than one year old.

Regards
Rajesh Kr Jha
________________________________

**Comment by Shepherd-rocks** [comment] 2020-08-09 20:20
Dear Rajesh,

Unfortunately, the attached add-in didn’t reach me. Can you provide your code & manifest?

Cheers,
Thomas

Von: Outlook Add-ins Team - MSFT <notifications@github.com>
Antworten an: OfficeDev/office-js <reply@reply.github.com>
Datum: Samstag, 8. August 2020 um 19:57
An: OfficeDev/office-js <office-js@noreply.github.com>
Cc: Thomas Schäfer <ths@shepherd.rocks>, Mention <mention@noreply.github.com>
Betreff: Re: [OfficeDev/office-js] Office.context.mailbox.displayMessageForm not working on Mac Outlook and UI less Add-In (#747)

Not able to reproduce it.
Have attached the add-in I have been trying with.
The bug seems to be more than one year old.

Regards
Rajesh Kr Jha
________________________________

**Comment by exextoc** [comment] 2020-08-26 05:02
@Shepherd-rocks Sorry you couldn't get this to work, but as mentioned in the StackOverflow this is because of a timing issue and you can use the newer APIs [(displayReplyAllForm](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.8#displayreplyallform-formdata-) / [displayReplyForm](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.8#displayreplyform-formdata-) / [displayNewMessageForm](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.8#displaynewmessageform-parameters-) /  [getAttachmentContentAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.8#getattachmentcontentasync-attachmentid--options--callback-) ) to solve your problem.

Here is a solution which you can try,
```
Office.context.mailbox.displayMessageForm(itemId,
 function (asyncResult) {
  if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
   // RETRY DISPLAY MESSAGE FORM AFTER SOME INTERVAL
  } else {
   // INFORM USER IF REQUIRED
  }
 }
);
```

**Closed as completed** 2020-09-02 08:00 UTC
Labels: Area: Outlook, Needs: author feedback, Status: no recent activity
