### ISSUE TITLE
[Excel] Excel office table onSelectionChanged is not get trigger anymore as long as drop down get click on task pane.

### ISSUE THREAD

**Issue by abralock** [OfficeDev/office-js#1328] opened 2020-08-13 03:23 UTC
We found an issue by using Window 10 (V1909) - latest &  Excel Office version  2002 & Edge version 84.0.522.59
on excel web add in. As long as drop down get click on task pane, excel office table onSelectionChanged is not get trigger anymore. If without drop down selection, onSelectionChanged  is well respect. However, this behaviour works well on Office JS with IE but not in Edge. 

## Expected Behavior
onSelectionChanged   should get respect even we click on drop down control. Office IE is working well & do not face this issues.

## Current Behavior
 As long as drop down get click on task pane, excel office table onSelectionChanged is not get trigger anymore. However, this behaviour works well on Office JS with IE but not in Edge. 

## Steps to Reproduce, or Live Example
	 i) Create Office Excel Js from Visual studio 2019.
	ii) Paste Home.js & Home.html form the code attached. 
	iii) click the fetch button
	iv) put a break point on onTableChanged
	v) Click on any value on the office table formed 
	vi) You will see onSelectionChanged well respected.
	vii) Now click on the drop down
	viii) onSelectionChanged  is no more respect!!! 

[Home.zip](https://github.com/OfficeDev/office-js/files/5066979/Home.zip)

## Context
We have about 100 of users using the office js for production data maintenance. Super high critical as every latest version and breaking. 
	
Do you guys have any suggested Edge version to follow? 

## Your Environment

	* Platform [PC desktop, Mac, iOS, Office on the web]: ____PC Desktop__
	* Host [Excel, Word, PowerPoint, etc.]: ____Excel__
	* Office version number: ___2002 ___
	* Operating System: __10 - V1909____
	* Browser (if using Office on the web): ___Edge_V 84.0.522.59__

![image](https://user-images.githubusercontent.com/2835194/90090678-3a67dd00-dd57-11ea-80e7-78e5bf0b0030.png)

![image](https://user-images.githubusercontent.com/2835194/90090668-320fa200-dd57-11ea-9cc5-3b58071b61b8.png)

![image](https://user-images.githubusercontent.com/2835194/90090684-3e93fa80-dd57-11ea-97d2-7b03057b3904.png)

**Comment by nsakar** [comment] 2020-08-13 14:21
Please provide a resolution asap. The dropdown list html control is not working in edge and consequently breaking web addin functionality.

**Comment by alison-mk** [comment] 2020-08-13 16:57
Hi @abralock and @nsakar, thank you for submitting this issue and providing so many details! I've assigned it to the Excel engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by nsakar** [comment] 2020-08-14 15:55
Any updates on this issue?

**Comment by jargil** [comment] 2020-08-14 23:06
Duplicate of #1100 
Fixed in build 16.0.13001, version 2006. I added notes for a workaround if you cannot update to the latest Office builds.

**Closed as completed by jargil** 2020-08-14 23:06 UTC
Labels: Area: Excel, Resolution: duplicate
