### ISSUE TITLE
IndexedDB not getting initialized on first add-in open request

### ISSUE THREAD

**Issue by vikaskeskar11** [OfficeDev/office-js#1281] opened 2020-07-15 12:29 UTC
This behavior is observed on MAC Catalina OS.
When I open office js Word add-in for the first time after quitting and reopening word or when I fresh open word, and then open add-in. But, when I close the task pane and reopen add-in, it loads data stored in IndexedDB.
## Expected Behavior

- It should always fetch data from IndexedDB if written in code
## Current Behavior

- On first time add-in open(Completely quit word from menu, and not the close button of word). Open word and open add-in, then for first time fresh open, it does not load data from IndexedDB
- Cause is, IndexedDB data is not loaded by task pane browser on Catalina OS.

## Steps to Reproduce, or Live Example

![mac-os-behaviour-for-word-mac-indexeddb-catalina-os](https://user-images.githubusercontent.com/24711514/87544959-e10f7e00-c6c4-11ea-89b0-a88aa293840b.gif)

* Additional details:
  1. Create any test add-in
  2. Add add and get operation on IndexedDB
  3. Add value to indexeddb, and verify it is added or not
  4. Then quit word from menu, reopen it
  5. Open add-in and verify if you get data previously added to database.

## Context

- This issue is affecting live customers.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.** (On Catalina only)
* Operating System: MAC Catalina OS(10.15.5 or 10.15.6)

## Useful logs

- I have checked for console logs, but there are not any

**Comment by lindalu-MSFT** [comment] 2020-07-23 17:26
Hi, sorry for the delayed response! We're a bit short on resources this week due to vacations. I assigned this to the Word team to investigate. Thanks, linda

**Comment by smaremanda** [comment] 2020-07-29 21:04
@vikaskeskar11 - does this happen just the 1st time or every time? Can you also share the full Office version?

**Comment by vikaskeskar11** [comment] 2020-07-30 04:59
@smaremanda  This happens when quit the word and reopen it(We can fresh open). 
Word Version:
![image](https://user-images.githubusercontent.com/24711514/88882342-5ba4d580-d24f-11ea-8a85-2f29ce9f1f76.png)

**Comment by vikaskeskar11** [comment] 2020-09-29 10:11
Are there any updates on this? This issue is affecting customers.

**Comment by somenathmaji** [comment] 2021-04-21 08:36
## Data on object store is not persisting on quitting Office application.

#### Issue description
We have an add-in(Outlook, Excel) and we use indexedDB to store data for offline access and caching. This issue is specific to only MacOS and works perfectly on Windows.

This behavior could be tried out from Script Lab as well, I have an Outlook gist - https://gist.github.com/somenathmaji/ce64908e360c047d2dfdd7e830597e03

#### Steps to reproduce the issue
1.  Open the IndexedDB
2. Create an object store
3. Write some data in the newly created object store
4. Quite the application(Outlook or Excel)
5. Reopen the application (Outlook or Excel)
6. Try to retrieve the same data from the same object store

Try out the gist on Script Lab mentioned earlier-
1. Add data by clicking the `Add Data` button
2. Quit Outlook
3. Read data by clicking the `Read All` button

#### What's the expected result?
Added data should persist in indexedDB and we should be able to get old data we added before quitting.

#### What's the actual result?
Added data gets cleared from the object store on quitting the application.

#### Additional details / screenshot
- Platform [PC desktop, Mac, iOS, Office Online]: Mac
- Host [Excel, Word, PowerPoint, Outlook, etc.]: Outlook(v16.48), Excel(v16.48)
- Office version number: 16.** (On Catalina only)
- Operating System: Mac OS Catalina (10.15.7)

**Comment by jargil** [comment] 2021-04-21 22:36
I cannot repro on macOS Big Sur, unfortunately I don't have access to a machine with Catalina to confirm this behavior with IndexedDB. There's nothing special that Office does in terms of clearing/not-clearing IndexedDB. It's possible that there was a change in WebKit between what you have in Catalina and what is in Big Sur. At this point my only recommendation is that if you need to work with IndexedDB, is looking like you'll have to update to the a newer macOS build.

When upgrading to Big Sur, consider that WebKit has now enabled ITP, and there's some special considerations to understand when dealing with storage.
https://webkit.org/tracking-prevention/

Given this is a no repro with the latest macOS, and that Office does not have control over WebKit internals, I'll go ahead and close this issue as external. Please let me know if you have the same problem when using the latest macOS.

**Closed as completed by jargil** 2021-04-21 22:36 UTC
Labels: Resolution: external, Area: Word
