### ISSUE TITLE
On Send web add-in is giving blank mail body in case of reply/forward mail.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4241] opened 2024-03-12 07:03 UTC
Description - On Send web add-in is giving blank mail body in return if we Reply or Forward on the existing sensitive email from inbox without modifying it.

Steps to Reproduce - 
1 - Reply/forward existing mail where multiple previous mail threads are already present.
2- Check in on send addin mailbox items body. 

Expected Result - 
1 - On send mailbox item body should give all previous mail-thread contents.

Note - 
If we modify any previous mail thread present in mail at the time of reply and forward, It is working properly.

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by mmanjaree-msft** [comment] 2024-03-12 07:10
@Sagar-lab1 Can you please share a repro video. The issue here is not clear. Are you trying to convey that getBody api is not returning the body content when you call the api from on send handler function?

**Comment by sagar-sonawane9** [comment] 2024-03-13 05:42
In on send handler function. In case of normal compose->new send mail .. we are getting mail body as expected.
But if we are forwarding/replying to existing mail without doing any modification in body (earlier mail threads data is visible in mail )
We are not able to get that data in on send handler.

Refers below API for example

let body = '';
Office.context.mailbox.item.body.getAsync(
  "text",
  function (result) {
    if (result.status === Office.AsyncResultStatus.Succeeded) {
      body = result.value;
      doSomething(body)
    }
  }
)

function doSomething(body){
  console.log(body);
}

Strangely If we modify any earlier thread’s mail body in mail before Forwarding/replying existing mail then the same API is giving correct details in body .

**Comment by mmanjaree-msft** [comment] 2024-03-13 08:48
@Sagar-lab1 Can you please share a video of the issue.

**Comment by neville-jones** [comment] 2024-03-14 22:04
Duplicate of #2317 ?

**Comment by sagar-sonawane9** [comment] 2024-03-15 09:10
Yes , Issues mentioned in https://github.com/OfficeDev/office-js/issues/2317  are same.

**Comment by ajays-msft** [comment] 2024-03-17 06:10
closing this issue, as the we are tracking as a part of #2317

**Closed as completed by ajays-msft** 2024-03-17 06:10 UTC
Labels: Area: Outlook, Resolution: duplicate

**Comment by sagar-sonawane9** [comment] 2024-03-21 09:29
Attaching video and screenshot.
If we are forwarding/replying to existing mail without doing any modification in body (earlier mail threads data is visible in mail )We are not able to get that data in on send handler.

https://github.com/OfficeDev/office-js/assets/158541755/dcf9c339-c8d0-4187-a9ae-d698e8394d60

<img width="950" alt="forward_Sensitive" src="https://github.com/OfficeDev/office-js/assets/158541755/a2af384d-a2c8-41a9-b49c-376ab789addb">
