### ISSUE TITLE
global fetch function forces encoding as windows-1252 on Outlook Desktop in event-based activation runtime

### ISSUE THREAD

**Issue by sami-romdhana** [OfficeDev/office-js#3892] opened 2023-12-06 13:38 UTC
When using the "classic" Outlook Desktop, with an add-in set up for event-based activation, when fetching Internet content during the event, fetch returns content as if forcibly using windows-1252 despite content being encoded using utf-8 and there being a header specifying that the response is encoded using utf-8.

This only happens in the runtime for background code (Hermes-based I think), when fetching content through the pane, there are no encoding issues.

*This does not happen in Outlook for the Web or New Outlook, only in "classic" Outlook Desktop*

## Your Environment

* Platform: Desktop
* Host & Version: Microsoft Outlook for Microsoft 365 MSO (Version 2312 Build 16.0.17126.20000) 64-bit
* Channel: Beta (and also preview now)
* Operating System: Windows 11
 
## Expected behavior

If I fetch something like `Property of Contoso–Amélior™` I get that exact string back

## Current behavior

Instead I get `Property of Contosoâ€“AmÃ©liorâ„¢`

Fetching content now corrupts [characters part of this range](https://www.i18nqa.com/debug/utf8-debug.html)

## Steps to reproduce

1. Create an event-based activated add-in
2. Fetch content using fetch containing special characters such as é, £, ... ([more](https://www.i18nqa.com/debug/utf8-debug.html))
3. Insert the content as part of a signature

## Link to live example(s)

Minimal reproducible example provided for convenience [here](https://github.com/sami-romdhana/outlook-encoding-mre)

Use `npm run certificates` if local development certificates are not yet installed, then run `npm start` (tested on Windows)

## Context

We're using the event-based activation scenario as part of a signature addin for Outlook, and we've already received complaints from users because their templates contain characters that are now problematic. We've had to temporarily replace content to avoid display issues in the meantime.

**Comment by vddgil** [comment] 2024-01-08 09:28
Hello,

It seems that version 2312 Build 16.0.17126.20000 was released on January 4 with the bug ...
We also have customers complaining about broken characters in their signature (which is inserted with an event-based Addin).

Do you have a plan for a fix?

Thanks in advance.

**Comment by bogdanst24** [comment] 2024-01-08 13:52
Same issue here

**Comment by kinkoazc** [comment] 2024-01-09 08:32
@exextoc This is urgent and impacts our clients' signatures. Please address it asap.

**Comment by nikovrdoljak** [comment] 2024-01-09 11:07
Our customers also started reporting this issue in email signatures with version 2312. E.g. "RÃ¶der" instead of "Röder", "StraÃŸe" instead of "Straße". The issue appears only when the request is made from an event-based function. Encoding for outgoing messages in Outlook is set to "UTF-8". Can we have some feedback on this?

**Comment by jjensenp44** [comment] 2024-01-10 07:32
We are having this issue also with signature provider Xink. Xink says they cannot reproduce the problem on 2312 so it is really hard for them to troubleshoot.

**Comment by Karstenvendler** [comment] 2024-01-10 07:41
Same for us and as we are an international company with employees all arround the world, we need a fix ASAP

**Comment by Karstenvendler** [comment] 2024-01-10 10:46
> We are having this issue also with signature provider Xink. Xink says they cannot reproduce the problem on 2312 so it is really hard for them to troubleshoot.

I have tested on several PC's, den the problem is still there after upgrade to (Version 2312 Build 16.0.17126.20132) 64-bit

**Comment by jjensenp44** [comment] 2024-01-10 10:51
> > We are having this issue also with signature provider Xink. Xink says they cannot reproduce the problem on 2312 so it is really hard for them to troubleshoot.
> 
> I have tested on several PC's, den the problem is still there after upgrade to (Version 2312 Build 16.0.17126.20132) 64-bit

Same here. All users with 2312 have the issue. Xink says it is a Microsoft issue and that they will not be able to fix this. Has Microsoft acknowledged that this is a bug on their end?

**Comment by Karstenvendler** [comment] 2024-01-10 10:55
> > > We are having this issue also with signature provider Xink. Xink says they cannot reproduce the problem on 2312 so it is really hard for them to troubleshoot.
> > 
> > 
> > I have tested on several PC's, den the problem is still there after upgrade to (Version 2312 Build 16.0.17126.20132) 64-bit
> 
> Same here. All users with 2312 have the issue. Xink says it is a Microsoft issue and that they will not be able to fix this. Has Microsoft acknowledged that this is a bug on their end?

Not yet, i have opned a MS supportcase, but as of now nothing, and most of you may know lvl 1. in MS support is not where this will be fixed, ;-)

**Comment by Karstenvendler** [comment] 2024-01-10 11:32
XINK has this statement
https://status.xink.io/

**Comment by thomasdarde** [comment] 2024-01-10 12:37
Our solution does work in this context FYI, but clearly this important bug need to be fixed !

**Comment by nikovrdoljak** [comment] 2024-01-10 12:58
How can the user switch back to version 2311?

**Comment by lovergaard** [comment] 2024-01-10 13:08
I had success running this command in an elevated command prompt
`"C:\Program Files\Common Files\microsoft shared\ClickToRun\OfficeC2RClient.exe" /update user updatetoversion=16.0.17029.20028`

**Comment by mickeynygaard** [comment] 2024-01-11 10:13
A couple of other articles regarding the same issue:

https://support.templafy.com/hc/en-us/articles/16009763053341-Email-Signatures-inserted-automatically-by-the-Outlook-Web-Add-in-are-breaking-special-characters

https://support.exclaimer.com/hc/en-gb/articles/6622042157085-Foreign-characters-are-not-displayed-correctly

We're yet to test changing the outgoing encoding as the exclaimer.com article mentions....

**Comment by mickeynygaard** [comment] 2024-01-11 10:51
No luck with changing the outgoing encoding for us.
We're using Xink, and apparently the issue exists if using the Xink Outlook Addin, but the issue is not to be found when using the Xink "fat client"

**Comment by SimonDania** [comment] 2024-01-11 13:54
@exextoc This impacts all of our customers at the moment. Are you able to give a status?

**Comment by Karstenvendler** [comment] 2024-01-12 07:11
> I had success running this command in an elevated command prompt `"C:\Program Files\Common Files\microsoft shared\ClickToRun\OfficeC2RClient.exe" /update user updatetoversion=16.0.17029.20028`

We tried this, but as soon as the user starts up Outlook it will upgrade right away again, if this is the workaround, ther must be a way to stop the windows update from updating 😯

**Comment by ptrflk** [comment] 2024-01-12 08:06
An update needed please! Big impact for all our customer. @exextoc

**Comment by jjensenp44** [comment] 2024-01-12 08:38
Xink just reached out letting me know that they have pushed a new version of their add-in. I just tested and it seems to have solved our issues. No action is needed from the customer side. Hopefully this also works for the rest of you using Xink

**Comment by nikovrdoljak** [comment] 2024-01-12 08:54
> > I had success running this command in an elevated command prompt `"C:\Program Files\Common Files\microsoft shared\ClickToRun\OfficeC2RClient.exe" /update user updatetoversion=16.0.17029.20028`
> 
> We tried this, but as soon as the user starts up Outlook it will upgrade right away again, if this is the workaround, ther must be a way to stop the windows update from updating 😯

You can try switching to Monthly Enterprise channel:
"C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeC2RClient.exe" /changesetting Channel=MonthlyEnterprise
"C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeC2RClient.exe" /update user

In my case I also have to set:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\office\16.0\common\officeupdate
updatebranch = "MonthlyEnterprise"

Or in 365 Admin Org Settings:
![image](https://github.com/OfficeDev/office-js/assets/7567269/8de5d487-bece-4004-8aef-6f6ab331bb3a)

I also noticed this bug is still existing in version 2401. In version 2402.20000 fetch does not even work.

We would appreciate at least getting details on the fix for addins working on 2312.

(Edit: in 2402.20000 fetch does not work)

**Comment by Karstenvendler** [comment] 2024-01-12 09:24
> Xink just reached out letting me know that they have pushed a new version of their add-in. I just tested and it seems to have solved our issues. No action is needed from the customer side. Hopefully this also works for the rest of you using Xink

I can confirm this and it seems to work 🤞👍

**Comment by Karstenvendler** [comment] 2024-01-15 09:08
I have just received a mail in my MS support case related to this issue, and as allways MS point's  at the addins to be the reason for the error/issue and they say that it has been fixed, by the addin vendors.
I have strongly disagreed with that conclusion, and men tioned that atleast in our addin there was no change in code between MS version 2311 and 2312/2401, i expect this to be uphill to get MS to accept that it is them that has a problem in thier code, but will keep pointing at them(MS) as the source of this issue/error, NOT our addin Vendors.

**Comment by SimonDania** [comment] 2024-01-16 14:19
We got swarmed by support cases, so we ended up fixing the error ourselves instead of waiting for a fix from Microsoft.

**Comment by Karstenvendler** [comment] 2024-01-18 07:07
> We got swarmed by support cases, so we ended up fixing the error ourselves instead of waiting for a fix from Microsoft.

Can you tell, how you ended up fixing it/workarround?

**Comment by nikovrdoljak** [comment] 2024-01-18 07:11
> > We got swarmed by support cases, so we ended up fixing the error ourselves instead of waiting for a fix from Microsoft.
> 
> Can you tell, how you ended up fixing it/workarround?

Yes, @SimonDania can you please share details on how did you fix the issue?

**Comment by vddgil** [comment] 2024-03-04 10:19
Hello @exextoc,
Did someone at Microsoft understand that we have paying customers who have had this issue for almost 3 months now?
We fixed the European accented characters by replacing them with their HTML entities. But we also have some customer with Arabic characters in their signature and they don't all have a corresponding HTML entity. For those one, we don't have any solution from Microsoft for 3 months.

I join some screenshot from one of our customer:
What it should be:
![msedge_1D6d6Zh3ld](https://github.com/OfficeDev/office-js/assets/81749/23748abd-bd5d-4110-a254-a67a898cee9b)

What they get:
<img width="347" alt="OUTLOOK_DmySvcGj7L" src="https://github.com/OfficeDev/office-js/assets/81749/8cd913c0-7cec-4dae-8cf0-b2cb41798af0">

**Comment by exextoc** [comment] 2024-03-28 00:09
We are looking into this issue and so we will get back shortly. Thanks for your patience.

**Comment by JunielKatarn** [comment] 2024-03-28 00:12
@exextoc please assign to me.

This is most likely an issue with the ~~new~~ **old** React Native Windows HTTP module.

**Comment by JunielKatarn** [comment] 2024-04-01 21:46
> Hello @exextoc, Did someone at Microsoft understand that we have paying customers who have had this issue for almost 3 months now? We fixed the European accented characters by replacing them with their HTML entities. But we also have some customer with Arabic characters in their signature and they don't all have a corresponding HTML entity. For those one, we don't have any solution from Microsoft for 3 months.
> 

Hi @vddgil, @sami-romdhana.
This issue appears to be fixed in recent versions of Office (starting with `16.0.17301.15000`).
Can you please upgrade to that version or later and try again?

**Comment by Oleg-O** [comment] 2024-07-15 21:21
Is this still an active issue or has this been resolved?

**Closed as completed** 2024-07-23 10:14 UTC
Labels: Area: Outlook, Needs: author feedback

**Comment by vddgil** [comment] 2024-08-07 14:21
Hello there,
Some of our customer are complaining again about the issue.
One have the following version =>  "Version 2402 Build 16.0.17328.20346) 64 bits"

@exextoc Is it possible that the bug came back ?

**Comment by Oleg-O** [comment] 2024-08-14 23:59
@vddgil please see https://github.com/OfficeDev/office-js/issues/4736
