### ISSUE TITLE
Outlook 365 add-in (Claritysoft for Outlook) is not working in the new Outlook

### ISSUE THREAD

**Issue by ClaritysoftLLC** [OfficeDev/office-js#4459] opened 2024-05-15 13:33 UTC
**App Name: Claritysoft for Outlook
App ID: 42949682348**

**URL of sample**

https://www.loom.com/share/3a90fcc82a514d9da0c43eedb637a4e0?sid=f19d8f52-6922-4cc0-b2db-f2db7c8b2bcc
https://www.awesomescreenshot.com/video/27208168?key=e3a39a1cdc883529788080d7c22e1b40

**Describe the bug**

Please find a few compatible Issues listed below what we observed:

>> Outlook relaunching multiple times and every time behaving differently.
>> Sometimes the app icon responds expectedly and sometimes it’s not.
>> The Add-in icon is intermittently disappearing.

It works when turning off the New Outlook toggle. Please see the below link for your observation

**Comment by AlexJerabek** [comment] 2024-05-15 15:58
Hi @ClaritysoftLLC,

Thanks for reporting this. I'm going to move this issue to the [office-js repo](https://github.com/OfficeDev/office-js), where product bugs are examined.

**Comment by mmanjaree-msft** [comment] 2024-05-17 07:43
@ClaritysoftLLC  Thanks for reporting this issue. Can you capture and share logs for the scenario when this issue is happening. Follow the steps mentioned here https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues. Also check if there are any errors in console after addin is clicked. Steps to open devtools in new outlook https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#debug-your-add-in.
Also is this an admin deployed or a sideloaded addin

**Comment by ClaritysoftLLC** [comment] 2024-05-28 09:42
@mmanjaree-msft Thanks for providing us the guide link. 
As per your provided link (https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues) we have reproduce the issue in 'New Outlook on Windows'.
Please find the .ZIP file for .HAR and console log.
[error.zip](https://github.com/OfficeDev/office-js/files/15467240/error.zip)

**Comment by ClaritysoftLLC** [comment] 2024-06-03 10:57
@exextoc @AlexJerabek @mmanjaree-msft 
As per your request we provided .HAR file and console log last week. Is there any update on this?

**Comment by akagarwa-msft** [comment] 2024-06-04 08:00
Apologies for the delayed response. We are not able to repro the issue at our end. We tried installing the same Add-in from store but it works without any issues. Is it possible to share the test account where the issue is reproable for you?

**Comment by ClaritysoftLLC** [comment] 2024-06-04 13:16
@akagarwa-msft 

Our QA team tested multiple time and issue exists. Please find the bellow video links for more details.

https://www.loom.com/share/3a90fcc82a514d9da0c43eedb637a4e0?sid=f19d8f52-6922-4cc0-b2db-f2db7c8b2bcc
https://www.awesomescreenshot.com/video/27208168?key=e3a39a1cdc883529788080d7c22e1b40

**Comment by akagarwa-msft** [comment] 2024-06-06 03:01
We are looking into the issue from our end. Can you please validate the following: 
1. Setting for the Customer:  Go to Settings > General > Privacy and data > Privacy settings. Check if "Optional Connected Experience" is turned ON for the user. 
2. Is the customer enterprise or consumer?
3. Please follow the instructions here to capture logs from New Outlook.
[Collecting log files for Outlook Add-ins issues · OfficeDev/office-js Wiki (github.com)](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues) . We are looking for one network call which is missing in the logs provided.

**Comment by ClaritysoftLLC** [comment] 2024-06-06 09:43
@akagarwa-msft 

As per your requirement please find the bellow attachments for details

1. 
![UserSettings](https://github.com/OfficeDev/office-js/assets/169909471/0d2896f5-7e90-4d25-ae70-803775749784)

2. Enterprise customer (**NOTE: Multiple number of our client reported the same issue from their end and they are from enterprise and consumer category.**)

3. 
[outlook.office.com_HARFILE.zip](https://github.com/user-attachments/files/15613120/outlook.office.com_HARFILE.zip)

4. 
[consoleLog_6thJune.txt](https://github.com/user-attachments/files/15613149/consoleLog_6thJune.txt)


We have recorded the process. Please find the below link
https://www.awesomescreenshot.com/video/28383920?key=171e7a1723ecd40b3d854d7b19047460

**Comment by mobisw-msft** [comment] 2024-06-14 10:49
Hey @ClaritysoftLLC ,

Unfortunately, we are not able to reproduce or debug this issue. If you have a test account where this behaviour consistently reproduces, can you share the test account credentials with us? You can share the credentials by adding them in a private repository and granting us access.

**Comment by ClaritysoftLLC** [comment] 2024-06-17 06:46
@mobisw-msft Please find the credentials.

AddIn: Claritysoft for Outlook
Username: Test
Password: Password#
DB: satyacx
![Untitled1](https://github.com/OfficeDev/office-js/assets/169909471/766f7a97-bc90-445c-aea5-25d4877afd4c)


You can find the issue with New Outlook. 
**Our client's are unable to use the Add-In, so try to resolve ASAP.** 

Note: As our support team and client's continuously monitoring this ticket, so please mark the ticket 'Open'.

**Comment by shighosh-msft** [comment] 2024-06-18 14:09
Hi @ClaritysoftLLC, thanks for sharing the add-ins credentials. Unfortunately, this is not what we meant. We need a user account that is used for log-in to Outlook that repros the issue.  You can share the credentials by adding them in a private repository and granting us access.

**Comment by ClaritysoftLLC** [comment] 2024-06-20 11:14
Hi @shighosh-msft , You can use any 365 account for this AddIn.
However we have created a private repository : https://github.com/ClaritysoftLLC/Credential

![Untitled](https://github.com/OfficeDev/office-js/assets/169909471/058e0506-b2a0-4404-8533-f24f8f0957b4)


**Note: As our support team and client's continuously monitoring this ticket, so please mark the ticket 'Open'.**

**Comment by shighosh-msft** [comment] 2024-06-21 16:11
Hi @ClaritysoftLLC, thank you for sharing the account details. We tested the ClaritySoft add-in with the account you shared but the add-in seems to load for us. Have added a screenshot of the add-in loading successfully on the private repo for you to check. Having said that, can you please confirm the following:
1. Are you seeing this behavior only in case of a multi-account setup in New Outlook?
2. What if you close and restart the Outlook client, does that make the add-in work?

**Comment by ClaritysoftLLC** [comment] 2024-06-24 12:51
Hi @shighosh-msft, thanks for your comment. Unfortunately, we are still facing the same and our client is frustrated 

Are you seeing this behavior only in case of a multi-account setup in New Outlook?
- I only tested with a multi-account setup and faced the Issue we reported. But our customer reported the same issue, using only one account for the new outlook.

What if you close and restart the Outlook client, does that make the add-in work?
- No It did not work. It is only working for the first time then we close and restart the Outlook client It is not working either.

**Comment by ClaritysoftLLC** [comment] 2024-06-27 05:58
Hi @shighosh-msft, any update? 

**Note: As our support team and client's continuously monitoring this ticket, so please mark the ticket 'Open'.**

**Comment by shighosh-msft** [comment] 2024-06-27 12:23
Hi @ClaritysoftLLC, as I mentioned earlier, the issue doesn't repro for us even with the test account that you have shared. The add-in loaded successfully in new Outlook and I've also shared a screenshot of the same in the private GH repo that you created. Having said that, we do understand that is issue quite long standing and we we'd want to get to a resolution soon. 

Can you please share another repro video, starting from adding the test account to New Outlook to the point it stops working since you mentioned that is does work sometimes here: "No It did not work. It is only working for the first time then we close and restart the Outlook client It is not working either."

**Comment by ClaritysoftLLC** [comment] 2024-07-01 09:35
Hi @shighosh-msft, We believe your attached image looks like a web version of Outlook. 

Please see the complete video for your understanding to replicate the Issue. (We are using the desktop version of Outlook)
[](https://www.awesomescreenshot.com/video/29127321?key=198e54148132eb2f49a9c90000f20373)

Please follow the steps below to reproduce the Issue:
1. Open the desktop version of Outlook
2. Switch to New Outlook
3. Add Our Add-In Named 'Claritysoft for Outlook'
4. Select any mail and click the Add-In Icon (It Supposed to Work as expected)
5. Relaunch the Outlook(new version) 
6. Select any mail and click the same Add-In icon (It is not responding) 


Alongside please see the below quires:
1. Are you investigating the desktop version of Outlook?
2. Are you following the same step to relaunching the outlook and replicating the Issue?


Each time we can rectify the issue from a different system and multiple 365 accounts, as well as our clients, continue responding to the same Issue.

**Please do the needful ASAP**

**Comment by Swathy-Mothilal** [comment] 2024-07-03 07:34
@ClaritysoftLLC We've been able to reproduce the issue, but it occurs intermittently. Could you please confirm if you are also experiencing it intermittently?

**Comment by ClaritysoftLLC** [comment] 2024-07-04 04:38
Hi @Swathy-Mothilal , We are delighted to get your response to reproduce the Issue. Not exactly it occurs intermittently but It will occur every alternative time to produce the Issue.

**Comment by Swathy-Mothilal** [comment] 2024-07-04 15:18
@ClaritysoftLLC Thanks for reporting this issue. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.
Internal tracking id: Eg: Office: 4591911

**Comment by shighosh-msft** [comment] 2024-08-09 10:00
@ClaritysoftLLC we have checked in a potential fix for this issue and available in client-version 20240719002 or greater. Can you please confirm if you are still able to repro the issue?

**Closed as completed** 2024-08-16 12:29 UTC
Labels: Area: Outlook, Needs: author feedback, Status: no recent activity
