### ISSUE TITLE
Outlook on Mac - New UI - getAttachmentContentAsync() fails inside ItemSend handler with Error 5001 'Internal error has occurred'

### ISSUE THREAD

**Issue by carlosb1504** [OfficeDev/office-js#2658] opened 2022-06-22 16:25 UTC
Calls to `Office.context.mailbox.item.getAttachmentContentAsync()` inside an ItemSend Event handler, fail with a 5001 'Internal Error has occurred' in Mac Outlook v16.62.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.62
* Operating System: MacOS Monterey
* Browser (if using Office on the web): N/A
 
## Expected behavior
Content of attachments in the email being composed should be retrievable consistently across Windows / Mac versions of Outlook

## Current behavior
5001 'Internal Error has occurred' or 7000 'You don't have permissions'
![Screenshot 2022-06-22 at 17 21 43](https://user-images.githubusercontent.com/47693383/175084282-d71c8e4a-5bbe-4cd4-add5-f7dc0fcf1c30.png)

This works in a regular 'taskpane' context, but not in ItemSend code.

## Steps to reproduce
1. Create a simple add-in utilising ItemSend handler, in the handler call Office.context.mailbox.item.getAttachmentContentAsync() and do something with the base64 content such as push it to console.
2. Add an attachment to an email being composed.
3. Send the message, invoking the ItemSend handler
4. Observe the above behaviour

**Comment by alison-mk** [comment] 2022-06-22 22:55
Hi @carlosb1504, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by exextoc** [comment] 2022-06-23 03:00
@carlosb1504 Can you please confirm whether you have registered the event handler for the ItemChanged? Doing this will notify the add-in when the item is changed. A sample for doing this can be found [here](https://docs.microsoft.com/en-us/outlook/add-ins/pinnable-taskpane#register-the-event-handler).

**Comment by exextoc** [comment] 2022-06-23 08:58
@carlosb1504 We are not able to reproduce the issue on our end. Can you please share the manifest file of your add-in, so that we can debug it?

**Comment by carlosb1504** [comment] 2022-06-23 10:22
Hi @exextoc - I have created a small test app which demonstrates the issue, see attached:

[onSendGetAttachmentContentTest.zip](https://github.com/OfficeDev/office-js/files/8966289/onSendGetAttachmentContentTest.zip)

Run this in the usual way and execute 'npm run start' to start a local web server, there is a cert to trust inside 'security', then add the manifest.xml to your Outlook.

during onSend, this add-in gets the list of attachments on the currently composed message, then for each tries to grab the content. It seems this is quite intermittent, sometimes working and sometimes not.

The base64 content string of each attachment should be logged, but instead as you can see below, the error I mentioned in my original post is logged.

For ease of debugging the onSend method, the console statements are dumped to the message body at the end of the process and the send event blocked so the message does not go out.

![Screenshot 2022-06-23 at 11 19 44](https://user-images.githubusercontent.com/47693383/175277841-756c48a2-c224-48b1-812e-c2b4b105f782.png)

Hope this helps.

**Comment by exextoc** [comment] 2022-06-23 14:35
@carlosb1504 We are able to repro the issue with the details provided. Thanks for reporting this issue regarding the intermittent issue in getAttachmentContentAsync(). It has been put on our backlog. We, unfortunately, have no timelines to share at this point.
Internal tracking id: Eg: Office: 2887846

**Comment by exextoc** [comment] 2022-11-23 08:56
@carlosb1504 We have fixed the bug and the fix should be available in build 16.67 or later. Please update to the latest Outlook and confirm if the issue is fixed. Thanks.

**Closed as completed** 2022-12-02 11:01 UTC
Labels: Area: Outlook, Type: product bug, Needs: author feedback, Status: fixed

**Comment by ikexq** [comment] 2023-09-18 21:57
Hi, there appears to have been a regression in a recent version of Outlook that has reintroduced this bug on macOS at a minimum.

Using the same test projected provided above, `getAttachmentContentAsync` returns a `5001 - An internal error has occurred` on macOS. Testing the same on the web does not yield that error.

**macOS + Outlook version 16.77 (23091003)**
<img width="1367" alt="Screenshot 2023-09-18 at 2 51 46 PM" src="https://github.com/OfficeDev/office-js/assets/80374455/aebf1752-f3fa-4e32-a055-5c2687f56765">

**Web (Microsoft Edge)**
<img width="988" alt="Screenshot 2023-09-18 at 2 24 50 PM" src="https://github.com/OfficeDev/office-js/assets/80374455/89df276c-59a7-4c58-a9bc-8d8a66a36b9d">

Please let me know if we need to open a different ticket for this one, as we have a project that is affected by this.
