### ISSUE TITLE
Outlook Addin API body.getAsync missing some styles on mac

### ISSUE THREAD

**Issue by bchenhs** [OfficeDev/office-js#149] opened 2018-05-21 15:00 UTC
Office.context.mailbox.item.body.getAsync() on mac misses certain styles, such as bullet points.

Details:
- CoercionType.Html is used.
- Only occurs on Outlook for Mac client, not on OWA.

## Expected Behavior
Insert the following bullet in message body using the client UI:
`• Testing bullets`

## Current Behavior
Call getAsync and receive the following:
`<p class=MsoListParagraph style='text-indent:0in'>Testing bullets</p>`
Call setAsync and expect the bullet to disappear:
`Testing bullets`

## Steps to Reproduce, or Live Example
See above

## Context
I understand the documentation indicates:
`Body.getAsync and Body.setAsync methods are not idempotent.`
But the bullet is inserted from the Outlook UI itself and I expect the API to fully support it.

## Your Environment
- Outlook for Mac Version 16.13
- macOS High Sierra 10.13.2

Stackoverflow question here:
https://stackoverflow.com/questions/50451394/outlook-addin-api-body-getasync-missing-some-styles-on-mac

**Comment by bchenhs** [comment] 2018-05-22 19:14
@mlafleur Thanks for tagging the issue and responding on stackoverflow.

For the Outlook team, is there an alternative way to get/set the body HTML (from a javascript addin) during message compose that we can look into, before this issue is investigated/resolved?

Thanks.

**Comment by macOutlookExtensibility** [comment] 2018-05-30 15:30
Thanks for raising it. We are working on towards fixing it.

**Comment by bchenhs** [comment] 2018-09-20 13:08
@macOutlookExtensibility Hi, is there an update on this issue or ETA for the fix? Thanks.

**Comment by bchenhs** [comment] 2018-10-19 18:40
@macOutlookExtensibility @exextoc Any updates on the fix progress? We have many clients affected by this issue. Thanks.

**Comment by vyazadji** [comment] 2019-03-11 13:57
@macOutlookExtensibility @exextoc Any updates ?

**Comment by vyazadji** [comment] 2019-03-13 15:30
As a workaround you can save it Exchange:

`Office.context.mailbox.item.saveAsync()`

and then get the body via 

`Office.context.mailbox.makeEwsRequestAsync()`

**Comment by vyazadji** [comment] 2019-05-20 14:37
;(

**Comment by ElizabethSamuel-MSFT** [comment] 2019-10-28 17:50
@macOutlookExtensibility Has this issue been fixed? Thanks.

**Comment by malsabbagh** [comment] 2020-01-29 17:16
The issue is still reproducible as of today.

**Comment by bchenhs** [comment] 2020-05-07 00:28
@ElizabethSamuel-MSFT @macOutlookExtensibility Is there an update on this issue? There are other similar issues reported (e.g. https://github.com/OfficeDev/office-js/issues/402), and it impacts our add-in users on Mac.

**Comment by arturs-buls** [comment] 2020-06-15 08:31
Issue still present.... 

> As a workaround you can save it Exchange:
> 
> `Office.context.mailbox.item.saveAsync()`
> 
> and then get the body via
> 
> `Office.context.mailbox.makeEwsRequestAsync()`

Unfortunately it will not work for all cases. Per [docs](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.4#saveasync-options--callback-), it may take some time until ID can be used in API if outlook is in caching mode (afaik it is a default for Outlook desktop for Windows). Because of this - you can never be sure if you will receive current body or body from last draft save.

**Comment by vyazadji** [comment] 2020-06-15 11:14
I am no longer working on this project. But as far as I remember, we added a check that new ID after `Office.context.mailbox.item.saveAsync()` was really saved in Exchange. It looked messy, but we didn't find a better way how to do it. 

Here is more info about this issue:
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/34593391-immediate-synced-to-the-server-saveasync-to-get

**Comment by fiftydegrees** [comment] 2021-12-02 15:05
The issue is still happening; is fixing this issue still in the roadmap?

**Comment by exextoc** [comment] 2021-12-14 06:10
It is in our backlog and unfortunately we do not have a timeline to share as of now.Can you please help us understand what is the impact you are having with this issue

**Comment by fiftydegrees** [comment] 2021-12-14 07:52
Thanks @exextoc for your reply.

In our case, we provide a spellchecking tool; errors found are displayed in a task pane, and the user can click on a suggestion to apply a correction. As there is no API to replace the text at a specific index, or delete a given length at any index, we retrieve the whole text, update it, then re-inject it using `setAsync`. Unfortunately, as some pieces of styles are lost in the `getAsync`, each time the user applies a suggestion, the formatting is broken on lists.

Hope this helps to find a workaround!

**Comment by exextoc** [comment] 2021-12-22 10:10
@fiftydegrees We do not have a workaround for this yet. Can you also please share number of impacted users?

**Comment by exextoc** [comment] 2023-12-15 16:50
This issue is fixed in  New Outlook Mac version >= 16.75

**Closed as completed by exextoc** 2023-12-15 16:50 UTC
Labels: Area: Outlook, Status: fixed
