### ISSUE TITLE
Trying to upload my add-in manifest no longer works

### ISSUE THREAD

**Issue by tamarpscs** [OfficeDev/office-js#4594] opened 2024-06-24 07:23 UTC
I'm trying to upload my add-in manifest file by navigating to Add-ins > more add-ins > my add-ins > manage my add-ins > upload my add-in > browse > *choosing my xml file* > upload

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web, 
* Host [Excel, Word, PowerPoint, etc.]: All hosts
* Office version number: ______
* Operating System: Windows 11 Pro
* Browser (if using Office on the web): Chrome
* Office account is a business account
 
## Expected behavior

I expect it to allow me to navigate through the above, and then to see a message that my extension loaded successfully.  

## Current behavior

When I click "My add-ins," it quickly redirects to the office store, before I have a chance to click on "Manage my add-ins." 
Then, when I click Admin managed > Upload my add-in > ... >,
An error message appears, "Your add-in manifest is not valid."

## Steps to reproduce

1. Click "Add-ins"
2. Click "more add-ins"
3. Click "my add-ins"

# Provide additional details

1. The same xml file works on multiple other computers, with the same operating system and the same office account. 
2. It used to work on the same computer with the same file. 

## Useful screenshots

https://github.com/OfficeDev/office-js/assets/173663565/270b4404-9e4c-4eaa-bedc-a03ccb7cf27f

![image](https://github.com/OfficeDev/office-js/assets/173663565/a5e30325-88db-4b8d-b9cf-7ce9b825e965)

**Comment by shanshanzheng-dev** [comment] 2024-06-24 09:04
Hi @tamarpscs Thanks for reporting this issue. But I can not repro this. Could you try to clean browser cache?  And try again to upload your manifest. May I know if your manifest work on desktop? Thanks.
![image](https://github.com/OfficeDev/office-js/assets/125014206/fc7ecf84-d186-453a-89df-758d1747705e)

**Comment by tamarpscs** [comment] 2024-06-25 09:26
Hi @shanshanzheng-dev, thank you for responding. I tried clearing the browser cache and it still doesn't work. The manifest works on desktop. It also works on office web on other computers, so the manifest file shouldn't be the issue.

**Comment by shanshanzheng-dev** [comment] 2024-06-26 01:57
Hi @tamarpscs, your mean only one computer has this issue, right? Could you try to restart the computer? If not work, could you share your session Id?

**Comment by tamarpscs** [comment] 2024-06-26 09:18
Restarting didn't work. Which URL in cookies contains the session ID?

**Comment by shanshanzheng-dev** [comment] 2024-06-26 09:23
Yes, we can find this session id:![image](https://github.com/OfficeDev/office-js/assets/125014206/1f3810c3-ca2e-4874-bd09-299413f35be3)

**Comment by tamarpscs** [comment] 2024-06-26 09:26
Mine looks like this:
![image](https://github.com/OfficeDev/office-js/assets/173663565/6cfe2a33-1733-4464-b878-3707fca4e70f)

**Comment by shanshanzheng-dev** [comment] 2024-06-26 09:28
Could you open this url: https://www.microsoft365.com/launch/PowerPoint/?acctsw=1

**Comment by tamarpscs** [comment] 2024-06-26 09:29
Yes

**Comment by shanshanzheng-dev** [comment] 2024-06-26 09:32
Maybe you can create a powerpoint to see if you can upload your manifest? Seem like "My add-in" tab is good on my side. or could you share your manifest with me?
![image](https://github.com/OfficeDev/office-js/assets/125014206/57bea0d9-7e30-41c7-a9fd-b26f5ddf2667)

**Comment by tamarpscs** [comment] 2024-06-26 09:40
When I try to open a new blank presentation it says:
**Office Online services aren't available right now**
We're working to restore all services as soon as possible. Please check back soon. If the error persists please contact Microsoft Support for assistance along with the Url you were trying to access

**Comment by shanshanzheng-dev** [comment] 2024-06-26 09:42
Or could you try this link to create new workbook: https://www.microsoft365.com/launch/Excel/?acctsw=1

**Comment by tamarpscs** [comment] 2024-06-26 09:45
That link works to create a new workbook, but I get the same result as my original issue.

**Comment by shanshanzheng-dev** [comment] 2024-06-26 09:48
You can click File -> about to see your sessionId and build number

**Comment by yjz2021** [comment] 2024-06-26 18:15
Hi @tamarpscs, we are currently investigating this issue. Could you please provide us with the manifest? Thank you.

**Comment by danielscsc** [comment] 2024-06-27 18:49
I worked with the author of this issue.  It seems to be related to a chrome extension interfering.  I told them to report back when they gain more clarity as to which one it was.

**Comment by shanshanzheng-dev** [comment] 2024-07-05 02:43
Hi @tamarpscs Hope you have a good day. I'd like to know if you still hit this error. Since this error related to extension interfering, if possible, could you please help to check if you have installed some extensions and other good computers don't have this extension? That helps us gain more clarity to investigate root cause. Thanks a lot.

**Comment by tamarpscs** [comment] 2024-07-11 09:19
I don't know which extension it was. I had 4 extensions enabled: Google Docs Offline, Nimbus Screenshot & Screen Video Recorder, Testim Editor, and Katalon Recorder. Turning off all 4 immediately fixed the issue. But even when I enabled all 4 again, the issue did not reoccur. The issue has not reproduced since then.

**Comment by shanshanzheng-dev** [comment] 2024-07-11 09:54
Hi @tamarpscs Thanks for provide these message. Seem this issue has been mitigated, we'll close this issue. If you still need help, please feel free to re-open. We value your feedback. Thanks very much.

**Closed as completed by shanshanzheng-dev** 2024-07-11 09:54 UTC
Labels: Needs: attention :wave:, Area: add-ins platform
