### ISSUE TITLE
getComposeTypeAsync returns a 5001 error

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#4028] opened 2024-01-19 11:55 UTC
# Provide required information needed to triage your issue

We have a customer using our add-in that sees an error when we are calling the `getComposeTypeAsync` method: `{"name": "Internal Error","message":"An internal error has occurred","code":5001}`.

This customer is using "NAV ERP Solution" and this happens when creating an email from that application instead of directly within Outlook itself.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.17126.20132
 
## Expected behavior

Our add-in can use the `getComposeTypeAsync` method

## Current behavior

`getComposeTypeAsync` fails, so we must try to determine the type of email ourselves, which I do not think we can do in any reliable manner (we use `conversationId` as a proxy to meaning this is a reply, but it's incorrect in at least this use case)

## Steps to reproduce

1. Use the Signature 365 add-in (or an add-in using the above method)
2. Using the NAV ERP Solution 3rd party application create an email
3. Notice the error from Outlook add-in

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ghelyar** [comment] 2024-02-20 15:44
We are also seeing this but with slightly different repro steps.

You can reproduce this just by sharing a document from another office program e.g.
1. Create a new word document
2. Click share
3. Attach a copy instead -> Word document

![image](https://github.com/OfficeDev/office-js/assets/3225358/07e7f3d3-d80f-45b1-849b-7679599217ac)

This will open Outlook desktop, and then when an add-in tries to call `getComposeTypeAsync`, it will fail.

If called from the task pane, the devtools show `{"name": "Internal Error","message":"An internal error has occurred","code":5001}`.

It called from event-based activation, the error is just "The operation failed."

See also https://github.com/OfficeDev/office-js/issues/2084

**Comment by Oleg-O** [comment] 2024-03-14 23:54
Thanks for reporting this issue regarding getComposeTypeAsync API. I was able to reproduce it. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office:8832788.

**Comment by ghelyar** [comment] 2024-10-07 14:38
We now have a user with a full on Outlook crash when emails are created in Navision/Dynamics NAV and they try to insert a signature from the task pane (which involves calls to `getComposeTypeAsync`, `addFileAttachmentFromBase64Async` and `setSignatureAsync` - I don't know exactly which call is causing the crash). We previously worked around this by catching the error in JavaScript but we can't do this if the whole Outlook application crashes.

> Faulting application name: OUTLOOK.EXE, version: 16.0.18025.20104, time stamp: 0x66f31bfa
Faulting module name: ntdll.dll, version: 10.0.22621.4111, time stamp: 0x518e67bb
Exception code: 0xc0000374
Fault offset: 0x000000000010caa9
Faulting process ID: 0x0x41d8
Faulting application start time: 0x0x1db18b125cf3d05
Faulting application path: C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 484e96cd-6034-4dac-8b70-e27b8e9ce271

The thing all of these have in common is that it only happens when the email is created by sending a file from another application, be it Windows Explorer, another Office application, Dynamics NAV, etc.

**Comment by timwan10** [comment] 2024-10-07 20:33
For the initial issue with getComposeTypeAsync this happens because the product team missed a situation that creates emails and then has an issue figuring out what the compseType is. These are bugs and should be fixed. There are a few bugs in this area that will be fixed in the coming month. 

For the crash, it is unlikely that a call from the Web Add-in Taskapne is causing a crash... but it's not impossible. Can you provide detailed repro steps that the product team can use to reproduce the error? (i.e. without Navision/Dynamics?). 

If the customer is using COM/Add-ins other apps to access Outlook. Those can also cause a crash, but it's hard to determine the cause without more information. 

You mentioned using Windows Explorer / Office Application to repro the crash. Are there some repro steps like: 

1) Do something in Explorer / Word / Excel etc. to send a mail 
2) Call some functions from Script Lab 
3) Crash 

Alternatively if you have a crash dump let us know, and we can provide a place to upload it.

**Comment by millerds** [comment] 2024-10-17 22:27
Barring any issues, the original reported issues should be fixed in build 16.0.18227.20000

**Closed as completed by millerds** 2024-10-17 22:27 UTC
Labels: Area: Outlook, Status: in backlog
