### ISSUE TITLE
Read mode Add-In is enabled without selected item (Outlook Mac, Multi Select Support)

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#4108] opened 2024-02-07 14:16 UTC
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.81.2
* Operating System: macOS 14.3
* Browser (if using Office on the web): -
 
## Expected behavior
When no item is selected in Outlook, I expect my read mode add-in to be disabled.

## Current behavior
On Outlook for Mac, a read mode add-in (with multi select support) is enabled, even though no item is selected:
<img width="810" alt="image" src="https://github.com/OfficeDev/office-js/assets/802015/29f4ab95-99f0-4208-8a70-b3cd645f71e7">

On Outlook for Windows the behaviour is correct:
<img width="791" alt="image" src="https://github.com/OfficeDev/office-js/assets/802015/2f98041a-c3a3-4114-9e22-f520e77c3099">

When opening the add-in in this state, `Office.context.mailbox.item` is `undefined` and therefore unusable.

When disabling multi select support in the manifest, the behaviour on Outlook for Mac works as expected (disabled when no item is selected).

## Steps to reproduce
1. Create a new sample Outlook add-in with yo generator
2. Enable multi select support (https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select)
3. Sideload add-in on Outlook for Mac
4. Make sure no mail is selected
6. The add-in is enabled instead of disabled

## Link to live example(s)
Example manifest:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">
  <Id>4bca7d9d-4c1a-459e-9e0c-edb0b468d690</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Private</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Outlook Multiselect"/>
  <Description DefaultValue="Sample for multi select items."/>
  <IconUrl DefaultValue="https://localhost:3000/assets/icon-64.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:3000/assets/icon-128.png"/>
  <SupportUrl DefaultValue="https://www.duckduckgo.com/"/>
  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1"/>
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteMailbox</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.13">
          <bt:Set Name="Mailbox"/>
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">
          <DesktopFormFactor>
            <ExtensionPoint xsi:type="MessageReadCommandSurface">
              <OfficeTab id="TabDefault">
                <Group id="msgReadGroup">
                  <Label resid="GroupLabel"/>
                  <Control xsi:type="Button" id="msgReadOpenPaneButton">
                    <Label resid="TaskpaneButton.Label"/>
                    <Supertip>
                      <Title resid="TaskpaneButton.Label"/>
                      <Description resid="TaskpaneButton.Tooltip"/>
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="Icon.16x16"/>
                      <bt:Image size="32" resid="Icon.32x32"/>
                      <bt:Image size="80" resid="Icon.80x80"/>
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="Taskpane.Url"/>
                      <SupportsMultiSelect>true</SupportsMultiSelect>
                    </Action>
                  </Control>
                </Group>
              </OfficeTab>
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>
      <Resources>
        <bt:Images>
          <bt:Image id="Icon.16x16" DefaultValue="https://localhost:3000/assets/icon-16.png"/>
          <bt:Image id="Icon.32x32" DefaultValue="https://localhost:3000/assets/icon-32.png"/>
          <bt:Image id="Icon.80x80" DefaultValue="https://localhost:3000/assets/icon-80.png"/>
        </bt:Images>
        <bt:Urls>
          <bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/taskpane.html"/>
        </bt:Urls>
        <bt:ShortStrings>
          <bt:String id="GroupLabel" DefaultValue="Contoso Add-in"/>
          <bt:String id="TaskpaneButton.Label" DefaultValue="Show Taskpane"/>
        </bt:ShortStrings>
        <bt:LongStrings>
          <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Opens a pane displaying all available properties."/>
        </bt:LongStrings>
      </Resources>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
```

**Comment by rajjha-msft** [comment] 2024-02-11 11:17
Hey @manuelsidler 

This is expected behavior. We do support add-ins on zero selection. 
You can use the `getSelectedItems' Api to identify this scenario and handle it accordingly.

**Comment by manuelsidler** [comment] 2024-02-12 12:18
@rajjha-msft thanks for your answer. If it's by design, why is the behaviour different between Outlook for Windows and Outlook for Mac? Does enabling `SupportsMultiSelect` implicitly enable `SupportsNoItemContext`?

**Comment by ashleygagregory** [comment] 2024-02-20 03:09
+1

We are developing an add-in and are encountering similar issues where the Manifest and OfficeJS features/options behave differently on macOS compared to other platforms. 

The official documentation ([link](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select)) on Item Multi Select states that if you include `SupportsNoItemContext` in your manifest then this will implicitly enable `SupportsMultiSelect`. 
![image](https://github.com/OfficeDev/office-js/assets/56142786/a89511d9-6058-4917-8faa-c47fd9f4d6a8)


If, as being stated here including the option `SupportsMultiSelect` in your manifest also implicitly enables `SupportsNoItemContext` by design, can you please explain why are there two explicit manifest options since they will do the same thing? And why does the result differ depending on which Outlook client you are using?
If this is expected behaviour as stated then using either option always enables the other.

**Comment by neprasad-microsoft** [comment] 2024-02-20 04:14
Hi! Thanks for your query. 
The current behavior on Mac and Win32 is by design for multi-select add-ins. This is due to the differences in the host platform itself. Based on specific use cases in each platform, the add-in behaviour might change. We are actively investing in ensuring parity for feature sets across platforms, but that behaviour may not always be consistent. 
Also, SupportsMultiSelect does not implicitly enable SupportsNoItemContext. If the Reading Pane is OFF, the add-in will not be enabled for zero items selected.
What the document states is that SupportsNoItemContext will enable SupportsMultiselect, not vice versa.
 
If you want to ignore zero item selection scenario, they can just call GSAPI and add a check for number of items selected == 0.
If you want same behaviour across platform, then you can also make your add-in Context free which behaves same across platforms.

**Comment by manuelsidler** [comment] 2024-02-20 11:59
Thanks for your explanation. To handle this scenario on Mac, we implemented a check for number of items selected as rajjha and you suggested.

**Comment by ashleygagregory** [comment] 2024-02-21 20:59
Hi @neprasad-microsoft 

My apologies, I misconstrued some of the earlier comments and got ahead of myself with that assertion!

**Comment by shighosh-msft** [comment] 2024-02-22 06:58
Hi @manuelsidler, please confirm if this 

> Thanks for your explanation. To handle this scenario on Mac, we implemented a check for number of items selected as rajjha and you suggested.

resolves the issue for you. In that case we can close this issue. Thanks!

**Comment by manuelsidler** [comment] 2024-02-22 07:06
@shighosh-msft it's not a good user experience, but at least it's a workaround for now. 

I hope MSFT will fix this behaviour on Outlook for Mac. It doesn't make any sense to open a read mode task pane, if no item is selected.

**Comment by ajays-msft** [comment] 2024-03-01 06:50
Thank you for the feedback. Due to differences in platform specific implementations of the api, at times there will be inconsistency in behavior. If you think this is absolutely a blocker, please feel free the create a new feature request.

We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Closed as completed by ajays-msft** 2024-03-01 06:50 UTC
Labels: Area: Outlook, Resolution: by design
