### ISSUE TITLE
I can't pass information from a dialog window to parent add-in

### ISSUE THREAD

**Issue by nickxbs** [OfficeDev/office-js#1440] opened 2020-10-15 19:11 UTC
I can't pass information from a dialog window to parent add-in

## Expected Behavior
calling Office.context.ui.messageParent from displayDialog shuld notify the function registered with  addEventHandler(Office.EventType.DialogMessageReceived,...) in a Word add-in

## Current Behavior
the call does not activate the manager registered in the addin

## Steps to Reproduce, or Live Example
```
//From add-in
Office.context.ui.displayDialogAsync(`login`, { },asyncResult => {
  const dialog = asyncResult.value;
  const processMessage = (arg)=> {console.log('loggedin')}
  dialog.addEventHandler(Office.EventType.DialogMessageReceived, processMessage);
})

//From the Dialog
Office.context.ui.messageParent('Hello');

```

## Your Environment
* Platform : PC desktop
* Host: Word
* Office version number: Office365 web
* Operating System: Windows10
* Browser : Chrome

## Useful logs
![Capture](https://user-images.githubusercontent.com/1084464/96174786-1f1d7780-0f2a-11eb-89f5-2d2804eb11c6.PNG)

Maybe the problem is in the **postDialogMessage** function, the value of o.protocol.hostname is undefined

**Comment by greatescape95** [comment] 2020-10-16 11:36
I am experiencing the same issue. Oddly, when I use this url to load to office scripts: https://appsforoffice.microsoft.com/lib/1/hosted/Office.js

I get this error in the console of the dialog window:
![image](https://user-images.githubusercontent.com/11823934/96253588-2b4e1700-0fb4-11eb-87ac-ebec284de3d8.png)

When I use this url(not the casing on "office"): https://appsforoffice.microsoft.com/lib/1/hosted/office.js
I get no error in console, but it still doesnt work.

And when I use the url from the npm CDN: https://unpkg.com/@microsoft/office-js/dist/office.js
It works as expected with message being sent. I am guessing that the npm CDN still didnt get the latest version with the bug introduced.

Could you please take a look at this, as this is serious issue for word web user, that for example cant login to the app if the dialog is used for login. Thanks!

**Comment by htryggva** [comment] 2020-10-20 14:04
@lliu113 We are also seeing this problem on Edge Chromium. Users of any of our add-ins on Word for the web are unable to sign in when using the DialogAPI flow. 

**We consider this a serious issue as it makes our add-in unusable in this context.**

Note: The DialogAPI works fine on PowerPoint and Excel for the web.
Note: It actually works on IE11

**Comment by htryggva** [comment] 2020-10-29 09:43
@lliu113 @nickxbs It appears that this issue is resolved on our side 👍

**Comment by nickxbs** [comment] 2020-11-06 10:49
@htryggva we moved to npm version. I think changing cdn content without changing the endpoint should be unsafe for us.

**Comment by ToniFr** [comment] 2020-11-06 10:59
@nickxbs @htryggva Isn't it the case that Office.js team recommends using the CDN url (that is always the same) for production apps, and not npm package (see https://github.com/OfficeDev/office-js#support)? If that is the case, then why CDN tends to break? What is the safer to use in the future?

**Comment by greatescape95** [comment] 2020-11-06 11:01
@nickxbs @htryggva Isn't it the case that Office.js team recommends using the CDN url (that is always the same) for production apps, and not npm package (see https://github.com/OfficeDev/office-js#support)? If that is the case, then why CDN tends to break? What is the safer to use in the future?

**Comment by htryggva** [comment] 2020-11-09 09:13
@nickxbs @greatescape95 Happy to hear that the NPM version fixes the issue for you but our add-in is published on AppSource, which means that we have to use the CDN version according the submission guidelines:

[Certification Policies - 1120.1 Easy identification](https://docs.microsoft.com/en-us/legal/marketplace/certification-policies#11201-easy-identification)

> All Office add-ins must use the latest version of the Microsoft-hosted Office.js file at https://appsforoffice.microsoft.com/lib/1/hosted/office.js.

With that in mind, the CDN version should be the 'safe' version to use, but unfortunately that is not always the case.

**Comment by nickxbs** [comment] 2020-11-09 14:07
@htryggva @greatescape95  the lib was modified without changing the versioning of cdn. As you can see my plugin was broken overnight, due to this bug, from 25 days... This is unsafe for me.
The npm version is older but can be managed and versioned

**Comment by greatescape95** [comment] 2020-12-01 09:51
@lliu113 @nickxbs @htryggva it seems the issue is on microsoft production again! dialog api communication is not working for me in word online app, but this time there is even no error in the console. I again made the same fix as last time (using office js from npm instead from official CDN). It is bad we need to introduce these hacks in our codebase just to make basic things to work.

**Comment by lliu113** [comment] 2021-01-30 00:54
@greatescape95  - sorry for the very belated response to this. I agree that having to switch to using the npm version of officejs instead of the official CDN is not ideal. Let me open a bug to investigate. 

Just to reiterate - using the official CDN means that the messageParent API does not work. However, switching to the npm version fixes the issue.

**Comment by lliu113** [comment] 2021-05-18 17:42
@greatescape95 @nickxbs @htryggva - it looks like the fix for this was checked in in January. It should be safe to revert back to the CDN version. 

I'm going to go ahead and close this issue, please reactivate if you're still seeing this problem and we can escalate. Thanks!

**Closed as completed by lliu113** 2021-05-18 17:42 UTC
Labels: Type: product bug, Area: add-in UI, Status: fixed
