### ISSUE TITLE
OneNote Settings.saveAsync() gives failed status

### ISSUE THREAD

**Issue by YutongLi291** [OfficeDev/office-js#1456] opened 2020-10-22 23:13 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When I try to save my settings in OneNote online using saveAsync, it returns an asyncResult with error code 5001.

## Expected Behavior
The settings should be saved to the notebook for later reading.

## Current Behavior
Instead, nothing is saved since it returns an error code 5001 with status 'failed'. When refreshAsync is called later, it retrieves empty objects.

## Steps to Reproduce, or Live Example
```
Office.context.document.settings.set('Hello', 'World');
console.log(Office.context.document.settings.get('Hello')); //gets 'World' as normal
  Office.context.document.settings.saveAsync((asyncResult) => {
    console.log('Settings saved with status: ' + asyncResult.status,asyncResult.error) // this prints 'failed' and code '5001'
  });
 Office.context.document.settings.refreshAsync((asyncResult) => {
    console.log('Settings refreshed with status: ' + asyncResult.status, asyncResult.error) // this prints 'succeeded'
  });
  console.log(Office.context.document.settings.get('Hello));  //undefined
```

## Context
I'm trying to save user settings so that they will persist across sessions of the same document. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office  on the web
* Host [Excel, Word, PowerPoint, etc.]: OneNote
* Office version number: 16.0.13408.41001
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome

**Comment by PrashSMSFT** [comment] 2020-10-23 22:01
Hey Jeremy - are you sure I am the right person to be assigned this? I am not the owner for OneNote topics, hence asking.

Thanx,
Prash

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by YutongLi291** [comment] 2020-10-26 15:55
Sorry, it seems that refreshAsync should not have been included the question as I misunderstood how it works. However, my question regarding the saveAsync failed problem inside of OneNote still stands. Hope I can get a response soon!

**Comment by YutongLi291** [comment] 2020-11-10 23:37
Could I please get a response soon? Thanks!

**Comment by PrashSMSFT** [comment] 2020-11-11 07:35
I am not on the OneNote team. Hey @Linda<mailto:Linda.Cannon@microsoft.com> / @Prashant Pathak<mailto:Prashant.Pathak@microsoft.com> – can you please address Yutong’s issue?

**Comment by ElizabethSamuel-MSFT** [comment] 2021-05-14 22:35
@lindalu-MSFT Can you help get this transferred to https://github.com/OneNoteDev/OneNoteApi?

Or @YutongLi291 Can you open a new issue in the https://github.com/OneNoteDev/OneNoteApi repo and reference this issue?

The issue should then get more traction with the OneNote API team.

Thanks.

**Comment by lindalu-MSFT** [comment] 2021-05-17 16:09
@ElizabethSamuel-MSFT That repo is in a different (non-OfficeDev) org. I don't have the required permissions to transfer this issue to that repo.

**Comment by lindalu-MSFT** [comment] 2021-06-03 19:01
@ElizabethSamuel-MSFT Easiest of @YutongLi291 opens the issue in the https://github.com/OneNoteDev/OneNoteApi repo. Once the issue is cross referenced here, we can close.

**Closed as completed** 2024-03-17 20:03 UTC
Labels: Area: OneNote
