### ISSUE TITLE
Excel Add-in Custom Functions returning #VALUE! with latest Current Channel build (2306)

### ISSUE THREAD

**Issue by cidev5** [OfficeDev/office-js#3477] opened 2023-07-03 21:45 UTC
As of recently I, and a client of ours, is unable to get custom functions in instances of our add-in to return the values they normally do. 

Instead, we get the below error:

![MicrosoftTeams-image (13)](https://github.com/OfficeDev/office-js/assets/22505624/31ddc0f3-4179-49a6-b5d1-7592ba909d92)

A client has reported this is company-wide, and I am able to reproduce it. They also reported that it does not appear to happen for them on a separate laptop that does not have 2306, but a version just prior.

The custom functions themselves appear as though they should work, and no usual troubleshooting steps (removing/re-adding/refreshing the add-in) has any effect.

## Environment

* Platform: PC
* Host: Excel
* Office version number: 2306 (Build 16529.20146)
* Operating System: Windows 10 and 11 both affected

**Comment by rundongmsft** [comment] 2023-07-04 08:30
Hi @cidev5, which CFs or which add-ins are you using? I tried some CF add-ins from store in Version 2306 (Build 16529.20146) Microsoft Current Channel, they all work well. [A #VALUE error typically indicates an error in the functions' script file.](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-troubleshooting#check-for-excel-error-messages) Please check your function script file for any errors, you can also provide this file out, I can help to take a look.

**Comment by AndyH420** [comment] 2023-07-04 10:00
I'm getting the same #VALUE! issue after the upgrade to 2306. It is still working ok on a PC I have with 2305.

**Comment by cooksys21** [comment] 2023-07-04 10:20
I have also found the same issue this morning after my Excel updated to 2306. Tested on a spare machine that was still at 2305 and the add-in worked fine. Upgraded it to 2306 and it now has the same fault.

**Comment by cidev5** [comment] 2023-07-05 12:49
Hi @rundongmsft, our add-in is not intended for general public use so if I could provide you the information you've asked off-thread that would be great. How can I do that?

Further, it's all the custom functions in our add-in and only for this one client and myself when I tested to try to reproduce it in the same version of Excel. I don't think there is an issue with our custom functions file as it works for all other clients and internal users (for the time being).

**Comment by cidev5** [comment] 2023-07-05 17:48
Hi, I upgraded to the Beta channel 2307, and the issue is not happening in that version. I'm fairly confident at this point that 2306 specifically has a breaking change. More of our clients and internal users are now reporting the issue.

Can we please escalate this as it has become a business critical issue? And our add-in doesn't appear to be the only add-in affected as evidenced by the above posts.

**Comment by ZYUN-MSFT** [comment] 2023-07-06 08:19
Hi @cidev5 , thanks for the information provided. \
If possible, we'd like to know the business impact of this issue in your scenario.

BTW. We're still investigating this issue internal.\
We will back here once we have any updates.\
Thanks.

**Comment by rundongmsft** [comment] 2023-07-06 09:52
Hi @cidev5, do these affected CFs have the followings in common:

1. Send web request.
2. Has optional parameters.

We have received several similar reports in a short period of time and are working on find a stable steps to reproduce this issue. For the function script file, you can upload it to a private github repo and invite me.

**Comment by cidev5** [comment] 2023-07-06 13:44
Hi @rundongmsft, the affected CFs have in common that they all send web requests. It does not matter if the parameters are optional or not. I have tried functions that use only one required param as well as ones with optional params.

**Comment by cooksys21** [comment] 2023-07-06 14:36
FYI - One of my CFs simply returns a string with no params at all and doesn't use web requests. That also just returns #value!

**Comment by rundongmsft** [comment] 2023-07-07 08:26
Thanks @cidev5 and @cooksys21, the information you provided was helpful. There are also users in another discussion who had met the same issue, we tried almost the same environment as them (i.e. same version, same add-in account, same CFs) but everything works fine. :(
Based on your feedbacks, we speculate that this issue would be related to some different configurations of our accounts. Some regressions would only happen in sessions with certain configurations. Could you please provide us with your Excel Session ID? It's not sensitive. In this way, we can compare the differences between our two configurations, so as to find the suspicious points that cause this issue. You can find your Excel Session ID by these steps: File->Account->About Excel.
![image](https://github.com/OfficeDev/office-js/assets/73267941/9c042f31-8155-42e9-8cdf-928df975f61f)

**Comment by cidev5** [comment] 2023-07-07 13:40
Session ID: 33531747-347D-49E9-8B4A-8DBAD150C743

**Comment by rundongmsft** [comment] 2023-07-10 09:28
Hi @cidev5, May I ask if there are any of your client who have not encountered this issue after updating to 2306? Or are all your clients having this issue after the update?

**Comment by rundongmsft** [comment] 2023-07-10 09:32
Hi @AndyH420 and @cooksys21, May I ask which CFs and Add-ins did you use when you encountered this issue? Are these Add-ins installed from the store? Do they use shared runtime?

**Comment by taralex77** [comment] 2023-07-11 17:42
All our customers using Excel for Windows started to experience this issue.
It's an Excel add-in installed from the store. NOT using shared runtime.

**Comment by cooksys21** [comment] 2023-07-12 07:04
> Hi @AndyH420 and @cooksys21, May I ask which CFs and Add-ins did you use when you encountered this issue? Are these Add-ins installed from the store? Do they use shared runtime?

Ours are in-house developed CFs hosted on our M365 tenant. Not using shared runtime.

**Comment by cidev5** [comment] 2023-07-13 22:17
Hi @rundongmsft and all:

We've identified what we believe to be the cause. It would seem that javascript runtime errors will cause this.

I've produced two minimal reproducible examples:


```
/**
 * Test Function 1.
 * @customfunction TEST1
 * @returns Test 1.
 */
async function test1(): Promise<string> {
  const something = null;
  const somethingElse = something.notAvailable; // attempting to access a property on a null object
  return 'Test 1';
}
CustomFunctions.associate("TEST1", test1);

/**
 * Test Function 2.
 * @customfunction TEST2
 * @returns Test 2.
 */
async function test2(): Promise<string> {
  const config = await OfficeRuntime.storage.getItem('anything');
  return 'Test 2';
}
CustomFunctions.associate("TEST2", test2);
```


In both cases if I remove everything above the return statement within the function it returns what is expected, otherwise it returns the #VALUE! value.

In the first case we can address any areas in our code that could produce runtime errors, but in the second case, the error seems to occur not within our code, but rather within the OfficeRuntime API, where we have no control over such things.

Can you please acknowledge and let us know when we can expect a fix?

Thanks.

**Comment by rundongmsft** [comment] 2023-08-09 08:51
We have located the root cause and fixed it. If everything goes well, this issue would be resolved by the version 16.0.16626.20132.

**Comment by cooksys21** [comment] 2023-08-09 13:36
Hi @rundongmsft, could you please confirm the likely version the fix will be in. We are already on 16.0.16626.20134 (Current Channel) so past the version mentioned earlier, and still have the problem

**Comment by rundongmsft** [comment] 2023-08-10 10:19
Hi @cooksys21, the likely version would be 16.0.16626.20086 and newer version. After the update, please try to close Excel, [clear the office cache](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-windows), and restart Excel. 
The issue we fixed is relate to `OfficeRuntime.storage`, are your CFs using `OfficeRuntime.storage`? I wonder if we are in the same page. If the cache clearing does not help, please provide me a function file that can reproduce your issue so that I can determine if this is due to an incomplete fix or a new bug.

**Comment by cooksys21** [comment] 2023-08-17 08:25
Hi @rundongmsft, we do use OfficeRuntime.storage but after further investigation and simplifying a function it seems our issues are with async functions. 

This returns correctly..
/**
 * Clears a stored token from OfficeRuntime.storage
 * @customfunction CLEARTOKEN clearToken
 * @description Clears value from Office.storage. 
 * @returns {string} String containing the result.
 */
function clearToken() {
  return Promise.resolve("Hello");
}

This returns #VALUE!
/**
 * Clears a stored token from OfficeRuntime.storage
 * @customfunction CLEARTOKEN clearToken
 * @description Clears value from Office.storage. 
 * @returns {string} String containing the result.
 */
async function clearToken() {
  return "Hello";
}

**Comment by sterasaki** [comment] 2023-10-12 03:54
I have suffered with similar issue on my streaming function. `#VALUE!` error happens at first custom function call, but not at second call. 

error log lines at the first call:
```
2023/09/29 12:17:09	Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CONTOSO.FUNC, Workbook=Book1		
2023/09/29 12:17:10	Unexpected	CustomFunctions	[Execution] [Async] [End] [Failure] Function=FUNC, Workbook=Book1		
```

successful at the second call:
```
2023/09/29 12:17:38	Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CONTOSO.FUNC, Workbook=Book1		
2023/09/29 12:17:38	Medium	CustomFunctions	[Execution] [Async] [End] [Success] Function=FUNC, Workbook=Book1		
```

**Comment by montezdesousa** [comment] 2024-01-15 15:10
@sterasaki I got the same problem with async custom function. The first call randomly (sometimes it works right away) fails with `#VALUE` then it works when user refreshes the cell.

**Comment by adim1973** [comment] 2024-01-29 20:45
Same error here:
- custom functions making web requests and using OfficeRuntime.storage
- first call randomly fails, returning #VALUE error, refreshing the cell fixes the issue
- Excel on Mac, version 16.81 (24011420)
- cache cleared, Excel restarted

**Comment by montezdesousa** [comment] 2024-03-15 18:15
This bug as I described above, still persists. 

I was able to reproduce it after locally running `office.debug.js` as suggested in the [README.md](https://github.com/OfficeDev/office-js/blob/release/README.md). Running a dev server and uploading the manifest.xml to web office with a few custom functions.

The problem seems to be that custom function association `CustomFunction.associate` occurs after the office.js library is running. 

The very first time the user runs the add-in and calls a custom function (without opening task pane), it fails with `#VALUE!` because the association mapping is empty since `CFRuntime` is still initializing.

When the cell is refreshed, the association mapping `{func_name: func_def}` is already populated and the function is called without problems.

I'd expect that the function execution would wait and be `#BUSY!` until the association is ready to be used, instead of failing right away.

Hope this helps fixing the issue.

**Comment by rundongmsft** [comment] 2024-04-26 07:31
Hi @cooksys21, @sterasaki, @adim1973, @montezdesousa, the original issue was caused by `OfficeRuntime.storage.getItem` which has been fixed. Mutiple reason would case #value error, if you still encounter this error, that would be another issue. To make every scenario clear, please open a new issue item in Github with the repro steps, I will take. Dup issue is OK, I will link them. Thanks! 
BTW, I'm trying to repro the issue triggered by async functions. If there is an update, I will sync. A new opened issue item with this scenario is welcome.

**Closed as completed** 2024-07-15 05:36 UTC
Labels: Area: Excel, Needs: author feedback, Status: fixed, Area: custom functions

**Comment by hdwatts** [comment] 2024-08-02 18:58
@adim1973 @montezdesousa Did you end up finding a solution to that issue? I'm encountering the same problem.

**Comment by adim1973** [comment] 2024-08-02 19:14
I didn't see that error lately, so I can't help.

**Comment by montezdesousa** [comment] 2024-09-09 10:57
Same here, not seeing it lately
