### ISSUE TITLE
After publishing a new version on the partner center, user's Excel application crashes when attempting to update the add in

### ISSUE THREAD

**Issue by hdwatts** [OfficeDev/office-js#4423] opened 2024-05-06 16:37 UTC
# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2403 Build 16.0.17425.20176) 64-bit
* Operating System: Windows
 
## Expected behavior
Users press Update, and our add-in updates without issue.

## Current behavior
The user pressed update, their excel crashed, and when they re-opened it it had disappeared. They then went to add-ins and were able to re-add the add-in and update successfully the second time. This has occurred across 100% of our test users so far.

## Steps to reproduce
1. Publish an update to the partner center
2. Get prompted to update the add-in in Excel
3. Click "Update"
4. Excel crashes

## Context
We should be able to ship updates to users without having their Excel crash. This will lead to confusing scenarios when our add-in disappears and users have to re-add it via the add-ins menu.

## Useful logs
Here are the windows event viewer crash logs for one user.

[Excel update crash.evtx.zip](https://github.com/OfficeDev/office-js/files/15223674/Excel.update.crash.evtx.zip)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment] 2024-05-08 08:13
Hi @hdwatts  Thanks for reporting. If possible, could you please provide a manifest file?  Thanks.

**Comment by hdwatts** [comment] 2024-05-08 13:52
@shanshanzheng-dev See below:
[prod-manifest.xml.zip](https://github.com/OfficeDev/office-js/files/15249793/prod-manifest.xml.zip)

**Comment by jargil** [comment] 2024-05-10 00:04
@hdwatts - are you able to attach WinDbg to Excel and share the memory dump when it crashes?

**Comment by hdwatts** [comment] 2024-05-10 00:15
@jargil If you can provide me with steps to install the prior version from the Microsoft store I can get that for you. Unfortunately, as of now our team has all updated so I do not have a machine to test an update with.

**Comment by jargil** [comment] 2024-05-13 22:51
@hdwatts - thanks for getting back.

Could you confirm the following:
* The same machine that was crashing was able to update.
* Everyone in your team was able to update, so you don't have a repro anymore.
* Are you aware of anyone of your customers whose experiencing this problem?

Unfortunately, moving to prior versions is not a supported flow, and I cannot reproduce nor I'm aware of there being a general problem with updating of add-ins. Without a memory dump for this particular case I'll move ahead with marking this as not reproducible until we can capture more information.

**Comment by shanshanzheng-dev** [comment] 2024-05-16 06:05
Hi @hdwatts, this issue should be fixed, hope you have got expected behavior. We'll closed this issue. If you have any question, please let us know. We value your feedback. Thanks.

**Closed as completed by shanshanzheng-dev** 2024-05-16 06:05 UTC
Labels: Needs: attention :wave:, Area: Excel

**Comment by hdwatts** [comment] 2024-06-06 14:28
@shanshanzheng-dev @jargil

We deployed a new update today and I can confirm that this issue did not occur for users who previously were affected. Thank you for the fix!
