### ISSUE TITLE
General Exception in Word Javascript API when adding New List Item in New Paragraph

### ISSUE THREAD

**Issue by lwaltman** [OfficeDev/office-js#2307] opened 2021-12-13 20:11 UTC
## General Summary
Open a word document and create a new numbered list, such as:

1. Item 1
2. Item 2
3. Item 3

Select and delete text in the second element, and click a button which triggers the following function using the Word Javascript API:

```
insertNewList() {

  Word.run(async (context) => {
   
    var wholeRange = context.document.getSelection();
    await context.sync();

    return context.sync().then(async function () {
      
      var newParagraph = wholeRange.insertParagraph("New paragraph", "After");
      var list = newParagraph.startNewList();
      list.insertParagraph("Text in new list item","End");
      
      return context.sync();
    });
  });
}
```
Result: The new paragraph is added. However, adding the new list item triggers the following exception:

```
word-win32-16.01.js:26 
       Uncaught (in promise) RichApi.Error: GeneralException
    at new n (word-win32-16.01.js:26)
    at n.i.processRequestExecutorResponseMessage (word-win32-16.01.js:26)
    at word-win32-16.01.js:26
```
Another issue is that the API has no obvious way to programmatically add list items to the middle of a list, rather than the beginning or the end, which would seemingly eliminate the need for the above function.

## Your Environment
**Seems to only reproduce on desktop version according to chiz-ms**
* Word Javascript API
* Platform [PC desktop, Mac, iOS, Office on the web]:  PC desktop, Windows 10
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2111 Build 16.0.14701.20206) 64-bit 
* Operating System: Windows 10
 
## Expected behavior
The new paragraph is added and new list item is added successfully.  Ideally, the new list item will be situated within the overall list at correct place and depth.

Ideally, there would be a simple way to programmatically add list items to the middle of a list, especially at the selected range's element, rather than the beginning or the end.

## Current behavior
The new paragraph is added.  No new list item is added; and adding the new list item triggers the following exception:

```
word-win32-16.01.js:26 
       Uncaught (in promise) RichApi.Error: GeneralException
    at new n (word-win32-16.01.js:26)
    at n.i.processRequestExecutorResponseMessage (word-win32-16.01.js:26)
    at word-win32-16.01.js:26

```
## Steps to reproduce
Follows General Summary above.

Open a word document and create a new numbered list, such as:

1. Item 1
2. Item 2
3. Item 3

Select and delete text in the second element, and click a button which triggers the following function using the Word Javascript API:
```
insertNewList() {

  Word.run(async (context) => {
   
    var wholeRange = context.document.getSelection();
    await context.sync();

    return context.sync().then(async function () {
      
      var newParagraph = wholeRange.insertParagraph("New paragraph", "After");
      var list = newParagraph.startNewList();
      list.insertParagraph("Text in new list item","End");
      
      return context.sync();
    });
  });
}

**Reproduced on desktop version by chiz-ms**
```

## Context
Issue is very important for legal customers and lawyers, who often add items to existing lists.  We will use it in our new product Motionize to successfully enable our current and future customers to add items to lists. 

## Useful logs
```
word-win32-16.01.js:26 
       Uncaught (in promise) RichApi.Error: GeneralException
    at new n (word-win32-16.01.js:26)
    at n.i.processRequestExecutorResponseMessage (word-win32-16.01.js:26)
    at word-win32-16.01.js:26
```

**Comment by lwaltman** [comment] 2022-01-03 20:24
Is there any update available for this issue -- as far as a resolution?

**Comment by yihuax-msft** [comment] 2022-01-05 18:54
@lwaltman , You wrote: **"Select and delete text in the second element, and click a button which triggers......"**

Why do you need to delete the second item in the list?
What is the cursor location, or what text is selected by cursor, right before you click the button to run the javascript code?

**Comment by lwaltman** [comment] 2022-01-05 19:11
The second item ("Item 2") is deleted simply in preparation for clearly demonstrating the issue -- inserting a new paragraph with a new list into that location in the function.  The cursor location is simply right there at that item's location ("Item 2") after you delete it -- with no text selected.  Users use this functionality in this way to add new lists of sub items or a paragraph to an existing list.

The issue demonstrates that inserting a new paragraph, and starting a new list in this location in the triggering code creates a General Exception which is obviously undesirable.

The Context summarizes that the functionality to add paragraphs with lists to existing lists is important for our customers.

chiz-ms was able to duplicate the issue on desktop.

**Comment by yihuax-msft** [comment] 2022-01-05 19:15
@lwaltman Thanks for your reply.  When you say "**Select and delete text in the second element**", you meant to delete the second item's **text only** and the empty item is still there (there is still three items in the list), right?

**Comment by lwaltman** [comment] 2022-01-05 19:18
Correct.  The item is still there -- the text has been deleted.

**Comment by yihuax-msft** [comment] 2022-01-05 19:50
@lwaltman, I think the cause is that, for a paragraph that is already a list item, the API startNewList will fail.  The startNewList API requires the paragraph is NOT an existing list item. Maybe you can try this:

Word.run(async (context) => {
	var paragraph = context.document.getSelection().paragraphs.getFirst();
	paragraph.detachFromList();
	return context.sync().then(async function () {
		paragraph.insertText("New paragraph", "Replace");
		var list = paragraph.startNewList();
		list.insertParagraph("Text in new list item","End");
		return context.sync();
	});
});

You can adjust each list item's level using paragraph.listItem.level = x;

**Comment by lwaltman** [comment] 2022-01-07 22:34
Yes, technically, you can avoid the exception by detaching from the list.  However, the user would benefit much more from the capability of inserting new list items while maintaining the levels of that original list.  Essentially, inserting new list elements at the location in the original list.

By using this work around, you negate what might be the benefit of inserting at that lists location because you detach completely from that list.  It would be better if there were another workaround or fix that you could use to add items in the middle of an existing list, not necessarily just 'start','end' etc.  I will explain further.

It's complex perhaps but it would be the behavior you would expect.  Consider Microsoft Word where you simply select another list Cut, and then Paste the list into the existing list retaining all of the levels and formatting (esp. if you tab to the correct level).

**Comment by lwaltman** [comment] 2022-01-07 22:40
We would want to at least arrive at par with Word's existing behavior:   you simply select another list Cut, and then Paste the list into the existing list retaining all of the levels and formatting (esp. if you tab to the correct level).

**Comment by yihuax-msft** [comment] 2022-01-07 22:50
@lwaltman I guess you are NOT starting a new list, but starting a sub-list within this existing list, right? Then startNewList is for starting a new top level list, not for starting a child list.  Suppose paragraph p is a list item and you want to start the child list under p, you can do something like:
var level = p.listItem.level;
var pNew = p.insertParagraph("child item 1", "After");
pNew.listItem.level = level + 1;

**Comment by yihuax-msft** [comment] 2022-01-07 22:59
@lwaltman Tell me what should be after running your script, so I can make some suggestions.

**Comment by lwaltman** [comment] 2022-01-09 21:48
Thank you.  I am going through the script now to use your suggestion for a sub list.  

One weird documentation issue came up:

API documentation for insert paragraph seems to say you can use "End" for the insert location, but this causes error; the documentation for this function can be quite confusing.

insertParagraph(paragraphText: string, insertLocationString: "Before" | "After" | "Start" | "End" | "Replace"): Word.Paragraph;

In fact, you cannot use "End", you can use Before/After I believe.

**Comment by yihuax-msft** [comment] 2022-01-10 18:04
Thanks, @lwaltman. Which object's insertParagraph method is what you said? I double checked our design and we only have the following three insertParagraph methods that can use "End":
Body.InsertParagraph
ContentControl.InsertParagraph
List.InsertParagraph.

**Comment by lwaltman** [comment] 2022-01-10 18:49
Scroll down to second insertParagraph in the Paragraph object:

https://docs.microsoft.com/en-us/javascript/api/word/word.paragraph?view=word-js-preview#word-word-paragraph-insertparagraph-member(1)

insertParagraph(paragraphText: string, insertLocationString: "Before" | "After" | "Start" | "End" | "Replace"): Word.Paragraph;

**Comment by yihuax-msft** [comment] 2022-01-10 18:54
Thanks, @lwaltman, for letting us know. This is clearly a documentation error. @AbidRahman-MSFT, maybe Elizabeth can fix the issue? The metadata file is correct.

**Comment by ElizabethSamuel-MSFT** [comment] 2022-02-18 20:40
@lwaltman Thanks again for raising this issue. We're in the process of refining the docs around this type of situation. For now, please continue to refer to the parameter's description for accepted/supported values.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment] 2022-07-15 16:45
**Update**: Some changes in [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59920) relate to this issue and have been published. We're still working on further updates that can help decrease the confusion.

**Comment by ElizabethSamuel-MSFT** [comment] 2022-09-12 21:02
**Update**: Further changes coming in PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62223 that should be published today.

**Comment by ElizabethSamuel-MSFT** [comment] 2022-10-25 15:10
@lwaltman The documentation has been updated to show only Before and After as options for Word.Paragraph.insertParagraph. As such, I'll close this issue.

Thanks.

**Closed as completed by ElizabethSamuel-MSFT** 2022-10-25 15:10 UTC
Labels: Type: doc bug, Type: programming question, Area: Word, Status: fixed
