### ISSUE TITLE
Unable to load custom properties in word using word officejs API in web version

### ISSUE THREAD

**Issue by src107** [OfficeDev/office-js#3979] opened 2024-01-09 17:51 UTC
[Disclosure_document.docx](https://github.com/OfficeDev/office-js/files/13877579/Disclosure_document.docx)

# Provide required information needed to triage your issue
`
var properties = context.document.properties.customProperties;

    properties.load("key,type,value");

    await context.sync();

    console.log(properties.items);`
Code link: [Link](https://gist.github.com/src107/c697c9de9bd1301237d1c6eb19dc63a5)
When we are running the above code from scriptLab it is not loading the custom properties and it is returning an empty items array. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Web version
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.17305.41013
* Operating System: Mac
* Browser (if using Office on the web): Chrome, Firefox
 
## Expected behavior
It should load the custom properties present in the document.

## Current behavior
The same code is working and the properties are loaded in the standalone desktop version and also when it is connected to oneDrive, but not working in the web version.

## Steps to reproduce

1. Upload the attached document to oneDrive
2. Open the document in word web version
3. Run the below code in scriptLab to
`var properties = context.document.properties.customProperties;
    properties.load("key,type,value");
    await context.sync();
    console.log(properties.items);`

## Link to live example(s)
1. https://learn.microsoft.com/en-us/javascript/api/word/word.customproperty?view=word-js-preview
2. https://gist.github.com/src107/c697c9de9bd1301237d1c6eb19dc63a5

**Comment by xiruatms** [comment] 2024-01-11 04:27
Thanks for reporting this. I confirm I can repro this with onedrive.  I've created an internal work item 8653546 to track it.

**Comment by xiruatms** [comment] 2024-04-24 07:49
@src107 , the fix should be now on production, will you please take one more try and confirm whether it works for you?

**Comment by AneeVentra** [comment] 2024-04-28 15:50
@xiruatms I have tried to load custom properties for the attached document "Disclosure_document.docx". The properties are being loaded but only the property key is loaded correctly and values is shown as a new line character inspite having value for one of the properties. ("
        ")
Attaching the response.
<img width="560" alt="Output" src="https://github.com/OfficeDev/office-js/assets/156987943/57e271af-f2cb-4811-aa6b-231c8b4aa69e">
<img width="258" alt="Response" src="https://github.com/OfficeDev/office-js/assets/156987943/e6ab4a8e-86f2-49ad-aea4-4998736191d9">

**Comment by src107** [comment] 2024-04-30 05:14
Hi @xiruatms, can you please look into it, it looks it is been partially fixed

**Comment by xiruatms** [comment] 2024-04-30 05:28
@src107 , @AneeVentra , sorry for late response. Just want to align with you: in the document, "Document ID" should be empty, but "Disclosure Number" should be a valid string "DISC0010105". Correct?

**Comment by AneeVentra** [comment] 2024-04-30 05:42
Yes @xiruatms, that is correct. "Disclosure Number" should have value of "DISC0010105" and "Document ID" should be empty.

**Comment by xiruatms** [comment] 2024-04-30 05:53
@AneeVentra , thanks for your confirmation, I'll take further investigation on it.

**Comment by venudoddi** [comment] 2024-05-16 06:16
Hi @xiruatms, do you have any additional findings on the issue reported? Any approximate ETA on the resolution?

**Comment by xiruatms** [comment] 2024-05-16 06:35
@venudoddi , thanks for checking. The fix is committed and in roll-out process. I check with my account on OneDrive, it works as following:
![image](https://github.com/OfficeDev/office-js/assets/40648203/5c86b1df-aa0e-43c5-bc57-77d3bfb46fca)

Will you please help to take a try to see whether it works for you?

**Comment by AneeVentra** [comment] 2024-05-17 04:13
@xiruatms, when I tried to load the custom properties, I could see both the properties being printed.
But when I download the document from oneDrive and open the document, I'm able to see only one property (Disclosure Number). Can you please check if there is any issue here.

<img width="856" alt="OfficeJS_Issue_Fix" src="https://github.com/OfficeDev/office-js/assets/156987943/8618f998-7493-4d9a-9ae0-9438e62fb9e0">

<img width="496" alt="customProperties" src="https://github.com/OfficeDev/office-js/assets/156987943/37c94b8b-6142-485d-a991-43e7dfe2a3fe">

**Comment by xiruatms** [comment] 2024-05-17 05:53
@venudoddi , thanks for your confirmation.

I've done as you mentioned: download the file from OneDrive, and open in Word on MacOS, it works for me.

![image](https://github.com/OfficeDev/office-js/assets/40648203/364091d5-0829-428f-81d8-fb1c390d8497)

Please correct me if there're any misunderstanding here.

**Comment by AneeVentra** [comment] 2024-05-17 08:41
The document I have tried had two custom properties with values. When printing from scriptLab, both the properties and values are getting printed correctly. But upon downloading, I'm seeing only one property. 
Can you please try with the file attached.
[Test Disclosure Template_DISC0010002.docx](https://github.com/OfficeDev/office-js/files/15346086/Test.Disclosure.Template_DISC0010002.docx)

**Comment by xiruatms** [comment] 2024-05-17 08:58
@AneeVentra , thanks for providing more details.

I can repro your issues. Based on current investigation, it should not be an API issue (as you confirmed, 2 were retrieved correctly with APIs). The issue might be happening with another feature with Word Desktop. I might transfer your question to other teams.

One more question regarding the testing document: how did you generate such a document? (I'm asking given I noticed differences in the ooxml format for those testing document).

**Comment by AneeVentra** [comment] 2024-05-17 19:31
We use Docx4j APIs to add custom properties to the inputstream of a word document and create a new document with the outputStream after adding the custom properties.

**Comment by xiruatms** [comment] 2024-05-28 09:13
@AneeVentra , I've created a ticket 9028996 to track this internally.

In the meantime, for you as a workaround: if you can, please make sure to add the custom properties in a strict format:

Instead of:
![image](https://github.com/OfficeDev/office-js/assets/40648203/79dab448-b208-4d21-a3fd-4ca9c36b6279)


Make sure as following:
![image](https://github.com/OfficeDev/office-js/assets/40648203/4f43c15a-43f6-40d7-a98d-c290b7f1866f)

**Closed as completed** 2024-06-11 14:39 UTC
Labels: Needs: author feedback, Area: Word, Status: fixed, Status: no recent activity
