### ISSUE TITLE
add-ins crash when using window.location.href on Excel O365 desktop, but Excel 2016 is fine.

### ISSUE THREAD

**Issue by ruei-yu-yang** [OfficeDev/office-js#2675] opened 2022-06-30 06:09 UTC
In the excel add-ins developed by us, it allows users to switch to different site in add-ins content for different usage scenarios. When using Excel O365 to redirect page (window.location.href etc.), it will cause the addins to crash (On average 5 times may be successful 1 time), and the error information cannot be recorded in the inspect tool, but in Excel 2016 is work, the problem happened at the beginning of this year, last year it was working fine.

## Your Environment
* Platform: PC desktop
* Host: Excel
* Office version number: Excel 365 Version 2205 (Build 15225.20288)
* Operating System: Windows 10 (Version 21H2, OS build 19044.1766)
 
## Expected behavior
Excel O365 uses window.location.href, etc. for page redirection, which can be fine as Excel 2016.

## Current behavior
When my program executes windows.location.href = '<url>' in Excel O365, the add-ins will crash.

## Steps to reproduce
1. Loaded add-ins in O365 desktop.
2. click link / button to executes windows.location.href = '<url>'.
3. add-ins will crash. and show ADD-IN ERROR.

## Useful logs
- [ v ] Screenshots
![add-ins redirect page error in o365](https://user-images.githubusercontent.com/28371625/176604686-a5a1a577-045b-443b-b2b3-af3e729f5471.png)

**Comment by ruei-yu-yang** [comment] 2022-07-18 03:46
Hi @keyur32  , have any feedback? Thank you!

**Comment by keyur32** [comment] 2022-07-18 21:45
Sorry, I was on vacation prior. Assigning to @yaweizhu-henson for follow up (I *think* this may be a previously reported issue)

**Comment by yaweizhu-henson** [comment] 2022-07-26 04:02
Sorry for the late response, I will let engineer have a look at this issue

**Comment by ruei-yu-yang** [comment] 2022-07-27 06:37
> Sorry for the late response, I will let engineer have a look at this issue

Thank u for the trouble.

**Comment by JinghuiMS** [comment] 2022-08-29 06:44
Thanks for reaching us. 
We're actively investigating it and will let you know if there're any updates!

**Comment by JinghuiMS** [comment] 2022-08-29 08:09
@ruei-yu-yang 
Empty href attributes can cause multiple problems. I would like to suggest you use href="javascript:void(0)" or href="#" instead of href = ''.  BTW, it should be "window.location.href" not "windows.location.href". I know, it might be a typo.
Please feel free to let us know if it can't unblock your scenario!

**Comment by JinghuiMS** [comment] 2022-08-29 14:24
@ruei-yu-yang  
Could you help check your browser(webview)? Please refer to https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#microsoft-365-subscription-on-windows
![image](https://user-images.githubusercontent.com/56814588/187223766-5dfc003e-045a-4680-b040-5637108e0da2.png)

**Comment by ruei-yu-yang** [comment] 2022-09-01 08:49
> @ruei-yu-yang Empty href attributes can cause multiple problems. I would like to suggest you use href="javascript:void(0)" or href="#" instead of href = ''. BTW, it should be "window.location.href" not "windows.location.href". I know, it might be a typo. Please feel free to let us know if it can't unblock your scenario!

The window.location.href will not be empty, it will point to another add-ins site url, and this location has been added to the <AppDomain> of menifest.xml, and it can be directed to target site last year, but when using it this year, I found that an error would occur in Excel 365, but Excel 2016 can be successfully redirect to the destination site.

**Comment by ruei-yu-yang** [comment] 2022-09-01 08:50
> @ruei-yu-yang Empty href attributes can cause multiple problems. I would like to suggest you use href="javascript:void(0)" or href="#" instead of href = ''. BTW, it should be "window.location.href" not "windows.location.href". I know, it might be a typo. Please feel free to let us know if it can't unblock your scenario!

Hi @JinghuiMS,
The window.location.href will not be empty, it will point to another add-ins site url, and this location has been added to the <AppDomain> of menifest.xml, and it can be directed to target site last year, but when using it this year, I found that an error would occur in Excel 365, but Excel 2016 can be successfully redirect to the destination site.

**Comment by ruei-yu-yang** [comment] 2022-09-01 09:01
> @ruei-yu-yang Could you help check your browser(webview)? Please refer to https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#microsoft-365-subscription-on-windows ![image](https://user-images.githubusercontent.com/56814588/187223766-5dfc003e-045a-4680-b040-5637108e0da2.png)

Hi @JinghuiMS,
My OS & Excel Version Info:
OS: Windows 10 Enterprise 21H2 Build:19044.1826
Excel 365: Microsoft 365 Apps for enterprise Version 2206 (Build 15330.20264)

Manifest file not include Runtimes elements.

**Comment by JinghuiMS** [comment] 2022-09-01 09:12
@ruei-yu-yang 
Whether the target url can be accessed by customer this year or now？
In order to better locate the problem, could you give us the steps to stabilize the repro? And the files/codes required by repro if possible(please remove sensitive information before you sent to us, such as passwords, user data, etc.).

**Comment by ghost** [comment] 2022-09-06 12:02
This issue has been automatically marked as stale because it is marked as needing author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**. Thank you for your interest in Office Add-ins!

**Comment by ghost** [comment] 2022-09-09 14:02
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by JinghuiMS** [comment] 2022-09-15 03:51
We actively worked with experts in related areas, and finally reproduced this issue locally, confirming that this is a WebView related issue. 
We have created a workitem<ADO#6649810> for internal track. We will keep track of this issue and let you know if there’re any update. Thanks again for reporting this issue!

**Comment by ruei-yu-yang** [comment] 2022-09-15 04:12
> We actively worked with experts in related areas, and finally reproduced this issue locally, confirming that this is a WebView related issue. We have created a workitem<ADO#6649810> for internal track. We will keep track of this issue and let you know if there’re any update. Thanks again for reporting this issue!

Hi @JinghuiMS , thank you for making time for this issue. I really appreciate it.

**Closed as not planned** 2024-06-11 03:18 UTC
Labels: Area: Excel, Type: product bug, Status: in backlog
