### ISSUE TITLE
Urgent: Taskpane does not load in browser

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js#3158] opened 2023-02-15 23:27 UTC
Starting the last few says, when someone tries to load our add-ins, (Analytic Solver , or Analytic Solver Datamining), the ribbon loads, but the taskpane does not open. 
It either says: "Add-in Error: We couldn't get the information needed to start this add-in", or "We couldn't connect to the 'Office Store' catalog server for this add-in."

The add-ins work fine in Desktop Excel, or Excel for the Mac. The problem "only" happens in all browsers with Excel for the web.

Any help/advice would be appreciated, as we are getting many complaints.....

Edwin Straver

**Comment by EdwinStraver** [comment] 2023-02-15 23:50
Sorry, I see this is a duplicate of issue 3152....    
But it is rather bad...

**Comment by Wenjun-Gong** [comment] 2023-02-16 01:45
yes, this is duplicate with #3152

**Comment by rvendiola-fds** [comment] 2023-02-16 03:38
I'm able to reproduce this also. Same error:
![image](https://user-images.githubusercontent.com/125529004/219261851-e2004191-87d0-49e4-91a9-c5749783a957.png)

One thing I noticed is that this only affects older files, if you create a new file, then open an addin using sideloading (only way to open an addin is via sideloading because [addins from the store wont open](https://github.com/OfficeDev/office-js/issues/3152)), taskpane loads properly and custom functions will run without issues.

But if the file is old, or even if you just refresh the newly created file, the add-in won't open and will show the error above instead. 

Same with #3152, this only affects files opened from the browser.
Just commenting this information here incase this is different than #3152.

**Comment by mattgeim** [comment] 2023-02-16 19:59
Closing this as duplicate https://github.com/OfficeDev/office-js/issues/3152

@rvendiola-fds  if you are seeing a different issue please open that up for investigation - thanks!

**Closed as not planned by mattgeim** 2023-02-16 19:59 UTC
Labels: Needs: triage :mag:
