### ISSUE TITLE
OfficeJs Add-in Task Pane Width Value is Ignored by Word

### ISSUE THREAD

**Issue by rainierlugue** [OfficeDev/office-js#1629] opened 2021-02-02 04:11 UTC
## Expected Behavior
OfficeJs Add-in taskpane width value should be used as the default width of the taskpane 

## Current Behavior
OfficeJs Add-in taskpane width value is ignored by Word. The task pane always opens with the same width.

## Steps to Reproduce, or Live Example
1. Create a new document
2. Open an OfficeJs add-in task pane, like for example Script Lab Code
3. Change the width of the task pane, make it wider or narrower
4. Save the document
5. Open the previous document, open the OfficeJs add-in task pane (e.g. Script Lab Code)
6. Observe that the taskpane width is the same as the original width
7.  Open the document in Visual Studio using "Open XML Package Editor for Modern Visual Studios" extension, to inspect the openxml.
    Alternatively, replace the file extension to .zip and open the zip file
8. Open /word/webextensions/taskpanes.xml
9. Observe that the width value is set correctly, but this is ignored by Word

## Context
We have developed an OfficeJS add-in, that guides the user in completing the document. The add-in auto show when the document is opened, our users expect that the width of the task pane be remembered, the next time it is opened.

## Your Environment
* Office version number: Microsoft Word for Microsoft 365 MSO (16.0.13530.20418)
* Operating System: Windows 10 

![TaskpaneXml](https://user-images.githubusercontent.com/78396333/106551188-cb7e7a80-6568-11eb-93e4-720e963dda34.JPG)

**Comment by lliu113** [comment] 2021-02-02 20:12
@rainierlugue - thanks for bringing this up! This is actually by design, we currently don't support taskpane width persistence. Your users will need to reset the width every time. 

If this is important for your add-in, feel free to submit this as a feature request to our Uservoice - https://officespdev.uservoice.com/

Closing the issue as "by design", please reactivate if you have any more questions/feedback.

**Closed as completed by lliu113** 2021-02-02 20:12 UTC
Labels: Resolution: by design

**Comment by ralphtheninja** [comment] 2022-01-25 11:04
@lliu113 Hi. Can you please provide an alternative url to https://officespdev.uservoice.com/ ? It's no longer working. Thanks!

**Comment by smiles3983** [comment] 2022-03-09 19:17
I also would like this ability.  We have an InTRAnet application we load which gives a review feedback form the users word document.  Having it inside the task pane helps us keep context with the right document since the users work on more then one at the same time.  So the web app we run needs some elbow room in the width.  We would like to be able to set the default width from within the manifest.xml maybe, so we can set it wider just for our add-in.

**Comment by ndreisg** [comment] 2022-05-25 12:28
@ralphtheninja I think this is the new platform to submit feature requests: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Comment by abhijitrc** [comment] 2024-01-22 15:18
Is there any further update on this request, i am also exploring the possibility of setting Excel web add-ins task pane width.

**Comment by ndreisg** [comment] 2024-01-22 15:40
@abhijitrc Here is the [feature request](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/customize-default-task-pane-width-for-excel-add-ins/idi-p/3254715). Please upvote it :)
