### ISSUE TITLE
getAsync for TO field in Compose mode returns empty array when manually entering email address

### ISSUE THREAD

**Issue by markb-trustifi** [OfficeDev/office-js#17] opened 2017-10-17 14:08 UTC
## Expected Behavior
return email address

## Current Behavior
returns empty array when **manually** entering email address **and not clicking enter**, the address appears greyed.
returns correct value when selecting existing contact

## Steps to Reproduce, or Live Example
1) create new email
2) manually print new address in TO field. Don't select from existing contacts and don't click enter!
3) execute: 
```JS
Office.cast.item.toItemCompose(Office.context.mailbox.item).to.getAsync(res => {
            if(res.status === Office.AsyncResultStatus.Succeeded) {
                    console.log('value: ', res.value);
           }
});
```

## Your Environment
* Platform: Mac
* Host: Outlook
* Office version number: 365
* Operating System: El Capitane
* Browser (if using Office Online): Chrome + Desktop Client

**Comment by exextoc** [comment] 2017-11-21 17:38
This is expected - the API only returns recipients after they are "resolved".

**Comment by JuaneloJuanelo** [comment] 2018-07-27 17:23
closing this case as its by design.

**Closed as completed by JuaneloJuanelo** 2018-07-27 17:23 UTC
Labels: Area: Outlook
