### ISSUE TITLE
"RichApi.Error: An internal error has occurred" when using insertWorksheetsFromBase64

### ISSUE THREAD

**Issue by adim1973** [OfficeDev/office-js#3809] opened 2023-11-04 10:32 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2310 Build 16.0.16924.20054
* Operating System: Windows 11, OSX Sonoma
* Browser (if using Office on the web): Chrome, Edge, Safari
 
## Expected behavior
`insertWorksheetsFromBase64 `should work

## Current behavior
We have a React/Typescript Excel add-in which should insert a sheet from an external file into active workbook (using `insertWorksheetsFromBase64`), when a button in the sidebar is clicked. Many times clicking the button ends up with the "RichApi.Error: An internal error has occurred" error in console and the sheet is not inserted.

# Provide additional details
The error happens on Office on the web only. Everything works fine in Excel desktop Windows and Mac.
`Excel.createWorkbook` with the same base64 string seems to work fine on Office on the web.

## Context
The function used for inserting the sheet(s):
  ```
export async function insertSheets(templateName: string) {
    await Excel.run(async (context) => {
      const workbook = context.workbook;
      const worksheets = workbook.worksheets;
      worksheets.load("items");
      await context.sync();
      var sheetCount = worksheets.items.length;

      const options = {
        sheetNamesToInsert: [], // Insert all the worksheets from the source workbook.
        positionType: Excel.WorksheetPositionType.after, // Insert after the `relativeTo` sheet.
        relativeTo: worksheets.items[sheetCount - 1].id // The sheet relative to which the other worksheets will be inserted. Used with `positionType`.
      };

      // Insert the new worksheets.
      const base64string = await getTextFromFileURL(templateName);
      const addedSheets = workbook.insertWorksheetsFromBase64(base64string, options);
      await context.sync();
    });
  }

```

## Useful logs
![image](https://github.com/OfficeDev/office-js/assets/5249431/4de2b349-36c6-4b14-9be6-fc60c9ed97e0)

![image](https://github.com/OfficeDev/office-js/assets/5249431/49e2ccd4-4d49-44f2-acc5-5fb05e44204d)

**Comment by dingjin-ms** [comment] 2023-11-07 08:03
Hi @adim1973 , thank you for raising the problem!

However, I cannot reproduce the same problem. I've tried with sample code of [insertWorksheetsFromBase64](https://learn.microsoft.com/en-us/javascript/api/excel/excel.workbook?view=excel-js-preview#excel-excel-workbook-insertworksheetsfrombase64-member(1)), and it works on web by repeatedly inserting 2 different workbooks. 

The difference between the code snippet you provided and the sample code seems only to be the base64string param, so could you please try with some static base64string to reproduce the problem and share the string with us so that wo could reproduce and better identify the problem? Thank you!

**Comment by adim1973** [comment] 2023-11-07 16:15
Hi @dingjin-ms 

Hmm, it consistently works fine with a static base64 string, so it's definitely not an `insertWorksheetsFromBase64 `issue.
On the other hand, the `getTextFromFileURL` function below I'm using for getting the base64 string from a hosted text file works consistently fine if I use `Excel.createWorkbook` instead of `insertWorksheetsFromBase64`.
Any idea what could go wrong here?

Thanks a lot for your help!

  ```
async function getTextFromFileURL(templateName: string) {
    const loc = location.href;
    const fullPath = loc.substring(0, loc.lastIndexOf("/"));
    const fullUrl = fullPath + "/templates/" + templateName;
    const response = await fetch(fullUrl);
    const textResponse = await response.text();
    if (!response.ok) {
      console.log(response.statusText);
    }

    return textResponse;
  }

```

**Comment by dingjin-ms** [comment] 2023-11-08 02:43
@adim1973 Have you tried to log or debug 'getTextFromFileURL' to see if it has returned the correct base64string? Or could you please try to simplify your code like below to see if it still reproduces the error?
```
export async function insertSheets(templateName: string) {
  await Excel.run(async (context) => {
    const workbook = context.workbook;
    const options = {
      sheetNamesToInsert: [], // Insert all the worksheets from the source workbook.
      positionType: Excel.WorksheetPositionType.after, // Insert after the `relativeTo` sheet.
      relativeTo: 'Sheet1' // The sheet relative to which the other worksheets will be inserted. Used with `positionType`.
    };

    // Insert the new worksheets.
    const base64string = await getTextFromFileURL(templateName);
    const addedSheets = workbook.insertWorksheetsFromBase64(base64string, options);
    await context.sync();
  });
}
```

**Comment by adim1973** [comment] 2023-11-08 09:59
The simplified version doesn't change the behavior. I even tried without the `options `parameter for `insertWorksheetsFromBase64`, the same. The base 64 strings are coming correctly.

I noticed a pattern:
- first template insertion usually works fine
- following template insertion throw the RichApi error and the sheets are not inserted
- after refreshing the file browser tab, all template insertions are working fine

Not sure what else can be done,

**Comment by dingjin-ms** [comment] 2023-11-09 03:17
@adim1973 Thank you for more information provided. 

So actually when this problem happened, refreshing the file browser tab could be treated as a workaround? As after the refreshing, everything works fine again?

Hopefully we could find a stable repro way so that we could better identify the problem. Could you please share the failure session-id so that we could try to find some more hints from our internal log?

**Comment by SiruiSun-MSFT** [comment] 2024-04-10 03:30
Considering there is a workaround for this case. Close this issue for now. If you are still struggling in the scenario, please feel free to re-open it. Thanks!

**Closed as completed by SiruiSun-MSFT** 2024-04-10 03:30 UTC
Labels: Needs: attention :wave:, Area: Excel
