### ISSUE TITLE
[Outlook] Add-in pane within Outlook OWA now incorrectly scrolling

### ISSUE THREAD

**Issue by davidfishlock** [OfficeDev/office-js#1071] opened 2020-03-27 01:31 UTC
## Expected Behavior
A scrollable region isn't shown when it isn't required. This has visually and functionally broken all Outlook Add-ins

## Current Behavior
There is an unnecessary vertical scrollbar because a div with class "ms-Panel-commands" now has a top margin of 18px, this causes unnecessary vertical scrolling within the div of class "ms-Panel-scrollableContent".

## Steps to Reproduce, or Live Example
- Open any Addin in Outlook OWA of type MessageReadCommandSurface or MessageComposeCommandSurface and observe the add-in pane.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Outlook OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook OWA
* Office version number: N/A
* Operating System: Windows 10
* Browser (if using Office Online): Chrome, Firefox, Edge all versions

## Useful logs
![image](https://user-images.githubusercontent.com/42198746/77712054-668bf700-701e-11ea-9095-760781f73558.png)

**Comment by exextoc** [comment] 2020-03-27 03:47
Thanks for reporting this issue regarding. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by davidfishlock** [comment] 2020-03-28 02:29
@exextoc it would be great to get some indication of when this is going to be resolved as we are actively developing a new add-in. This regression appeared yesterday and affects all addins.

We're unlikely to ship and put marketing effort into a new addin if it is going to be functionally broken on release so this is going to become a blocker for us.

It seems there are a number of contributors to this:
- div.ms-Panel-commands I think was previously hidden and has a top margin of 18px, which is pushing the header down.
- div.ms-Panel-content has a hardcoded height of "calc(100vh - 50px)". The 50px value is no longer correct given the appearance of the extra commands div.
- Even by removing div.ms-Panel-commands, the vertical scrolling will still break if the browser window width is reduced to a point where a horizontal scrollbar appears, as this occupies another 16px

So either:
- Preferably a more reliable method needs to be implemented for stretching div.ms-Panel-content vertically.
- Or the ms-Panel-commands div needs to be hidden again, and the height calculation on div.ms-Panel-content should be "calc(100vh - 66px)" so the layout doesn't break when a horizontal scrollbar appears. This would however mean there is an extra 16px gap at the foot of the panel when not horizontally scrolling.

**Comment by CameronDwyer** [comment] 2020-03-30 00:08
This issue is hitting our commercial add-in and leading to a negative user experience (in some places we show our own scrollbar so this leads to unsightly double scrollbars). Please prioritize a fix since this affects ALL add-ins.

**Comment by corytheboyd** [comment] 2020-03-31 19:17
+1 This is also negatively impacting our customers.

**Comment by exextoc** [comment] 2020-04-02 04:44
We have fixed the bug and the fix should be available soon.

**Comment by tobegg** [comment] 2021-09-25 10:40
the same situation only with padding

**Comment by DmitryAvanesov** [comment] 2021-09-27 13:32
Hello!
I suddenly got the same issue, even though everything was working just fine before.

![image](https://user-images.githubusercontent.com/38003563/134918686-6d39c3b7-781e-4efa-9fef-a82215ab7a58.png)

**Comment by exextoc** [comment] 2021-09-28 07:16
@DmitryAvanesov  We are able to repro this issue. It has been put on our backlog for further investigation. We, unfortunately, have no timelines to share at this point

**Comment by CameronDwyer** [comment] 2021-09-28 07:20
I was about to log Microsoft support call and probably still will as we have our commercial add-ins hit by this problem again. Please fix ASAP.

**Comment by JuaneloJuanelo** [comment] 2021-09-28 17:56
hello folks. The team already investigated this issue, there is a fix done, we are in the process of checking it in and rollout. Thanks so much for reporting this issue, we will investigate what is causing this regression, but in the meantime expect the fix rolling out soon.

**Comment by CameronDwyer** [comment] 2021-09-28 23:35
Thanks for the updated timeline on the fix Juan ❤

**Comment by gitcnd** [comment] 2021-09-29 14:19
Maybe do not close this until it is **_actually_** fixed?  10 hours have passed, and it's still broken for me on every browser I tested.

**Comment by exextoc** [comment] 2021-09-29 14:47
@gitcnd  This issue is still open. The duplicate issue #2147 was closed. We will update this thread once the fix is rolled out.

**Comment by exextoc** [comment] 2021-09-30 15:45
The fix has been rolled out. Thank you for your patience.

**Comment by DmitryAvanesov** [comment] 2021-10-01 03:06
Yes, it seems to be fixed now. Thank you guys!

**Closed as completed** 2021-10-04 03:38 UTC
Labels: Area: Outlook, Status: fixed
