### ISSUE TITLE
[Excel] Uncaught Error: Sys.ArgumentNullException: Value cannot be null. Parameter name: conversationId

### ISSUE THREAD

**Issue by mjrforce** [OfficeDev/office-js#1556] opened 2020-12-18 00:59 UTC
I am using office JS to build my Excel add in, which authenticates into another system via oAuth. I can open the dialog like this:
```
     var dialogConnectUrl = 'https://example.com'; 
     await Office.context.ui.displayDialogAsync(
        dialogConnectUrl,
        { height: 40, width: 30, promptBeforeOpen: false },
        result => {
          if (result.status === Office.AsyncResultStatus.Failed) {
            g.state.setConnected(false);
          } else {
            connectDialog = result.value;
            connectDialog.addEventHandler(
              Office.EventType.DialogMessageReceived,
              processMessage
            );
          }
        }
      );
```
Then go through the authentication flow, but when we get to my callback page, I am getting the following error:
```
excel-web-16.00.js:26 Uncaught Sys.ArgumentNullException: Sys.ArgumentNullException: Value cannot be null.
Parameter name: conversationId
    at Function.e.create (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:93463)
    at Function.e.argumentNull (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:94121)
    at Function._validateParameterType.Function._validateParameterType (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:98661)
    at Function._validateParameter.Function._validateParameter (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:98091)
    at Function._validateParams.Function._validateParams (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:97522)
    at new Microsoft.Office.Common.ClientEndPoint (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:105066)
    at Object.connect (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:114771)
    at OSF.InitializationHelper.setAgaveHostCommunication (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:135867)
    at s (https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js:46:26421)
    at d (https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js:46:3609)
```

This is preventing Office.onReady() from being called.  Currently running in Office365 in Chrome. I haven't tested other browsers.

**Comment by lliu113** [comment] 2021-01-21 14:58
@mjrforce - sorry for the late response to this. Are you able to provide your add-in manifest so we can repro on our end? ConversationID is a parameter for Outlook, so it's odd it's throwing in Excel.

**Comment by mjrforce** [comment] 2021-01-21 16:43
@lliu113 So I've gotten past this issue. However, Now I am getting a different error.
`
error: {
code: 12011
message: "Browser restrictions prevented us from creating the dialog box. The domain of dialog box and the domain of the add-in host are not in the same security zone."
name: "Display Dialog Error"
}
`

Which is odd because the addin is using window.location.origin to build the url for the dialog box.

**Comment by lliu113** [comment] 2021-02-08 16:41
@mjrforce - thanks for the update! What did you do to get past the last issue? Would you be able to provide your add-in manifest, it would help us repro. 

Is the domain of the URL you are trying to load in your dialog the same as that of your taskpane? If it is different, did you add it as a trusted domain in the manifest?

**Comment by lliu113** [comment] 2021-04-16 16:54
@mjrforce - Adding the domain to your manifest may resolve this issue, for more information see - https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/appdomain

I'm going to go ahead and close the issue for now. Please reactivate if you need further help. Thanks!

**Closed as completed by lliu113** 2021-04-16 16:54 UTC
Labels: Needs: attention :wave:, Area: Excel

**Comment by hbnrmx** [comment] 2022-04-21 12:06
in my case, the issue seems to be related to the `hostInfoValue` item in sessionStorage.
When I remove it, the error disappears. Will try to provide a simple reproduction in #1824
