### ISSUE TITLE
Ms Office integration with DMS- greenbox

### ISSUE THREAD

**Issue by Maheshwaridiscus** [OfficeDev/office-js#3948] opened 2023-12-22 12:37 UTC
Addin name is : Greenbox for Office

Steps: 

Using MS Office word

Here you can Edit documents by opening the documents in preview screen and by clicking on “Edit” icon in the webpage

Steps for Editing the document in windows

Open the Green box application and double click the document (docx, pptx, xlsx files) to open the file
Click on “Edit” icon in the screen
Select “Edit in microsoft office”
After selecting this Pop-up will be displayed in the browser
Click on “Open word(desktop)”
Document will open in Word
Go to Insert section and click on “Add-ins”
And select the Add-ins installed already for Green box application
Login with same credentials that you opened the file for editing
Make changes you want in the file
Click on the “Save” button which will be shown in add-ins at the right side of your editing document. Placeholder will show as “upload as new version”
Once it is saved, go to Green box application and do hard refresh the browser tab
File will be saved with new changes and document version will be updated

Steps to install Add-ins in Windows

Get the Add-ins from Discus IT
Download the add-ins file ( which will be in xml file format)
Create a new folder and save the file inside it
Now right click on the folder and go to properties
Click “Sharing” tab in that and click share button
Click on dropdown button and select “Everyone”
Give “read and write” permission for everyone option and click share button
Right click the folder and copy the link and save it in notepad or some notes.
Now open Word in your system and open blank document
Go to Insert section and click on add-ins dropdown and select “manage other add-ins”
Click on Trust center → Trust center settings → Trusted add-in catalogs
Paste the URL which you saved in notepad and add it and save
 

Url of Greenbox Apps: https://greenbox.discus.solutions/greenbox/#/HomeIndex/

https://greenbox-demo.discus.solutions/greenbox/#/

Credentials: 

prashant.jadav+11@discus.solutions

admin@123

 
## Expected behavior
I want to edit documents with MS Office from Greenbox application. But while I tried to edit doc with MS Office i received an error message as shown in the attachment

https://github.com/OfficeDev/office-js/assets/154597561/75ba3768-adb0-4977-9485-bf48e40b262a

![image](https://github.com/OfficeDev/office-js/assets/154597561/458c3f6e-fa0e-4238-95ff-8dcb70693187)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by stevefengjin** [comment] 2023-12-25 01:53
Hello @Maheshwaridiscus, thank you for this question. The error message from your shared screenshot indicates a mismatch between the localhost URIs and the application ID. Have you attempted to debug from that perspective?

**Comment by Maheshwaridiscus** [comment] 2023-12-25 04:13
> Hello @Maheshwaridiscus, thank you for this question. The error message from your shared screenshot indicates a mismatch between the localhost URIs and the application ID. Have you attempted to debug from that perspective?

Thank you so much @stevefengjin for your response. I didnt attemp it as i am not aware how to run it?

**Comment by stevefengjin** [comment] 2023-12-25 05:44
> > Hello @Maheshwaridiscus, thank you for this question. The error message from your shared screenshot indicates a mismatch between the localhost URIs and the application ID. Have you attempted to debug from that perspective?
> 
> Thank you so much @stevefengjin for your response. I didnt attemp it as i am not aware how to run it?

As indicated in the error message, it provided a short URL for more information, and the details are provided in this article: https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50011-redirect-uri-mismatch please give it a try as this looks like a mismatch issue.

**Comment by stevefengjin** [comment] 2023-12-29 01:01
We are closing this as this seems an external debugging issue, not a bug with our product, please consider following suggested article to debug, or if you have a programming question, we suggest you visit: https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html, see if your question has already answered or ask a new question. Thanks!

**Closed as completed by stevefengjin** 2023-12-29 01:01 UTC
Labels: Resolution: external, Resolution: not actionable, Area: DevX
