### ISSUE TITLE
Office.onReady results don't match documentation

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/office-js#306] opened 2018-11-26 08:08 UTC
## Expected Behavior

According to the `Office.onReady` Typescript documentation "...it can also be used outside the add-in. In that case, once Office.js determines that it is running outside of an Office host application, it will call the callback and resolve the promise with "null" for both the host and platform."

Thus, I am expecting both host and platform to be null when opening my app in the browser, inside onReady.

## Current Behavior

Reading the host/application after Office.onReady after launching an application in the browser shows: 
Host: "Excel" Platform: "PC"

This is especially weird given I'm on a Mac. As a workaround, I use `if (!isEmpty(Office.context))` to check if I'm in or out of Word.

## Steps to Reproduce, or Live Example

    Office.onReady()
        .then((info): any => {
            console.log(info.host, info.platform);
	});

    Office.onReady((info: any) => {
        console.log(info.host, info.platform);
    });

## Context

I'm trying to do some basic UI testing with VS Code debugging, and also run an addin in Word without needing to recompile.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: MAC
* Host [Excel, Word, PowerPoint, etc.]: WORD
* Office version number: 16.19 (181109)
* Operating System: MOJAVE
* Browser (if using Office Online): CHROME 70.0.3538.102

**Comment by JuaneloJuanelo** [comment] 2018-11-26 18:11
this is a known issue and we are working to update our JS CDN soon with a fix. thanks!

**Comment by JuaneloJuanelo** [comment] 2018-11-26 18:12
this is duplicate of this issue, so closing this one as such..
https://github.com/OfficeDev/office-js/issues/301

**Closed as completed by JuaneloJuanelo** 2018-11-26 18:12 UTC
