### ISSUE TITLE
Excel Taskpane Addin on Edge looses cookies

### ISSUE THREAD

**Issue by Moby-dev** [OfficeDev/office-js#846] opened 2019-11-14 10:20 UTC
## Expected Behavior

Without closing the current Excel document, showing repeatedly the Taskpane in an Excel Addin  should preserve cookies.

## Current Behavior

The issue is present only If Excel uses *Edge* to host the Addin in the Taskpane.
Instead, If Excel uses *IE* to host the Addin in the Taskpane, there is no issue.
If Excel uses *Edge* to host the Addin in the Taskpane, when the Taskpane is opened more than once, the cookies that were stored by the Addin just when it was opened the time before, are gone.

## Steps to Reproduce, or Live Example

With Yeoman generator, create a simple Taskpane Addin for React.
When your react App is loaded, in your code check if a cookie "XYZ"  exists:
```
        if (document.cookie.indexOf("XYZ") < 0) {
            console.Log("COOKIE WAS NOT FOUND. CREATING IT.");
            document.cookie = "XYZ=hello";
        }
```
When you run it, the first time you show the Taskpane, the cookie "XYZ" will be created as expected.

Then, without closing the Excel document, if you show the Taskpane again, the cookie "XYZ" should not be created again.

But if you have *Edge* in the Taskpane, the cookie "XYZ" is created again and again every time the Taskpane is opened.
Instead if you have *IE* in the Taskpane, the cookie "XYZ" is created only the first time, as expected.

## Context

This issue affects Addins that rely on cookies from 3rd party domains, acquired after authentication.

For example, in my case:
My Addin uses the OfficeDialog to authenticate to a 3rd party domain. After the OfficeDialog took me to the 3rd party authentication URL, some cookies for that domain are returned.
If i don't close or reload the Addin, the cookies are there, and the Addin can call some APIs in the 3rd party domain.
But if the Addin is reloaded, the 3rd party cookies are lost, and the user has to authenticate again.
This happens only with *Edge*, not with *IE*, in the Taskpane.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop

* Host [Excel, Word, PowerPoint, etc.]: Excel

* Office version number: Office 365 ProPlus Version 1910 (Build 12130.20272 Click-to-Run)

* Operating System: Windows 10 Enterprise Version 1903 (OS Build 18362.467)

* Browser (if using Office Online): ______

**Comment by smaremanda** [comment] 2019-11-19 20:01
@Moby-dev - Thanks for reporting the issue. I was able to repro it. We'll look into it and get back to you.

**Comment by jargil** [comment] 2019-11-22 18:35
@Moby-dev - with Edge, when you close the Taskpane the "browser" process is closed. Your cookie is not setting any expiration, thus the cookie is deleted immediately, which is the default behavior when no expiration is specified. See https://www.w3schools.com/js/js_cookies.asp

If you want your cookie to exist through taskpane reopens, then do something like what the site above suggests:

```
function setCookie(cname, cvalue, exdays) {
    var d = new Date();
    d.setTime(d.getTime() + (exdays*24*60*60*1000));
    var expires = "expires="+ d.toUTCString();
    document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
}

if (document.cookie.indexOf("XYZ") < 0) {
    console.log("Cookie not found.");
    setCookie('XYZ', 'hello', 1);
}
else
{
    console.log("Cookie found.");
}
```

**Comment by mrqzzz** [comment] 2019-11-25 09:17
@jargil - Thanks for looking into this. 
I verified that cookies with an expiration are kept.
But the Session cookies are not.
And the typical scenario is where authentication to a 3rd party domain passes a Session Cookie, that gets deleted when the "browser" process is closed.
With IE there was a "backing browser" process that kept cookies alive.
Instead with Edge there is only the "browser" process.
So the issue persists in the above scenarios, and users must repeatedly authenticate each time the Taskpane is opened with such plugins.
The 3rd party domain services won't replace Session Cookies with expiring cookies for security reasons.

**Comment by jargil** [comment] 2019-11-25 17:06
@mrqzzz - most auth providers offer a way for the user to choose if they want to persist their login, also their 2FA in case they require that, it obviously depends on which auth provider you're using, if you have that option that should help solve this.
I've taken note of your feedback, thanks!

@smaremanda FYI.

**Comment by mrqzzz** [comment] 2019-11-26 09:40
@jargil - Besides the fact that most service providers won't change their way to persist a login (at least not so soon), I would like to add more significant feedback, from a user/developer perspective.

It makes sense that any kind of "Session Object" is kept alive for the lifespan of the whole Excel/Word/Powerpoint App, not for the lifespan of the Taskpane.
So, for example, until i keep the Excel App opened, i should Login only once to a 3rd party service, until i close Excel, and all kind of Session Objects should be kept alive with Excel as well.
This is what a user and a developer would expect, and that is the way it is working now with IE.
The change that Edge introduces is undesirable, and on my opinion this should be taken in consideration.
Thanks.

**Comment by Moby-dev** [comment] 2019-12-02 09:47
@jargil , will this issue be tracked here or elsewhere?
Thank you.

**Comment by jargil** [comment] 2019-12-02 17:41
@Moby-dev - we took note of this feedback, thanks! However please know that at the moment there's no planned work to change the way this works and should be considered by design for the platform.

The best way for this type of scenarios to move forward, is to have your auth flow have an option to "remember" the user, equivalent to how most auth providers work, where you select a checkbox and moving forward you don't have to continue typing your credentials.

Also I wanted to clarify that with users still running on IE and not Edge, you can also get into this situation if you close your taskpane, and without closing the document, wait enough time for the platform to decide to close the IE process. Closing your document/workbook also causes the IE process to close, so on a second new document you'd also lose your session cookies. So really you'd need to design for this behavior regardless of IE or Edge.

Thank you again for your feedback. I'm closing this issue here.

**Closed as completed by jargil** 2019-12-02 17:41 UTC
Labels: Type: programming question, Area: Edge WebView, Resolution: by design
