### ISSUE TITLE
How do I get hold of PowerPoint JavaScript API 1.2 - its not on the CDN

### ISSUE THREAD

**Issue by waliwa** [OfficeDev/office-js#1595] opened 2021-01-14 22:35 UTC
How do I get hold of PowerPoint JavaScript API 1.2 - its not on the CDN?
Is it officially released?

**Comment by lindalu-MSFT** [comment] 2021-01-14 23:47
Closing. Dupe of https://github.com/OfficeDev/office-js/issues/1597

**Closed as completed by lindalu-MSFT** 2021-01-14 23:47 UTC
Labels: Needs: triage :mag:
