### ISSUE TITLE
Insert content control with hebrew text

### ISSUE THREAD

**Issue by VitaliyLavrenko** [OfficeDev/office-js#654] opened 2019-08-06 12:10 UTC
When insert hebrew text to Content Control it insert bad.

<img width="319" alt="Screen Shot 2019-08-06 at 15 04 09" src="https://user-images.githubusercontent.com/2865372/62538464-8b4b1880-b85b-11e9-8d1c-8b3de8dd2000.png">

## Expected Behavior

Text should be inside content control.
## Current Behavior

Now text insert near control, by using 
```js
control.insertText('שלום', Word.InsertLocation.replace);
```
## Steps to Reproduce, or Live Example
https://gist.github.com/VitaliyLavrenko/a21af8c61af8bf92439dae8f4db5c99a
Code to insert control and text:
```js
 return Word.run(function(context) {
    var range = context.document.getSelection();
    var control = range.insertContentControl();
    control.appearance = "Tags";
    control.title = "Custom";
    control.color = "green";
    control.insertText('שלום', Word.InsertLocation.replace);

    return context.sync();
  });
```
## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.25
* Operating System: Mac Os Mojave 10.14.5
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by wamaina** [comment] 2019-08-06 18:13
Thanks @VitaliyLavrenko for reporting this issue!

@weshi, I was able to reproduce this in windows as well. Could you please follow-up on this bug?

**Comment by weshi** [comment] 2019-08-07 02:22
This issue does not repro in Word Online. @JuaneloJuanelo Could you reassign this bug?

**Comment by tsabbay** [comment] 2019-08-07 03:27
FYI: We see the same thing with Arabic as well.

**Comment by tsabbay** [comment] 2019-08-11 19:50
@weshi  and @JuaneloJuanelo  Any updates regarding this?

**Comment by JuaneloJuanelo** [comment] 2019-10-01 17:41
I can repro in windows...looks like a bug , we are tracking internally with 3679427

**Comment by JuaneloJuanelo** [comment] 2019-10-02 19:39
@VitaliyLavrenko we have an update. Are you trying the API in a Right-To-Left RTL culture ?
I was able to repro your issue, but only when I try to insert the Hebrew (who is a RTL language) into a paragraph using a LTR Culture (English on this case). Mixing a RTL and LTR text in the same paragraph is kind of a corner case. It IS valid to have multiple cultures in the same document, but you need to make sure to add them, and then you will get the tool to RTL or LTR a specific paragraph. (see ribbon image below)

So, in order for this to work correctly, I suggest you to add the Hebrew culture to your Office environment. Go to File -> Options -> Languages and please add Hebrew.  Check out screenshot below.


We anyways raised the issue with the Word team, but given that there is this workaround, the fix for this potential issue might not come  in the short term. 

Please let us know if you observe a similar behavior. 
 
![RTLConfig](https://user-images.githubusercontent.com/8866386/66075668-fb4ee580-e510-11e9-9ecf-60cc4ea25cfa.png)
![ribbon](https://user-images.githubusercontent.com/8866386/66075675-fee26c80-e510-11e9-806d-db5d5e0463e4.png)

**Comment by JuaneloJuanelo** [comment] 2019-10-02 19:43
@tsabbay  my answer above applies to Arabic too and to any RTL language. thanks!

**Closed as completed** 2019-10-09 21:00 UTC
Labels: Type: product bug, Needs: author feedback, Area: Word, Resolution: has workaround, Status: no recent activity
