### ISSUE TITLE
body.contentControls not listing all content controls in my document in online version

### ISSUE THREAD

**Issue by libjosep** [OfficeDev/office-js#1382] opened 2020-09-11 11:10 UTC
I am creating a document with base64 content using `body.insertFileFromBase64()` function. The base64 content contains a content control. I also am adding a wrapper content control to the document body range. I am using `document.body.contentControls` to get all content controls in the document.

## Expected Behavior

The document contains 2 content controls: Wrapper content control added from the client-side and the content control from the base64 file content. When I print `document.body.contentControls`, it should give me 2 items

## Current Behavior

When I try to access `document.body.contentControls`, it is giving me only one item( The wrapper content control added from the client-side)

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/Libinjoseph/8ec23d02b792db348c34c9d3068a0e35
Click the "Insert Document Contents" button to insert document contents and use the "List All Content Controls" button to print `contentControls `object to console

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.13308.41005
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome

## Useful logs

- [x] Screenshots
Open XML for content control
![image](https://user-images.githubusercontent.com/28481997/92917924-93a55800-f44c-11ea-8a85-8e0107072b36.png)
- [ ] Console errors
- [ ] Test file (if only happens on a particular file)

**Comment by XiangGaoMSFT** [comment] 2020-09-14 03:45
@Libinjoseph Thanks for reporting it to us!

As the [document](https://docs.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview) states, only rich text content controls are supported.
![image](https://user-images.githubusercontent.com/38523755/93041474-39d8a400-f67f-11ea-898e-d8ca60917a6f.png)

The "MyCompany" content control is a plain text content control, so it's not returned by Office.js

To work around, you can convert it to rich text content control and re-generate base64 based on it.

I'm closing this issue as this is by-design. Please feel free to reactive if needed.

**Closed as completed by XiangGaoMSFT** 2020-09-14 03:45 UTC
Labels: Area: Word, Resolution: by design

**Comment by libjosep** [comment] 2020-09-14 04:37
In the XML for the content control `<w:text>` tag is missing. Can we do the conversion using OOXML?

**Comment by XiangGaoMSFT** [comment] 2020-09-14 05:04
To be clear, what you need to do is removing the `<w:text>` tag from the "MyCompany" content control.
You can edit the OOXML directly with any editor you like.

**Comment by libjosep** [comment] 2020-09-14 05:14
When I print the body OOXML using the  "Print OOXML" button in the scriptlab snippet, I don't see a `<w:text>` tag in the content control section (Please see the attached screenshot). In this case, how should I convert it to rich text content control?

**Comment by XiangGaoMSFT** [comment] 2020-09-14 05:25
I didn't see the "Print OOXML" button in the snippet you shared.

Anyway, the problem is the base64 you used in the snippet. You can do below things to see the OOXML
1. Find a tool to convert your base64 to file. You can find free online tools to do that.
2. Download the file. It should be a zip file.
3. Unzip the file and find file `word/document.xml`, and you can see `<w:text />` there.
![image](https://user-images.githubusercontent.com/38523755/93046893-a35faf00-f68d-11ea-9b6a-bdd078895ff4.png)

**Comment by libjosep** [comment] 2020-09-14 05:32
Updated the gist. I am looking for a solution to programmatically convert it to rich text content control

**Comment by XiangGaoMSFT** [comment] 2020-09-14 05:49
Office.js doesn't provide the functionalities to manipulate OOXML itself, and Office.js can't convert plain text content controls to rich text content control now.

You probably need to use other libraries to update the OOXML first, and then pass it to Office.js

You can also raise the request in [User Voice](https://office365.uservoice.com/) so that we may consider to add it to our product in the future.

**Comment by libjosep** [comment] 2020-09-14 05:52
Thanks for the support @XiangGaoMSFT

**Comment by XiangGaoMSFT** [comment] 2020-09-14 05:53
@Libinjoseph Glad to help :)
