### ISSUE TITLE
Automatic formatting setting in desktop apps (different in Excel Online)

### ISSUE THREAD

**Issue by Alex0cean** [OfficeDev/office-js#1722] opened 2021-03-16 10:56 UTC
You select an area in Excel and format the area with a specific style. Cells around this area are still on default styles.

If you now enter values in the surroundings, Excel desktop apps (Win and Mac - latest semi-annual channel) try to derive some styles automatically. 

For the add-in we're developing, it looks like we have not reset some styles after some layout changes.  (Note: Excel Online behaves as expected).

https://user-images.githubusercontent.com/80747078/111298030-9cbaf000-864e-11eb-88a6-b48541fbe6bc.mov

**Comment by smaremanda** [comment] 2021-03-16 18:22
@Alex0cean - can you pls share expected behavior, esp as this relates to add-ins?

**Comment by Alex0cean** [comment] 2021-03-16 19:55
Sudheer,
our expectation is that - like in Excel Online - the style of the new cells is not changing automatically, but stays as originally defined/defaulted. The automatic alignment is not straightforward and I do not understand the logic behind - some styles are changed, some not. Better to keep the original style and let the user change manually if needed. 

Thanks,
Alex

**Comment by lumine2008** [comment] 2021-03-17 01:43
Hi @Alex0cean, Thanks for your report. From the video, it looks like you observe this issue from UI directly. May I know whether you have called some JS APIs or not? if not, it seems it may not related to office-js issue.

**Comment by Alex0cean** [comment] 2021-03-17 08:20
Hi @lumine2008 , no it is not related to office-js. Just pure UI ... but it came up as "bug" from our add-in testers.

**Comment by lumine2008** [comment] 2021-03-17 10:40
Got it, Thanks Alex

**Comment by lumine2008** [comment] 2021-03-30 06:02
As this is not an office-js issue, so I am going to close this issue for now. thanks

**Closed as completed by lumine2008** 2021-03-30 06:02 UTC
Labels: Resolution: external
