### ISSUE TITLE
Office.context.mailbox.item.location object not recognized correctly

### ISSUE THREAD

**Issue by rodrigoguariento** [OfficeDev/office-js#453] opened 2019-04-01 10:44 UTC
Dears,

When we use the following code, the room created in Admin Office 365 is not treated like a "resource room":

Office.context.mailbox.item.location.setAsync('Mezanino');

The outcome is an unknown place, without Exchange tracing. Namely, when we add the same resource manually using Outlook Web or Microsoft Office Oultook, selecting the same room, the room is treated like a sort of object which permits Exchange book that time and location, and show it on its room scheduling.

Is it a bug? 

How we can add a Office.context.mailbox.item.location as an object, like does Outlook Web and Microsoft Outlook?! Actually the setAsync is seemly treating the information like a simple text without references.

The only way that I found to solve this is add the 'Mezanino' room as an attendee too, beyond the location. But do it is a jerry-rig.

![ex1](https://user-images.githubusercontent.com/25516653/55336119-c505b000-5472-11e9-8997-f28467aa0f53.png)

Using https://developer.microsoft.com/en-us/graph/graph-explorer# we can see:

![ex2](https://user-images.githubusercontent.com/25516653/55338323-dcdf3300-5476-11e9-9c58-fb0de5eefd96.png)

**Comment by exextoc** [comment] 2019-04-10 19:53
This is by design. Unfortunately, item.location does not currently support multiple locations. This has been resolved with a new Enhanced Location API that supports multiple locations. Keep in mind the API is currently in preview and may be prone to issues. Enhanced Location API is available in the [Preview API Requirement Set](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview?context=outlook%2Fcontext). You could also either use the work around like you suggested or use REST to set the locations as well.

**Closed as completed** 2019-04-17 12:49 UTC
