### ISSUE TITLE
Office.context.mailbox.item.internetMessageId has inconsistent formatting on clients

### ISSUE THREAD

**Issue by jlevenssfdc** [OfficeDev/office-js#997] opened 2020-02-20 15:23 UTC
Office.context.mailbox.item.internetMessageId has inconsistent formatting on clients

## Expected Behavior
When accessing this property, regardless of client, the return value formatting should be consistent.

## Current Behavior
On Mac and Window Outlook clients the property value is NOT wrapped in greater/less than symbols.

## Steps to Reproduce, or Live Example
Access the internetMessageId property on specified clients and view the discrepancy.  

## Context
We need a correctly formatting value that is consistent across clients.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: ~~PC Desktop~~, Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.35
* Operating System: ~~Windows~~ / OSx
* Browser (if using Office Online): n/a

## Useful logs
n/a

**Comment by exextoc** [comment] 2020-02-20 22:08
I was not able to reproduce this behavior in PC Desktop. What is the version number of Outlook on your PC Desktop?

**Comment by jlevenssfdc** [comment] 2020-02-21 21:57
@exextoc I'm sorry for including the window client in here, you are correct and it shouldn't be included here, my mistake, I'll edit this.  I am confident that we are seeing this on Mac though.

**Comment by exextoc** [comment] 2020-02-24 05:05
Thanks for reporting this issue regarding Office.context.mailbox.item.internetMessageId. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment] 2020-07-31 22:35
Internal tracking id: Office:3974112

**Comment by exextoc** [comment] 2020-08-01 00:39
Duplicate of #746 

While reviewing open GitHub Issues, I realized there were two Issues describing this product bug.

**Closed as completed by exextoc** 2020-08-01 00:39 UTC
Labels: Area: Outlook, Status: in backlog
