### ISSUE TITLE
We're sorry, we couldn't access [Add-in Name]. Make sure you have a network connection ERROR!

### ISSUE THREAD

**Issue by neptunel** [OfficeDev/office-js#3283] opened 2023-04-05 01:38 UTC
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**
I'm trying to create an email add-in on Outlook. When a user creates a New Event, add-in should populate the meeting location with the meeting link and add a body to the email for join settings. Just like Zoom and BlueJeans add-ins. I'm following [this tutorial ](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting?tabs=non-mobile) exactly. When I create an  Outlook add-in following [quick start](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial) and using Yeoman, I'm able to start and use the add-in from my localhost. However, when I tried the same thing and exactly followed the [tutorial](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting?tabs=non-mobile) , I'm getting this error in Desktop App:
<img width="1184" alt="Screenshot 2023-04-04 at 6 28 39 PM" src="https://user-images.githubusercontent.com/63646687/229958304-794fcc41-e824-4752-ac51-f91b98f75ff5.png">
On Web, Add-in takes a bit to load and gives the error below:
![Screenshot 2023-04-04 at 6 31 42 PM](https://user-images.githubusercontent.com/63646687/229958425-f0ba3378-b784-497a-a7d7-a91b0ac1c6e3.png)
When I tried to get to the localhost:3000 I'm not able to get any resource on the browser:
![Screenshot 2023-04-04 at 6 34 34 PM](https://user-images.githubusercontent.com/63646687/229958672-abb3da85-dfed-47ca-9883-a07f0c89408f.png)

Also, `npm run start` doesn't work for me it gives this error:
<img width="545" alt="Screenshot 2023-04-04 at 6 36 15 PM" src="https://user-images.githubusercontent.com/63646687/229958790-69fc4a42-5d96-40ab-b9a8-525226d1d691.png">

That's why I'm using `npm run dev-server` to start my add-in. How can I fix this issue? Please help! 
Thank you!

**Comment by AlexJerabek** [comment] 2023-04-05 18:15
Hi @neptunel,
Thanks for raising this issue. Let me transfer this to the office-js repo where product issues can be looked at by members of the team.

**Comment by AlexJerabek** [comment] 2023-04-05 18:16
Sorry, I see now this is a duplicate of #3281. I'll close this issue and triage the other one.

**Closed as completed by AlexJerabek** 2023-04-05 18:16 UTC
Labels: Needs: triage :mag:, Resolution: duplicate
