### ISSUE TITLE
WebView(Edge) control breaks the interactive functionality of all content in PPT presentation mode

### ISSUE THREAD

**Issue by tsardy** [OfficeDev/office-js#1815] opened 2021-04-21 13:00 UTC
In PPT presentation mode all WebView Controls(edge) stop responding to user actions once the user passes the slide. Meaning navigating back to already passed slides and interacting with controls on them is not possible.

## Expected Behavior
Controls remain responsive to user actions

## Current Behavior

The recent versions of the WebView(Edge) control break the interactive functionality of all content in PPT presentation mode.
Here is the description alongside a simple ppt file you can use t experience the issue.
All WebView based add-ins are affected, for the sample enclosed I have used the Microsoft Web Viewer add-in for the sake of easy reproduction… 

WebView version | Result
10.0.18362.1316 | OK
10.0.18362.329 | OK
10.0.19041.264 | Does not work
10.0.19041.746 | Does not work

In PPT presentation mode all WebView Controls stop responding to user actions once the user passes the slide. Meaning navigating back to already passed slides and interacting with controls on them is not possible.

This behavior is a deal-breaking for all of our clients running under WebView (and it is not possible for most of them to move to WebView2 – as it is the case with most of the enterprise orgs we deal with ).
As I mentioned above it was working correctly in the past but recent updates destroyed the experience.
[webviewbug.pptx](https://github.com/OfficeDev/office-js/files/6350595/webviewbug.pptx)

## Steps to Reproduce, or Live Example

* Link to live example: ______
Repro steps:
Repro steps using the enclosed ppt:
1.	Go to presentation mode
2.	Click on the web control to see it is interactive, reacts to mouse over events
3.	Click to 2nd page. Do the same test. Should be OK.
4.	Go to 3rd page, same test. Should be OK too.
5.	Go back to the 2nd slide and do the test again. The control now is not responsible, does not react to any mouse actions. 

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

This behavior is a deal breaking for all of our clients running under WebView (and it is not possible for most of them to move to WebView2 – as it is the case with most of the enterprise orgs we deal with ).

you need to fix the edge based WebView . so it works again (see above for affected versions).
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:PC
* Host [Excel, Word, PowerPoint, etc.]: Excel, PowerPoint
* Office version number: 2003 (all versions)
* Operating System: 20H2
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors  - No consol errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by tsardy** [comment] 2021-04-26 15:50
Hi @jeremy-msft,

do you have any updates on the above issue? it is very important for us. thank you!

**Comment by jeremy-msft** [comment] 2021-04-26 16:38
Hi @tsardy, tagging @smaremanda to help.  Thanks!

**Comment by tsardy** [comment] 2021-04-27 08:12
@smaremanda could you pls drop an update. thank you!

**Comment by tsardy** [comment] 2021-05-03 10:00
@smaremanda do you have any updates?

**Comment by nancy-wang** [comment] 2021-05-06 23:04
Thanks for leaving us this feedback @tsardy! I'll make sure @smaremanda from our team is notified of your issue - appreciate your understanding here.

**Comment by sohailzafar** [comment] 2021-05-10 22:05
Thank you for your patience, we will provide an update as soon as we are done investigating.

**Comment by smaremanda** [comment] 2021-05-11 00:46
@tsardy first and foremost, thanks for bringing this to our attention and my sincere apologies for the delay. I can repro the issue on WebView [legacy Edge based] but not consistently. the WebView on page 1 does respond if you wait a while, but there were certainly times when it went unresponsive. We'll be digging deeper to figure out the root cause here. In the mean time, here are some thoughts:
1. have you tested with fewer WebView controls in your ppt slide? Are you able to repro in that situation?
2. We are deploying WebView2 with Office for all monthly channels at this point - and i dont repro this issue with WebView2. What is blocking your customers from adopting WebView2?
3. Is your add-in in the Office store or is it deployed via centralized deployment? I ask this just for my information.

**Comment by tsardy** [comment] 2021-05-11 09:47
@smaremanda I just got the information via other channels that the issue was recognized and it is fixed in Windows build 21340 and higher. (i can confirm this testing the issue in Windows insider version 21376.1).
Could you check the internal status about fixing this issue for the affected versions between 20H2 and 21H1?
Enterprise clients are not that flexible in their windows and office update policy, so it is important for us to know what we can expect.
Our add-in is not in the Office store yet, since it requires a separate server component installed locally - this blocks the store verification process :-(

**Comment by smaremanda** [comment] 2021-05-11 16:33
@tsardy - good to hear you were able to confirm that this was fixed in newer builds of Windows. We are working on pushing for the backport. Will let you know what comes out of it.

**Closed as completed** 2021-07-22 07:55 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: add-ins platform
