### ISSUE TITLE
Calls to api/v2.0/me/messages/ with a REST token obtained using getcallbacktokenAsync fail with 404 for a shared folder

### ISSUE THREAD

**Issue by GrumpyAL** [OfficeDev/office-js#1146] opened 2020-05-05 15:36 UTC
Calls to api/v2.0/me/messages/ with a REST token obtained using getcallbacktokenAsync on an item in a shared mailbox fail with 404.  This was working a few weeks ago and suddenly stopped.

## Expected Behavior
When an Office Add-in has the `supportssharedmailbox` flag set to true, REST tokens obtained should work to pull messages from the shared mailbox when invoked by a user with the proper permissions.  As it did previously.

## Current Behavior
REST tokens obtained by the add-in on a shared mailbox and used to authenticate to `api/v2.0/me/messages/` return a 404:

> {"error":{"code":"ErrorInvalidMailboxItemId","message":"Item Id doesn't belong to the current mailbox."}}

## Steps to Reproduce, or Live Example
I do not have code I can share at this time, but the repro steps are simple.

### Repro Steps
  1. Load a manifest with <SupportsSharedMailboxes> set to true
  2. Invoke on an email in a shared mailbox in which you have Full Control
  3. Obtain the REST token, Item ID and REST URL using Office Add-ins Functions
      a. Office.context.mailbox.item.itemId
      b. Office.context.mailbox.restUrl
      c. Office.context.mailbox.getCallbackTokenAsync({isRest:true}, ...)
4. Using those, attempt to retrieve the item at api/v2.0/me/messages/[ITEMID]
5. A 404 is returned (this worked previously)

## Context
We have an add-in that implements <supportsharedfolders> that was tested and found to work until something changed recently.

## Your Environment

* Platform PC, Mac, OWA, iOS, Android
* Host Outlook
* Office version number: Any that supports API set 1.8 (e.g. 2004 (Build 12730.20236)
* Operating System:  Windows 10, Server 2016
* Browser (if using Office Online): Chrome, IE, Edge, Safari
* Can reproduce in PowerShell if correct information obtained through an Add-in (Token, ID, etc).

## Useful logs
{"error":{"code":"ErrorInvalidMailboxItemId","message":"Item Id doesn't belong to the current mailbox."}}

**Comment by DmitryKostochko** [comment] 2020-05-05 15:55
We are facing the same issue and need a fix ASAP. FYI, this REST API functionality worked fine a few days ago.

**Comment by exextoc** [comment] 2020-05-05 19:12
To confirm, are you seeing this for a read mode item? Does this only repro for a shared folder (items that the user is accessing are owned by someone else)? And are the mailboxes hosted on Microsoft/Office 365 instead of on-premise?

If so, to construct the rest URL for shared item, instead of using api/v2.0/me/messages/, the addin should use the info from SharedProperties, following https://docs.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-1.8.

**Comment by DmitryKostochko** [comment] 2020-05-06 09:17
>> To confirm, are you seeing this for a read mode item?

Our add-in works in the compose mode. We are using REST API to read emails from another mailbox.

>> Does this only repro for a shared folder (items that the user is accessing are owned by someone else)?

In our case, user A gave access to a folder (and all parent folders) for user B. User B got access to all emails in the folder. Note, user A did not delegate access to mailbox, just folder permissions were used.

>> And are the mailboxes hosted on Microsoft/Office 365 instead of on-premise?

Yes, both mailboxes are hosted on Microsoft 365.

@exextoc, we don't have the SupportsSharedFolders flag in our manifest, moreover, we have clients that use 1.7 and even 1.5 versions of Outlook JS. As you understand, we cannot use SharedProperties. And I think all these details are secondary, not important. The important thing is that the part of the REST API that worked for years does not work today. And no workarounds or new APIs will help all existing applications that rely on the REST API. I think this **compatibility** problem shall be fixed asap, agree? Please consider the issue from this point of view.

**Comment by GrumpyAL** [comment] 2020-05-06 12:16
Thank you for the information @exextoc.  I will create a POC with that information and see if it works for us.  

However, I do notice one thing.  When I access my mailbox via outlook.office.com (vs outlook.office365.com) the sharedProperties property `targetRestUrl` does not exist.  When I look in the network tab, I see it's trying to reach out to an autodiscover URL (`https://outlook.office.com/autodiscover/autodiscover.json/v1.0/[STMP]?Protocol=REST`) and getting a 404.  If I change my outlook URL to outlook.office365.com and run the test script again then the` targetRestUrl` property works as expected and the autodiscover URL returns properly.  Curious if this is a bug or temporary issue or if we should code a fallback to use Office.context.mailbox.restUrl in the event that sharedProperties targetRestUrl is undefined and just hope they are the same in that event.

Also, could you please explained what changed? Previously we were able to use the api/v2.0/me/messages/ end point to retrieve a message from a shared mailbox.  Unfortunately, the supportsSharedMailboxes documentation does not reference the also new sharedProperties interface documentation so we simply added that tag and saw that it worked.  I see now changes we can implement to use the sharedProperties interface, but curious if something on the back-end changed, or if there was a bug etc that allowed it to work in the first place via api/v2.0/me/messages/

Thanks very much.

**Comment by exextoc** [comment] 2020-05-07 01:54
@GrumpyAL for the missing targetRestUrl issue, to confirm, are you seeing that particular issue with OWA?
With api/v2.0/me/messages/ 'me' is meant for the calling user. This is one of the reasons we introduced the SharedProperties API for supportssharedmailbox with addins.
Thank you for you feedback on documentation, we will update based on this discussion.

**Comment by exextoc** [comment] 2020-05-07 01:55
@DmitryKostochko since your addin is for compose, and you are not using SupportsSharedFolders, could you please create a new post with more details?
Support for addins in a shared folder is introduced with 1.8 API and SupportsSharedFolders in the manifest. Having said that, some compose scenarios (eg. sending as another user) still operate within the user's mailbox, and a new post will help us understand more.

**Comment by exextoc** [comment] 2020-05-07 05:33
For reference, here's a post related to this change: https://developer.microsoft.com/en-us/office/blogs/accessing-outlook-items-in-a-users-archived-shared-or-delegated-mailboxes-using-microsoft-graph/

**Comment by GrumpyAL** [comment] 2020-05-07 12:35
> @GrumpyAL for the missing targetRestUrl issue, to confirm, are you seeing that particular issue with OWA?

@exextoc Yes, this is in OWA, when accessed via outlook.office.com

**Comment by JamesBigChange** [comment] 2020-05-07 12:40
We're in a similar position.
Thanks @GrumpyAL  for the cause of the 404 errors - that had me stumped for the last 24 hours as I had https://outlook.office.com bookmarked!
@exextoc must we tell our add-in users to use https://outlook.office365.com rather than https://outlook.office.com for Office Online?

**Comment by naemcivic** [comment] 2020-05-07 22:05
This issue seems to be similar to our issue on hand. https://github.com/OfficeDev/office-js/issues/1116 

The flow use to work up until 2 weeks ago on our end. Please help us resolve this.

**Comment by exextoc** [comment] 2020-05-10 08:42
@GrumpyAL Could you please provide the following details regarding the issue " sharedProperties property targetRestUrl does not exist in outlook.office.com?

- In which browser are you seeing this issue and is the issue consistent?
- Are you getting any errors in console while making the call to Office.context.mailbox.item.getSharedPropertiesAsync and whether other Shared Properties such as targetRestUrl, owner, delegate Permissions populating correctly?
- Are you making this call for Shared Message in Read mode?

**Comment by JamesBigChange** [comment] 2020-05-11 13:12
@exextoc hope you don't mind me adding our findings while you wait for @GrumpyAL .

When using https://outlook.office.com in the Chrome and Firefox browsers (others untested), we see a 404 error in the console for:
  https://outlook.office.com/autodiscover/autodiscover.json/v1.0/psdevelopment@bigchange.com?Protocol=REST 
at:
  getSharedPropertiesApiMethod.ts:34

targetRestUrl is NOT populated while others such as delegatePermissions, owner and targetMailbox ARE populated.

We do not see this issue when using Office Online at https://outlook.office365.com (different domain)

We are making the call in Read mode.

**Comment by exextoc** [comment] 2020-05-13 08:00
@JamesBigChange #1161 is tracking this fix.
@naemcivic This is because of a [change](https://developer.microsoft.com/en-us/office/blogs/accessing-outlook-items-in-a-users-archived-shared-or-delegated-mailboxes-using-microsoft-graph/) in Graph API, using getSharedPropertiesAsync is the solution. Our team is working towards enable this API on Outlook for Mac.
@GrumpyAL Can you respond to our queries?

**Comment by GrumpyAL** [comment] 2020-05-13 13:21
Hi @exextoc sorry for the delay.

> - In which browser are you seeing this issue and is the issue consistent?

I was testing in Chrome and using the console to input the commands.  It was consistent with the office.outlook.com URL

> - Are you getting any errors in console while making the call to Office.context.mailbox.item.getSharedPropertiesAsync and whether other Shared Properties such as targetRestUrl, owner, delegate Permissions populating correctly?

This last time I tried, I get a 503 trying to reach the autodiscover URL, thrown by getSharedPropertiesApiMethod.ts at 34

The properties I have available are:

- DelegatePermissions
- owner
- targetMailbox

targetRestURL is missing / undefined

> - Are you making this call for Shared Message in Read mode?

This is in the context of an add-in in read mode with the add-in frame open.  The add-in has declared the "supportsSharedFolders" tag in the manifest.

Please let me know if you need additional information.

**Comment by GrumpyAL** [comment] 2020-05-13 15:27
I think we're seeing the same thing as @JamesBigChange and as stated in #1161 as well.  Just sometimes it can be a 503, other times a 404.  But the end result is the same, the targetRestUrl property is undefined.

![image](https://user-images.githubusercontent.com/28786762/81832614-ba8a6680-950c-11ea-9a18-ece85fc8b52a.png)

**Comment by exextoc** [comment] 2020-05-14 07:32
Thanks for the confirmation @GrumpyAL please use #1161  to track

**Comment by davyarris** [comment] 2020-06-24 06:46
I would like to please request that this issue is reopened considering that the linked issue has not been resolved.

### Summary
[**Office.context.mailbox.item.getSharedPropertiesAsync**](https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-1.8#getsharedpropertiesasync-options--callback-) method returns an instance of [**Office.SharedProperties**](https://docs.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-1.8) that should contain targetRestUrl but doesn't.

### Outline
We are using Office JS API to get information for the current message that the user is viewing in a shared mailbox. We require ability to build up a full Outlook REST API URL to the message. 
In order to build up this URL we need the base URL which for shared messages requires a call to **Office.context.mailbox.item.getSharedPropertiesAsync(...)** (see [getSharedPropertiesAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-1.8#getsharedpropertiesasync-options--callback-)) which then returns via callback a result of type **Office.SharedProperties** (see [SharedProperties](https://docs.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-1.8)).
This returns fine except there is a glaring omission of the **targetRestUrl** without which we are unable to build up a valid URL for subsequent calls to the Outlook REST API.

The user has delegated permissions.

### Steps to Reproduce

1. Create addin manifest, that will allow usage in shared mailboxes with properly set **SupportsSharedFolders** in it.
2. Deploy the addin to https://outlook.office.com/
3. Open the addin for a message in a shared mailbox for **_which the user has delegated permissions_**
4. Execute Rest request to obtain data for the currently viewed mail

```
Office.context.mailbox.getCallbackTokenAsync({
    isRest: true
}, function (result) {
    var id = Office.context.mailbox.convertToRestId(Office.context.mailbox.item.itemId, Office.MailboxEnums.RestVersion.v2_0);
    if (result.status === "succeeded") {
        window.Office.context.mailbox.item.getSharedPropertiesAsync(function (options) {
            if (options.status === "succeeded") {
                if(!options.value.targetRestUrl)
                        // ERROR: this property should be populated!!
                        console.error("No targetRestUrl was returned");
                else {
                        // we are all happy do fetch
                        fetch(options.value.targetRestUrl + "/v2.0/users/" + options.value.targetMailbox + "/messages/" + id
                    , {
                        headers: {
                            'Authorization': "Bearer " + result.value,
                            'Content-Type': 'application/json'
                        }
                    }
                ).then(function (r) {
                    console.log(r);
                }).catch(function (e) {
                    console.log("error:", e)
                });
            } else {
                console.log("Error fetching shared options");
            }
        });
    } else {
        console.log("Error obtaining token.");
    }
});

```
### NOTE: 
This is not the same as #1140  - The call to getSharedPropertiesAsync returns successfully but the targetRestUrl is absent.

While this is similar to #1161 - that ticket has been closed because _it failed to outline clearly the result of the issue_ being that there is no way to construct a valid REST URL to the delegated shared resource (message or calendar item). To spell it out the **Office.context.mailbox.item.getSharedPropertiesAsync** method returns an object that should contain targetRestUrl but doesn't.

**Comment by GrumpyAL** [comment] 2021-02-08 14:33
> To confirm, are you seeing this for a read mode item? Does this only repro for a shared folder (items that the user is accessing are owned by someone else)? And are the mailboxes hosted on Microsoft/Office 365 instead of on-premise?
> 
> If so, to construct the rest URL for shared item, instead of using api/v2.0/me/messages/, the addin should use the info from SharedProperties, following https://docs.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-1.8.

@exextoc I'm seeing this reverted again in a shared mailbox:

1. If I get an item ID for a shared item and...
2. Get a rest token using getCallbackTokenAsync(isRest:true) and...
3. Construct the rest URl using the /me/messages endpoint

I am able to pull the message, however, I don't expect this to work per the blog post linked above:

https://developer.microsoft.com/en-us/office/blogs/accessing-outlook-items-in-a-users-archived-shared-or-delegated-mailboxes-using-microsoft-graph/

The result of this is that we're able to pull emails from shared mailboxes in unsupported scenarios (https://github.com/OfficeDev/office-js/issues/1295) but in an unintended way.

I'm wondering if what we're seeing here is a bug and that the ability to pull an item from another mailbox using the /me endpoint is unintentionally or if this was reverted intentionally.

Thanks!

**Comment by exextoc** [comment] 2021-02-10 13:22
Is it started happening for Read or compose Item or both?

**Comment by GrumpyAL** [comment] 2021-02-10 13:29
Read.  It's almost as if it's working the way it was previously.  Per the blog post this was the wrong way to access shared items and it was disabled.

The odd behavior I'm seeing is that it's "working" when I use "Open Another Mailbox" but only because the sharedProperties interface isn't available so we're using the /me endpoint thinking we're not in a shared scenario and for some reason the /me endpoint is allowing us to access that mail item that belongs in another mailbox.

**Comment by exextoc** [comment] 2021-03-21 17:38
Hey @GrumpyAL ,

It should not be possible to access the /me API for a different mailbox. Is it possible for you to share a fiddler trace for this repro, and we can have a look?

You can share the trace at this email ID: admin@M365x010952.onmicrosoft.com

**Comment by GrumpyAL** [comment] 2021-03-25 17:04
Sorry for the delayed response here.  I will test and share the trace as soon as I can.  It may be a few more days.  Thanks!

**Comment by GrumpyAL** [comment] 2021-04-05 18:37
I apologize, it appears my initial assessment was incorrect.  It's not successfully getting a shared mailbox at the /me API.  What's happening in my case is that I'm automatically trying the EWS API and that is working to allow me to pull the message from another mailbox using the EWS callback token obtained (which is a token for the user and not the mailbox).

So not a change related to the REST API at all. But what is happening:

1. Invoke add-in on a shared mailbox item
2. Get itemID and EWS callback token and URL
3. Backend can pull the mail item using the EWS URL, Callback token and item ID

I can't recall if EWS tokens worked in this way before (or if it was possible to get an EWS token in a shared item).  I thought that previously I wasn't able to pull with EWS at all in this scenario so when it started working again (to my surprise) I thought it was REST (and I can't recall the steps I took to ensure it was REST like a manual GET or checking via Fiddler). Sorry for any confusion!

**Comment by exextoc** [comment] 2021-04-06 07:49
Sure. 
Feel free to close the issue if it's resolved.

**Comment by GrumpyAL** [comment] 2021-04-06 13:33
Do you happen to know if EWS working this way is intentional? Should we be able to pull a shared item like this, is it a valid attempt to make when the shared interface isn't available?

**Comment by exextoc** [comment] 2021-04-11 19:56
The behaviour of EWS for Exchange mailbox items can be found here : https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-work-with-exchange-mailbox-items-by-using-ews-in-exchange

The behaviour of EWS when used as delegate can be found here : https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-access-email-as-a-delegate-by-using-ews-in-exchange

And more can be found about EWS shared folder behaviour here : https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/public-folder-access-with-ews-in-exchange#:~:text=EWS%20can%20provide%20the%20access,out%20of%20a%20public%20folder.

Please close the issue if the original issue is resolved. 
Feel free to create a new issue if you have doubts regarding behaviour.

**Closed as completed** 2021-04-12 12:47 UTC
Labels: Needs: attention :wave:, Area: Outlook
