### ISSUE TITLE
MSWord: After calling section.getHeader("Primary") multiple headerReferences and footerReferences are added to .docx xml

### ISSUE THREAD

**Issue by dgtllion** [OfficeDev/office-js#1904] opened 2021-06-03 07:14 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When i open new document and extract XMLs within `.docx` file i see these references:
```
<w:headerReference r:id='rId8'
                   w:type='default'/>
<w:footerReference r:id='rId9'
                   w:type='default'/>
```
But after running this code below i get multiple headerReferences and footerReferences:
```
Word.run(async context => {
    const sections = context.document.sections;
    sections.load();
    return context.sync().then(function () {
        sections.items[0].getHeader("Primary"); //This line adds multiple references

        return context.sync().then(r => {
           return new Promise((resolve, reject) => {
               resolve();
           });
        }).catch(handleError);
     }).catch(handleError);
}).catch(handleError);
```

# Provide required information needed to triage your issue

## Your Environment
* Platform: Mac
* Host: Word
* Office version number: 16.49 (21050901)
* Operating System: macOS
 
## Expected behavior
By getting or inserting data into header `section.getHeader("Primary")` the references will remain as is.
```
<w:headerReference r:id='rId8'
                   w:type='default'/>
<w:footerReference r:id='rId9'
                   w:type='default'/>
```

## Current behavior
Without inserting/adding new Headers or Footers i get multi references by calling `section.getHeader("Primary")`
```
<w:headerReference r:id='rId9'
                   w:type='even'/>
<w:headerReference r:id='rId10'
                   w:type='default'/>
<w:footerReference r:id='rId11'
                   w:type='even'/>
<w:footerReference r:id='rId12'
                   w:type='default'/>
<w:headerReference r:id='rId13'
                   w:type='first'/>
<w:footerReference r:id='rId14'
                   w:type='first'/>
```

**Comment by yihuax-zz** [comment] 2021-06-04 23:00
Let me file a bug and then investigate this issue. Thanks for letting us know.

**Comment by yihuax-zz** [comment] 2021-06-05 03:23
I investigated the issue, and I think this is by design.

When a new document gets created initially, we don't create the header and footer sub-documents.  We create them when they are needed.

We can repro this manually:

  1.  Start Word.
  2.  Create a blank document.
  3.  Don't touch the header or the footer areas.
  4.  Save the document.
  5.  Close Word.
Check the newly created .docx file: It has no header or footer information.

  1.  Start Word again.
  2.  Open the document just saved.
  3.  Double click the header area. Now the cursor is in header. This makes the header/footer ready for operation.
  4.  Save the document again.
  5.  Quit Word.
Check the .docx file again, you will see it has three header parts (thus three header references) and three footer parts (thus three footer references). The three are:

  *   default: for odd pages.
  *   even: for even pages.
  *   first: for the first page - the first page can be special.
So, it is by design. When sections.items[0].getHeader("Primary") is called, Word makes the header/footer ready for operation, so the three header sub-documents and the three footer sub-documents are created. Thanks!

**Comment by dgtllion** [comment] 2021-06-05 19:19
@yihuax thanks for your answer. Thats correct, but...
The design does also the following:

1. Start Word.
2. Open blank document.
3. Double click the header area. Now the cursor is in header. This makes the header/footer ready for operation.
4. **Type something in there**
5. **Now click the body (so that the cursor will be in body)**
6. Save the document
7. Quit Word.
8. Check `.docx` file

You'll see only 1 reference:
```
<w:headerReference r:id='rId6' w:type='default'/>
```

As i can see it removes all unnecessary references.

**Comment by yihuax-zz** [comment] 2021-06-07 18:53
Good discovery! Let me investigate more.

**Comment by yihuax-zz** [comment] 2021-06-08 06:23
I investigated more. Looks Word has the following function: When the focus goes from the header/footer view back to the main doc view, Word knows it is the end of header/footer editing, so Word removes the extra unused headers/footers.

When the API getHeader or getFooter is called, it is basically equivalent to entering the header/footer editing view. But we don't know when or which API marks the end of header/footer editing. Thus, I propose the following solution: When the current selection is in header/footer, and then the "select" API is called in the main document to let the view goes back to the main doc, we know it is the end of header/footer editing.  Thus, the following javascript works without the reported issue:

Word.run(function(context) {
    var hdr = context.document.sections.getFirst().getHeader("Primary");;
    hdr.insertText("hhhhh", "Replace");
    hdr.select();
    return context.sync().then(function(){
        setTimeout(setCursorBack, 3000);
    });

    function setCursorBack()
    {
        context.document.body.select();
        return context.sync().then(function(){
            console.log("Done");
        });
    }
});

However, this javascript code IS NOT WORKING yet on your machine: I need to fix the behavior of the "select" API. I have created the code change and it works on my machine. I am going to submit the code change so it should be available in Office's June release. Thanks again!

**Comment by dgtllion** [comment] 2021-06-08 09:30
Ah thanks @yihuax 
Can i have a notice when it will be released?
Or is there a page or roadmap where i can check?

**Comment by yihuax-zz** [comment] 2021-06-08 21:21
No, the same select() method, but improved behavior: When the new selection is in header/footer, Word goes into the header/footer view.

If nothing unexpected happens, it should be in the June's monthly release, and you will get the update in late July. I will tell you the earliest Office version that contains the change.

@***@***.***>, Do we issue any notice or whether we have a page to check the current released version?

Thanks!

**Comment by dgtllion** [comment] 2021-06-09 07:13
@yihuax , one more question...
I see that you are using twice `select()` method. Why is `hdr.select();` needed? 
Will it not select if i do `section.getHeader("Primary")` anymore and i need to call `hdr.select()` always to manipulate data init?
And i see also that you are using `setTimeout(setCursorBack, 3000);` Why is that? 
You cant call it directly? like this?
```
hdr.select();
return context.sync().then(function(){
    context.document.body.select();
    return context.sync().then(function(){
        console.log("Done");
    });
});
```

**Comment by yihuax-zz** [comment] 2021-06-09 17:39
Looks Word can remove the extra unused header/footer when Word leave header/footer view, so our API can do the UI change by first entering the header/footer view (hdr.select(); or select anything in header/footer), and then leave the header/footer view (context.document.body.select();  or select any other places in main document).  section.getHeader("Primary") only returns the header/footer's body object and it does not cause the UI selection. Please note the select method is just like making a selection using mouse cursor. You don't need to call select if you don't need to remove the extra headers/footers.

If we call the second select directly, it may also work. I didn't verify it. I used some waiting time to guarantee Word can finish the view switching.
Thanks!

**Comment by yihuax-zz** [comment] 2021-06-09 17:47
I have submitted the change to office version 16.0.14210. You can check the new version you are receiving and see whether it is 14210 or later. Unfortunately, we don't have a webpage to let the users outside to monitor the release process. Thanks!

**Comment by dgtllion** [comment] 2021-06-09 18:04
Ah ok, uhmmm the version that i have now is 16.49.21050901 (MacOS). or you mean this is the version of office.js?

**Comment by yihuax-zz** [comment] 2021-06-09 20:03
For MacOS: Your version is the April release.  The May release could be rolled out very soon. My change will be in June release.

MacOS version 16.51.210610xx or later contains the change.

**Comment by dgtllion** [comment] 2021-11-24 19:50
@yihuax now i got time to test the fix.
Its long time ago that i posted about that issue... and unfortunately i see that the issue still persists.
Can you check if the update you added is available on production version?
The version of Mac Word: **16.55 (21111400)**

**Comment by dgtllion** [comment] 2021-12-03 06:49
@yihuax @AbidRahman-MSFT, is there someone who can fix this issue?

**Comment by yihuax-msft** [comment] 2021-12-03 18:43
Hi, @dgtllion, Sorry to reply late. I was on vacation until this Wednesday.

I just verified that, with a new empty Word document, if I run the code I put above on Jun 7, I only get one header reference:
<w:body>
<w:p w14:paraId="4B3D01DD" w14:textId="77777777" w:rsidR="00224BE4" w:rsidRDefault="00224BE4"/>
<w:sectPr w:rsidR="00224BE4">
<w:headerReference w:type="default" r:id="rId6"/>
<w:pgSz w:w="12240" w:h="15840"/>
<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>
<w:cols w:space="720"/>
<w:docGrid w:linePitch="360"/>
</w:sectPr>
</w:body>

I verified it using Word win32 desktop version 16.0.14729.

@AbidRahman-MSFT, Do you have a MAC machine to do the same verification? Thanks!

**Comment by AbidRahman-MSFT** [comment] 2021-12-03 19:13
Verified to be working as expected on 16.57 Mac version.

**Comment by dgtllion** [comment] 2021-12-07 10:59
I see why it didnt works in my case.
It will give unexpected results if you dont add `hdr.select()`

In my case if i only want to `clear()` the data in header section (without selecting it) it will give multiple references.
Example:
```
Word.run(async context => {
    const sections = context.document.sections;
    sections.load();
    return context.sync().then(function () {
        sections.items[0].getHeader("Primary").clear(); //This line adds multiple references
     
        return context.sync().then(r => {
           context.document.body.select();
           return context.sync().then(r => {
               return new Promise((resolve, reject) => {
                   resolve();
               });
           });
        }).catch(handleError);
     }).catch(handleError);
}).catch(handleError);
```

**Closed as not planned** 2024-03-28 19:53 UTC
Labels: Type: product bug, Area: Word, Status: fix pending
