### ISSUE TITLE
GeneralException on context.sync after loading properties on Excel Online

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/office-js#47] opened 2018-01-12 17:32 UTC
**_Note:_** 
I'm opening this issue on behalf of a customer, who originally opened the issue in the docs repo. Since this is potentially a product bug, this issue belongs here in the **office-js** repo. Here are the related issues that the customer logged in the docs repo:
- https://github.com/OfficeDev/office-js-docs/issues/1229
- https://github.com/OfficeDev/office-js-docs/issues/1283

-------

Error on Javascript Console thrown after the first `context.sync` after loading properties on a writing text to cells in Excel Online.  This does not appear to happen in Excel Applications for Windows and Mac, just Online.  

> `r {name: "OfficeExtension.Error", code: "GeneralException", message: "Ocorreu um erro interno.", traceMessages: Array(0), innerError: null, …}
> code:"GeneralException"
> debugInfo:{code: "GeneralException", message: "Ocorreu um erro interno.", toString: ƒ}
> innerError:null
> message:"Ocorreu um erro interno."
> name:"OfficeExtension.Error"
> traceMessages:[]
> __proto__:Error`

Code that is throwing this error:

```
$scope.writeText = function (item) { 
Excel.run(function (context) {                       
	var click = item.Click;
	var sourcestring = item.onAction;
	var excelString = item.excel;
	var sheet;
	var activeRange;
	var string;
	if (excelString === "") string = sourcestring;
	else string = excelString;
	sheet = context.workbook.worksheets.getActiveWorksheet();
	activeRange = context.workbook.getSelectedRange();
	activeRange.load('columnIndex');
	activeRange.load('rowIndex');
	return context.sync().then(function () {
	  CODE NOT EXECUTED, error thrown before this code
	}
   }
}
```

## Expected Behavior
Expected behavior is for this code to run without error on all platforms (Excel 2016, Mac, Online).

## Current Behavior
Code runs without error in Excel 2016 and on Mac, but the error noted above occurs in Online.

## Context
This problem in Excel Online is permanent since November and has not been corrected. This is a serious issue, we can't launch a product because the add-in is not approved because it gets this error in Excel Online, and does not do what it is intended for.

## Your Environment
* Platform:  Office Online
* Host: Excel

**Comment by nunocv** [comment] 2018-01-18 13:04
Made a simple Test.
This:

                $scope.test = function () {
                    Excel.run(function (context) {
                        var ws = context.workbook.worksheets.getActiveWorksheet();
                        var cel = ws.getCell(1, 1);
                        cel.load('columnIndex');
                        return context.sync().then(function () {
                            var a = ws.getCell(2, 2);
                            var txt = cel.columnIndex;
                            a.values = txt;
                            return context.sync();
                        })
                    });
                }

Does Not work on Excel Online, Throws the same exception, "GeneralException"
Just to clarify, $scope is just an angular object needed to call this function when the button is clicked in the Panel on Excel.

**Comment by Zlatkovsky** [comment] 2018-01-18 20:19
@forlemon , thanks for showing the code sample.

I ran it in Office Online using [Script Lab](https://aka.ms/scriptlab), and it worked fine.  So I'm guessing that it's not a framework bug per se, but rather the way that you're hooking up Angular.

It sounds somewhat akin to the issue described in https://stackoverflow.com/a/44118441/678505.  Do you have an "Office.initialized()" somewhere on the page, and are you sure that it's firing?

**Comment by nunocv** [comment] 2018-01-19 15:39
Yes I have an  "Office.initialized()".
I've even put it like this:

```
Office.initialize = function (reason) {
    $(document).ready(function () {
        $('#test').click(function test() {
            Excel.run(function (context) {
                var ws = context.workbook.worksheets.getActiveWorksheet();
                var cel = ws.getCell(1, 1);
                cel.load('columnIndex');
                return context.sync().then(function () {
                    var a = ws.getCell(2, 2);
                    var txt = cel.columnIndex;
                    a.values[0][0] = txt;
                    return context.sync();
                })
            });
        });
    });
};
```

And it still throws GeneralException after this line "return context.sync().then(function () {"
I couldn't make it even work on ScriptLab, no results and no console errors or message.
But sideloading the add in, and executing that function on a simple button, throws the error once again.

**Comment by Zlatkovsky** [comment] 2018-01-19 16:38
In Script Lab, you don't need an Office.initialize.  Having one would actually throw Script Lab off.  Script Lab is meant as a simplified playground, where you only need to write in the "interesting" bit of code -- whereas we take care of the backend infrastructure.

Just to check:  if you had only the inner code in Script Lab, does it work for you in Office Online?

        $('#test').click(function () {
            Excel.run(function (context) {
                var ws = context.workbook.worksheets.getActiveWorksheet();
                var cel = ws.getCell(1, 1);
                cel.load('columnIndex');
                return context.sync().then(function () {
                    var a = ws.getCell(2, 2);
                    var txt = cel.columnIndex;
                    a.values[0][0] = txt;
                    return context.sync();
                })
            });
        });

**Comment by nunocv** [comment] 2018-01-19 16:48
It throws an error saying the values property is not loaded
It shows this output(it's in portuguese though):
```
Unhandled Promise rejection: A propriedade "values" não está disponível. Antes de ler o valor da propriedade, chame o método de carregamento no objeto contentor e chame "context.sync()" no contexto de pedido associado. ; Zone: <root> ; Task: Promise.then ; Value: PropertyNotLoaded: A propriedade "values" não está disponível. Antes de ler o valor da propriedade, chame o método de carregamento no objeto contentor e chame "context.sync()" no contexto de pedido associado. {...} Error: A propriedade "values" não está disponível. Antes de ler o valor da propriedade, chame o método de carregamento no objeto contentor e chame "context.sync()" no contexto de pedido associado.
    at r.ZoneAwareError (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:77489)
    at new r (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:21:283042)
    at t.throwIfNotLoaded (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:21:335136)
    at k.get [as values] (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:21:379271)
    at https://script-lab-runner.azureedge.net/compile/page:15:27
    at ZoneDelegate.invoke (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:85192)
    at Zone.run (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:80018)
    at https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:77231
    at ZoneDelegate.invokeTask (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:85935)
    at Zone.runTask (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:80709)
    at drainMicroTaskQueue (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:75411)
    at ZoneTask.invoke (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:86983)
Error: Uncaught (in promise): PropertyNotLoaded: A propriedade "values" não está disponível. Antes de ler o valor da propriedade, chame o método de carregamento no objeto contentor e chame "context.sync()" no contexto de pedido associado.
Error: A propriedade "values" não está disponível. Antes de ler o valor da propriedade, chame o método de carregamento no objeto contentor e chame "context.sync()" no contexto de pedido associado.
    at r.ZoneAwareError (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:77489)
    at new r (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:21:283042)
    at t.throwIfNotLoaded (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:21:335136)
    at k.get [as values] (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:21:379271)
    at https://script-lab-runner.azureedge.net/compile/page:15:27
    at ZoneDelegate.invoke (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:85192)
    at Zone.run (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:80018)
    at https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:77231
    at ZoneDelegate.invokeTask (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:85935)
    at Zone.runTask (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:80709)
    at drainMicroTaskQueue (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.bundle.js:1:75411)
    at ZoneTask.invoke (https://script-lab.azureedge.net/bundles/polyfills.2e9078c49c55fa18c57b.b
```

If I load the property it just doesn't do nothing, no change on the cell (2,2) and no message on the console.

**Comment by Zlatkovsky** [comment] 2018-01-19 16:55
Ah, right.  Sorry, this code is different from what you'd once had, though :-)

Instead of `a.values[0][0] = txt`, you need `a.values = [[txt]]`.  There is something special about array-handling in particular, where you have to set the *entire* array at once, not piece-meal.  More info here:  http://buildingofficeaddins.com/array-properties/.

Try it now with `a.values = [[txt]]`

**Comment by nunocv** [comment] 2018-01-19 16:59
It worked on ScriptLab!
But the same function in the context of the Add-In, this happens:
![image](https://user-images.githubusercontent.com/26458114/35162117-2c5e6dfa-fd3a-11e7-9188-4d0d940b9824.png)

It does not it the breakpoint.
But this does not happen on Desktop Excel

**Comment by Zlatkovsky** [comment] 2018-01-20 03:11
I am not sure what is happening.

If you can create the absolute minimal repro project, I can try to take a look.  By minimal, I mean something that has little extraneous stuff, and where I can just do a simple "npm install" "npm start" or equivalent to run it locally.  It seems like it's something in your hookup between your framework code and the Office code, but I can try to help if I see the full source code and can debug it on my computer.

**Comment by nunocv** [comment] 2018-01-23 10:21
I've created a Visual Studio Excel Add In project that only has this html and this javascript. Published it on a server and ran the Manifest on excel Online. Same exception:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>Excel Add-In: Xporter Snippets</title>

    <script src="Scripts/jquery-3.1.1.js" type="text/javascript"></script>
    <script src="Scripts/FabricUI/MessageBanner.js" type="text/javascript"></script>
    <script src="Scripts/jquery.fabric.min.js"></script>
    <script src="Scripts/angular.js"></script>
    <link href="Content/Office.css" rel="stylesheet" type="text/css" />
    <script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js" type="text/javascript"></script>
    <link rel="stylesheet" href="Content/fabric.min.css" />
    <link rel="stylesheet" href="Content/fabric.components.css" />
    <script src="Scripts/Jquery.NavBar.js"></script>

    <!-- To enable offline debugging using a local reference to Office.js, use:                        -->
    <!-- <script src="Scripts/Office/MicrosoftAjax.js" type="text/javascript"></script>  -->
    <!-- <script src="Scripts/Office/1/office.js" type="text/javascript"></script>  -->

    <link href="ExcelSnippets.css" rel="stylesheet" type="text/css" />
    <script src="ExcelSnippets.js" type="text/javascript"></script>

    <!-- For the Office UI Fabric, go to https://aka.ms/office-ui-fabric to learn more. -->
    <!-- To enable the offline use of Office UI Fabric, use: -->

</head>
<!-- Angular controller that has all the scope variables to be used to create the web page -->
<body >
        <button class="ms-Button" style="margin-top:20%;" id="test">
            <span class="ms-Button-label">TEST</span>
        </button>
</body>

</html>
```

```
(function () {
    "use strict";

    // The initialize function must be run each time a new page is loaded.
Office.initialize = function (reason) {
    $(document).ready(function () {
        $('#test').click(function test() {
            Excel.run(function (context) {
                var ws = context.workbook.worksheets.getActiveWorksheet();
                var cel = ws.getCell(1, 1);
                cel.load('columnIndex');
                var a = ws.getCell(2, 2);
                a.load('values');
                return context.sync().then(function () {
                    var txt = cel.columnIndex;
                    a.values = [[txt]];
                    return context.sync();
                })
            });
        });
    });
};
})();
```

**Comment by Zlatkovsky** [comment] 2018-01-23 17:13
I reached out for someone on our team to help investigate.

**Comment by Zlatkovsky** [comment] 2018-01-23 17:14
(For the record, for internal folks:  this is ICM issue 57542289)

**Comment by nunocv** [comment] 2018-01-30 11:26
Is there any news regarding this?

**Comment by phtai** [comment] 2018-01-31 07:04
@forlemon I have tried your simplified code on Excel Online, but cannot repro the issue. The snippet completes successfully without any exceptions.

I wonder if you could give us more details about it?

![image](https://user-images.githubusercontent.com/35979655/35609346-c5a1bbfe-0611-11e8-98ef-ac592cd68b8b.png)

Normally, by executing the simplified snippet you gave, it will send in a couple of requests to ExecuteRichApiRequest and GetRangeContent. Could you please turn-on the Network capture just before you click the TEST button, and see if those requests are completed successfully? And could you please give us the correlation IDs from the headers of each responses, so that we can diagnose the issue more easily?

**Comment by nunocv** [comment] 2018-01-31 12:43
CorrelationId: "09c326b9-b646-407d-82a1-89b5cbe13bfc"
![image](https://user-images.githubusercontent.com/26458114/35623646-43e42282-0684-11e8-95c3-8eb827de55c5.png)
![image](https://user-images.githubusercontent.com/26458114/35623654-492f1ab2-0684-11e8-90b8-04aaf6d14bdc.png)

**Comment by phtai** [comment] 2018-02-05 20:21
@forlemon Thank you for your response. We found this is likely to be a bug in the Office Online. We are working to get it fixed.

**Comment by nunocv** [comment] 2018-02-16 11:19
Any updates?

**Comment by rmrodrigues** [comment] 2018-02-28 14:26
Hi team,
Is there any progress on this? We are creating a new add-in and we are unable to finish some feature because we are depending on this fix.
Could you give us some update?

Cheers,
Rui Rodrigues

**Comment by phtai** [comment] 2018-02-28 18:36
Hi @forlemon & @rmrodrigues, we found the problem is that Office Online fails to parse a version number that consists of less than four parts (like 2.12). The version number in the add-in manifest should be in a format like **2.12.0.0**

We have checked-in a fix for this but it needs a few weeks to deploy. In the mean time, **you can just change the version number in the add-in manifest to a supported format**, and it should fix the problem.

**Closed as completed** 2018-03-12 18:08 UTC
Labels: Area: Excel

**Comment by soorajhealthplotter** [comment] 2020-03-10 06:56
I am also having the same bug

My Code is 

Excel.run((context) ->
  sheet = context.workbook.worksheets.getItem(s_name)
  response_data = {"A1"=>"1000","A2"=>"1001","B1"=>"1000","B2"=>"1001","C1"=>"1000","C2"=>"1001"} # similary 54000+ records
  angular.forEach response_data, (key, value) -> 
    range = sheet.getRange(key)
    range.values = [[ value ]]
  context.sync().then ->
    console.log("Data synchronized")
    return
).catch (error) ->
  console.log 'Error: ' + error

My Excel version is

![excel_version](https://user-images.githubusercontent.com/12229181/76283553-e72dc200-62c0-11ea-8e98-7e469f51a1ae.png)

I am having issue is Excel Online
