### ISSUE TITLE
2nd call to OfficeRuntime.auth.getAccessToken throws an error

### ISSUE THREAD

**Issue by T-Roth** [OfficeDev/office-js#1389] opened 2020-09-16 00:00 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have a spa app that has a signout button, and when a user signs out and back in the 2nd call to **OfficeRuntime.auth.getAccessToken** throws an exception.  I'm using this in an Outlook add-in and using this office.js file
`<script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>`

Calling it 2 times in a rows also produced the same error.

```
    private getOfficeToken = async (): Promise<string> => {
        try {
            let token = await (<any>window).OfficeRuntime.auth.getAccessToken({ allowConsentPrompt: true, allowSignInPrompt: true });
            let t = await (<any>window).OfficeRuntime.auth.getAccessToken({ allowConsentPrompt: true, allowSignInPrompt: true });
            return token;
        } catch (exception) {
            console.error(exception.message);
        }
    }
```

```
TypeError: e[j] is not a function
    at OSF.DDA.ApiMethodCall.a.constructCallArgs (https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:19:59693)
    at OSF.DDA.AsyncMethodCall.verifyAndExtractCall (https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:19:61292)
    at g.<computed> (https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:19:74821)
    at OSF.DDA.Auth.getAccessTokenAsync (https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:19:83508)
    at https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:19:210025
    at new Promise (<anonymous>)
    at Object.getAccessToken (https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:19:209974)
```

**Comment by exextoc** [comment] 2020-09-17 20:04
Hey @T-Roth ,

Can you give me the javascript transpiled version of this code so that I can understand better? The semantics make it a little confusing to actually understand what it's trying to do. Also, can I understand why you would need to call getAccessToken twice, since calling it twice consecutively is likely to return the error "The operation failed because this add-in is already requesting an access token" anyway.

**Comment by T-Roth** [comment] 2020-09-17 21:48
@exextoc 
I only called it twice in a row in the code I posted above when I was trying to trouble shoot the issue.  My actual app does not do that, but like I said there is a logout button on my Spa app so when the user tries to log back in that 2nd call will trigger the error.

```
            this.getOfficeToken = function () { return __awaiter(_this, void 0, void 0, function () {
                var token, exception_1;
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0:
                            _a.trys.push([0, 2, , 3]);
                            return [4 /*yield*/, window.OfficeRuntime.auth.getAccessToken({ allowConsentPrompt: true, allowSignInPrompt: true })];
                        case 1:
                            token = _a.sent();
                            return [2 /*return*/, token];
                        case 2:
                            exception_1 = _a.sent();
                            console.error(exception_1.message);
                            return [3 /*break*/, 3];
                        case 3: return [2 /*return*/];
                    }
                });
            }); };
```

**Comment by exextoc** [comment] 2020-09-19 13:26
Hey @T-Roth ,

I am unable to correctly reproduce the exact issue. The second call to accessToken should return an exception, but should not fail with the trace that you have mentioned. Could you just execute a simple code snippet:
```
window.OfficeRuntime.auth.getAccessToken({ allowConsentPrompt: true, allowSignInPrompt: true });
window.OfficeRuntime.auth.getAccessToken({ allowConsentPrompt: true, allowSignInPrompt: true });
```
And see if you see the same error? (The handling of the promise might be irrelevant in this case).

**Comment by T-Roth** [comment] 2020-09-22 05:57
@exextoc 

Took quite a while, but I tracked it down to the  Array prototype methods in our project.  I still don't know why it causes the error, even stranger no matter what I name the methods something in outlook-web.js calls it (see image below).  Once I updated the methods to check that the index param exists, the getAccessToken error went away.

```
        Array.prototype.someRandomName = function (item, index) {
            var array = this;
            array.splice(index, 0, item);
        };
```

![image](https://user-images.githubusercontent.com/7863411/93847614-4307d900-fc5c-11ea-9fd8-f89afa6c823f.png)
![image](https://user-images.githubusercontent.com/7863411/93848101-9cbcd300-fc5d-11ea-8add-ab7634065370.png)

**Comment by exextoc** [comment] 2020-09-23 11:23
@T-Roth is there a way we can reproduce this ourselves so we can investigate? And is the issue fixed on your end?

**Comment by T-Roth** [comment] 2020-09-24 21:15
@exextoc 

I would think that if you made an Array Prototype like I did above you should be able to reproduce it.  Something in Office appears to call **all** the array prototype methods in our project, but only the ones that had a 2nd index parameter that wasn't being checked caused the error (actually got into the splice method).   I ended up fixing it by checking that the index was a number.   


The issues appears to be fixed on our end, but I'm not sure if my changes are just masking a bigger problem, and if that problem is in our code or yours.

**Comment by exextoc** [comment] 2020-10-06 07:27
@T-Roth
Thanks for reporting this issue regarding getAccessToken. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

**Closed as completed** 2024-03-17 20:00 UTC
Labels: Area: authentication, Area: Outlook, Type: product bug, Status: in backlog
