### ISSUE TITLE
Mac outlook body.getAsync doesn't use ol/ul/li elements for lists

### ISSUE THREAD

**Issue by fraziermork** [OfficeDev/office-js#474] opened 2019-04-12 19:21 UTC
I have an email body like this:

![image](https://user-images.githubusercontent.com/16546625/56059370-c52a6900-5d18-11e9-90ca-38d26b401eab.png)

The html I get back from body.getAsync looks like this: 

<img width="450" alt="Screen Shot 2019-04-12 at 11 48 38 AM" src="https://user-images.githubusercontent.com/16546625/56059452-f2771700-5d18-11e9-87f8-799eff7ca3a1.png">

## Current Behavior
Right now both ordered list items and unordered list items come out as paragraph elements instead of as ordered/unordered list elements, with only a class to indicate that they were once lists. Worse, the class is identical for both ordered and unordered list items, so it's impossible to tell what kind of list it came from.

## Expected Behavior
I expected that the lists would be converted to li elements wrapped in either ol or ul tags (the way it works in every other version of outlook I've tried). Even another classname to distinguish between ordered and unordered lists would be helpful.

## Steps to Reproduce, or Live Example
In mac outlook, start a new message, type something, and make it a list use the formatting options in the top bar. If you call body.getAsync and console log the result, the list is a paragraph.

## Context
Since there are only options to set the entire mail body or to prepend to it, I have to set the whole mail body. When I do, I also end up butchering every list in the email because I couldn't tell that they were lists, and even if I could have, I wouldn't have been able to tell what kind of list it was. I just want my plugin to be able to make changes to the email body in mac outlook without stripping formatting from every list in the message.

## Your Environment
Running office for mac 16.22.1, requirement set 1.4

**Comment by exextoc** [comment] 2019-04-13 08:57
Thanks for reporting this issue regarding body.getAsync() not returning bullets and numbering. We are able to reproduce this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by nathandpeterson** [comment] 2019-08-19 23:01
@exextoc Any update on this? I am also finding that bullet items are not preserved in Mac Outlook, which means that we cannot determine the styles that users are applying to their emails. Thanks!

**Comment by AnjanaValsan** [comment] 2019-08-21 03:54
Hello @nathandpeterson , we do not have an accurate ETA. Late Q4 is what we are targeting.
thanks,

**Comment by amiram** [comment] 2020-07-16 18:28
Is there any progress with this issue? It causes us serious trouble with Mac users.

**Comment by exextoc** [comment] 2020-07-17 08:02
Tracked by BUG 1412472<https://o365exchange.visualstudio.com/O365%20Core/_workitems/edit/1412472>
________________________________

**Comment by exextoc** [comment] 2020-07-24 10:13
The issue is in our backlog and we will update the thread once the fix is available. Thank you for your patience.

**Comment by james-huang** [comment] 2020-09-27 22:53
+1 vote on fixing this issue.

**Comment by fergy-hs** [comment] 2020-09-28 22:44
+1 to fix this issue that is causing a lot of pain. Thanks

**Comment by exextoc** [comment] 2020-10-07 06:12
We have added this to our backlog but it is not a priority item at this moment. We will keep this thread posted when this work item gets picked.

**Comment by cody-lettau** [comment] 2021-04-27 22:03
+1 to fix this issue - this is a pretty big issue when attempting to control the content of the email being sent. Lists are commonly used in emails and this results in the loss of those lists if we use the value from ```Office.context.mailbox.item.body.getAsync``` to set the email body with some modifications.

**Comment by exextoc** [comment] 2023-12-15 16:51
This issue is fixed in Mac New Outlook version >= 16.75

**Closed as completed by exextoc** 2023-12-15 16:51 UTC
Labels: Area: Outlook, Type: product bug, Status: fixed
