### ISSUE TITLE
Shared MailBox, OfficeJS Office.context.mailbox.item.body.getAsync() not working on Outlook Mac

### ISSUE THREAD

**Issue by naemcivic** [OfficeDev/office-js#1010] opened 2020-02-26 03:13 UTC
On our Outlook add-in for compose mode, we are using the Office JS API to parse the body of the email body by calling OfficeJS Office.context.mailbox.item.body.getAsync("html", callback) 

## Expected Behavior

Should return the HTML of the email body

## Current Behavior

Returns as Null object

## Steps to Reproduce, or Live Example

Add a shared mailbox:

1. Find and Open a shared mailbox

Steps to reproduce:

1. Create a new email in Outlook for Mac
2. In the From field, select the shared mailbox
3. Open and add-in's pane and try to call
```
    Office.context.mailbox.item.body.getAsync("html", function(result) {
      var body_html = result.value;
      console.log('HTML', body_html);
    });
```
The logged object is ```null```

**Additional details:**

This use to work in older version of Mac Outlook prior to the described Mac Outlook version

## Your Environment

* Platform: Mac
* Host: Outlook for Mac
* Office version number: 16.34 (20020900)
* Operating System: ______
* Browser (if using Office Online): ______

**Comment by lindalu-MSFT** [comment] 2020-03-02 20:30
Hi @exextoc Here's another issues, looks like the previous one except for the Mac. Did you want to resolve this one **add to backlog** as well?

**Comment by lindalu-MSFT** [comment] 2020-03-02 21:52
Hi @naemcivic Looks like this issue was added to the backlog as well. I don't know when there will be resources available to address this.

**Comment by exextoc** [comment] 2020-07-31 21:56
Internal tracking id: Office:3977208

**Comment by neprasad-microsoft** [comment] 2024-02-29 17:26
This is a duplicate of https://github.com/OfficeDev/office-js/issues/1004 . This has been fixed. Please reopen if you still face this issue.

**Closed as completed by neprasad-microsoft** 2024-02-29 17:26 UTC
Labels: Area: Outlook, Status: fixed
