### ISSUE TITLE
Outlook API not returning shared contacts folder

### ISSUE THREAD

**Issue by rbhudson** [OfficeDev/office-js#2861] opened 2022-09-23 00:10 UTC
## Expected Behavior
A user of our Word AddIn should be able to add a contacts folder which was shared with the user.  Then the user should see contacts from the shared folder as well as their own contacts.

## Current Behavior
The AddIn code calls the Outlook API:  OutlookSearch.ActiveNamespace.GetSharedDefaultFolder(oUser, Outlook.OlDefaultFolders.olFolderContacts).
But, that API call throws an Exception: “Cannot open the mailbox for this user because the user does not have a server mailbox.”

The user and the source of the shared folder are both on the same Exchange Server within the same environment.  The oUser object is the correct one for the one who is sharing the shared folder.

## Steps to Reproduce, or Live Example
1. Click on an AddIn button to add a shared folder
2. Search for the name of the user who owns the shared folder
3. Search for shared folders for that other user.
4. It should return any shared folders to add to the current user's available folders but instead it throws an Exception: “Cannot open the mailbox for this user because the user does not have a server mailbox.”

## Context
Our Word AddIn is used by law firms all over the world.  A secretary/administrative assistant will frequently access the contacts of the attorney(s) they work for while creating a letter using our AddIn.

## Your Environment
This behavior is reported to us by a specific large law firm.  We can reproduce it in our dev/test environment.
Desktop
Office 365, 64-bit (Click to Run), Word
Windows 10 x64

## Useful logs
This log occurs in the catch clause after calling OutlookSearch.ActiveNamespace.GetSharedDefaultFolder(oUser, Outlook.OlDefaultFolders.olFolderContacts):
9/20/2022 11:22:16 AM -- Exception in ContactUI.OutlookFolder() trying to get shared folder for 'XXXX XXXXXX (XXXX.XXXXXX@bighand.com)' - error message: 'Cannot open the mailbox for this user because the user does not have a server mailbox.'

**Comment by exextoc** [comment] 2022-09-26 03:08
@rbhudson Thanks for reporting this issue. Are you using "Outlook Desktop" on Windows for this?

**Comment by Oleg-O** [comment] 2022-09-27 19:23
This issue is opened for office-js repo, but I am not sure this question is related to this repo - the failing API in question does not appear to be an office-js API. Or am I missing something? Could you please clarify?

**Comment by rbhudson** [comment] 2022-09-27 21:29
The issue occurs in a VSTO Addin not a js addin.

**Comment by rbhudson** [comment] 2022-09-27 21:31
Yes.  This is on Office 2016 installed on Windows.  The Addin is a VSTO addin, not the newer js kind.

**Comment by ElizabethSamuel-MSFT** [comment] 2022-11-03 15:53
@Oleg-O @exextoc As the author has confirmed this is a VSTO add-in, can we point them somewhere to get help with that?

Thanks.

**Comment by rbhudson** [comment] 2023-01-06 23:13
As noted above this application is using the VSTO addin, not the newer addin using javascript.  Since this seems to be the wrong channel can you point me to a more appropriate channel?

**Comment by eugene-plutoflume** [comment] 2023-01-06 23:29
`Microsoft Q&A` or `StackOverflow` is the right place for such posts.

**Comment by rbhudson** [comment] 2023-01-07 00:05
Yes.  Office 2016 Professional, the desktop application.

Rick Hudson |  Developer | BigHand | Tel: (951) 848 3948 | www.bighand.com<https://protect-eu.mimecast.com/s/E9mRCJ6r5FZrQWsGGXse/>

**Comment by Oleg-O** [comment] 2023-02-27 23:03
Closing this post here since it's not related to office.js...

**Closed as completed by Oleg-O** 2023-02-27 23:03 UTC
Labels: Needs: attention :wave:, Area: Outlook, Type: product bug
