### ISSUE TITLE
OSF.DDA.Error: Permission denied when opening dialog

### ISSUE THREAD

**Issue by beatrixmorar** [OfficeDev/office-js#2231] opened 2021-11-05 15:48 UTC
When launching a dialog from our Excel or Word add-in on desktop using the Office.context.ui.displayDialogAsync API, the following error is logged to the browser console:

> OSF.DDA.Error
> code: 7000
> message: "You don't have sufficient permissions for this action."
> name: "Permission Denied" 

## Your Environment
* Platform: PC desktop
* Host: Excel and Word
* Office version number:  Microsoft 365 MSO (16.0.14326.20384) 64-bit
* Operating System: Windows 10 Pro
 
## Expected behavior
The error not to appear when a dialog is opened.

## Current behavior
Every time we open a dialog from our add-ins, we get this error (which seems to be internal to the Office JS API - excel.win32-16.01.js). The dialog is rendered correctly and communication between host and dialog is working fine (using the Office Dialog API). However, it would be good to understand what is the source of the problem, as right now we have no clue and it is not clear what are the side effects and impact of this error.

## Steps to reproduce
1. Open any dialog using Office.context.ui.displayDialogAsync
2. Check console of the browser
3. OSF.DDA.Error is logged, always for line 1 in the html file

## Useful logs
![image](https://user-images.githubusercontent.com/52167887/140538260-ed2811bd-e03c-4725-83f1-2f1ebdec633f.png)

**Comment by pkkj** [comment] 2021-11-08 19:12
Hi, would you like to confirm that the URL is defined in the manifest, or it has the same host name as parent? You may find more useful information in this [document](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=excel-js-preview):

_The domain must be either the same domain as the host page (including protocol and port number), or it must be registered in the `AppDomains` section of the add-in manifest._

And also ensure that the URL is using an https server. Thanks.

**Comment by beatrixmorar** [comment] 2021-11-09 07:09
Hi, yes, the host and dialog are using the same domain and port: https://localhost:3000.
An example of the HTTPS URL that we pass to the Office.context.ui.displayDialogAsync method is "https://localhost:3000/dialog.html?page=login".

**Comment by pkkj** [comment] 2021-11-10 18:26
Without looking your code, I am not able to figure out what's happening. But I would like suggest trying my sample add-in in your environment. Here is the manifest: [Manifest](https://kepengtestapp.azurewebsites.net/manifest/AzureDialogTest.xml) You could side load this taskpane add-in and verify whether it's working.

![image](https://user-images.githubusercontent.com/7818153/134721357-41785289-0d3d-4e4a-b9d3-ee5c5ba2ddc9.png)

**Comment by beatrixmorar** [comment] 2021-11-11 07:15
Thanks for your response. I tried out your sample add-in and the error is there, both when opening dialog from same origin ("launchDialogSameOrigin") and from different origin ("launchDialogDifferentOrigin"):

![Screenshot_1](https://user-images.githubusercontent.com/52167887/141254197-39eb9df6-717e-4d1e-817e-930a7339d165.png)
![Screenshot_2](https://user-images.githubusercontent.com/52167887/141254217-720af0f2-b420-47fc-8a98-7105c2f2b09a.png)

**Comment by pkkj** [comment] 2021-11-11 20:51
I understand. This exception is a false alarm caused by an internal exception in Office code and we will be working on it. Generally speaking this won't break any functionalities for the dialog API, so you may just ignore it. Thanks.

**Comment by swiftinitdotcom** [comment] 2021-11-17 07:55
I have exact same issue suddenly. This was working few months back.
dialogSSOv1.html:1
I have logged a support ticket because the dialogbox is not closing

   Tracking Prevention blocked access to storage for https://appsforoffice.microsoft.com/lib/1/hosted/office.js.
OSF.DDA.Error
code: 7000
message: "You don't have sufficient permissions for this action."
name: "Permission Denied"
[[Prototype]]: Object

**Comment by Shujee** [comment] 2021-11-30 07:34
Any update on this? I'm facing this exact issue.

**Comment by pkkj** [comment] 2021-11-30 23:25
This exception is a known issue and it will be fixed. However it's an internal problem and it won't cause any storage-related issue.

**Comment by chenxizhang** [comment] 2022-02-19 13:30
same issue here

**Comment by swiftinitdotcom** [comment] 2022-02-24 07:29
Is this fixed we are not able to do sso because of this issue.

**Comment by splinter** [comment] 2022-03-02 06:09
We are also facing the same issue and it seems to be blocking  a login flow

**Comment by pkkj** [comment] 2022-03-02 07:30
Hi.

This issue is caused by an internal exception from Office.js. Generally speaking, it's a false alarm and it won't block the add-in's JavaScript logic. 

The fix has reached the beta version of Office.js. In my test environment, this exception disappears after I use this version. Feel free to try it if possible. The path to beta CDN is https://appsforoffice.microsoft.com/lib/beta/hosted/office.js.

Thanks.

**Comment by chenxizhang** [comment] 2022-03-02 10:11
Thanks for the update @pkkj  let me try the beta version and will back to you soon

**Comment by swiftinitdotcom** [comment] 2022-03-02 10:24
We did a lot of head scratch and finally found one workaround....
The way its fixed for us is by using
Office.context.ui.messageParent("Some message", { targetOrigin: "*" })

**Comment by chenxizhang** [comment] 2022-03-02 13:53
> Hi.
> 
> This issue is caused by an internal exception from Office.js. Generally speaking, it's a false alarm and it won't block the add-in's JavaScript logic.
> 
> The fix has reached the beta version of Office.js. In my test environment, this exception disappears after I use this version. Feel free to try it if possible. The path to beta CDN is https://appsforoffice.microsoft.com/lib/beta/hosted/office.js.
> 
> Thanks.

I tried this solution, and the error was gone.

But it still another problem, I called the method "Office.context.ui.messageParent", seems like it don't close the dialog, and the main page will not receive anything.

Is there anything I am missing?


The sample code in main page 

```
      <button onClick={() => {
        Office.context.ui.displayDialogAsync("https://nice-moss-06bb30900.1.azurestaticapps.net/login.html", { width: 40, height: 30 }, (result) => {
          const dialog = result.value;
          dialog.addEventHandler(Office.EventType.DialogMessageReceived, (message) => {
            alert(message);
          });
        })
      **}}>弹出对话框</button>**
```

The sample code in the dialog page
```
<body>
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root">点击登陆</div>


  <button id="back">返回</button>

  <script>
    Office.onReady(() => {
      console.log("ready");
      const button = document.getElementById("back");
      button.addEventListener("click", function () {
        console.log("click");//this line logged
        Office.context.ui.messageParent("test", { targetOrigin: "*" });//don't work without any error, don't close the dialog
      })
    })

  </script>
</body>

```

**Comment by chenxizhang** [comment] 2022-03-02 13:54
> We did a lot of head scratch and finally found one workaround.... The way its fixed for us is by using Office.context.ui.messageParent("Some message", { targetOrigin: "*" })

Unfortunately this is not works for me😂

**Comment by pkkj** [comment] 2022-03-02 14:08
> We did a lot of head scratch and finally found one workaround.... The way its fixed for us is by using Office.context.ui.messageParent("Some message", { targetOrigin: "*" })

Actually this is the correct way to call the messageParent API, if your code is doing cross-domain messaging. This is a recent breaking change in our API and you could find more detail in this [page](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#cross-domain-messaging-to-the-host-runtime). Thanks.

**Comment by pkkj** [comment] 2022-03-02 14:20
> > Hi.
> > This issue is caused by an internal exception from Office.js. Generally speaking, it's a false alarm and it won't block the add-in's JavaScript logic.
> > The fix has reached the beta version of Office.js. In my test environment, this exception disappears after I use this version. Feel free to try it if possible. The path to beta CDN is https://appsforoffice.microsoft.com/lib/beta/hosted/office.js.
> > Thanks.
> 
> I tried this solution, and the error was gone.
> 
> But it still another problem, I called the method "Office.context.ui.messageParent", seems like it don't close the dialog, and the main page will not receive anything.
> 
> Is there anything I am missing?
> 
> The sample code in main page
> 
> ```
>       <button onClick={() => {
>         Office.context.ui.displayDialogAsync("https://nice-moss-06bb30900.1.azurestaticapps.net/login.html", { width: 40, height: 30 }, (result) => {
>           const dialog = result.value;
>           dialog.addEventHandler(Office.EventType.DialogMessageReceived, (message) => {
>             alert(message);
>           });
>         })
>       **}}>弹出对话框</button>**
> ```
> 
> The sample code in the dialog page
> 
> ```
> <body>
>   <noscript>You need to enable JavaScript to run this app.</noscript>
>   <div id="root">点击登陆</div>
> 
> 
>   <button id="back">返回</button>
> 
>   <script>
>     Office.onReady(() => {
>       console.log("ready");
>       const button = document.getElementById("back");
>       button.addEventListener("click", function () {
>         console.log("click");//this line logged
>         Office.context.ui.messageParent("test", { targetOrigin: "*" });//don't work without any error, don't close the dialog
>       })
>     })
> 
>   </script>
> </body>
> ```

It seems in your sample code in main page, there is no code to close the dialog. Besides, "alert" function is disabled by Office.js and it cannot be used to show the alert dialog (this is by-design). Therefore you could not use it for debugging purpose.

If possible you could use the debugger to debug the taskpane source code, to figure out whether the event is triggered there correctly. I also have a test [add-in](https://kepengtestapp.azurewebsites.net/manifest/AzureDialogTest.xml) and you could side load it. It demonstrates how to use the dialog and messaging API. In my add-in, sending a message "CLOSE_DIALOG" from dialog to taskpane will close the dialog.

![image](https://user-images.githubusercontent.com/7818153/156379469-7ceb5750-e29c-47ee-86e1-acba27841d9f.png)

**Comment by chenxizhang** [comment] 2022-03-03 06:04
@pkkj thanks for the information. I realized that we need to close the dialog by ourseleve now. and I modified a littble bit the code, it works for me now.

**Comment by chenxizhang** [comment] 2022-03-03 06:41
when we can get this fix in production version? @pkkj

**Comment by stenly311** [comment] 2022-06-28 04:39
> We did a lot of head scratch and finally found one workaround.... The way its fixed for us is by using Office.context.ui.messageParent("Some message", { targetOrigin: "*" })

didn't work for me :/

**Comment by pkkj** [comment] 2022-06-28 04:58
Hi. The fix for this issue has been deployed to the official Office CDN for more than one month. I tested it again and there is no OSF.DDA.Error when the dialog is launching. If an add-in is referring the Office.js from CDN, the error should disappear. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment] 2022-08-10 00:00
Closing as this seems to have been fixed.

@beatrixmorar and others: If that's not the case, let us know by commenting on this thread so we can reopen if needed. Or you can create a new issue.

Thanks.

**Closed as completed by ElizabethSamuel-MSFT** 2022-08-10 00:00 UTC
Labels: Area: add-ins platform, Status: fixed
