### ISSUE TITLE
Outlook on the web: Attachments are not attached when forwarding a message

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#1839] opened 2021-04-30 08:18 UTC
If you click the Send button before the attached file is loaded, the email will be created without the attached file.

You can reproduce this by performing a quick send operation when forwarding the email.

## Expected Behavior

The message will be created with attachments.

## Current Behavior

The message will be created without attachments.
At this time, the body of the message will also be omitted, but will be added when you send mail.

## Steps to Reproduce, or Live Example

1. Select an email with large attachments
2. Click the forward button to send it before it is loaded

If the OnSendAddinsEnabled flag is True and the On-Send add-in is installed, it will automatically pop out.

https://user-images.githubusercontent.com/58804032/116665445-51a03680-a989-11eb-961c-10c66fb0a6d1.mp4

## Context

It can be reproduced by opening the pop-out window by yourself, so I think it is a problem of OWA itself.

If the OnSendAddinsEnabled flag to true, you are more likely to encounter this issue because it forces you to go to the pop-out window.
If the OnSendAddinsEnabled flag is false, you will not encounter this issue unless you click the "Open in new window" button to open the pop-out window yourself.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 20210426004.07
* Operating System: Windows 10
* Browser (if using Office on the web): Edge 90.0.818.49

**Comment by mscharlock** [comment] 2021-04-30 18:17
Hi @exextoc - can you have a look at this issue? Thank you!

**Comment by exextoc** [comment] 2021-05-02 06:45
Does this happen only when you install any on send add-ins or does it happen even when just the flag OnSendAddinsEnabled is set to true without any on send add-ins installed?

**Comment by clavx** [comment] 2021-05-07 09:09
If the OnSendAddinsEnabled flag is True and any On-Send add-in is not installed, clicking the Send button will not automatically pop-out the window, so this will not occur. However, you can reproduce it by opening the window yourself.

**Comment by clavx** [comment] 2021-05-08 08:27
https://user-images.githubusercontent.com/58804032/117532418-eed91b80-afd6-11eb-8c26-6e03910f56c8.mp4

**Comment by exextoc** [comment] 2021-05-11 10:24
Thanks @clavx for your response.  It looks like this bug is reproducible even with just simple mail compose pop-out and no addin. This is same as issue #1838 which we have asked OWA Team to look at internally. I will mark this issue as duplicate of #1838 and also notify internally about this issue as well.

**Closed as completed by exextoc** 2021-05-11 10:24 UTC
Labels: Area: Outlook, Resolution: duplicate
