### ISSUE TITLE
Date value not recognized by Excel

### ISSUE THREAD

**Issue by jag-cloudextend** [OfficeDev/office-js#1559] opened 2020-12-21 16:44 UTC
When we format the column as Date type (dd/mm/yyyy) and write a date (Ex: 21/12/2020), Excel is not recognizing it as a Date value

## Expected Behavior
It should treat the value as Date and give us the option to filter them as Dates instead of Text
![image](https://user-images.githubusercontent.com/12657943/102798407-0ff9f080-43d7-11eb-9e8b-aff0c2bae2b3.png)

## Current Behavior
They are recognized as Date properly and we are not able to use the Excel Date filters
![image](https://user-images.githubusercontent.com/12657943/102797534-d4125b80-43d5-11eb-9da4-9c9b4788c2a6.png)

## Steps to Reproduce, or Live Example
* Link to live example: 
https://gist.github.com/Jagapathi126/0bdf729dd97267c2cd4a098ee27aa640

## Context
We have a product that pulls data from NetSuite to Excel. Different customers have different date formats in NetSuite. If we don't format the column accordingly, Excel can treat the month as a date giving wrong information. If we try to format it, Excel is not recognizing the dates due to which customers are unable to use the filter feature of Excel.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Happening on all the Platform
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16:44 (20121301)
* Operating System: Mac, Windows

**Comment by MandytMSFT** [comment] 2020-12-24 05:53
@Jagapathi126 Thanks for reaching us. Can I know how you get below date filter window pop up ?  I tried the same setting in Gist on Excel UI, It behaved the same as API did. 

![image](https://user-images.githubusercontent.com/52641972/103064557-33978380-45ef-11eb-9aff-bd09ac04c746.png)

**Comment by jag-cloudextend** [comment] 2020-12-24 11:11
I got this dropdown by directly typing in the dates in the specified format (In this example `dd/mm/yyyy`) into the Excel table

**Comment by MandytMSFT** [comment] 2020-12-25 03:03
@Jagapathi126 If I typed dates with format(dd/mm/yyyy), I still can't get the data filter shown as below. But If I typed date with format (yyyy/mm/dd), then I can get the date filter shown correctly and the UI displayed as dd/mm/yyyy since you set the numberformat as dd/mm/yyyy
 
![image](https://user-images.githubusercontent.com/52641972/103116036-d3ace580-469f-11eb-9900-d7ec8bd7cdc2.png)

I changed one line in your gist as below, then it works for me. Could you help confirm if this is what you want ?

    **table.rows.add(0, [["2020/02/14"], ["2020/02/15"], ["2020/02/16"], ["2020/02/17"], ["2020/02/18"]]);**

**Comment by jag-cloudextend** [comment] 2020-12-26 05:40
@MandytMSFT thank you for the response. The reason we are formatting the column first so that we don't need to run a loop on the date fields in the response from our source system and convert it into ISO format. We expect that if the Date provided is in the same format as the column format, Excel should recognize it as a date. What do you suggest?

**Comment by MandytMSFT** [comment] 2020-12-29 02:41
@Jagapathi126 (I am not sure if it's related to locale) Looks like if the input data format is DD/MM/YYYY, Excel will recognize it as Text instead of Date. Is it possible to change your input data format as MM/DD/YYYY or YYYY/MM/DD ? Input data format is the one table.rows.add used.

**Comment by jag-cloudextend** [comment] 2020-12-29 12:34
@MandytMSFT my system preferences are set to use `DD/MM/YYYY` as the date
![image](https://user-images.githubusercontent.com/12657943/103283872-b9f10280-49ff-11eb-93b5-fe5ed8a05799.png)
So the expectation is Excel should recognize the text in the above format and process it as the Date field.

**Comment by sameera** [comment] 2021-01-06 02:43
@MandytMSFT @lindalu-MSFT 
Can you kindly take another look at this issue.

I have further simplified @Jagapathi126 's gist here to highlight the key issue.
Please run this gist in ScriptLab: https://gist.github.com/sameera/40208a075eecf03553a06f396f608493

Steps:
1. Set the computer's region settings to UK. Date format will now be DD/MM/YYYY
2. Write The following dates to a table range (as in the gist):
` [["02/14/2020"], ["02/15/2020"], ["16/02/2020"], ["17/02/2020"], ["18/02/2020"]]`
Note that first 2 dates are in US format and the rest is in UK format. What would be expected is that dates in UK format will be treated as valid dates and US formatted dates treated as General data. This expectation is based on the fact that there is no reason for Excel/Office.js to assume US format given the current setup.
3. Observe that when the data is written, the 2 US dates are formatted as date properly (and now appear in UK format in the cells). Other 3 cells are not.

Here is a screen recording showing what happens:

https://user-images.githubusercontent.com/208470/103722862-e7890d80-4ff6-11eb-8a47-8c8ededf2cec.mp4


Our add-in integrates Excel with a 3rd party CRM that has global distribution. If we were to reformat data coming from the CRM (which is sent in the user's date format), we'll be potentially reformatting tens of thousands of rows per request.

**Comment by MandytMSFT** [comment] 2021-01-08 03:22
@sameera thanks for the update. We have confirmed the API do have different behavior as Excel UI when inputting the same date . BUG 4766979 has opened for internal track. Unfortunately there is no timeline to share at this time.

**Comment by honxmsft** [comment] 2021-01-19 09:33
@sameera After we discussed with PM, we think the current API's behavior is by design.

At the early design of the js API, the APIs use USA locale by default. The same code run in different regions will produce same result unless you explicit use locale related API. If you want to use the current locale to set value, please explicitly use [Range.formulasLocal](https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#formulasLocal).

You can use it as a workaround for the case like your example, the result cells date format will be opposite with result of using `Range.value`.

Currently the feature, setting Range value using current locale instead USA locale by default, you requested, is not a part of the product. We track Office Add-in feature requests on our [UserVoice page](https://officespdev.uservoice.com/). Please add your request there. Feature requests on user-voice are considered when we go through our planning process.

**Comment by sameera** [comment] 2021-01-20 01:19
@honxmsft Thank you for the details.
We will switch to using `formulasLocal`.

**Comment by donlvMSFT** [comment] 2022-11-16 11:06
I'd like to close this thread as the discussion is closed, thanks for the discussion.

**Closed as completed by donlvMSFT** 2022-11-16 11:06 UTC
Labels: Area: Excel, Resolution: has workaround, Status: in backlog
