### ISSUE TITLE
"Runtimes" section in TaskPaneApp section within VersionOverrides incorrect

### ISSUE THREAD

**Issue by Geraint87** [OfficeDev/office-js#1756] opened 2021-03-26 16:53 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Either it's not wholly accurate, or there is an old schema definition, but what I observe is:
The documentation says that the Runtimes section comes immediately inside the `Host` and before `AllFormFactors`:
![image](https://user-images.githubusercontent.com/5928208/112665454-fdb6a500-8e52-11eb-8b05-cb30da824812.png)
[TaskPane VersionOverrides](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering#task-pane-add-in-element-ordering-within-versionoverrides)

The other doc page, related to Runtimes is roughly consistent, but the ... dots before suggest there are elements before it too.
![image](https://user-images.githubusercontent.com/5928208/112665606-28086280-8e53-11eb-8d61-52be93549912.png)

The schema definition may say the same:
![image](https://user-images.githubusercontent.com/5928208/112665902-761d6600-8e53-11eb-9d3c-76b9ea24b803.png)

But the manifest project won't build in Visual Studio 2019.
![image](https://user-images.githubusercontent.com/5928208/112666105-b5e44d80-8e53-11eb-927a-9cf540da29d7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ed9215-8890-0046-5ead-86125b02e74e
* Version Independent ID: 97ceba41-89d3-a3fd-0942-e62e9fca7f72
* Content: [How to find the proper order of manifest elements - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering)
* Content Source: [docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/manifest-element-ordering.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment] 2021-03-27 00:53
@mattgeim Can you take a look, or assign to an appropriate person to investigate? We may need to contact Visual Studio folks.

Thanks.

**Comment by Geraint87** [comment] 2021-04-22 17:33
Any news please @mattgeim ?

**Comment by mattgeim** [comment] 2021-04-26 23:17
@millerds can you help look in to this?

**Comment by millerds** [comment] 2021-05-24 18:48
VS uses some xsd files to validate the manifest and provide intellisense.  I looks like those files are out dates compared to the updated documentation you are referring to.  This needs to be updated in VS.

In the mean time, if you take the documented schema you've pointed to and update the xsd files on your machine (at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Xml\Schemas\1033) then you should be able to temporarily workaround this issue on that machine (updates to VS could cause these to get reverted).

**Comment by kevinxbrown** [comment] 2021-07-20 11:33
Hi, even after I updated Visual Studio 2019 to the latest release, I had the same issue. However, I can confirm that I obtained the latest XSD file from https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/c6a06390-34b8-4b42-82eb-b28be12494a8 and overwrote the local file mentioned above, and this fixed the problem.

**Comment by davidchesnut** [comment] 2021-08-02 16:33
Hi @Geraint87 and @kevinxbrown,

We documented recently in the troubleshooting guide how to work around this problem and update the XSD files in Visual Studio. See [Troubleshoot development errors with Office Add-ins - Manifest schema validation errors in Visual Studio projects](https://docs.microsoft.com/office/dev/add-ins/testing/troubleshoot-development-errors#manifest-schema-validation-errors-in-visual-studio-projects). 

Thanks!
David

**Closed as completed** 2024-03-17 20:04 UTC
Labels: Needs: attention :wave:, Area: add-ins platform
