### ISSUE TITLE
Office.Document.getFileAsync returns wrong file type for xlsm files

### ISSUE THREAD

**Issue by jwhite-venacorp** [OfficeDev/office-js#1955] opened 2021-06-24 23:29 UTC
# Provide required information needed to triage your issue

We are using code similar to what is provided in [the documentation](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=excel-js-preview#getFileAsync_fileType__options__callback_) to get the bytes of the Excel file being used with our addin. The file is then saved in our own cloud file system for download later, back-end processing, or report distribution. When the file is XLSM, the bytes we retrieve from the API and save to our server appear to be for an XSLX file, and re-opening as an XLSM fails.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.14210.20004
* Operating System: Windows 10, OS build 19042.1052
* Browser (if using Office on the web): N/A
 
## Expected behavior

The file should be XLSM file type.

## Current behavior

The file is XLSX file type.

## Link to live example(s)

Calling code such as [this](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=excel-js-preview#getFileAsync_fileType__options__callback_) on an XLSM file.

# Provide additional details

## Context

Our users may have macros to provide their own custom functionality through form elements or custom functions, which they expect to use with our addin (although they would not interact directly.)

## Useful logs

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by lindalu-MSFT** [comment] 2021-06-25 17:09
@keyur32 is this something you can answer easily or do we need to ask the product team?

**Comment by gingerjia** [comment] 2021-07-01 07:47
Thanks @jwhite-venacorp for reporting the issue! 
From our [doc,](https://docs.microsoft.com/en-us/javascript/api/office/office.filetype?view=excel-js-preview)  getFileAsync return .xlsx is by design.
![image](https://user-images.githubusercontent.com/62282034/124085718-ebb45600-da82-11eb-8660-668c1532d640.png)

I tried to create a new workbook with the base64 string from getFileAsync and save it as XLSM file directly as below, the newly created XLSM file can open successfully.
Excel.createWorkbook(base64string).catch(function (error) {
       console.error(error);
    });
![image](https://user-images.githubusercontent.com/62282034/124085952-20c0a880-da83-11eb-92e6-0c0a11a5b627.png)

May I know how you save the file to your server? Can you try my above suggestion?
If it still cannot unblock you, please let us know. Thanks!

**Comment by jwhite-venacorp** [comment] 2021-07-05 21:00
Thanks for the follow up @gingerjia. I tried using one of scriptlab's built-in example snippets "Get file using slicing" which uses the functions `Office.context.document.getFileAsync` and `file.getSliceAsync` to generate a Base64 string for the current file and then create a copy of the file using `Excel.createWorkbook`. I made a simple file with a button and macro (it just says "hello world"). When I run the snippet, it will generate the base64 string, the file will open, and the button will be on the sheet, but the macro triggered by the button is _not_ in the new document. The file can then be saved as an XLSM but the macro contents are lost at that point. (I was going to include the file I was just testing on, but since this is a macro-enabled file, I cannot share it through GitHub!)

Is there any alternative to getting the file by slices?

We save the file to the server by getting the file by slices and POSTing the contents (the base64 string) in the body to an endpoint that accepts a multipart request body.

**Comment by gingerjia** [comment] 2021-07-06 15:53
Hi @jwhite-venacorp Please help to confirm my below repro steps to make sure we are talking the same issue:
1. create a new xlsm file 1.xlsm
2. Insert button at Ribbon [Developer] tab
3. Create a new Macro as below and named it as 'Hello'
   Sub Hello()
   MsgBox "Hello World"
   End Sub
4. Select the button and right click it, click [Assign Macro] and assign the step3 macro to the button
5. Click the button and make sure dialog with "Hello World" pops up
6. Run gist https://gist.github.com/gingerjia/748c1fdbf23a16ffc9b6b0bbb18520a1 to [Get File] and [Create workbook from string] with Office.context.document.getFileAsync, file.getSliceAsync  and Excel.createWorkbook APIs, get a new file 2.xlsm
7. Click the button at newly created file 2.xlsm, it will pop up below message:
![image](https://user-images.githubusercontent.com/62282034/124623771-d5f1c700-deae-11eb-975e-27d62179a26a.png)
It's due to the button at 2.xlsm didn't assign correct macro to it. 
And if you see nothing at 2.xlsm Macros dialog, then it's because your original 1.xlsm file isn't at same location with newly created 2.xlsm file.

If this is the same issue you met, then maybe you can take below actions to unblock you first:
1.  Please upload the original xlsm file that has defined macros to the same server folder location that new files will be stored, such as put the file under c:\doc\1.xlsm
2.  Create new workbook with APIs and save it to c:\doc\2.xlsm
3.  At 2.xlsm, select the button and right click it, click [Assign Macro], you will see macro like ['1.xlsm'!hello] and assign the macro  to the button -> now the macro works at 2.xlsm file 
4.  Run gist at 2.xlsm to create new workbook 3.xlsm, you will find the macro is stored at 3.xlsm and macro can be triggered by the button, no need to assign macro to button again.
It means after get the file slices once by API and save it as xlsm, then based on the newly saved xlsm file to create new xlsm files, the macro can be triggered as expected.

From current behavior investigation, it's a little kind of by design. 
We will investigate further to see if possible to copy the macro with absolute path. And if have new progress, we will let you update also. 
Thanks @jwhite-venacorp!

**Comment by gingerjia** [comment] 2021-07-12 03:09
@jwhite-venacorp, I double confirmed the original API design and for macro enabled file xlsm, we didn't support it as at that time there is no customer requirement for it. So it's by design issue.
I have created a bug 5257622 to track your requirement and the fix will check-in soon. We will keep you update for the deploy progress. 
Thanks again for reporting the issue!

**Comment by gingerjia** [comment] 2021-07-15 02:40
@jwhite-venacorp and @lindalu-MSFT, the fix has been check-in. When deployed to Desktop, will update to the thread. Thanks!

**Comment by jwhite-venacorp** [comment] 2021-07-22 19:12
@gingerjia thanks for the follow up, sorry I was a bit delayed responding. Does this mean that the API will support macro-enabled files? Or will it just support the case of copying macros with absolute path?

**Comment by gingerjia** [comment] 2021-07-23 02:04
@jwhite-venacorp, my fix is to support macro-enabled files (.xlsm) for this API, when calling Office.context.document.getFileAsync, the file slices will contain the macro related info also. :)
Please let us know if you have any other issues. Thanks!

**Comment by jwhite-venacorp** [comment] 2021-07-23 14:23
Do you have an estimate for when this will be in the Beta channel and we can test it out?

**Comment by gingerjia** [comment] 2021-07-27 02:57
Since it depends on Win32 deployment, so may need about 1~2 month later. Currently it's waiting for merging to main branch. When the merge work done, then can get more accurate estimation. I will update here when get the accurate time.
Thanks!

**Comment by gingerjia** [comment] 2021-08-16 09:18
@jwhite-venacorp, the fix has been deployed to CC( Preview) at Aug 05. And for CC(Production) is planned to deploy at Aug 23. Thanks!

**Comment by gingerjia** [comment] 2021-08-30 05:40
@jwhite-venacorp, I verified the issue at PROD and it works as expected now:
![image](https://user-images.githubusercontent.com/62282034/131290660-a3638af4-32e2-402c-9efc-11b9b165529b.png)

Thanks!

**Comment by jwhite-venacorp** [comment] 2021-08-30 12:59
Thanks @gingerjia -- I tested this on a beta/preview a few weeks ago and everything worked! We really appreciate this fix.

**Comment by lumine2008** [comment] 2021-08-30 13:35
Thanks @jwhite-venacorp for your confirmation on the fix

**Closed as completed by lumine2008** 2021-08-30 13:35 UTC
Labels: Needs: attention :wave:, Area: Excel, Type: product question
