### ISSUE TITLE
Outlook Online, IE & Edge, the displayDialogAsync method does not work

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1285] opened 2020-07-17 10:56 UTC
In an Outlook add-in for compose mode, we call displayDialogAsync. In IE and Edge, the method does nothing, the dialog window does not show up, the callback is not executed.

## Expected Behavior
The displayDialogAsync method shall work correctly.

## Current Behavior
Nothing happens, the dialog window does not show up, the callback is not executed.

## Steps to Reproduce, or Live Example
Please try the following code:

`Office.context.ui.displayDialogAsync('https://ablebits.com', { width: 30, height: 30 }, (asyncResult) => {`
`  console.log(asyncResult);`
`});`

## Your Environment
* Platform: Office Online
* Host: Outlook
* Office version number:
* Operating System: Windows 10
* Browser (if using Office Online): IE 11.959.18362.0 & Edge 44.18362.449.0

**Comment by exextoc** [comment] 2020-07-17 12:07
@DmitryKostochko I tried the code shared by you it works for me. Does API work in other browsers or Outlook Desktop Client? Can you check what does console.log(Office.context.requirements.isSetSupported("DialogApi",1.1)); returns?

**Comment by DmitryKostochko** [comment] 2020-07-20 12:48
2exextoc, sorry, my original code sample was incorrect, please try this one:

`    try {`
`      const url = location.origin + '?param1&param2';`
`      console.log(url);`
`      Office.context.ui.displayDialogAsync(url, { width: 30, height: 30 }, (asyncResult) => {`
`        console.log(asyncResult);`
`      });`
`    } catch (ex) {`
`      console.error(ex);`
`    }`

It seems something happens when a URL with parameters is passed to displayDialogAsync.

>> Does API work in other browsers or Outlook Desktop Client?

Yes, it does. Other browsers and Desktop Client are not affected, we only see this issue in the IE and Edge browsers.

>> Can you check what does console.log(Office.context.requirements.isSetSupported("DialogApi",1.1)); returns?

It returns true.

**Comment by exextoc** [comment] 2020-07-20 15:07
We are able to reproduce this issue on our side on above mentioned versions of IE and Edge. Thanks for reporting this issue regarding DisplayDialog API. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by DmitryKostochko** [comment] 2020-07-21 09:09
@exextoc, I think this issue is quite critical because Edge is the default browser in Windows 10 and users actively use it. Please consider fixing this issue as soon as possible.

**Comment by fkranenburg** [comment] 2020-07-22 07:50
This is the same issue as #1255. This should be fixed ASAP because it makes almost any add-in completely unusable.

**Comment by seandevenish** [comment] 2020-07-22 09:38
We have production enterprise code broken by this, it needs urgent attention!

**Comment by exextoc** [comment] 2020-07-22 10:57
Can you tell us which Add-in is impacted by this issue?

**Comment by onesev** [comment] 2020-07-22 12:35
I am experiencing this as well and the issue is rendering the desktop version of Outlook useless. If you look at #1286 , it's mentioned that this issue didn't occur until July 8th.  I did some digging and it looks like [parseUrl](https://github.com/OfficeDev/office-js/blob/bf505bf7310c28718df373720eab015369d5a15f/dist/outlook-web-16.01.debug.js#L901) is returning a blank url for IE, thus causing `.split` to throw `"TypeError: Unable to get property 'split' of undefined or null reference`. 

I also rolled back/referenced office.js locally to the version mentioned in #1286, which fixes the problem, for now. 

I hope this helps.

**Comment by axelauvinen** [comment] 2020-07-23 07:15
Any update on possible timeline for this fix? We are experiencing massive usability block for a hefty amount of users in our services, and are also opting to rolling back to locally hosted version mentioned in https://github.com/OfficeDev/office-js/issues/1286

**Comment by exextoc** [comment] 2020-07-23 07:38
Thanks for providing for more information @onesev. We are actively working on this issue as it is high priority. We will update this thread once the fix is deployed.

**Comment by Enotsoul** [comment] 2020-07-23 14:29
Hi there, I can confirm that this issue also affects our test, staging AND production environment in  OWA Outlook Addin. 
Seems to impact Edge, oddly enough IE 11 seems to work for what I've tested. (Other things don't work there, but that's another issue) 

```
 TypeError: Unable to get property 'split' of undefined or null reference
   at getHostnamePortionForLogging (https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:19:14630)
   at OSF.DDA.WAC.Delegate.**openDialog** (https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:19:197864)
   at g[] (https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:19:79725)
   at value (https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.js:19:174714)

```

**Comment by exextoc** [comment] 2020-08-04 09:59
The issue has been fixed and the fix has been pushed to production. 
Please check, if the issue is still reproducible or not.

**Comment by DmitryKostochko** [comment] 2020-08-05 14:35
@exextoc, I have just retested the issue in IE and Edge and can confirm that this #1285 is fixed, the displayDialogAsync method works.

**Closed as completed** 2020-09-02 10:00 UTC
Labels: Area: Outlook, Status: fixed
