### ISSUE TITLE
How to Open External excel file using network path or drive path.

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#4978] opened 2024-10-16 06:00 UTC
My Environment
Platform : PC desktop
Host: Excel
Office version number: Excel® for Microsoft 365 MSO (Version 2406 Build 16.0.17726.20078) 64-bit
Operating System: Windows 11 Pro

Hi team,
I want to load excel file using addin without base64 bytes.
How can I load that with physical path(Network path).

I can find that it's working for docx file in word using openDocument(filePath) method. 
https://learn.microsoft.com/en-us/javascript/api/word/word.application?view=word-js-preview#word-word-application-opendocument-member(1)

If there is method for excel please let me know.

thanks.

**Comment by qinliuMSFT** [comment] 2024-10-18 02:40
Duplicate of #3790 , this feature is currently not supported in Excel. If you expect to use this in Excel, it would be very helpful if you could help submit a feature request in our tech community ([here](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)) so that we can properly prioritize it based on the community voting numbers. Thank you very much!!

**Closed as completed by qinliuMSFT** 2024-10-18 02:40 UTC
Labels: Area: Excel, Type: product feature request, Resolution: duplicate
