### ISSUE TITLE
Cannot install/uninstall sideloaded add-in from OWA

### ISSUE THREAD

**Issue by truchonh** [OfficeDev/office-js#3545] opened 2023-07-27 16:44 UTC
# Provide required information needed to triage your issue
For a few months, we have been unable to uninstall (and install) add-ins from the web version of Outlook. After installing/uninstalling the add-in, it does get added/removed from the ribbon on the desktop version of Outlook, but even after reloading Outlook on the web, the add-in is either not removed when uninstalling, or does not show up when installing.

At first the issue appeared to be for our dev environment only, but we got reports from our clients and internally that the add-ins are not working properly on the web version of Outlook.

The manifest has not changed in over a year.

It is noted that *any* sideloaded Outlook add-in cannot be installed/uninstalled.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook web app
* Office version number: latest
* Operating System: Windows
* Browser (if using Office on the web): Chrome/Edge/Firefox
 
## Expected behavior
Installing/uninstalling sideloaded add-ins from the orange "Get Add-ins" button should respond.

## Current behavior
Installing the add-in and reloading the page -> the add-in is not visible in Outlook.
Uninstalling the add-in and reloading the page -> the add-in is still visible in Outlook, but any calls to the js api fail.

## Steps to reproduce
1. Open Outlook web app
2. Click the "Get add-in" button
3. Install any add-in
4. Reload the page
5. Add-in not visible

## Link to live example(s)
List of add-ins after uninstalling one of the two custom add-ins:
![image](https://github.com/OfficeDev/office-js/assets/25945907/c3bdc5ef-fb24-474e-8d43-76d0c6f70633)

Add-ins visible from the context of an email ("Borealis - LINC" should be uninstalled):
![image](https://github.com/OfficeDev/office-js/assets/25945907/1ba5fc55-a99f-4fc8-b19c-29bad85b3f84)

Add-ins visible with the same email opened in Outlook for desktop (expected behaviour):
![image](https://github.com/OfficeDev/office-js/assets/25945907/74e91e1d-2064-4c8b-bcc5-1793677b3c3b)

# Provide additional details
After a few weeks, the installed add-ins will eventually show up. 

Opening Outlook on the web from a different browser, clearing cached data and using incognito mode does not resolve the issue.

## Context
1. It is impossible to test the add-in internally using the web version of Outlook
2. It is impossible to onboard clients to our add-in if they are using Outlook on the web

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by t-ariyoshi30907** [comment] 2023-07-28 03:40
@exextoc 

I am experiencing the same issue in my environment.
Additionally, there have been reports of this problem occurring from other users as well.

This behavior is not limited to my product; it occurs with other custom add-ins too.
My customers are facing difficulties because of this problem. Could you please investigate it urgently?

**Comment by exextoc** [comment] 2023-08-07 11:24
We are currently seeing a delay of up to four hours in installation and the add-in being available. If you are still facing issue and delay is more than four hours please let us know.

**Comment by exextoc** [comment] 2023-08-08 11:37
Closing this bug as it is a duplicate of https://github.com/OfficeDev/office-js/issues/3231

**Closed as not planned by exextoc** 2023-08-08 11:37 UTC
Labels: Area: Outlook, Needs: author feedback, Resolution: duplicate
