### ISSUE TITLE
Please provide a checklist for the main pitfalls which might block the add in to work.

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/office-js#1983] opened 2021-07-13 08:19 UTC
We have a wide range of customers which use our add in complex mostly highly secured environments.
It is very hard to provide the customer exact what he should configure to make the add in work in his "castle".

From the customer view it is our problem as vendor and we have to provide the needed configuration settings for them.
It would be very helpful to provide the administrator at the customer side a link to a checklist for the main pitfalls and workarounds for each.

For example one customer is getting this error: 
> ADDIN-ERROR :  This add-in could not be started. Close this dialog to ignore the problem or click "Restart" to try again.

It seems to be a group policy problem but we are not able to provide a minimal GP configuration for them...

**Comment by davidchesnut** [comment] 2021-08-02 23:25
Hi @ndeeH,

To be clear are you asking for a troubleshooting guide/checklist for IT/admins on managing add-ins? We do have a [Centralized Deployment FAQ](https://docs.microsoft.com/microsoft-365/admin/manage/centralized-deployment-faq?view=o365-worldwide) Is this what you are looking for? Or something similar?

Thanks,
David

**Comment by ndeeH** [comment] 2021-08-03 06:32
Nop. We are not looking for guidelines for centralized deployment.

We are looking for a FAQ for normal store deployed add ins - all common problems that could occur 
for example IE problems like Protected Mode or Group Policy based problems. 

Something like this - but complete and not product related and containing all common issues:
https://docs.revenuegrid.com/ri/fast/articles/Troubleshooting-Add-In-Could-Not-Be-Started/

**Comment by efrene** [comment] 2021-09-17 19:49
Hi @ndeeH 
Thank you so much for this feedback and for pointing to the example. I am going to be looking into this and will research putting this together. Please provide any additional information that you think might be helpful.  Thanks again!
Efren

**Comment by ghost** [comment] 2021-10-11 21:00
This issue has been automatically marked as stale because it is marked as needing author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**. Thank you for your interest in Office Add-ins!

**Comment by ndeeH** [comment] 2021-10-12 04:40
Closing without anything done. Huh?

**Comment by davidchesnut** [comment] 2021-10-12 15:43
@ndeeH,  My bad. Thanks for reopening. @efrene I updated the status to under investigation...

**Comment by efrene** [comment] 2021-10-12 16:30
@ndeeH Sorry, I was out on vacation while this issue was inadvertently closed. @davidchesnut, thanks for reopening it.

**Comment by davidchesnut** [comment] 2023-02-10 21:57
@ndeeH and @efrene is there any progress on this issue? Should we transfer it to another repo? Thanks!

**Comment by efrene** [comment] 2023-02-10 22:16
@davidchesnut Sorry, this is still on my backlog but I have not had time to work on it yet and I've been working on other priority work.

**Comment by mmoore-3lc** [comment] 2023-02-11 04:46
Well, I'll get the ball rolling. I've had an add-in in production globally for almost 4 years, in (what feels like) a hundred different environments. Here are the most common pitfalls I've seen in terms of add-ins failing to work:

### General Add-in description ("It's just a website")
In environments that consider themselves 'secure', the team usually works with an IT dept to get authorization for the add in to be installed and actually working. In a company of one the IT dept may have just enough experience to be dangerous. 

I usually start by telling them that the add-in is essentially a special type of website, that runs in a browser inside of <Office app>. It gives them a frame of reference for the rest of what I'm about to tell them:

### Common checklist of problems in runtime environment

- Blocking (or otherwise no access to) the URLs listed in the manifest: When the add-in is installed from AppSource, the user never sees the manifest, it's invisible to them. However, the URLs/Domains listed there must be accessible from the user's machine, _specifically from their runtime environment._ That means the specific browser that <OfficeApp> uses to host the add-in must not have any settings that prevent the add-in and all of it's dependencies in the manifest from being loaded. These settings could be set in the browser itself, on the computer the browser is installed on, or on the network infrastructure that the computer is connected to. The specific cause could be several different things, for example a firewall, network proxy, the lack of an actual network route to the host, or even a DNS server that cannot resolve the hostnames. A good step for at least detecting this type of problem is to create a test page on the same site that hosts the add-in, to determine if the user's computer can reach that site. A static html page with the word 'Success' is plenty. Try to access this site using the browser that is on the computer that is the same one that <Office App> also uses (Edge/IE/Safar/etc.). 

Be sure to have a list of URLs handy for the IT team that have to go and confirm network routes to all of the URLs in the manifest, it will make their job much easier and they would be more inclined to help you :) 

I should also note here the cause of these types of access problems could occur at the target itself and not necessarily the environment. Check incoming IP restrictions or other necessary authorizations on the target. 

- Blocking URLs (or otherwise no access to) the URLs the app uses in the add-in: There is a section in the manifest that allows creators to specify any addresses their app will navigate the UI to. If, say, API calls were made from within the add-in, javascript files (such as `office-js`) and/or images from external sources were fetched, the add-in would still require access to these URLs as well, and they would not have to be listed in the manifest. In the case of office-js, without access to this the add-in couldn't do anything Office related (if it would even be able to boot), and in the case of other resources different problems would be caused. A not so simple workaround for this would be to include a simple diagnostic that could run to check any required routes as early in your app as possible, and the rest should go into the document containing the manifest URLs.

- Including features the runtime does not support: Here we move away from the network/supporting layers more into the app layers. Let's start with the browser: Any HTML/Javascript/CSS must be supported by all the browsers <Office App> uses to run your add-in. Breaking this rule may not result in a minor UI 'bug', it could mean consumers of your add-in merely see a blank page. Few UI problems are as nerve-wrecking as a blank page. 

To sprinkle some salt on this wound, viewing the console log in these situations usually results in non-bingable or rabbit-hole error messages. Catching this one depends on a strong testing strategy, and it would be more efficient by knowing which browsers your users might use to run your add-in (this gives standardized environments a leg up). The creator, or the consumers rather, is limited to the greatest common feature set supported by all of the different environments.

Last you have support for `office-js`. This one is kinda hard to mess up, but it can happen. In general trying to use features from one requirements set in your app while linking to a different office-js javascript file in your app may be problematic if you link to a more recent version than what the runtime will support, or use a feature that 'compiled' fine with the most recent @types/office-js, but is not in the office.js linked to in the app. Just confirm the requirements and keep an eye on your commits when troubleshooting.

That's all I can think of for now. I welcome others to add to this list.

**Comment by ndeeH** [comment] 2023-02-13 12:15
@mmoore-3lc Thank you for all your insights. 
@efrene Is there a way to bring them as common issues into the "official" office-js documentation?

**Comment by efrene** [comment] 2023-02-14 00:18
@ndeeH 
This is still on my backlog and will try to find time to bring this up as a future article.  I have to be honest in telling you I am not sure when I could get to this, as most of my efforts are on things that are deemed higher priority at this time.  But I will make some time to try to get to this.
@mmoore-3lc 
That you for the great info.  Would you have interest is publishing your article to the [Microsoft Community content repository](https://learn.microsoft.com/en-us/microsoft-365/community/?WT.mc_id=m365-15744-cxa)?  You write well and this is a great spot to include this info for now and for you to get credit for it as the contributor. If so, here is a [how-to article](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/README.md) on how to publish to the repo.  I can also put you in contact with the repo owner if you have questions.

**Comment by mmoore-3lc** [comment] 2023-04-26 10:21
> @ndeeH This is still on my backlog and will try to find time to bring this up as a future article. I have to be honest in telling you I am not sure when I could get to this, as most of my efforts are on things that are deemed higher priority at this time. But I will make some time to try to get to this. @mmoore-3lc That you for the great info. Would you have interest is publishing your article to the [Microsoft Community content repository](https://learn.microsoft.com/en-us/microsoft-365/community/?WT.mc_id=m365-15744-cxa)? You write well and this is a great spot to include this info for now and for you to get credit for it as the contributor. If so, here is a [how-to article](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/README.md) on how to publish to the repo. I can also put you in contact with the repo owner if you have questions.

I would be glad to! Thank you for the invitation.

**Comment by exextoc** [comment] 2023-07-14 05:04
No action for quite some time. Closing the issue.

**Closed as completed by exextoc** 2023-07-14 05:04 UTC
Labels: Needs: attention :wave:, Status: under investigation, Area: Centralized Deployment

**Comment by ndeeH** [comment] 2023-07-14 05:21
@mmoore-3lc Have you published your content in MS Community?
Your insights should be "conserved".
