### ISSUE TITLE
Dialog is sized as percentage of current window

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-js#189] opened 2018-07-05 19:03 UTC
The docs state that the width parameter "Defines the width of the dialog box as a percentage of the current display." However, actually, the dialog is sized as percentage of the currently active window, not current display.

## Steps to Reproduce, or Live Example
1. Add ScriptLab to [Excel]
2. Click "Help" from "ScriptLab" ribbon
3. Resize Excel and click "Help" again
4. Observe that the second dialog is sized relative to the size of Excel window, not the current display (which did not change).

## Context
We are not able to size dialogs appropriately to accommodate the content, because as the size of parent application (such as Excel) is changed, the dialog size changes and we cannot find this out from the code.

![image](https://user-images.githubusercontent.com/13841696/42342368-b73cf9da-804a-11e8-9ad1-c8739fd4b09d.png)

![image](https://user-images.githubusercontent.com/13841696/42342430-e4c92de2-804a-11e8-950a-e607ede30c7f.png)

**Comment by JuaneloJuanelo** [comment] 2018-07-23 21:53
@Rick-Kirkham  this is maybe a documentation issue,

**Comment by Rick-Kirkham** [comment] 2018-07-23 23:03
This was also raised as an issue on office-js-docs: https://github.com/OfficeDev/office-js-docs/issues/1457
I believe that the documentation is correct. @JuaneloJuanelo I will CC you on an email thread.

**Comment by JuaneloJuanelo** [comment] 2018-07-23 23:12
the document says only one is allowed. PLease:
1. dont remove assignment. (until we sync, or the issue is fixed.) 
2. if this is an issue in docs, lets close this one.

thanks!

**Comment by Rick-Kirkham** [comment] 2018-07-23 23:28
@JuaneloJuanelo I don't think _this_ issue is an issue with the docs. See the email thread. 
I don't know what you mean by "the document says only one is allowed". Are you thinking of the other issue about multiple dialogs open at the same time?

**Comment by dstaley** [comment] 2018-08-09 23:38
Just another data point: this seems to only affect Windows. Dialogs are properly sized based on screen dimensions on macOS.

**Comment by danielgwilson** [comment] 2018-09-07 17:52
Confirmed that this wasn't just an issue with the docs—this has been fixed (will match docs; percent of screen size not window) and will be shipped in an upcoming build

**Comment by kbl212** [comment] 2018-09-18 13:03
Just wanted to chime in and mention that I'm also seeing this exact same issue in my Outlook add-in  (I assume that the above mentioned upcoming build will fix the issue across all Office hosts, including Outlook, but I just thought I would mention it here)...it works according to the documentation on macOS, but on Windows the dialog is sized as a percentage of the Outlook client window.

**Comment by ATrogolo** [comment] 2018-11-23 13:52
@danielgwilson  @kbl212 I tried today to see if this issue was fixed but we're still stucked .. the dialog is created relatively to the size of the Excel application yet. 
Is there any update?

**Comment by Rick-Kirkham** [comment] 2019-03-21 00:08
@ATrogolo This should be fixed. I'll close this. If you are still having this issue, please add a comment here and we can reopen it.

**Closed as completed by Rick-Kirkham** 2019-03-21 00:08 UTC
