### ISSUE TITLE
Deployed Excel addin disapeared 

### ISSUE THREAD

**Issue by xti77** [OfficeDev/office-js#3035] opened 2022-12-12 11:27 UTC
Centrally deployed addin stopped working showing message "Update-Addin". Also disappeared from "Admin managed" Addins (Refresh did not help). Majority of users regained the addin after several days with no proactive remediation. Addin is enabled for "All" users.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office365
* Host [Excel, Word, PowerPoint, etc.]: MS Excel
* Office version number: v 2202
* Operating System: Win10
 
 
## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by wamaina** [comment] 2022-12-12 17:37
Thank you for reaching out! Without the steps to reproduce this issue, it is very difficult to be able to help give guidance around what may have happened. Can you share any additional details? For example, had you made any recent changes to the add-in?

**Comment by xti77** [comment] 2022-12-12 18:05
I suspect that the issue was related to major addin update. Theoretically, the addin should be updated automatically as it is deployed from MS store but experienced some issues in the past.There was no Windows or Office update. The addin is SAP Analytics Cloud.
Best regards,
Tomas Indruch
________________________________

**Comment by AkhileshShah-MS** [comment] 2022-12-12 19:33
@xti77 this could most likely be happening if the custom domain added to manifest at time of deployment got reset with the upgrade. Please follow the steps mentioned in the App details on AppSource.com to register custom domain. Please reach out to us if that does not resolve the issue for you.

**Comment by AkhileshShah-MS** [comment] 2023-01-04 10:07
@xti77 Resolving this due to no further communication. Please open new ticket if further help is needed.

**Closed as completed by AkhileshShah-MS** 2023-01-04 10:07 UTC
Labels: Area: Excel, Resolution: question answered
