### ISSUE TITLE
Opening dialog from custom functions inside of Excel desktop 

### ISSUE THREAD

**Issue by SWDevB** [OfficeDev/office-js#650] opened 2019-08-05 13:27 UTC
When I open a dialog via OfficeRuntime.displayWebDialog during the execution of a custom function in the Excels's desktop version, the page I provided the URL for is only shown once. So when I evaluate a single formula it is shown, after running the function again the dialog only shows a white page. 

## Expected Behavior
I would expect the dialog shows the page matching the url parameter on every call.

## Current Behavior
Like mentioned above the second execution of the function causes the dialog to show an empty page. When I try to call the dialog twice in one function evaluation, (await the calls of course) the dialog is shown a second time it is only white.

In Chrome and Excel online it is working correctly.

I tried to call an external page (google.com) to check whether it is caused by the called page and the behavior in Excel desktop remains the same.

Sometimes, it seems to depend on the time went by since the last run, the page will show up occasionally on another opening of the dialog

## Steps to Reproduce, or Live Example
That's the function I use to open the dialog inside functions.ts

```
function getTokenViaDialog(url) {
    return new Promise(function (resolve, reject) {
        OfficeRuntime.displayWebDialog(url, {
            height: '50%',
            width: '50%',
            displayInIFrame: true,
            onMessage: function (message, dialog) {
                resolve(message);
                dialog.close();
                return;
            },
            onRuntimeError: function (error, dialog) {
                reject(error);
            },
            onClose: function () {
                resolve();
            },
        }).catch(function (e) {
            reject(e);
        });
    });
}
```
That's the call in a custom function
`await getTokenViaDialog("https://google.com");`

## Context
There are two use cases, opening a login dialog or a message on error 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1906 (Build 11727.20210 Click-to-Run)
* Operating System: Windows 10 Enterprise 1903 18362.239
* Browser (if using Office Online): Chrome (running there)

**Comment by zakhan4** [comment] 2019-08-05 14:55
I'm also facing the same exact issue. 

### My environment

- Platform [PC desktop, Mac, iOS, Office Online]: PC
- Host [Excel, Word, PowerPoint, etc.]: Excel 64 bit
- Office version number: 1908 (Build (11929.20002 Click-to-Run)
- Operating System: Windows 10 Enterprise 1903 18362.239

**Comment by wamaina** [comment] 2019-08-06 18:24
Thanks @SWDevB and @zakhan4 for reporting this issue!

@keyur32, I was able to reproduce this as well. Could you follow-up on this bug?

**Comment by keyur32** [comment] 2019-08-06 19:23
Investigating. Thanks for reporting.

**Comment by keyur32** [comment] 2019-08-06 20:28
Internal Bug #3538661.

**Comment by matsisak** [comment] 2019-11-15 19:38
I'm facing the same problem. Any update on this issue?

My environment
Platform [PC desktop, Mac, iOS, Office Online]: PC
Host [Excel, Word, PowerPoint, etc.]: Excel 64 bit
Office version number: 1905 (Build (11617.20002 Click-to-Run) Office Insider
Operating System: Windows 10 Enterprise 1809 17763.864

**Comment by RuoyingLiang** [comment] 2019-12-09 09:14
The issue is already fixed. Could you update to latest version and check again? If you still encounter this issue, please let us know with your Excel Build number. Thanks

**Comment by keyur32** [comment] 2020-05-11 19:56
Closing this as was previously fixed.

**Closed as completed by keyur32** 2020-05-11 19:56 UTC
Labels: Area: Excel, Type: product bug, Status: fixed, Area: custom functions
