### ISSUE TITLE
New Outlook for Mac does not show Custom Categories

### ISSUE THREAD

**Issue by Byron-Mo** [OfficeDev/office-js#1535] opened 2020-12-03 22:17 UTC
The new Outlook for Mac UI does not show custom categories on emails that previously had them. Default categories, however, are available.

## Expected Behavior
Emails with a custom category should be displayed

## Current Behavior
Emails with a custom category is not available. Emails with a default/pre-existing category is available

## Useful logs
New Outlook for Mac (custom category):
![image](https://user-images.githubusercontent.com/14811552/101094386-2ef02a00-3571-11eb-970b-16e774ab07ca.png)

New Outlook for Mac (default category):
![image](https://user-images.githubusercontent.com/14811552/101094988-1a606180-3572-11eb-9c47-b60264c16ef5.png)

Old Outlook for Mac (custom category):
![image](https://user-images.githubusercontent.com/14811552/101094559-770f4c80-3571-11eb-9f2f-f75a201b5cc7.png)

**Comment by exextoc** [comment] 2020-12-05 13:34
Can you share the version of Outlook Mac?
We can route this to the Outlook team internally.

**Comment by exextoc** [comment] 2020-12-07 19:39
We are not able to reproduced this issue at our end nor the concerned team is aware of any such issue.
Can you please share Outlook version and more detailed repro steps?

**Comment by Byron-Mo** [comment] 2020-12-07 23:51
Thanks, following up with the customer and will provide updates soon

**Comment by Byron-Mo** [comment] 2020-12-08 18:41
Affected Outlook for Mac version: 16.43 (20110804)

We have an Outlook addin that is setting a custom category with EWS (https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/categories). All custom categories that are set before or after enabling the new Outlook UI do not show when the new UI is enabled.

**Comment by exextoc** [comment] 2020-12-16 05:56
> Affected Outlook for Mac version: 16.43 (20110804)
> 
> We have an Outlook addin that is setting a custom category with EWS (https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/categories). All custom categories that are set before or after enabling the new Outlook UI do not show when the new UI is enabled.

Hello @Byron-Mo , just to confirm if you're trying to set custom categories in the new UI, then it is not possible since the new UI does not support 1.8 API set currently.

More details on this documentation - https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview

**Comment by Byron-Mo** [comment] 2020-12-16 05:59
Thank you for the information! Do you have a timeline of when 1.8+ will be supported?

**Comment by exextoc** [comment] 2020-12-17 06:14
> Thank you for the information! Do you have a timeline of when 1.8+ will be supported?

It is targeted to be available in [insiders ](https://insider.office.com/en-us/join/mac)in Feb of 2021.

**Comment by lindalu-MSFT** [comment] 2020-12-21 22:43
Closing resolved Feb 2021 (if needed, feel free to reopen)

**Closed as completed** 2020-12-21 22:43 UTC
Labels: Area: Outlook, Resolution: external
