### ISSUE TITLE
Office 365 online - We could not connect to the Office store catalog server for this add-in.

### ISSUE THREAD

**Issue by aplahore4** [OfficeDev/office-js#4825] opened 2024-08-23 11:44 UTC
### I am unable to run **_Microsoft Office Excel add-ins_** in **_Office 365 online_**.
I am receiving the error: 

> We could not connect to the Office Store catalog server for this add-in.

![image_2024_08_23T07_09_17_433Z](https://github.com/user-attachments/assets/f1775cda-55f7-498a-95cd-7b80ae086b35)

### The issue occurs only in **_Office 365 online_**; the add-ins work fine in the **_office desktop version_**.

**Comment by aplahore4** [comment] 2024-08-23 11:57
### Inspecting the browser console, it seems to be failing to load [MicrosoftAjaxDS.js](https://euc-excel.officeapps.live.com/x/_layouts/AddinServiceHandler.ashx?action=getEntitlements&app=excel&av=WAE160&corr=0d4592dc-6cc7-a4ee-fdde-ba5b1cd0b3a5&WOPIsrc=https%3A%2F%2Fmy%2Emicrosoftpersonalcontent%2Ecom%2Fpersonal%2Fd4d34d9d2a18d935%2F%5Fvti%5Fbin%2Fwopi%2Eashx%2Ffiles%2F2a18d9354d9d20d380d4d00000000000&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InVYZWhRSlBsZVZqTkNiYWtVaEdENkl5RlFRayJ9%2EeyJhdWQiOiJ3b3BpL215Lm1pY3Jvc29mdHBlcnNvbmFsY29udGVudC5jb21AOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwQDkwMTQwMTIyLTg1MTYtMTFlMS04ZWZmLTQ5MzA0OTI0MDE5YiIsIm5iZiI6IjE3MjQ0MTMxNjgiLCJleHAiOiIxNzI0ODQxNTY4IiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfGFobWFkMTIxNTJAaG90bWFpbC5jb20iLCJuaWkiOiJtaWNyb3NvZnQuc2hhcmVwb2ludCIsImlzdXNlciI6InRydWUiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwwMDA2MDAwMGY2ZmZmOTFhQGxpdmUuY29tIiwic2lkIjoiNTA0NzM3MDIwMjQ3NTg4NTM4MCIsImlzbG9vcGJhY2siOiJUcnVlIiwiYXBwY3R4IjoiMmExOGQ5MzU0ZDlkMjBkMzgwZDRkMDAwMDAwMDAwMDA7TU1Jb2RUdWsyeFpwNFNMUjJSVDdxT0dxM2xNPTtEZWZhdWx0OzsxQjAzQzQzMTJFRjtUcnVlOzs7Mzg0MDs1YTEzNDlhMS0zMDRmLTkwMDAtODRiZS0zYjZlNzJkY2E4NzciLCJmaWQiOiIxODg4NjgifQ%2EJahwqqqKiY%2Dlptaz9p7v57iH5LOwoooj9rEigrR1o5wyZrnun2QhNRU%2Dn%2DlVf4n%2DyiyYp2XwgyvBCEFVXhZwpfD1G6LM%2Dhe%5FkLLTCykaQ%2DeZ6ubx12ahYlV8c2Aq37GWDRrWeLl87%2DVpWL0f9tSuUJteb82bAH%5F8yyR%2D2eWLDnXx9nnMDmyhD0e8%2DUYUlGK1mZ7XdELZB%5FoGQOjwawuv2wPFubTYIJ%5FWEw4opbi8TCqtHgHNREd9QuHoA0grYF0J4JXRlVbi%2DGZT9lNFG%5F%5FbDTiZqt21xPbmLpOeNr3BahiXY%5FWtFD1ovdnuL4AJP9zMFFEOs8AfgkwV%5FeV7F0hbSw&access_token_ttl=1724841568930)

![image](https://github.com/user-attachments/assets/df4208e6-546a-49ba-8a5d-b9528ae7ced7)

**Comment by aplahore4** [comment] 2024-08-23 13:26
### This is my **_Office 365 online_** version
![image](https://github.com/user-attachments/assets/5a35732b-4699-4c53-a255-8161a43a4f04)

**Comment by shanshanzheng-dev** [comment] 2024-08-26 05:19
@aplahore4 Thanks for reporting this issue. We're looking into this root cause. Thanks for your patience.

**Comment by shanshanzheng-dev** [comment] 2024-08-26 09:19
Hi @aplahore4 this issue has been mitigated. Thanks.

**Comment by aplahore4** [comment] 2024-08-26 09:24
@shanshanzheng-dev Now working. Thanks.

**Comment by shanshanzheng-dev** [comment] 2024-08-26 09:36
OK Thanks, we'll close this issue.

**Closed as completed by shanshanzheng-dev** 2024-08-26 09:36 UTC
Labels: Needs: attention :wave:
