### ISSUE TITLE
Word: Context menu is only visible when the selection has a length (Office on the web)

### ISSUE THREAD

**Issue by osasseville** [OfficeDev/office-js#1427] opened 2020-10-07 15:50 UTC
Context menu buttons added using the manifest is only visible when some text is selected in the Word Webapp. This is not an issue in the Word Desktop.

## Expected Behavior
The context menu button should display even if no text is selected.

## Current Behavior
The context menu button is only visible when some text is selected in the Word web application. If the cursor has no text selected, the context menu button will not display.

## Steps to Reproduce, or Live Example

1. Create a new blank document in the Word web application.
2. Insert some text in that document.
3. Insert a new add-in by uploading a manifest.xml having a contextual menu as an entry point.
4. Right-click in the document and assert that the context menu button from the manifest is not visible.
5. Select some text in your document and then right-click on that text.
6. Assert that the contextual menu is visible.

[Video demo of the bug](https://termlynxpublic.blob.core.windows.net/media/github-issue-officejs-contextmenu-webapp.mp4)
[manifest.xml used for the video](https://gist.github.com/osasseville/95ae7d035c794210f17bdb1f4eb0078d)

## Context
Because of this issue and this other [issue](https://github.com/OfficeDev/office-js/issues/1392), we decided to not rely on office-js for implementing our context menu. We created a second plugin using AddinExpress that send the context menu events to the web application threw SignalR. That significantly increases the complexity the update deployment and authentication because there's two application now. We hope that Microsoft can fix this quickly so we can get back on only using the office-js.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Ofice on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System:  Windows
* Browser (if using Office on the web): Chrome

**Comment by lliu113** [comment] 2021-01-30 00:46
@osasseville - sorry for the very belated response to this. Are you still seeing this issue?

**Comment by osasseville** [comment] 2021-02-01 20:35
Hi @lliu113, I still see the issue.

**Comment by lliu113** [comment] 2021-02-08 22:04
@osasseville - thanks for confirming! Really appreciate the repro video and manifest too, thanks for providing that. Context menus are only supported for basic text, and not when no text is selected. It will also not work when e.g. text is inside a table. I understand this is frustrating and has added additional overhead, but unfortunately this is by design.

You can submit a new feature request on Office Voice - https://officespdev.uservoice.com/

Closing this issue, please reactivate if you have any additional questions/concerns.

**Closed as completed by lliu113** 2021-02-08 22:04 UTC
Labels: Area: Word, Resolution: by design

**Comment by leoseccia** [comment] 2021-02-27 11:11
@osasseville - did you submit a feature request? If yes, please share a link and I will throw some votes at it...

**Comment by vivek-lakhataria** [comment] 2022-07-01 10:59
@lliu113 @osasseville  I have created something similar my menu loads successfully but the issue I face is when i select some text and click on button it is not interacting with the TaskPane.
Hoping you can help

**Comment by osasseville** [comment] 2022-07-25 13:21
@lliu113 I can see that the uservoice has been closed. Can you provide a link where I can make a feature request?
