### ISSUE TITLE
On-send feature for Outlook add-ins takes a long time

### ISSUE THREAD

**Issue by guzman-rc** [OfficeDev/office-js#3079] opened 2023-01-10 20:51 UTC
The OnSend add-ins takes a long time to perform internal processes until it finally sends the email.
This delay occurs especially in **Outlook on the Web from pop out window maximized**. Occurs less frequently in Outlook desktop on Windows and Mac OS.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook on the web 
* Host [Excel, Word, PowerPoint, etc.]: Outlook on the Web and less frequently in Outlook desktop on Windows and Mac OS.
* Office version number: Microsoft 365.
* Operating System: Windows 10 and Mac Ventura 13.0.1
* Browser (if using Office on the web): Edge (Versión 108.0.1462.76 (Compilación oficial) (64 bits)) and Chrome (108.0.5359.125 (Build oficial) (64 bits)).
 
## Expected behavior
A test addin is provided that only checks if the email contains attachments:
https://www.adarsus.com/addin/OnSendTest/AttachmentsChecker.xml

The Addin checks if there are attachments in the email, if there are no attachments the email is blocked from being sent.

Emails should be sent without delay as the process of checking for attachments should not cause a delay. **The delay is even greater when, once the e-mail is blocked, we click to send email again.**

## Current behavior
The delay occurs randomly (approximately 70% of the time). This delay is 5 or 10 seconds until the email is finally sent.
In some occasions, the delay is longer than 30 seconds and the email is not sent.

## Steps to reproduce
1. Install the add-in: https://www.adarsus.com/addin/OnSendTest/AttachmentsChecker.xml
2. The mailbox policy must have the **OnSendAddinsEnabled** flag set to **true**, instructions: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=modern
3. Log in to Outlook on the Web.
4. Press the New message button to create a new email.
5. Press the button in the upper right corner of the new email to **view it in a new window** (pop out) and  **maximize this pop out window**.
7. Fill in the fields: e-mail address, subject and text of the message.
8. Send the email.

## Context
We provide a product that removes metadata from attachments.
This delay is especially annoying when the email has no attachments.

## Useful logs
- [X] Console errors
Attached is a screenshot of the log console where you can see that from the moment you click on send email, many calls are made to the MicrosoftAjax.js file.

![CapturaLog](https://user-images.githubusercontent.com/96702862/211652545-30e7eb73-81a1-451a-8824-1cb53aae1369.PNG)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by AlexJerabek** [comment] 2023-01-10 22:49
Thank you for reporting this @guzman-rc.

@exextoc, could you please investigate?

**Comment by timwan10** [comment] 2023-01-17 20:58
Will notify the OWA Add-ins crew about this, since you say the problem is longer in OWA. If this is indeed happening across platforms though, it is probably the connection to the actual add-in is slow. (i.e. it can only take as fast to load as the html file takes to load in the browser). using Fiddler when your add-in loads may reveal where the slowness is happening. (for example if you host the add-in in Localhost...does the problem go away?) 

On Win32, there is an option to use launchevents instead. Where Win32 Downloads the JS file ahead of time onto disk, and runs just the JS file in a Javascript engine. (on OWA and Mac, you still have to provide an HTML file to load though). So if the problem is slowness in loading HTML, this won't help. 

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest

**Comment by guzman-rc** [comment] 2023-01-19 09:35
Hi timwan10,
I don't think the problem is the connection to the add-in as it happens mainly in Outlook on the Web.

I have tested this Addin (this addin is very lightweight, it only checks for email attachments):
https://www.adarsus.com/addin/OnSendTest/AttachmentsChecker.xml
In Outlook desktop on Windows and Outlook on the Web (also in localhost), and the delay occurs in Outlook on the Web **from pop out window maximized**.

As you can see in the attached screenshot, from the moment we click _send email_ multiple calls are made to the file:
MicrosoftAjax.js until it finally finishes the process.

**Comment by timwan10** [comment] 2023-01-19 20:25
How long is the delay on non-OWA clients? 

This issue has been transferred internally to OWA Extensibility, so they will need to investigate the OWA issues.

**Comment by guzman-rc** [comment] 2023-01-20 11:08
For non-Owa clients, the delay varies between approximately 1 and 3 seconds. These values are perfectly acceptable.

**Comment by exextoc** [comment] 2023-01-23 12:29
Thank you for reporting this issue. We are able to repro and have added this to our backlog and will have a look at it. However, we have no timelines to share at this point.

Internal tracking id: 187625

**Comment by exextoc** [comment] 2023-02-10 07:52
Hi @guzman-rc, we are not able to reproduce this issue on our end now. Could you please confirm if you're still facing this issue? Thanks!

**Comment by alexm-plutoflume** [comment] 2023-02-14 17:16
@exextoc 

I'm not the OP of this issue but I can still recreate the issue with our addin.

In OWA - start drafting a new email - pop it out into a separate window. Open the developer console, then try sending the email.

You will see multiple calls are made to MicrosoftAjax.js with the error "Unknown conversationid". This sometimes interferes with processing it seems and slows things down.

This is in Chrome.

![image](https://user-images.githubusercontent.com/80270047/218809803-01553e69-1484-4027-a513-ce072dba9f78.png)

**Comment by guzman-rc** [comment] 2023-02-15 08:54
I have checked again and the issue still occurs in **Outlook on the Web** from **pop out window maximized**.

**Comment by t-miyake** [comment] 2023-02-16 00:45
The exact same problem occurs to me and my clients in Outlook on the Web from pop out window maximized.

![Screenshot 2023-02-16 094120](https://user-images.githubusercontent.com/9583126/219228821-a25f0042-934f-42b7-ac84-865b26da616c.png)

**Comment by exextoc** [comment] 2023-02-20 04:55
Hey,

Sorry for the delay in response, we are investigating this issue and will keep this thread posted.

**Comment by eugene-plutoflume** [comment] 2023-02-24 17:13
Hi @exextoc! I also see that problem in OWA while Outlook for Desktop works correctly, here is what I get when debugging:

![image](https://user-images.githubusercontent.com/32734640/221243818-81d4bb37-aaa4-48d8-a8cf-5b5b6c40bf67.png)

**Comment by avisheknand** [comment] 2023-04-11 03:19
Hello @exextoc , we are also experiencing same issue using Onsend add-in on Outlook on the Web from **pop out window maximized**. It takes ages to load the add-in . Any update on the issue or ETA on the fixes please?

**Comment by exextoc** [comment] 2023-04-11 11:34
Thank you for reporting the issue. We are able to repro it and are looking into it. We will update the thread soon after investigation.

**Comment by exextoc** [comment] 2023-08-07 09:58
This issue is fixed and fix has been rolled out to 100% users.

**Comment by avisheknand** [comment] 2023-08-08 00:43
Thanks @exextoc , i have verified, it loads much more faster now on Outlook on the Web when pop out window maximized.

**Closed as completed** 2023-08-08 06:14 UTC
Labels: Area: Outlook, Type: product bug, Status: fixed
