### ISSUE TITLE
Pinnable Add-In breaking Recipient Change notifications on Windows Desktop

### ISSUE THREAD

**Issue by jak-hammond** [OfficeDev/office-js#1437] opened 2020-10-15 12:17 UTC
We have recently implemented the pinnable add-in functionality and registered the required item change handler, however we have come across an issue on Windows desktop Outlook client where, when in inline composing mode, the recipient change handler seems to break completely and we do not get any change events firing, the active item event does still fire however.

Mac Outlook does not support the inline composing so the issue does not seem to be present there but the events all fire as expected; see Pinnable_Mac screenshot below. We have checked on OWA, using Chrome, with the inline composing and all the events behave as expected there; see Pinnable_OWA screenshot below.

## Expected Behavior
Both the recipient change and item change events should fire.

## Current Behavior
When we have registered the item change event, the recipient change event will no longer fire.

## Steps to Reproduce, or Live Example
* Link to live example: https://gist.github.com/jak-hammond/6274cac407208cd0ff89fb9927ab7331

## Context
This breaks the pinnable add-in functionality since when the user changes to a new message we cannot provide any information about new or removed recipients on their message.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: We have replicated this issue on a Beta and Current release
  - Current; Version 2009 (Build 13231.20262 Click-to-Run)
  -  Beta; Version 2011 (Build 13408.20000 Click-to-Run)
* Operating System: Windows
* Browser (if using Office on the web): N/A

## Useful logs
![Pinnable_Windows](https://user-images.githubusercontent.com/664193/96121963-b4981780-0ee8-11eb-912f-41a2a1fc5a6e.png)
![Pinnable_OWA](https://user-images.githubusercontent.com/664193/96121968-b6fa7180-0ee8-11eb-81ae-0729744f26e5.png)
![Pinnable_Mac](https://user-images.githubusercontent.com/664193/96121979-ba8df880-0ee8-11eb-9d3b-b7d5b6da7489.png)

**Comment by exextoc** [comment] 2020-10-15 23:31
The RecipientsChanged event registration is an item-only event. It doesn't persist after switching items.
Looking at your code, it appears you are not re-registering the event after switching items. If that's the case, the behavior you are seeing is By Design.

**Comment by jak-hammond** [comment] 2020-10-17 17:47
@exextoc gist has been updated to register handler again on item change and issue is still presenting itself as before.

**Comment by exextoc** [comment] 2020-10-18 01:10
We are able to repro this issue. We has been placed it in our backlog. Unfortunately, we have no timelines to share at this point. Internal tracking id : Office: 4565987

**Comment by jak-hammond** [comment] 2021-07-01 10:02
Hi there, is there any further update or ETA on this as it's still impacting the work we are trying to accomplish with a pinnable add-in

**Comment by milankonir** [comment] 2022-03-31 16:10
I was just about to report this only to find out this has already been around for.... 18 months 👎 

I spent a little bit more time on this and found out that adding the handler to the new item will only work after you remove it from the previous one. This can get a little bit tricky since when the `ItemChange` event fires, the office API does not provide any reference to the original one, you have to keep track of that yourself.

Here's a crude ScriptLab code sample:

```typescript
$("#run").click(run);

let previousItem: Office.MessageCompose | undefined;

function run() {
  Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, () => {
    if (previousItem) {
      previousItem.removeHandlerAsync(Office.EventType.RecipientsChanged, result => {
        console.log('Removed recipients changed handler', result);
        
        previousItem = Office.context.mailbox.item;

        if (Office.context.mailbox.item) {
          addRecipientsChangedHandler();
        }
      });
    } else {
      previousItem = Office.context.mailbox.item;

      if (Office.context.mailbox.item) {
        addRecipientsChangedHandler();
      }
    }

    
  }, result => {
    console.log('Add item changed handler', result)
    previousItem = Office.context.mailbox.item;
    addRecipientsChangedHandler();
  });
}

function addRecipientsChangedHandler() {
  Office.context.mailbox.item.addHandlerAsync(
    Office.EventType.RecipientsChanged,
    (eventAargs) => console.log(eventAargs),
    result => console.log('Add recipients changed handler', result)
  );
}
```

**Comment by exextoc** [comment] 2022-04-06 01:00
This bug was fixed recently. It will be fixed in builds 16.0.15028.***** and later.

**Closed as completed by exextoc** 2022-04-06 01:00 UTC
Labels: Area: Outlook, Type: product bug, Status: in backlog

**Comment by carlosb1504** [comment] 2022-11-09 16:32
@milankonir can you advise if this is now fixed for yourself? As far as I can see the ItemChanged event is only called for the first change, and not thereafter. @exextoc FYI

**Comment by milankonir** [comment] 2022-11-09 22:27
@carlosb1504 Tested with following ScriptLab Gist https://gist.github.com/milankonir/32b20a28d4ed68f7b36463702f263dbf and looks fixed to me. Keep in mind that you still have to register the recipients change handler on the new item whenever the item change event triggers

**Comment by carlosb1504** [comment] 2022-11-10 12:01
Thanks for the reply @milankonir - confirmed your code works in scriptlab as expected. I then stripped down my item change handler to do nothing but print 'item changed' to console, and that works. So there must be something else going in my other code. I'll keep digging, but the event does now seem to work as expected.

Cheers!
