### ISSUE TITLE
[Word-Semi-Annual Channel] Table row with content controls becomes gray after running context.document.getSelection().getOoxml()

### ISSUE THREAD

**Issue by remar27** [OfficeDev/office-js#1214] opened 2020-06-11 07:52 UTC
## Expected Behavior
Running context.document.getSelection().getOoxml() on table row with content control should not affect content.

## Current Behavior
Table row becomes gray, but actually is not the part of table row background. Color dissapears after closing & reopening the document .

## Steps to Reproduce, or Live Example
* Link to live example: [Script Lab](https://gist.github.com/remar27/133c045abc7a4e2a81fc8d1caa8f5af3)

1. Insert any table to content
2. Insert content control to whole table row (use Developer tab -> Rich Text Content Control)
3. Select whole row
4. Run the code from the example (context.document.getSelection().getOoxml())
5. Whole row becomes gray.

## Context
I'm trying to obtain table row data as OOXML and pass to server side for processing. But the content should be not affected.

## Your Environment
Office for Windows (desktop):
- Office 365 Pro Plus (Version 2002, Build 12527.20612)
- Office Professional Plus 2016 (Version 2002, Build 12527.20278)

OS:
- Windows 10 1909, Windows Server 2019, Windows Server 2012.

Issue is the same in all tested versions and environments.

## Useful logs
1. Create just a simple table
![1](https://user-images.githubusercontent.com/15183344/84358476-dea29b80-abcf-11ea-8aba-708be16ff598.png)

2. Select whole row and run the code selection.getOoxml()
![2](https://user-images.githubusercontent.com/15183344/84358488-e3674f80-abcf-11ea-8405-144bdbb0c86c.png)

3. The row becomes gray
![3](https://user-images.githubusercontent.com/15183344/84358496-e6624000-abcf-11ea-94c7-0be6698e318d.png)

4. But actually grayed row is not a part of a table - you can move table down or even delete it but gray row still there and will not dissapear unless you close & reopen the document.
![4](https://user-images.githubusercontent.com/15183344/84358507-e8c49a00-abcf-11ea-9eaa-aeeafd29c356.png)

**Comment by JuaneloJuanelo** [comment] 2020-06-15 19:50
I cannot repro this issue in the Monthly channel, however, this case apparently its been observed in the semi-annual channel. We'll keep investigating.

**Comment by JuaneloJuanelo** [comment] 2020-06-15 21:27
I was able to repro this issue in the semi annual channel. We are tracking internally with 4222326

**Comment by JuaneloJuanelo** [comment] 2020-07-23 16:25
The issue is fixed and will be released in the next semi-annual update. (to be released ~ Jan 2021)

**Closed as completed by JuaneloJuanelo** 2020-07-23 16:25 UTC
Labels: Type: product bug, Area: Word, Status: fix pending
