### ISSUE TITLE
API not supported on this platform when getting access token in MS Teams Word editor

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/office-js#3291] opened 2023-04-11 02:57 UTC
Wasn't sure if I should log this here or on a Teams github, but we have a Word add in that authenticates as the current user like so:

```
let options = { allowSignInPrompt: true, allowConsentPrompt: true, forMSGraphAccess: false } 
let bootstrapToken = await Office.auth.getAccessToken(options); return bootstrapToken; 
```

When we attempt to do this in using the Edit in Teams button available from the Teams files tab we get this error:

![image](https://user-images.githubusercontent.com/137350/231040682-432ed2d7-a08f-4ff9-a35e-073a92096e77.png)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/137350/231040585-0a62f46c-894f-4d0e-869a-3784755b66d7.png)

**Comment by JinghuiMS** [comment] 2023-04-11 10:04
Thanks for reaching us. Can I know which Word Add-in you are seeing this error? if you can provide a repro video, that will be helpful for us to better understand your scenario.

**Comment by catmanjan** [comment] 2023-04-11 10:17
It’s our own add in.

The reproduction steps are to create an add in that uses the function I
provided in the original ticket, then attempt to use the add in from the
Word online app embedded inside Teams.

**Comment by YijunMS** [comment] 2023-04-12 03:30
The cause may be that your add-in is not SSO (single sign-on) enabled. You could check this doc for more details: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs

**Comment by catmanjan** [comment] 2023-04-12 04:29
@YijunMS it is SSO enabled, it works in Word on the Desktop and Word Online, its only Word in Teams that has the issue.

**Comment by YijunMS** [comment] 2023-04-12 08:20
It seems that getting access token is not supported on Teams Word. Will this be a big blocking issue for your add-in?

**Comment by catmanjan** [comment] 2023-04-12 08:40
@YijunMS is that documented anywhere?

Yes we need access token for all app behaviour for authentication

**Comment by YijunMS** [comment] 2023-04-12 08:42
I read related code, but I haven't found documentation about it or the reason why it is not supported. I will update once I find more information.

**Comment by YijunMS** [comment] 2023-04-13 07:41
@catmanjan I haven't found any external documents about it so far. You could send a feature request to Teams team (I think some customers already did that) and they would arrange the development based on priorities and their resources.

**Comment by catmanjan** [comment] 2023-04-13 08:07
@YijunMS how would I go about doing that?

If there is no documentation or reason why it isn’t supported isn’t this a bug not a feature?

**Comment by YijunMS** [comment] 2023-04-13 08:38
For new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

**Comment by catmanjan** [comment] 2023-04-13 08:39
@YijunMS can you confirm is this a feature or a bug? It seems like a bug to me given it works in regular word online

**Comment by YijunMS** [comment] 2023-04-14 08:46
@catmanjan I am trying to find the owner of this API who can answer your question but it may need some time. I only have limited knowledge about the reason why it is not supported on this platform.

**Comment by mattgeim** [comment] 2023-04-19 22:40
Hi @catmanjan - this behavior is expected, as the getAccessToken API is not supported when running Word inside of Teams unfortunately.  For the current compatible hosts, you can reference the identity requirement set, found here:  https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/identity-api-requirement-sets 

For now, I don't have any information to share on possible support in the future, but we are always working on bringing support to additional scenarios so feel free to suggest the feature as mentioned above (or upvote it if you see it there already).

I've closed this issue, but please feel free to reopen it if you need additional help on this issue.

**Comment by VelinGeorgiev** [comment] 2023-07-06 12:12
How can this is not a bug. Users expect to open Word in Teams and get their add-in working similar to Word in browser or Word desktop application. 

@JinghuiMS  @mattgeim It is highly disappointing that this issue  got closed with no attention. 

More and more users are using Teams as their main tool and not having this in place there is discouraging me to suggest office add-ins as a solution at all.

Never the less the [official SSO documents](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins) should have a clear note that Word Teams is not supported. For the past month we solution an add-in based on the assumption from the [official SSO documents](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins) that it works until we have to find ourselves it does not. 

I am doubting myself if I should suggest an office add-in to my clients as a solutions architect anymore :)

**Comment by Rick-Kirkham** [comment] 2023-07-06 19:43
@catmanjan and @VelinGeorgiev As I understand it, your add-in's code can branch to a fallback login when it gets the 13012 error. This isn't as good an experience for the user as SSO, but it enables the add-in to function. Is my understanding correct?

**Comment by Rick-Kirkham** [comment] 2023-07-06 20:38
Didn't mean to reopen this.

**Closed as completed by Rick-Kirkham** 2023-07-06 20:38 UTC
Labels: Area: Word
