### ISSUE TITLE
Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again.

### ISSUE THREAD

**Issue by taralex77** [OfficeDev/office-js#3019] opened 2022-12-06 01:43 UTC
# Provide required information needed to triage your issue

Any call to office runtime crashes with the following exception:
_Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again._

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: **Office on the web**
* Host [Excel, Word, PowerPoint, etc.]: **Excel**
* Office version number: **16.0.15930.42301**
* Operating System: **MacOS**
* Browser (if using Office on the web): **Chrome, Safari**
 
## Expected behavior
This exception should only appear when the user is in cell editing mode when accessing the API.

## Current behavior
**The exception is thrown all the time even though the user is NOT in the cell editing mode. It happens consistently on any call to office runtime.**

## Steps to reproduce
Run the following code in any add-in loaded to Excel Online (even though it's supposed to wait for cell edit):

```
await Excel.run({ delayForCellEdit: true }, async (ctx) => {
      const ws = ctx.workbook.worksheets.getFirst().load(['id', 'name']);
      await ctx.sync();
      console.log('Worksheet info: ', ws.id, ws.name);
    });

```
## Context

No workaround exists. The crash renders our published Excel add-in unusable for all users.

**Comment by hkaizzer** [comment] 2022-12-06 09:26
The same issue. Operating System: Windows
yesterday all was fine

**Comment by zymon** [comment] 2022-12-06 11:33
The same for me, even when using some older version of the office-js lib.

**Comment by RuizhiSunMS** [comment] 2022-12-06 13:29
@zymon @taralex77  @hkaizzer Thanks for reporting.
Looks similar with #3021 , have replied in that issue, please update there to collect our information.

**Comment by RuizhiSunMS** [comment] 2022-12-07 08:32
@zymon and @taralex77 
the issue has been mitigated, could you help to double confirm from your side? If it still repro, please let us know. Thanks very much and apologize for the impact!

**Comment by taralex77** [comment] 2022-12-07 19:22
Confirming that we stopped seeing the issue as of yesterday. 
Thank you for the quick fix!

**Comment by RuizhiSunMS** [comment] 2022-12-08 14:01
Close the issue since the customer has confirmed the fix.
Feel free to reopen it if it happens again.

**Closed as completed by RuizhiSunMS** 2022-12-08 14:01 UTC
Labels: Area: Excel, Type: product bug, Status: fixed
