### ISSUE TITLE
Outlook add-in fails when starting in OWA with multiple selected emails

### ISSUE THREAD

**Issue by VasilyIvanov** [OfficeDev/office-js#3800] opened 2023-11-01 04:48 UTC
We are developing an Outlook add-in that should be able to work with multiple selected emails as documented [here](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select).
While testing in Outlook Web Application (OWA) we noticed a problem that appears when we select multiple emails and start the add-in. If we select only one email and start the add-in, everything goes as expected even if we select multiple items **after** starting the add-in.

The error text is '_Elevated permission is required to call the method: 'getSelectedItemsAsync._'.

To facilitate the issue reproduction, we have created [another](https://github.com/VasilyIvanov/TestAddIn) simple add-in exactly as described in the manual above and made a short  [video](https://oneplacemail-my.sharepoint.com/:v:/g/personal/vasily_ivanov_oneplacesolutions_com/EYfG0ZGlWElBspP8Yo_w9bYBvIxeuCms-i3TJzYHBDWGmQ) that demonstrates the problem.

Please help us either resolve the issue if it is possible, or fix it if it is an Office JS bug.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **Office on the web**
* Host [Excel, Word, PowerPoint, etc.]: **Outlook**
* Office version number: **latest**
* Operating System: **Windows 11**
* Browser (if using Office on the web): **Chrome 119, Edge 118**
 
## Expected behavior
There should be no error in the console when we start the add-in from multiple selected emails, and also the `Office.context.mailbox.getSelectedItemsAsync()` method should work properly and return multiple emails.

## Current behavior
If we select multiple emails on Outlook Web and start the add-in, we get an error.
When started, the add-in subscribes to the `Office.EventType.SelectedItemsChanged` event.
After that the user can click 'Run' to get the list of selected emails. To do this, we call `Office.context.mailbox.getSelectedItemsAsync()`.
The error text is 'Elevated permission is required to call the method: 'getSelectedItemsAsync.'.

## Steps to reproduce

1. Clone the [repo](https://github.com/VasilyIvanov/TestAddIn).
2. Install the manifest '_manifest.xml_' from the project root.
3. Start the project by `npm run dev-server`.
4. In Outlook Web select multiple emails.
5. Start the add-in and click the 'Run' link on it.

## Link to live example(s)

1. [Reproduction repo](https://github.com/VasilyIvanov/TestAddIn)

# Provide additional details

1. [Video with the testing process](https://oneplacemail-my.sharepoint.com/:v:/g/personal/vasily_ivanov_oneplacesolutions_com/EYfG0ZGlWElBspP8Yo_w9bYBvIxeuCms-i3TJzYHBDWGmQ)
2. In the past we tried to add the following code prior to calling `Office.context.mailbox.getSelectedItemsAsync()`:
`(Office.context.mailbox as any).initialData = { permissionLevel: 3 };`
and this helped to fix the issue. If we do it now, the error text will change to: '_An internal error has occurred._'.
![image](https://github.com/OfficeDev/office-js/assets/59409548/fff5b2be-753e-4d34-8e85-c01a6747a23a)
We are pretty sure we should **not** add that code at all but we find it could be useful to mention it here.

## Context

We would like to develop an add-in that will be able to support multiple selected emails.

## Useful logs

- [ ] Console errors
![image](https://github.com/OfficeDev/office-js/assets/59409548/7b0c3559-9a4b-47fc-8ff8-bd41bea00bac)
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for looking into th issue.

**Comment by ottD** [comment] 2023-11-05 23:34
We are having exactly the same issue with the 'Elevated permission is required to call the method: 'getSelectedItemsAsync.' error being thrown when activating an Outlook add-in with multiple messages selected. 
It's worth pointing out that this error only occurs the first time when activating the add-in with more than one message selected. Activating the add-in with a single message and then selecting multiple messages works as expected and `Office.context.mailbox.getSelectedItemsAsync()` returns all selected messages. 
Activating an add-in when multiple messages are selected seems like a pretty basic use case for [supporting item multi-select]( https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select).

**Comment by exextoc** [comment] 2023-11-14 08:56
Thanks for reporting this issue regarding multiselect API. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking Id: 242067

**Comment by elegault** [comment] 2023-12-12 20:03
> We are having exactly the same issue with the 'Elevated permission is required to call the method: 'getSelectedItemsAsync.' error being thrown when activating an Outlook add-in with multiple messages selected. It's worth pointing out that this error only occurs the first time when activating the add-in with more than one message selected. Activating the add-in with a single message and then selecting multiple messages works as expected and `Office.context.mailbox.getSelectedItemsAsync()` returns all selected messages. Activating an add-in when multiple messages are selected seems like a pretty basic use case for [supporting item multi-select](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select).

I'm seeing a different result in 1.2023.1207.400: if I load the task pane with one item selected, then select another item, the Reading Pane is replaced with this UI:

![image](https://github.com/OfficeDev/office-js/assets/4130365/201d2078-05cd-4cf8-8ffb-6bdcc2de2c12)

And this error is thrown when calling Office.context.mailbox.getSelectedItemsAsync():

![image](https://github.com/OfficeDev/office-js/assets/4130365/f5340119-abca-4fbd-92be-d8f943f81323)

**Comment by CameronDwyer** [comment] 2023-12-15 04:52
Has this been fixed - although this issue has been open much longer it looks like a duplicate issue was reported 2 days ago here #https://github.com/OfficeDev/office-js/issues/3914 where a comment from Microsoft indicates a fix has been made and should be rolling out within a week?

**Comment by exextoc** [comment] 2023-12-15 06:01
@CameronDwyer Yes, the issue has been fixed. The fix is being rolled out and should be 100% by end of week.

**Closed as completed** 2023-12-25 09:10 UTC
Labels: Area: Outlook, Needs: author feedback, Status: fixed

**Comment by kirtisuri** [comment] 2024-03-05 17:43
This issue is happening when we are using other regular user except for Global admin and Outlook on web. For Global admin it works fine. In the manifest have the permission set as ReadWriteMailbox.

For regular user. When selecting multiple emails the event handler that we use to get the selected items does not consistently return the selected email items. The Outlook getSelectedItemsAsync throws "Internal error has occured". The error does not have any specific error codes.
Is it that the manifest I am using does not have the fixes that were done by Microsoft recently? How to make sure I am using the later version of Office.js In my html page I have

<script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/Office.js" type="application/javascript"></script>
Here is the screenshot of the error:

![error](https://github.com/OfficeDev/office-js/assets/157402030/2315643b-cf23-4d14-b0e8-f19fb92eec15)


Is there any specific permission that is needed. For regular users? I tried to check the Office.context.mailbox.initialData and the permission level is set as 3 for this user.

**Comment by mrebuffet** [comment] 2024-03-06 05:11
I can confirm that this issue is happening again in some of our environments (OWA here) where it was previously working. 
<img alt="image" src="https://github.com/OfficeDev/office-js/assets/3445077/00edce5d-356d-4041-b1ac-12cf3b70b807">

Same user on Outlook for Windows has no issue. 
![image](https://github.com/OfficeDev/office-js/assets/3445077/1685ce12-d58e-4d38-9cac-634b56a6b4e0)
![image](https://github.com/OfficeDev/office-js/assets/3445077/b9e60561-5a84-4f97-9d0b-44559e76c368)

Different user on OWA on another Edge profile on the same machine has no issue either so it is very intermittent at this stage.

**Comment by kirtisuri** [comment] 2024-03-06 18:16
For Outlook New Desktop does not seem to work either. Works for Old Outlook Desktop.
