### ISSUE TITLE
Outlook Online: item.body.getAsync() method works strange

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#2316] opened 2021-12-20 11:30 UTC
In an Outlook add-in for compose mode, we use the Office.context.mailbox.item.body.getAsync() method to get the entire email body in the HTML format. The method returns just part of the email body when you are replying to an existing email.

## Your Environment
* Platform: Office on the web
* Host: Outlook
* Office version number: 
* Operating System: Windows 10, Mac OS
* Browser (if using Office on the web): Edge, Chrome, Safari
 
## Expected behavior
The Office.context.mailbox.item.body.getAsync() method shall return the entire body.

## Current behavior
The Office.context.mailbox.item.body.getAsync() method returns only a part of the email body.

## Steps to reproduce
1. Sign in to Outlook Online by using for example the Chrome browser.
2. Make sure the Settings -> View all Outlook settings -> Layout -> "How do you want your messages to be organized" option is set to "Show email as individual messages".
3. Select an existing email in your Inbox, click the Reply All button.
4. Execute the following code:
`      var output = document.getElementById("output");`
`      if (output) { output.value = ''; }`
`      Office.context.mailbox.item.body.getAsync('html', function (result) {`
`        console.log('Body', JSON.stringify(result));`
`        if (output) {`
`          output.value += 'Body:' + '\r\n' + JSON.stringify(result) + '\r\n';`
`        }`
`      });`

5. As you can see, the getAsync() method returns a small part of the HTML, not the entire body.
6. Type some text in the body but *don't move* the keyboard cursor, execute the code above again - the same issue occurs.
7. Now, move the keyboard cursor down (if you have a signature, place the cursor underneath it) and execute the code again - now the getAsyncMethod() method starts working correctly.

## Link to live example(s)
1. You can use the following test add-in, click the item.body.getAsync() button:
https://online-addins.ablebits.com/testaddin/manifest.xml

**Comment by exextoc** [comment] 2021-12-22 06:55
Issue looks duplicate of https://github.com/OfficeDev/office-js/issues/2317

**Closed as completed by exextoc** 2021-12-22 06:55 UTC
Labels: Area: Outlook, Type: programming question

**Comment by DmitryKostochko** [comment] 2021-12-22 08:16
@exextoc, there is a difference between this #2316 and #2317 reports:
2316: "Show email as individual messages" option is set. The getAsync() method starts working after manipulations with the cursor.
2317: "Show email grouped by conversation" option is set. getAsync() never returns the whole body.

I tried to describe both issues in a single report but it turned out to be too complicated and confusing.

**Comment by exextoc** [comment] 2021-12-22 08:38
@DmitryKostochko Thanks for clarifying. We have noted now.
But my observation was the api returns the whole body when we move the cursor down irrespective of the Setting.

**Comment by DmitryKostochko** [comment] 2021-12-22 11:44
@exextoc, thank you for getting back to the issue!
I have never been able to get the **whole** body when reply to an existing email with the "Show email grouped by conversation" option selected. In this case, getAsync() always returns only the text that I typed.

**Comment by neville-jones** [comment] 2022-03-24 05:18
Seeing similar as exextoc - the API only returns the complete body when the cursor is moved down in to the reply content, irrespective of the Setting. If is "Show email grouped by conversation" then first have to click three ellipsis under reply to show original message content, then move cursor down in to it.

**Comment by monika8093** [comment] 2025-01-31 07:59
Hi Team,

I am working on web add-in for Outlook,and I want to implement a feature where, when I reply to an email the conversation history of that email need to be removed. I tried doing this using **item.body.getAsync** and **item.body.setAsync** , but it is not working because when I click on send, the conversation history gets appended automatically. I also tried using the graph api **updateAsync**, but it is not removing the conversation history either.Can you please help.
