### ISSUE TITLE
Word Addin is getting crashed when trying to delete a row which contains a content control in a table

### ISSUE THREAD

**Issue by SudheerK06** [OfficeDev/office-js#1056] opened 2020-03-23 15:20 UTC
I'm developing a Word Add-in (Word API + Office.js) where i am working with content controls, I am trying to read the table content inside a content control where I need remove the empty rows

Sample: I have this table inside a content control I have to remove the blank rows 

![yTR12](https://user-images.githubusercontent.com/62557572/77332404-0ceaaa80-6d48-11ea-93c7-2a4f1e39bfc6.png)

i am able to delete the blank row in this case.

but if the table contains a content control which is blank then when i try to delete that row the addin itself is getting crashed.

![Capture](https://user-images.githubusercontent.com/62557572/77332202-bf6e3d80-6d47-11ea-84b2-b592a79b0a39.PNG)

`
              function checktable(element) {
                         Word.run(function (context) {
                                // Queue a command to get the current selection and then
                               // create a proxy range object with the results.
                                 var contentControl = context.document.contentControls.getByTag('control1').getFirst();

                     var table = contentControl.tables.getFirst();

                    context.load(contentControl, 'tables');

            table.load('values');

            return context.sync()
                .then(function () {
                    // Get the longest word from the selection.
                    if (contentControl.tables.items.length === 0) {
                        document.getElementById('lblstatus').innerText += "No Tables found";
                    }
                    else {

                        document.getElementById('lblstatus').innerText += " Tables found";
                        var Tablevaules = table.values;

                        for (var i = 0, len = Tablevaules.length; i < len; i++)
                        {
                            var nullcheck = "";
                            var inner=Tablevaules[i];

                             // inner loop applies to sub-arrays
                            for (var j = 0, len2 = inner.length; j < len2; j++) {
                                // accesses each element of each sub-array in turn
                                if (inner[j] == "") {
                                    if (nullcheck != "False") {
                                        nullcheck = "True";
                                    }
                                }
                                else {
                                    nullcheck = "False";

                                }
                            }

                            if (nullcheck == "True") {
                                table.deleteRows(i);
                            }
                        }
                    }

                })
                .then(context.sync)
                .then(function () {

                    // Queue a command to highlight the search results.
                    document.getElementById('lblstatus').innerText += element + ":" + "Successs";

                });
        })
            .catch(errorHandler);
    }

**Comment by SudheerK06** [comment] 2020-03-30 04:33
someone please look into this issue

**Comment by weshi** [comment] 2020-04-02 07:24
@commoncoder101 Is this issue for Word Desktop, or Word Online?

**Comment by SudheerK06** [comment] 2020-04-02 10:22
@weshi word desktop

**Comment by weshi** [comment] 2020-04-10 01:03
I was not able to reproduce this issue with my version of Word for Windows. 
![image](https://user-images.githubusercontent.com/11494417/78953012-0b6fff00-7b0a-11ea-94d7-5df6cd1ec870.png)

It would be helpful if you could provide the version/build information. If you can provide the document you tested with the issue, it would also be helpful.  Thanks.

**Comment by weshi** [comment] 2020-04-10 01:20
@commoncoder101  It seems this can only be reproduced if you delete the rows with table.deleteRows() API. I can reproduce it now. I'll create an issue internally to track this issue.

At the same time, if you first get the rows, and then call the row.delete() API, it will succeed. Could you try this approach to see if you work around it for now while we investigate the table.deleteRows API?

**Comment by weshi** [comment] 2020-04-10 01:49
Tracked internally with 4085106.

**Comment by hjkim-MSFT** [comment] 2020-04-24 20:03
Microsoft identified this issue. It should be fixed in 16.0.12823.10000 or higher builds.

**Comment by JuaneloJuanelo** [comment] 2020-05-05 19:54
@commoncoder101  the issue is now fixed and is available in the latest insiders fast release.
Can you please help us validate the fix?

**Closed as completed** 2020-05-12 23:00 UTC
Labels: Type: product bug, Needs: author feedback, Area: Word, Status: fixed
