### ISSUE TITLE
TypeError: Object doesn't support property or method 'getItem'

### ISSUE THREAD

**Issue by brandonfake69** [OfficeDev/office-js#3488] opened 2023-07-06 17:34 UTC

**Comment by andycircle** [comment] 2023-07-07 17:07
This is happening to folks in our company as well. The add-in works fine in office.com/excel but not in the Excel Desktop App.
The issue started with recent excel updates. 
Please let us know there is a fix coming.

**Comment by Biktop** [comment] 2023-07-11 01:15
I can confirm that we also came across with this bug in custom functions (without shared runtime) in the latest versions of Excel for windows.

**Comment by ark81ro** [comment] 2023-07-11 11:03
I have the same problem using Excel with the CryptoSheets add-in, both on PC and Phone

=CS.PRICE("BTC","USD")     or   =CS_EXRATE("GBP","USD","1")    returns the same error

Using an Excel file both locally and uploaded on OneDrive .
OfficeProffesional 2021 x64 on my PC

**Comment by ZYUN-MSFT** [comment] 2023-07-12 08:06
Hi @brandonfake69 ,

We have confirmed that this issue has been fixed and wait for deploy.\
We will back here and update this thread once the fixed has been deployed to prodction.

Thanks.

**Comment by BroaderOrb** [comment] 2023-07-12 09:52
How do I download the fix - or will happen automatically in Office 365?

**Comment by ZYUN-MSFT** [comment] 2023-07-13 07:14
Hi @brandonfake69 ,

The fix will reach production nearly the end of July (or early of August).\
Once the fix is deployed, you need to update the Office to the specific version to get that fix.\
(We will update the related version information here)

Thanks.

**Comment by BroaderOrb** [comment] 2023-07-17 11:37
This doesn’t need feedback from the contributor - it should be left open until the fix has been deployed and tested.

**Comment by ark81ro** [comment] 2023-07-27 00:01
I can confirm that after updating Office today the issue is gone and everything seems to work as it should. Thank you for fixing it!

**Comment by BroaderOrb** [comment] 2023-07-27 12:27
I just updated Office 365 and I'm still getting the same problem.  UK based - not sure if this is a rollout issue?

@Bogdan-Alex - what version have you updated?

**Comment by Biktop** [comment] 2023-07-27 23:04
@BroaderOrb I can confirm that it works in Excel version 2307

**Comment by ark81ro** [comment] 2023-07-27 23:52
@BroaderOrb This is the version I have after the update: Microsoft® Excel® 2021 MSO (Version 2307 Build 16.0.16626.20086) 64-bit 

Office Pro 2021 x64

**Comment by ZYUN-MSFT** [comment] 2023-07-28 06:07
Hi all, the fix is deployed, please update the office version to 16.0.16626.20132 (production) above to confirm.

Thanks.

**Closed as completed** 2024-06-11 03:16 UTC
Labels: Area: Excel, Type: product bug, Status: fixed
