### ISSUE TITLE
Adding event handler for dialog messages fails in Outlook for Mac

### ISSUE THREAD

**Issue by richnew10** [OfficeDev/office-js#349] opened 2019-01-03 03:26 UTC
## Expected Behavior

STR:

1. Add-in page opens a dialog and registers a handler.

```typescript
window.Office.context.ui.displayDialogAsync(uri, options, (result: Office.AsyncResult) => {
  const dialog = result.value;
  dialog.addEventHandler(Office.EventType.DialogEventReceived, (ev: any) => {
    onClose();   // Simple function defined elsewhere.
  });

  dialog.addEventHandler(Office.EventType.DialogMessageReceived, (m: string) => {
    handleMessage(dialog, m);   // Simple function defined elsewhere.
  });
});
```

2. Dialog page sends back.

```typescript
window.Office.context.ui.messageParent("{'action': 'foo'}");
```

Expected: `handleMessage` is called.

Actual: `handleMessage` is not called. Using Vorlon I find that Outlook logs `"messages received cannot be handlered"` when adding the event handler.

`onClose` is successfully called, so events are being delivered to the add-in.

This seems exactly like:

* https://stackoverflow.com/questions/45837934/outlook-add-in-does-not-return-message-from-dialog-on-macos

and similar to:

* https://camerondwyer.com/2017/03/01/beware-the-dialog-api-falling-silent-under-ie11/

## Context

This makes it impossible to send responses from a dialog, limiting us to only those things that can be accomplished after closing the dialog.

## Your Environment

Outlook 16.16.5, Mac 10.13.6.

**Comment by kbrandl** [comment] 2019-01-03 19:35
@richnew10 thanks for reporting this and sorry to hear that you've run into this problem. @exextoc can you please look into this?

**Comment by macOutlookExtensibility** [comment] 2019-01-04 08:21
Thanks for raising it. Please provide the code for us to help in debugging.

**Comment by richnew10** [comment] 2019-01-04 16:45
> Please provide the code for us to help in debugging.

I'd love to, but I'm encountering this in a closed-source product.

Are you able to reproduce with the snippets I provided above?

From my research, this looks like a failure to parse the message envelope that's constructed [here](https://github.com/OfficeDev/office-js/blob/b18900e1d90a4e3bb7ab4baad5f0c493e9d9aae9/dist/outlook-mac-16.00.debug.js#L4601) and parsed [here](https://github.com/OfficeDev/office-js/blob/b18900e1d90a4e3bb7ab4baad5f0c493e9d9aae9/dist/outlook-mac-16.00.debug.js#L4553), or to invoke the handler a few lines below. As far as I can tell none of my code related to message handling gets to run, and my payload is a small string representation of valid JSON, which should be fine.

**Comment by jargil** [comment] 2019-04-03 01:44
@richnew10 - I just tried with a very similar script to yours and it worked just fine:

Office.context.ui.displayDialogAsync(someUrl, {height:40,width:40}, function(result){
  const dialog = result.value;
  if(result.status == Office.AsyncResultStatus.Failed) {console.log('error');}
  dialog.addEventHandler(Office.EventType.DialogMessageReceived, function(m){
    console.log('message received');
    console.log(m);
  });
});

And then from the dialog used pretty much your snippet. Granted I'm using a newer version of Outlook and also a newer macOS version 10.14, but we haven't made any recent changes around this code that would make it fail in the build versions that you're using.

Is there any way you can help identify more details to help us debug? Perhaps can you try building a small example where you can consistenly reproduce this problem and share it with us?

**Comment by richnew10** [comment] 2019-04-04 21:05
I suspect that a newer Outlook and a newer WebKit, plus 3 months, could make a difference. I will attempt another repro next time I cycle around to this area of the code.

**Comment by djpereira** [comment] 2019-04-16 22:17
I'm on macOS 10.14.4 and Outlook 16.24, and I can reproduce this issue.
Everything works well on Safari, FireFox, Edge, IE11 and outlook for Windows, but outlook for mac is not triggering `DialogMessageReceived` when we call `Office.context.ui.messageParent` at least for our app.

If we do very simple app, it works well, but not with our app.

From the dialog I see `Office.onReady` and the global `Office.context.ui.messageParent` object is there, the data is just not going thru.

**Comment by djpereira** [comment] 2019-04-23 19:36
In our case, we discovered that only for Outlook on macOS, both the function file and the dialog need to be exactly in the same domain, including any subdomains (and even in the same port).

**Comment by richnew10** [comment] 2019-04-24 01:51
When I reported that was indeed the case — the only difference between the main page (not a function file) and the dialog was the path changing from `/outlook/` to `/outlook/signin`.

**Comment by pdesai-mimecast** [comment] 2019-08-12 08:37
Can confirm that this is still an issue with Mac Outlook 16.16.12. As @djpereira mentions, it appears to be a domain issue. The problem doesn't exist for Web or Windows.

> Unable to post message to https://aaa.com. Recipient has origin https://bbb.com.

Both aaa.com and bbb.com are <AppDomain> in the manifest.

**Comment by m-pd** [comment] 2019-08-13 07:51
This is still an issue with Outlook for Mac version 16.16.12. It's a serious blocker. Any road map to fix this?

**Comment by ChayaChechik** [comment] 2019-10-29 10:51
Having the same issue with outlook on the web. This is a major issue - any updates re fixing this?

**Comment by m-pd** [comment] 2019-10-30 10:41
I resolved this issue by redirecting the task pane to be in the same domain as the dialog.

**Comment by ChayaChechik** [comment] 2019-10-30 10:54
The issue I'm having persists, even thought I have the taskpane and dialog page on the same domain. The only way it works is with an iframe. However, for most cases I would need a proper page not an iFrame. 
https://stackoverflow.com/questions/58606436/outlook-add-in-dialog-api-eventhandler-not-firing/58607606#58607606

**Comment by macOutlookExtensibility** [comment] 2019-11-04 03:35
@m-pd , are you unblocked on Mac?

**Comment by abimaelmartell** [comment] 2020-05-16 03:13
I'm having this same issue on Excel, is there a fix for this yet?

**Comment by abdidaudpropel** [comment] 2020-07-03 02:55
I am facing the same issue on Mac 10.15.5 and Excel 16.38. 
The same code works in Excel Online and Excel windows.

Office.context.ui.messageParent does nothing and displayDialogAsync's callback is not triggered. Additionally, only on mac  Office.context.ui.closeContainer through undefined error (called by the dialog after office is initialized)

**Comment by Hamdan85** [comment] 2021-02-16 20:36
Cmon guys, how this is closed? It's not working yet.

**Comment by abimaelmartell** [comment] 2021-02-16 20:41
It seems like `displayDialogAsync` mutates the options object, so in order to get this working you need to send a new object every time.

```ts
const options = { height: 100, width: 100 };

// this will result on event handler not triggering
Office.context.ui.displayDialogAsync(url, options, cb);

// this works
Office.context.ui.displayDialogAsync(url, { ...options }, cb);
```
Seems like an issue on the library, but this seems to work ok.

**Comment by Hamdan85** [comment] 2021-02-17 13:40
I just do it once, and it opens the window in mac but not in windows.

But in mac, it doesn't receive events back (call back triggers this message: "messages received cannot be handlered")

It seems that there are also an error in edge which prevents us from knowing the opener window. Do you know anything about that?

using this:

Office.context.ui.messageParent(JSON.stringify({ authenticationCode }));

only triggers this in the parentWindow: 

messages received cannot be handlered. Message:{"dialogMessage":{"messageType":0,"messageContent":"{\"authenticationCode\":\"uHeTqFx6pKHxAUSZcsoipNdp2t0cvbyIjLid_o6w5e0\"}"}}

PS: in windows, as before, displayDialogAsync simply doesn't open anything

**Comment by exextoc** [comment] 2021-02-24 05:27
@abdidaudpropel Is this issue happening in Outlook Mac new UI or old UI?
@Hamdan85 Do you mean you are seeing issue in Outlook windows client also? Can you share the Outlook client version?
Have you tried the workaround suggested by @abimaelmartell ?

**Comment by Hamdan85** [comment] 2021-02-24 15:43
I discovered the issue here. 
THe problem is that the documentation doesn't says anything about the URL argument necessarily need to be absolute and outlook on mac behaving differently. 

On mac it opens the dialog but the parent cant receive messages back. 
On windows, it just don't do anything. 

Changing it to absolute URL fixed my issues. 
Just add this to the documentation.

**Comment by masha-mariya4** [comment] 2021-08-16 10:18
issue is still reproduced for mac!

**Comment by exextoc** [comment] 2021-08-18 15:33
Hey @masha-mariya4 ,

The document has been updated to read that the dialog URL provided must be an absolute URL with the hostname and protocol present. Are you seeing an issue despite providing the absolute URL for the dialog?

**Comment by masha-mariya4** [comment] 2021-08-18 17:08
Hey again @exextoc !) I uses absolute URL for it. Maybe the reason that I run the add-in on my local web server (localhost) and dialog URL has different domain? Although I added it in <AppDomain> list

**Comment by exextoc** [comment] 2021-08-20 10:59
Hey @masha-mariya4 ,

The fact that you're on localhost should not be an issue if you have added the dialog URL domain to the AppDomains. Can you reproduce this only on Mac (on both old and new UI?), or is it the same for you on OWA too?

**Comment by masha-mariya4** [comment] 2021-08-20 11:03
unfortunetely I don't have an opportunity to test it on OWA now, but the research in github issues tells me that it's only mac issue)

**Comment by exextoc** [comment] 2021-08-24 06:37
@masha-mariya4 Could you please provide us sample code along with the manifest or an add-in endpoint so that we can reproduce it in house?

**Comment by chadhobson** [comment] 2021-08-26 16:59
@exextoc There's several examples above so please stop asking for them and just fix the problem. You can follow your very own tutorial (https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator) and get the exact same result that everyone here has gotten.

Regardless, I will also chime in and confirm it does NOT work on Mac. Works fine on Windows, though.

So, please drop the stalling and get to fixing your broken software. This issue is over 2.5 years old and STILL persists.

**Comment by jargil** [comment] 2021-08-27 19:28
Hey all. I'm sorry to hear you're having problems with the Dialog API on Mac. I've tried reproducing this in multiple ways and I'm not seeing any problems with the API, so getting your samples is very useful for us in order to understand if there's a particular use case where things are breaking for the Mac platform. We really appreciate your input and help here!

Anyway, I created a very simple Script Lab gist that uses the Dialog API, it shows two buttons, one that pops the Dialog and one that calls messageParent to log a message in the Task Pane, could you try to see if things work for you?
Gist: https://gist.github.com/jargil/5cefdc755f804be003ad2e119dcf8afc

Once you install and import the gist into Script Lab Code, you should then open the Run pane and you'll see something like this:
![image](https://user-images.githubusercontent.com/10125816/131178570-4dd4c9e8-06ac-42a1-9863-3c3cb3c577c0.png)

1. If you click "Display Dialog"  the dialog should show, there will be a Type Error reported about an undefined object in the Dialog, please ignore that.
2. Now if you click "Call Parent" in the dialog, you should see the log appears in the original Task Pane, like this:
![image](https://user-images.githubusercontent.com/10125816/131178710-b7f715ef-5e56-4ff6-9b90-b9183bfcbac9.png)

If you see the log it means everything worked as expected. If you can see this working, but your own sample still doesn't work, then please share your sample so that we can try to understand what's going on.

Thank you!

Link to Script Lab for Outlook: https://appsource.microsoft.com/en-us/product/office/WA200001603
Script Lab docs: https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab

**Comment by exextoc** [comment] 2021-08-30 10:44
Hello @masha-mariya4 , @chadhobson 

We regret the inconvenience caused. 
We are still not able to reproduce it from our end.
And if it is not reproducible for us, we can't fix it.

Please help us understand the situation better
- Does it happen on New Mac UI or Old Mac UI? Is the repro consistent ?
- Does the same Snippet for work on other platforms and fail for Mac?
- Have you tried the above Script Lab snippet? Does it also fail?
- Can you help us with a repro video, if possible around the issue?
- Can you help us with a sample manifest, which can highlight the issue?

We are looking into this bug on priority, please help us with the above information. 

Thanks

**Closed as completed** 2021-09-07 20:00 UTC
Labels: Area: Outlook, Type: product bug, Needs: author feedback, Status: under investigation, Area: add-ins platform, Status: no recent activity
