### ISSUE TITLE
Unable to get Token using MSAL

### ISSUE THREAD

**Issue by sandeep007bonds** [OfficeDev/office-js#1811] opened 2021-04-17 20:26 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am unable to get access token using 
**"await OfficeRuntime.auth.getAccessToken({ allowSignInPrompt: true, allowConsentPrompt: true })"** getting below mentioned error if I am using online excel hosted in sharepoint.com domain but working fine with online excel with OneDrive domain.

Error message : 
Unsafe attempt to initiate navigation for frame with origin authorize:85 
Unsafe attempt to initiate navigation for frame with origin 'https://nestedquery-my.sharepoint.com' from frame with URL 'https://login.microsoftonline.com/519c93c3-f079-4575-80e3-15e3f2fb278e/oauth2/v2.0/authorize?. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/sso-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by sandeep007bonds** [comment] 2021-04-21 08:41
Thanks @ElizabethSamuel-MSFT waiting for the response from the office-js so the product team.

**Comment by sandeep007bonds** [comment] 2021-05-03 12:26
@JefWight Any update?

**Comment by randeepchaudhary** [comment] 2021-05-05 17:05
Hi, did you get the cause for this behavior?

**Comment by codexeon** [comment] 2021-05-08 00:07
You are getting this error because our SSO developer scenario for Office Online was built for admin deployment scenario. For Office Online only, it requires you to have an admin account for the tenant to test your SSO add-in, or an admin to have previously deployed an SSO enabled add-in on the same tenant you are testing with. With an administrator account, you can go to https://portal.office.com/adminportal/home?#/Settings/AddIns to deploy the SSO add-in and then the add-in should be able to call getAccessToken API. After the initial deployment for the tenant, you should be able to use the upload manifest option from dialog for future iterations. If you don't have an administrator account, Office for Windows and Mac do not have the pre-requisite. We understand this is inconvenient for Office Online to test the add-in, and it will be available without this requirement in the future.

**Comment by justin0522** [comment] 2021-11-19 11:47
Duplicate of #3601

**Closed as not planned** 2024-03-25 20:12 UTC
Labels: Area: add-ins platform
