### ISSUE TITLE
[Outlook] Office.context.ui.displayDialogAsync sometimes open dialog and sometimes opens browser tab

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#1797] opened 2021-04-14 19:16 UTC
When calling ```Office.context.ui.displayDialogAsync``` with all of the same parameters on desktop or mobile, it sometimes opens a dialog and sometimes opens a new tab in the default browser. This appears to depend on which account I have setup and I am unable to determine what in that account would cause this difference in functionality.

## Expected Behavior
```Office.context.ui.displayDialogAsync``` should always act in a consistent fashion no matter what account is used. We believe this is related to accounts as it was tested on the same desktop computer (Mac OSX with Outlook 2016 app) and same iPhone (iOS with Outlook app) by just logging into the different accounts (while always only having 1 account setup at a time).

## Current Behavior
See description above.

## Steps to Reproduce, or Live Example
We are unable to determine what exactly causes this issue to occur, but it appears to be related to the type of account or some settings within an account possibly.

## Context
We are hoping to understand what could lead to the ```Office.context.ui.displayDialogAsync``` resulting in using a new browser tab vs opening a dialog window. 

## Your Environment

* Mac OSX + Outlook 2016 (App)
* iOS Outlook (App)
* Android Outlook (App)
* Unsure about Windows 10 + Outlook 2016 (App) at this time. I will test and add results asap.

**Comment by exextoc** [comment] 2021-04-14 22:27
To clarify, are you running Outlook online running in a browser in Mac?  What about iOS/Android - are you running Outlook online in the browser or are you using Outlook app on mobile?  Do you see this in Windows (either the Outlook app or Outlook in browser)?

**Comment by cody-lettau** [comment] 2021-04-14 23:59
@exextoc thanks for following up. This was seen on the following:
- Mac Desktop: Outlook 2016 app
- iOS: Outlook App
- Android: Outlook App

I will test on Windows tomorrow when I have an opportunity.

We do not see this issue when in the browser, but that is likely because our add-in specifically checks the platform to determine if it should just open a new tab or use the ```Office.context.ui.displayDialogAsync``` functionality for this specific feature.

**Comment by cody-lettau** [comment] 2021-04-15 21:48
We are seeing this with a fair amount of test accounts. Without knowing what causes this, it is quite the blocker as it leads to users not being authenticated correctly (opening the link in their default browser instead of the dialog leads to cookies and localStorage data not being available).

**Comment by cody-lettau** [comment] 2021-04-16 15:01
@exextoc @lindalu-MSFT I created a recording of what we are seeing. This was tested on OSX Desktop App on the same computer (no change in environment as you will see). View here: https://screencast-o-matic.com/watch/crfD2RVnHwV

The same exact line is called ```Office.context.ui.displayDialogAsync(...)``` with a near identical url (just different query values. Yet, for one account, it opens the default browser instead of opening a dialog. This browser window then doesn't have access to a cookie set within the add-in and our authenticate fails.

**Comment by exextoc** [comment] 2021-04-19 15:51
@cody-lettau  Could you please provide a test account with which we can repro this issue on our side?
You can share the test account details to admin@M365x010952.onmicrosoft.com.

**Comment by cody-lettau** [comment] 2021-04-20 12:52
@exextoc I sent one over yesterday.

During further testing, we were also seeing the same call to ```Office.context.ui.displayDialogAsync``` sometimes return an error saying the url was not in the defined domain list, even when it was (and worked fine with the same url, just different query values, at other times).

**Comment by cody-lettau** [comment] 2021-04-20 17:46
@exextoc as we continue to try to figure out a solution for this, we are seeing the issue intermittently now. At times, it is opening in the dialog and at other times, opening in the default browser. There has been no change the URL we are attempting to open. The thing that may be changing is the set of cookies that the add-in has set.

**Comment by exextoc** [comment] 2021-04-21 09:48
@cody-lettau Thanks for sharing Account details but we did not get a repro with the Test Account. Could you please clarify the following?

1. When Office.context.ui.displayDialogAsync opens browser instead of dialog, do you see any errors in the callback?
2. Is the URL being opened mentioned in the AppDomains element or under the resources/urls section of manifest?. If not, please add the URL domain to AppDomain section and check if the issue repros.
Documentaion on AppDomain can be found [here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/manifests#app-domains).

**Comment by cody-lettau** [comment] 2021-04-21 12:49
@exextoc thanks for taking a look. In our testing yesterday, we actually couldn't reproduce the issue either. Yet, nothing in terms of how we are calling ```Office.context.ui.displayDialogAsync``` has changed and the URL has not changed.

That said, I did not check the callback for errors while we were seeing it. I will continue to keep an eye out for this issue and will take note of any errors when it instead opens the default browser.

The domain of the url we are attempting to open is part of the manifest in the AppDomains element. Now the url does result in a redirect for authentication purposes, but I don't believe that is the issue as it had worked fine for some accounts.

If you wish to close this for now, I'm okay with that. I can re-open the issue if we can reliably reproduce it.

**Comment by exextoc** [comment] 2021-05-05 09:05
Since we are no longer able to reproduce this issue I will close this for now. Feel free to reopen once you have a repro.

**Closed as completed by exextoc** 2021-05-05 09:05 UTC
Labels: Area: Outlook
