### ISSUE TITLE
[Excel Online] range.calculate() triggers recalc of all custom functions

### ISSUE THREAD

**Issue by fds-ssg** [OfficeDev/office-js#576] opened 2019-06-25 21:48 UTC
## Expected Behavior
range.calculate() should only cause functions within the specified range to recalculate

## Current Behavior
In Excel online, calculate() on a single cell results in all custom functions in the entire workbook being recalculated.  In Excel on Windows, the recalculation occurs only on the specified range, as expected.

## Steps to Reproduce, or Live Example

* Additional details: 
1. For my example, I used a custom function that incremented and returned a global 'count' variable
  2. Create a task pane button linked to a function that runs recalculate on the current sheet or active cell, e.g.: 
```
async function DoCalc() {
  await Excel.run(async (context) => {
    const r = context.workbook.getActiveCell();
    r.calculate();
    await context.sync();
  });
}
```
  3. Insert the custom function onto one sheet, go to another sheet, and click the task pane button to run the DoCalc function.
  4. Note that the value of the function on the other sheet has incremented, indicating it was recalculated.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Build 16.0.11824.37950
* Operating System: ______
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lumine2008** [comment] 2019-06-27 02:41
@RuoyingLiang, would you please have a look on this issue? thanks

**Comment by keyur32** [comment] 2019-07-15 19:34
Update: team is investigating, currently range.recalc causes built-in and custom functions to recalculate (not just volatile ones). This also occurs in Excel Online when an adjust occurs.

**Comment by XiangGaoMSFT** [comment] 2019-11-01 02:13
The fix has been deployed to production.
I'm closing this issue. Please feel free to reopen it if the issue is still there.

**Closed as completed by XiangGaoMSFT** 2019-11-01 02:13 UTC
Labels: Type: product bug, Status: fixed, Area: custom functions
