### ISSUE TITLE
Can't Upload Excel Add-In Manifest to 365 Admin Center

### ISSUE THREAD

**Issue by FreeSoftwareServers** [OfficeDev/office-js#3214] opened 2023-03-13 20:22 UTC
Greetings,

I've built an Excel Add-In that is currently being used by a number of people via Sideloading. I've gotten IT to try to upload via M365 Admin Center, but all they got was a generic "failure" message without any logs/debugging information.

Any idea how to troubleshoot this?

Note: I tested using an XML direct from this repo to ensure it wasn't my own XML that had issues (it passed validation) and continue to receive the same error.

SO Post --> https://stackoverflow.com/questions/75403381/uploading-add-in-to-365-admin-center-deployment-failed-next-steps

![Deployment Failed Screenshot](https://user-images.githubusercontent.com/16218200/224823890-740cf2ab-2435-4959-a736-92b12c25079c.png)

Manifest --> https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/excel-shared-runtime-scenario/manifest.xml

**Comment by preethikakiru** [comment] 2023-03-16 18:35
Hello @FreeSoftwareServers, thank you for submitting this issue! 
I've assigned it to @AkhileshShah-MS who will be able to provide you with more information or help resolve the issue.
Best,
Preethika

**Comment by AkhileshShah-MS** [comment] 2023-03-20 05:21
Hi @FreeSoftwareServers 
Thanks for reaching out. To help us debug the issue, can you please share the tenant ID and manifest file on email to addin-help@outlook.com. Please deprecate any personal and sensitive information from the file before sharing with us. 
Thank You!

**Comment by FreeSoftwareServers** [comment] 2023-03-20 06:51
@AkhileshShah-MS I emailed the information requested, you will note I have already provided a link to the manifest in the OP. For the purpose of this investigation, I will use that Manifest.

**Comment by FreeSoftwareServers** [comment] 2023-03-21 20:41
@AkhileshShah-MS I e-mailed that link and they responded via e-mail asking for a "Fiddler". I deduced they mean to install a browser extension and capture logs, but the e-mail wasn't very descriptive. I have a few points/questions. 

* Can we please communicate via this GitHub thread unless e-mail is needed? 
* 
* It will not be easy for me to request IT to install an extension and capture logs and they may not want to release the logs externally. 
* 
* The e-mail stated that the Manifest worked, well I'd hope so, its direct from this Repo. I was curious if since you asked for the "tenant" ID, was this install test done against the Tenant ID at all or anything related to the Tenant ID? 
* 
* Was the test done using Office 365 Deployment or Side Loading?
*
* Is there somewhere we can look internally for logs that might describe why it failed?
*
* I'll mention the Fiddler logs to IT, but again, it may be a "tall ask" and not possible. 
* 
* This is quite disappointing after the amount of effort put in to have the deployment method fail. It makes the time somewhat of a waste as the main goal was centralized deployment methods.

**Comment by exextoc** [comment] 2023-03-24 04:23
@FreeSoftwareServers 
**Can we please communicate via this GitHub thread unless e-mail is needed?**
-Sure. We can do that.
It will not be easy for me to request IT to install an extension and capture logs and they may not want to release the logs externally.
**The e-mail stated that the Manifest worked, well I'd hope so, its direct from this Repo. I was curious if since you asked for the "tenant" ID, was this install test done against the Tenant ID at all or anything related to the Tenant ID?**
-Addin was installed for a test account.
**Was the test done using Office 365 Deployment or Side Loading?**
-Deployed using Upload custom App -> upload from file from admin portal
**Is there somewhere we can look internally for logs that might describe why it failed?**
-You can check in the network trace why upload is failing and check the error message there. We can check internally but for that tenant id/name and admin id information is required. Please send that info over mail.
I'll mention the Fiddler logs to IT, but again, it may be a "tall ask" and not possible.
-We can try to work without fiddler

**Comment by FreeSoftwareServers** [comment] 2023-04-05 22:46
Greetings,

I've had a follow up w/ IT and unfortunatley, they only provided limited further details. As well, they are unwilling to export Fiddler logs due to concerns of credentials being shared.

The error we are getting is:

This operation was unsuccessful - reasons may include:
* Learn more about eligibility requirements.
(2ae33142-74c0-41bc-9919-fb0f5950cbd8)

Does this mean anything to you? I saw a post on SO that a user was able to fix by moving to Azure, but I can't see that affecting anything and I'm using an official Manifest from Microsoft/This repo with Public URLs. I can't figure it out!

I did wonder, we have "Add-Ins" disabled from the store, could this be preventing uploading custom apps?

Is there a way for me to setup a demo environment? My own Office 365 Admin Center?

Thank you for your time @exextoc !

**Comment by FreeSoftwareServers** [comment] 2023-04-25 22:07
@exextoc Can you do me a favor and test w/ the Office Store disabled as it is in my environment?

**Comment by FreeSoftwareServers** [comment] 2023-05-25 21:46
Does deploying an Add-In require access to the "Office Store" as our company has disabled access to the "Office Store" for Excel.

Hello? (Hello, hello, hello) / Is there anybody in there? / Just nod if you can hear me / Is there anyone home? 

@exextoc @AkhileshShah-MS @preethikakiru

**Comment by AkhileshShah-MS** [comment] 2023-06-14 05:23
Hi @FreeSoftwareServers! Apologies for the delay in response here. 
It helps our team to debug the issue if we have a network trace. However, we understand the limitations you might have on your side to get new software deployed. 
In such case, we'll try to trace the issue from our back end logs. For that could you please try this again and share error message with ID?  
Appreciate your patience and collaboration!

**Comment by FreeSoftwareServers** [comment] 2023-06-15 19:24
@AkhileshShah-MS 

Its not about the software deployment, my IT dept is uncomfortable sharing network trace as it may contain confidential information. 

I can ask IT to try one more time and send me log, I did post an error message that I got previously

```
Learn more about eligibility requirements.
(2ae33142-74c0-41bc-9919-fb0f5950cbd8)
```

But, before I ask IT, can you confirm for me the questions I've asked above, which is to test/confirm that it is possible to deploy an app internally while simultaneously having access to "The Office Store" disabled globally?

Thank You!

**Comment by FreeSoftwareServers** [comment] 2023-06-20 20:07
@AkhileshShah-MS 

I've also tried SO, SuperUser and now trying ServerFault as I can't seem to get response -->

(SO and SuperUser were wrong forums for this type of Q, my fault)...

https://superuser.com/questions/1790161/deploy-office-add-in-for-excel-with-office-store-globally-disabled

https://serverfault.com/questions/1134381/deploy-office-add-in-for-excel-with-office-store-globally-disabled

**Comment by AkhileshShah-MS** [comment] 2023-07-07 08:17
@FreeSoftwareServers Yes, its possible for an admin to deploy an app for the users with accoess to Office Store disabled globally. However, end users would not be able to deploy an app for themselves. 
Regarding the error message, for us to trace it in internal logs, we would request you to try again and share the latest failure. We would not be able to trace the issue with old error Id. 
Thank you!

**Comment by exextoc** [comment] 2023-07-14 05:08
@FreeSoftwareServers Can you please ask the customer to retry and share the fresh error message with us. We only store backend logs for certain duration, so won't be able to track based on the older error.

**Comment by FreeSoftwareServers** [comment] 2023-07-14 05:17
> @FreeSoftwareServers Can you please ask the customer to retry and share the fresh error message with us. We only store backend logs for certain duration, so won't be able to track based on the older error.

I will ask again tomorrow they've been less than responsive but said they're going to do it I'll push again

Thanks!

**Comment by Nils3311** [comment] 2023-07-18 13:16
+1 we have exactly the same error in our Company...

**Comment by FreeSoftwareServers** [comment] 2023-07-19 19:46
@exextoc and @AkhileshShah-MS 

My global admin tried to upload today, July 19, 2023 at 12:38pm Vancouver Time. I've asked for any error message/ID and will post.

Note: He is using the Manifest linked above "Contoso Data Importer". 

Hopefully this can help! Let me know what I can do next.

Could this somehow be Firewall related?

**Comment by FreeSoftwareServers** [comment] 2023-08-11 18:18
@exextoc  and @AkhileshShah-MS BUMP

**Comment by exextoc** [comment] 2023-08-17 12:26
Hi @FreeSoftwareServers no this shouldn't be firewall related most likely. Can you please share the error message/ID as you mentioned above?

1. Please ask the admin to deploy the addin and share the error message ID. We only have backend logs for 30 days. It would be helpful if you can ask the admin to try again and share it.

2. Also, if possible, can you share the tenant domain or tenant ID here?  That would be helpful, I see that you had mailed this details to [addin-help@outlook.com] but some of us don't have access to that.

**Comment by FreeSoftwareServers** [comment] 2023-08-17 18:24
@exextoc What a joke, did you wait more then 30 days past the time my global admin tried previously on purpose?

I give up....

**Comment by exextoc** [comment] 2023-08-18 06:00
Hi @FreeSoftwareServers,
We are sorry for the inconvenience.
But from your last reply "**My global admin tried to upload today, July 19, 2023 at 12:38pm Vancouver Time. I've asked for any error message/ID and will post.**"

I think it went under the assumption that you'll post the message/ID here and the on-call engineer will take a look.
This account is being used by multiple oncalls, so it might have got missed.

I could have looked the logs from TenantID but that also wasn't sent in this discussion, but it was sent to a mail id which I don't have access to that's why I asked to share Tenant ID here.

I hope you understand and provide at least the TenantID if possible so we can look into this. Apologies again for the inconvenience!

Thanks for your cooperation! And please don't give up :)

**Comment by exextoc** [comment] 2023-08-18 06:25
Hi @FreeSoftwareServers,
Update on this one: I checked logs around that date "July 19 2023 12:38 Vancouver time", and I found the root cause of the issue being the tenant is a multi-forest tenant and the org mailbox is in some different forest and the admin's mailbox is in some different forest. This caused failure in deployment as we didn't have support for this scenario.

Good news is that, this week only, we rolled out the changes which allows the above scenario to work. So, the deployment should work fine now for your admin user.

Please try again and let us know if there are still any issues, otherwise we can mark this issue as closed.

**Closed as completed** 2023-08-21 06:38 UTC
Labels: Needs: attention :wave:, Area: add-ins platform, Area: Centralized Deployment
