### ISSUE TITLE
Shared MailBox, OfficeJS saveAsync() returns a draft ID that is not permitted by the owner's mailbox

### ISSUE THREAD

**Issue by naemcivic** [OfficeDev/office-js#1116] opened 2020-04-23 17:23 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

On our Outlook add-in for compose mode, we are using the Office JS API to save the email draft by calling ```Office.context.mailbox.item.saveAsync()``` then passing the result to  
```javascript
Office.context.mailbox.convertToRestId(
            results[0],
            Office.MailboxEnums.RestVersion.v1_0
          );
``` 
to obtain the **_draft ID_**

## Expected Behavior

The draft ID provided should be accessible by the mailbox owner on MS Graph service

## Current Behavior

code: 404 
message: 404 ErrorInvalidMailboxItemId: "Item Id doesn't belong to the current mailbox."
status: “failed”

## Steps to Reproduce, or Live Example

Add a shared mailbox:

1. Find and Open a shared mailbox

Steps to reproduce:

1. Create a new email in Outlook for Mac
2. In the From field, select the shared mailbox
3. Open and add-in's pane and try to call
Office.context.mailbox.item.saveAsync()
4. Pass the result from `Office.context.mailbox.item.saveAsync()` to 
```javascript
Office.context.mailbox.convertToRestId(
            results[0],
            Office.MailboxEnums.RestVersion.v1_0
          );
```
5. Use that ID to make a graph call with the mailbox owners graph token . The call should error out with the following message ```404 ErrorInvalidMailboxItemId: "Item Id doesn't belong to the current mailbox."```
 

* Additional details:

This flow use to work up until a day or two ago and this flow cureently works on Windows Outlook and Outlook Web Access with our web-addin

## Your Environment

* Platform: Mac
* Host: Outlook for Mac
* Office version number: 16.34 (20020900)
* Operating System: MacOS Catalina 10.15.4 (19E287)
* Browser (if using Office Online): ______

**Comment by ZainW** [comment] 2020-04-23 17:45
I have the above issue as well, tunning running macOS 10.15.4 and outlook version 16.36 (20041300)

**Comment by yumao5** [comment] 2020-04-23 18:39
I experienced the similar issue. Outlook Version 16.36 (20041300).

**Comment by exextoc** [comment] 2020-04-28 08:34
Did you start facing this issue after upgrading to MacOS Catalina 10.15.4?

**Comment by naemcivic** [comment] 2020-04-28 15:53
> Did you start facing this issue after upgrading to MacOS Catalina 10.15.4?

We are not certain if upgrading to MacOS Catalina 10.15.4 (19E287) was the issue. Something that is worth mentioning is that on another Mac that I have which is on MacOS Catalina 10.15.4 (19E266) was working last week, however when trying again today it doesn't work anymore.

**Comment by naemcivic** [comment] 2020-04-28 20:59
We got another team member to test with macOS Mojave Version 10.14.6 with Outlook Version 16.36 (20041300) and it doesn't work as well

**Comment by exextoc** [comment] 2020-04-29 10:45
Can you try to get the message via Rest API as mentioned in [doc](https://outlook.office365.com/api/v2.0/me/messages/) using postman app and see if you are able to access the item.
Also when you say mailbox owner is it owner of shared mailbox or the person whom mailbox is delegated to?

**Comment by naemcivic** [comment] 2020-04-29 14:28
@exextoc 
We are trying to retrieve the draft from the delegated mailbox via Graph, as suggested we have also tried calling the Rest API with the draft id and the result is the same as the error we have provided in this issue.  The draft id we obtain from OWA or Windows Outlook is working, but the draft ID we are getting back on Mac is not working.

**Comment by liamtim** [comment] 2020-04-30 14:52
@exextoc Can you provide a timeline on a fix for this?

**Comment by exextoc** [comment] 2020-05-05 12:06
Could you please share the code snippet used to retrieve the draft? We would  also like to understand what is the rest URL being used to retrieve the draft item.

**Comment by naemcivic** [comment] 2020-05-05 14:42
> Could you please share the code snippet used to retrieve the draft? We would also like to understand what is the rest URL being used to retrieve the draft item.

The gist of the code snippet is as follow:

```javascript
Office.context.mailbox.item.saveAsync(function(result) { 
  var promises = [];
  promises.push(result.value);

  Office.Promise.all(promises).then(
    function(results) {
      var draft_id = Office.context.mailbox.convertToRestId(
        results[0],
        Office.MailboxEnums.RestVersion.v1_0
      );
    },
    function(err) {
      // handle error
    }
  );
});
```

We then use the `draft_id` to call graph api with. 

We are using:

`https://graph.microsoft.com/v1.0/users/<:id>/mailFolders/<:id>/messages/<:draft_id>?$expand=attachments`

Please keep in mind that this flow does work with our addin with OWA and Outlook for windows.

**Comment by naemcivic** [comment] 2020-05-05 14:46
@exextoc 
> > Could you please share the code snippet used to retrieve the draft? We would also like to understand what is the rest URL being used to retrieve the draft item.
> 
> The gist of the code snippet is as follow:
> 
> ```js
> Office.context.mailbox.item.saveAsync(function(result) { 
>   var promises = [];
>   promises.push(result.value);
> 
>   Office.Promise.all(promises).then(
>     function(results) {
>       var draft_id = Office.context.mailbox.convertToRestId(
>         results[0],
>         Office.MailboxEnums.RestVersion.v1_0
>       );
>     },
>     function(err) {
>       // handle error
>     }
>   );
> });
> ```
> 
> We then use the `draft_id` to call graph api with.
> 
> We are using:
> 
> `https://graph.microsoft.com/v1.0/users/<:id>/mailFolders/<:id>/messages/<:draft_id>?$expand=attachments`
> 
> Please keep in mind that this flow does work with our addin with OWA and Outlook for windows.

**Comment by liamtim** [comment] 2020-05-07 22:03
@exextoc Have you replicated the issue? We need a fix for this as soon as possible. Let me know if you need additional details.

**Comment by exextoc** [comment] 2020-05-08 13:36
We are able to repro this issue from our side when the user id in the graph call is the delegatee's Account. Can you confirm the user id being used here?

**Comment by naemcivic** [comment] 2020-05-08 13:48
> We are able to repro this issue from our side when the user id in the graph call is the delegatee's Account. Can you confirm the user id being used here?

Yes, this is correct. The user id used in the graph call is the delegate's account.

**Comment by liamtim** [comment] 2020-05-11 19:03
@exextoc When can we expect this to be resolved?

**Comment by exextoc** [comment] 2020-05-13 10:24
Using [getSharedPropertiesAsync](https://docs.microsoft.com/en-gb/office/dev/add-ins/outlook/delegate-access) is the solution here, our team is working towards enable this API on Outlook for Mac. It should be available in [Insider builds](https://insider.office.com/en-us/join/mac) soon.

**Comment by naemcivic** [comment] 2020-05-13 17:32
@exextoc

Thank you for the update. As our clients rely on this web add-in for their day to day business is not on board with using insider builds, can you provide an approximate timeline on when this will be available on the next insider build and release so we can start working on using getSharedPropertiesAsync()? In the future in case of a breaking change like this one, please communicate this to us in advance so we can have enough time to respond and find potential solutions or a work around.

**Comment by liamtim** [comment] 2020-05-20 16:02
@exextoc Do you have an ETA on this fix?

**Comment by exextoc** [comment] 2020-05-22 06:07
We unfortunately have no timelines to share at this point. Thanks a lot for your patience.

**Comment by liamtim** [comment] 2020-06-09 13:48
@exextoc Do you have any updates regarding this? Our customers have not been able to use our Add-in on their Mac version of Outlook for 6 weeks now.

**Comment by liamtim** [comment] 2020-06-23 14:19
@exextoc Do you have updates here? This functionality had never been an issue up until April this year.

**Comment by exextoc** [comment] 2020-06-24 14:44
Hi @liamtim , unfortunately support for getSharedPropertiesAsync has still not rolled out to Insiders. We are working on rollout, but cannot share timelines at this point. Thank you for your patience. We will update this thread once it is available.

**Comment by exextoc** [comment] 2020-07-10 16:30
Update: getSharedPropertiesAsync has been rolled out to Insiders. You should be able to use the API on the latest Insider Fast build. It will be rolled out to non-Insider builds soon.

**Comment by naemcivic** [comment] 2020-07-16 18:43
@exextoc 
From the docs (https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#getsharedpropertiesasync-callback-) this function is not supported on Mac Outlook

I have tried with the following:
API set: Mailbox 1.8 is met
Mac Outlook: Insider Build 16.40 (20071407)
Office JS 1.1.40

The following call returns an undefined function
```javascript
Office.context.mailbox.item.getSharedPropertiesAsync(function(result) {
  console.log(result.value);
});
```

**Comment by liamtim** [comment] 2020-07-17 20:41
@exextoc Can you provide some insight here please?

**Comment by daneshd** [comment] 2020-07-17 21:03
I'm hitting this issue with as well, on the insider build for Outlook for Mac

**Comment by exextoc** [comment] 2020-07-20 09:02
getSharedPropertiesAsync has been rolled out to Insiders and is available in latest IF build 16.40 (20071407). But, the issue reported is reproducible in Message Compose surface alone while it works as expected on other surfaces. Can you confirm this on your side?

**Comment by naemcivic** [comment] 2020-07-20 14:23
> getSharedPropertiesAsync has been rolled out to Insiders and is available in latest IF build 16.40 (20071407). But, the issue reported is reproducible in Message Compose surface alone while it works as expected on other surfaces. Can you confirm this on your side?

We currently only use the library in compose mode for Outlook, therefore we are not certain if it works on other surfaces or not. Compose surface is what we are concerned at the moment, which unfortunately doesn't work.

**Comment by exextoc** [comment] 2020-07-21 06:48
Thanks for confirming that you are seeing this issue in Message Compose surface. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by naemcivic** [comment] 2020-07-21 13:20
@exextoc Can this issue be reopened? or is there another issue we can follow along here?

**Comment by exextoc** [comment] 2020-07-21 13:34
We will update this thread once the issue is fixed.

Internal tracking id: Office:4312812

**Comment by liamtim** [comment] 2020-07-22 15:53
@exextoc Is there any way to bump the priority on this issue? It was initially reported that the function does not work when using Compose mode via Mac OS  3 months ago

**Comment by liamtim** [comment] 2020-07-30 13:16
@exextoc Can you please provide an update here? Our customers have not been able to use our Add-in on their Mac version of Outlook for 14 weeks now.

**Comment by liamtim** [comment] 2020-08-04 22:23
@macOutlookExtensibility Do you have any updates for us here?

**Comment by liamtim** [comment] 2020-08-11 15:58
@exextoc @macOutlookExtensibility Can you provide us with an update? We are without this functionality for 3.5 months now.

**Comment by exextoc** [comment] 2020-08-14 09:28
Apologies for this delay. We are actively working on this and will be able to provide update soon on this.

**Comment by liamtim** [comment] 2020-08-17 18:22
@exextoc Thank you for confirming. Looking forward to receiving a timeline.

**Comment by liamtim** [comment] 2020-08-21 13:54
@exextoc, any updates on a timeline for this?

**Comment by daneshd** [comment] 2020-08-27 21:39
I'm also still hitting the same issue from before. It'd be great to see this fixed!

**Comment by exextoc** [comment] 2020-08-30 17:08
The support for getSharedProperties in MessageCompose Scenario is added and it is in Insiders fast now.
With this getSharedPropertiesAsync API you will get the params targetRestUrl , targetMailBox which you can use to construct rest url and get the required information.

**Comment by naemcivic** [comment] 2020-09-01 20:22
@exextoc 
I have tried using the getSharedPropertiesAsync API which is now available in the insiders fast build from following the example in the docs https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#getsharedpropertiesasync-options--callback-

However, I am getting a http response of 403.  The only thing different on my end is, I am doing this in compose mode, therefore I am not using this `var ewsId = Office.context.mailbox.item.itemId;` from the docs to get the itemId, instead `Office.context.mailbox.item.saveAsync` is used to get the identifier as suggested here in the docs https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.8#itemid

PS. Both delegatePermissions and Office.MailboxEnums.DelegatePermissions.Read is 1

What would cause this 403 Forbidden status to return?

**Comment by naemcivic** [comment] 2020-09-14 18:01
```sharedProperties.targetRestUrl + "/v2.0/users/" + sharedProperties.targetMailbox + "/messages/" + draft_id;``` which translates into ```https://outlook.office.com/api/v2.0/users/InternalComms@contactmonkey.ca/messages/<:draft_id>``` would return a status of 403 Forbidden. I am using the (token `asyncContext`) from the result of `getSharedPropertiesAsync`, for the rest call. 

Please help us resolve this issue, as we have tried this API several times with similar result.

**Comment by ZainW** [comment] 2020-09-21 18:32
I've been following this thread as well, I still have the problem as described by @naemcivic even on insiders build

**Comment by yumao5** [comment] 2020-09-21 20:24
@exextoc thank for update. But still have issues as @naemcivic mentioned. Fast build not quite works.

**Comment by naemcivic** [comment] 2020-09-28 22:50
@exextoc @macOutlookExtensibility 

Is there any update on this please. would really like to get this to be sorted out, as this has been on going for so long. thank you

**Comment by SamAchten** [comment] 2022-05-09 14:14
Is there any update on this issue? The getSharedPropertiesAsync() does not return the ID of the appointment in the owner's calendar...

**Closed as not planned** 2024-03-25 20:15 UTC
Labels: Area: Outlook, Type: product bug, Status: in backlog
