### ISSUE TITLE
How to run desktop Word AddIn with Angular 11.0.5 in MS office 2016

### ISSUE THREAD

**Issue by vinodifour** [OfficeDev/office-js#1575] opened 2021-01-06 13:10 UTC
- With Angular 5.2.11 and MS Word 2016 my AddIn working fine 
when upgrading the version of angular to 11.0.5 it's not working.

**Comment by KelBowen** [comment] 2021-01-06 22:29
Thank you for logging this issue. I think we need more details to properly route your issue. Would you mind providing us more details?



## Expected Behavior


## Current Behavior



## Steps to Reproduce, or Live Example



* Link to live example: ______


* Additional details:
  1. ______
  2. ______
  3. ______

## Context



## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by vinodifour** [comment] 2021-01-07 07:01
With Angular 5.2.11 and MS Word 2016 my AddIn working fine
when upgrading the version of angular to 11.0.5 it's not working.

**Code attached on below link :**
https://drive.google.com/file/d/1sftv5yFuH7yzyQHC34oH52wxopHR8KgP/view?usp=sharing

**Additional details:**
- AddIn working fine with Outlook Word online fine 
- AddIn not working with MS Word 2016 desktop App after upgrading to latest angular 

**Environment Detail**
- PC Desktop : Windows 10 
- Browser on Web - Microsoft Edge, Mozila Firefox
- Office version - 2016, office 365
- 64 bit Operating System

**Comment by vinodifour** [comment] 2021-02-01 10:58
Just checking if there is any ETA on fixing this issue.

**Comment by lindalu-MSFT** [comment] 2021-03-18 22:27
@AbidRahman-MSFT Somehow, this issue did not get an assignee and got overlooked. Can you please help triage and assign the correct person to follow up with Vinod? Thanks, linda

**Comment by AbidRahman-MSFT** [comment] 2021-03-19 22:07
Hey Vinod,

We need more detailed information to help you here. Are you running across errors? What is preventing the add-in from running? Does the add-in run but has errors? Are you able to side load the add-in? What is the actual issue? 

Also, as it stopped working after updating your angular version, this seems to be an issue with angular and not office js. 
I'm going to close the issue, please feel free to open if you have more info.

Thanks,
Abid

**Closed as completed by AbidRahman-MSFT** 2021-03-19 22:07 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: Word
