### ISSUE TITLE
Excel AddIn Dialog.messageChild not send message to child

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#2372] opened 2022-01-18 13:28 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am trying Excel Addin with Dialog API.

I want to create a dialog and then send message with `dialog.messageChild`, but the child not receive the message.

Here is code

Parent
```
var loginDialog: Office.Dialog;
async function login(event: Office.AddinCommands.Event) {
  var dialogInput = new DialogInput();
  dialogInput.name = MeekouConsts.DataFromWeb;
  await showDialog(dialogInput);
  //show specific dialog
  // await Office.context.ui.displayDialogAsync(
  //   `${AppConsts.appBaseUrl}/login.html`,
  //   { height: 40, width: 20 },
  //   function (asyncResult) {
  //     loginDialog = asyncResult.value;
  //     loginDialog.addEventHandler(Office.EventType.DialogMessageReceived, processMessage);
  //   }
  // );
  event.completed();
}

async function showDialog(dialogInput: DialogInput) {
  console.log(dialogInput);
  await Office.context.ui.displayDialogAsync(
    `${AppConsts.appBaseUrl}/dialog.html`,
    { height: 40, width: 20 },
    function (asyncResult) {
      dialog = asyncResult.value;
      dialog.addEventHandler(Office.EventType.DialogMessageReceived, dialogMessageFromChild);
      **dialog.messageChild("Hello");**
      log("A3", "ff");
    }
  );
}
```
Child
```
Office.initialize = async () => {
  console.log("ww");
  document.getElementById("send").addEventListener("click", (e:Event) => {
    Office.context.ui.messageParent("Hello World");
  });
  Office.context.ui.addHandlerAsync(Office.EventType.DialogParentMessageReceived, dialogMessageFromParent);
};

function dialogMessageFromParent(arg: any) {
  log("B2","dialog" + JSON.stringify(arg));
  var newlabel = document.createElement("Label");
  newlabel.innerHTML = "Here goes the text";
  document.getElementById("messages").appendChild(newlabel);
  dialogInput = JSON.parse(arg.message) as DialogInput;
  document.getElementById(dialogInput.name).style.display = "inline";
}
```
`dialogMessageFromParent` is not fired.

**Comment by RuizhiSunMS** [comment] 2022-01-24 05:36
@lliu113 could you please take a look on this?

**Comment by devbryan0225** [comment] 2022-03-09 06:03
Similar issue. My angular addin project uses Office.onReady() instead of Office.initialize .

I have Office.context.ui.addHandlerAsync() called in a chain promise (.then() ).
I have a catch promise, and it caught a TypeError with the message 'Office.context.ui.addHandlerAsync is not a function' .

That is probably why the dialogMessageFromParent does not fire.


```typescript
Office.onReady(() => {
  var e = document.getElementById('sideload-msg');
  if (e != null) {
    e.style.display = 'none';
  }

  platformBrowserDynamic()
    .bootstrapModule(AppModule)
    .catch((err) => console.error(err));
}).then(function(res) {
  console.log(res);
// OSF.DDA.UI.ParentUI or OSF.DDA.UI.ChildUI 
  console.log(Office.context.ui);
  // TypeError: addhandlerasync is not a function
  Office.context.ui.addHandlerAsync(Office.EventType.DialogParentMessageReceived,
    onMessageFromParent,
    onRegisterMessageComplete);
}).catch((error) => {console.log('there is an error in office ready : '+error)});

function onMessageFromParent(arg: Office.DialogParentMessageReceivedEventArgs) {
  console.log('i received message from parent.');
  var messageFromParent = JSON.parse(arg.message);
  console.log(messageFromParent.name);
}

function onRegisterMessageComplete(asyncResult: Office.AsyncResult<void>) {
  console.log(asyncResult );
  if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
      console.log(asyncResult.error.message);
  }
}
```

The display dialog called from a page button:

```typescript
Office.context.ui.displayDialogAsync(
      `${window.location.origin}/somename`, 
      {height: 80, width: 50, displayInIframe: true},
      (result) => {
        if (result.status == Office.AsyncResultStatus.Succeeded) {

          console.log(result);
          dialog = result.value;
          dialog.addEventHandler(Office.EventType.DialogMessageReceived, this.processMessage);

          // it doesn't work if I call the messageChild immediately here?
          dialog.messageChild(JSON.stringify({token: 'sdfdsfad'}));
        }
      }
    );
```

I noticed that:
- Office.context.ui of type OSF.DDA.UI.ParentUI does not have the `addHandlerAsync()` method.
- If the instance is a dialog and not the addin/taskpane, Office.context.ui is of type OSF.DDA.UI.ChildUI and that it has the `addHandlerAsync()` method.

![image](https://user-images.githubusercontent.com/52289084/157383851-9e7012c1-34e4-4df3-899f-7c87b34c21da.png)

![image](https://user-images.githubusercontent.com/52289084/157383788-657a33b6-894f-4976-9e96-14461d3544e8.png)

**Comment by Iso5786** [comment] 2022-03-09 17:45
I have exactly the same issue within Outlook.

I register the dialog as follows:
```js
var mailPopup

export function showMailPopup(mailBody: string) {
  var fullUrl =
    location.protocol +
    '//' +
    location.hostname +
    (location.port ? ':' + location.port : '') +
    '/emailpopup.html'

  window.localStorage.setItem('mailBody', mailBody)
  Office.context.ui.displayDialogAsync(
    fullUrl,
    { height: 60, width: 60 },
    function (asyncResult) {
      mailPopup = asyncResult.value
      mailPopup.messageChild(mailBody)
    }
  )
}
```

The handler of the dialog is added as follows:
```js
Office.initialize = function () {
  console.log('Emailpopup: init')
  Office.context.ui.addHandlerAsync(
    Office.EventType.DialogParentMessageReceived,
    onMessageFromParent,
    onRegisterMessageComplete
  )
}

function onRegisterMessageComplete(asyncResult) {
  if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
    console.log('Emailpopup error: ', asyncResult.error.message)
  } else {
    console.log('Emailpopup registering complete ')
  }
}

function onMessageFromParent(arg) {
  console.log('Emailcontent: ', arg.message)
  document.getElementById('email').innerHTML = arg.message
}
```

I also assume that the cause of the issue is that I call the `messageChild` immediately in the callback of `displayDialogAsync`.
But this is also what I need as I want to pass the HTML email content directly to the dialog after it has been created without further user action.

**Comment by neville-jones** [comment] 2022-06-22 06:58
I have observed the same problem in Word, but also found that if I call messageChild a second time the message is received by the dialog...

**Comment by ElizabethSamuel-MSFT** [comment] 2022-08-10 00:22
@massonj Can you assign to the appropriate person to take a look? Thanks.

**Comment by plamenbotev** [comment] 2022-08-14 13:16
If the issue is caused by the event handler in the dialog not yet been bound due to the async nature of the dialog API, you can delegate it as follows:

1. In the dialog l, trigger custom event to the parent to notify it that the dialog is loaded. Before triggering that event, bind the handler for the messageChild
2. In the handler of the event sent to the parent from the child, trigger the event to the child.

Using the above we will be sure that the event handler in the child is bound prior to triggering the event in the parent. 

Hope the above helps. :)

**Comment by pvsleeper** [comment] 2022-08-15 03:08
Yes, I am doing something similar to what @plamenbotev is doing and its working fine for me.

The code opening the dialog looks something like this:
```
  Office.context.ui.displayDialogAsync("dialog.html"
        url,
        { height: 40, width: 20 },
        (asyncResult) => {

          dialog = asyncResult.value;
// wait for the dialog to tell us its ready to process messages. Once it is, we can sent messages to it
          dialog.addEventHandler(Office.EventType.DialogMessageReceived, (arg) =>{
            if (arg.message === "IAmReady"){
              dialog.messageChild("WhatEverINeedToTellChild");
            }
          });
        }
  );
```

And then the code in dialog.html looks something like this:

```
Office.initialize = async () => {
 Office.context.ui.addHandlerAsync(Office.EventType.DialogParentMessageReceived, (args) => {
    console.info(args.message)
  });
  Office.context.ui.messageParent("IAmReady");  
};
```

**Comment by shassain** [comment] 2023-03-28 22:26
thanks [plamenbotev](https://github.com/plamenbotev) and [pvsleeper](https://github.com/pvsleeper), your suggestion works for me

**Comment by 2jjk** [comment] 2023-05-07 06:24
Sorry for bumping this after a while, but [pvsleeper](https://github.com/pvsleeper)'s answer kind of worked for me; however, I want to send a message back to the parent only when a button is pressed. 

When I send a message using messageChild from the parent, the dialog box does not display anything unless messageParent is triggered, which is what I'm doing as a workaround. But that means, in the dialog code, I will have two messageParent: one for "loading" the data sent from the parent, and another when pressing a button to send data back to parent. And I just need the second.

Another issue for me is when pressing the button, I want the dialog to close but having two messageParent calls, means the dialog box closes immediately.

**Closed as not planned** 2024-04-18 18:57 UTC
Labels: Needs: attention :wave:, Area: add-in UI
