### ISSUE TITLE
RichApi.Error: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again.

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/office-js#856] opened 2019-11-18 04:08 UTC
Clicking a cell and then randomly or immediately selecting a cell back and forth breaks the app.

## Expected Behavior
It shouldn't cause any errors or break the app when randomly or immediately selecting cells and ranges multiple times.

## Current Behavior

Excel is not responding, hangs, freezes or stops working after randomly selecting cells and ranges several times. As a result, I have to reload an Office-add in (Taskpane) or refresh the page.

## Steps to Reproduce, or Live Example

1. Clicking a cell and then  randomly or immediately selecting the cell back and forth breaks the app.
2. Error happens
3. The excel/taskpane crashes

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]:  Mac (Office Online)
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: macOS Mojave
* Browser (if using Office Online): Chrome

## Useful logs

<img width="1325" alt="Screen Shot 2562-11-18 at 10 58 43" src="https://user-images.githubusercontent.com/18175994/69025489-cbdd3500-09f9-11ea-9b45-e500e1457879.png">

**Comment by MandytMSFT** [comment] 2019-11-18 06:19
@topkoong thanks for the reporting. For cell-editing mode error, it's by design as we don't support js running after entering cell edit mode. 

But for taskpane hang and crash, it's definitely an issue. Do you mind to share your code to me as i can't repro on office online.

**Comment by lumine2008** [comment] 2019-11-18 06:20
In cell edit mode, JS API cannot execute in the Excel, 
you could use this API delayForCellEdit, if the user is in cell edit mode the batch request will be delayed until the user exits cell edit mode.
https://docs.microsoft.com/en-us/javascript/api/excel/excel.runoptions?view=excel-js-preview#delayforcelledit

**Comment by topkoong** [comment] 2019-11-18 07:20
@MandytMSFT 
Below is my code snippet.

@lumine2008 I've already added delayForCellEdit, but there's still an error.
```javascript
onSelectionChanged(selectedSection, isCellReferenceMode: boolean, tables):
		Promise<void | CellReferenceChanged | ChangeDestinationCell | NewDestinationCell> {
			return Excel.run({ delayForCellEdit: true }, async ctx => {
				const selectedRange = ctx.workbook.getSelectedRange();
				const worksheet = ctx.workbook.worksheets.getActiveWorksheet();
				selectedRange.load({
					address: true,
					values: true,
				});
				worksheet.load({ id: true, name: true });
				await ctx.sync();
				const values: any[] = flatten(selectedRange.values);
				this.cellReference.next({
					value: values[0],
					address: selectedRange.address,
					worksheetId: worksheet.id,
					worksheetName: worksheet.name,
				});
				if (isCellReferenceMode) {
					return new CellReferenceChanged({
						values,
						address: selectedRange.address,
						worksheetId: worksheet.id
					});
				} else {
					const destCell = CellAddress.fromAbsoluteAddress(worksheet.id, selectedRange.address);
					return selectedSection === Section.Destination && !this.isCellBelongsToTable(tables, destCell)
						? new ChangeDestinationCell(destCell)
						: new NewDestinationCell(destCell);
				}
			}).catch(err => ExcelHelper.handleError(err));
	}
```

**Comment by lumine2008** [comment] 2019-11-18 13:30
Thanks @topkoong , it would be super helpful if you could share me the gist, which could generate by script lab and upload to the github. thanks a lot

**Comment by sethachoi** [comment] 2019-11-19 21:08
Hello I believe this is related to my issues #792 and #791 there's some additional test code + gists in those as well!

**Comment by lumine2008** [comment] 2019-11-20 04:44
@sethachoi , I checked with my team, for the cell edit mode error message, we are not able to repro. but we can repro prevent the format change from updating. (#792 issue)  team is investigating on preventing format change issue now.

**Comment by topkoong** [comment] 2019-11-25 08:04
@lumine2008 Thanks for the update! Can you try clicking a cell and then randomly or immediately selecting the cell back and forth breaks the app with a simple Excel.run code?

**Comment by lumine2008** [comment] 2019-11-26 08:36
Thanks @topkoong , I could not repro this issue when clicking the cell randomly but not entering the cell edit mode. if I enter the cell edit mode, it throws an exception, which is expected. because API cannot be run in cell edit mode is by design, the reason is CellEditMode is a very special mode in the Excel, both VBA and JS API cannot run in the CellEditMode. So API calls will fail and throw the exception .

**Comment by tjcrowder** [comment] 2020-11-03 15:55
@lumine2008 - Is it possible to either turn off cell-editing mode or proactively check whether the app is in cell-editing mode?

With our add-in the user fills in some cell information and clicks Save in the add-in's task pane. We have a user who habitually presses Enter after editing the cell, activating cell-edit mode in the next cell in a range they've selected, and then clicks Save -- and runs into the cell-editing error. (On Desktop Excel; in Web Excel, clicking the Save button automatically exits cell-editing mode.) Although we could delay our save operation with the flag you mentioned, the user wouldn't know why it was delayed. If we could turn off cell-editing mode when they click Save, or at least detect the mode and tell them to exit it, that would help a lot. TIA!

*(We could use a hack, include the flag but then if our callback hasn't been called within X seconds, assume it's a cell-editing mode issue and warn the user, but...)*

**Comment by lumine2008** [comment] 2021-03-17 06:09
Current office js do not support turn off cell-edit mode. from your description, Win32 click save button not exiting cell edit mode is a bug 4216350 is logged to track this issue

**Comment by donlvMSFT** [comment] 2022-11-16 09:25
The bug already been fixed and released after Office build version: 16.0.14702.37375, please help verify, and I'd like to close this thread due to the status.

**Closed as completed by donlvMSFT** 2022-11-16 09:25 UTC
Labels: Area: Excel, Status: in backlog

**Comment by taralex77** [comment] 2022-12-06 01:36
Are you sure this was fixed?
We are now getting this error when trying to perform any call on Excel runtime. 
The problem renders our Excel plug-in unusable as we cannot make any calls.
Here's a sample code that crashes:
```
await Excel.run(async (ctx) => {
      ctx.workbook.worksheets.getFirst().load(['id', 'name']);
      await ctx.sync();
});
```

The exception text is:
_Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again._

This is the second critical bug that was released within just a couple of months. Do you guys even test your changes before deploying them?

**Comment by Denwah** [comment] 2022-12-06 03:38
I am getting the same issue as taralex77. Is anyone investigating this?

**Comment by gingerjia** [comment] 2022-12-06 05:39
@taralex77 and @Denwah, sorry for the confuse, the bug (4216350) has been fixed is for "Win32 click save button not exiting cell edit mode" part.
![image](https://user-images.githubusercontent.com/62282034/205824734-5537b5db-a508-4f2b-a8c4-a7580dec0a16.png)
For executing API in cell-edit mode, currently it's not supported.  If it's a hard blocker for your add-in, could you help to post new request in [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and our PM will help to priority it? Thanks!

**Comment by Denwah** [comment] 2022-12-06 05:44
> @taralex77 and @Denwah, sorry for the confuse, the bug (4216350) has been fixed is for "Win32 click save button not exiting cell edit mode" part. ![image](https://user-images.githubusercontent.com/62282034/205824734-5537b5db-a508-4f2b-a8c4-a7580dec0a16.png) For executing API in cell-edit mode, currently it's not supported. If it's a hard blocker for your add-in, could you help to post new request in [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and our PM will help to priority it? Thanks!

Hi gingerjia,

My issue is that the workbook is not in edit mode but the addin thinks it is. There is no cell being edited when the addin runs the following:

`const selectedRange: Excel.Range = context.workbook.getSelectedRange();
selectedRange.load();
await context.sync();`

This was working fine last week, but now it states the following on sync:
RichApi.Error: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again.

**Comment by gingerjia** [comment] 2022-12-06 06:46
@Denwah I cannot repro it locally. Could you share more details to help with the repro? Thanks!

**Comment by bushraHavi** [comment] 2022-12-06 08:36
My issue is that the workbook is not in edit mode but the addin thinks it is.
I am facing the same issue, it was working fine till yesterday.
@Denwah @gingerjia

**Comment by PravallikaPokala** [comment] 2022-12-06 08:37
I am facing the same issue as @Denwah. 
That was working fine last week, but now it states the following on sync:
RichApi.Error: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again. 
Is anyone investigating this?

**Comment by dsmabulage** [comment] 2022-12-06 09:13
I am facing the same issue

![image](https://user-images.githubusercontent.com/99941065/205867278-ae9b1e00-72ee-4de9-ad67-b803fde76f61.png)

My Excel web add-in worked fine yesterday. but now all Excel APIs are failing. on Excel web version. But the Excel desktop working fine

**Comment by gingerjia** [comment] 2022-12-06 09:36
@DSmabulage thanks very much for pointing the platform! I also can repro the issue on Excel online. Report a bug (7261941) to track it. 
We will keep update for the progress! Thanks!

**Comment by jan-claeys** [comment] 2022-12-06 12:59
Until yesterday everything works fine. Now I get this error.

**Comment by szymongdula** [comment] 2022-12-06 13:15
I am facing the same issue.

**Comment by gingerjia** [comment] 2022-12-06 13:48
Thanks all for reporting the issue! We have found the root cause and contact the owner for it. When mitigated, we will update here.

**Comment by gingerjia** [comment] 2022-12-07 00:52
The issue has been mitigated. Please help to double confirm and if still have issue, please let us know. Thanks for reporting the issue and apologize for the impact!

**Comment by akkireddyram** [comment] 2022-12-07 04:44
Thank you all. It's working fine now. Hey @gingerjia please post the root cause if this issue, as we want to update it to our business people

**Comment by gingerjia** [comment] 2022-12-07 12:00
@ramalingeswarakki, this is due to a conflict happened during a new change deployment and we rollback the deployment to mitigate the issue. We are working on adding more protection for the gap found. If you have any good suggestions or new issues, please feel free to share to us. Really appreciated for help to improve our quality and benefit our customers!
