### ISSUE TITLE
addFileAttachmentAsync not working on Office MAC

### ISSUE THREAD

**Issue by ShadowAnonymous** [OfficeDev/office-js#3724] opened 2023-10-03 10:51 UTC
# Provide required information needed to triage your issue
Hello everybody,
Sorry for my English I am a French developer.
I need your help because I am having a problem integrating my solution with the addFileAttachmentAsync functionality on Office Mac because on other Office 365 online platforms or on Windows everything works.

## Your Environment
* Platform Outlook Desktop PC All version > OK
* Platform Outlook 365 Web All Browser > OK
* Platform Outlook 365 Desktop Mac > ERROR
 
## Expected behavior
Despite several attempts, I cannot integrate inline pictures into my message body on Mac.

## Current behavior
Below is an example of testing integration that works everywhere except on Mac.
In the logs I have ID attached element with the status succeded but the pictures are corrupted.
When I analyze the source code of the message received I do not have any inline image in the email.

## Code example below to reproduce
```javascript
insertInlinePictures();

function insertInlinePictures(){
    var file_attachments_arr =
    [
        {
            "name" : "gold_puppy.jpg",
            "url" : "https://picsum.photos/200"
        },
        {
            "name" : "black_puppy.jpg",
            "url" : "https://picsum.photos/200"
        },
        {
            "name" : "white_puppy.jpg",
            "url" : "https://picsum.photos/200"
        }
    ];
    my_add_file_attachments_recursively_helper(file_attachments_arr, 0, "");
}

function my_add_file_attachments_recursively_helper(file_attachment_arr, index, message) {
    if (index < file_attachment_arr.length) {
        var file_attachment_obj = file_attachment_arr[index];
        Office.context.mailbox.item.addFileAttachmentAsync
        (
            file_attachment_obj.url,
            file_attachment_obj.name,
            {
              isInline: true,
              "asyncContext" :
              {
                  "message" : message,
                  "index" : index
              }
            },
            function (asyncResult)
            {
                var next_message = asyncResult.asyncContext.message + "id : " + asyncResult.value + " , " + "status : " + asyncResult.status + "<br>";
                my_add_file_attachments_recursively_helper(file_attachment_arr, asyncResult.asyncContext.index + 1, next_message);
                debug("<div><img height=150 width=150 src='cid:" + file_attachment_obj.name + "'></div>");
            }
        );
    }else{
        debug(message);
    }
}

function debug(message, details) {
  console.log(message, details);
  let log = "<div style=\"background:red;padding:5px;color:white;font-size:14px;\"> " + message + " </div>";
  if( details !== undefined ) log += "<div style=\"background:black;padding:5px;color:white;font-size:14px;\"> " + details + " </div>"
  Office.context.mailbox.item.body.setSelectedDataAsync(log, { coercionType: Office.CoercionType.Html });
}
```

**Comment by DivyaPatidar** [comment] 2023-10-04 08:34
@ShadowAnonymous  Closing this as it's a duplicate of #3717. We will follow up on #3717

**Closed as completed by DivyaPatidar** 2023-10-04 08:34 UTC
Labels: Area: Outlook, Resolution: duplicate
