### ISSUE TITLE
Excel: Data Validation set/get has different behaviours

### ISSUE THREAD

**Issue by webartoli** [OfficeDev/office-js#2128] opened 2021-09-17 14:43 UTC
# Provide required information needed to triage your issue

Trying to set data validation to another cell, data are different.

## Your Environment

* Platform PC_ desktop
* Host: Excel
* Office version number: 2108
* Operating System: Windows 10 - 20H2
* Localization: it_IT
* Region: it_IT
 
## Expected behavior

I want to copy paste data validation infos between cells.

## Current behavior

Validation of 3 elements, become 6 elements, splitted by comma.

## Steps to reproduce

1. Set manually (via ribbon ui) data validation in a cell like this:
`1, Jan;2, Feb;3, Mar` (separator for it_IT is `;`)

2 data validation dropdown in that cell will be like this:
|values|
|-----|
|1, Jan|
|2, Feb|
|3, Mar|

3 try to re-apply the data validation in another cell via office js (snipped below)
4 data validation dropdown will be like this:
|values|
|-----|
|1|
| Jan|
|2|
| Feb|
|3|
| Mar|

## Link to live example(s)

https://gist.github.com/webartoli/e8aaa1922f82d7bda2cc4636405b9472

**Comment by qinliuMSFT** [comment] 2021-09-27 02:25
Hi @webartoli , thanks for logging this issue. Unfortunately the source property in Excel.ListDataValidation is not locale supported, it doesn't support parsing list data validation strings using locale-specific separator like UI does. It's a by design behavior, more details please refer to https://docs.microsoft.com/en-us/javascript/api/excel/excel.listdatavalidation?view=excel-js-preview#source.

**Comment by gingerjia** [comment] 2021-09-27 07:12
@webartoli We are doing a survey to understand the pain points of add-in’s developing experience. Would you mind to help fill this survey https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR5eAlIUFFQFHqE95qTMqQuVURVE4QkZPREoxOEk1TFEySDMyQTc0U0o0Ti4u ? It should take less than 5 minutes and will be supper helpful for us. Thank you!

**Comment by donlvMSFT** [comment] 2022-11-17 03:20
I'd like to close this thread due to the question already answered. Thanks for the discussion!

**Closed as completed by donlvMSFT** 2022-11-17 03:20 UTC
Labels: Area: Excel, Resolution: by design
