### ISSUE TITLE
Excel crashes if add-in deletes named item while another window is active

### ISSUE THREAD

**Issue by tj-aew** [OfficeDev/office-js#2983] opened 2022-11-19 17:13 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

Deleting a named item with code in an add-in crashes Excel hard if the user has switched to a different worksheet.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2209 Build 16.0.15629.20256) 64-bit 
* Operating System: Windows 10
* Browser (if using Office on the web): N/A
 
## Expected behavior

The item is deleted and Excel doesn't crash.

## Current behavior

Excel crashes hard. **All** windows disappear.

## Steps to reproduce

Run the ScriptLab below:

1. Open the ScriptLab snippet in one Excel window
2. Open another Excel window
3. In the snippet window, click the **Delete Named Item** button and switch to the other Excel window

The code will delete the named item in three seconds, at which point Excel will crash.

## Link to live example(s)

Here's a ScriptLab gist:
https://gist.github.com/tj-aew/95d49354cea048ccb450cdf84073effd

For completeness, the HTML:

```html
<div>
	Instructions:
	<ol>
		<li>Open this ScriptLab snippet in one Excel window</li>
		<li>Open another Excel window</li>
		<li>In this window, click the <strong>Delete Named Item</strong> button and switch to the other Excel window
		</li>
	</ol>
	After three seconds, code in this snippet will delete the named item&nbsp;&mdash; and Excel will crash hard.
</div>
<button id="delete-item" class="ms-Button">
    <span class="ms-Button-label">Delete Named Item</span>
</button>
<pre id="log"></pre>
```

Script:

```
const ITEMNAME = "Testing";

const log = $("#log");
const deleteButton = $("#delete-item");
deleteButton.prop("disabled", true);
const deleteButtonText = deleteButton.find("span");
deleteButton.on("click", deleteItem);

tryCatch(createItem);

async function createItem() {
  await Excel.run(async (context) => {
    write("Creating item...");
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    const range = sheet.getRangeByIndexes(0, 0, 1, 1);
    range.load("address");
    const item = sheet.names.getItem(ITEMNAME);
    await context.sync();
    if (item.isNullObject) {
      sheet.names.add(ITEMNAME, range);
    } else {
      write("(Already exists, updating.)");
      item.formula = "=" + range.address;
    }
    await context.sync();
    write("Done creating item.");
    deleteButton.prop("disabled", false);
  });
}

function deleteItem() {
  let counter = 3;
  deleteButton.prop("disabled", true);
  deleteButtonText.text(`${counter}...`);
  const handle = setInterval(() => {
    if (--counter === 0) {
      clearInterval(handle);
      tryCatch(() =>
        Excel.run(async (context) => {
          const sheet = context.workbook.worksheets.getActiveWorksheet();
          const item = sheet.names.getItem(ITEMNAME);
          await context.sync();
          if (item.isNullObject) {
            write("Item not found?!");
          } else {
            write("Deleting item");
            item.delete();
            await context.sync();
          }
        })
      );
    } else {
      deleteButtonText.text(`${counter}...`);
    }
  }, 1000);
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}

function write(text) {
  log.append(text + "\r\n");
}
```

## Context

Aside from making users **very** concerned, we've spent a lot of time trying to come up with workarounds, without luck. So users just worry that when they tell our add-in to do its thing, it may crash. :-( (We've told them what not to do, but...users...)

**Comment by JinghuiMS** [comment] 2022-11-22 10:30
Thanks for reporting this issue. We can repro it locally.
It has been put on our backlog<Bug#7181843> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by tj-aew** [comment] 2024-04-12 10:58
@gergzk  - This is a major bug, it should be fixed, not closed. I know there's a mass closure going on, but there really should be some criteria.

**Comment by gergzk** [comment] 2024-04-12 15:51
@tj-aew - the mass closure is in least-recently-updated order. Feedback from others is helpful in finding the few percent where the closure wasn't appropriate. Thanks!

**Comment by XuanZhouMSFT** [comment] 2024-04-22 11:14
@tj-aew, thanks for your waiting. Could you help to double check if the issue still exists? I see we already release a fix last year. If it still exists, we need to re-triage the issue internally.

**Comment by tj-aew** [comment] 2024-04-22 14:13
@XuanZhouMSFT Do you have a link? There wasn't any notification in this issue of a fix having been released.

The good news is that I just tried to replicate it with the ScriptLab gist I linked in the issue above and Excel didn't crash. Not an exhaustive test, but it was utterly reliable before, so that's a good indicator.

(Just FYI, I had to fix the two places that snippet used `const item = sheet.names.getItem(ITEMNAME);` to use `getItemOrNullObject` instead, not sure how I missed that when reporting the issue originally.)

**Comment by XuanZhouMSFT** [comment] 2024-04-23 05:33
@tj-aew, we don't have a release documentation for this bug. I get the information from internal item tracking. 

The things you mentioned to replace getItem with getItemOrNullObject is a by-design behavior. If the item may does not exist, we suggest using the getItemOrNullObject to avoid the exception.

Glad to hear that the issue is not repro with the ScriptLab gist. I will close the issue as fixed. Please feel free to leave comments if you still have any concerns.

**Closed as completed by XuanZhouMSFT** 2024-04-23 05:33 UTC
Labels: Area: Excel, Type: product bug, Status: in backlog

**Comment by tj-aew** [comment] 2024-04-23 06:07
@XuanZhouMSFT  - The `getItem`/`getItemOrNullObject` wasn't about this bug, it was just a mistake in the snippet that replicated the bug. But yes, again, looks good that it's fixed.
