### ISSUE TITLE
`OfficeRuntime.auth.getAccessToken` hangs indefinitely after a session expires

### ISSUE THREAD

**Issue by damacisaac** [OfficeDev/office-js#3969] opened 2024-01-05 20:54 UTC
We're building an Excel addin. Currently, we're able to authenticate with SSO and start a session. If the addin is left sitting for an hour or two, `OfficeRuntime.auth.getAccessToken` will start hanging indefinitely. 

- How can we detect that this is going to happen?
- Why does this happen? The SSO session in Excel itself continues to work. 
- How should we recover from this?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.79.2 (23112723)
* Operating System: macOS Sonoma 14.1.1
* Browser (if using Office on the web): Chrome
 
## Expected behavior
`OfficeRuntime.auth.getAccessToken()` should not hang

## Current behavior
`OfficeRuntime.auth.getAccessToken()` hangs. It should at least fail with an error. Also if there could be some kind of recovery mechanism apart from refreshing Excel itself that would help. 

## Steps to reproduce
1. Start an SSO session via `OfficeRuntime.auth.getAccessToken`
2. Leave the addon sit for a couple of hours
3. Attempt to call `OfficeRuntime.auth.getAccessToken`, it will hang.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

## Context
Trying to keep a user logged in while using the addon over an extended period of time. With this issue, we need to tell the user to refresh their page periodically.

## Useful logs
I was able to see this uncaught exception in the office.js code, showing that the token is likely expired. That is more or less expected. What's not expected is `OfficeRuntime.auth.getAccessToken` hanging and having no way to recover.

<img width="1392" alt="Screenshot 2024-01-05 at 16 29 23" src="https://github.com/OfficeDev/office-js/assets/3689921/57755dbd-25a4-4702-816f-2da955baa384">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by zhenhuangMSFT** [comment] 2024-01-10 02:30
@mattgeim Hi Matt, could you take a look at this SSO related issue? Thanks!

**Comment by codexeon** [comment] 2024-01-10 07:09
I can repro in Excel Online. You listed Excel Mac in the description, but I assume it is actually Excel Online by the screenshot? We will work on a fix to resolve the Excel Online issue.

**Comment by damacisaac** [comment] 2024-01-10 12:13
Sorry yes, this is Excel Online @codexeon. Edited the description.

**Comment by damacisaac** [comment] 2024-01-25 12:44
@codexeon any progress on this? It's really causing us a lot of trouble. The experience for the end user is quite bad and it's not clear how to avoid it.

**Comment by damacisaac** [comment] 2024-01-29 19:26
@mattgeim @zhenhuangMSFT ?

**Comment by codexeon** [comment] 2024-02-07 21:40
The repro I had was actually related to my own configuration of internal environment, it is likely not the same issue you are running into. I have tried sessions lasting 12 hours and cannot repro in production, and was able to reliably get the access token. We will need more diagnostics to be able to find the root cause and fix. 

1. For the exception in the screenshot, is that an unhandled promise rejection, or just an internal promise that is later handled? That exception should mean that the refresh token is not valid, but it should then get a new refresh token and make a call to https://login.microsoftonline.com/organizations/oauth2/v2.0/token endpoint afterwords. Is there any network trace you could share (endpoints only, or private data redacted for public github issue). Is there an error response to https://login.microsoftonline.com/organizations/oauth2/v2.0/token call that you could share?
2. Is there any other messages you are seeing in console that could be relevant to exceptions, or auth?
3. If you refresh the browser, is it able to acquire a new access token and then fails again after 2 hours?
4. Are there any unique configurations for your tenant or browser you are aware of, that could be relevant to auth? Custom conditional access policies, refresh token lifetimes, etc.
5. Is the tab active, and not throttling DOM timers?
6. My initial thinking is that the localStorage could be in a bad state from a previous session. Does clearing browser cache, or using a different browser resolve the issue? Relevant cache would be in the same domain as sharedauthclient.js shared in the screenshot.

**Comment by damacisaac** [comment] 2024-02-23 13:09
Sorry for the wait. We ended up implementing auth with our own token to get around it so haven't come back to the issue (although we still have to deal with it once our own token expires). I will try to get back to you with a simpler repro, just haven't been able to yet. From what I've seen so far though:
1. That was an unhandled rejecting somewhere in the stack while the error was happening.
2. No other messaging when it happens.
3. Refreshing fixes everything.
4. It's not related to browser or browser config since many users get it. Not aware of special configurations for the tenant.
5. The tab can either be active or in the background.
6. Not sure, need to check.

**Comment by zhenhuangMSFT** [comment] 2024-03-05 05:36
Hi @damacisaac, I am closing the issue. Please reopen if you find anything.

**Closed as completed by zhenhuangMSFT** 2024-03-05 05:36 UTC
Labels: Area: authentication, Area: Excel
