### ISSUE TITLE
ItemChanged event stops coming after a few form manipulations

### ISSUE THREAD

**Issue by aspantel** [OfficeDev/office-js#2143] opened 2021-09-23 12:37 UTC
By its symptoms the issue is very similar to this one: https://github.com/OfficeDev/office-js/issues/1100
It's a pinned Outlook addin mode and after a user works with an html form (a few selects, dropdowns changed) the addin stops receiving ItemChanged event.

Will try to collect more info from our customer... For now we've see a couple of different Outlook versions have the problem, i.e. Build 14326.20238. It's Edge, w/o WebView2

Microsoft Edge Version 93.0.961.52 (Official build) (64-bit)

The re-subscription workaround suggested by issue 1100 does not help.

**Comment by AlexJerabek** [comment] 2021-09-23 17:27
Thanks for reporting this issue @yoxel.

@exextoc, could you please investigate?

**Comment by aspantel** [comment] 2021-09-24 12:18
Microsoft Edge Version 93.0.961.52 (Official build) (64-bit)

**Comment by exextoc** [comment] 2021-09-28 23:15
A possible workaround is to upgrade to a newer versions, so add-ins are rendered using Edge Webview2.  Details about what versions that Webview2 are supported can be found [here](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) and [here](https://developer.microsoft.com/en-us/office/blogs/announcing-webview2-for-office-add-ins-platform/).

**Comment by ghost** [comment] 2021-10-09 00:00
This issue has been automatically marked as stale because it is marked as needing author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**. Thank you for your interest in Office Add-ins!

**Comment by aspantel** [comment] 2021-10-09 00:04
We tried installing Webview2 but it did not help.

**Comment by exextoc** [comment] 2021-10-11 20:42
Another customer had a similar issue on this thread: https://github.com/OfficeDev/office-js/issues/2076

They found a workaround to use WebView2 based on this documentation: https://developer.microsoft.com/en-us/office/blogs/understanding-office-add-ins-runtime/ 
Can you try installing WebView2 following this?

(Make sure to follow the regkey instructions, etc. to ensure that webview2 is used)

**Comment by exextoc** [comment] 2021-10-13 00:55
We haven't been able to repro this locally. Do you have a small simple add-in (or perhaps a scriptlab gist) that can repro the problem consistently that you could share?

**Comment by aspantel** [comment] 2021-10-13 12:08
We'll try to find one but it'll take time as this happens on a client's computer. We have not reproduced this locally either yet.

**Comment by exextoc** [comment] 2021-11-01 22:53
We are closing the bug, but please feel free to re-open if you have additional information or a repro to share.

**Closed as completed by exextoc** 2021-11-01 22:53 UTC
Labels: Area: Outlook, Type: product bug, Needs: author feedback

**Comment by clavx** [comment] 2021-11-05 08:12
I have the same issue.
Edge WebView2 (Chromium) works fine, but Edge WebView (EdgeHTML) does not.

This issue seems to be caused by changing `location.hash` after calling the `addHandlerAsync` method.

You can reproduce this by editing the `App.tsx` file with the code generated by `generator-office`:
``` ts
  componentDidMount() {
    Office.context.mailbox.addHandlerAsync(
      Office.EventType.ItemChanged,
      (args) => {
        console.log(args);
      },
      (result) => {
        console.log(result);
        location.hash = "/test";
      }
    );

    ...
  }
```

Test environment:
- Current Channel: Version 2110 (Build 14527.20234)

**Comment by croicu** [comment] 2021-11-05 22:53
Edge WebView2 (Chromium) should be used by default by Office Version 2110, and it should be installed by Office setup.

**Comment by clavx** [comment] 2021-11-08 08:07
This is the result of the test with the WebView2 runtime uninstalled.

Microsoft 365 Apps in Current Channel:
- Works: Version 2106 (Build 14131.20332) and earlier
- Does not work: Version 2107 (Build 14228.20204) and later

If you recommend the use of Edge WebView2 (Chromium) for Microsoft 365 Apps version 2110 and later, it would be helpful if you could clearly state this in the documentation so that we can notify our customers.

https://docs.microsoft.com/en-us/deployoffice/webview2-install
