### ISSUE TITLE
Selection in drop down menu in Outlook is not working

### ISSUE THREAD

**Issue by AlonEkelund** [OfficeDev/office-js#16] opened 2017-10-13 07:22 UTC
Selection in drop down menu is not working. I have got reported from several customer about a problem in drop down menu on Office Outlook Add-ins. In our case it is iPlanner Pro. We ask some user to test on other ADD-INS and the problem was the same. 

We found that it happens when using two screens. If I disconnect and are only using my laptop all works. 

The problem relates to Outlook Office 365 Add-in where I cannot select any items from a drop down menu using the mouse. If I use the keyboard arrow I am able to select. 

As we know Office Add-isn are using IE. I have been trying to see if there are any special settings in my IE. It is standard. 

Notice! As I recall this was a problem before and it got solved, but now it is back again. 

Please advice

**Comment by hongbo-miao** [comment] 2017-10-14 04:43
Hi @AlonEkelund we will start to invest this soon and return to you. Thanks

**Comment by hongbo-miao** [comment] 2017-10-16 08:01
Hi @AlonEkelund we are investing this now and will return to you if there is an update.

**Comment by AlonEkelund** [comment] 2017-10-16 08:12
Thank you. Please contact me for any informations

**Comment by shawnmcdowell** [comment] 2017-10-16 18:33
While this issue is being investigated, the simplest workaround in the time being is to use the host and add-in on your primary monitor.  If you are not sure which is your primary, open "Change display settings" and click on the numbered displays to see which one is checked as "Make this my main display".  Also, if there were display changes that occurred recently, you may need to sign out and back in.  You will see red text that says "Some apps won't respond to scaling changes until you sign out."

**Comment by AlonEkelund** [comment] 2017-11-17 06:14
Is there any update for this bug? I have several customer waiting and many are complaining about this bug.  As a response for the workaround this is what an enterprise customer is saying 

_"I tried this, the problem is I change my displays often from laptop only to dual monitors to multiple monitors based on the multiple locations I work from and display from.  Same for a lot of our executives as well. "_

I hope for a solution ASAP.

Thanks.

**Comment by hongbo-miao** [comment] 2017-11-17 18:44
Sorry, from one of our team members:

> We tracked this issue down to a bug in IE web control in which mouse hit test is out of whack with non standard DPI.

I will let them reply directly here later.

**Comment by hongbo-miao** [comment] 2017-11-17 19:22
@AlonEkelund Another mail I got today:

> The issue is with the IE control and we are currently blocked until we get help from them. We have a bug logged to them and an email thread with their PM to get them to look at our bug but no time commitment yet. Unfortunately, they’ve already let us now that that they have many other P0/P1  IE bugs that we’re competing with for engineering resources..  This is a critical issue for us for Add-in in Dynamic DPI Office and we will keep pushing them.  We’ll let you know when we get more data from the IE team.

Our own add-in also met this issue, so we will push them to fix it ASAP.
Our side, it is priorty 1 bug.

**Comment by AlonEkelund** [comment] 2017-11-18 09:17
Thank you for your response and for pushing the IE team. I do hope the IE team will prioritize this. It is a big issue and are affecting thousand and thousand off users around world. Actually it is not only the drop downlist. This IE bug is affecting add-ins in many other ways. The size/dimension is just changing randomly as you use the Add-in. This means sometimes not all content of the Add-in is visible. 

And yes this is effecting ALL add-ins. 

Thank you.

**Comment by cyhong** [comment] 2017-11-22 02:43
@AlonEkelund 
Can you share the build number of Office affecting the size/scaling issue specifically? You can find it from File | Account | About. We made changes of size/scaling issue regarding dynamic dpi and would like to know if it addressed that or not.

**Comment by AlonEkelund** [comment] 2017-11-22 08:52
Hi cyhong. Microsoft Office ProPlus Version 1711 - build 8730.2074 - (16.0.8730.2046) I have tested on a windows 10 pc on Outlook and Excel. It looks like the scaling issue has been resolved. I would like to test on my MAC as well and get back to you. The dropdown is still a problem.

**Comment by cyhong** [comment] 2017-11-22 21:35
AlonEkelund, thanks for the info and verification the scaling issue. As you mentioned that the build has the change of scaling fix. The hittest issue like the dropdown is still occurring though.

**Comment by AlonEkelund** [comment] 2018-01-09 12:10
Any status update??? when can we expect that selection in drop down menu will wokr??? @cyhong @Hongbo-Miao

**Comment by hongbo-miao** [comment] 2018-01-09 18:58
@AlonEkelund Sorry, I don't have any timeline. But I will keep asking.

**Comment by AlonEkelund** [comment] 2018-01-10 07:42
@Hongbo-Miao This is a problem. You know that we are being asked to use the Fabric UI and HTML 5. Changing this will require a lot of development and we will not be using what Microsoft recommend. There must be something we can do to push this forward. It must be a problem for many other.

**Comment by Hongbo-Miao** [comment] 2018-01-10 07:47
@AlonEkelund oh yeah I know, I will ask another team member who has more details to reply here directly.

**Comment by Hongbo-Miao** [comment] 2018-01-10 07:50
@AlonEkelund send me a mail Hongbo.Miao at microsoft.com, I can add in the thread to know what is going on.

**Comment by hongbo-miao** [comment] 2018-01-10 08:04
@AlonEkelund Ok, got your mail. I will add your in thread.

**Comment by stephenfshen** [comment] 2018-01-11 00:02
Glad to see this issue confirmed by the DEV team, thans @AlonEkelund  and @Hongbo-Miao . I've got the exact same issue that stopped me pushing out my add-in to PROD.  Would be nice if @Hongbo-Miao  can share the details of update.

**Comment by hongbo-miao** [comment] 2018-01-11 07:11
Hi @stephenfshen I will post here if I have more update. The team is actively trying to solve this issue now.

**Comment by AlonEkelund** [comment] 2018-01-24 06:22
Hi any update? I just got a new complaint from a potential customer. I do hope for a solution soon, I am loosing cases. 

Thanks

**Comment by hongbo-miao** [comment] 2018-01-24 06:59
hi @AlonEkelund contact Jeremy Yoo directly through email might help.

**Comment by hongbo-miao** [comment] 2018-01-24 07:38
@AlonEkelund Sorry for cannot help move this forward, I won't have any update from our team for this issue in the future. Please ask Jeremy Yoo for future update. You have his mail.

**Comment by AlonEkelund** [comment] 2018-01-24 07:42
@Hongbo-Miao Hongbo thank you I will

**Comment by laurence73** [comment] 2018-03-01 10:16
We are experiencing the exact same behaviour on latest Outlook Desktop (Office 365)  - add-in cannot select item from Dropdown list unless using key buttons if on non-standard DPI monitor. Did this ever get fixed?

**Comment by AlonEkelund** [comment] 2018-03-01 11:25
Still not fixed. I know the IE team is currently working on it. I hope :-)

**Comment by laurence73** [comment] 2018-03-01 11:31
yeah hope so too - driving more than a couple of our clients up the wall...thanks for reply

**Comment by shawnmcdowell** [comment] 2018-03-14 23:50
I wanted to give an update on this thread.  We have identified the root cause of the issue.  We do not have an ETA at this point, but understand its importance and are continuing to work towards a resolution.  Thanks for your patience.

**Comment by AlonEkelund** [comment] 2018-03-17 09:02
Thank you for the update. And thank you for recognizing the importance of this. I do hope for a solutions soon as we are many that are waiting for it :-)

**Comment by shawnmcdowell** [comment] 2018-06-22 17:43
Thanks for your patience, this issue has been fixed in Windows.  Please click the Check for updates button in the Windows Update settings app to pick up this fix.

**Comment by laurence73** [comment] 2018-06-22 17:45
Thanks Shawn! appreciate you guys sticking with it...

**Closed as completed** 2018-06-22 18:48 UTC
Labels: Area: Outlook, Type: product bug

**Comment by Pentao** [comment] 2018-10-24 02:31
Hi all, 
Is there any know workaround? Start/stop any particular services? Rebooting the laptop is not ideal.
thanks,

**Comment by AlonEkelund** [comment] 2018-10-24 06:18
Hi Pentao 
If you are asking about the drop down issue? It has been fixed. It is working on my end and I havn't got any reports from customers that it don't.

**Comment by cc8080** [comment] 2019-04-18 16:41
Please give more details about where to find the fix. Which version/build/etc.? Thanks!

**Comment by AlonEkelund** [comment] 2019-04-19 06:51
Hi cc8080 I am not sure of the version, but it was fixed along time a go. I have my Office from O365 and running the updates automatically. I cannot remember exactly when it was fixed, but around July or August last year.
