### ISSUE TITLE
In Contextual office addins in Outlook specific word not gets highlighted properly

### ISSUE THREAD

**Issue by avgode** [OfficeDev/office-js#1265] opened 2020-07-07 15:35 UTC
## Expected Behavior

When using contextual addins in Outlook, I wanted to highlight few words like ill, holiday, leave and wrote regex as **\b(\r\n|\r|\n)|(leave|holiday|vacation|sick|ill|sickness|poorly|absent|absence)|(\r\n|\r|\n)\b**

So if  the message contains below text...
**Hi I'm still on holiday.**

It should only highlight **Holiday**
## Current Behavior

When using contextual addins in Outlook, using regex as **\b(\r\n|\r|\n)|(leave|holiday|vacation|sick|ill|sickness|poorly|absent|absence)|(\r\n|\r|\n)\b** it highlights **ill** word in st**ill** and **holiday** in **holiday**ing which is not expected. I have tried various ways but result is same and I think regex written by me is straight forward and its working on online third-party regex tools.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook, Outlook on Web
* Office version number: ______
* Operating System: Windows 10
* Browser (if using Office Online): Chrome, Chromium

## Useful logs

- [ ] Console errors
- [ ] Screenshots
![image](https://user-images.githubusercontent.com/15957229/86805404-c3606a00-c06f-11ea-8ada-0113aef204ab.png)

- [ ] Test file (if only happens on a particular file)

**Comment by lindalu-MSFT** [comment] 2020-07-09 01:03
@avgode Is this a dupe of the other issue?

**Comment by lindalu-MSFT** [comment] 2020-07-09 01:04
This is a dupe of [https://github.com/OfficeDev/office-js/issues/1266](https://github.com/OfficeDev/office-js/issues/1266)

**Comment by avgode** [comment] 2020-07-09 05:06
Why you closed this issue. 1266 is different issue which talks about highlight not happening on forwarded and replied mails in web outlook. This issue talks about some words highlighted wrongly. Please reopen this issue.

**Comment by avgode** [comment] 2020-07-09 05:07
> @avgode Is this a dupe of the other issue?

This is not dupe of 1266

**Comment by avgode** [comment] 2020-07-09 05:11
Please reopen the issue(1265) as this is different issue from 1266. This issue talks about words getting highlighted in improperly.
And 1266 talks about words not getting highlighted in forward and reply mails in outlook on web.

Cheers,
Amey Gode

On 09-Jul-2020, at 6:34 AM, Linda Lu Cannon <notifications@github.com> wrote:

﻿

Closed #1265<https://github.com/OfficeDev/office-js/issues/1265>.

**Comment by exextoc** [comment] 2020-07-12 00:45
Re-opening this issue because it is different from #1266

**Comment by exextoc** [comment] 2020-07-12 03:16
Closing this issue since #1271 was created to replace this one.

**Closed as completed by exextoc** 2020-07-12 03:16 UTC
Labels: Needs: triage :mag:
