### ISSUE TITLE
Calls to mailbox.getCallbackTokenAsync and notificationMessages.replaceAsync sometimes fail on Outlook Win32 with permissions error.

### ISSUE THREAD

**Issue by davidfishlock** [OfficeDev/office-js#1911] opened 2021-06-07 19:19 UTC
Our add-in runs within the read item view, which means that it should implicitly have the necessary permissions to call both [getCallbackTokenAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#getCallbackTokenAsync_options__callback_) and [notificationMessages.replaceAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.notificationmessages?view=outlook-js-preview#removeAsync_key__callback_) as it has `ReadItem` permissions.

In Sentry, we see errors reported in some instances when we call these two methods:

> Elevated permission is required to call the method: 'mailbox.getCallbackTokenAsync'.

> Elevated permission is required to call the method: 'notificationMessages.replaceAsync'.

Our add-in runs on Mac, Windows and OWA, but we only see errors of this nature being thrown by `lib/1.1/hosted/outlook-win32-16.02`, so it seems to be isolated to the Outlook Windows desktop client SDK.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.02
* Operating System: Windows
 
## Expected behavior
Calls to these methods should work without error where the add-in has the necessary permissions.

## Steps to reproduce
I have been unable to reproduce this issue locally, I'm receiving this as live user errors reported via our Sentry instance.

## Useful logs
```
Error: Elevated permission is required to call the method: 'mailbox.getCallbackTokenAsync'.
  at L(/lib/1.1/hosted/outlook-win32-16.02.js:19:184430)
  at Pe(/lib/1.1/hosted/outlook-win32-16.02.js:19:201593)
```

```
Error: Elevated permission is required to call the method: 'notificationMessages.replaceAsync'.
  at G(/lib/1.1/hosted/outlook-win32-16.02.js:20:187602)
  at Lt(/lib/1.1/hosted/outlook-win32-16.02.js:20:216096)
```

**Comment by exextoc** [comment] 2021-06-08 23:36
What version of Outlook Windows desktop client are you on?

**Comment by davidfishlock** [comment] 2021-06-10 14:13
@exextoc As I mentioned above I am not reproducing this locally, I see it in Sentry reports from users.

I see errors coming from versions `16.0.13903.10000` and more recently `16.0.14021.10000` of `outlook-win32-16.02.js`.

**Comment by exextoc** [comment] 2021-06-10 18:28
How often are the errors being reported? Is it consistently happening across certain users?
Is your add-in using pinnable task pane and is it self-hosted?

**Comment by davidfishlock** [comment] 2021-06-10 18:44
I see about 10 reports of this per-week, in some cases I see it reported multiple times for the same user but generally a different user on each report.

Our add-in is not using a pinnable task pane, it closes when a user switches to a different message or we have finished the workflow on the current item.

I'm not sure what you mean by a self-hosted add-in, we are hosting the static html/js files on our own web service. The add-in manifest and installation is handled via Outlook as it is available in the Outlook store / Appsource.

**Comment by exextoc** [comment] 2021-06-10 21:22
Just to clarify, are you also self-hosting Office.js or Outlook.js files? (ie https://appsforoffice.microsoft.com/lib/1/hosted/Office.js)

**Comment by davidfishlock** [comment] 2021-06-11 12:25
No, we include them via a script tag in the html header:
```
<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
```

**Comment by exextoc** [comment] 2021-06-16 23:48
We have not been able to reproduce issue.  Do you have more specific repro steps here?  Do you see this issue with other APIs?  Just to make sure, are the calls to mailbox.getCallbackTokenAsync and notificationMessages.replaceAsync made after Office.initialize /Office.onReady (https://docs.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in)?

**Comment by davidfishlock** [comment] 2021-06-21 13:08
@exextoc unfortunately I do not have more specific steps as I cannot reproduce the issue myself, I only see this coming in regularly from user Sentry reports.

I currently only see this permissions error from these APIs. All calls to these APIs are issued after Office.initialize.

**Comment by exextoc** [comment] 2021-06-22 00:07
Unfortunately this is really hard for us to follow up on without repro steps, any additional information that you would have here (no matter how small may be helpful in figuring out the repro conditions). 

Do you make calls to other APIs after getting errors from these? (and I assume they're succeeding, since you only mention errors). If so which APIs are succeeding?  

It's somewhat confusing, as errors like this, if they happen should be more widespread. (i.e. if you get this error once, you would get them for almost all api calls, on that instance of the add-in). 

At this point, your symptoms seem to imply a new issue that we don't have much traction on, so as mentioned, any additional information would be helpful

**Comment by davidfishlock** [comment] 2021-06-22 10:42
> Do you make calls to other APIs after getting errors from these?

I don't think there are scenarios where we would go on to continue calling other APIs. As if we are unable to get a REST token then this is pretty much a fatal error for our use-case.

In the same session of the add-in though I don't see any issues from earlier accessing values from `Office.context.mailbox.item` or calling `Office.context.roamingSettings.get()`.

I'm not sure if this helps much but I've expanded the areas of this stack that are applicable to the client SDK.

![image](https://user-images.githubusercontent.com/42198746/122910886-b8582580-d324-11eb-8f72-78c64479acad.png)

You can see that `Office.initialize` has already run, which I have highlighted. But given that this issue is only contained to Windows desktop SDK and not appearing on other platforms it would be unlikely this is due to execution flow as that should be applicable to all.

**Comment by exextoc** [comment] 2021-06-24 01:17
It may be interesting if the failures are only coming from certain versions of Outlook. Earlier you had reported on the version of outlook-win32-16.02.js, but by any chance are you logging: 

Office.context.mailbox.diagnostics.hostVersion 

And can report on the versions that are seeing the error? 

Also what type of add-in are you? An AppCommand Taskpane? a UILess Execute Function? Contextual? 

Based on the stack you collected, the JS code believes that your add-in is running at Restricted permission level, and not ReadItem (or higher). 

By any chance did you have versions of the manifest (or test versions) where you were Restricted at some point, and maybe those users have not updated? (I realize this is highly unlikely, but thought I would ask)

**Comment by davidfishlock** [comment] 2021-06-24 12:37
> are you logging: Office.context.mailbox.diagnostics.hostVersion

I'm not currently capturing this information on these errors but will add some further logging.

> what type of add-in are you?

I am seeing most of these errors from a Taskpane but also a UILess function. Both are launched from `MessageReadCommandSurface`.

Our manifest has always declared `ReadWriteItem` permissions so should have always had access to both of these APIs.

**Comment by davidfishlock** [comment] 2021-06-30 18:23
@exextoc I added some logging of hostVersion. I've only had a few reports with this additional information so far but all the ones I have seen are showing version `16.0.14026.20308`.

**Comment by davidfishlock** [comment] 2021-07-08 13:11
@exextoc following up here, I am seeing reports of these permissions issues from two different versions of the Windows desktop client: `16.0.14026.20308` and `16.0.14131.20278`

**Comment by exextoc** [comment] 2021-07-08 23:38
Thank you for the additional builds.

To clarify, are you using only a taskpane add-in (not contextual, not autorun, no pinning)?

Are you using shared folders/delegate access? Are you using this add-in on signed or encrypted mails?

**Comment by davidfishlock** [comment] 2021-07-13 12:10
@exextoc we are using a taskpane and a UI-less function and see the issues reported in both. We do not declare support for shared folders in the manifest. 

The add-in is published in the store so users are free to launch it on any email that the add-in framework supports, we don't declare any support for signed / encrypted emails specifically but if your framework supports them then I guess this is possible.

**Comment by exextoc** [comment] 2021-07-14 23:57
@davidfishlock unfortunately without a repro it's really difficult for us to pin point the issue here. By any chance do you know if and when your users hit this, if it's consistent for all items or just intermittent within the same session of Outlook. Also, when this error is hit in the add-in, is there some sort of UI/error message that is shown to the user? If so, it might be worth asking if they've seen a pattern in terms of their use/repro steps when they hit this error or if it's always a specific item that this issue hits on or things along those lines. It may help provide further insight into the issue/to get some repro steps for us to try. Also, when they hit this error, does closing and re-opening the taskpane on the same item fix the issue? Also, may sound a bit out in the wild, but when you hit this error, can you check if you have anything in Office.context.mailbox.item.subject/item.to/item.cc and Office.context.mailbox.restUrl property or are all empty/missing. For privacy reasons it may be worth simply logging a bool if value exists or not when this error is hit along with other details you're already logging.

**Comment by davidfishlock** [comment] 2021-07-15 13:10
@exextoc Unfortunately I won't be able to get this information unless I have a direct report from a user that I can tie up to this.

Do you guys have logging set up when errors like this are hit? It seems very clear that this is a client / SDK issue given that it consistently only affects one of the client SDKs. So it seems unlikely to be specifically related to a particular usage.

**Comment by exextoc** [comment] 2021-07-19 14:20
@davidfishlock Is it possible to at least log the additional information requested above when the calls fail with this error? These should all be achievable through the JS side of the add-in. This will help us narrow down the issue to either Office JS or the client side.

**Comment by davidfishlock** [comment] 2021-07-20 12:24
@exextoc what additional information has been requested that has not been provided? 

It was requested that we log `Office.context.mailbox.diagnostics.hostVersion`, and that information was provided here 2-3 weeks ago. Was there something else that I missed?

**Comment by exextoc** [comment] 2021-07-21 23:18
The additional information that we were referring to is what we mentioned in this previous reply and not the original log you shared

> Also, may sound a bit out in the wild, but when you hit this error, can you check if you have anything in Office.context.mailbox.item.subject/item.to/item.cc and Office.context.mailbox.restUrl property or are all empty/missing. For privacy reasons it may be worth simply logging a bool if value exists or not when this error is hit along with other details you're already logging.

This should be achievable through the JS side of the add-in, can you try this and share with us the result?

**Comment by davidfishlock** [comment] 2021-07-22 16:57
Ok, I'll add some further logging of this.

**Comment by davidfishlock** [comment] 2021-07-30 13:49
@exextoc it seems that when this issue occurs, there is nothing returned by `Office.context.mailbox.item.subject` or `Office.context.mailbox.restUrl` either.

**Comment by exextoc** [comment] 2021-08-09 18:25
Thanks for the information. One thing to mention is that if an add-in is uninstalled while the taskpane is open, maybe the permissions from the add-in would be reset, and then the issue would repro after changing items.

**Comment by exextoc** [comment] 2021-08-10 01:01
To explain a bit more about the questions we have asked so far, the error you are hitting would be correct if your addin permission is Restricted. This is clearly not the case, since you have other successful users and your addin is in the store. We suspect the issue is that part of the framework is somehow marking the addin as having Restricted permission incorrectly.  Your help to get the results from item.subject/mailbox.restUrl confirms this suspicion. At the same time, because Restricted addin is a legitimate case, without a local repro, it is difficult to pinpoint the root cause. The product team expects additional work/logging is necessary to help figure out what's going on.

Your report is the only one we have so far (with clear signal that the addin is not Restricted and in a state that APIs should be available) and knowing the impact will help us prioritize the additional work/logging. Earlier you noted about 10 reports of this issue a week. What's the size of your user base?   In addition to the logging from your addin, have users directly reported issues with using your addin? If there are direct user reports or if potentially a significant percentage of user is hitting this, it would help the team prioritize the work.

**Comment by davidfishlock** [comment] 2021-08-11 14:40
@exextoc The add-in currently has around 3000 unique users per week, so the overall percentage of users that are encountering it appears low. On the other hand, if the add-in is being refused permissions entirely this may be the root cause of some other error reports beyond the calls to the two methods originally mentioned.

Where it does affect a user it seems they can encounter it several times in a row as I see consecutive error reports from the same user.

Unfortunately I've not yet had a report from a user that I've been able to correlate to this issue specifically.

**Comment by exextoc** [comment] 2021-08-17 22:59
We can continue looking at this at our end, but we are having difficulty in making headway here. 

When this happens, a restart of Outlook may fix the issue? If your code detects this is happening, bringing up this suggestion to the end user could be helpful (I realize this is not an ideal solution)

**Comment by exextoc** [comment] 2021-09-03 21:38
We don't have a solid repro at this point so we will investigate/add more detailed error logs to find the problem and fix it. If you can identify a user condition or have a solid repro please feel free to comment here again that will help our investigation and get sooner to the issue.

**Closed as completed by exextoc** 2021-09-03 21:38 UTC
Labels: Area: Outlook, Type: product bug

**Comment by illing2005** [comment] 2024-02-21 19:24
@exextoc and @davidfishlock, did you ever find a solution for this?
We are running into the same issue with our Add-In. 

For most of our users it works find but we see a handful of errors in Sentry every week:
```
Error: Elevated permission is required to call the method: 'mailbox.getUserIdentityToken'.
```

**Comment by davidfishlock** [comment] 2024-02-22 10:12
@illing2005 no I think we provided all the context that we could from our side and were relying on the Outlook team adding some further logging to try and identify the root cause. 

I'm no longer involved with the project but as far as I am aware there was no resolution found from the add-in side as it just seemed to have its permissions revoked for no obvious reason.

You could maybe try reopening this and see if the logging was ever added, but it seems unlikely given the Microsoft policy seems to be to just close any issues after 7 days without any action or resolution.
