### ISSUE TITLE
Add-in Word/Excel Online: displayDialogAsync does not work “NotHttps”

### ISSUE THREAD

**Issue by Petryxasport** [OfficeDev/office-js#1845] opened 2021-05-05 16:15 UTC
Our word add-in uses function "displayDialogAsync" and everything was good, then this function was broken for a Word Online in Chrome browser. 

Our product in life and this is critical issue. Could you please fix and advice a temporary workaround? 

**Example of code:**
`Office.context.ui.displayDialogAsync(url, { height: 80, width: 25, displayInIframe: true }, dialogCallback);`

## Expected Behavior
Add-in has to open pop-up.

## Current Behavior
Add-in does not open a pop-up and Chrome catch the error. (see screenshot)

## Details
The same code executes for Excel add-in and for Excel this function is working fine. Seems issue in the word-web-16.00.js file after some updates.
Also we tried to use different parameters and host. 
Parameter url has the same domain as add-in.

## Environment

* Office on the Web
* Word
* O365
* Windows 10
* Chrome

## Useful logs
![image](https://user-images.githubusercontent.com/17165899/117173263-45770780-add5-11eb-849f-6f172f0002b9.png)

**Comment by lliu113** [comment] 2021-05-12 19:34
@Petryxasport - sorry you're hitting this issue! Do you see the same error if displayInIframe: false?

**Comment by lliu113** [comment] 2021-05-12 19:40
Internal bug number: 5106779

**Comment by Petryxasport** [comment] 2021-05-13 08:28
@lliu113 Yes, we have  played with different options and url etc.
![image](https://user-images.githubusercontent.com/17165899/118100865-a018f080-b3df-11eb-8415-517b0d16d6c3.png)

**Comment by Petryxasport** [comment] 2021-05-13 08:39
> Internal bug number: 5106779

Pop-up is critical for our product. Could you please provide the plan of fix?

**Comment by Petryxasport** [comment] 2021-05-13 09:28
> > Internal bug number: 5106779
> 
> Pop-up is critical for our product. Could you please provide the plan of fix?

The same issue came for Excel as well.  A week ago this worked.
![image](https://user-images.githubusercontent.com/17165899/118106720-934bcb00-b3e6-11eb-8b70-a60dd075d861.png)

**Comment by jayrathi** [comment] 2021-05-14 06:57
The error "NotHttps" tells that the url being passed in to displayDialogAsync is not https. Can you check the url and confirm? Thanks.

**Comment by Petryxasport** [comment] 2021-05-14 13:04
> The error "NotHttps" tells that the url being passed in to displayDialogAsync is not https. Can you check the url and confirm? Thanks.

Please see the first screenshot in my post and below:
![image](https://user-images.githubusercontent.com/17165899/118274667-172cb280-b4ce-11eb-8033-55960d938326.png)

**Comment by Petryxasport** [comment] 2021-05-21 13:29
> The error "NotHttps" tells that the url being passed in to displayDialogAsync is not https. Can you check the url and confirm? Thanks.

Any updates? Can you reproduce the issue?

**Comment by davidtauriello** [comment] 2021-05-26 18:19
I'm also having this issue with our Excel add-in on the web.

Issue is not confined to Chrome - not working in Edge, either

![image](https://user-images.githubusercontent.com/11542574/119711673-caca6680-be2d-11eb-8b71-36fd60dc223f.png)


https://stackoverflow.com/questions/67712731/timing-for-fix-to-broken-excel-web-16-00-js

**Comment by Rick-Kirkham** [comment] 2021-05-26 21:58
I'm trying to get an update on this issue internally. In the meantime, does this happen on a localhost domain or only on the azurewebsites.net domain?

**Comment by davidtauriello** [comment] 2021-05-26 22:10
Thanks, Rick - it’s in GitHub (production) and Azure

Search the office store for ‘XBRL filed data’ in excel and install, then try to login via web excel. Login window doesn’t appear.

**Comment by davidtauriello** [comment] 2021-05-27 20:24
Hi @Rick-Kirkham and @lliu113 - any updates on the status of **Internal bug number: 5106779** - ?

We're in the same situation as @Petryxasport and anyone else using a popup for login: _our add-in is currently useless on the web_ (so, school computing labs and other 'public' facilities).

Please let me know timing for a fix - thanks.

https://appsource.microsoft.com/en-us/product/office/WA200002591

**Comment by lliu113** [comment] 2021-05-28 17:09
@davidtauriello , @Petryxasport - thanks for your patience with us on this. I know this is frustrating as your add-ins are failing. Our engineering team is still investigating and unfortunately we don't have any updates to share right now.  

Will keep everyone updated as we know more.

**Comment by iotataru** [comment] 2021-05-28 22:08
Hi everyone! I took a look at this and there seems to be calls to http://api.xbrl.us which is not using https. Please get a valid cert and use https for api calls in production.

![image](https://user-images.githubusercontent.com/63681485/120046173-7a3a4100-bfc6-11eb-8065-75211b3f8d72.png)

**Comment by davidtauriello** [comment] 2021-05-29 12:46
thanks, @iotataru - I updated our add-in manifest to remove http: domain references, tested and confirm this fix works in our circumstance.  Is there documentation I can point our dev to regarding the change - ? - asking because the add-in worked with http: in the manifest until sometime earlier this month.

@marcward - FYI, please see the note regarding 'valid cert' (? not sure this is an actionable item, though, as I think you have this in hand already).

**Comment by iotataru** [comment] 2021-06-01 07:31
Awesome glad to hear that! We are trying to enforce 'https' across add-ins on all platforms in order to enhance security. You likely saw a gap caused by different deployment timelines.

**Comment by iotataru** [comment] 2021-06-01 07:32
@lliu113 please close the issue

**Closed as completed** 2021-06-01 18:40 UTC
Labels: Needs: attention :wave:, Area: Word, Area: add-in UI, Resolution: question answered

**Comment by Petryxasport** [comment] 2021-06-04 14:23
Thank you! Updating of manifest works fine!
