### ISSUE TITLE
Calculation option in Formulas tab does not affect to calculation of custom formulas when opening the workbook

### ISSUE THREAD

**Issue by leybal** [OfficeDev/office-js#1567] opened 2020-12-29 16:21 UTC
When we set Calculation options to Automatic in Excel it should run the calculation of custom formulas after opening the workbook. But currently changing Calculation options does not lead to recalculation of custom formulas when we opening the workbook.
If we work with Streaming custom functions or add Volatile values in custom functions then changing Calculation options affects recalculation of these formulas.
Please take a look at screenshots that were made after the workbook opening:
1. custom functions with Automatic Calculation option [link](https://drive.google.com/file/d/1A6dT03i8io7-TFCM1vI6MNF643JmLnZC/view?usp=sharing)
2. custom functions with Manual Calculation option [link](https://drive.google.com/file/d/1FCpDnzdx_8AyYY3yTW5MeQv07fnbnaDT/view?usp=sharing)
3. streaming custom functions with Automatic Calculation option [link](https://drive.google.com/file/d/14W7nOWXiQRRinGmr7d_1b0i8o4CgURXW/view?usp=sharing)
4. streaming custom functions with Manual Calculation option [link](https://drive.google.com/file/d/1JryqEShQy6VHmF7lQ96wVdc6NQqSUuPy/view?usp=sharing)

File session ID:  b878aeac-8e9e-4204-8a8f-63da80e3d858

## Expected Behavior

Changing Calculation options to Automatic should run the calculation of custom formulas after opening the workbook.

## Current Behavior

Changing Calculation options to Automatic does not lead to recalculation of custom formulas when we opening the workbook.

## Steps to Reproduce, or Live Example
1. Open new workbook and open Script Lab tab.
2. Press Functions button on ribbon.
3. Add SPHEREVOLUME custom function in a cell
4. Set Calculation options to Automatic in Formulas tab.
4. Reload browser page and see that SPHEREVOLUME custom function don't start recalculation.

If we do same steps with Streaming custom functions such as INCREMENT that will see recalculation process.

## Context

We want to start recalculating custom formulas when a user opening the workbook. But custom formulas do not  start recalculating with Automatic Calculation options.

## Your Environment

* Platform: Office on the web
* Host: Excel
* Office version number: 16.0.13622.35911
* Operating System: Windows 10, x64
* Browser: Google Chrome 87.0.4280.88

**Comment by xiaochunms** [comment] 2020-12-30 02:29
@leybal Thanks to reach us. According to your description, i.e. "If we do same steps with Streaming custom functions such as INCREMENT that will see recalculation process." I'd say the behavior is expected. By setting the option to "Automatic", when loading a workbook, for a normal custom functions, i.e. not a streaming or a volatile one, if there is already a right value returned, the recalculation will not be triggered. This can reduce the unnecessary calculation for Excel.

If you want to trigger the calculation when loading workbook, you may can [config your add-in to use Shared Runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime) and follow [the tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/run-code-on-document-open) to call Javascript Calculate RichApi, [Application.calculate](https://docs.microsoft.com/en-us/javascript/api/excel/excel.application?view=excel-js-preview#calculate_calculationType_) or [worksheet.calculate](https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheet?view=excel-js-preview#calculate_markAllDirty_) or [range.calculate](https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#calculate__) on document initialization.

**Comment by leybal** [comment] 2020-12-30 09:09
@xiaochunms Thanks for the answer.
Previously, we created the [issue](https://github.com/OfficeDev/office-js/issues/1542#issuecomment-746843739), setStartupBehavior(Office.StartupBehavior.load) results in the ADD-IN ERROR when opening saved workbook. Are there any updates on this issue?
Maybe there is another way to start recalculating normal custom functions when user opening a workbook?

**Comment by keyur32** [comment] 2021-01-07 22:39
Hi @leybal,  to allow functions to recalculate on workbook open, you'll want to declare the specific functions as volatile. (note: doing this will cause the formulas to recalculate even not outside of open): https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-volatile

Willl check with @davidchesnut  on the previously created issue and team will reply back on to that specific github issue. Thanks.

**Comment by lindalu-MSFT** [comment] 2021-03-18 22:31
Closing due to issue is by design/has workaround. If further assistance is needed, please reactive! Thanks, linda

**Closed as completed by lindalu-MSFT** 2021-03-18 22:31 UTC
Labels: Area: Excel, Resolution: by design, Resolution: question answered
