### ISSUE TITLE
IsSetSupported not reliable

### ISSUE THREAD

**Issue by bdentino** [OfficeDev/office-js#1031] opened 2020-03-08 19:28 UTC
## Expected Behavior

I expect `Office.context.requirements.isSetSupported("CustomFunctionsRuntime", "1.1")` to return `false` on Excel for Mac, v16.36, running with Retail License 2019.

## Current Behavior

`Office.context.requirements.isSetSupported("CustomFunctionsRuntime", "1.1")` returns `true`, even though custom functions are not supported in this environment.

Potentially related, `Office.context.requirements.isSetSupported("RibbonApi", "1.1")` also returns `true`, even though Mac support for this API is [not available yet](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/ribbon-api-requirement-sets).

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/bdentino/d590323037a77321de56f1fe19fb2aed

## Context

I am trying to launch an obvious alert to users when the add-in is installed in an unsupported environment that some features may not be supported, so that we can direct them to a legacy version of our add-in (VBA) that will work in their environment. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: *Mac*
* Host [Excel, Word, PowerPoint, etc.]: *Excel*
* Office version number: *16.36 (Retail License)*
* Operating System: *MacOS Catalina 10.15.3*
* Browser (if using Office Online): *N/A*

**Comment by RuoyingLiang** [comment] 2020-03-10 00:52
Thanks for raising this. Currently, the requirement set is check based on build number. As custom function and Ribbon API also restrict only support O365 subscriber, so the requirement set return true but the feature doesn't support for the license you are testing. We are proactively working on solving that. Will update here once we have further progress.

**Comment by RuoyingLiang** [comment] 2020-03-12 02:10
@bdentino, for Ribbon API we've just rlease preview yesterday. Now it's available to Mac and without extra license check. Could you help to try again? Please let us know if you still cannot use Ribbon API.

**Comment by keyur32** [comment] 2020-03-16 19:56
@bdentino - There was some additional logic that custom functions specifically had. Team is looking to relax or update that.

For the Ribbon API preview, this follows the same behavior of other apis. The check is just specific to custom functions.  I think @RuoyingLiang  will follow up once we have an update on the custom functions check.

Thanks!

**Comment by bdentino** [comment] 2020-06-02 20:17
@keyur32 Thanks for the info. Does this mean that the team is considering expanding availability of Custom Functions to 2019 users with a perpetual license?

**Comment by rickygarg** [comment] 2021-05-03 13:55
Still able to reproduce the original issue:

```Office.context.requirements.isSetSupported("CustomFunctionsRuntime", "1.1") returns true, even though custom functions are not supported in this environment.```

Alternatively, it would be nice if custom functions are made available to users with perpetual license, as done for Ribbon API earlier. @keyur32

**Comment by keyur32** [comment] 2021-05-03 15:06
assigning to @grangeryy to take a look.

@rickygarg  - we are planning to make custom functions (and Excel Dynamic Arrays) available in the next version of perpetual version of Office, coming later this year. More details on what APIs will be supported in that version are here: https://docs.microsoft.com/en-us/deployoffice/office2021/overview-ltsc-preview#office-add-ins-javascript-apis

**Comment by rickygarg** [comment] 2021-05-12 06:24
Thanks @keyur32 , looking forward to the next version of Office. Meanwhile, if isSetSupported could be made to work for custom functions, it'd be super helpful @grangeryy !

**Closed as completed** 2021-05-19 11:00 UTC
Labels: Area: Excel, Needs: author feedback, Status: fixed

**Comment by thechrisoshow** [comment] 2025-02-06 16:11
This is still an issue. 

One of our users is using **LTSC Standard for Mac 2021 (Version 16.93 build 25011212)** - however the Word API after 1.4 does not work (and this led to a lot of frustrating time trying to debug, because isSetSupported returned true).
