### ISSUE TITLE
Neither Office.initialize=... nor Office.onReady() is invoked in Outlook desktop app (Version 2406 Build 17726.20160) on Windows

### ISSUE THREAD

**Issue by junhuiluosalesforce** [OfficeDev/office-js#4735] opened 2024-07-30 18:39 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop_____
* Host [Excel, Word, PowerPoint, etc.]: __Outlook____
* Office version number: __Version 2406 Build 17726.20160____
* Operating System: __Windows____
* Browser (if using Office on the web): ______
 
## Expected behavior

Office.initialize assignment and Office.onReady() should be invoked
## Current behavior
 Neither Office.initialize nor Office.onReady() is invoked

## Steps to reproduce

The issue is happening only for one user in Outlook desktop app. There is no issue for the user in OWA. It works fine for other users, for the same Outlook app version and OS.
1. _The user opens an email in Outlook desktop app._____
2. _The user opens the "Salesforce Outlook Integration" Office add-in._____
3. ______

## Link to live example(s)

1. ______Here is simplified example with a few lines of code https://prlbg.csb.app/manifest.xml
2. ______To reproduce the symptom, download the manifest from https://prlbg.csb.app/manifest.xml
3. ______Install the add-in via the manifest.
4. This is the only code in the add-in:
window.Office.onReady(function () {
  console.log("***** onReady is called");
  document.querySelector("#onReady").innerHTML = "Office.onReady is called";
});

window.Office.initialize = function () {
  console.log("***** Office.initialize is called");
  document.querySelector("#initialize").innerHTML =
    "Office.initialize is called";
};
Expected: The above log lines are printed to console
Actual: For one user, the above log lines are not printed in the Outlook desktop app, but it works fine for the same user in OWA.

# Provide additional details

1. ______Cleaned up Office cache based on instructions in https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache but it did not help
2. ______Created a new Outlook user profile but it did not help
3. ______Tested with all COM-based add-ins disabled and Outlook restarted, but it did not help
4. Office.context returns an empty set { }

## Context
 Office.js is not initializing for one user in Outlook desktop app

Can you please help identify the reason why the issue only happens to one user and only in her desktop app but not OWA?
We tested with the user using the above simplified code.
## Useful logs

- [ ] Console errors: Nothing was printed in console when the issue happens to the user.
- [ ] Screenshots: The first two screenshots show when it is not working, breakpoints not hit and initialization code not executed. The last screenshot shows when it is working in OWA:
![breakpointsNotHit](https://github.com/user-attachments/assets/6d5e22ae-f908-4b40-a39c-d55be7a5882b)

![initializationCodeNotExecuted](https://github.com/user-attachments/assets/a12c7299-7551-4d24-958c-cf3b0d148369)

<img width="2378" alt="expected" src="https://github.com/user-attachments/assets/134c7829-eb1a-43a4-9c1b-1fefc8000218">

- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment] 2024-08-01 20:53
@junhuiluosalesforce, can the customer try again?
We had similar reports about 2 days ago that have all been resolved.
If the issue is still ongoing, what is the customer's geolocation?
Can they try force-refreshing the taskpane, by opening dev tools, clicking on the "Network" tab, check "Disable cache", keep the dev tools open and then right-click in the taskpane and click "Refresh".

**Comment by junhuiluosalesforce** [comment] 2024-08-02 15:10
@exextoc Thank you for the suggestion. They tried the steps but it did not help. We found Viva Insights and Send to OneNote from Microsoft are also not working for the user in Outlook desktop app but work fine in OWA. The user is located somewhere in US east coast. They said they were to directly engage Microsoft Support.

**Comment by pepso** [comment] 2024-09-06 12:44
Hi @exextoc,

Having this right now on Classic Outlook: Version 2408 Build 16.0.17928.20114, 64-bit...

I tested the ways I can think of onReady and initilize and they are not being executed before the LaunchEvents. These are supposed to be fired just like for Taskpanel, and New/Web Outlook LaunchEvents?

```
Office.onReady(function(info) { console.log(`Office.js is now ready in ${info.host} on ${info.platform}`); });
Office.onReady().then(function() { console.log("Office library is ready via then chain"); });
(async () => {
    await Office.onReady();
    console.log("Office library is ready via async await");
})();
Office.onReady(function() { console.log("Office library is ready via synchronous function"); });
Office.initialize = function () { console.log("Initialize is called"); };

function action(e) { console.log("action", e); }
Office.actions.associate("action", action);
Office.actions.associate("sendAction", action);
```

And this is the resulting logs (Appointment launch events) when I open an appointment:

```
06/09/2024 13:34:01	Verbose	Runtime	[Console] [Log] Platform Bundle - Office exists!		
06/09/2024 13:34:01	Verbose	Runtime	[Console] [Log] Platform Bundle - Office.actions exists!		
06/09/2024 13:34:01	Verbose	Runtime	[Console] [Log] Platform Bundle - Office.actions.associate exists!		
06/09/2024 13:34:01	Verbose	Runtime	[Console] [Log] Outlook Batch JS loaded!		
06/09/2024 13:34:01	Verbose	Runtime	[Console] [Log] Outlook LaunchEvent JS loaded!		
06/09/2024 13:34:01	Verbose	Runtime	[Console] [Log] InvokeMailboxCreateOM was invoked!["REDACTED"]		
06/09/2024 13:34:01	Verbose	Runtime	[Console] [Log] SDX Control is ready!		
06/09/2024 13:34:01	Verbose	Runtime	[Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = action		
06/09/2024 13:34:01	Verbose	Runtime	[Console] [Log] 'action', { launchEventType: 13, type: 'olkAppointmentOrganizer' }		
06/09/2024 13:34:01	Verbose	Runtime	[Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = action		
06/09/2024 13:34:01	Verbose	Runtime	[Console] [Log] 'action', { launchEventType: 8, type: 'olkRecipientsChanged', changedRecipientFields: { requiredAttendees: true, optionalAttendees: false, resources: false } }		

```

**Comment by t-ariyoshi30907** [comment] 2024-09-21 02:17
@exextoc 
I'm facing the same issue. I've been unable to use Office Add-ins in my older Outlook interface for over a month now.
I've seen similar reports from other developers, so I'm wondering if this is the same problem.
https://github.com/OfficeDev/office-js/issues/4705
Many developers are struggling with this issue. Could you please explain what you're doing to address it?

**Comment by ztcdsb** [comment] 2024-10-21 22:27
@junhuiluosalesforce Can you let us know if the issue still repro?

**Comment by ztcdsb** [comment] 2024-10-21 22:29
@pepso This is expected, we don't specifically triggers it as part of launch event

**Comment by ztcdsb** [comment] 2024-10-21 22:32
@t-ariyoshi30907 It is unsure if the cause of these 2 issues are the same, but we are actively investigating in both. 
Please open in a separate issue if you are currently experience the same problem and share repro steps and logs there.

**Comment by junhuiluosalesforce** [comment] 2024-10-21 22:54
@ztcdsb I need to wait for my customer to confirm since I only know one user experiencing this.

**Comment by junhuiluosalesforce** [comment] 2024-11-04 01:07
@ztcdsb We are only aware of one of our customer users having this issue and we are not able to confirm if the issue still happens with that user.

**Comment by ztcdsb** [comment] 2024-12-02 21:34
@junhuiluosalesforce Thanks for the update. I will close this ticket for now, feel free to re-open it if your customer complains it again

**Closed as completed by ztcdsb** 2024-12-02 21:34 UTC
Labels: Area: Outlook

**Comment by EdwardNavarro** [comment] 2024-12-11 19:33
Check [Event-based add-ins in classic Outlook on Windows](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#event-based-add-ins-in-classic-outlook-on-windows) section form [Configure your Outlook add-in for event-based activation](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch) documentation.

If your add-in uses Events, it wouldn't run any code inside Office.initialize or Office.onReady() when runs on classic Outlook on Windows.

> When developing an event-based add-in to run in the classic Outlook on Windows client, be mindful of the following:
> - Add-ins don't run code included in `Office.onReady()` and `Office.initialize`. We recommend adding any startup logic, such as checking the user's Outlook version, to your event handlers instead.
> ...
