### ISSUE TITLE
OfficeJS doesn't load in Outlook for Windows

### ISSUE THREAD

**Issue by pavelstudeny** [OfficeDev/office-js#4131] opened 2024-02-14 11:59 UTC
# Multiple users cannot load MicrosoftAjax.js
Happens for both classic Outlook and New Outlook, OWA is not affected.

## Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: both classic Outlook and New Outlook
* Office version number: 16.0.17231.20194
* Operating System: Windows 10
* Browser (if using Office on the web): n/a
 
## Expected behavior
Add-in side pane loads correctly

## Current behavior
https://ajax.aspnetcdn.com/ajax/3.5/MicrosoftAjax.js is blocked by the JS engine with "No 'Access-Control-Allow-Origin' header is not present on the requested resource.
MicrosoftAjaxs.js is loaded by outlook-win32-16.02.js and with this failure, Office JS doesn't initialize correctly and Outlook add-in is unable to run. 

<img width="883" alt="image-20240209-093641" src="https://github.com/OfficeDev/office-js/assets/8670912/d0e7f1fe-badc-4204-8e94-a74941ca7ab5">

## Steps to reproduce
Reproduced by several customers' users.

**Comment by zhngx1** [comment] 2024-02-18 07:26
Does classic Outlook also load `outlook-web-16.01.js` file?

**Comment by pavelstudeny** [comment] 2024-02-19 08:59
@zhngx1 thanks for noting this, fixed in the report above. It's outlook-win32-16.02.js for classic Outlook.

**Comment by zhngx1** [comment] 2024-03-13 03:50
Hi, how did you start with the project? Was it from yo office templates? Did you call any APIs with office.js?

**Comment by pavelstudeny** [comment] 2024-03-13 15:20
This is a project that is in production for a few years. Is wasn't created with a template. It would normally start with the Office.Mailbox API, but I'm not sure if it can call it when MicrosoftAjax.js is not loaded. Now that https://github.com/OfficeDev/office-js/issues/4132 is resolved, it makes me think if this could have been caused by cache issues as well.

**Comment by zhngx1** [comment] 2024-03-25 18:09
@pavelstudeny Can you confirm if the issue is resolved?

**Comment by pavelstudeny** [comment] 2024-03-27 15:18
https://github.com/OfficeDev/office-js/issues/4132 will probably included in the upcoming Outlook release? I can check with the users after that.

**Comment by pavelstudeny** [comment] 2024-04-24 11:13
Since https://github.com/OfficeDev/office-js/issues/4132 is not fixed for the users, I cannot confirm this issue disappearing either.

**Comment by zhngx1** [comment] 2024-04-26 04:34
@pavelstudeny I am closing the issue for now. Please feel free to reopen it if user is still experiencing the issue.

**Closed as completed by zhngx1** 2024-04-26 04:34 UTC
Labels: Area: Outlook
