### ISSUE TITLE
Outlook Onsend addin is invoked multiple times after clicking send

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#1367] opened 2020-09-04 05:13 UTC
OnSend addin is invoked multiple times after the send button is clicked. Also, the addin javascript is not called even once.

## Expected Behavior

OnSend should be activated and invoked only once. 

## Steps to Reproduce, or Live Example

Attached zip contains video as the live example of the issue coming on some machines:
[VideoSpecificTo_Mail_Send_Issue.mov.zip](https://github.com/OfficeDev/office-js/files/5172800/VideoSpecificTo_Mail_Send_Issue.mov.zip)

## Context

Our onSend addin is not called and customer is not able to send email.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __MacOS Catalina____
* Host [Excel, Word, PowerPoint, etc.]: _Outlook For Mac_____
* Office version number: __16.39____

**Comment by exextoc** [comment] 2020-09-04 13:16
@Premsagar-lab 
This issue is not reproducible on our end using the Outlook Mac Version 16.39. Could you please provide us the manifest URL of the add-in you are using?

**Comment by Premsagar-lab** [comment] 2020-09-07 06:05
@exextoc Customer is facing this issue consistently on their machine. Please find attached manifest file.
[Manifest.pdf](https://github.com/OfficeDev/office-js/files/5181301/Manifest.pdf)

**Comment by exextoc** [comment] 2020-09-10 06:50
> @exextoc Customer is facing this issue consistently on their machine. Please find attached manifest file.
> [Manifest.pdf](https://github.com/OfficeDev/office-js/files/5181301/Manifest.pdf)

Hello, we tried to install with the manifest supplied but its invalid. Can you please provide the correct manifest?

**Comment by Premsagar-lab** [comment] 2020-09-10 09:26
Hello @exextoc, we use this manifest in our environment. What error you receive while installing the manifest? 

Reattaching as txt because xml cannot be uploaded. 
[manifest_prod.txt](https://github.com/OfficeDev/office-js/files/5200561/manifest_prod.txt)

Kindly rename it as xml.

**Comment by exextoc** [comment] 2020-09-10 17:48
Hello @Premsagar-lab , we tried this with this specific manifest but still we couldn't repro this.

Just to confirm, is this happening on all accounts? Or on certain accounts?

**Comment by Premsagar-lab** [comment] 2020-09-11 05:33
@exextoc This is happening only on some accounts. They have tried reinstalling of outlook but still facing same issue.

**Comment by exextoc** [comment] 2020-09-17 07:43
Hey @Premsagar-lab ,

We could not reproduce this issue on our end. Can you share the exact build number of the build you see this issue in? Is it possible for you to share a test account where this issue is reproducible?

**Comment by dlpsysqa** [comment] 2020-09-17 13:44
@exextoc  we have collected spindump from the customer machine for the outlook process when the issue occurs. can you please check these dumps if these helps
[outlook_spindumps.txt](https://github.com/OfficeDev/office-js/files/5239442/outlook_spindumps.txt)
. else please point if any others logs needed to debug this issue.

**Comment by exextoc** [comment] 2020-09-17 18:18
Can you share the exact build number where this issue is reproducible?

**Comment by exextoc** [comment] 2020-09-20 14:05
Hey @dlpsysqa ,

Thanks for the spindumps, we will investigate this further and let you know what else we need.

**Comment by Premsagar-lab** [comment] 2020-09-21 10:22
@exextoc Can someone from Microsoft Support join us in discussion and debugging this issue in Customer's environment? This can help us achieve faster resolution and collect required logs from user's machine where we are facing issue.

**Comment by exextoc** [comment] 2020-09-21 13:06
Hi @Premsagar-lab sure, we can join for a debugging session. Could you send a meeting invite to admin@a830edad9050849405E20081103.onmicrosoft.com?

**Comment by Premsagar-lab** [comment] 2020-09-25 05:59
Hi @exextoc, Team forwarded a meeting invite at the given email id admin@a830edad9050849405E20081103.onmicrosoft.com. 

The invite is about 2 pm 25th Sept IST. Please confirm.

**Comment by Premsagar-lab** [comment] 2020-10-08 04:08
Hi @exextoc, any updates on this issue?

**Comment by exextoc** [comment] 2020-10-08 04:59
Thanks for reporting this issue regarding OnSend. It has been put on our backlog. We, unfortunately, have no timelines to share at this point

**Comment by exextoc** [comment] 2021-02-05 06:38
@Premsagar-lab Are you still facing this issue? If so, Could you please provide us with logs from Outlook using the below steps?
1.  Launch Outlook (start a new session) 
2. Wait for Add-ins to load 
3. Reproduce the On-Send issue
3. Click on Help -> Collect Diagnostics.
This will generate an Incident ID. Note the same and share it with admin@M365x010952.onmicrosoft.com

**Comment by Ashishagrawalbroadcom** [comment] 2021-02-09 11:04
Fortunately(since yesterday), we haven’t encountered any user in our work queue, asking for help on this case.
Hence, we’d require few more time to identify a user with similar symptoms, as it’s a random pattern and not all are affected by this.

**Comment by Ashishagrawalbroadcom** [comment] 2021-02-09 16:52
Hi Team,

Please find the required incident ID 23SGKP2N, also sent it to the admin@M365x010952.onmicrosoft.com

**Comment by exextoc** [comment] 2021-02-10 05:46
Thanks for sharing the log .It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by Premsagar-lab** [comment] 2021-02-15 05:35
@exextoc, @Ashishagrawalbroadcom had shared the logs with incident ID 23SGKP2N.

**Comment by exextoc** [comment] 2021-02-18 06:28
Thanks @Premsagar-lab.

One more question: Do you know how many customers (approximately) are affected by this problem?

**Comment by Shaon1989** [comment] 2021-03-04 09:08
@exextoc pls re-open it. 
Give us some insight on this issue occurring repeatedly. Our technology support(@Ashishagrawalbroadcom) has shared the incident id of Outlook logs submitted to you, pls come up with a RCA soon.
It's been about 5 months now from the beginning date/time of this case.

**Comment by Premsagar-lab** [comment] 2021-03-04 09:27
Hello @exextoc, Our Customer is still facing this issue. As @Shaon1989 already said that logs have been provided by Ashish on the given email id. 
Kindly let us know if you were able to analyse the cause from given logs.

**Comment by exextoc** [comment] 2021-03-04 18:29
Can we please get the data how many customers are facing this issue? An approximate number would help us prioritize this issue faster. As mentioned before this issue is alrady in our backlog. But we unfortunately have no timelines to share at this point.

**Comment by Shaon1989** [comment] 2021-03-26 06:07
This problem is still happening, pls post some update.
Also this Exchange online Addin (after deployed through Microsoft admin centre) is been populated in Windows Outlook client & therefore people also complaining about slowing down their computers while sending emails.

**Comment by Premsagar-lab** [comment] 2021-03-26 10:36
@exextoc Currently it has been reported by only one prominent customer. @Ashishagrawalbroadcom Kindly comment on exact data.

**Comment by exextoc** [comment] 2021-05-11 03:58
@Premsagar-lab @Ashishagrawalbroadcom 
 
We have not heard from your in last couple of weeks (on github or email). So, we are not able to troubleshoot this issue further. We will go ahead and close this issue for now, please feel free to reopen if you want us to continue looking into this.
 
Furthermore, can you please also try this scenario in "New Outlook Mac" and check if this problem persists there as well.

**Closed as completed by exextoc** 2021-05-11 03:58 UTC
Labels: Area: Outlook, Resolution: cannot repro, Status: in backlog
