### ISSUE TITLE
insertOoxml() fails to replace content with w:sectPr

### ISSUE THREAD

**Issue by macote** [OfficeDev/office-js#110] opened 2018-05-01 12:16 UTC
Word fails to replace the content of a content control using insertOoxml() when a content control contains a section properties element without a trailing paragraph.

## Expected Behavior
The content control content is replaced with the supplied OOXML content. After the operation, there's only one section properties element in the content control content.

## Current Behavior
Word tries to replace the content control content with the supplied OOXML content, but it look like it fails to remove the existing section properties. This results in a content control content containing two sections properties elements. 

## Steps to Reproduce
[Script Lab](https://gist.github.com/macote/e2cf56785fd5ff7fbcba0d748e1a5cd9)
  1. Click "Setup" to initialize the document with the problematic structure.
  2. Click "Run" to replace content.
  3. Inspect the content of the content control.

## Context
I'm developing a tool that replaces content control content. Dealing with documents having this structure represents a blocker for me, since I don't know how to workaround this problem.

I have no control on how documents are generated, but the OOXML they contain is valid.

## Your Environment
* Platform: PC desktop
* Host: Word
* Office version number: Office Click-to-Run Version 1804 (9226.2114)
* Operating System: Windows 10

## Useful logs
No errors are generated while experiencing this issue.

**Comment by hjkim-MSFT** [comment] 2020-06-17 20:59
The issue is that the last paragraph doesn't get deleted with delete method. As a result, the section break will be outside of the content control in setup phase. In run phase, as another section break will be inserted in the content control. Consequently there are two section breaks in the document.

To work around this problem, we can select the last paragraph first and then delete the selected object in setup phase. Here is a gist to show how to do that.
https://gist.github.com/hjkim71/3961ccc057286ca7c13833fa14f0cb29

Please let me know if it works for you.

**Closed as completed** 2020-06-25 18:46 UTC
Labels: Needs: author feedback, Area: Word, Resolution: has workaround, Status: no recent activity
