### ISSUE TITLE
Office.context.contentLanguage does not respect Office host app's selected language (In Windows 7)

### ISSUE THREAD

**Issue by georgechr** [OfficeDev/office-js#199] opened 2018-07-23 06:15 UTC
## Expected Behavior
`Office.context.contentLanguage` should return the currently selected content language in Excel/Office

## Current Behavior
`Office.context.contentLanguage` always returns 'en-US' 

## Steps to Reproduce, or Live Example
```
Excel.run((context) => {
  const range = context.workbook.getSelectedRange();
  range.values = [[Office.context.contentLanguage]];
  await context.sync();
}).catch(function(_) {
})
```

## Your Environment
* Platform: PC
* Host : Excel
* Office version number: 16.0.10228.20080 32-bit
* Operating System: Win 7

**Comment by JuaneloJuanelo** [comment] 2018-07-23 20:59
This API returns the default content language, not of the current selection.  If that needs to be added please upvote a uservoice request.

**Comment by georgechr** [comment] 2018-07-24 05:15
Why was this closed? The [documentation ](https://dev.office.com/reference/add-ins/shared/office.context.contentlanguage) clearly specifies that :

> The  contentLanguage value reflects the Editing Language setting specified with File > Options > Language in the Office host application.

I raised this first as an issue with the documentation team and they claim that the documentation is correct and that I should raise an issue with office-js

**Comment by Rick-Kirkham** [comment] 2018-07-24 16:31
@georgechr As I mentioned in the issue you created for the documentation, I cannot reproduce your error on subscription Office 365 (Click-to-Run). Your code works for me. My OS is Win 10. I see that you are on Win 7. That might be significant. Are you on subscription Office 365 (Click-to-Run) or on Office 2016 MSI? 

@JuaneloJuanelo Do we support add-ins on Win7?

**Comment by JuaneloJuanelo** [comment] 2018-07-24 20:51
Yes
closing the issue again, this is by design.

**Comment by JuaneloJuanelo** [comment] 2018-07-24 21:21
@Rick-Kirkham  yes we support add-in in win7.

@georgechr  quick question for you, can you please share you Microsoft Office Language preferences? what Editing languages you have configured there?  we take the default from that dialog.

**Comment by georgechr** [comment] 2018-07-25 05:53
@JuaneloJuanelo I have Greek as the default but have also tried en-GB without any luck.
![image](https://user-images.githubusercontent.com/865564/43181914-0d592882-8fe8-11e8-98e4-405b8f87f132.png)

@Rick-Kirkham I am on Office 365

**Comment by JuaneloJuanelo** [comment] 2018-07-25 16:03
@georgechr  thanks for sharing this. another question: what are you going to use this property for? i think you are falling into a fallback case where we dont find a supported office.js language and falling back to us-eng.

**Comment by georgechr** [comment] 2018-07-25 19:02
@JuaneloJuanelo basically, I fetch some data from a service and display them as ranges. Some of these data are dates and I would like to use Excel's locale to display them. At the moment my workaround is to use IE's locale to format them but this could be different from Excel's.

**Comment by JuaneloJuanelo** [comment] 2018-07-26 23:21
then you are using the wrong property, you need to use [office.context.displaylanguage](https://dev.office.com/reference/add-ins/shared/office.context.displaylanguage)  that will give you the locale of Excel.

**Comment by georgechr** [comment] 2018-07-27 07:09
@JuaneloJuanelo The same exact bug happens with display language as well i.e. whatever language i choose for display language I get 'en-US'

**Comment by JuaneloJuanelo** [comment] 2018-07-27 15:18
@georgechr  what is the language in the Excel UI?

**Comment by georgechr** [comment] 2018-07-27 19:03
@JuaneloJuanelo Do you mean display language? I've tried various options (greek, en-gb and en-us) and every time I get en-US. For what it's worth, my keyboard is always on en-GB or greek, never en-us.

**Comment by danielgwilson** [comment] 2018-09-07 18:01
@georgechr From a conversation with an engineer on the subject, it appears displaylanguage and contentLanguage only expose the install language to an add-in which might suggest a documentation issue. I'm following up, but that's the current status.

**Comment by Rick-Kirkham** [comment] 2018-09-07 18:11
@danielgwilson I can switch languages from the install language and `contentLanguage` reflects my changes. So I think the docs are correct. I can't reproduce what @georgechr is reporting.

**Comment by danielgwilson** [comment] 2018-09-07 18:27
Strange. I'll still follow up and see if we can get a repro.

**Comment by danielgwilson** [comment] 2018-11-15 22:36
@Rick-Kirkham I can also change languages and get correct output - @georgechr, sorry for the delay and that the source of your issues is unclear. I'm going to close this for now, but please let us know if you can more minimally provide repro steps.

My repro steps (admittedly on a much more recent build):
```
$("#run").click(() => tryCatch(run));

async function run() {
    await Word.run(async (context) => {

        console.log(Office.context.contentLanguage);

        await context.sync();
    });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
    try {
        await callback();
    }
    catch (error) {
        OfficeHelpers.UI.notify(error);
        OfficeHelpers.Utilities.log(error);
    }
}
```

Correctly outputs es-US when Spanish (United States) is selected as the default editing lanugage.

**Comment by georgechr** [comment] 2018-11-16 14:37
@danielgwilson  Not sure why this was closed. Did you try reproducing it on Windows 7? This is where the code I specified in the original bug report was/is running. It's been 6 months and all I can see is en-US. I gave up on this already as I have found a workaround.

```
Office.context
{...}
    contentLanguage: "en-US"
    displayLanguage: "en-US"
    host: "Excel"
```
The above is with editing language as Greek and content language as en-GB

**Comment by Rick-Kirkham** [comment] 2018-11-17 03:25
@georgechr  We're trying to reproduce on Win 7. Win7 machines are surprisingly hard to find around here.

**Comment by lindalu-MSFT** [comment] 2020-06-25 18:59
@Rick-Kirkham I'm tracking down issues with no recent activity and was wondering if this was ever determined to be a doc issue or a bug? Can we close this? Assigning to you to determine the next step. Feel free to close or reassign.

**Closed as completed** 2020-06-25 19:31 UTC
Labels: Needs: attention :wave:, Area: Excel
