### ISSUE TITLE
ImageCoercion 1.2 XMLSvg not working in Powerpoint

### ISSUE THREAD

**Issue by afcruzs** [OfficeDev/office-js#1889] opened 2021-05-27 06:46 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows
* Host [Excel, Word, PowerPoint, etc.]: Powerpoint
* Office version number: version 2105 (build 14026.20246)
* Operating System: Windows 10
* Browser (if using Office on the web): NA
 
## Expected behavior

Retrieve Image XML using the ImageCoercion 1.2 API supported in powerpoint (see [this](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/image-coercion-requirement-sets#imagecoercion-12)). The expected behavior is to use the following snippet and be able to access the image and its metadata:
```
Office.context.document.addHandlerAsync(Office.EventType.DocumentSelectionChanged, function(eventArgs) {
      eventArgs.document.getSelectedDataAsync(
        Office.CoercionType.XmlSvg, // coercionType
        function(result) {
          console.log(result);
          // result.value contains the data
        }
      );
    });
```

## Current behavior

Referencing the latest API (https://appsforoffice.microsoft.com/lib/1/hosted/office.js), and running the code above returns the following value in the callback:
```
OSF.DDA.AsyncResult {value: undefined, status: "failed", error: OSF.DDA.Error}
error: OSF.DDA.Error {name: "Invalid Coercion Type", message: "The specified coercion type is not supported.", code: 1000}
status: "failed"
value: undefined
```
Which is unexpected because this should be supported in the v1.2 API. In fact, calling `Office.context.requirements.isSetSupported("ImageCoercion", 1.2)` returns true, so this seems to be a bug on the API?

I've tried to explicitly set the requirement set in the manifest, but it didn't load the Add-in (fails with an Add-in error saying it is not available). Even though according to [this docs](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/powerpoint-api-requirement-sets) my PowerPoint version is compatible with the API v1.2.

```
  <Requirements>
    <Sets DefaultMinVersion="1.2">
       <Set Name="ImageCoercion " MinVersion="1.2"/>
    </Sets>
    <Methods>
       <Method Name="Document.getSelectedDataAsync"/>
    </Methods>
 </Requirements>
```

## Steps to reproduce

1.  Use a Powerpoint version similar to version 2105 (build 14026.20246)
2. Create a powerpoint add-in using the [yeoman tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/powerpoint-quickstart?tabs=yeomangenerator)
3. Add the snippet from the "expected behavior" section where the code gets initialized.
4. Make sure to be using the latest js API (`https://appsforoffice.microsoft.com/lib/1/hosted/office.js` on the html)
4. Insert and select an image, observe the value of the `result` variable.

## Link to live example(s)

1. Scriptlab link: https://gist.github.com/afcruzs/6825ba23a1174edab48df5e36aae3f82
2. Insert an image and then select it (possibly selecting something before)
3. Check the console output, it should not contain an error.

# Provide additional details

1. ______
2. ______
3. ______

## Context

This is preventing us from writing an add-in which improves image descriptions in powerpoint. Possibly preventing other people to use this API which should be supported already.

## Useful logs

- [x] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by lliu113** [comment] 2021-06-15 22:09
@afcruzs - sorry you're hitting this issue! Unfortunately this is not a bug, ImageCoercion 1.1 and 1.2 is only supported for writing data, and not for retrieving data. 

Please feel free to open up a request for this on the [Microsoft 365 Developer Platform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform).

**Comment by lliu113** [comment] 2021-06-28 19:30
@afcruzs - I'm going to go ahead and close this issue. Feel free to reactivate if you have any additional questions or feedback. Thanks!

**Closed as completed by lliu113** 2021-06-28 19:30 UTC
Labels: Area: PowerPoint, Resolution: by design

**Comment by cmitjans-at-wiris** [comment] 2021-11-24 10:45
Hello, sorry to open this again, but what would be the approach to reading a previously inserted image via `setSelectedDataAsync`?
