### ISSUE TITLE
Function Arguments window truncates multiline argument description

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#2063] opened 2021-08-19 12:21 UTC
# Function Arguments window truncates multiline argument description

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2107 (Build 14228.20250)
* Operating System: Windows
* Browser (if using Office on the web): None
 
## Expected behavior

Full custom function argument description to be displayed

## Current behavior

![image](https://user-images.githubusercontent.com/5159662/130067255-d259a53f-50d7-4119-9d48-15db8c1e5a83.png)

The description is multiline:

```
The order in which the financial periods will be listed:
    
1 - Ascending
2 - Descending
```

The "descending" line is lost.

## Steps to reproduce

1. Use Excel Desktop
2. Install Velixo add-in from the store 
3. Open Insert Function dialogue
4. Select Velixo section, `FINANCIALPERIODLIST` custom function
5. Observe the Function Arguments dialog where the Sort Order description is truncated

**Comment by Rick-Kirkham** [comment] 2021-08-19 19:32
@wh1t3cAt1k It's not clear to me if the issue is for developers that are creating custom functions or a problem in the UI for end users. Please clarify.

**Comment by wh1t3cAt1k** [comment] 2021-08-19 19:41
Hi Rick, the problem is on the user interface, however I am not certain if it's a problem of the framework or the platform.

**Comment by grangeryy** [comment] 2021-08-26 03:06
@wh1t3cAt1k Looks to me more like Excel dialogue interface display issue instead of Custom Functions creation/execution issue. I'll    reach to the Excel side to see what we can do on this. You may also send the issue through:
![image](https://user-images.githubusercontent.com/50093161/130893942-ed7fe9a8-0894-43d3-b2f5-bfd9c516096c.png)

**Comment by wh1t3cAt1k** [comment] 2021-08-26 06:50
Hi @grangeryy ! Thank you, I'd appreciate you reaching out to the Excel team. 

I enjoy having a bi-directional communication with you here, you guys are very responsive. On the other hand, I've never had anyone reach out through the "Feedback" dialogue :(

**Comment by grangeryy** [comment] 2021-08-31 06:49
Hi @wh1t3cAt1k, I've reached to the Excel team and got some suggestion on this. Current best practice is to refine the description without line break. As the dialogue is implemented quite long time ago and line break is not used by any 1st party strings so far.

**Comment by wh1t3cAt1k** [comment] 2021-08-31 09:44
Hi @grangeryy , thank you! 
We have refined the description without any line breaks as a work-around.

We can close this ticket. Perhaps it makes sense to make an internal note for the Excel product nevertheless, I'm sure more people with custom functions will try multiline descriptions :)

**Comment by grangeryy** [comment] 2021-08-31 09:57
Thanks for the suggestion! I'll close this issue and also share feedback to Excel team:)

**Closed as completed by grangeryy** 2021-08-31 09:57 UTC
Labels: Resolution: has workaround, Area: custom functions
