### ISSUE TITLE
Error when opening a dialog

### ISSUE THREAD

**Issue by christian-sap** [OfficeDev/office-js#1959] opened 2021-06-25 07:30 UTC
# Provide required information needed to triage your issue
When opening a dialog with Office.context.ui.displayDialogAsync and option "displayInIframe: false" we get this error:
{ code: 12011 message: "Browser restrictions prevented us from creating the dialog box. The domain of dialog box and the domain of the add-in host are not in the same security zone." name: "Display Dialog Error" }

The second call of Office.context.ui.displayDialogAsync with exactly the same options in the same session does not throw the error.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows
* Browser (if using Office on the web): Edge
 
## Expected behavior
Office.context.ui.displayDialogAsync should always work.

## Current behavior
Office.context.ui.displayDialogAsync only works when calling twice. The first time an error is thrown.

## Steps to reproduce
1. Call Office.context.ui.displayDialogAsync with option "displayInIframe: false" ==> error in the task pane and dialog stays empty.
(The error claims that the domain of dialog box and the domain of the add-in host are not in the same security zone. But this is wrong. They are in the same security zone. )
2. Close the empty dialog and confirm the error with "Ok" in the task pane
3. Make the same call again ==> no error. Dialog opens correctly and displays data.

## Link to live example(s)
Screen cam: https://user-images.githubusercontent.com/79985386/123386815-5c490780-d597-11eb-8e4b-f3c30b109b74.mp4

## Useful logs
Console error: { code: 12011 message: "Browser restrictions prevented us from creating the dialog box. The domain of dialog box and the domain of the add-in host are not in the same security zone." name: "Display Dialog Error" }

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by lliu113** [comment] 2021-06-25 19:10
@christian-sap - sorry you're hitting this! Just want to confirm that the dialog domain you are trying to reach is included in you manifest as a trusted domain?

**Comment by christian-sap** [comment] 2021-06-28 05:08
@lliu113 we start the task pane (shared runtime) on a domain (e.g. example.com) and then navigate to a subdomain of it (e.g. demo.example.com). The dialog domain is the same as the task pane domain (e.g. demo.example.com).
It works in Excel desktop (Win and Mac) but not in Edge. In Edge it only works with the second (exact same) call.

**Comment by lliu113** [comment] 2021-06-28 19:34
@christian-sap - thanks for the clarification! Are you able to provide a manifest for the add-in to help us repro?

**Comment by christian-sap** [comment] 2021-07-02 05:13
@lliu113 unfortunately not. We want to switch one existing dialog from iframe to "non-iframe" but as long as we get this error we can not deploy this change to production. We have it in our dev landscape but you are not able to access it.

**Comment by davidfishlock** [comment] 2021-07-08 15:39
We are also seeing reports of this error from our add-in to our Sentry instance but I have been unable to reproduce this locally.

In our case this is part of an oAuth flow, and the domain of the authentication url is present in the manifest `AppDomains`.

This seems to happen in a small minority of cases, all reports of this come from `OutlookWebApp`. Perhaps this is due to some specific configuration of the browser.

**Comment by christian-sap** [comment] 2021-07-22 16:12
Hi @lliu113 , is there some progress? Are you able to analyze the issue without manifest?

**Comment by lliu113** [comment] 2021-07-22 19:52
@christian-sap - thanks for checking back in! A bug has been logged for this issue and is awaiting triage. Will update this thread once we have more info. 
Internal bug #: 5295252

**Comment by christian-sap** [comment] 2021-07-23 13:01
@lliu113 thanks for the update. Do you need more details and a reproduction scenario? I would be able to provide you a way to reproduce it beginning of next week.

**Comment by timbeese** [comment] 2021-08-19 20:01
I am seeing the exact same behavior with my add-in.  I am running with a Shared Runtime.  If I launch my dialog from within my task pane (react app) it works every time.  But, if I call it from the ribbon and it fires an event over to my react app to launch the dialog, it fails the first time, but works the second time.  Both are using the exact same call.  I'm running this inside of Excel on the Web, running in Chrome or Edge.

If I open the Chrome Debugger tools for the dialog that pops up, I get the following error in the console when it fails:
Uncaught TypeError: Cannot read property '_appName' of null
    at r (excel-web-16.00.js:26)
    at OSF.InitializationHelper.getAppContext (excel-web-16.00.js:26)
    at D (office.js:46)
    at s (office.js:46)
    at d (office.js:46)
    at f.waitForFunction (office.js:46)
    at x (office.js:46)
    at HTMLScriptElement.m (office.js:46)

That error is not present when I am able to open the dialog successfully.

I do not have this problem when running inside of the Excel desktop client.

**Comment by mariomash** [comment] 2021-09-14 12:26
I'm having the same error with my add-in, running in Chrome, **OUTLOOK WEB**,  we are using `promptBeforeOpen: false`

In my main window I see this error, which I certainly know it's not correct, dialog box and add-in host are https://localhost:8080 in both cases:

**12011:Browser restrictions prevented us from creating the dialog box. The domain of dialog box and the domain of the add-in host are not in the same security zone.**

and in my newly opened window I see this one:

```
polyfills.js:1 Uncaught TypeError: Cannot read property '_appName' of null
    at d (outlook-web-16.01.js:formatted:5589)
    at OSF.InitializationHelper.getAppContext (outlook-web-16.01.js:formatted:5630)
    at D (office.js:46)
    at s (office.js:46)
    at d (office.js:46)
    at m.<computed> (polyfills.js:1)
    at h.invokeTask (polyfills.js:1)
    at h.runTask (polyfills.js:1)
    at h.invokeTask (polyfills.js:1)
    at invoke (polyfills.js:1)
```


![AAAAAA](https://user-images.githubusercontent.com/757730/133253905-db0159f7-f45a-4c2b-bf7f-2f6cb2215fdb.png)


in the dialog we are loading "https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js" via <script>

This is my manifest:

```
<....>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">

    <!-- VersionOverrides for the v1.1 schema -->
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.5">
          <bt:Set Name="Mailbox"/>
        </bt:Sets>
      </Requirements>

      <Hosts>
        <Host xsi:type="MailHost">
          <DesktopFormFactor>
            <FunctionFile resid="Commands.Url"/>
            <ExtensionPoint xsi:type="MessageReadCommandSurface">
              <OfficeTab id="TabDefault">
                <Group id="msgReadGroup">
                  <Label resid="GroupLabel"/>
                  <Control xsi:type="Button" id="TranslateButton">
                    <Label resid="Translate.Label"/>
                    <Supertip>
                      <Title resid="Translate.Label"/>
                      <Description resid="Translate.Tooltip"/>
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="Icon.16x16"/>
                      <bt:Image size="32" resid="Icon.32x32"/>
                      <bt:Image size="80" resid="Icon.80x80"/>
                    </Icon>
                    <Action xsi:type="ExecuteFunction">
                      <FunctionName>showTranslationWindow</FunctionName>
                    </Action>
                  </Control>

<....>
```

This is my functions.js file:
```
openedEvent = null;
isOpenedEventCompleted = false;
openedDialog: Office.Dialog;

function displayDialogAsyncCallback(asyncResult) {
  if (asyncResult.status === Office.AsyncResultStatus.Failed) {
    // if asyncResult.error.code === 12009 -> The user chose to ignore the dialog box
    // show a notification or something
    // https://docs.microsoft.com/en-us/javascript/api/outlook/office.notificationmessages?view=outlook-js-preview
    console.log(`${asyncResult.error.code}:${asyncResult.error.message}`);
  } else {
    openedDialog = asyncResult.value;
    openedDialog.addEventHandler(
      Office.EventType.DialogMessageReceived,
      (event) => {
        processMessageFromDialog(openedDialog, JSON.parse(event.message));
      }
    );
  }
}

function showTranslationWindow(event) {
  openedEvent = event;
  const url = `https://${location.host}/dialog`;
  const options = {
    /**
     * Determines if the pop-up blocker dialog will be shown to the user. Defaults to true.
     *
     * `true` - The framework displays a pop-up to trigger the navigation and avoid the browser's pop-up blocker.
     * `false` - The dialog will not be shown and the developer must handle pop-ups (by providing a user interface artifact to trigger the navigation).
     */
    promptBeforeOpen: false,
  };
  Office.context.ui.displayDialogAsync(url, options, (asyncResult) =>
    displayDialogAsyncCallback(asyncResult)
  );
}

//unless you add it in the window, Webpack removes this function as unused, and then Manifest file can never find it
window.showTranslationWindow = showTranslationWindow;

function processMessageFromDialog(dialog, message) {
  switch (message.command) {
    case "initializationCompleted":
      // HACK
      // This is here to address a bug, if we don't mark the event as completed
      // several windows will be opened anytime outlook gets resized
      if (!isOpenedEventCompleted) {
        openedEvent.completed();
        isOpenedEventCompleted = true;
      }
      break;
    case "getData":
      const item = Office.context.mailbox.item;
      if (item) {
        item.body.getAsync(
          Office.CoercionType.Html,
          null,
          (asyncResultBody) => {
            if (asyncResultBody.status !== Office.AsyncResultStatus.Succeeded) {
              console.log("ERROR GETTING BODY");
            } else {
              const data = {
                body: asyncResultBody.value,
                subject: item.subject,
                to: item.to,
                from: item.from,
                dateTimeCreated: item.dateTimeCreated,
              };
              dialog.messageChild(
                JSON.stringify({
                  command: "setData",
                  data: data,
                })
              );
            }
          }
        );
      }
      break;
  }
}

(() => {
  Office.initialize = (reason) => {
    // https://docs.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in#major-differences-between-officeinitialize-and-officeonready

    // https://docs.microsoft.com/en-us/javascript/api/office/office.initializationreason
    // https://docs.microsoft.com/en-us/javascript/api/office
    console.log("Office has been successfully initialized. Reason = ", reason);
  };
})();

```



Do you need any other specific information to fix this one? 

thanks

``

**Comment by mariomash** [comment] 2021-09-20 11:55
I did debug the code to actually understand that (probably):

- the dialog is opened  by using `window.open(url, windowName, options)`.
- windowName contains the full serialized context.
- the (chrome) browser is forcing windowName to be `undefined` if it doesn't detect a manual click in a dialog prior to the one we actually want to open, probably anti-phishing.
 
Then maybe this problem doesn't have a solution, as the browser only allows setting window name if it detects a manual click in a dialog prior to open the actual one we want to display.
I think this information should be available in the documentation somehow, or opening a dialog not from the taskpane using `promptBeforeOpen: false` should be disabled in Outlook (or a different way of sharing the context should be made).

**Comment by iotataru** [comment] 2022-01-18 18:52
@mariomash you are right, this is an issue caused by browser configs. We ask users to please enable pop-ups in order to use the window dialog (if you get the error) and we ask devs to turn on promptBeforeOpen for the window dialog

@lliu113 please follow-up to document this limitation if not already documented and close this issue

**Comment by CoreyKovalik** [comment] 2022-01-27 18:45
We had this error reported, `12011` is not documented here as it should be: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-handle-errors-events#errors-from-displaydialogasync

The dialog has been working until recently. I wonder if there have been any changes to the office API recently

**Comment by ElizabethSamuel-MSFT** [comment] 2022-08-09 22:00
@Rick-Kirkham Are you the right person to help us document this limitation?

Thanks.

**Comment by Rick-Kirkham** [comment] 2022-08-12 17:28
@CoreyKovalik Sorry for the long delay. This had been assigned to someone who left the company shortly after your comment and it was mistakenly not reassigned. I'm researching 12011 (and 12010) and will update the documentation as soon as I can.

**Comment by CoreyKovalik** [comment] 2022-08-12 18:58
> @CoreyKovalik Sorry for the long delay. This had been assigned to someone who left the company shortly after your comment and it was mistakenly not reassigned. I'm researching 12011 (and 12010) and will update the documentation as soon as I can.

Thanks for the update!

@Rick-Kirkham What's your recommended way to get support or questions answered for Outlook add-ins and the Office API these days?

**Comment by Rick-Kirkham** [comment] 2022-08-15 22:19
> > @CoreyKovalik Sorry for the long delay. This had been assigned to someone who left the company shortly after your comment and it was mistakenly not reassigned. I'm researching 12011 (and 12010) and will update the documentation as soon as I can.
> 
> Thanks for the update!
> 
> @Rick-Kirkham What's your recommended way to get support or questions answered for Outlook add-ins and the Office API these days?

Go here: [Microsoft Q&A](https://docs.microsoft.com/answers/products/)

Use the tags **office-addins-dev** and/or **office-js-dev**,

**Comment by Rick-Kirkham** [comment] 2022-08-31 22:13
I have confirmed with the Microsoft engineers that 12011 occurs whenever an under-the-hood call of window.open fails. This error is only seen on Office on the web, and it means that the user has some browser or web configuration that blocks window.open. The main situation for which it was created is when the user is using IE or Edge Legacy and the add-in is not in the same security zone as the host. But it can happen in other situations too. For example, if Safari is the browser and it is configured to block popups. I will update the documentation.

**Closed as completed** 2022-09-01 05:02 UTC
Labels: Needs: attention :wave:, Area: add-in UI, Status: fix pending, Type: doc request
