### ISSUE TITLE
Excel Bindings gets Deleted on refresh

### ISSUE THREAD

**Issue by pvsleeper** [OfficeDev/office-js#2935] opened 2022-11-01 09:12 UTC
When performing a hard refresh in the browser (CTRL + F5), any bindings that were created in and Excel workbook gets delete when an Add-in loads.

Bindings were persisted up to about a day ago and suddenly, when my plugin loads, it deletes all bindings in the Workbook and there is no way to recover it.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome/Edge
 
## Expected behavior

Bindings should be persisted and not deleted unless an explicit operation happens to delete said bindings.

## Current behavior
Bindings in a workbook gets deleted whenever a browser gets hard refreshed (CTRL + F5) and you open an Add-in.

## Steps to reproduce
Run attached Script Lab [script](https://gist.github.com/pvsleeper/c9b3d084c01286195099b4ba0911b7b7).

1. Click the "**Create**" button. That will create a binding in the Workbook.
2. Now press the "**Read**" button, and it should print out "You have 1 bindings".
3. Now, HARD refresh the browser (CTRL+F5) and once reloaded (Sometimes normal refresh works), go back to Script Lab and run this script again, however this time only press the "**Read**" button.
4.  It now prints out "You have 0 bindings".  The binding we created before has been **deleted**. This should NOT be happening.

## Link to live example(s)
Script Lab script to demonstrate issue here: https://gist.github.com/pvsleeper/c9b3d084c01286195099b4ba0911b7b7

## Context
This issue started happening in the last 24 hours. We use named bindings as a way to "index" certain pieces of data and to quickly find and read the values.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment] 2022-11-04 06:33
hi @pvsleeper ,
Thanks for reporting this. Our colleague tried but failed to reproduce the issue. Could you please share your version number? His is 16.0.15903.42307.

**Comment by pvsleeper** [comment] 2022-11-04 07:29
I think this is the same issue as experienced here : https://github.com/OfficeDev/office-js/issues/2940

It magically stared working again yesterday, probably why you can’t replicate. Clearly there was some bug deployed and then hot fixed to address this issue. 

Unfortunately we have a whole bunch of documents whose binding have been deleted (confirmed by looking at the xml contents as mentioned in linked bug above)

**Comment by RuizhiSunMS** [comment] 2022-11-07 03:29
@pvsleeper Since we can't track it, I'd like to close it now. Please feel free to reopen it if it occurs again.
Thanks.

**Closed as completed by RuizhiSunMS** 2022-11-07 03:29 UTC
Labels: Area: Excel, Resolution: cannot repro, Type: product question
