### ISSUE TITLE
If you call delete on the last paragraph of a content control it deletes the content control.

### ISSUE THREAD

**Issue by SirDavenport** [OfficeDev/office-js#4975] opened 2024-10-15 19:12 UTC
In office js for word version 2408 (Build 17928.20216), if you have a content control that is the last paragraph of the document, and you call the delete method on that paragraph thats inside the content control, the content control is deleted. See images below.
![image](https://github.com/user-attachments/assets/8df3ee92-7226-4554-ac05-fc215391ba7f)
If i call .delete() on that empty paragraph in the content control, the content control is removed.

Here is how I'm getting the last paragraph and deleting it.
`const last = answerCC.items[0].paragraphs.getLastOrNullObject();
last.delete();`

**Comment by qinliuMSFT** [comment] 2024-10-17 12:49
Hi @SirDavenport , thank you for reporting this issue. We have filed an item #9449070 and put on our backlog, the team will investigate and reply to you as soon as there is any progress. Thank you for your patience.

**Comment by jipyua** [comment] 2024-10-18 03:37
hi @SirDavenport thanks for reaching out. For this issue, it's a by designed behavior. Acturally not the last paragraph, if you add a content control on just the first paragraph, it will also remove the control when you delete the paragraph. If you show the paragraph mark, you may notice that the content control is inside the paragraph mark and thus it's considered part of the content ctrol.

**Comment by qinliuMSFT** [comment] 2024-10-18 07:27
Closing this issue as it has been confirmed to be designed behavior.

**Closed as completed by qinliuMSFT** 2024-10-18 07:27 UTC
Labels: Area: Word, Status: in backlog

**Comment by SirDavenport** [comment] 2024-10-18 14:14
Thanks for the reply, @jipyua .
However, I think I didn't make myself clear. Lets say I have a content control, and I press Enter 5 times in the content control, so now I have 5 paragraphs. If I call .delete() on the last paragraph of that content control, the content control is deleted, even though there should be 4 other paragraphs still inside it.

Here is an example. We start with this
![image](https://github.com/user-attachments/assets/ab93e947-f11a-413a-befe-28bf14178472)

And then if there is no empty paragraph below that bottom content control, when we insert a file into it, which when I dont delete the last paragraph, gets inserted like
![image](https://github.com/user-attachments/assets/24f6a773-22aa-46bd-8878-91c9f7e08d67)

But when I get the Content controls paragraphs like let last = contentControl.items[0].paragraphs.getLastOrNullObject() and then last.delete(), you wind up with 

![image](https://github.com/user-attachments/assets/b49e92df-93ab-4dfa-a2f8-d5f64c5e6b41)

But all that doesn't happen if there is a paragraph below the content control thats being inserted (highlighted in the picture below)
![image](https://github.com/user-attachments/assets/90a0df84-d071-47f7-a614-e95aef6b2cd4)


Also the reason I found this issue is because we are required to add an empty paragraph to the bottom during insertFileFromBase64 because if you don't, the last paragraph of the inserted file loses its formatting.
