### ISSUE TITLE
Outlook add-in OfficeOnline IE11: Office.context.mailbox.item.body.setAsync not work on IE11

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1040] opened 2020-03-12 12:25 UTC
```
var options = {coercionType: Office.CoercionType.Html};
Office.context.mailbox.item.body.setAsync("1234",  options, function (result) {
    console.log(result);
});
```

execute above code for ie11 outlook office365 online on add-in, it can't set any body to the mail invitation body.

**Comment by AlexJerabek** [comment] 2020-03-12 16:46
Thank you for reporting this @hello-chenchen, 

Assigning to @exextoc for investigation.

**Comment by exextoc** [comment] 2020-03-12 18:46
@hello-chenchen We tried to reproduce this in-house with IE11 and OWA. We are not able to reproduce this. We are able to set the body "1234" in the email.

1. Can you please share with us test account to try out this?
2. Can you please share console logs if there are any errors on it?

**Comment by hello-chenchen** [comment] 2020-03-13 05:16
[catlog.mp4.zip](https://github.com/OfficeDev/office-js/files/4327960/catlog.mp4.zip)
this is the video for how to reproduce this problem. And this is a problem for all the add-ins, as you can see that, i use the owa default add-in(My Templates), it still not work.

1. sorry i can't share my account to you, i think this is not the account problem, cause it worked well on the last week.
2. the logs is on the video, but there is no any errors on it.

My 2 ie11 have the same problem.
this is the one which i record the video.
![image](https://user-images.githubusercontent.com/1878089/76591848-74288380-652c-11ea-8bde-c0c08173b8ab.png)

this is the another one:
![image](https://user-images.githubusercontent.com/1878089/76591885-86a2bd00-652c-11ea-90de-4a2f1694fc82.png)

**Comment by hello-chenchen** [comment] 2020-03-13 05:41
![image](https://user-images.githubusercontent.com/1878089/76593092-41808a00-6530-11ea-975c-6ea293ed06de.png)
My account licenses

**Comment by hello-chenchen** [comment] 2020-03-13 05:42
this is also happened on my other colleagues

**Comment by exextoc** [comment] 2020-03-13 06:08
Thanks for the reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by hmistry-lz** [comment] 2020-03-18 06:34
Our Team is also facing the similar issue where `setAsync` has stopped working out of nowhere. 
To get around it I have replaced `setAsync ` with `prependAsync`. 
There is one catch though. `prependAsync` only works if body is getting updated for the first time. if you delete everything from body and tried to prepend again it will not work.
 There needs to be at least one letter in the appointment body to work it correctly for subsequent updates.
One thing I have observed while debugging this issue is that Chrome returns `<span><br></span>`  after clearing the body of an appointment whereas IE11 does not return anything and that might be causing the issue.

**Comment by exextoc** [comment] 2020-05-07 04:46
Could you please confirm if you are still facing this issue?

**Comment by hmistry-lz** [comment] 2020-05-07 05:48
yes, I am still facing this issue unless fix has been released?

**Comment by hello-chenchen** [comment] 2020-05-07 05:59
yeah, still the same behavior.

**Comment by exextoc** [comment] 2020-05-27 09:45
Fix for this issue has been deployed now and should be available. Can you all please check if this issue is resolved for you? Thanks.

**Comment by hmistry-lz** [comment] 2020-05-27 19:34
Yes, it is resolved. thank you so much!

**Comment by exextoc** [comment] 2020-05-29 11:46
Closing the issue since problem is resolved for atleast one user. Let us know if it is not fixed for some users.

**Closed as completed by exextoc** 2020-05-29 11:46 UTC
Labels: Area: Outlook, Type: product bug, Status: fixed
