### ISSUE TITLE
Office.js Addin doesnt load in Word for MAC

### ISSUE THREAD

**Issue by RoyalMugu** [OfficeDev/office-js#602] opened 2019-07-05 18:11 UTC
Unable to load the Office.js addins in Word for MAC. The issue is seen only when Word file is attached to mail and directly opened from the mail. The word file is opened in read only mode. The "My addins" option under addin ribbon is greyed out. We are trying to sideload addin  to Word but we are unable to load any addins because of this behavior. We dont see this issue when word document is already present in the background.

## Expected Behavior
The "My addins" option under addin ribbon should not be greyed out. 

## Current Behavior
 The "My addins" option under addin ribbon is greyed out.

## Steps to Reproduce, or Live Example
1. On your Mac, Quit Word(right click on the Word icon at the bottom and select Quit) if it’s running already.
2.Open a .docx attachment(this can be one page blank document, doesn’t need to be anything complicated) from an email.
3.Doc opens in a read-only mode and the add-in is not loaded. Go to Insert tab and click My add-ins. The "My addins" option under addin ribbon is greyed out

## Context

Customers are unable to use the addin in this scenario

## Your Environment

* Platform [Mac]: 10.13.6
* Host [Word]: 16.27
* Office version number: 16.27

The issue is reproducible even with a simple manifest file. I can provide the manifest if required

**Comment by kbrandl** [comment] 2019-07-05 20:27
@RoyalMugu I believe this behavior is "by design". i.e., when you open a file attachment from email, it'll be opened in "Protected View" -- nearly all ribbon buttons are grayed out when a document is in "Protected View". When this happens, there should be a banner displayed directly above the document that contains an **Enable Editing** button. 

![image](https://user-images.githubusercontent.com/3019529/60743831-0f8e4100-9f28-11e9-9485-a752a6b214e3.png)

Are you seeing what I've described, and if yes, if you click the **Enable Editing** button then do all ribbon buttons become enabled (including the **My Add-ins** button)?

**Comment by RoyalMugu** [comment] 2019-07-05 23:33
@kbrandl , 
1. You are trying to repro this behavior in Word for Windows but this behavior is seen in Word for MAC
2. In word for MAC, we dont see the enable editing, we see the duplicate option
![repro](https://user-images.githubusercontent.com/38550182/60748406-64d74c00-9f42-11e9-9235-b0bb66fc7482.png)
3. The addins are visible when you have a word instance already running in the background and trying to open the attachment
4. Is this by design? or Excpected?

**Comment by kbrandl** [comment] 2019-07-06 00:56
@RoyalMugu thanks for the screenshot that shows exactly what you're seeing in Mac. You're correct that I tested in Windows; generally behavior like this is similar (although not always identical, as in this case) between platforms. I'll follow up with others here internally to determine whether the behavior you're describing on Mac is a bug or by design (expected).

**Comment by RoyalMugu** [comment] 2019-07-06 17:32
@kbrandl Thanks. Awaiting your response.

**Comment by kbrandl** [comment] 2019-07-10 17:17
@RoyalMugu thanks for your patience on this. I've confirmed with the Office Add-ins Platform team that the **My Add-ins** button being grayed out when a document is opened from an email attachment is the expected behavior. In this scenario, only once you click the button that's displayed in the banner across the top of the doc ("Protected View" button on Windows or "Duplicate" button on Mac) should ribbon buttons become enabled.

That said though, I can understand how the fact that you're seeing different behavior on Mac when you open the email attachment -- ribbon buttons _enabled_ if Word is already running versus ribbon buttons _disabled_ if Word is not already running -- could be potentially confusing and disruptive for users. The best way to report this inconsistency to the team who controls that functionality in Word is for you to report that feedback as described here: [How do I give feedback on Microsoft Office?](https://support.office.com/en-US/article/How-do-I-give-feedback-on-Microsoft-Office-2b102d44-b43f-4dd2-9ff4-23cf144cfb11#platform=MacOS) (i.e., use the feedback tool in the upper-right corner of the app to "send a frown" and provide detailed feedback when prompted).

Thanks again for your patience as I tracked down this info. I'm going to go ahead and close this issue now (since it's a problem with the Word application itself, not addressable by the Office Add-ins team). If you can please [report](https://support.office.com/en-US/article/How-do-I-give-feedback-on-Microsoft-Office-2b102d44-b43f-4dd2-9ff4-23cf144cfb11#platform=MacOS) the inconsistent behavior you're seeing as I've described above, the team who manages the core functionality of Word can hopefully address it.

**Closed as completed by kbrandl** 2019-07-10 17:17 UTC
Labels: Needs: attention :wave:, Area: add-ins platform
