### ISSUE TITLE
How to change the Dialog title?

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#2373] opened 2022-01-18 14:03 UTC
I am trying Excel Addin with dialog api, and I have such dialog below:

[![enter image description here][1]][1]

How can I change the content in green area?

How can I disable the close button in red area?

  [1]: https://i.stack.imgur.com/qJUZR.png

**Comment by RuizhiSunMS** [comment] 2022-01-20 08:06
@lliu113 could you please take a look on this?

**Comment by lliu113** [comment] 2022-01-25 17:28
@Edward-Zhou - thank you for your question! The title of the dialog cannot be changed - this is by design. This is to prevent spoofing as the title displays the URL of the page that is loaded. 

We also do not have the ability to disable the close button. We try to develop our platform consistent with native Office principles, and having a close function on dialogs aligns with that. It is also preferred UX, as users should have a clear way to dismiss the dialog if needed. 

If you have a strong user scenario justification for needing to disable the close button, feel free to open a feature request on the[ Microsoft 365 Developer Platform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). 

Closing this bug, please reactivate if you have any further questions. Thanks!

**Closed as completed by lliu113** 2022-01-25 17:28 UTC
Labels: Area: Excel, Area: add-in UI, Resolution: by design
