### ISSUE TITLE
Not possible to close the dialogs. The dialog.close() API is broken.

### ISSUE THREAD

**Issue by stefanoslig** [OfficeDev/office-js#2457] opened 2022-03-02 14:17 UTC
# Provide required information needed to triage your issue

Our OWA addin is currently broken because the dialog.close() API is not working. We get the following error: 

```
zone-evergreen.js:171 Uncaught TypeError: Cannot set properties of undefined (setting 'targetOrigin')
    at OSF.DDA.WAC.Delegate.closeDialog (outlook-web-16.01.js:20:212335)
    at g.<computed> (outlook-web-16.01.js:20:86901)
    at OSF.DialogHandler.value [as close] (outlook-web-16.01.js:20:187604)
    at SendingService.closeOnSendEvent (sending.service.ts:539:21)
    at TapSubscriber._tapNext (sending.service.ts:152:24)
    at TapSubscriber._next (tap.ts:120:21)
    at TapSubscriber.next (Subscriber.ts:99:12)
    at FilterSubscriber._next (filter.ts:101:24)
    at FilterSubscriber.next (Subscriber.ts:99:12)
    at CatchSubscriber._next (Subscriber.ts:139:22)
```

All of our customers are affected. It's crucial for us to be fixed ASAP since it's a very basic API.

If you know already a workaround, please let us know.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: OWA
* Office version number: ______
* Operating System: macOS
* Browser (if using Office on the web): Chrome

**Comment by designcode** [comment] 2022-03-02 14:34
As Stefanos mentioned, It's quite basic functionality and it's rendering our whole application broken. Can you please make it high priority?

**Comment by pinchukdiana** [comment] 2022-03-02 14:42
@exextoc could you please treat this issue as a high priority? It completely blocks our product and our customers

**Comment by neville-jones** [comment] 2022-03-02 22:53
This break is causing major disruption for our customers - showing dialog with the on send event and the users cannot close the dialog and message not being sent

`Uncaught TypeError: Cannot set properties of undefined (setting 'targetOrigin')
    at OSF.DDA.WAC.Delegate.closeDialog (outlook-web-16.01.js:20:212335)`

**Comment by t-miyake** [comment] 2022-03-03 02:32
This very serious problem is also occurring with our clients.
(Our customer has over 120,000 users.)

@exextoc I hope you will fix this problem ASAP.

**Comment by Gustavogbs** [comment] 2022-03-03 02:44
> # Provide required information needed to triage your issue
> Our OWA addin is currently broken because the dialog.close() API is not working. We get the following error:
> 
> ```
> zone-evergreen.js:171 Uncaught TypeError: Cannot set properties of undefined (setting 'targetOrigin')
>     at OSF.DDA.WAC.Delegate.closeDialog (outlook-web-16.01.js:20:212335)
>     at g.<computed> (outlook-web-16.01.js:20:86901)
>     at OSF.DialogHandler.value [as close] (outlook-web-16.01.js:20:187604)
>     at SendingService.closeOnSendEvent (sending.service.ts:539:21)
>     at TapSubscriber._tapNext (sending.service.ts:152:24)
>     at TapSubscriber._next (tap.ts:120:21)
>     at TapSubscriber.next (Subscriber.ts:99:12)
>     at FilterSubscriber._next (filter.ts:101:24)
>     at FilterSubscriber.next (Subscriber.ts:99:12)
>     at CatchSubscriber._next (Subscriber.ts:139:22)
> ```
> 
> All of our customers are affected. It's crucial for us to be fixed ASAP since it's a very basic API.
> 
> If you know already a workaround, please let us know.
> 
> ## Your Environment
> * Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
> * Host [Excel, Word, PowerPoint, etc.]: OWA
> * Office version number: ______
> * Operating System: macOS
> * Browser (if using Office on the web): Chrome

**Comment by Gustavogbs** [comment] 2022-03-03 02:46
We (Microsoft Engineers) are working on this issue. It will be fixed soon

**Comment by avisheknand** [comment] 2022-03-03 04:02
We are having similar issue as well. Our clients are affected and they are complaining that they can not send emails at all because the dialog is not closing on the onsend event. Hoping this gets solved ASAP.

**Comment by clavx** [comment] 2022-03-03 04:47
@exextoc is it related to the following issue?

> EX337868
> Users can’t open email sent with Secure/Multipurpose Internet Mail Extensions (S/MIME) encryption in Outlook on the web

> Current status: We’ve confirmed that a recent update contained a code regression that’s causing impact to the Outlook on the web pop-out feature. We’re in the process of testing a fix which we anticipate to remediate impact.

![admin-health](https://user-images.githubusercontent.com/58804032/156497753-abe48c6a-2773-4498-85a9-876e0dc120d1.png)

**Comment by t-miyake** [comment] 2022-03-03 06:56
@Gustavogbs @exextoc How is the fix progressing?
When the fix is completed, please notify us here as well.

**Comment by clavx** [comment] 2022-03-03 08:16
> EX337976
> Some users are unable to send email via the on-send feature for Outlook add-ins in Outlook on the web

![admin-Incident](https://user-images.githubusercontent.com/58804032/156523682-9ef13799-eb4f-4d52-8742-a16dcf915d61.png)

**Comment by LivertonSecurity** [comment] 2022-03-03 08:53
This is affecting our customers in New Zealand also.

It's great to see that the issue listed on 'Microsoft365 Service Health'.
Thank you!

<SNIP BELOW from Microsoft 365 admin center>
------------------------------------------------------------------------------
Some users are unable to send email via the on-send feature for Outlook add-ins in Outlook on the web
EX337976, Exchange Online, Last updated: March 3, 2022 8:31 PM
Estimated start time: March 3, 2022 10:24 AM
Affected services
Exchange Online
Issue type
Incident
Issue origin
Microsoft
Status
Service degradation
Manage notifications for this issue
User impact
Users are unable to send email via the on-send feature for Outlook add-ins in Outlook on the web.
Are you experiencing this issue?
Is this post helpful?
All updates
March 3, 2022 8:30 PM
Title: Some users are unable to send email via the on-send feature for Outlook add-ins in Outlook on the web

User Impact: Users may be unable to send email via the on-send feature for Outlook add-ins in Outlook on the web.

More info: Affected users aren't able to click the Send button in the pop up window for the on-send feature, so the email goes to the Draft folder instead of being sent. Affected users also can't click Cancel to close the pop up window.

Current status: We've determined that a recent change intended to improve Outlook on the web functionality is impacting the on-send feature for Outlook add-ins in Outlook on the web. We're pursuing methods for halting and reverting the change to remediate the impact.

Scope of impact: This issue affects users who have received the change and are attempting to send email via the on-send feature for Outlook add-ins in Outlook on the web is impacted.

Start time: Thursday, March 3, 2022, 10:24 AM (3/2/2022, 9:24 PM UTC)

Root cause: A recent change intended to improve Outlook on the web functionality is impacting the on-send feature for Outlook add-ins in Outlook on the web.

Next update by: Thursday, March 3, 2022, 10:30 PM (9:30 AM UTC)
March 3, 2022 6:59 PM
Title: Users are unable to send email via the on-send feature for Outlook add-ins in Outlook on the web

User Impact: Users are unable to send email via the on-send feature for Outlook add-ins in Outlook on the web.

More info: Users aren't able to click the Send button in the pop up window for the on-send feature, so the email goes to the Draft folder instead of being sent. Users also can't click Cancel to close the pop up window.

Current status: We're continuing to analyze code and recent changes to isolate the problem and identify a remediation plan.

Scope of impact: Your organization is affected by this event, and any user attempting to send email via the on-send feature for Outlook add-ins in Outlook on the web is impacted.

Next update by: Thursday, March 3, 2022, 10:00 PM (9:00 AM UTC)
March 3, 2022 4:33 PM
Title: Users are unable to send email via the on-send feature for Outlook add-ins in Outlook on the web

User Impact: Users are unable to send email via the on-send feature for Outlook add-ins in Outlook on the web.

More info: Users aren't able to click the Send button in the pop up window for the on-send feature, so the email goes to the Draft folder instead of being sent. Users also can't click Cancel to close the pop up window.

Current status: We've confirmed with your representatives that email is getting moved to the Draft folder instead of being sent because users aren't able to click the Send button in the pop up window for the on-send feature. We believe this is being caused by a code regression, so we're analyzing code for the on-send feature and recent updates to identify the source of the regression.

Scope of impact: Your organization is affected by this event, and any user attempting to send email via the on-send feature for Outlook add-ins in Outlook on the web is impacted.

Next update by: Thursday, March 3, 2022, 7:00 PM (6:00 AM UTC)
March 3, 2022 3:51 PM
Title: Users are unable to send email via the on-send feature for a custom Outlook add-in in Outlook on the web

User Impact: Users are unable to send email via the on-send feature for a custom Outlook add-in in Outlook on the web.

More info: While we're focused on remediation, users who have access to the Outlook desktop client can use that connection method to send email with the custom add-in.

Current status: We're analyzing impact information provided by your organization to determine the source of the issue.

Scope of impact: Your organization is affected by this event, and all users attempting to send email via Outlook on the web are experiencing impact.

Next update by: Thursday, March 3, 2022, 5:30 PM (4:30 AM UTC)
March 3, 2022 3:21 PM
Title: Users are unable to send email via Outlook on the web

User Impact: Users are unable to send email via Outlook on the web.

More info: Users that have access to the Outlook desktop client can send email using that connection method.

Current status: We’ve received a report from your organization that impact associated with EX333858 persists. We've resumed our investigation of the issue.

Scope of impact: Your organization is affected by this event, and all users attempting to send email via Outlook on the web are experiencing impact.

**Comment by t-miyake** [comment] 2022-03-03 09:45
Incident (EX337976) has been updated.

>March 3, 2022 6:16 PM
>Title: Some users are unable to send email via the on-send feature for Outlook add-ins in Outlook on the web
>
>User Impact: Users are unable to send email via the on-send feature for Outlook add-ins in Outlook on the web.
>
>More info: Affected users aren't able to click the Send button in the pop up window for the on-send feature, so the email goes to the Draft folder instead of being sent. Affected users also can't click Cancel to close the pop up window.
>
>Current status: We've successfully halted the change and developed a fix, which we're deploying to the impacted environment.
>
>Scope of impact: This issue affects users who have received the change and are attempting to send email via the on-send feature for Outlook add-ins in Outlook on the web is impacted.
>
>Start time: Thursday, March 3, 2022, 6:24 AM (3/2/2022, 9:24 PM UTC)
>
>Root cause: A recent change intended to improve Outlook on the web functionality is impacting the on-send feature for Outlook add-ins in Outlook on the web.
>
>Next update by: Thursday, March 3, 2022, 8:30 PM (11:30 AM UTC)

**Comment by exextoc** [comment] 2022-03-03 11:06
Issue has been fixed and rolled out. Please confirm.

**Comment by carlosb1504** [comment] 2022-03-03 11:13
Still seeing the issue as of 11:13 AM GMT

**Comment by exextoc** [comment] 2022-03-03 11:16
Can you please do hard refresh, clear cache and try again.

**Comment by carlosb1504** [comment] 2022-03-03 11:17
I did do that, just tried again. Same outcome unfortunately

**Comment by LivertonSecurity** [comment] 2022-03-03 11:39
Hi Guys,
Our Ex365 tenancy in Aus/NZ has recently been updated from

- 20220218005.03 (broken) to
- 20220211003.12 (fixed)

This was a fantastic turnaround of fix from the Microsoft team!
Thank you!

Others - please note that fixes do take time to replicate through O365 tenancies around the world.
Maybe test again in 12 or 24 hours?

**Comment by carlosb1504** [comment] 2022-03-03 11:51
12 or 24 hours is a long time when you have potentially tens of thousands of paying customers with a broken product for almost 24 hours now already. 

Can anyone advise whether this has been raised as a critical incident? The issue quoted above in the Admin Portal is showing only 'Advisory'.

**Comment by LivertonSecurity** [comment] 2022-03-03 11:58
@[carlosb1504] my comment re 12 or 24 hours was based on previous experience here in NZ where O365 tenancies here had to wait for fix replication.

My assumption (probably incorrect) is that Aus/NZ is at the tail end of replication. Therefore YOU (wherever you are in the world) should be updated already?

@exextoc - are you able to comment on MS process around replicating updates worldwide?

**Comment by avisheknand** [comment] 2022-03-03 20:21
@exextoc , confirming that it is now working for us ( in Fiji) . Thanks for fixing the issue.

**Comment by neville-jones** [comment] 2022-03-03 20:54
working for us, in Australia

**Comment by t-miyake** [comment] 2022-03-03 23:49
I have confirmed that the fix is complete too. (in Japan)
Thanks.

**Comment by exextoc** [comment] 2022-03-04 03:03
Thanks for confirmations.

@carlosb1504 Can you also please test again and let us know if issue exists or it is fixed?

**Comment by carlosb1504** [comment] 2022-03-07 21:48
Hi. Apologies for the delayed reply. Yes I can confirm this is fixed for us too. Thanks

**Comment by nkkinariwala** [comment] 2022-03-28 17:16
looks like the issue is fixed. Hence closing it.

**Closed as completed by nkkinariwala** 2022-03-28 17:16 UTC
Labels: Status: fixed
