### ISSUE TITLE
Calling the getAttachmentContentAsync method freezes Outlook add-ins

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#912] opened 2019-12-18 03:42 UTC
If we attach an Outlook item to a mail, call the `getAttachmentsAsync` method to obtain an ID, and then call the `getAttachmentContentAsync` method using that ID, you will get no exceptions, just a freeze.

## Expected Behavior

The process does not freeze and the contents of the attached item can be obtained.

## Current Behavior

We can't do anything because the process is frozen.

## Steps to Reproduce, or Live Example

1. Open Outlook for Windows
2. Click the "New Mail" button to create a new mail
3. Adds a single multibyte character to the mail text. You do not need to enter the address or subject.
For example, enter a Japanese character "あ" in the mail text. When you copy and paste multibyte characters from a website, select "Keep Text Only" in Paste options.
4. You can save the mail. Contribute creates the mail in your draft.
5. Create another new mail
6. Click the "Outlook item" button, select the mail that was saved in the draft you just created, and check "Insert as Attachment" to attach it.
7. Run the following code

```javascript
  const item = Office.context.mailbox.item;
  item.getAttachmentsAsync((result) => {
    console.log(result);
    for (let i = 0; i < result.value.length; i++) {
      item.getAttachmentContentAsync(result.value[i].id, (result2) => {
        console.log(result2);
      });
    }
  });
```
I reinstalled Office 365 ProPlus based on the following site, but there was no change.
[Uninstall Office from a PC - Office Support](https://support.office.com/en-us/article/Uninstall-Office-from-a-PC-9dd49b83-264a-477a-8fcc-2fdf5dbf61d8)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 365 ProPlus Version 1911 (Build 12228.20364 Click-to-Run)
* Operating System: Windows 10 Pro, version 1903
* Browser (if using Office Online): Microsoft Edge 44.18362.449.0

**Comment by Reezaali** [comment] 2019-12-19 21:44
@clavx sorry to hear that you've run into this issue. 

@exextoc can you investigate please? Thanks.

**Comment by exextoc** [comment] 2020-01-10 01:40
I've tried this scenario. and what I repro is that the callback for getAttachmentContentAsync is never called. Is this what you mean by "frozen"? Or does the actual Outlook Process Crash?

**Comment by clavx** [comment] 2020-01-10 12:57
It means that `getAttachmentContentAsync` is never return. The Outlook process does not crash.

**Comment by exextoc** [comment] 2020-01-10 19:43
Thanks, as mentioned, we can repro the bug. I have added this bug to the product team's backlog, but I cannot comment on when or if the bug will be fixed.

**Comment by exextoc** [comment] 2020-08-01 00:15
Internal tracking id: Office:3857410

**Comment by Matej4386** [comment] 2020-12-09 07:17
Any news?

**Comment by Diegoescalonaro** [comment] 2021-03-01 11:57
Any news on this? `getAttachmentContentAsync` is not working

**Comment by exextoc** [comment] 2021-03-01 22:30
There were some issues while fixing this that the product team is taking another look at. I don't have further updates to share at this time. 

Internal Tracking Id changed to: Office: 4720588

**Comment by clavx** [comment] 2021-05-11 08:30
@exextoc 
I was unable to reproduce the issue with the steps I reported.
I think this issue has been resolved, do you have any updates?

Tested:
- Outlook for Windows: Version 2104 (Build 13929.20296)
- OWA: 20210426004.08

**Comment by exextoc** [comment] 2021-07-06 06:09
We cannot reproduce this issue as well using the steps you provided above.
We will look into this issue again if it ever resurfaces.

**Closed as completed** 2021-07-08 21:23 UTC
Labels: Area: Outlook, Type: product bug, Status: in backlog
