### ISSUE TITLE
[Excel] getSelectedRange() error

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [OfficeDev/office-js#8] opened 2017-08-02 21:42 UTC
`getSelectedRange` throws an error if my selection is a `ChartObject`, a `Shape`, a `Picture`, an ActiveX Object or an embeded Office Addins object to name a few. Maybe there are other types too, but I don't recall right now.
My setup is Excel 365 v1706 / Windows 10, tested on ScriptLab.

I'm not sure if this is really a bug because the method name is get selected **range**, so it should throw an error if the selection is not a `Range` object. But, if you want to mirror the `Application.ActiveCell` property from VBA, it shouldn't throw an error.

I had this error because I was wondering if it is possible to get the selected object type, as I do in VBA: `TypeName(Selection)`, but (I think) there is no such property as `Application.Selection`.

**Comment by Zlatkovsky** [comment] 2017-08-06 01:40
@kevishi , could you please take a look?

**Comment by sumurthy** [comment] 2017-11-15 17:13
Hi @FelipeCostaGualberto, in this scenario, what would you expect the right behavior to be? 

We don't yet support get selected table/chart/or other objects. 

We did add getActiveCell API in the newer release (still in beta). https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_OpenSpec/reference/excel/workbook.md#getactivecell 

Would that help?

**Comment by FelipeCostaGualberto** [comment] 2017-11-15 17:30
I need a macro to easily color the background of my selection, be it a Range or a TextBox. VBA demonstration:

    Sub ColorSelection()
        Const FILL_COLOR = 6299648
        
        Select Case TypeName(Selection)
            Case "Range"
                Selection.Interior.Color = FILL_COLOR
            Case "TextBox"
                Selection.ShapeRange.Fill.ForeColor.RGB = FILL_COLOR
            Case Else
                MsgBox "Can't color this type of object: " & TypeName(Selection)
        End Select
    End Sub

**Comment by JuaneloJuanelo** [comment] 2018-07-23 23:38
Probably this is a by design issue. The name of the method is getSelected**Range**  

Now that we are implementing shapes, charts, etc we should consider adding a generic "getSelection()" and let the user infer whats contained.   This is actively on design.


we understand the requirement, so closing the issue at this point.

**Closed by JuaneloJuanelo** 2018-07-23 23:38 UTC
Labels: area: excel, bug
