### ISSUE TITLE
Outlook AddIn 'OnMessageAttachmentsChanged' was not triggered

### ISSUE THREAD

**Issue by guzman-rc** [OfficeDev/office-js#2329] opened 2021-12-26 22:12 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I tried below steps to testing 'OnMessageAttachmentsChanged' on Outlook application add-in.

https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch

But it seems that the event was not triggered.

Javascript code added to the end of commands.js file

function onMessageAttachmentsChangedHandler(event) {
  console.log("Attached file");
}

Office.actions.associate("onMessageAttachmentsChangedHandler", onMessageAttachmentsChangedHandler);

OnNewMessageCompose event works successfully.

Test performed Outlook Web Microsoft 365 account.

**Comment by exextoc** [comment] 2021-12-27 12:41
@guzman-rc Thanks for raising the issue. Can you host your add-in with the code that reproduces this and share the add-in manifest file for the same.

**Comment by guzman-rc** [comment] 2021-12-27 19:59
[My Office Add-in.zip](https://github.com/OfficeDev/office-js/files/7781625/My.Office.Add-in.zip)
The ZIP file contains all the AddIn files.

**Comment by exextoc** [comment] 2021-12-29 10:30
@guzman-rc Thanks for sharing the details. We tried with your manifest, code and it works properly for us. We validated with the console log from the handler function. Can you retry? 
If the issue is still observed please share repro video.

**Comment by ansarishohrab** [comment] 2021-12-30 07:18
I'm facing the same issue

here is video link
https://nimb.ws/xXgPZ3

**Comment by exextoc** [comment] 2022-01-04 11:42
@ansarishohrab From video it looks like you are trying the addin on Linux and Chrome. Can you confirm if this is correct?
@guzman-rc Please share your repro vid, along with OS and browser details.

**Comment by guzman-rc** [comment] 2022-01-08 18:03
https://user-images.githubusercontent.com/96702862/148654605-8f1d179a-7bd1-449d-8e02-a74448077aee.mp4

S.O: Windows 10 Pro (64 Bits) Version: 21H1
Web Browser: Chrome Versión 97.0.4692.71 (Build oficial) (64 bits)

**Comment by guzman-rc** [comment] 2022-01-10 12:24
Or add the Outlook add-in for event-based activation on your PC from the url:
https://www.adarsus.com/addin/outlook_event/manifest.prod.xml

**Comment by exextoc** [comment] 2022-01-18 08:56
@guzman-rc  This feature is currently being rolled out and will be in production by the end of the week. Please let us know if you still face any issues starting 24th Jan.

**Comment by guzman-rc** [comment] 2022-01-24 11:54
OnMessageAttachmentsChanged event still not working.

**Comment by exextoc** [comment] 2022-01-25 09:59
Thanks @guzman-rc for your input. We are checking it internally if feature released as planned.

**Comment by exextoc** [comment] 2022-01-31 05:50
The feature is completely rolled out now, Can you please test it from your end and confirm if it works for you now.

**Comment by guzman-rc** [comment] 2022-01-31 10:15
The event is executed only for the first attachment. When the second file is attached the event is not fired.

You can use the following implementation of Outlook add-in for event-based activation to test:
https://www.adarsus.com/addin/outlook_event/manifest.prod.xml

**Comment by exextoc** [comment] 2022-02-01 05:49
Thanks for reporting this issue regarding OnMessageAttachmentChanged event. We are able to reproduce this issue internally. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by guzman-rc** [comment] 2022-02-15 11:45
Can you provide an approximate date to resolve this issue?
We need to know the resolution date to inform our clients.
Thanks a lot.

**Comment by carlosb1504** [comment] 2022-02-17 19:11
We are also seeing this same issue. Some timescales would be appreciated for us too.

**Comment by exextoc** [comment] 2022-02-22 10:13
we are prioritizing the dev investigation and will let you know when there is a further update.

**Comment by guzman-rc** [comment] 2022-02-27 10:14
OnMessageAttachmentsChanged event still not working. We hope to have news soon.

**Comment by guzman-rc** [comment] 2022-03-23 14:45
Can you give us an estimated date to solve this issue?
Thanks a lot.

**Comment by 1842014** [comment] 2022-04-07 14:27
Currently working on an add-in that needs this implementation of OnMessageAttachmentsChanged. Still only works for the first file uploaded.

**Comment by nssoft-rlagrange** [comment] 2022-07-05 15:37
Hi, any news on this ?

**Comment by exextoc** [comment] 2022-07-06 04:15
The issue has been fixed. Is it still reproable for you?

**Comment by coredeveloper** [comment] 2022-07-14 10:56
Any progress with this? I am facing the same issue.

**Comment by exextoc** [comment] 2022-07-19 09:32
Hi @coredeveloper, are you using event.completed method after processing the launch event? Refer to the document at:
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#event-based-activation-behavior-and-limitations

**Comment by guzman-rc** [comment] 2022-07-23 12:11
OnMessageAttachmentsChanged event still not working.

**Comment by exextoc** [comment] 2022-07-25 07:09
@guzman-rc, the add-ins framework requires developers to use the event.completed method after processing the launch event in order to ensure that your subsequent events are correctly handled on both ends. 

Can you please confirm that you are calling the event.completed() method at the end of your handler function as detailed in the documentation?

Refer to the documentation at:
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#event-based-activation-behavior-and-limitations

**Comment by guzman-rc** [comment] 2022-08-01 09:16
If we invoke the event.completed() method at the end of the process it works correctly.

Thank you very much.

**Closed as not planned** 2024-03-28 18:46 UTC
Labels: Needs: attention :wave:, Area: Outlook
