### ISSUE TITLE
dialog.close is incorrectly asynchronous

### ISSUE THREAD

**Issue by ig-jb** [OfficeDev/office-js#1451] opened 2020-10-21 15:06 UTC
The close method on the Office.Dialog returned in the callback to Office.context.ui.displayDialogAsync is not listed in the documentation as an asynchronous method (https://docs.microsoft.com/en-us/javascript/api/office/office.dialog?view=word-js-preview#close--), and you cannot await it or provide a callback to be called once the dialog has been closed.

This means if you wish to display a dialog after closing a dialog, you must yield using setTimeout; otherwise you receive the following error:
```
code: 12007
message: "The operation failed because this add-in already has an active dialog."
name: "Display Dialog Error"
```

## Expected Behavior
Either:
1. Office.Dialog.close is synchronous
2. Office.Dialog.close returns a promise
3. Office.Dialog.close accepts a callback

## Current Behavior
Office.Dialog.close is asynchronous and provides no callback mechanism. This behaviour is not documented.

## Steps to Reproduce, or Live Example
Script lab example (closing dialog, then opening a new dialog)
```
name: Blank snippet
description: Create a new snippet from a blank template.
host: OUTLOOK
api_set: {}
script:
  content: |
    $("#run").click(run);

    function run() {
      Office.context.ui.displayDialogAsync("https://script-lab.azureedge.net/", { width: 50, height: 50, displayInIframe: true }, (result: Office.AsyncResult<Office.Dialog>) => {
        switch (result.status) {
          case Office.AsyncResultStatus.Succeeded: {
            const dialog = result.value;
            dialog.close();
            Office.context.ui.displayDialogAsync("https://script-lab.azureedge.net/", { width: 50, height: 50, displayInIframe: true }, (result: Office.AsyncResult<Office.Dialog>) => {
              switch (result.status) {
                case Office.AsyncResultStatus.Succeeded: {
                  console.log("Everything's fine");
                  break;
                }
                default: {
                  console.log("Something went wrong");
                  console.log(result);
                  break;
                }
              }
            });
            break;
          }
        }
      });
    }
  language: typescript
template:
  content: |
    <button id="run" class="ms-Button">
        <span class="ms-Button-label">Run</span>
    </button>
  language: html
style:
  content: |-
    section.samples {
        margin-top: 20px;
    }

    section.samples .ms-Button, section.setup .ms-Button {
        display: block;
        margin-bottom: 5px;
        margin-left: 20px;
        min-width: 80px;
    }
  language: css
libraries: |
  https://appsforoffice.microsoft.com/lib/1/hosted/office.js
  @types/office-js

  office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
  office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

  core-js@2.4.1/client/core.min.js
  @types/core-js

  jquery@3.1.1
  @types/jquery@3.3.1
```
## Context
This is problematic when using a Dialog for authentication, and then subsequently for displaying content that requires the user to be authenticated. You need to either perform a redirect within the existing dialog, or defer execution arbitrarily to wait for the authentication dialog to close.

## Your Environment
Can be reproduced in any environment

## Useful logs
code: 12007
message: "The operation failed because this add-in already has an active dialog."
name: "Display Dialog Error"

**Comment by lliu113** [comment] 2021-01-28 23:13
@ig-jb - thanks for reporting this! Is there a reason why you are unable to redirect the existing dialog after auth?

**Comment by ig-jb** [comment] 2021-01-29 09:35
@lliu113 The auth dialog renders best as a different size than our content dialogs. Additionally, allowing a redirect URL to be passed into the dialog leaves it wide open to an open redirect attack unless you tightly couple the authentication dialog to approved pages to redirect to. 

However, regardless of reason for closing one dialog and opening another - a synchronous method acting asynchronously without being documented as such is not correct.

**Comment by lliu113** [comment] 2021-01-29 23:43
@ig-jb your concerns are very valid, we do have a locked down surface in the dialog in order to support auth, and it can only redirect to trusted domains in your manifest. For more info, see [Authenticate and Authorize with Dialog API](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api)

I totally see your point about the docs. The method is actually designed to be asynchronous. Please let me know if there are documentation that is stating it to be synchronous, because that would be incorrect. It currently doesn't accept any callbacks by design. Adding a callback will be a new feature ask.

**Comment by ig-jb** [comment] 2021-02-01 08:55
@lliu113 I believe the trusted domain list in the manifest is only used for direct usage when opening a dialog etc? If you window.open or redirect to a url passed into the dialog via query string parameter, it'll happily load despite not being listed in the manifest?

RE: designed to be asynchronous -- in Javascript, the norm is for a function to be synchronous unless it returns a PromiseLike/thenable, accepts a callback as a parameter, or is documented to be asynchronous - so my view would be the design is incorrect. 

I don't mind whether this gets changed to return a promise, changed to accept a callback, or the documentation changed to state that it is asynchronous; but I would disagree with it being a feature request.

**Comment by lliu113** [comment] 2021-02-04 23:09
@ig-jb - yes - the trusted domain list is only used for opening the dialog. It can redirect to any other domain, but must be back on a trusted domain to communicate back to the taskpane. 

And I completely agree that this should be documented, the current design is indeed odd. I'll log a work item with the content team to update our docs, appreciate the feedback.

**Comment by ig-jb** [comment] 2021-02-05 09:17
Thanks @lliu113

**Comment by lliu113** [comment] 2021-02-08 21:32
@ig-jb - I'll go ahead and close this bug, thanks for reporting it. Will work with our doc team to get the info updated so it's clear that the API is async. Thanks!

**Closed as completed by lliu113** 2021-02-08 21:32 UTC
Labels: Area: add-ins platform

**Comment by Rick-Kirkham** [comment] 2021-02-25 21:17
The docs are updated: https://docs.microsoft.com/en-us/javascript/api/office/office.dialog?view=common-js#close__
