### ISSUE TITLE
Event-based activations not triggered on Outlook web client add-ins

### ISSUE THREAD

**Issue by nicolasmendonca** [OfficeDev/office-js#2839] opened 2022-09-15 12:22 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform: Outlook web client
* Host: Outlook
* Office version number: - (Web)
* Operating System: Mac OS Ventura
* Browser (if using Office on the web): Chrome 105.0.5195.102
 
## Expected behavior
Event-based activations should be working on the Outlook web client for emails and appointments. Which currently work on the native Mac OS Client.

## Current behavior
Side-loading an add-in on the Outlook Mac OS client loads the add-in correctly, and activates all the functions associated to events (for example, `OnAppointmentAttendeesChanged`). But side-loading an add-in on the outlook web client does not. None of the event activations provided by the [outlook-encrypt-attachment](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-encrypt-attachments) sample nor the [outlook-set-signature](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-set-signature) sample works on the web, but they do work on the desktop client.

### Broken path: Web client
1. Visit https://outlook.live.com/calendar/
2. New event > Get Add-ins > My Add-ins > "Add Custom Addins" > From URL > Paste "https://officedev.github.io/Office-Add-in-samples/Samples/outlook-encrypt-attachments/manifest.xml"
3. Go back to the calendar app > Click on the three dots button > click "Event Activation Example" addin > The sidepanel shows as expected
4. Discard the event and create a new one
5. Add a new participant to the event and expect a notification / or add any lightweight attachment and expect an automatically generated encrypted version of the attachment
6. Nothing happens 🤷 . According to the docs, a notification message should be shown

### Working path: Native desktop client
1. Follow steps 1 to 4 from above
2. Add a new participant to the event
3. A notification is shown at the top of the event indicating that an attendee was added to the meeting

## Link to live example(s)
\-

# Provide additional details
\-

## Context

I'm working on an outlook add-in that requires to setup some meeting room links associated with a time and date. And in order to keep our backend updated with the availability time of the virtual meeting room, we need to detect event metadata changes (such as time/date changes, new attendees, etc).

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Screen recording: non-working path on web client**
https://www.loom.com/share/6d925bf64568415d889cf6525a8e83cf

**Screen recording: working path on desktop client**
https://www.loom.com/share/6a18e045388c470f98a9f21f5a09fd59

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 

---

Thanks so much for your support!

**Comment by exextoc** [comment] 2022-09-16 10:38
@nicolasmendonca Thanks for bringing this up. We are looking into the issue and will get back as soon we have an update.

**Comment by nicolasmendonca** [comment] 2022-09-19 20:25
BTW I posted a question related to this issue on stackoverflow [here](https://stackoverflow.com/questions/73717544/outlook-add-in-event-based-activations-not-working-on-web-browser), and I've got a reply where it says that the API is not supported for non-365 users. Which I signed up for the 90 day trial for developers and now I got it working.

Personally, as I don't fully understand how the office 365 product works, I would expect this API to be supported. May I ask why isn't this feature supported for non-365 subscribers? this restriction will impact the users of my add-in.

Thanks!

**Comment by exextoc** [comment] 2022-09-27 08:25
Event based add-ins are currently supported for commercial accounts as they are only available as part of admin deployment. Supporting event-based activation for user acquired add-ins is on the road map and we will consider this as part of that requirement. We don't have an ETA for this yet.

**Comment by nicolasmendonca** [comment] 2022-09-28 12:03
I understand, thank you so much for clarifying this.

Although I'm a bit concerned with the "OnAppointmentSend" event, which is not working on an https://outlook.office.com/ for my account which I created using the 365 developer program. As soon as I indicate in my manifest that I need the API 1.12, my addin is not longer mounter anymore. And if I omit it, the event command is never invoked. I tried to follow along the example of the "Smart Alerts" and I can't make it work.

If I could prompt the user with some instructions before the event is saved, that would solve most of my problems.

Thank you so much again @exextoc .

**Comment by exextoc** [comment] 2022-09-29 06:52
we need more details to be able to provide guidance and request for your add-in manifest and a repro video.

**Comment by nicolasmendonca** [comment] 2022-10-03 12:41
Hello team, thanks for your patience.

I recorded a video explaining my issue here https://www.loom.com/share/9dcd76c5bdfb43a58d9475e995f7fdb8

Basically changing the Requirement sets from 1.10 to 1.12 makes my add-in dissappear.

Here's a cropped version of the manifest.xml I'm using. I'm trying to hide my add-in information for privacy reasons, so let me know if you need the full version and I can obfuscate some other references to provide a full example.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">
  <Id>SomeId</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Addin</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Addin" />
  <Description DefaultValue="Addin" />
  <IconUrl DefaultValue="https://localhost:4173/icon-64.png" />
  <HighResolutionIconUrl DefaultValue="https://localhost:4173/icon-128.png" />
  <SupportUrl DefaultValue="https://www.ericlegaultconsulting.com" />
  <AppDomains>
    <AppDomain>https://localhost:4173</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.12" /> <!-- I changed this here -->
    </Sets>
  </Requirements>

  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:4173/commands/index.html" />
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
    <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Read" />
    <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Edit" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Description resid="AppDescription" />
      <Requirements>
        <bt:Sets DefaultMinVersion="1.12"> <!-- I changed this here -->
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">

          <Runtimes>
            <Runtime resid="WebViewRuntime.Url">
              <Override type="javascript" resid="JSRuntime.Url" />
            </Runtime>
          </Runtimes>

          <DesktopFormFactor>
            <FunctionFile resid="WebViewRuntime.Url" />

            <ExtensionPoint xsi:type="LaunchEvent">
              <LaunchEvents>
                <LaunchEvent Type="OnAppointmentAttendeesChanged" FunctionName="onAppointmentAttendeesChangedHandler" />
                <LaunchEvent Type="OnAppointmentTimeChanged" FunctionName="onAppointmentTimeChangedHandler" />
              </LaunchEvents>
              <SourceLocation resid="WebViewRuntime.Url" />
            </ExtensionPoint>

...
```

**Comment by exextoc** [comment] 2022-10-06 14:29
Will it be possible for you to send the manifest over mail: OutlookExtensibility@M365x27035562.onmicrosoft.com ?
(Please send a sample add-in where we can reproduce the issue, and hide all non important details)

**Comment by stefanoslig** [comment] 2022-10-07 13:46
It's the same for me. After changing the Requirement set from 1.11 to 1.12, the add-in is not visible anymore

The only change I made in the manifest was to change the DefaultMinVersion and MinVersion to 1.12 from 1.11. After this change, the add-in is installed but it's not appearing in the "My add-ins" section and it's not possible to use it when I compose a message

**Comment by exextoc** [comment] 2022-10-09 13:17
The manifest provided above is incomplete. We tried to install it by completing it but were not able to reproduce the issue. 
It'll be great if you can send the manifest over to OutlookExtensibility@M365x27035562.onmicrosoft.com so that we can install it and reproduce the issue. 
(Please send a sample add-in where we can reproduce the issue, and hide all non-important details)

**Comment by stefanoslig** [comment] 2022-10-09 13:59
@exextoc thanks for your reply. 

No need to send my own manifest. I have the same problem with the manifest created from the Yeoman Generator. For example, this is the manifest from the app created with the generator. The only thing I changed is the DefaultMinVersion. Even when I install this add-in, I cannot see it after the installation in the "My admins" section and I cannot use it.

I try to install this add-in on OWA / Macbook

Check the following recording as well. I'm trying to install the Yeoman generated add-in:

https://user-images.githubusercontent.com/6942946/194761426-e02d3ef1-70e5-4d38-b3a7-70f7e450337a.mov

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">
  <Id>d20880b2-59c4-4c22-9c5e-2800c745fa16</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Contoso</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="test-addin"/>
  <Description DefaultValue="A template to get started."/>
  <IconUrl DefaultValue="https://localhost:3000/assets/icon-64.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:3000/assets/icon-128.png"/>
  <SupportUrl DefaultValue="https://www.contoso.com/help"/>
  <AppDomains>
    <AppDomain>https://www.contoso.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.12"/>
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Requirements>
      <bt:Sets DefaultMinVersion="1.12">
        <bt:Set Name="Mailbox"/>
      </bt:Sets>
    </Requirements>
    <Hosts>
      <Host xsi:type="MailHost">
        <DesktopFormFactor>
          <FunctionFile resid="Commands.Url"/>
          <ExtensionPoint xsi:type="MessageReadCommandSurface">
            <OfficeTab id="TabDefault">
              <Group id="msgReadGroup">
                <Label resid="GroupLabel"/>
                <Control xsi:type="Button" id="msgReadOpenPaneButton">
                  <Label resid="TaskpaneButton.Label"/>
                  <Supertip>
                    <Title resid="TaskpaneButton.Label"/>
                    <Description resid="TaskpaneButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
                <Control xsi:type="Button" id="ActionButton">
                  <Label resid="ActionButton.Label"/>
                  <Supertip>
                    <Title resid="ActionButton.Label"/>
                    <Description resid="ActionButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>action</FunctionName>
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16x16" DefaultValue="https://localhost:3000/assets/icon-16.png"/>
        <bt:Image id="Icon.32x32" DefaultValue="https://localhost:3000/assets/icon-32.png"/>
        <bt:Image id="Icon.80x80" DefaultValue="https://localhost:3000/assets/icon-80.png"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="Commands.Url" DefaultValue="https://localhost:3000/commands.html"/>
        <bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/taskpane.html"/>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="GroupLabel" DefaultValue="Contoso Add-in"/>
        <bt:String id="TaskpaneButton.Label" DefaultValue="Show Taskpane"/>
        <bt:String id="ActionButton.Label" DefaultValue="Perform an action"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Opens a pane displaying all available properties."/>
        <bt:String id="ActionButton.Tooltip" DefaultValue="Perform an action when clicked."/>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>
```

**Comment by stefanoslig** [comment] 2022-10-11 07:47
@exextoc did you manage to reproduce this one?

**Comment by exextoc** [comment] 2022-10-12 15:01
@stefanoslig , we are able to reproduce it. We are looking into it and will provide some update soon.

**Comment by nicolasmendonca** [comment] 2022-10-12 17:33
Thank you team!

**Comment by stefanoslig** [comment] 2022-10-12 18:36
thank you!

**Comment by exextoc** [comment] 2022-10-20 07:56
@stefanoslig we have checked in a fix and it is presently rolling out. It should be available within a week.

**Comment by nicolasmendonca** [comment] 2022-10-21 17:50
Good to know! thank you team!

**Comment by exextoc** [comment] 2022-10-27 06:09
We have fixed the bug and the fix should be available in Production now.

**Comment by stefanoslig** [comment] 2022-10-28 08:49
thanks @exextoc !

**Closed as completed** 2022-11-04 11:01 UTC
Labels: Area: Outlook, Type: product bug, Needs: author feedback, Area: add-ins platform, Status: no recent activity
