### ISSUE TITLE
Getting emailaddress from shared mailbox in Outlook Client

### ISSUE THREAD

**Issue by Crikkelieke1** [OfficeDev/office-js#3381] opened 2023-05-23 13:01 UTC
I want to transfer a mail from a shared mailbox with my Outlook Webaddin. I use Javascript.

I retreive the emailaddress by "const emailAddress = office.context.mailbox.userProfile.emailAddress" then I put it in "fetch(https://graph.microsoft.com/v1.0/users/${**emailAddress**}/messages/${emailId}/$value," to get the mail to transfer.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop Windows 
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2303 Build 16.0.16227.20202) 64 bits 
* Operating System: W10
* Browser (if using Office on the web): /
 
## Expected behavior
I retreive the emailaddress by "const emailAddress = office.context.mailbox.userProfile.emailAddress" then I put it in "fetch(https://graph.microsoft.com/v1.0/users/${**emailAddress**}/messages/${emailId}/$value," to get the mail to transfer. Works in Outlook client in shared mailbox

## Current behavior
On Owa it works. If I'm in my own mailbox it gives "me@domain.com", I'm in a shared mailbox it gives "shared@domain.com".

The problem is in my Outlook client. I stays on "me@domain.com" also if I'm working in a shared mailbox. So I want to get the mail from "shared@domain.com" but it search in "me@domain.com"

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by zhngx1** [comment] 2023-06-12 21:05
Will you be able to install ScriptLab add-in in Outlook Desktop? If you are, can you try make the same "Office.context.mailbox.userProfile.emailAddress" call and see if it returns the correct email address?

**Comment by Crikkelieke1** [comment] 2023-06-14 08:28
Hi,

I tested it but it gives also my personal emailaddress when I'm in a shared mailbox on Outlook client (Microsoft® Outlook® for Microsoft 365 MSO (Version 2208 Build 16.0.15601.20526) 32-bit )

Kg

**Comment by zhngx1** [comment] 2023-06-14 22:50
Closing it as it's a duplicate of #1348

**Closed as completed by zhngx1** 2023-06-14 22:50 UTC
Labels: Needs: attention :wave:, Area: Outlook
