### ISSUE TITLE
Office.context.ui.openBrowserWindow opens 'You'll need a new app to open this about link' empty application selector popup

### ISSUE THREAD

**Issue by fgyula17** [OfficeDev/office-js#3084] opened 2023-01-12 10:15 UTC
In Outlook if we call Office.context.ui.openBrowserWindow with a Url pointing to a file to download, the Windows's application selector popup is shown for the user with the title 'You'll need a new app to open this about link' with the option 'Look for an app in the Microsoft Store'. The file is downloaded so that part is working and after the download the application selector popup disappears as it gets out of focus.

The application selector pupop was not shown before.

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2211 Build 16.0.15831.20098) 64-bit 
* Operating System: Windows 10
* Browser (if using Office on the web): -
 
## Expected behavior
The 'Look for an app in the Microsoft Store' should not be shown for the user.

## Current behavior
The 'Look for an app in the Microsoft Store' is shown for the user.

## Steps to reproduce
Use Office.context.ui.openBrowserWindow with a url pointing to a file in Outlook

![Screenshot 2023-01-12 10 27 38](https://user-images.githubusercontent.com/37736159/212039969-d15f32ce-141b-4a07-b241-090ef3dd16ec.png)

**Comment by AlexJerabek** [comment] 2023-01-12 18:22
Hi @fgyula17, 

Thanks for reporting this issue. @exextoc, could you please investigate?

**Comment by samantharamon** [comment] 2023-01-18 01:51
Hi @fgyula17,

Thanks for reaching out. I'm wondering if this issue you're experiencing was caused by the [recent Microsoft Defender threat detection update](https://learn.microsoft.com/windows/release-health/status-windows-11-22h2#2998msgdesc). If you haven't already, please follow the 'Next steps' section in the article to install the fix. Please let me know if that resolves the issue.

**Comment by fgyula17** [comment] 2023-01-18 07:34
Hi @samantharamon,

Thanks for the info, but I'm already on newer version of defender security intelligence and the issue still exists:
![image](https://user-images.githubusercontent.com/37736159/213110700-2b9b74b3-0af0-47b8-8c5c-2fca5bd67e3b.png)

So this is not solving the issue.

This is my Windows version:
Edition	Windows 10 Pro
Version	22H2
Installed on	‎21/‎08/‎2020
OS build	19045.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by samantharamon** [comment] 2023-01-20 01:49
Thanks for verifying, @fgyula17. I tested running `Office.context.ui.openBrowserWindow` in Outlook, which downloaded and opened a .docx file from OneDrive without issues. To help me investigate further, what's the file type/extension you're attempting to open? When you get a chance, one other thing you could verify is whether a default app is configured for the file extension you're trying to open. For assistance with verifying this, see [Change default programs in Windows](https://support.microsoft.com/windows/e5d82cad-17d1-c53b-3505-f10a32e1894d).

**Comment by fgyula17** [comment] 2023-01-24 09:30
@samantharamon It is extension independent. It comes with this link too:
https://www.formula1.com/content/dam/fom-website/sutton/2022/AbuDhabi/Tuesday/1443463015.jpg.transform/9col/image.jpg
The image is opened in browser, so no download in this case but the 'You will need a new app...' popup comes. The issue comes on other machines in out office too.

I have the default photo viewer configured:
![image](https://user-images.githubusercontent.com/37736159/214255675-35414cb8-104d-4873-bebc-46caefdedc54.png)

**Comment by samantharamon** [comment] 2023-01-27 00:50
Thank you, @fgyula17. I tested on a domain-joined and non-domain-joined Windows 10 and Windows 11 machine, however, I'm still unable to replicate the issue you're seeing. I also set the default photo viewer to XnView Classic for Windows in both cases, but I didn't get the pop-up either. I'm wondering if there might be a certain setting in your office domain that may be causing the pop-up. Are you able to test this on a non-work machine by any chance?

**Comment by attilabalazsy** [comment] 2023-02-14 10:26
@samantharamon I'm having the same issue in Outlook desktop and saw at one of my colleagues too. Below you can see my Outlook version. My mailbox is located in O365.

![image](https://user-images.githubusercontent.com/17673937/218708666-1cc9109c-1a83-4ac4-b7f1-c74014da2173.png)


And this is what happens:
![image](https://user-images.githubusercontent.com/17673937/218714145-1a842c89-b69f-4713-84b8-7304a9a25c75.png)

**Comment by attilabalazsy** [comment] 2023-03-03 15:16
Any update on this issue?

**Comment by samantharamon** [comment] 2023-03-03 19:27
Hi @attilabalazsy. Apologies for missing your earlier message, as we received it after the issue was closed.

To help us troubleshoot this further:
- When did this dialog start appearing?
- What Windows version are you and your colleague using?
- Would it be possible to know what add-in you're using? If it was downloaded from the Store, we could test it to see if we can replicate the issue.

Thanks!

**Comment by attilabalazsy** [comment] 2023-03-10 13:09
Hi @samantharamon,

I'm using Windows 10 (latest updates installed)
Some of my colleagues are using windows 11
Everyone is using O365 Office (latest version )
![image](https://user-images.githubusercontent.com/17673937/224323621-4afe7e14-98f2-40c5-bca7-aeec570b30b1.png)
 
The dialog comes, when I click on a link in the app, which downloads a file for me (opens the file URL in the default browser). The file is correctly downloaded by the browser, but next to it, this strange dialog comes to select an app to open with. The same app, the same feature was working till last year december, then this strange popup is appearing. The behavior is the same on all machines, we can repro it everywhere.

**Comment by fgyula17** [comment] 2023-03-10 13:33
Hi @samantharamon 

This is the code we are using for reproducing the issue:
![code](https://user-images.githubusercontent.com/37736159/224328003-f695e46b-b300-40bf-8306-2ccbed1db6d7.jpg)
As you see I added a hardcoded link to an image.

This is what I get when execute the above code:
![ss1](https://user-images.githubusercontent.com/37736159/224328248-3d502e55-ee79-4911-aa0d-65fff79a6294.jpg)

This is the console log from out app (don't care about the link in the 1st line, that is overwritten, but you see that Office.context.ui.openBrowserWindow is available and we are using that to open the url):
![ss2](https://user-images.githubusercontent.com/37736159/224329056-9f4f2c32-4509-4e74-91c4-6ccab1e89191.jpg)

**Comment by samantharamon** [comment] 2023-03-13 22:13
Thank you both for the additional information. We'll look into this further.

**Comment by Dengshan2018** [comment] 2023-04-04 00:18
@fgyula17 , seems the issue might be related with OS. Could you add OS version information(win10 and win11) which can repro the issue?

**Comment by fgyula17** [comment] 2023-04-04 07:07
@Dengshan2018 
![image](https://user-images.githubusercontent.com/37736159/229714776-3236b155-7814-454d-94da-99f57da8d16a.png)

**Comment by attilabalazsy** [comment] 2023-04-05 06:32
@Dengshan2018, my version is exactly the same.

**Comment by fgyula17** [comment] 2023-04-05 09:07
@Dengshan2018 The issue IS NOT reproducible on this machine:
![image](https://user-images.githubusercontent.com/37736159/230034712-85022dbd-0e3a-410a-9f5f-ac705bc5f8aa.png)
![image](https://user-images.githubusercontent.com/37736159/230034753-63478078-a107-47e9-babc-f1c929fb0b7b.png)

But IS reproducible on this machine:
![image](https://user-images.githubusercontent.com/37736159/230035206-234fc655-700d-4d08-9351-5ed54fc986ab.png)
![image](https://user-images.githubusercontent.com/37736159/230035139-60ea3b02-048e-4927-bdaa-294cd522821b.png)
![image](https://user-images.githubusercontent.com/37736159/230035393-09191c41-dfee-4e21-abf4-ce10acd46b2c.png)

**Comment by Dengshan2018** [comment] 2023-04-05 15:17
Thanks @fgyula17 and @attilabalazsy. Is it possible that any of you can record the TTD trace? and share to us. It will be much helpful for debugging the issue.

Just share the link for HOW-TO:
https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record

**Comment by fgyula17** [comment] 2023-04-18 07:52
@Dengshan2018 What process should I record?
I got the option to install the preview version of Outlook and the issue is NOT reproducible there.
"You have Microsoft Outlook Version 1.2023.411.200 (Production).
Client Version is 20230407001.14 ."

**Comment by Dengshan2018** [comment] 2023-04-18 15:59
@fgyula17, Outlook.exe should be recorded if you have other devices which can reproduce the issue.
No familiar with the version of 1.2023.411.200. Could you have a screen shot?

**Comment by fgyula17** [comment] 2023-04-24 07:28
@Dengshan2018 This is how the Outlook looks like:
![image](https://user-images.githubusercontent.com/37736159/233928131-f6d3cedc-fd02-446d-81f5-db23075eab2e.png)
Here you find the TTD file:
https://drive.google.com/file/d/10DjMFwVRJ8ODpNurrhU6Dx1QEBk_kpyL/view?usp=sharing

**Comment by Dengshan2018** [comment] 2023-09-07 23:34
@fgyula17 sorry for late replay. I debug TTD. The issue might come from Javascript. when Office.context.ui.openBrowserWindow is called, the addin is also navigating to "about:blank#blocked". I will close the issue as Not Repro.

**Closed as completed by Dengshan2018** 2023-09-07 23:34 UTC
Labels: Status: under investigation, Area: add-in UI, Type: product question
