### ISSUE TITLE
[Outlook for windows] 5001 Internal Error in Outlook for windows

### ISSUE THREAD

**Issue by Howard-Song** [OfficeDev/office-js#3038] opened 2022-12-13 03:11 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **PC desktop**
* Host [Excel, Word, PowerPoint, etc.]:  **Outlook**
* Office version number: **16.0.14931.20806 and 16.0.14326.21200**
* Operating System: **Windows**
* Browser (if using Office on the web): ______
 
## Expected behavior

Office-JS can return right response in Outlook for windows
## Current behavior

I meet this issue in Outlook for windows when using these code to get body/recipient/attachment every 300ms.
```javascript
$("#run").click(loop);
let errors = [];
function loop() {
 window.Office.context.mailbox.item.to.getAsync((result) => {
     if(!isSuccess(result)) return;
      window.Office.context.mailbox.item.cc.getAsync((result) => {
        if(!isSuccess(result)) return;
        window.Office.context.mailbox.item.bcc.getAsync((result) => {
        if(!isSuccess(result)) return;
        window.Office.context.mailbox.item.getAttachmentsAsync((result) => {
        if(!isSuccess(result)) return;
        window.Office.context.mailbox.item.sessionData.setAsync("test", new Date().getTime() + '', (result) => {
            retry();
        })
            })
              })
      })
    })
}
function retry(){
     setTimeout(()=>loop(),300)
}
function isSuccess(result){
    if(result.status !== window.Office.AsyncResultStatus.Succeeded){
        errors.push(result);
        retry();
        return false;
    }else{
        return true;
    }
}
```
The error in one day(last 24 hours) grown up to 18.9k: 
``` {"name":"Internal Error","message":"An internal error has occurred.","code":5001}```
And only happened in Outlook for windows **16.0.14931.20806** and **16.0.14326.21200**
**Please take a look and how can we avoid this Internal Error when using Office-JS**
![image](https://user-images.githubusercontent.com/28775661/207213498-0520a8e4-8935-419b-92a4-d300fe283460.png)

![image](https://user-images.githubusercontent.com/28775661/207213361-fc8077f8-a7ef-4dc2-b998-7fd243b4f329.png)

## Steps to reproduce

1. open script lab in Outlook for windows 16.0.14931.20806 or 16.0.14326.21200
2. run the above test code
3. will return internal error in console

**Comment by ndeleuze** [comment] 2023-01-12 20:30
I attempted to repro this issue with a slightly newer build (16.0.14931.20888) and was not able to repro. What is your use case scenario that requires retrieving / setting data every 300ms?

Based on your post it seems that only two versions are impacted, and both are older versions.

More details would be helpful for use to fully understand the scenario and impact of the issue.

**Comment by Howard-Song** [comment] 2023-01-13 03:05
In our logs, our clients are not met this issue when using this(16.0.14931.20888) version, only can reproduce in 16.0.14931.20806 and 16.0.14326.21200. This 300ms case is to monitor bodyChange, and change our check status in add-in. Please take a look in the old version, from now there are still many clients using the old version of Outlook, and we can not force clients to update to the latest version.

**Comment by ndeleuze** [comment] 2023-01-17 19:35
Would you be able to provide a bit more detail on your use case here? We need a solid understanding of how you are using the APIs to help more effectively.

**Comment by Howard-Song** [comment] 2023-01-18 01:59
**Use case:**
If user added a special message in email body, we have set an added status in our add-in. After user remove this special message, we need to remove the added status immediately. But Office-JS doesn't have the bodyChange event, so we use setTimeout to call body.getAsync once in 300ms, and set the right status in our add-in.

**Comment by JuaneloJuanelo** [comment] 2023-01-23 19:27
@JesseHeisenberg  the body.getAsync was not designed to be used like this, it can be particularly challenging if the email message is large.  I wonder if is it important to remove that add-in status while the user is typing (in real time?).. is this something you might process after the user sends the email?  I wonder if [smart alerts](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest) which enables you to handle a send event can be used instead? 
FYI we are considering adding something similar to id changes in the body, but as of now we need to explore alternatives.

**Comment by Howard-Song** [comment] 2023-01-29 01:09
Hi @JuaneloJuanelo,  it's really important for us to tracking status change in real time when email body is changed, and this case only exists before user send emails. So onSend event can not help us to handle this.
There are still some question need to think:
1. Do we still need to pay attention to the problem of **5001 Internal Error** in some old outlook version?
2. What's the root cause of this error?

**Comment by JuaneloJuanelo** [comment] 2023-02-10 19:08
Again, polling was not the original intend/design we delivered and doing it with the frequency you are doing it it's not a recommended practice. This could fail for many reasons including the size of the message.  I would strongly recommend you to not do it like this and use smart alerts to validate the content.

We don't have the root cause because we can't repro this issue.  Are you getting this for telemetry only? or you have a solid repro we can debug?

It's also interesting that you are only getting those errors on those builds who happen to be the Semi-Annual Channel build, which might mean most of your customers are in that SKU.  is that the case? 

Also, they are not in the latest version of the semiannual which is 16.0.15601.20456 , is there any possibility that those customers move to the newest update?

An error like this will be super tough to backport [low priority given the randomness of it] it to the Semi-Annual Channel that was forked a year ago.

**Comment by Howard-Song** [comment] 2023-02-15 02:26
Hi @JuaneloJuanelo,  I confirm that all version is come from SKU, and we can not let all these user to update  to newest update, they are from many different company. 
Can you use a same version and run these script to reproduce, these may only happened in these version I can't provide a online demo here.
I know these this loop method is not recommended, but we should continue to pay attention to the hidden dangers of internal errors to avoid causing other unknown problems.

**Comment by JuaneloJuanelo** [comment] 2023-06-13 22:57
We are closing on this issue becasue:
1. does not repro on latest semi annual builds (please ask customers to update)
2.  the item to properly identify body changed events in our backlog and with undeterministic ETA

**Closed as completed by JuaneloJuanelo** 2023-06-13 22:57 UTC
Labels: Needs: attention :wave:, Area: Outlook, Type: product bug
