### ISSUE TITLE
Inserting ooxml does not work in Word version 1906 (Build 11727.20244 Click-to-Run)

### ISSUE THREAD

**Issue by jchilde** [OfficeDev/office-js#617] opened 2019-07-15 22:15 UTC
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

In a Word TaskPane Add-In used for Templating, I copy the body from an existing document and insert the OOXML into the body of the current document using a replace operation.  That has been working as expected for some time.  With the July 9, 2019 release 11727.20244 (targeted monthly), this does not work.  A GeneralException is thrown with the name "RichApi.Error".  I can confirm that this works properly with Version 1906 (Build 11727.20230) and all earlier builds over the past two years.

To confirm this issue, rather than copying from one document to another, I changed the code to copy and replace the body from the current document.  The error still occurs.

See also https://github.com/OfficeDev/office-js/issues/240, 

I think @JuaneloJuanelo has worked on a similar issue from Stack Exchange also https://stackoverflow.com/questions/52097263/inserting-ooxml-into-word-throwing-error-unknown

## Expected Behavior
The body element is replaced with another body element.

## Current Behavior
Using the code below, an error is thrown during the final sync() operation with the following console.error.
[logs.txt](https://github.com/OfficeDev/office-js/files/3394401/logs.txt)
[logs.txt](https://github.com/OfficeDev/office-js/files/3394404/logs.txt)

## Steps to Reproduce, or Live Example
In a word add-in, run the following function:
` private _copyTemplate(body: string): void {
        Word.run((ctx: Word.RequestContext) => {
            var currentBody = ctx.document.body;
            ctx.load(currentBody);            
            return ctx.sync().then(() => {
                var currentBodyOOXML = currentBody.getOoxml();
                ctx.sync().then(() => {
                    console.log(currentBodyOOXML.value);
                    currentBody.insertOoxml(currentBodyOOXML.value, Word.InsertLocation.replace);
                    ctx.sync().then(() => {
                        console.log("complete");
                    }).catch(console.error);
                });                
            });
        });
    }`

n/a

## Context
This issue has affected all users on the Monthly Targeted and non-Targeted schedule that updated to the July 9, 2019 release 11727.20244 (Click to Run).  I don't have other non-click to run versions to test on, so the problem may be on other versions.  Machines running previous versions continue to work properly.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Monthly Channel Version 1906 (Build 11727.20244) Click to Run
* Operating System: Windows 10
* Browser (if using Office Online): N/A

## Useful logs
Below is the exception thrown.  The full logs are attached.

`{
code: "GeneralException", 
debugInfo: {
code: "GeneralException",
errorLocation: "Document._GetObjectByReferenceId",
fullStatements: {
0: "var v=context.root._getObjectByReferenceId("b!0000003D") /* originally body */;"
1: "var insertOoxml=v.insertOoxml("<?xml version=\"1.0\" standalone=\"yes\"?>\r\n<?mso-application progid=\"Word.Document\"?>\r\n<pkg:package...[TRUNCATED]...</pkg:package>\r\n", "Replace");"
},
message: "GeneralException"
statement: "var v=context.root._getObjectByReferenceId("b!0000003D") /* originally body */;"
},
description: "GeneralException", 
innerError: null, 
name: "RichApi.Error",
stack: "GeneralException: GeneralException at Anonymous function (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.debug.js:12571:6) at run (https://localhost:44372/dist/main.js?v=kWMkIvS9YkRYRcN3cZqZR_1duTvuoz1jQpUq4GhF6rg:27761:13) at Anonymous function (https://localhost:44372/dist/main.js?v=kWMkIvS9YkRYRcN3cZqZR_1duTvuoz1jQpUq4GhF6rg:27778:30) at flush (https://localhost:44372/dist/main.js?v=kWMkIvS9YkRYRcN3cZqZR_1duTvuoz1jQpUq4GhF6rg:27332:9)"
}`

**Comment by jchilde** [comment] 2019-07-16 05:12
After further testing, I have found a workaround, but not a great one.  Instead of
`currentBody.insertOoxml(currentBodyOOXML.value, Word.InsertLocation.replace)`

if you use 
`Office.context.document.setSelectedDataAsync(body, { coercionType: Office.CoercionType.Ooxml });`
then the body is correctly inserted at the cursor location.  Of course if a user has the cursor in the header/footer or some other location, then this won't work as expected.  If the cursor is in the body, then it will insert, but will not replace the body.   One could also do a clear() of the body to achieve the same effect if the cursor is in the body.

This tells me that the problem is definitely not malformed Oooxml.

The above work around works in all versions of word.

**Comment by jonknowles** [comment] 2019-07-18 19:27
I experienced a very similar issue on 11727.20244, resulting in a RichAPI AccessDenied error in my case. I reverted my Word version to 11727.20230 using the instructions [here](https://www.msoutlook.info/question/784) and that fixed my addin.

**Comment by jchilde** [comment] 2019-07-19 01:54
Jon, I tried the fix you mentioned.  I have one computer still on that version  that works.  Roll back using above recommendation doesn’t work on my machines.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by denipop83** [comment] 2019-07-26 06:52
I experienced a similar problem, but in PowerPoint 2016 product (2016 MSO (16.0.4849.1000) 64-bit) (PowerPoint add-in panel), resulting in a RichAPI AccessDenied error in my case, when using `Office.context.document.setSelectedDataAsync("string")` method.

using this:
```
Office.context.document.setSelectedDataAsync(base64ImageUri, 
{
coercionType: Office.CoercionType.Image, imageHeight: defaultImageHeight, imageLeft: 0, imageTop: 0
});
```
results the same.

Rolling back to 1809 (build 10827.20181) fixed the problem.

Any chances that it will be work in future?

**Comment by jchilde** [comment] 2019-09-05 19:13
So now my users are on version 1908 (11929.20254) and the workaround mentioned here https://github.com/OfficeDev/office-js/issues/617#issuecomment-511667536 has now stopped working.  I will do further troubleshooting to try and identify the error; however, the "Resolution: has workaround" should now be removed from the tags since the work around has now been broken as well.

**Comment by jchilde** [comment] 2019-09-05 22:53
Upon further troubleshooting, this bug appears to be related to https://github.com/OfficeDev/office-js/issues/697.

Based on my troubleshooting, inserting smaller OOXML bytes does in fact work.   Only when the size of the Ooxml to be inserted gets to around 60K bytes or larger does insertion fail.

Not sure what magic words I need to use next time, but seems like this and but 697 were easily preventable before GA.

**Comment by samuelkdavis-mccarthyfinch** [comment] 2019-09-05 23:59
My issue #702 was closed as a duplicate of #697 which is hopefully correct given all the responses from MS saying they're unable to reproduce the issue. The issue is specific to add-ins using the latest version of office, and using Edge as the rendering engine.

My issue is getOoxml with msword, fails for large documents & works for small documents. The example I provided was the standard Visual Studio templated MSWord addin, with the addition of adding pages of text & and running the failing getOoxml method.

#697 says there's a fix to the issue planned for ~10th of this month.

**Comment by jchilde** [comment] 2019-09-10 16:34
I can confirm that today's update to version 1909 (12026.20108 Click-To-Run) fixed the issue at this post https://github.com/OfficeDev/office-js/issues/617#issuecomment-528537479.

What prompted that comment was the conversion of a document from file was failing.  I incorrectly assumed that the workaround https://github.com/OfficeDev/office-js/issues/617#issuecomment-511667536 was also broken.  It wasn't.  

The workaround continues to work.

The original bug still exists in that I can paste OOXML into the body of a document, but I cannot "Replace" the body of a document with the body of another document.  

So, the bug is still there.

**Comment by fiddler** [comment] 2020-02-18 07:46
This bug seems to be still alive and well. Tested on Word For Mac Version 16.32 (19120802).

The same code can replace OOXML just fine with small payloads, but when the size of the OOXML payload becomes big enough it starts failing with `GeneralException: RichApi.Error`.

What's the status of this? Any fix in sight?

**Comment by mishu-** [comment] 2020-04-19 11:30
Still around!

**Closed as not planned** 2024-03-28 18:47 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: Word, Area: add-ins platform
