### ISSUE TITLE
Wrong Dialog Title  on MAC dialogs

### ISSUE THREAD

**Issue by DotNet-Fan** [OfficeDev/office-js#772] opened 2019-10-11 13:36 UTC
In MAC , the dialog title is coming as "Office Add-ins - "xxxx.xxxx.com"".
## Expected Behavior
It should behave the same as in Windows - "App name" - "html title tag contents" "

## Current Behavior

In MAC , the dialog title is coming as "Office Add-ins - "xxxx.xxxx.com".

## Steps to Reproduce, or Live Example
Create a html with title tag - <title>XXXXXX</title>
In Mac , open the html within the Dialog.
Check the title text

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ____MAC_
* Host [Excel, Word, PowerPoint, etc.]: __Excel,Word,Powerpoint____
* Office version number: ______Office 2016, 2019
* Operating System: ______MAC High sierra
* Browser (if using Office Online): ______

**Comment by mpetro-t** [comment] 2019-10-11 17:58
I want to add that this same bug happens on PC too since updating to Edge WebView control.

**Comment by lliu113** [comment] 2021-05-05 22:49
@Kallzz @mpetro-t - sorry for the very late response to this, and thank you for the feedback. The difference in dialog titles is by design. We have a work item in our backlog to normalize the titles across platform, but we have no ETA to share currently. 

I'll go ahead and close this issue for now, feel free to reactivate as necessary. Thanks!

**Closed as completed by lliu113** 2021-05-05 22:49 UTC
Labels: Type: product bug, Area: add-in UI, Resolution: by design, Status: in backlog
