### ISSUE TITLE
Admin-managed Add-in is *missing* on Outlook for Mac but it is available on Windows and web client

### ISSUE THREAD

**Issue by tuskar-dev** [OfficeDev/office-js#4694] opened 2024-07-17 13:24 UTC
# Provide required information needed to triage your issue
This might be a bit off topic as it is more of a infrastructure issue than this library. But we are seeking help here after contacting Outlook for Mac support team. So the issue is that we can not see our Add-in on MacOS platform, it's not listed under Admin-managed Add-ins like it is on web and Windows client. We tried suggested fixes from SO to give full disk access and enabling/disabling privacy settings but none of it helped. We hope that you can help us with solving this issue, if you need any logs or info from our side please let us know.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook for Mac 16.86.3
* Office version number:  16.86.3
* Operating System: MacOS Sonoma 14.4
* Browser (if using Office on the web): Chrome 126
 
## Expected behavior

Admin-managed Add-in should be listed under Admin-managed but it is no where to be found.

## Current behavior
Add-in is not listed under Admin-managed Add-ins on Outlook for Mac.

## Steps to reproduce

Deploy an add-in and check if it's available across all platforms.

**Comment by AlexJerabek** [comment] 2024-07-18 00:01
Thanks for reporting this @tuskar-dev.

@exextoc, could you please investigate?

**Comment by kumarshrey-msft** [comment] 2024-07-21 18:07
Hi @tuskar-dev, as mentioned in our [public documentation](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide#deploy-an-office-add-in-using-the-admin-center), Outlook add-ins can take up to 24 hours to appear on a client. A few queries:

1. Can you let know how long it has been since this specific add-in was deployed? 
2. Does this add-in work on Outlook Mac after sideloading?

**Comment by tuskar-dev** [comment] 2024-07-22 09:20
Hi @kumarshrey-msft ,

1. The add-in has been deployed for around 2 months already, so the time constraint is not an issue here I guess, as it has already propagated to all accounts on other platforms.

2. That also doesn't work. On upload of manifest file directly on local client it will show the add-in under My add-ins and it will fetch the image from remote server and show the Add-in but once I close Add-ins settings it will disappear on the next opening of Add-ins settings.

Thank you for your assistance, I hope we will resolve this issue.

**Comment by neprasad-microsoft** [comment] 2024-07-23 06:06
Hi @tuskar-dev 
Can you share the add-in manifest? You can create a private repo and add the manifest. Share it with exextoc. 
Please try to share the actual deployed manifest instead of the localhost one. Thanks.

**Comment by tuskar-dev** [comment] 2024-07-24 06:11
Hi @neprasad-microsoft,

I have created a private repo with production manifest.xlm, I have added @exextoc as collaborator. The repo is under this link https://github.com/tuskar-dev/outlook-addin

Thank you

**Comment by neprasad-microsoft** [comment] 2024-07-25 12:48
Hi @tuskar-dev, 
Thanks for reporting this issue regarding add-in installation. We were able to reproduce this, and it has been put on our backlog. We unfortunately have no timelines to share at this point
 
Internal tracking id: Office: [4763783]

**Comment by MariaLawrenceAntony** [comment] 2024-07-29 16:25
@neprasad-microsoft I am facing this issue for the past 1 month. Could you please give some updates when this will be resolved. Also sometimes assigned add-ins not automatically showing up in user machine. I assigned it to 1500 users and it showed up for only 400 users. Office add-in deployment always a nightmare.

**Comment by tuskar-dev** [comment] 2024-08-13 00:26
Hi @neprasad-microsoft,

Thank you for reproducing and confirming the issue. Any update on the fix?

**Comment by anjalitp** [comment] 2024-08-19 04:19
@tuskar-dev Could you please remove Host section (mentioned below) from VersionOverride1_0 and try installing the add-in.
```
<Hosts>
            <Host xsi:type="MailHost"/>
  </Hosts>
```

**Comment by tuskar-dev** [comment] 2024-08-20 00:06
Hi @anjalitp, 

Thank you for your comment, but unfortunately removing MailHost inside Hosts tag for version overrides 1.0 did not help. The manifest is passing the check as valid as you can see on the screenshot, but it is still disappearing upon installing and reopening My Add-ins section. It's still no where to be found in the Outlook client.

<img width="711" alt="Screenshot 2024-08-20 at 01 58 02" src="https://github.com/user-attachments/assets/08982096-07ab-4cd6-aa72-f0deeadd1725">

**Comment by anjalitp** [comment] 2024-08-20 07:17
Are you installing from Outlook Mac? Could you please try installing using https://aka.ms/olksideload ? Then, restart Outlook Mac and see if add-in reflects on the Toolbar.

**Comment by tuskar-dev** [comment] 2024-08-23 14:50
Hi,

I was indeed installing inside Outlook client.

Installing via sideload link did help and the add-on is now visible in Outlook for Mac client. But the issue still remains as we can't use this sideloading method to add add-in to all users within organization. They do not have the rights to add add-ins themselves.

Thank you

**Comment by anjalitp** [comment] 2024-08-26 02:18
@tuskar-dev Please try deploying the updated manifest (after removing the Host section in VersionOverride1_0) and the add-in should appear on Mac.

**Closed as completed** 2024-09-02 07:24 UTC
Labels: Area: Outlook, Type: product bug, Needs: author feedback, Status: in backlog, Status: no recent activity
