### ISSUE TITLE
displayNewAppointmentForm fails on Outlook for Mac when body contains more than 255 characters

### ISSUE THREAD

**Issue by neso613** [OfficeDev/office-js#117] opened 2018-05-04 03:31 UTC
I am developing an Outlook for Mac Add-in using Office.js. I am using `Office.context.mailbox.displayNewAppointmentForm()` to open an Appointment window programmatically:

``` js
Office.context.mailbox.displayNewAppointmentForm(
{
  location: '{Location}',
  subject: '{subject}',
  body: '{some large text}'
});
```

If the body text is 255 characters or less, then the appointment window gets opened with the pre-populated body, subject, and location. But if the body text exceeds that size, no appointment window is opened.

I know that there is a limit of 32KB for the appointment form's body but my text is not more than that. (I have confirmed it on a character to KB converter).

If I add a `subject` and the text exceeds more than 255 characters (specified in API documentation), it gives an exception. 

For the `body` it gives no exception with more than 255 characters but does not open new Appointment window.

I am also sharing a link to a [demo project](https://drive.google.com/file/d/1NoWfxd8p3kYQ1AkRXtE0DS4NmyN4PmiY/view?usp=sharing). It works on Outlook for Web and Outlook for Windows but failed Outlook for Mac.

**Comment by kanak-infoObjects** [comment] 2018-05-04 07:22
Am also facing the same issue and already posted the question on StackOverflow. I am not getting any help over there. 

The same application works fine on Windows platform but failing for  Mac. Seems like it is a bug. Reference of SO post -

[https://stackoverflow.com/questions/49921467/size-issue-with-body-of-office-context-mailbox-displaynewappointmentform-with-te](https://stackoverflow.com/questions/49921467/size-issue-with-body-of-office-context-mailbox-displaynewappointmentform-with-te)

**Comment by kanak-infoObjects** [comment] 2018-05-08 16:24
Hey @mlafleur Did you get some time to look into this issue? My plugin development is complete and ready to publish and this bug is a showstopper in this direction.

**Comment by kanak-infoObjects** [comment] 2018-05-18 08:09
Hi @exextoc, just wanted to check how long will it take to get fixed? :)

**Comment by kanak-infoObjects** [comment] 2018-05-28 09:07
Humble request for an update.

**Comment by macOutlookExtensibility** [comment] 2018-05-29 09:53
This fix has been checked in. Please use build version > 180518

**Comment by kanak-infoObjects** [comment] 2018-05-29 10:16
Thanks, @macOutlookExtensibility how do I find this build version and the office js with this fix?

**Comment by kanak-infoObjects** [comment] 2018-05-31 06:44
Hi all,

If you are suggesting about outlook build version. I have upgraded to latest outlook build and still, I can see this bug. Please update me the correct way to get the fix.

Previous version: Microsoft Outlook for Mac Version 16.11 (180311) License: Office 365 Subscription
Current version: Microsoft Outlook for Mac Version 16.13.1 (180523) License: Office 365 Subscription

**Comment by bandhan-nawal** [comment] 2018-06-12 06:02
Hi all, I am also facing this issue. Please respond asap.

**Comment by macOutlookExtensibility** [comment] 2018-06-12 07:59
HI,
Could you please try the latest insider fast build and verify if the issue is still happening. 
Instructions to get insider fast build is available here:  (https://products.office.com/en-in/office-insider?tab=Mac ).                
16.13.1 (180523) is a production build and do not have this fix.

**Comment by bandhan-nawal** [comment] 2018-06-12 09:15
Hi,
Now this is working fine in insider fast build. Thanks a lot.
Can you tell me when will this fix roll out for production builds?

**Comment by macOutlookExtensibility** [comment] 2018-06-12 09:27
Thanks bandhan for confirming it. The fix would be available as part of the July production release which normally happens in the 2nd week of July.

**Comment by exextoc** [comment] 2018-06-12 20:02
Related to outlook for Mac, so ignoring

**Comment by exextoc** [comment] 2019-07-31 16:02
Closing due to inactivity

**Closed as completed by exextoc** 2019-07-31 16:02 UTC
Labels: Area: Outlook, Type: programming question
