### ISSUE TITLE
Change in behavior on Shared Calendars API

### ISSUE THREAD

**Issue by bx-anil** [OfficeDev/office-js#1193] opened 2020-05-29 21:40 UTC
Accessing Outlook Shared Calendar item via REST API is failing.

## Expected Behavior
When calling 

`https://outlook.office.com/api/v2.0/users/<shareduser@domain.com>/calendar/events/<rest_event_id>?$select=iCalUId`

 fails with 403 error. This was working fine a week ago. But the same endpoint works fine if the add-in app is running locally (localhost) or when using OWA (Outlook web). 

This is callout to get the shared item info 
```
Office.context.mailbox.item.getSharedPropertiesAsync(
                                {
                                    asyncContext: accessToken
                                }, function (resSharedProps) {
                                    var sharedProps = resSharedProps.value;
                                    var itemRestId = getItemRestId(itemId);
                                    var rest_url =
                                        sharedProps.targetRestUrl + "/v2.0/users/" + sharedProps.targetMailbox + "/calendar/events/" + itemRestId + "?$select=iCalUId";
                                    makeRestCall(rest_url, resSharedProps.asyncContext)
                                })
```

## Current Behavior
When accessing https://outlook.office.com/api/v2.0/users/<shareduser@domain.com>/calendar/events/<rest_event_id>?$select=iCalUId fails with 403 error. 
Below is from the response headers: 

> x-ms-diagnostics: 2000008;reason="Delegate access to this API requires the following permissions: 'Calendars.Read.All,Calendars.Read.Shared,Calendars.ReadWrite.All,Calendars.ReadWrite.Shared,Calendars.Write.All,Calendars.Write.Shared'. However, the application only has the following permissions granted: 'Mail.ReadWrite,Mail.Send,Calendars.ReadWrite,Contacts.ReadWrite'.";

This works fine on OWA. The issue is very specific for desktop client.

## Context
This was working earlier and for some reason stopped working. This is affecting our production users. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Desktop PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 365 v1912
* Operating System: Windows 10 v1809
* Browser (if using Office Online): Chrome 80.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment] 2020-05-30 00:12
Thanks for providing a detailed description of the issue.

This error indicates that the `accessToken` is missing the scope needed to access a shared calendar.

I assume the add-in is using `Office.context.mailbox.getCallbackTokenAsync({ isRest: true }, ...` to generate the access token?

While trying to reproduce this issue, I noticed (and verified) there were just two cases where the Shared scopes were omitted from the token. To get the scopes, the add-in manifest must contain both the `ReadWriteMailbox` permission and the `<SupportsSharedFolders>true</SupportsSharedFolders>` element.

Could you double-check that the manifest used for testing in Desktop Outlook contains both of those properties? (Try uninstalling and re-installing the add-in as well just in case an older manifest was cached in Outlook).

Another possibility is if the mailbox is connected to a version of on-premise Exchange that doesn't return the Shared scopes in the access token. Though if all of the testing was done from the same mailbox, this shouldn't be an issue since the token is working in other clients.

**Comment by bx-anil** [comment] 2020-05-30 00:46
Thanks for looking into it.

Yes `Office.context.mailbox.getCallbackTokenAsync({ isRest: true } ...` is the call to get the token.  The manifest hasn't changed for quite sometime and confirming that permissions are ` <Permissions>ReadWriteMailbox</Permissions>` and `<SupportsSharedFolders>true</SupportsSharedFolders>`  on the manifest.

And yes, the mailbox is the same when accessing from OWA and Desktop client. 

Just noticed something: On OWA the end point resolves to `https://outlook.office365.com/api/v2.0/users/<myid@domain.com>/calendar/events/<eventid>$select=iCalUId` vs on desktop `https://outlook.office.com/api/v2.0/users/<shareduser@domain.com>/calendar/events/<rest_event_id>?$select=iCalUId` 
Also nothing hasn't changed on our end AFAIK to reflect this change.
Any insights would be helpful.

**Comment by exextoc** [comment] 2020-06-03 22:46
How is your add-in deployed? If it is deployed using centralized deployment, there is an known issue where getCallbackTokenAsync is returning a token that is missing the shared scope permissions. This issue is being tracked [here](https://github.com/OfficeDev/office-js/issues/1140).

**Comment by bx-anil** [comment] 2020-06-04 13:06
yes the issue is on centralized deployment. Thanks.
Closing this as it is being tracked as a different issue.

**Comment by bx-anil** [comment] 2020-06-24 13:56
Reopening this for tracking even though this is a duplicate

**Comment by exextoc** [comment] 2020-06-26 23:15
I noticed the discussion is based on centralized deployment. I just want to make sure the issue is indeed duplicate. Does your addin work fine if the addin is user installed (not installed via centralized deployment)?  Would user installation be an acceptable deployment method for the short term until this issue is fixed? 

admin can use new-app -mailbox https://docs.microsoft.com/en-us/powershell/module/exchange/new-app?view=exchange-ps to deploy for users without asking user to install manually. The downside is that admin will have do this to update the manifest and also to remove-app and redeploy via centralized deployment, so this is not great for large number of users.

**Comment by bx-anil** [comment] 2020-06-28 11:06
We haven't tested on user deployment. Though the app works locally (dev env) it should most likely work for user deployment as well. We will give it a try.

**Comment by bx-anil** [comment] 2020-07-07 12:08
Tried the new-app command and confirm that it works.

**Comment by exextoc** [comment] 2020-07-13 22:43
This is a duplicate of issue #1140 which we have on our backlog. We don't have any timelines to share regarding this fix.

**Closed as completed by exextoc** 2020-07-13 22:43 UTC
Labels: Area: Outlook
