### ISSUE TITLE
Recipient setAsync not triggering recipient change event on Mac Outlook

### ISSUE THREAD

**Issue by jak-hammond** [OfficeDev/office-js#1211] opened 2020-06-09 15:20 UTC
We have some code setup that will periodically allow the user to update the recipient list of a message. When this code runs, we also have a secondary function that is listening for the recipient change event that will then do some further processing.

When we use add or remove on the recipient, this code is executed, but using the set method, nothing happens.

## Expected Behavior
Registered function on the recipient change event would be fired for all change events; add, remove and set.

## Current Behavior
Set method does not trigger the recipient change event.

## Steps to Reproduce, or Live Example
* Additional details:
  1. Add recipient change handler to the current item
  2. Invoke setAsync on to, cc or bcc recipient item
  3. Change event will not be fired and handler function will not be run

## Context
We are using this to run secondary checks on the recipient list and the functionality works in OWA and Windows Desktop Outlook so we are now in a situation where the Mac Desktop Outlook app is offering our users a degraded experience.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.39 (20060705)
* Operating System: macOS Catalina 10.15.3

**Comment by exextoc** [comment] 2020-06-11 04:41
We cannot reproduce the issue mentioned, can you share the code snippet/manifest used?

**Comment by jak-hammond** [comment] 2020-06-11 09:34
I have recreated the issue in Script Lab for Outlook, the gist link can be found here; https://gist.github.com/jak-hammond/e05378e93ca65f7eb43af2c82ae3b301

The code in the gist replicates the functionality we are offering in our add-in at the moment which runs fine on browser and Windows, but is currently not logging the last recipient change on Mac when Jane Doe is replaced with John Doe

![Chrome](https://user-images.githubusercontent.com/664193/84369634-10673280-abcf-11ea-82bc-a5f0ba7ec02c.png)
![Mac](https://user-images.githubusercontent.com/664193/84369651-13fab980-abcf-11ea-8c59-5eb495beed8e.png)

**Comment by exextoc** [comment] 2020-06-12 08:22
@jak-hammond Thanks for the script, we are able to reproduce the issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment] 2020-07-29 22:37
Internal tracking id: Office:4224491

**Comment by carlosb1504** [comment] 2021-09-16 09:11
Could anyone advise if a fix has been progressed for this issue yet? Thanks

**Comment by exextoc** [comment] 2023-12-15 17:02
This issue has been fixed.

**Closed as completed by exextoc** 2023-12-15 17:02 UTC
Labels: Area: Outlook, Type: product bug, Status: fixed
