### ISSUE TITLE
Outlook plugin reminder time is set to "none" in Outlook 365

### ISSUE THREAD

**Issue by kanaksony** [OfficeDev/office-js#497] opened 2019-05-01 17:10 UTC
I have set the Reminder on Outlook 2016 for Mac Preferences -> Calendar -> Default Reminder (say 15 minutes). In my add-in when I click on a button to open new appointment window using Office.context.mailbox.displayNewAppointmentForm method, the reminder should be shown as 15 minutes. This is working as expected for Outlook for Windows and OWA. Its should also work the same in Mac Outlook 2016.

**Comment by exextoc** [comment] 2019-05-02 17:59
I believe this is a duplicate of #498

**Closed as completed** 2019-05-02 17:58 UTC

**Comment by kanaksony** [comment] 2019-05-02 20:54
Yes.
