### ISSUE TITLE
[Word] content control adds new line

### ISSUE THREAD

**Issue by rvanlaak** [OfficeDev/office-js#339] opened 2018-12-19 10:59 UTC
## Expected Behavior

Content should stay identical when adding content control, and when replacing ooxml with it's own ooxml.

## Current Behavior

Extra line is added with header, paragraph. No extra line gets added when just a few words are selected.

## Steps to Reproduce, or Live Example

```js
Word.run(async (context) =>
{
    const serviceNameRange = context.document.getSelection();
    const cc = serviceNameRange.insertContentControl();

    let ooxml = cc.getOoxml();

    await context.sync();

    cc.insertOoxml(ooxml.value, "Replace");

    return context.sync();
})
.catch((error) =>
{
    console.log("Error: " + error + JSON.stringify(error.debugInfo));
});
```

## Context

Users can not rely on functionality with this bug in place, because they have to fix layout after use.

## Your Environment

* Platform PC desktop
* Host Word
* Office version number: 365
* Operating System: Win 10
* Browser (if using Office Online): ______

## Useful logs

![bug-contentcontrol-header](https://user-images.githubusercontent.com/2707563/50216089-22269b80-0385-11e9-83d8-9dfc21005d28.gif)

**Comment by JuaneloJuanelo** [comment] 2018-12-19 23:36
@rvanlaak can you please share the specific build your are using for Word? And I am asking this because we fixed this issue (long time ago) and it should not be adding a new line.

**Comment by rvanlaak** [comment] 2018-12-20 09:10
We are using Word version 1803, which should be the latest version? https://docs.microsoft.com/en-us/officeupdates/update-history-office365-proplus-by-date

![image](https://user-images.githubusercontent.com/2707563/50275331-624a5480-043f-11e9-8aa0-265749b11324.png)

Is there actually a way for us to write automated tests for this? As in, how can we write functional integration tests for our Word addin?

Are there by any chance some mock test helpers for methods like `Office.context.document.getFileAsync` and `Office.context.document.getSelectedDataAsync`?

**Comment by rvanlaak** [comment] 2019-01-23 16:48
Any update on this bug report?

**Comment by JuaneloJuanelo** [comment] 2019-06-25 19:47
this is effectively a regression, it used to be fixed. we are tracking with 3451201

**Comment by grangeryy** [comment] 2019-07-26 02:12
notice 3451201 is resolved by design.

**Closed as completed by grangeryy** 2019-07-26 02:12 UTC
Labels: Type: product bug, Area: Word

**Comment by rvanlaak** [comment] 2019-07-26 07:22
@grangeryy could you elaborate a bit more on that?

We are preparing for putting lots of effort in migrating our "find and replace" macros to office-js. If the API design changed in a way that is offers us more flexibility as before that would be of great help 💪
