### ISSUE TITLE
Window.location functions replaceState and pushState defined to null in OfficeJS

### ISSUE THREAD

**Issue by Medhyena** [OfficeDev/office-js#1344] opened 2020-08-24 13:52 UTC
The library replaces some native JavaScript functions.

## Expected Behavior
Not to replace native JavaScript functions except if it is an override to implement new features to it.

## Current Behavior
Error when using window.location.replaceState or window.location.pushState. They are defined as null and thus, breaking other libraries using these native JavaScript functions.

Please do not replace such core functions to not break applications.

## Steps to Reproduce, or Live Example
1: Create an addin with OfficeJS
2: Try window.location.replaceState (for example)
3: Application breaks.

## Context
Our authentication system is using these to redirect the user to our application. It's basically impossible to reach the application at this point.

## Your Environment
* Tried on Office of the web for easy debugging (since debugging in the application is a pain). Also breaks in the native application
* Host: Outlook.
* Platform: PC.
* Office: Office365 (so it is mainly up to date but anyway the problem comes from the library, since I found it inside)
* OfficeJS: OfficeJS version 1.1, tried on preview/beta also and had the same bug
* Operating System: Windows 10
* Browser (if using Office on the web): Firefox, also should happen on Chrome but can't test it myself yet because cookies being an issue recently.

**Comment by dbene** [comment] 2020-08-24 17:20
Duplicate of [#429](https://github.com/OfficeDev/office-js/issues/429)

Take a look at this [workaround from stackoverflow](https://stackoverflow.com/a/53662709/6401912). 

I know it is awful that this is still not fixed, or at least added an exveption for Edge like they do for addins on android. See [Line 1901](https://github.com/OfficeDev/office-js/blob/release/dist/office.debug.js#L1901)

**Comment by sumurthy** [comment] 2020-08-26 07:11
This is in the backlog to be fixed.

**Closed as completed by sumurthy** 2020-08-26 07:11 UTC
Labels: Type: product bug, Area: add-ins platform, Status: in backlog, Needs: triage :mag:

**Comment by jcbdev** [comment] 2021-11-19 00:44
This works for me to fix in angular which manifests as a routing loop bug

```
<body>
    <app-root></app-root>
  </body>
  <script>
    // this late load is required due to bug in office-js causing a routing loop
    // https://github.com/OfficeDev/office-js/issues/1198
    // https://github.com/OfficeDev/office-js/issues/1344
    // https://github.com/OfficeDev/office-js/issues/429
    let replaceState = window.history.replaceState;
    let pushState = window.history.pushState;
    var head = document.getElementsByTagName("head")[0];
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.onload = function () {
      Office.onReady().then(() => {
        console.log("Office is ready!");
        window.history.replaceState = replaceState;
        window.history.pushState = pushState;
      });
    };
    script.src = "/assets/office-js/office.js";
    head.appendChild(script);
  </script>
```

**Comment by JimbobTheSailor** [comment] 2023-08-07 00:42
This issue has raised its ugly head again when I updated to Angular 16 and msal-angular 3.0.0-beta (which is required for angular 16).

My purpose in writing is to comment that the workaround as outlined by [jcbdev](https://github.com/jcbdev) is not an optimum solution as it causes asynchronous issues in the loading of Office.js and the subsequent use of its functions. If Office.js is not cached, then any code in `<app-root></app-root>` will execute before Office.js is loaded, resulting in the error "'Office' not defined when you try to use any Office.js functions. To make it work you would need to wire in additional code to wait for Office.js to be loaded into the DOM before bootstrapping your app. 

Or,  alternatively, you can keep everything in sync by modifying [jcbdev](https://github.com/jcbdev) solution slightly as below:


```
<head>
	<script>
		window.myReplaceState = window.history.replaceState;
		window.myPushState = window.history.pushState;
	</script>
	<script src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js" type="text/javascript"></script>
	<script>
		window.history.replaceState = window.myReplaceState;
		window.history.pushState = window.myPushState;
		delete window.myPushState;
		delete window.myReplaceState;
	</script>
<head>
```

**Comment by gergzk** [comment] 2024-03-04 17:59
Hi everyone, 
The dev team has recently made a fix for this issue (removed the override with null). Expect to see it roll out to CDN in the next 1-2 weeks.

**Comment by JimbobTheSailor** [comment] 2024-03-04 23:38
Great news

**Comment by torgestehr** [comment] 2024-04-17 06:42
That's really great news. Are there any updates regarding the rollout to CDN?

**Comment by RK1PF** [comment] 2024-07-05 11:50
> That's really great news. Are there any updates regarding the rollout to CDN?

We are in July 2024 and still no rollout. I was waiting for this change for 2 years, I was initially using Blazor to develop office add-ins but this "issue by design" made me change to React (without any framework or router). Today we are using NextJs in almost every of our projects and can't use it for office add-ins projects.

**Comment by jimages** [comment] 2024-10-29 11:59
It seems the fix still doesn't roll out. Is there any update here?

**Comment by JimbobTheSailor** [comment] 2024-12-30 05:48
Any progress on this fix??
