### ISSUE TITLE
Add-ins don't open on New Outlook for Windows

### ISSUE THREAD

**Issue by pavelstudeny** [OfficeDev/office-js#4262] opened 2024-03-15 16:28 UTC
When clicking an Outlook add-in icon, the add-in does not show up, not even the Polls add-in from Microsoft.

## Environment
* Platform: PC desktop
* Host: New Outlook
* Office version number: 16.0.17328.20184
* Operating System: Windows 11
 
## Expected behavior
Add-in side pane opens

## Current behavior
Clicking the add-in button does not trigger anytning.

## Steps to reproduce

- Launch New Outlook desktop app
- Open “Apps” menu
- Click “Polls” icon

video:
https://github.com/OfficeDev/office-js/assets/8670912/3c38b61e-a6cd-41aa-919d-2c52c684666c

**Comment by bchenhs** [comment] 2024-03-15 21:19
@exextoc  We are also seeing this issue, and getting reports from our users.

From our testing, this issue affects all add-ins, include the default ones from Microsoft (Viva Insights, Teams, etc.)
Microsoft Outlook Version 1.2024.306.400 (Production).
Client Version is 20240308003.09 .

**Comment by ajays-msft** [comment] 2024-03-17 06:03
@pavelstudeny @bchenhs - I tried just now, and not able to repro. Can you please confirm if you are still seeing the issue? If you are still seeing, can you please collect HAR file, put it in a private github repository, and give access to @exextoc? I will analyze the logs to understand what is happening.

**Comment by dmitriikashin-outreach** [comment] 2024-03-18 10:27
@ajays-msft We are still seeing the issue. 

Please note, that

a) It affects almost **all** the Add-ins I have, I added few of new to test, and they are not invoked as well.
b) It doesn't affect "My templates", "Viva insights". Also, doesn't affect Add-ins which don't rely on the Side panel, like "Jira" or "Trello". 
c) The ribbon menu of the Add-in simply does not open
d) The issue is somewhat Mailbox, and **not App**(Add-in) based, as when we switch to the other mailbox by marking it primary, Add-ins start working (same Outlook client. See usage of "Polls" under two different mailboxes in demo), as expected, but when we mark the previous one as primary and try to use any of add-ins - there is no response.

Example of affected mailbox:  dmitrii.kashin@4qx0t4.onmicrosoft.com
Example of not affected mailbox: old_dmitrii@4qx0t4.onmicrosoft.com

The same can be replicated by several people in our org: one account does work and opens Add-ins, the other doesn't. 

See the video:

https://drive.google.com/file/d/1BeF31Kt23PlchgV-j5ELL8r_2SdDHzJz/view?usp=sharing



What kind of logs you would suggest us to provide, considering that Apps (Add-ins) are not invoked? Are there any instructions for getting HAR logs or any other useful logs in such cases? 

Thank you!

**Comment by ajays-msft** [comment] 2024-03-18 13:07
@dmitriikashin-outreach - In "New Outlook" addins are only available in primary accounts. Looks like addins are visible in secondary account and not working, which is causing the confusion. 

Earlier addins wouldn't show up at all in secondary account, but some bug caused the addins to now show up, which is causing the confusion.

@shighosh-msft : Can you please investigate further?

You can open dev tools with New Outlook, go to network tab, repro the issue, and export the har file. You can share that privately. 
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#debug-your-add-in
1

**Comment by dmitriikashin-outreach** [comment] 2024-03-18 13:24
@ajays-msft not really, please check the video. The primary account can't load the add-ins as well. So it's Mailbox-based. Or has some weird correlation. 

Doesn't matter if  [dmitrii.kashin@4qx0t4.onmicrosoft.com](mailto:dmitrii.kashin@4qx0t4.onmicrosoft.com) is marked as Primary or not (I did both): the Add-ins are visible, **but not working**, they are simply **not clickable.** 

Expected: when I mark dmitrii.kashin@4qx0t4.onmicrosoft.com as primary,  I can use my add-ins on new windows client. 
Actual:  dmitrii.kashin@4qx0t4.onmicrosoft.com is primary (first), Add-ins are visible, but I can't use them at all on new windows client (they are not actionable). 

I'm not able to run any Add-ins using  dmitrii.kashin@4qx0t4.onmicrosoft.com since last Thursday, and it's my primary account. Also, this issue came all of sudden in the middle of the day, as I'm certain enough that on Thrusday morning everything was working as expected.
 
 Dev Tools can be opened only for the Add-ins start started, not for the ones which are not clickable, so I don't know how it applies to the issue

**Comment by bchenhs** [comment] 2024-03-18 13:24
@ajays-msft The affected add-ins do not open to provide an entry to the dev tool. There has been no changes on our side regarding the add-ins, nor the account setup in Outlook. We only have one primary account. 

I agree with @dmitriikashin-outreach that this issue isn't add-in logic related.

I can try to collect network traffic on the system if that helps.

Notes:
- Viva Insights seems to be working today (it wasn't on Friday)
- These Microsoft add-ins are not working: Script Lab, Copilot for Sales, Share to Teams, Send to OneNote.

**Comment by paul-schroeder-msft** [comment] 2024-03-18 13:49
This may be unrelated, but I want to throw it out here as a possibility in case it helps.  Last week, Thursday morning, our add-in stopped working for local development. **What fixed it was redoing/reinstalling certificates related to Service-to-Service Authentication**.  However, in that case, our add-in's initial screen would start, but it was like no network calls to our services were being allowed through OWA.  

At that time, when I tried to add a secondary account to Outlook desktop, I was presented with this error message, "Looks like we can't connect to one of our services right now. Please try again later, or contact your helpdesk if the issue persists."  Error 0xCAA80000 login.microsoftonline.com

![image](https://github.com/OfficeDev/office-js/assets/107234768/d1aa905f-4fc4-4b73-994a-79a9af44febb)

**Comment by pavelstudeny** [comment] 2024-03-18 14:24
@ajays-msft , as @dmitriikashin-outreach mentions, this seems to be somehow related to the email account - when I make one account primary, this issue doesn't happen and the add-ins open. When I make the other account primary, I cannot open the add-ins. Here's a video that shows the account switching: https://drive.google.com/file/d/1FklYd_884t4urAfVDFK3YzJ93UK_Dpv5/view?usp=sharing

@paul-schroeder-msft thanks for the hint. OWA behavior is OK. If I understand correctly, my machine might not trust the new certificates. What would you suggest to try on my side regarding the certificates? Just for the record, I have verified in Edge the login.microsoft*.com passes well in the browser. Shall I try capturing the Outlook network communication with Fiddler?

**Comment by ajays-msft** [comment] 2024-03-18 15:30
@pavelstudeny @paul-schroeder-msft @dmitriikashin-outreach - I am focusing this issue only for "Addins not opening in New Outlook". For any other concern please open a separate issue to avoid cross referencing and confusion.

@pavelstudeny @bchenhs - What will help is if you are able to collect fiddler network traces and send across. Is the issue happening after you re-start the new outlook? I understand it is happening after first restart post switching. What about subsequent re-starts?
Instead of fiddler trace, you can also open dev tools in new outlook and capture har file. Meanwhile, also watch out for any errors in dev tools console window and let me know.
olk.exe --devtools will launch devtools in new outlook.

Please upload the logs in a private git repository and give access to @exextoc .

**Comment by pavelstudeny** [comment] 2024-03-18 21:00
This happens 100% for the given account, independently on restarts.

console log and har added to private repo https://github.com/pavelstudeny/office-js-4262 , invite sent to @exextoc .

**Comment by shighosh-msft** [comment] 2024-03-19 11:07
Hi @pavelstudeny, thanks for sharing the logs, could you please check the client version being loaded when you set the pavel.studeny account as primary? You can check for the following network call in DevTools to get the client-version

![image](https://github.com/OfficeDev/office-js/assets/160569634/60e33fc1-51b1-471d-bbd0-39a66a32cfc2)


Also, does this issue occur only in a multi-account scenario in New Outlook? Do add-ins launch correctly if the non-working account (smart.pavel in this case) is the only add-in added to the client?

**Comment by pavelstudeny** [comment] 2024-03-19 13:35
Sadly, while my other account was working well yesterday, this issue happens for all my accounts today for me and also for my colleagues.
It keeps happening when I remove other accounts from  Outlook and have just one.

After I click the Polls icon, there is nothing in the console log. It _seems_ to me that about a second or two later, the toolbar blinks a bit and there is a POST request https://outlook.office.com/owa/service.svc?action=SendChannelRoundTripNotification&app=Mail&n=75 . When I click the icon for the second time and more, there is completely nothing - no blink, no request.

**Comment by bchenhs** [comment] 2024-03-19 13:48
@shighosh-msft @ajays-msft 

HAR file is shared with @exextoc in https://github.com/bchenhs/private_artifacts
- The session is from the app launch and includes multiple attempts to open add-ins (Script Lab, Copilot for Sales, Share to Teams, Send to OneNote)
- There is only one account, and occurs consistently even after Outlook and system restarts.

Same observation as @pavelstudeny on the toolbar blink.

**Comment by ajays-msft** [comment] 2024-03-19 13:49
@pavelstudeny - is it possible to securely share the test credentials?

**Comment by pavelstudeny** [comment] 2024-03-19 14:31
I added them to https://github.com/pavelstudeny/office-js-4262

**Comment by shighosh-msft** [comment] 2024-03-19 22:36
Hi @pavelstudeny / @bchenhs - there are few recent changes to the privacy settings for New Outlook that is causing this issue. Please follow the following steps to update the privacy settings and let us know if the issue gets resolved for you:

1. Open settings by clicking the gear icon on the top right corner of the screen
2. Navigate to General > Privacy and data > Privacy settings
![image](https://github.com/OfficeDev/office-js/assets/160569634/5b745091-ea10-407e-b1c7-de03e5398806)
3. Toggle the optional connected experiences button to ON
![image](https://github.com/OfficeDev/office-js/assets/160569634/e979255f-5bd2-4e2b-aa79-839ebbb5d214)

More more information on what this settings does, please refer to : https://learn.microsoft.com/en-us/deployoffice/privacy/optional-connected-experiences

**Comment by pavelstudeny** [comment] 2024-03-20 06:55
I'm confirming that this helps. The effect there and back is immediate. Thanks!

What shall we tell to our users? Is this a temporary workaround (until when, roughly?) or a permanent solution that they would always need to enable?

**Comment by shighosh-msft** [comment] 2024-03-20 08:28
Hi @pavelstudeny, thanks for confirming. Yes, this is something that the users need to enable going forward to allow add-ins to work as expected. The details around this can be found here: https://learn.microsoft.com/en-us/deployoffice/privacy/optional-connected-experiences

The users can also access this page by clicking on this learn more link in Outlook
![image](https://github.com/OfficeDev/office-js/assets/160569634/8d857938-0022-42a8-88e3-36c290dfb0d9)


Closing this issue as the issue reported is now resolved.

**Closed as completed by shighosh-msft** 2024-03-20 08:28 UTC
Labels: Area: Outlook, Status: in backlog

**Comment by pavelstudeny** [comment] 2024-03-20 11:46
@shighosh-msft thanks, we will share the optional connected services instructions with our users. Hopefully, Microsoft will be able to invest some extra time to make this more user-friendly. It took 5 days to developers to figure this out.

**Comment by dmitriikashin-outreach** [comment] 2024-03-20 12:12
@shighosh-msft is it going to be adopted by all other platforms, including Web, Mac, Classic Windows Outlook? 

On Mac I have this setting turned on By default, and it's apparently connected to the Outlook Client (Mac), not to the Account/mailbox - all Add-ins work.

On Old windows I don't have such setting -  all Add-ins work.

On Web I don't have such setting -  all Add-ins work.

On New windows, seems you rolling this out, opening access to this Privacy setting with default value Off, and Mailboxes get affected proportionally, as my second mailbox got affected ~5 days after the first mailbox.

Should we expect that all Add-ins will stop working for our users across all platforms because of it any time soon, or should we guide New windows client users through these steps to revive Add-ins? 

Or do you consider it as a valid issue and this change won't be rolled out with default value Off going forward? 

Thank you

**Comment by bchenhs** [comment] 2024-03-20 13:20
@shighosh-msft We share the same sentiment with the rest of the community here. Breaking users unexpectedly without prior communication cannot be the way to roll out new features. Is there a plan going forward to close this communication gap and prevent such unexpected outages?

Thank you.
