### ISSUE TITLE
[Content Addin] getFilePropertiesAsync call fails for Excel online file

### ISSUE THREAD

**Issue by sajsarka** [OfficeDev/office-js#760] opened 2019-10-07 13:59 UTC
## Expected Behavior

getFilePropertiesAsync should return file properties of the file for which call is made.

## Current Behavior

It fails intermittently with ErrorCode : 5004, ErrorMessage : Invalid API call in the current context

## Steps to Reproduce, or Live Example

This is intermittent and in last one week we encountered 4 such failures.

## Your Environment

* Platform : Excel Online
* Host : Excel
* Office version number: (x-officeversion: 16.0.12204.31875)

**Comment by weshi** [comment] 2019-10-08 00:47
Could you share your test code? I didn't reproduce it. Here is my test code:

```
    Office.context.document.getFilePropertiesAsync(function (asyncResult) {
        var fileUrl = asyncResult.value.url;
        if (fileUrl == "") {
            console.log("The file hasn't been saved yet. Save the file and try again");
        }
        else {
            console.log(fileUrl);
        }
    });
```

**Comment by sajsarka** [comment] 2019-10-10 06:25
our code is similar to the test code above. It is very intermittent in nature, whenever trying to reproduce not hitting the issue. When we investigated error logs, we found this issue.
In which scenario, this error (ErrorCode : 5004, ErrorMessage : Invalid API call in the current context) could come?

**Comment by ravikmrsingh8** [comment] 2019-10-21 06:55
Found this https://office.visualstudio.com/OC/_workitems/edit/2660006 bug, which was closed and marked as Not Repro. We face this issue and it affects 2% of the sessions.

**Comment by ravikmrsingh8** [comment] 2019-10-21 11:05
<pre><code>
Office.context.document.getFilePropertiesAsync(function (asyncResult) {
	if ((asyncResult.status === Office.AsyncResultStatus.Succeeded)) {
		let fileUrl = asyncResult.value.url;
		if (isNullOrUndefined(fileUrl) || fileUrl === "") {
			console.log("Error:Excel Online file is not saved yet");
			resolve("");
			return;
		}
		console.log("Excel File saved");
		resolve(fileUrl);
	} else {
		console.log("getFilePropertiesAsync failed for Excel Online. Error Code: " + asyncResult.error.code + "Error Message: " + asyncResult.error.message + "Error Name: " + asyncResult.error.name);
		resolve("");
	}
});</code></pre>

**Comment by ravikmrsingh8** [comment] 2019-10-21 11:11
The AsyncResult in callback function has status as Failed.  and we get log "**getFilePropertiesAsync failed for Excel Online. Error Code: 5004Error Message: Invalid API call in the current context.Error Name: Invalid API Call**"

**Comment by donlvMSFT** [comment] 2019-10-22 00:41
Hi Ravi, I still couldn't repro this bug on my machine.
Could you give us more information to shoot the issue? Like how you get the 2% failure rate? Which version does the failure happened?
Thanks.

**Comment by ravikmrsingh8** [comment] 2019-10-30 10:27
Hi @J-January 
We tried to repro this issue and found that it fails consistently when we move the cursor to formula bar and if during this time API runs it fails. Could you try once?

**Comment by donlvMSFT** [comment] 2019-11-25 02:00
Thanks for the information. We move the cursor to formula bar, it actually into cell edit mode.

This error message could be caused by cell edit mode. We forbid API call explicitly when user enters cell edit mode (i.e. user inputs in formula bar or in a cell).

You could try to catch this error and give some tip to user to escape cell edit mode and try again.

**Comment by donlvMSFT** [comment] 2022-11-16 09:08
Close this thread due to long time in-active.

**Closed as completed by donlvMSFT** 2022-11-16 09:08 UTC
Labels: Area: Excel, Type: product bug
