### ISSUE TITLE
Mac: Auto Show Task pane with document

### ISSUE THREAD

**Issue by asparrowhawk** [OfficeDev/office-js#3567] opened 2023-08-07 12:01 UTC
## Your Environment
* Platform: Mac
* Host: Word
* Office version number: 16.75 (23070901)
* Operating System: Ventura 13.4.1
* Browser: Safari 16.5.2
 
## Expected behavior
Task pane opens and shows the Add-in's content.

## Current behavior
Task pane opens, but no content is shown.

## Steps to reproduce
1. Create a basic Add-in using yeoman, `yo office --projectType taskpane --name "yo-office-addin" --host word --ts true`.
2. Update the generated application with a checkbox to set the `Office.AutoShowTaskpaneWithDocument` property.
3. Build the Add-in and start it: `yarn && yarn dev-server`.
4. Modify the `manifest.xml` file with the following change `<TaskpaneId>Office.AutoShowTaskpaneWithDocument</TaskpaneId>`.
5. Using a Microsoft 365 trial developer subscription account, log in as the Administrator and upload the `manifest.xml` as
   a new `Integrated App`.
6. Start Word, login with a user account from the Microsoft 365 trial developer subscription, create a new document and insert the `Admin Managed` Add-in.
7. Show the task pane using the button on the ribbon bar.
8. Set the check box that was added to the yeoman generated code.
9. Using the `File` menu, save the the document as a template, i.e. `.dotx`, file.
10. Quit Word.
11. Locate the saved `.dotx` file, using Finder, and double click on it.
12. A new document opens in Word, the task pane is visible, but is blank. See below

## Link to source code
https://github.com/asparrowhawk/yo-office-addin

# Provide additional details
It is not clear if the `Office.onReady` is being called. Closing the empty task pane and using the button on the ribbon bar to show it again reveals the Add-in's content.

This source code and reproduction steps work as expected with Word for Windows version 2016 MSO (Version 2307 Build 16.0.16626.20110) 32-bit 

## Context
I am developing an Office Add-in for a client that wishes the Task pane to be visible when a document is created or is downloaded from a server. The Add-in is to target, Word, Excel and PowerPoint for Office on the Mac, Windows and Web platforms.

## Useful logs
[Current appearance](https://github.com/asparrowhawk/yo-office-addin/blob/main/empty-task-pane.png)

[Expected appearance](https://github.com/asparrowhawk/yo-office-addin/blob/main/expected-task-pane.png)

**Comment by JHJ-MS** [comment] 2023-08-14 08:06
Maybe it caused by your Addin server is not running when reopened the word document. You can open two documents and install your Addin separately. Use one for testing. Close it and reopen it to validate the autoSHowTaskPane feature.  The other opening doc could keep the addin server always running.

**Comment by asparrowhawk** [comment] 2023-08-17 08:57
> Maybe it caused by your Addin server is not running when reopened the word document. You can open two documents and install your Addin separately. Use one for testing. Close it and reopen it to validate the autoSHowTaskPane feature. The other opening doc could keep the addin server always running.

No, I am sure that the Add-in server is running. If I close the blank Add-in's side panel with the X next to the Add-in's name (don't exit Word) and click on the button to show the Add-in, its content is shown as expected.

**Comment by asparrowhawk** [comment] 2023-08-21 14:43
I have NOT been able to reproduce this issue of a blank Add-in task pane with a 2012 MacBook Pro:

* Platform: Mac
* Host: Word
* Office version number: 16.66.1 (22101101)
* Operating System: Catalina 10.15.7
* Browser: Safari 15.6.1 (15613.3.9.1.16 15613)

**Comment by asparrowhawk** [comment] 2023-08-22 10:58
I have updated my Mac with the latest operating system and version of Office. The problem is still present

* Office version number: 16.76 (23081101)
* Operating System: Ventura 13.5.1
* Browser: Safari 16.6 (18615.3.12.11.2)

I switched on webpack logging using `export DEBUG='express:*'`.  There are no HTTP calls when double clicking on the .dotx file and Word opening. If I close the Add-in's task pane using the X beside the title, then click on the `Show Taskpane` button then I see HTTP calls by webpack.

**Comment by asparrowhawk** [comment] 2023-08-22 12:50
I modified the `taskpane.ts` file and `manifest.xml` file to support Excel and PowerPoint. After removing the original Integrated app from the Developer Office 365 organisation, I uploaded the modified `manifest.xml` file as a new Intergrated app. I repeated the same steps of starting each Excel and PowerPoint application, adding the Add-in to a new document, showing the taskpane, setting the `Auto show task pane` checkbox, saving the document as a template. Closing all the Office applications and double clicking on either the Excel or PowerPoint template file created a new document with the Add-in's taskpane showing and the expected content visible. So it is only with **Word** that there appears to be a problem.

**Comment by asparrowhawk** [comment] 2023-08-22 13:09
I have repeated the re-production steps using a 2019 MacBook Pro and the problem with **Word** does NOT exist. It is using the following software:

* Office version number: 16.76 (23081101)
* Operating System: Ventura 13.5.1
* Browser: Safari 16.6 (18615.3.12.11.2)

**Comment by JHJ-MS** [comment] 2023-08-23 08:45
@asparrowhawk Do you mean the issue has gone away? Could we close this Github issue?

**Comment by asparrowhawk** [comment] 2023-08-23 09:09
> @asparrowhawk Do you mean the issue has gone away? Could we close this Github issue?

No, the issue is still there with a 2021 M1 Max, MacBook Pro. It is just not reproducible on Intel based MacBook Pros from 2012 and 2019 (the only ones I have available to test with)

**Comment by asparrowhawk** [comment] 2023-09-07 10:56
Any update on this issue? Has any one else been able to reproduce?

**Comment by ZYUN-MSFT** [comment] 2023-09-07 11:12
@asparrowhawk Sorry for the delay reply, we are still investigating this with our partner team, we will back here soon once we got the update.

Thanks for your patience.

**Comment by asparrowhawk** [comment] 2023-09-19 09:56
Any further updates on this issue?

**Comment by jargil** [comment] 2023-09-26 20:57
@asparrowhawk  - we are unable to reproduce. Tested using a Mac Studio with M1 Max. Word 16.78, 23091801. Safari 16.6 (18615.3.12.11.2). This seems to be an issue with your local setup. Please reactivate if you're able to reproduce in more than just that one MacBook and with consistent repro steps.

**Closed as completed by jargil** 2023-09-26 20:57 UTC
Labels: Area: Word, Resolution: cannot repro
