### ISSUE TITLE
VSTO's question about how to undo

### ISSUE THREAD

**Issue by JunYuZhang0812** [OfficeDev/office-js#2053] opened 2021-08-16 11:12 UTC
## Content
I started using VSTO recently and found that if I modified Excel using code, I could not undo it. Looked for many places but did not find a suitable solution. You have to figure out how to undo it. The current method is to record the current selection in SheetSelectionChange, put it in the Stack, and backtrack when it needs to be undone. The downside to this solution is that SheetSelectionChange does not listen to old content when copying into the table from elsewhere. So how do I do undo in C#? Thank you for your reply

## My Environment
Platform : PC
Host : Excel
Operating System: Windows10

**Comment by Rick-Kirkham** [comment] 2021-08-16 19:04
Closing as duplicate of 2050.

**Closed as completed by Rick-Kirkham** 2021-08-16 19:04 UTC
Labels: Resolution: duplicate
