### ISSUE TITLE
Get add-in button does not appear on ribbon menu of PC desktop outlook.

### ISSUE THREAD

**Issue by zjmchoi** [OfficeDev/office-js#3655] opened 2023-09-11 05:17 UTC
# Provide required information needed to triage your issue
"Get add-in" button does not appear on ribbon menu of PC desktop outlook.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft 365 MSO(version 2308 build 16.0.16731.20052) 32bit
* Operating System: Windows
* Browser (if using Office on the web): PC desktop (not browser)
 
## Expected behavior

"Get add-in" button should appear on ribbon menu.

## Current behavior

I am testing with Office 365 license.
With this, I have been able to use Outlook of PC desktop, Mac and Office on the web with one account at the same time..
However, at some point, suddenly "Get add-in" button does not appear only on ribbon menu of PC desktop outlook.
It displays normally in other Outlooks (on Mac and web).

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Lesturb** [comment] 2023-09-11 08:22
Having the same, in combination with https://github.com/OfficeDev/office-js/issues/3605 which is closed because reproduction is lacking it's just impossible to get rid of the add-in on Outlook.

The weird thing is, I have a different environment with the same login and here I do see the add-in button.

I think the reason is https://github.com/OfficeDev/office-js/issues/3645 where they acknowledge to be working on it. But I think they're messing it up. Even after manually adding the get add-in button, it stays greyed out.

![image](https://github.com/OfficeDev/office-js/assets/6918780/8f5be56e-9f8e-4ce4-be5a-5fb67004d23e)

While as stated on my other system (using the same email on outlook) it is present
![image](https://github.com/OfficeDev/office-js/assets/6918780/3b9df31a-ecf5-4e88-8ffe-d59259398c00)

**Comment by exextoc** [comment] 2023-09-11 08:46
@zjmchoiWhen Get Add-ins button is not available, you can click on "All Apps" and use the "Add Apps" option to get to the store.
Please see more details here:
https://support.microsoft.com/en-us/office/get-an-office-add-in-for-outlook-1ee261f9-49bf-4ba6-b3e2-2ba7bcab64c8#:~:text=Select%20the%20Store%20button%20or%20the%20Manage%20add-ins,to%20see%20more%20information%20about%20it.%20See%20More

**Comment by Lesturb** [comment] 2023-09-11 09:44
> @zjmchoiWhen Get Add-ins button is not available, you can click on "All Apps" and use the "Add Apps" option to get to the store. Please see more details here: https://support.microsoft.com/en-us/office/get-an-office-add-in-for-outlook-1ee261f9-49bf-4ba6-b3e2-2ba7bcab64c8#:~:text=Select%20the%20Store%20button%20or%20the%20Manage%20add-ins,to%20see%20more%20information%20about%20it.%20See%20More

Based on what will the new button be shown? Because I'm in conflict now, my account has the new one on system x, but the old on system y, and when adding, now it can't be removed anymore.

Also, I don't see any option to upload a manifest in the new "All apps", is that correct?

**Comment by zjmchoi** [comment] 2023-09-12 02:33
Are you saying that the "Get add-in" button disappeared after the version was upgraded?
Specifically, which version did it disappear from?
Like @Lesturb, I also could not find a way to upload a manifest for testing in the new "All apps".

**Comment by truchonh** [comment] 2023-09-12 19:04
Same for us. At first the "Get Add-ins" button was removed on OWA, then this morning after an update it was removed from the desktop app. I can indeed see the new "All Apps" button, but the ability to side-load apps doesn't seem to exist anymore.

What is the new procedure to manage dev version of app currently ? And what about private apps that are side-loaded for production use ?

**Comment by exextoc** [comment] 2023-09-13 03:01
Here is the procedure for sideloading when you don't see the "Get Add-ins" button.
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows
(From your preferred browser, go to https://aka.ms/olksideload)

The change to remove "Get Add-ins" button in OWA and Desktop is gradually rolling out, so in this process some clients may still not get the change yet.

**Comment by zjmchoi** [comment] 2023-09-13 05:06
@exextoc: According to the Microsoft document you provided, the procedure for testing my add-in in desktop Outlook (Windows) is as follows.
1. sideload my test add-in through Outlook on the web.
2. Wait up to 24 hours for sideloaded my test add-in to appear in the Outlook client on Windows..
3. test my test add-in in the Outlook client on Windows

This procedure seems very inefficient.
Why did you remove "Get add-in" button?

**Comment by avisheknand** [comment] 2023-09-13 20:48
@zjmchoi , i agree this procedure is  very inefficient. It causes more stress to developers and testers who quickly wishes to side load addin and test it out on the Outlook for Desktop Env. I hope Microsoft gives an option to side load addin again using Outlook Desktop.

**Comment by exextoc** [comment] 2023-09-14 01:49
@zjmchoi @avisheknand - We are aware of this issue, and actively working on fixing this. 

As a workaround, please use Outlook Desktop (Old Outlook) for getting the sideloaded add-in immediately, even if you have used the web version to sideload.

**Comment by zjmchoi** [comment] 2023-09-15 02:37
@exextoc :
Old Outlook?  
Is it  the version with "Get add-in" button?
So, where can I get Outlook Desktop (Old Outlook)?

**Comment by exextoc** [comment] 2023-09-15 03:35
@zjmchoi By Old Outlook, I meant the current version of outlook, that does not have the toggle to on. If you turn on the toggle, you will see "New Outlook"
![image](https://github.com/OfficeDev/office-js/assets/28549921/68d79889-11cb-4080-90a1-8a2339dfe69d)

**Comment by zjmchoi** [comment] 2023-09-15 04:58
@exextoc,
Because I am currently developing an add-in on Outlook Desktop (Old Outlook), I need a solution(or a way) to sideload directly from Outlook Desktop (Old Outlook).
In Outlook Desktop (Old Outlook),  I hope that
1, "Get add-in" button appear(restore) again..
2. or,  it show as "All Apps" > "Get Add-ins" option.  (currently, I  see the "Add Apps" option instead of "Get Add-ins".)
![image](https://github.com/OfficeDev/office-js/assets/34048924/560f3c02-b6d3-4244-9d1f-5d5e24baabd2)

**Comment by t-ariyoshi30907** [comment] 2023-10-05 04:41
@exextoc 
The "Old" Outlook has been updated, and here the "Get Add-ins" menu has been removed. Some customers use side-loading to utilize add-ins in Outlook, so we would like to see improvements that enable add-in side-loading in the "Old" Outlook.
![image](https://github.com/OfficeDev/office-js/assets/106288213/d9241e27-4192-473b-8b36-346e32dcc7bf)

**Comment by zhngx1** [comment] 2024-04-26 04:30
Closing this as this is by design: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows-web

**Closed as completed** 2024-04-26 04:30 UTC
Labels: Area: Outlook, Resolution: question answered
