### ISSUE TITLE
Cannot access names in inactive workbook

### ISSUE THREAD

**Issue by jwhite-venacorp** [OfficeDev/office-js#2078] opened 2021-08-25 17:24 UTC
# Provide required information needed to triage your issue

When the workbook hosting the addin is not the active window, named ranges cannot be added. In some cases, this results in an exception, "ItemNotFound". In other cases, Excel will actually crash (closing all the documents.)

ScriptLab examples for both cases provided.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2109
* Operating System: Windows 10 Pro, version 21H1
* Browser (if using Office on the web): N/A
 
## Expected behavior

The named range should be created in the workbook hosting the addin.

## Current behavior

When I create the name by calling `workbook.names.add("name_1", "Sheet1!$A$1", "")` the "ItemNotFound" exception is thrown.

When I create the name by getting a `Range` and passing it to `names.add`, eg:

```
        const range = context.workbook.worksheets.getItem("Sheet1").getCell(0, 0);
        context.workbook.names.add("name_1", range, "");
```

Excel will actually crash.

## Link to live example(s)

1. [Named range in inactive window](https://gist.github.com/jwhite-venacorp/cc4d6fab072863ab6f35e04861b13831)
2. [Create named range and crash Excel](https://gist.github.com/jwhite-venacorp/289b99efa2d1ca34cbb437121dbf5cd4)

## Context

We have some long running processes and our users will switch to other workbooks while waiting, and this will ultimately cause our addin or Excel to crash, depending on when they switch to the other workbook and what processing we are doing.

## Useful logs

- [x] Console errors
```
[ERROR]: Error:
{
    "stack": "RichApi.Error: The requested resource doesn't exist.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:236320)\n    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:299551)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:297656",
    "message": "The requested resource doesn't exist.",
    "name": "RichApi.Error",
    "code": "ItemNotFound",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "ItemNotFound",
        "message": "The requested resource doesn't exist.",
        "errorLocation": "NamedItem._OnAccess",
        "statement": "var add = names.add(...);",
        "surroundingStatements": [
            "var workbook = context.workbook;",
            "var worksheets = workbook.worksheets;",
            "var names = workbook.names;",
            "var itemOrNullObject = names.getItemOrNullObject(...);",
            "itemOrNullObject.delete();",
            "// >>>>>",
            "var add = names.add(...);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 404
}
```
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jroycroft-venacorp** [comment] 2021-08-25 18:51
I get the same results when I run the scripts in the ScriptLab gists above, on Excel version 16.52 on Mac Big Sur

**Comment by keyur32** [comment] 2021-08-25 20:09
@lumine2008  - Can you please take a look?

**Comment by qinliuMSFT** [comment] 2021-08-26 09:31
Thank you for logging this issue. The issue is reproducible for us, and has been put on our backlog VSO#5372098, will let you know once we have any updates.

**Comment by honxmsft** [comment] 2021-09-29 05:47
The fix of this bug is checked in. It might take a month for desktop version to ship the fix. Let me know if you have any further question.

**Comment by christian-sap** [comment] 2021-11-04 13:44
@jwhite-venacorp thanks a lot for reporting this issue. Our add-in users run into the same error and I did not manage to reproduce it so far. After I found your reported issue I opened a second workbook and then the error comes immediately. You saved me a lot of time :-)

**Comment by christian-sap** [comment] 2021-11-04 13:45
@honxmsft Can you please tell us when the fix will be released in the different Excel channels?

**Comment by RuoyingLiang** [comment] 2021-11-08 05:41
@honxmsft could you help to check if the fix is in prod? Thanks

**Comment by christian-sap** [comment] 2021-11-09 06:07
Hi @RuoyingLiang , @honxmsft, this is a severe issue for our customers. Could you please provide a detailed plan, when the fix will be released in the different Excel channels? Is there a workaround available?

**Comment by honxmsft** [comment] 2021-11-09 11:16
@christian-sap 

It should be included in Oct. fork. The Oct. fork plan is:
```
Version 2111
Build #s: 14701.xxxxx
CC (Preview) (Planned): Mon Nov 15 2021
Production (Planned): Mon Nov 29 2021
```

You can try it now if you have Microsoft Current Channel (OuterRing) excel, which is shipping the version 2111 (Build 14701.20060 Click-to-Run).

**Comment by christian-sap** [comment] 2021-11-10 07:09
@honxmsft thanks for the information. How can I install the "Current Channel (OuterRing)"? It is not documented, see https://docs.microsoft.com/en-us/deployoffice/update-channels-changes.
I installed the "Current Channel (Preview)" but only got version 2110 (14527.20234).

And what do you mean with "Production"? We need the fix asap in all the channels, especially in "Semi Annual Enterprise" and "Monthly Enterprise".

**Comment by christian-sap** [comment] 2021-11-16 07:40
@honxmsft I installed CC (Preview) version 2111 (14701.20100) and the issue is still there. This is a really serious issue. Should the fix be part of this version?

**Comment by honxmsft** [comment] 2021-11-17 06:54
@christian-sap My colloeage and I have tried two gists again on the version 2111 (14701.20100), 2111 (14701.20040), 2111 (Build 14701.20142). The win32 excel does not throw exception or crash. Perhaps it's not the proper way to verify this issue? Can you describe how you verify this issue?

**Comment by christian-sap** [comment] 2021-11-17 09:58
Hi @honxmsft , see the attached modified gist.
The root cause is that after opening another workbook the named item type is "null". Before opening the workbook is it "range" which is correct. 
If you run the gist in "Current Channel (Preview)" you see the error on the console.
If you run the gist in "Semi-Annual Enterprise" Excel crashes completely.
[namedItemType.txt](https://github.com/OfficeDev/office-js/files/7553607/namedItemType.txt)

**Comment by honxmsft** [comment] 2021-11-18 05:59
Thanks @christian-sap. I've checked your new gist, and the named item type did return null (unexpected), but I think this is an issue other than workbook.names.add API 😞 , as I tried to checkNamedItemType on the named item created from Name Manager UI right after a workbook creation, it will still return null on namedItem.type. We will create another internal bug to track this issue.

BTW, the fix on the crash does not reach the Semi-Annual Enterprise yet. The next Semi-Annual might be on next January.

**Comment by dingjin-ms** [comment] 2022-01-12 06:52
Hi @christian-sap , we have the fix of add problem on Semi-Annual (Preview) now, and it would be on Semi-Annual Channel on the end of January. 

And we have the fix for type related problem checked in, it would be on next Semi-Annual (Preview) also on the end of the January, it would be on Semi-Annual Channel on next July.

Thank you for reporting!

**Comment by christian-sap** [comment] 2022-01-18 07:45
@dingjin-ms thanks for the update.

**Comment by donlvMSFT** [comment] 2022-11-17 03:26
The fix already rolled out, please help verify.
I'd like to close this thread, thanks for the discussion!

**Closed as completed by donlvMSFT** 2022-11-17 03:26 UTC
Labels: Area: Excel, Type: product bug
