### ISSUE TITLE
Addin itemsend event in manifest block the send operation

### ISSUE THREAD

**Issue by chopraniitn** [OfficeDev/office-js#799] opened 2019-10-22 11:57 UTC
## Expected Behavior
When i register ItemSend event in manifest, Whilst sending a meeting invite to someone a corresponding handler should execute.

## Current Behavior
When i register ItemSend event in manifest , Whilst sending a meeting invite to someone addin blocks whose send operation and registered function does not even execute. seems like its trying to find handler but could not find . see screen shot
![issue](https://user-images.githubusercontent.com/55550147/67281564-9fe89580-f4c7-11e9-853c-2df2e54e281d.png)

AS you can see its saying " Mss Js cloud test is working on your request" , i found this message never goes away and send operation get blocked

## Steps to Reproduce, or Live Example
Make sure you register item send event first in manifest file

1. Open outlook appointment
2. Activate addin(Make sure you ad the function you resister for item send)
3. Go to appointment and add an invitee
4. keep the addin open and hit send button

Error : register function does not execute and addin does not send any invite.
## Context
I am trying test preview set for outlook addins so that we can decide our product road map

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: OfficeOnline/ office client with 365 pro plus subscription
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.12209.20010 (Insider channel)
* Operating System: Windows 10
* Browser (if using Office Online): chrome

## Useful logs
I have attached the whole test project with sample manifest file in order to reeproduc eissue
[js_cloud_test (2).zip](https://github.com/OfficeDev/office-js/files/3755380/js_cloud_test.2.zip)

- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment] 2019-10-23 07:27
Dupe of

Bug 1276181<https://o365exchange.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_workitems/edit/1276181>: New GitHub Issue [OfficeDev/office-js]: Addin itemsend event in manifest block the send operation


________________________________

**Comment by exextoc** [comment] 2019-10-23 09:15
1) Is this issue started recently? Was this working correctly some days/week ago?
2) We fixed a very critical bug in Calendar + Addin and pushed to production. Can you please retry this again and see if this problem persists?

**Comment by chopraniitn** [comment] 2019-10-23 09:32
Hi,

I tried this feature yesterday only and found this happening. i will try updating outlook client and see if it make any difference.  but not sure how  can test this on outlook web with the changes made

**Comment by chopraniitn** [comment] 2019-10-23 09:41
ok i tried updating outlook , but same issue. Addin is still blocking send operation. Not sure if i missed something in my code, but i believe i did whats in documentation.

Is there any working sample which you can provide and i can try that.

**Comment by chopraniitn** [comment] 2019-10-23 11:23
ok, one of the issue which was blocking send operation seems resolved on office client after i modified my manifest, seems like **FunctionFile** resid was not correct.  But main issue is still here , the handler is not being invoked when send button is being pressed.

Problem still remains on outlook web, but i think thats due to fact its not a preview version.

**Comment by exextoc** [comment] 2019-10-24 06:37
@chopraniitn Thanks for your response. I downloaded your Addin code and issue was reproducible. There are few problems the way OnSend feature is implemented in your addin. I was able to fix all of those and then it started working. I suggest you to look at following problems and resolve them:
1. FunctionFile was not defined. This is must for UILess addin (OnSend is UILess addin)
2. You need to have separate .html file for FunctionFile which should include JS file which has itemSendHandler() function.

Please look at these references:
(1) https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins?tabs=windows
(2) https://github.com/OfficeDev/Outlook-Add-in-On-Send/tree/master/outlook-add-in-on-send

**Comment by chopraniitn** [comment] 2019-10-24 08:36
Hi,

Thank you very much for your response. Yes i figured out my functionfile was not correct.

when you say OnSend is UILess addin , does that mean it wont work if i have addin with UI. Reason why i am asking because in my usecase requires to some operation on ui first before starting send operation. in my scenario

1)  I want to load addin
2) get meeting data from outlook and show some options to user which will be  derived form our own system based on data provide by outlook
3) Prepare the data to be saved on our system
4) Hit send button, thats where i want ItemSendHandler to jump in, so before completing send event i want the data to be saved in our system and if everything is fine then complete send operation otherwise block.

Let me know if itemsend can work with this scenario , otherwise using ItemSend operation will not benefit us.

i went through documentation already, May be i did not understand but it says

**The on send feature is triggered by events. Currently, the feature supports the ItemSend event type. Events in Outlook add-ins enable you to handle, check, or block user actions when something of interest occurs. For example, events provide ways to:

Control user actions
Handle changes
Signal user actions such as button clicks
Verify user data input
Validate content in a message**

After reading this I was under impression that you can delay the event complete operation , But going through sample as well, it seems like itemsendhandler function will execute as soon as addin loads up and block operation will be decided at that moment and you cant change it later.

**Comment by exextoc** [comment] 2019-11-04 10:44
Yes, OnSend feature only supports UI Less add-in. You can achieve your scenario by having two extension points in your add-in, one for task pane add-in and other for on send.
You can use task pane extension to do 1,2,3 items from your scenario and use onSend extension point for 4th item. Also the addin should be launched manually by user as it has task pane extension point. OnSend part will be launched automatically.

**Comment by exextoc** [comment] 2019-11-07 06:33
To avoid confusion, we have updated documentation, please check below link:
https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins?tabs=windows

**Closed as completed** 2020-01-06 02:51 UTC
Labels: Area: Outlook, Type: product bug, Area: add-ins platform
