### ISSUE TITLE
New inReplyTo property of the compose message returns incorrect value

### ISSUE THREAD

**Issue by cut2run** [OfficeDev/office-js#4717] opened 2024-07-25 20:57 UTC
Mailbox 1.14 level API introduced [inReplyTo](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#outlook-office-messagecompose-inreplyto-member) property of the Office.MessageCompose interface. 
The value of the property gets the message ID of the original message being replied to by the current message, per the posted description, to be used for consequence requests to find the original message a user is replying to.

When the message the user is replying to from "Sent Items" folder or the message received from external domains, the property would hold the Internet Message Id which matches to `PR_IN_REPLY_TO_ID_W` field of the compose message that corresponds to `PR_INTERNET_MESSAGE_ID_W` of the original message and would look similar to ...

> `<YT4P288MB0234234HH3430AA4DE8AAFA92@YT4P34534535.CKFR456.PROD.OUTLOOK.COM>`

At the same time, if the original message was sent to yourself (for example, CC to yourself) and you are replying to this message, the `inReplyTo` property would hold absolutely different value, similar to ...

> `<YT4P288MB0234234HH3430AA4DE8AAFA92@YT4P34534535.CKFR456.PROD.OUTLOOK.COM>0ZDZhNWFiLWE0Y2EtNDc4My05MGU1LTY5ZWNiOTQ5MmY5YwBGAAADEgGHnGK1T06Yq8xwQCjiHwcAkUJPW0th2EGwjXYeK6AWSQAAAgEMAAAAkUJPW0th2EGwjXYeK6AWSQAIZ3/xsgAAAA==`

I guess this value is some kind of concatenation of the Internet Message Id (`inReplyTo`) with Item Id (`ItemId`), but this is total speculation from my side.  As you may guess this `inReplyTo` value cannot be used to look for original message and `find` request will return no items.

I am observing this in Outlook for Web, Office 365 account.

To reproduce the issue just send the message and include yourself into "CC" field. Try to reply on the message you received in the mailbox, check the value of `inReplyTo` property.

**Comment by Oleg-O** [comment] 2024-07-29 18:04
This does not look right; however, I am not able to reproduce so far. Do you see the same result if you just send a message to yourself and reply to that (in other words, is CC part important to reproduce this?)? I tried both and still couldn't reproduce though. Do you see this issue on one message only or can you reproduce this consistently on new messages?

**Comment by Oleg-O** [comment] 2024-07-29 19:20
Oddly, somebody else in my team was able to reproduce using exactly same steps. We'll look into it. We unfortunately have no timelines to share at this point. Thanks for reporting this issue.

Internal tracking id: OutlookWeb: 295124

**Comment by cut2run** [comment] 2024-07-29 20:02
Hello @Oleg-O , wow long time, I remember I even had a support session with you like 10insh years ago, I believe at this point the API level was 1.3 or something and we are trying to resolve `Office.context.mailbox.item.saveAsync` in Outlook desktop with synchronisation time for subsequential EWS requests. Time is flying by and you still running the team of clever Outlook guys :)

I am glad somebody got the repro of this issue, because I have tried today following my own (very simple) steps and couldn't get it. The old messages from last week are still with these weird Ids, but the new ones, I am creating, have expected Ids. 
Anyway, thanks a lot for looking into this issue and all the best.
Slava.

**Comment by Adrian-MSFT** [comment] 2024-07-29 22:28
@cut2run It seems like it's been since fixed. I was the person that was able to repro, but I noticed I was on a version from last week. After refreshing for the new version, I'm unable to repro this anymore. I do see the same behavior you are seeing - the messages created with the old version have the incorrect property, but the newly created ones are fixed. I'll close this for now. Please let us know if you see this happening again.

**Closed as completed by Adrian-MSFT** 2024-07-29 22:28 UTC
Labels: Area: Outlook, Type: product bug, Status: fixed, Platform: Online
