### ISSUE TITLE
Web Addin certificate issue while building artifacts in CI/CD

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3663] opened 2023-09-11 11:30 UTC
When we are building the Web Addin React App manually using “npm run build” command ,it looks for Office-AddinDev-Certs and if the certificates are not available then it get installed in user’s local but while building the app in CI/CD pipeline “npm run build” command is getting timed out as its trying to install the certificates and waiting for user input . We tried installing the certificate npx office-addin-dev-certs install –machine before building artifacts in CI/CD but it did not worked .

**Comment by slabereemsft** [comment] 2023-09-11 17:22
This is really a duplicate of issue  -https://github.com/OfficeDev/office-js/issues/3664.  We don't support linux builds at the moment.

**Closed as completed by slabereemsft** 2023-09-11 17:22 UTC
Labels: Needs: triage :mag:
