### ISSUE TITLE
Classic Outlook Windows ItemSend Add-in: Endless looping after updating manifest version

### ISSUE THREAD

**Issue by alexm-plutoflume** [OfficeDev/office-js#4483] opened 2024-05-21 12:26 UTC
# Provide required information needed to triage your issue

We have reports of endless looping from our ItemSend Add-in after updating the deployment in the admin center with a manifest with an updated `Version` element. I've attached a video of the behavior, it appears the Add-in is running over and over again (not just hanging). 

Reverting back to the previous manifest seems to resolve the issue. Our customers directly upload our manifest in the Admin center to deploy. In order to ensure no conflicts, if a customer re-downloads our manifest, we will increment the `Version` element. 

We have reports of this happening with **no** changes to the manifest other than an incremented version, and with changes to manifests that include an incremented version and updates to query parameters for example.

I have also been able to reproduce this locally via sideloading with a simple OnSend addin that does nothing but log a line and allow the email to send. It's hard to deduce what is causing it and it doesn't appear to happen all the time when updating the manifest, but I'm wondering if it's something awry with MSFT caching of Add-ins?

## Your Environment

Platform: Classic Outlook for Windows - Version 2404 Build 17531.20152, but we've had reports in other versions as well, e.g. Version 2402 Build 17328.20282
Windows Build:  Windows 11 Enterprise Build 22631

Does not affect Outlook for Mac, OWA, or New Outlook for Windows that we can tell.
 
## Expected behavior
We expect the ItemSend Add-in to not loop endlessly after updating the Add-in deployment with an updated manifest.

## Current behavior
After uploading an updated manifest in the Admin center, users are seeing endless looping from our Add-in. No changes made except incremented `Version` element. Reverting to an older manifest fixes it.

Was able to reproduce locally with a simple Add-in and sideloading as well. 

I've attached a video of the behavior below from sideloading:

https://github.com/OfficeDev/office-js/assets/80270047/a88dc166-e172-421a-8d66-4c1f4af68c84

## Steps to reproduce

I've been able to  consistently reproduce it with these two manifests over a couple different mailboxes.

<details>
<summary>Manifest 1</summary>

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xsi:type="MailApp">
  <Id>dfa4240b-bb7e-5c4d-bc78-67521725e0e7</Id>
  <Version>4.17140.58345.89775</Version>
  <ProviderName>Debug Addin</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Debug Addin"/>
  <Description DefaultValue="Debug Addin"/>
  <IconUrl DefaultValue="https://office-addin.tessian.xyz/dev/simple/assets/tessian_logo.png"/>
  <HighResolutionIconUrl DefaultValue="https://office-addin.tessian.xyz/dev/simple/assets/tessian_logo.png"/>
  <SupportUrl DefaultValue="https://www.google.com/"/>

  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>

  <Requirements>
    <Sets>
      <Set Name="MailBox" MinVersion="1.8"/>
    </Sets>
  </Requirements>

  <FormSettings>
    <Form xsi:type="ItemEdit">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://office-addin.tessian.xyz/dev/simple/commands.html" />
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteMailbox</Permissions>

  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit"/>
    <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Edit"/>
  </Rule>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">

      <Description resid="residAppDescription" />

      <Requirements>
        <bt:Sets DefaultMinVersion="1.8">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>

      <Hosts>
        <Host xsi:type="MailHost">
          <DesktopFormFactor>
            <FunctionFile resid="residUILessFunctionFileUrl" />
            <ExtensionPoint xsi:type="Events">
              <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="onSendCallback" />
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>

      <Resources>
        <bt:Images>
          <bt:Image id="Icon.64x64" DefaultValue="https://office-addin.tessian.xyz/dev/simple/assets/icon_64.png"/>
        </bt:Images>

        <bt:Urls>
          <bt:Url id="residUILessFunctionFileUrl" DefaultValue="https://office-addin.tessian.xyz/dev/simple/commands.html" ></bt:Url>
        </bt:Urls>

        <bt:LongStrings>
          <bt:String id="residAppDescription" DefaultValue="Debug" />
        </bt:LongStrings>
      </Resources>

    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
```
</details>

<details>
<summary>Manifest 2</summary>

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xsi:type="MailApp">
  <Id>dfa4240b-bb7e-5c4d-bc78-67521725e0e7</Id>
  <Version>4.17140.58654.89885</Version>
  <ProviderName>Debug Addin</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Debug Addin"/>
  <Description DefaultValue="Debug Addin"/>
  <IconUrl DefaultValue="https://office-addin.tessian.xyz/dev/simple/assets/tessian_logo.png"/>
  <HighResolutionIconUrl DefaultValue="https://office-addin.tessian.xyz/dev/simple/assets/tessian_logo.png"/>
  <SupportUrl DefaultValue="https://www.google.com/"/>

  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>

  <Requirements>
    <Sets>
      <Set Name="MailBox" MinVersion="1.8"/>
    </Sets>
  </Requirements>

  <FormSettings>
    <Form xsi:type="ItemEdit">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://office-addin.tessian.xyz/dev/simple/commands.html" />
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteMailbox</Permissions>

  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit"/>
    <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Edit"/>
  </Rule>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">

      <Description resid="residAppDescription" />

      <Requirements>
        <bt:Sets DefaultMinVersion="1.8">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>

      <Hosts>
        <Host xsi:type="MailHost">
          <DesktopFormFactor>
            <FunctionFile resid="residUILessFunctionFileUrl" />
            <ExtensionPoint xsi:type="Events">
              <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="onSendCallback" />
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>

      <Resources>
        <bt:Images>
          <bt:Image id="Icon.64x64" DefaultValue="https://office-addin.tessian.xyz/dev/simple/assets/icon_64.png"/>
        </bt:Images>

        <bt:Urls>
          <bt:Url id="residUILessFunctionFileUrl" DefaultValue="https://office-addin.tessian.xyz/dev/simple/commands.html" ></bt:Url>
        </bt:Urls>

        <bt:LongStrings>
          <bt:String id="residAppDescription" DefaultValue="Debug" />
        </bt:LongStrings>
      </Resources>

    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
```
</details>

Instructions:
1. Install/sideload manifest 1. In classic outlook for windows, see that the Add-in runs and lets the email send.
2. Remove manifest 1 and install/sideload manifest 2. You may need to delete your cache/WEF folder, then in classic outlook for windows, try sending an email and see that the looping occurs.
3. Remove manifest 2 and sideload manifest 1 again. See that the looping stops.

Note the only difference between the two manifests is the `Version` element. The Add-in simply logs a line and allows the email to send.

## Link to live example(s)
See above

# Provide additional details

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by abdumanas-plutoflume** [comment] 2024-05-22 13:49
Hi Team, any updates on this ? Currently this behavior poses a blocker for customers from updating their manifest.

**Comment by JuaneloJuanelo** [comment] 2024-05-22 15:56
@alexm-plutoflume thanks for reporting this issue, have a few follow up questions to properly investigate this.
1. On your repro steps, did outlook stayed open during the manifest update process?  did you restarted Outlook after updating to manifest 2?  what was the behavior here?
2.  Will also be interesting to understand the scenario, when this issue happened, should we assume the customer was using M365 centralized deployment? what changes were incl

**Comment by abdumanas-plutoflume** [comment] 2024-05-22 16:16
@JuaneloJuanelo thank you for taking a look into this. To your queries:

1. I tested using both scenarios, i.e. keeping Outlook open and closed during the manifest update process. I'm able to reproduce the problem in both cases. Outlook was also restarted after manifest update process and the issue still persists.
2. The customers who have reported this issue are using the centralized deployment from their admin portal.

Please let us know if you need any additional info.

**Comment by timwan10** [comment] 2024-05-23 00:43
Does this happen if you ONLY install the second manifest? (and not the first?)

**Comment by timwan10** [comment] 2024-05-23 01:28
I cannot seem to repro with the steps you provided.

1) Install Manifest 1
2) Check the WEF Folder for the Manifest (see that it's there) 
3) Send an Email...it sends. 
4) REMOVE Manifest 1. 
5) Close the Installation Dialog
6) Check the Wef Folder that it's gone
7) Reopen the Installation Dialog. Install Manifest 2. Close Dialog. Check the Wef Folder that the Manifest 2. Version is there. 
8) Send an email.... it sends. 


I did also skip Steps 4-6. And just directly upload Manifest 2, without removing Manifest 1. But emails still sent. 

I am on a later version. but it's doubtful something has changed. 

Do you see any significant changes in my steps from yours?

in your Wef Folder for manifests, is the expected manifest there at the appropriate times?

C:\Users\[user name]\AppData\Local\microsoft\office\16.0\wef\{E19E6C57-8A36-49C5-BDD7-265D4EBFF292}\6lDh5BqVDFYMtLWUxFtNYw==\Manifests

The guid/encoing between wef + manifests will be unique for you. 

The fact this persists through restart is pretty strange. (as the manifest cache should be updated on reboot). Is there anything else about this that may be unique to your machines? 

Can a regular taskpane app be opened when this happens?

**Comment by alexm-plutoflume** [comment] 2024-05-23 08:33
Just for clarity - in our testing we are side loading the Add-in via this link in OWA: https://aka.ms/olksideload, after I sideload the manifest in OWA, I close Windows Outlook (within a VM, if that matters, but our customers are experiencing this inside and outside VMs across various environments after Centralised deployment), clear the WEF folder, then open Outlook again. I do this every time I reinstall a sideloaded Add-in.

Sometimes the reproduction stops working for me and it's not clear why. Potentially a restart of the environment, or something else, but if I then increment the `Version` element in the manifest to a new version and sideload it, once again I can have it happen again. Reverting the manifest back to an old version stops the looping.

Right now I am experiencing the looping again, and can see the manifest under my user in the WEF folder, yes. I can open a taskpane Add-in, yes.


> Does this happen if you ONLY install the second manifest? (and not the first?)

If you only install the second manifest, no. 

The issue seems to be related to having an Add-in installed, then installing a new version of the same Add-in. In the reproduction provided, if you've never installed this add-in, then we would not expect the looping to occur for either manifest installed in isolation. Only when you install the manifest 2 after manifest 1, which is a higher version.

**Comment by alexm-plutoflume** [comment] 2024-05-24 10:38
@timwan10 Just following up here - is there any more information we can provide to help you guys debug this?

I can still reproduce the looping. I want to reiterate that sometimes it resolves itself (unsure if it's an environment restarting, or just more generally some unknown amount of 'time' passing), but all I need to do is sideload the same add-in manifest with an incremented `Version` element, and I can re-produce the looping once again. If the manifests provided don't reproduce it for you, I suggest trying to increment the version again and sideload again, maybe a few times until you potentially hit the looping.

With the current looping - I have tried:
1. Closing outlook, clearing WEF folder, restarting.
2. Switching from new outlook back to classic outlook
3. Restarting my entire environment.

But none of those resolve it. I am only able to resolve it by sideloading a previously installed manifest (or waiting what seems like a day or two, but this isn't totally conclusive).

Our customers will be deploying updated manifests through Centralized Deployment somewhat frequently as we allow some customization options that customers will adjust that are passed through the Add-in manifest. This has a possibility of affecting all of our customers in due time as they deploy updated manifests.

**Comment by alexm-plutoflume** [comment] 2024-05-24 13:47
Here is another video that shows my full process of reproducing it. In this video you'll see that it starts off with the Add-in looping on an email. I then remove the Add-in and upload the same Add-in but an **older** manifest version. I then close outlook, clear my WEF, and then open outlook and try to send an email. It will go through with no looping. I then uninstall and sideload the **newer** manifest that was already installed at the beginning of the video, follow the same process, and the looping is back.

[Video link here](https://drive.google.com/file/d/1eXuDZ4T1B9iuuutuD8KYZi7VdpXBvm_o/view?usp=sharing)

**Comment by alexm-plutoflume** [comment] 2024-05-28 13:13
@timwan10  following up again - I left the broken/endless looping manifest sideloaded over the weekend and was able to confirm that by today the looping behavior stopped. This makes me think there is some sort of issue related to caching or similar?

I am able to reproduce the looping yet again by installing another manifest with a higher version number.

I've recorded another video to show exactly how I am modifying the manifest and to show that the looping returns - all I'm doing is randomly increasing the version number.


[Video link here](https://drive.google.com/file/d/1BYucdXeS2pAeu1XQqiBEadSH66wiCVrF/view?usp=sharing)

**Comment by timwan10** [comment] 2024-05-28 21:14
This is a complicated enough and unique enough issue that I need to look into if it is possible for you to transfer us more information. Let me get some info from the dev team, and see how I can set that up. 

Would you mind to provide information on your company/add-in? (if this is not ok to share on a public forum that is ok)

**Comment by timwan10** [comment] 2024-05-28 23:10
Hm, nevermind, your repro steps allowed us to repro it locally. We will investigate further.

**Comment by timwan10** [comment] 2024-05-29 00:25
Okay, thanks for the help here. You were correct this is indeed a caching issue. At this point in time, I would refrain from updating the version # of your Add-in, otherwise users will hit this issue. 

More details: 

* We believe that this caching issue should resolve itself within **30 min to 4 hours.** (on an individual user basis) Which is why you are seeing inconsistent results. However, a reboot of Outlook will NOT always trigger a refresh of the faulty cache. (as the cache is server side), but could speed along OTHER cache refreshes. (which is why sometimes rebooting helps) 

Does this match kind of what you have experienced?

* The cause for this is that duplicate versions of your add-in are making it to the client. (for example, another symptom of this would be duplicate buttons in the ribbon. Or other duplicate events (like onNewMessageCompose). 

* There is a change that will fix this that is rolling out. But I am not clear what versions will be fixed, or the timeline of that rollout. We may try to roll out a separate fix to speed this process.

**Comment by alexm-plutoflume** [comment] 2024-05-29 08:26
Thanks a bunch for the effort in looking into this!

Yes that does match our experience. One of our customers said that rebooting seemed to help some users, but not all. Additionally they said they are not seeing it occur anymore at all with their users and our metrics confirm that it appears to have stopped looping for them a day or two after they had updated the manifest.

We will inform customers for the time being to not update their manifests - but it will be extremely helpful to get a timeline and know what versions will be fixed ASAP. Customizability of our Add-in is an important feature, and any time a customer wants to update their customization, the manifest version will be incremented for them.

**Comment by timwan10** [comment] 2024-05-31 01:16
Does your add-in have a taskpane/ribbon button? Is the ribbon button also duplicated when this happens? 

I do want to update, that this is being treated with the utmost importance here. I don't have an update of timelines yet, but we are trying to get a fix out as fast as possible as updates for Outlook can possibly come out. 

it is likely that build/timelines can be pin pointed down next week.

**Comment by alexm-plutoflume** [comment] 2024-05-31 11:37
Thanks for the update!

No our add-in doesn't use a taskepane or ribbon button - only ItemSend and some other launch events like `OnMessageCompose`.

**Comment by timwan10** [comment] 2024-06-14 00:02
This has been backfixed in versions: 
2405 -> 16.0.17628.20144 and later
2406 -> 16.0.17726.20074 and later

The 2405 build is slowly rolling out to users. the 2406 should be available to all user in preview right now. 

A fix for 2404 is under consideration, and we will update if/when a fixed build comes out for that. 

Edit: A Fix for 2404 should be released July 7th.

**Closed as completed** 2024-06-20 21:04 UTC
Labels: Area: Outlook

**Comment by pepso** [comment] 2024-08-26 09:14
Hi @timwan10,

We got report from our client that an Add-in update (through admin center) has caused this (or exactly the same) endless loop on the semi-annual update channel this morning. It does not seem to impact everyone (yet?). The problem is apparently resolved by Outlook restart in these few cases we are aware of.

They actually are on 2402 (17328.20452) on Semi-Annual from mid-July. (I earlier wrote about a report from the client with wrong version information).

Is there plans to backport the fix to lower builds?

Thank you!

**Comment by Oleg-O** [comment] 2024-10-24 17:33
@pepso there is currently no plan to backport to 2402 semi-annual - we've been having a hard time reproducing it on this version ourselves, and so did one of the customers who previously have seen this surface on this version. At this point, we'd need a reliable repro to understand the issue well. Have you heard about this issue from customers since your last comment here in late August?
