### ISSUE TITLE
The result of method getDirectPrecedents it shows a group result in one index array

### ISSUE THREAD

**Issue by Refinitiv-365** [OfficeDev/office-js#2548] opened 2022-04-22 08:45 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: All
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System:  Window 10
 
## Expected behavior

[Range.getDirectPrecedents](https://docs.microsoft.com/en-us/javascript/api/excel/excel.range#excel-excel-range-getdirectprecedents-member(1)) The result of method getDirectPrecedents it is group result in one index
## Current behavior
1. setting value in excel and I use yo office angular for running code
![1 init value on excel js](https://user-images.githubusercontent.com/98725157/164649276-de363874-226d-4669-b452-e8fb0507f224.png)
2.  I use a getDirectPrecedents method for code. the result is getting item 1 index on array and address grouping together
![error](https://user-images.githubusercontent.com/98725157/164649473-c6aae3df-c9d5-463f-99b6-d36411f41857.png)

## Steps to reproduce

1. open project has Excel.js ( this issue use yo office) 
2. initial value cell reference stick together and same size dimensions 
3. run code

# Provide additional details
1. It appears errors on the cell reference item stick together and The dimensions of the data are the same size. 
Example 1x4 with 1x4, 2x2 with 2x2 
2. code
![code](https://user-images.githubusercontent.com/98725157/164649351-c8cca09d-2a92-40d4-a42a-f780c3b3b171.png)
3. I'm not sure this report is an Issue or by the design of getDirectPrecedents but  I think, this result wants to be a below picture
![correct_pic](https://user-images.githubusercontent.com/98725157/164651836-18a528ab-08b9-4679-a8fa-9279af6cb2aa.jpg)
4. real case is  I want to a getting value from getDirectPrecedents but the pattern result not fixed It's hard to keep applying the results.

by refinitiv.com

**Comment by guliums** [comment] 2022-04-24 06:37
Hi @Refinitiv-365 , Thanks for reporting this. The behavior is by design that the precedents ranges will be merged if possible. So if the formula has both A1 and A2 it will be merged to A1:A2 in final result. The original reason of this design is to avoid creating too many ranges which may have impact on performance, and also align with VBA corresponding API behavior. 
Could you please share more about your scenario, how will you use the getDirectPrecedents results, and why "It's hard to keep applying the results"? Thanks.

**Comment by Refinitiv-365** [comment] 2022-04-24 08:10
My scenario
I want create a formula from cell reference geetting result `=Data("A,B","closePrice,openPrice")` but user using cell reference
`=Data("A1:B2","C1:B2")`

step to process

1. find the address and woksheetId of formula
2. create range from no 1 `const range = context.workbook.worksheets.getItem(worksheetId).getRange(address)` 
3. use function getDirectPrecedents()
4. return value of getDirectPrecedents()
5. use value No.4 create  a formula 

thank you for the result, I raise. I maybe change the logic to create a formula from cell reference 

Kind regards

**Comment by guliums** [comment] 2022-05-05 00:57
Hi @Refinitiv-365 , Thanks for the details. If you still need non-merged result, could you post a feature request on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Feature requests will be considered when we go through our planning process. Thanks for your support.

**Closed as completed** 2022-05-06 06:26 UTC
Labels: Area: Excel, Type: product feature request, Resolution: by design
