### ISSUE TITLE
Ribbon Icons not displayed for Windows desktop client, but work on web client

### ISSUE THREAD

**Issue by timbeese** [OfficeDev/office-js#1681] opened 2021-03-01 19:40 UTC
## Expected Behavior

We expect for the same icons on the ribbon to be shown on the desktop that we see on the web.

## Current Behavior

We have an add-in for Excel that defines several icons for the ribbon.  Our add-in is deployed on site for the customer, so the URL for the icons is specific to the customer deployment.  Here is a snip from our manifest file, where ~remoteAppUrl would be replaced by the host at that site:

  <IconUrl DefaultValue="~remoteAppUrl/SASOfficeAddin/public/sas32.png" />

        <bt:Image id="SAS.Home.16" DefaultValue="~remoteAppUrl/SASOfficeAddin/public/sas16.png" />
        <bt:Image id="SAS.Home.32" DefaultValue="~remoteAppUrl/SASOfficeAddin/public/sas32.png" />
        <bt:Image id="SAS.Home.80" DefaultValue="~remoteAppUrl/SASOfficeAddin/public/sas80.png" />

This works great for the web client of Excel, but when we load the add-in on the windows desktop version of Excel, all of the ribbon icons are missing.  The icon that is shown in the "Get Add-Ins" dialog is displayed correctly though.  It comes from the same web address as one of our ribbon icons.

At one point this did work for me on my desktop Excel, back when we had our security policy wide open to just make sure that we could load.  Once we tightened up the security, they stopped showing in the desktop (but still show in the web).  Afterwards, we went back and undid all of the security settings that we changed, but the real icons never showed back up.

We verified with fiddler that the image was being returned over the wire to the Excel desktop client.

## Steps to Reproduce, or Live Example

Unfortunately we don't have a live example, since our add-in is deployed directly to a customer site on top of our suite of products.

## Your Environment

My entire team is experiencing this.  Here are the specifics for what I'm running:
Excel: 2008 (Build 13127.21216 click-to-run) 32-bit
          Semi-Annual Enterprise Channel
Windows: 20H2 (OS  Build 19042.630)

## Useful logs

Here are the headers from when I access this image in an Edge Browser.

accept-ranges: bytes
cache-control: public
content-length: 2184
content-security-policy: default-src 'self';font-src *;script-src https://appsforoffice.microsoft.com 'self' 'unsafe-inline' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src * blob: data:;child-src * blob:;frame-ancestors 'self' https://sasoffice365-my.sharepoint.com https://excel.officeapps.live.com;
content-type: image/png; charset=utf-8
date: Mon, 01 Mar 2021 19:38:32 GMT
last-modified: Mon, 01 Mar 2021 17:42:54 GMT
sas-service-response-flag: true
set-cookie: a13692ff-xxxx-405f-990b-0c5c1f61c4b6=xxxxxxxxxxUxMnxOd3dBTkVGQlExSlVTMHBJUkVRMlRqUkZRMUZGVXpKSVFrMVRNek0yUWtoRk4wVkhWVkpFV0ROUk5WbElWalZCVDFSQlYxZENXRUU9fOT7z3MYi7DnS72024rltaLQOWTU4IIpwKWDBV4rYwlM; Path=/SASOfficeAddin/; Expires=Mon, 01 Mar 2021 20:08:32 GMT; Max-Age=1800; HttpOnly; Secure; SameSite=None
strict-transport-security: max-age=15724800; includeSubDomains
vary: Origin
vary: Cookie
x-b3-sampled: 0
x-b3-spanid: 13ddb85465779573
x-b3-traceid: 13ddb85465779573
x-content-type-options: nosniff

**Comment by AlexJerabek** [comment] 2021-03-01 21:59
Thanks for reporting this @timbeese.

@sohailzafar, can you please investigate?

**Comment by sohailzafar** [comment] 2021-03-09 01:24
Thank for providing the detailed repro steps. We suspect that the icon is not getting cached in desktop. Desktop client needs a cache in order to use the icon and this is by design. Can you try checking the response for “vary: Cookie” header and remove that if present because that prevents the caching.

Thanks
Sohail

**Comment by timbeese** [comment] 2021-03-09 14:03
Yes, the vary: Cookie header is indeed the culprit here.  I changed our header to return vary: Accept-Encoding instead, and the icons showed up in my desktop Excel client.  Thank you for the information!

**Comment by ElizabethSamuel-MSFT** [comment] 2022-08-09 21:22
Closing as the question was answered and issue resolved.

**Closed as completed by ElizabethSamuel-MSFT** 2022-08-09 21:22 UTC
Labels: Area: add-in UI, Type: product question, Resolution: question answered
