### ISSUE TITLE
Office dialog is not loading (Dialog API) from Excel add-in Taskpane on some desktop excel application.

### ISSUE THREAD

**Issue by ektadesai22** [OfficeDev/office-js#1867] opened 2021-05-17 06:51 UTC
Office dialog box is not loading (Dialog API) from Excel add-in Taskpane on some desktop excel application.
Can you help us to identify the root cause?

Configurations:
	Windows 10 Pro 
         Microsoft office Professional Plus 2016 (version 2104, build 13929.20372) – 64 bit

![image](https://user-images.githubusercontent.com/40557245/118443916-1785a300-b6b2-11eb-9f86-a66cc92dc56a.png)

Even unable to debug as target is not showing in either Edge Devtool preview or F12 developer tool.

**Comment by slabereemsft** [comment] 2021-05-17 17:22
Hi ektadesai22,

From the title, it says its not able to work on "some desktop excel application".  Does that mean it does work on others?  If so, you do you have details on the differences?

A great way to diagnose the issue is to take a fiddler trace to see what resources its trying to hit (if any) and compare between the two.  

One thing to check out is the following - https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#:~:text=%20Use%20the%20Office%20dialog%20API%20in%20Office,messages%20from%20the%20host%20page%20to...%20More%20.  The dialog box's domain is the same as the domain of the host page, which can be the page in a task pane or the function file of an add-in command. This is required: the page, controller method, or other resource that is passed to the displayDialogAsync method must be in the same domain as the host page.

**Comment by ektadesai22** [comment] 2021-05-18 02:00
@slabereemsft - Thank you for quick response.

Yes, it is working on other, below is configurations.

   Windows 10 Home
   Microsoft office Professional Plus 2016  (version 2104, build 13929.20372) – 64 bit

I will check fiddler trace and compare.
The dialog box domain is different. I will do changes & will update you on this.

**Comment by ektadesai22** [comment] 2021-05-20 15:06
@slabereemsft - The site which I am trying to open in dialog is not supported Internet explorer. Do you think this could be a reason? Is there any way that add-in uses Microsoft Edge browser instead on internet explorer?

**Comment by SergDi** [comment] 2021-05-27 14:25
I have the same error when opening dialog (displayDialogAsync)
in **MonthlyEnterprise Channel**
_Version 2103 (Build 13901.20516)
MSO 16.0.13901.20516  64-bit_

**Windows Event Viewer:**
> Add-in Error
> Sorry, we can't load the add-in. Please make sure you have network and/or Internet connectivity. Click "Retry" once you're back online.
> P1: Apps for Office
> P2: 16.0.13901.20516
> P3: 0x800C0004

however, it works OK in **SemiAnnual Channel**
_Version 2008 (Build 13127.21624)
MSO 16.0.13127.21624  64-bit_

Besides, we cannot debug our add-in in Version 2103 with Microsoft Edge DevTool - the add-in process is not available in the Debug Targets list. It is available there in Version 2008.

**Comment by lliu113** [comment] 2021-06-01 22:31
@ektadesai22 are you able to provide your manifest so we can help troubleshoot?

**Comment by lliu113** [comment] 2021-06-02 19:14
@ektadesai22 - another quick test you can do is to try and run the Scriptlab add-in. This will determine if it is a platform issue. To acquire the add-in, go to your Excel App > Insert > Get Add-ins > Search for Scriptlab > Click "Add". Once installed, try and launch a dialog by clicking on "Tutorial" in the ribbon. 

Let us know if you're able to successfully launch a dialog. If so, there might be an error in your code - one possible culprit is not hooking up the onReady callback correctly.

**Comment by ektadesai22** [comment] 2021-06-02 22:39
@lliu113 - I have found the root cause why it is not loading but I am not able to understand what causing it.

I have use window.location.href in DialogParentMessageReceived event. It is not redirecting. So I made changes and reopen dialog for that URL.

`Office.EventType.DialogParentMessageReceived,
    (event) => {      
		var req = new XMLHttpRequest();
		req.open("POST", "/xxx/");
		req.onreadystatechange = function () {
		  if (this.status == 201) {
			**window.location.href = url;**
		  }
		};
		req.send();
    }
}`

So instead of redirecting here, using messageParent event, reopen dialog.
Office.context.ui.messageParent("avc");

**Comment by ektadesai22** [comment] 2021-06-07 03:41
@lliu113 - I have found the root cause why it is not loading but I am not able to understand what causing it.

I have use window.location.href in DialogParentMessageReceived event. It is not redirecting. So I made changes and reopen dialog for that URL.

Office.EventType.DialogParentMessageReceived, (event) => { var req = new XMLHttpRequest(); req.open("POST", "/xxx/"); req.onreadystatechange = function () { if (this.status == 201) { **window.location.href = url;** } }; req.send(); } }

So instead of redirecting here, using messageParent event, reopen dialog.
Office.context.ui.messageParent("avc");

**Comment by SergDi** [comment] 2021-06-07 09:35
@lliu113 - I have added some content to the page that opens in a dialog box for testing. I can see this content, so the problem is not caused by the onReady callback. 
After this, a Javascript running the oauth code flow is started on this page, and then Auth0 Authorization Server redirects the user to the login and authorization prompt. 
This page is not displayed in the dialog box.

**Comment by lliu113** [comment] 2021-06-08 22:18
@ektadesai22 - thanks for debugging this. Just so I understand, the dialog was throwing an error when you were using window.location.href, is the code you provided the fixed version? So instead of redirecting directly you're setting the URL as part of the DialogParentMessageReceived event and navigating to it from the dialog? 

@SergDi - is your dialog displaying correctly, but throws the "Sorry we can't load the add-in" error once the oauth code runs? Or is it displaying the error as soon as the dialog is launched? Are you able to provide a manifest to help us repro? Thanks!

**Comment by SergDi** [comment] 2021-06-09 06:50
@lliu113  - 
I already solved the problem, I added setTimeout for the oauth code runs

**Comment by ektadesai22** [comment] 2021-06-11 01:18
> @ektadesai22 - thanks for debugging this. Just so I understand, the dialog was throwing an error when you were using window.location.href, is the code you provided the fixed version? So instead of redirecting directly you're setting the URL as part of the DialogParentMessageReceived event and navigating to it from the dialog?
> 
@lliu113 - Yes, it fixed my issue. Instead of window.location.href, I have used messageParent event and reopen open dialog on success.

**Comment by lliu113** [comment] 2021-06-28 19:36
@ektadesai22 - awesome, that's great to hear! Glad you got it working. 

I'll go ahead and close this issue, feel free to reactivate if you have any additional questions. Thank!

**Closed as completed by lliu113** 2021-06-28 19:36 UTC
Labels: Needs: attention :wave:, Area: add-in UI
