### ISSUE TITLE
Error in Admin Portal -> "Update Manifest via URL"

### ISSUE THREAD

**Issue by Kronenberg** [OfficeDev/office-js#2278] opened 2021-11-28 10:17 UTC
In admin portal in any web browser when admin trying update the add-in using "I have a URL for the manifest file" he gets error.

Cannot perform the action you requested. Please try again later.
(e94d32e2-6031-4b99-86f4-d49ddcf79fe3)

If we are going same flow but with "I have the manifest file (.xml) on this device.
Everything is working, and we are using same manifest version that we download from our link.

As a workaround we are using update from file meanwhile.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac/Windows
* Office version number: not related to this bug
* Operating System: Windows/MacOS
* Browser: All browsers 
 
## Expected behavior
Update should work with the same manifest using "update manifest via URL" feature.

## Current behavior
1. Trying update manifest via URL
2. Getting error
3. Cannot perform the action you requested. Please try again later.
(e94d32e2-6031-4b99-86f4-d49ddcf79fe3)

## Steps to reproduce
1. Go to the admin portal
2. Update manifest
3. Choosing the first option -> "I have a URL for the manifest file" 

## Context

I need to know there is a bug on your side, or it's our issue.
Meanwhile as a work around "our customers" using the update from file, which is not so comfortable for them from UX perspective.

p.s. if you need more details from our side, please tell me in a comments.

## Useful log
![2021-11-21_15h29_52 (1)](https://user-images.githubusercontent.com/13053374/143763829-6f92a558-654a-4e29-92dd-9fe9267f569b.png)

**Comment by AkhileshShah-MS** [comment] 2021-12-01 19:18
Hello! Could you please share following info regarding the issue. 
- Is the issue limited to single add-in and/or single tenant or happening with multiple? 
- Does the URL contain any redirection or is directly pointing to the add-in manifest? 
Thanks!

**Comment by Kronenberg** [comment] 2021-12-02 12:56
Hello, here is all the details:
1. No its not for single tenant, it's happening with multiple -> "22a34b4e-6093-4e8c-ae5e-bc296f985bca", if you need more tenants let me know. This is our internal tenant of our organization.
2. No ULR didn't contain any logic behind the scenes, and we didn't change for very long time (during like two years) and it worked perfect.

**Comment by atsopuronen** [comment] 2021-12-08 23:45
Have you attempted to insert the manifest URL with or without "https://" in the beginning? 
At least at one point the empty URL field contained "https://", suggesting you shouldn't include that part in your copy-paste. Adding the manifest URL without "https://" resulted in an identical error for me.

**Comment by eran-levy** [comment] 2021-12-09 17:01
As far as I know @atsopuronen , just checked it now - the field includes the https:// in the beginning as a pattern. I just checked and the error still happens and we are not pasting the "https" twice

**Comment by atsopuronen** [comment] 2021-12-10 08:53
Sorry for ambiguity in my last post. I meant:
Make sure the manifest URL you paste into the field DOES include "https://".

**Comment by Kronenberg** [comment] 2021-12-13 13:41
> Sorry for ambiguity in my last post. I meant: Make sure the manifest URL you paste into the field DOES include "https://".

Here is example of our URL -> https://user.company-name.cloud/inbox-security/outlook/addin/cis-manifest.xml

**Comment by batatg** [comment] 2021-12-14 07:26
The thing here is that when we do 'Deploy Add-In' with this URL - it works.
Only when we do 'Update Add-In' - it fails.
When looking at the error in the network, I see that the request to UpdateAddIn returns with status code 200 but with but with ResponseResult "BadRequest" in the body

**Comment by batatg** [comment] 2021-12-21 18:08
@AkhileshShah-MS hi, what do you think? do you have any suggestion?

**Comment by clavx** [comment] 2021-12-23 08:55
I've been unable to update from the **URL** for almost a month. Is there a plan to fix this?

`UpdateVersionSameOrLower` should be returned.

---

### I have the manifest file (.xml) on this device

```
ErrorMessages: null
ResponseResult: "UpdateVersionSameOrLower"
ScopesNeedConsent: null
```

### I have a URL for the manifest file

```
ErrorMessages: null
ResponseResult: "BadRequest"
ScopesNeedConsent: null
```

https://user-images.githubusercontent.com/58804032/147214165-69eb3b35-49e5-4b62-95a9-43ebf9d837cf.mp4

**Comment by AkhileshShah-MS** [comment] 2021-12-24 08:19
Hello! We are working on fixing the issue with update from URL. In meantime as a work around, you can update the add-in by uploading the manifest file after increasing the version number. Another alternate is to update the add-in from Integrated Apps portal in M365 Admin Center (Settings>Integrated Apps).

**Comment by clavx** [comment] 2022-02-22 07:30
I checked the current status and found that the Deploy from URL function works fine.
So does that mean it is fixed? Thanks.

**Comment by Driss878** [comment] 2022-06-15 14:07
@AkhileshShah-MS we have the issue now the other way around. Why can't we upload a file for update at this time ?

![MicrosoftTeams-image](https://user-images.githubusercontent.com/107562369/173847616-5699523b-06ba-454d-ae0b-d0eab34b6dbd.png)

**Comment by exextoc** [comment] 2022-06-28 09:18
@Driss878  Kindly share the manifest on addin-help@outlook.com. You can mask those fields in manifest which you think is PII. We will be fixing this issue. We are not able to reproduce this issue for any other LOB addin.

Thanks.

**Comment by exextoc** [comment] 2023-07-14 05:04
No action for quite some time. Closing the issue.

**Closed as completed by exextoc** 2023-07-14 05:04 UTC
Labels: Area: Centralized Deployment
