### ISSUE TITLE
Office.context.mailbox.item.body.getAsync not working properly with Office.context.mailbox.item.body.setSignatureAsync

### ISSUE THREAD

**Issue by kinkoazc** [OfficeDev/office-js#3104] opened 2023-01-20 11:15 UTC
## Your Environment

* Platform: PC desktop
* Host: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2302 Build 16.0.16110.20000) 64-bit 
* Operating System: Windows
* Browser (if using Office on the web): N/A
 
## Expected behavior
Office.context.mailbox.item.body.getAsync should return the full e-mail body(including the set signature)(even when no character was written yet by the user)(like is currently the case in OWA).

## Current behavior
`Office.context.mailbox.item.body.getAsync` doesn't pick up on the signature set by `Office.context.mailbox.item.body.setSignatureAsync` on recipient change event, `OnMessageRecipientsChanged`, for initial(empty) compose messages.

## Steps to reproduce

1. start composing an e-mail
2. signature gets set automatically
3. start typing recipients
4. `Office.context.mailbox.item.body.getAsync` doesn't pick up on the set signature(returning the initial body value, pre signature setting)

## Link to live example(s)

https://github.com/kinkoazc/Office-Add-in-samples.git (adds recipient change launch event) + edit `addTemplateSignature` like here https://gist.github.com/kinkoazc/c48db02bb3ccbcd77bd04a2933c4ad34 (asks for body during signature setting)

# Provide additional details

* current behavior(as seen in the above repro test): OWA: `true true`; Outlook for Desktop: `true false`
* expected behavior(as seen in the above repro test): OWA: `true true`; Outlook for Desktop: `true true`

## Context

Compose-event applied signature cannot be detected on recipient changes events for initial(empty) compose messages.

## Screenshots

- OWA:
![image](https://user-images.githubusercontent.com/2164590/213681748-fb37a4f4-7715-4190-b60f-78bc61b60b00.png)
- Outlook for Desktop:
![image](https://user-images.githubusercontent.com/2164590/213681838-69148318-c22e-4c6b-a8f8-634c8d671928.png)

**Comment by ztcdsb** [comment] 2023-01-27 17:50
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point 

Internal tracking id: Office: [7544516]

**Comment by ztcdsb** [comment] 2023-01-30 23:28
Hi @kinkoazc, I want to update you that we are planning a fix for this issue. I wonder if you can share your user scenarios about it?
For example, what are you planning to do with the updated signature

**Comment by kinkoazc** [comment] 2023-01-31 08:22
Hello @ztcdsb! Thank you for your reply. Some scenarios would be:
-checking if a signature is actually present/applied(with further ramifications, e.g. task pane signature highlighting, etc.);
-adjusting the applied signature based on the recipients(only if it is present).

Another thing I forgot to point out. If the user starts typing the message first and later add the recipients, `Office.context.mailbox.item.body.setSignatureAsync` works as expected(retrieving both the user's message content & the signature).

**Comment by ztcdsb** [comment] 2023-02-01 18:17
@kinkoazc Thanks for sharing the scenario!

Yes, this is expected, because we don't want to dirty the email body with auto-inserted signature. But if you type in the body, the item will be considered as dirtied and it will be cached.

Another work around is to call saveAsync() after inserting signature, but this will automatically save the current item in draft as well.

**Comment by kinkoazc** [comment] 2023-02-02 07:00
@ztcdsb Thank you for the suggestion. I think I've tried `saveAsync()` in the past and it didn't work/make a difference for me. Maybe I'm doing it wrong?
I've updated the `addTemplateSignature` function here https://gist.github.com/kinkoazc/eac30f43bf311999c1046465fcdf75dc.

For consistency, I think `getAsync`s response in Outlook for Desktop should be on par with the current response in OWA.

**Comment by ztcdsb** [comment] 2023-02-28 20:16
@kinkoazc I am sorry for the delay in getting you back and thanks for sharing the code snippet, we have created a internal task to resolve this issue, but we do not have a timeline to share at the moment. The internal task number is 7544516.

It will help us better understand your needs if you can answer the following questions,  
1. What is the  # users of impact 
2. Is this going to be a blocker for your mail workflow?

**Comment by kinkoazc** [comment] 2023-03-01 08:10
@ztcdsb Hello. Thank you for the reply.

On the questions:
1. Currently thousands; blocking tens of thousands from migrating to the add-in from other type of application.
2. Yes.

**Comment by JuaneloJuanelo** [comment] 2023-03-06 22:36
@kinkoazc  why is this blocking? whats the user bad? i was wondering if we can meet with you to go through your scenario, of thats possible let us know here and can schedule some time with you.

**Comment by kinkoazc** [comment] 2023-03-07 16:13
@JuaneloJuanelo I could send you a recording of the use case. Would that help? If so, where should I send it to?

**Comment by ztcdsb** [comment] 2023-03-08 00:20
@kinkoazc To better protect users data, we recommend you create a private repo and upload the recording there. You can give access to @exextoc so that everyone in my team can review it.

**Comment by JuaneloJuanelo** [comment] 2023-03-09 19:38
@kinkoazc  or send me the link directly: juanbl@microsoft.com

**Comment by kinkoazc** [comment] 2023-03-10 12:47
@JuaneloJuanelo I've tried to reproduce the issue. In doing so, I've realized I rely on checking if the signature is present or not(before actually updating the said signature). But I could just as well re-set the initial/auto-injected signature(initially set on compose event), only this time adjusted according to the current recipients(on recipient change event).
This works well when operating while having the taskpane opened(but, for the majority of the time, this is not the case). It doesn't work well however when the user explicitly removes the initial signature and later adjusts(adds/removes from) the recipients list, in which case the default/initial/auto-injected signature gets re-injected(when it shouldn't have).

So at this time I can say it's not a blocker. I will post here if, while testing, these changes do turn out to be a blocker(through some other mechanism). Thank you.

**Comment by JuaneloJuanelo** [comment] 2023-03-29 02:05
@kinkoazc  what you describe on your first paragraph is exactly the guidance we recommend. You can use the recipientChanged auto launch events to id if you need to add different signatures for external recipients.  You DONT need to have the taskpane open for this, that's the beauty of [Event Based Add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest)s! again there is a recipientsCHanged event. 

Btw i am assuming you are also using event based add-ins for adding the signature on new Message compose events!. so you just need to add another event there! 

thanks and i am glad to hear this is no longer blocking you! .

**Closed as completed by JuaneloJuanelo** 2023-03-29 02:05 UTC
Labels: Needs: attention :wave:, Area: Outlook

**Comment by kinkoazc** [comment] 2023-03-29 05:13
@JuaneloJuanelo Why was this issue closed? In which version of Outlook for desktop will the fix be available? I've mentioned it was not a blocker, not that it was not an issue anymore. Please check the current issues/scenarios I described at https://github.com/OfficeDev/office-js/issues/3104#issuecomment-1463756173.

**Comment by JuaneloJuanelo** [comment] 2023-03-29 18:02
@kinkoazc I believe you have the necessary pieces to make your scenario work. If you don't want to replace what you originally inserted on  the newMessage or in the recipientsCHanged  autolaunch events  you can add customer property or sessionData value on the message working as flag to avoid doing that.   I also  think you will find situation when you NEED to replace the current [customized] signature, for instance upon first external recipient if there is a signature for externals might need to be replaced.  I think having something keeping state of your previous operations can help you to reinsert or not the new signature. 

btw the approach you are taking to get to see if the signature was customized, i believe is not the optimal one (by getting the body of the email) this could become a performance issue depending on the size of the message.

We added an item in our backlog for consideration to add a new API to get the current signature. [intenally tracked as 7748334]. we dont have an ETA  on the release date as of now.

**Comment by kinkoazc** [comment] 2023-03-31 07:19
@JuaneloJuanelo The issue is, as I've described in https://github.com/OfficeDev/office-js/issues/3104#issuecomment-1463756173, that I'm working blindly(considering that the user didn't mess with the auto-injected signature, in the sense of clearing it). Not sure how I can track this(since the body isn't showing any signature, whether there is one or not). The new/proposed 7748334 API could help with this. Currently, this is still an issue.

**Comment by JuaneloJuanelo** [comment] 2023-04-03 21:36
Thanks @kinkoazc and yes 7748334  will help.

 Just to add clarity here, "blindly" could lead to potential misinterpretations, because if the user changes the body content you will get the latest signature via getBody, in other words, this will only be an issue if the user is done typing the body AND changes the inserted signature AND adds a recipient at the end.  Even in that case the signature might need to be replaced if your add-in supports external recipients and an external recipient was added.

So, with all those factors to a degree this makes this issue relatively edgy, but anyway it's in our backlog for consideration and will be implemented after proper prioritization.

**Comment by ernie-b-jaamin** [comment] 2025-03-18 10:01
@JuaneloJuanelo we have this same issue, and unfortunately it is not an edge case for us. I was hoping this item can be reconsidered for prioritisation.

Our use case:
Our customer uses Signature365 add-on to automatically add their signatures that contain marketing info, campaigns, etc. The add-on uses setSignatureAsync to add the signature to the email. The user will then use a separate add-on to send the email (frontend logic with OfficeJS and server-side sending via MS Graph).

The only scenario that does not work is that they are using a third-party system to generate emails, this uses a mailto link. If an email is created via mailto and sent immediately without changing the body of the email, the signature is not added. If the user makes any change to the body, it works. Programmatically "dirtying" the email doesn't work. The problem is that the expectation from the customer's side is that this system is used extensively, and mostly emails are not changed before sending, making this a major blocker for them, they are unable to accept manually changing the email as a workaround (as they shouldn't, doesn't make sense as "expected behaviour").

Any assistance would be greatly appreciated, especially if there has been any new info on this since this item has been closed.

Thanks!
