### ISSUE TITLE
Click spamming breaks pushing a format update

### ISSUE THREAD

**Issue by sethachoi** [OfficeDev/office-js#792] opened 2019-10-20 06:06 UTC
(Related to #791 at least in context)
When pushing a format update (IE cell highlight color), spamming clicks can prevent the format change from updating.

## Expected Behavior
Click spamming should not prevent cell formatting push.

## Current Behavior
Occasionally, spamming clicks will prevent the cell from properly updating formatting.

## Steps to Reproduce, or Live Example
- On some sort of trigger, push an update to cell format (in our case, cell highlighting)
- After trigger is initiated, spam clicks on other cells, etc.
- Occasionally to rarely, format will not trigger
- [Relevant scriptlab gist](https://gist.github.com/sethachoi/8964a4dea397ca6e4fb7841af4975647)

## Context
In our app, we're looking to push some sort of visual feedback based on user input. In the context of a larger app (thus with more context.sync()s and such) it's much easier to reproduce this bug than in the minimum case gist.

## Your Environment
- Platform [PC desktop, Mac, iOS, Office Online]: Win Desktop with Office Online
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Operating System: Windows 10
- Browser (if using Office Online): Chrome 77.0.3865.120

## Useful logs
Wrapping the context.sync() after formatting in a try/catch with console.log(error) produced this message upon borkage:
```
RichApi.Error: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again.
    at new c (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:286433)
    at a.e.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:346713)
    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:345089
```

**Comment by catchingyu** [comment] 2019-10-23 05:51
Can you share with us how often do you encounter this problem? To say, trying 10 times, how many time it can be reproduced?

**Comment by sethachoi** [comment] 2019-10-24 00:24
@catchingyu hi thanks for the reply

In the case above when I am deliberately trying to break it, I can usually break it about half the time, but that's with me spamming clicks at an inordinately fast rate. In our actual "real world" code, we run into problems with it maybe like... 3/10 times when we aren't deliberately trying to trigger it? Maybe a little less or a little more, but 100% enough to notice that it's happening.

Thanks!

**Comment by catchingyu** [comment] 2019-10-30 06:12
team is investigating and reproducing it now. with the bug ID 3747321

**Comment by topkoong** [comment] 2019-11-15 08:09
Any update on this? I face this issue as well. @catchingyu

**Comment by lumine2008** [comment] 2019-12-10 08:29
Hi @sethachoi, 
I think there are 2 issues in your post:
1) Cell Edit mode API issue 
2) Spam click prevent the format change from updating

for 1#, I could not repro this issue when clicking the cell randomly but not entering the cell edit mode. if I enter the cell edit mode, it throws an exception, which is expected. because API cannot be run in cell edit mode is by design, the reason is CellEditMode is a very special mode in the Excel, both VBA and JS API cannot run in the CellEditMode. So API calls will fail and throw the exception.

for 2#,  Spam click -> will your spam click result in range selection?
I can repro if I spam click which results in range selection. This issue repro in Excel Online, I would like to know whether we are experiencing the same issue or not
PS. can you repro in Win32?

**Comment by sethachoi** [comment] 2019-12-10 21:25
hi @lumine2008 

Thanks for the reply

For #1 that makes sense, but I was wondering if there's something we/I can do about that. The issue is because we can have calls queued up in the queue whenever something is happening, but because the user still has full control over the client they can just trigger the failure case whenever by accident. Is there any way to deny the user from trigger those circumstances, like blocking clicks from triggering anything?

#2 I will check out later when I have access to my home machine and get back to you on that. I'm not 100% certain that is the case however I would not be shocked if during my rapid clicking I was selecting a range instead of a cell.

**Comment by sethachoi** [comment] 2019-12-11 04:56
Update: can confirm that #2 happens, no idea re win32, only have access to x64

**Comment by lumine2008** [comment] 2019-12-25 08:26
@sethachoi , 
for 1#, you could use delayForCellEdit,  When true, the batch request will be executed immediately if the user is not in cell edit mode, but if the user is in cell edit mode the batch request will be delayed until the user exits cell edit mode. the document can be found at https://docs.microsoft.com/en-us/javascript/api/excel/excel.runoptions?view=excel-js-preview

This is the gist I used, please have a try
https://gist.github.com/lumine2008/ee3041b5f56b2c247c9163cada09af88

for 2#, sorry for the confusion, Win32 what I mean is Win Desktop, x64 is good too.

**Comment by lumine2008** [comment] 2021-03-17 06:31
Closing this issue, please reactivate or open a new issue if you still observe the issue.

**Closed as completed by lumine2008** 2021-03-17 06:31 UTC
Labels: Needs: attention :wave:, Area: Excel, Type: product bug, Area: add-ins platform
