### ISSUE TITLE
Reload button in task pane of Excel installed version on Window10 did not reload on previous URL

### ISSUE THREAD

**Issue by seenark** [OfficeDev/office-js#1805] opened 2021-04-19 06:47 UTC
The **Reload Button** provided in taskpane did not reload on previous URL but there is reload from Ribbon URL.
I did reload my taskpane by same URL and add some query-params for determine which angular module to be lazy-load after taskpane reload completed, this things work well on Excel website in Chrome, IE11, MS Edge(Chromium), MacOS(installed version) but on Window10 it is not. I opened **F12-IEChooser** for debugging the taskpane, in **console** I write `window.location.reload() ` then it can be reload the taskpane, also `window.location.href="https://myurl?module-tobe-load=my-angular-module-name"` also work fine
The things I was explained I need the query-param info to be describe which module I have to lazy-load
When click reload taskpane it load URL from Ribbon so my query-param is not there because I was add into URL later

In my Angular app we use hash # for routing so my my URL look like this `https://localhost:10100/Apps/RFO-Ribbon/app?module=ribbons&rdpdata=RDP.Data2&cf=custom-functions-dev&_host_Info=Excel$Win32$16.01$en-US$$$$3#/formula-builder` so when reload in excel website I can get this url from iframe src. reload at the first time I will get this URL then I look after hash(#) that is my module name in this case is `formula-builder` then I send `window.location.href=https://localhost:10100/Apps/RFO-Ribbon/app?module=ribbons&rdpdata=RDP.Data2&cf=custom-functions-dev&_host_Info=Excel$Win32$16.01$en-US$$$$3&redirectToModule=formula-builder` for reload second time 
but in Excel installed version of Window10 when click reload the query-param I was added`&redirectToModule=formula-builder`  is not there the URL look like from Ribbon instead.

## Expected Behavior

I Expect to reload from URL in the previous like in Excel website will reload by the URL in src of iframe <iframe src="url&myqueryParam=my-module-name">
## Current Behavior

Excel reload by use taskpane URL from Ribbon so my query-param I was added is not there 

my suggestion is when click reload it should be take the previous url and use it for load taskpane again instead of URL from Ribbon
## Steps to Reproduce, or Live Example

In my Angular app we use hash # for routing so my my URL look like this `https://localhost:10100/Apps/RFO-Ribbon/app?module=ribbons&rdpdata=RDP.Data2&cf=custom-functions-dev&_host_Info=Excel$Win32$16.01$en-US$$$$3#/formula-builder` so when reload in excel website I can get this url from iframe src. reload at the first time I will get this URL then I look after hash(#) that is my module name in this case is `formula-builder` then I send `window.location.href=https://localhost:10100/Apps/RFO-Ribbon/app?module=ribbons&rdpdata=RDP.Data2&cf=custom-functions-dev&_host_Info=Excel$Win32$16.01$en-US$$$$3&redirectToModule=formula-builder` for reload second time 
but in Excel installed version of Window10 when click reload the query-param I was added`&redirectToModule=formula-builder`  is not there the URL look like from Ribbon instead.

* Link to live example: [video example on google drive](https://drive.google.com/file/d/1oiLg_jeiEYyIFvQLUVPlW9d2j9U2MzjW/view?usp=sharing)

## Context

this affected me only in excel installed version on Window10 only but when click on ribbon again it will work fine the taskpane can be load, for real world this is a bad user experience they just click reload for refresh taskpane why they have to click on ribbon again for reload it once

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Notebook Dell
* Host [Excel, Word, PowerPoint, etc.]: MS Excel installed version 
* Office version number: version 2008 build: 13127.21348
* Operating System: Window10
* Browser (if using Office Online): none

## Useful logs

- [x] [video example on google drive](https://drive.google.com/file/d/1oiLg_jeiEYyIFvQLUVPlW9d2j9U2MzjW/view?usp=sharing)

**Comment by jipinshi** [comment] 2021-04-25 07:54
@jeremy-msft , can you help take a look?

**Comment by lliu113** [comment] 2021-04-26 19:41
@seenark sorry you're hit this! This is by design, the "Reload" command on the personality menu reloads the add-in to the base URL specified in the manifest. Sorry for the confusion this may have caused. 

I'm going to go ahead and close this issue, please reactivate if you have any further questions. Thanks!

**Closed as completed by lliu113** 2021-04-26 19:41 UTC
Labels: Area: Excel, Resolution: by design
