### ISSUE TITLE
Outlook Web add-in which opens up Dialog using displayDialogAsync. It crashes after keeping it open for ~5-6 mins. After that I am unable to open unless I refresh the tab in which it was open.  Office Web Addin Dialog pop up to close in 5mint . There is a time limit of approx 5 mins. If the pop is not closed with in that time span it would be automatically closed.  

### ISSUE THREAD

**Issue by soumyamondal-accenture** [OfficeDev/office-js#3823] opened 2023-11-08 14:33 UTC
Outlook Web add-in which opens up Dialog using displayDialogAsync. It crashes after keeping it open for ~5-6 mins. After that I am unable to open unless I refresh the tab in which it was open.  Office Web Addin Dialog pop up to close in 5mint . There is a time limit of approx 5 mins. If the pop is not closed with in that time span it would be automatically closed.  

Reporting the same issue as this issue got closed without further info : https://github.com/OfficeDev/office-js/issues/3761

**Comment by alison-mk** [comment] 2023-11-09 20:30
Hi @soumyamondal-accenture, thank you for submitting an issue. Your issue #3761 was closed because we requested more information ("Is this new issue also browser only?") and a response was not received within the necessary timeframe. Our system will automatically close issues if information is requested and not provided. 

I'll assign this new issue to the @exextoc team so that they can review it. Please also provide an answer to the earlier question: Is this issue browser only?

Thank you, 
Alison

**Comment by soumyamondal-accenture** [comment] 2023-11-16 05:41
@alison-mk  it happens both in outlook thick client and OWA.

**Comment by soumyamondal-accenture** [comment] 2023-11-24 13:22
@alison-mk @exextoc  can you please provide any comment on the status of whether the item is going t be picked or not?
We have certain concurrent operations that carry out validations on a chnk of data and siplay the results in the popup, but those operations sometime take near about 5mins, so we need a way to persist the popup >5mins, is there ahy way we can achive that?

**Comment by ajays-msft** [comment] 2023-12-12 06:59
@soumyamondal-accenture  - When you say think client is it New Outlook or Old Outlook? Do you see similar behavior in Outlook Mac?

**Comment by soumyamondal-accenture** [comment] 2023-12-12 07:15
@ajays-msft The behavior is similiar in outlook (old,new thick client) and OWA on windows platform and MAC.
In 5mins the dialog box that opens using Office.context.ui.displayDialogAsync(window.location.origin + '/shell.html',{ height: 70, width: 50, displayInIframe: true }, automatically timesout and closes..with or wihout any activity within the dialog.

**Comment by ajays-msft** [comment] 2023-12-12 08:35
Thank you. What do the "It crashes after keeping it open for ~5-6 mins"? Does the application crash and close automatically?

**Comment by soumyamondal-accenture** [comment] 2023-12-12 09:12
@ajays-msft yes, the Office Dialog popup closes within 5mins, With or without any action inside the popup.

**Comment by ajays-msft** [comment] 2024-01-16 06:48
This is by design. If you think this needs to be changed, please request the feature through the Tech Community forum.
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Closed as completed** 2024-01-23 12:38 UTC
Labels: Area: Outlook, Needs: author feedback, Status: no recent activity
