### ISSUE TITLE
Outlook Add in Issue: Unable to Maintain Unified Login State Across Subdomains with Shared Authentication

### ISSUE THREAD

**Issue by ZabeehUllah** [OfficeDev/office-js#3964] opened 2024-01-04 13:55 UTC
# Issue Description
I have encountered an issue with maintaining a unified login state across subdomains despite utilizing shared authentication on a common domain. Here's the setup:

Authentication module and Outlook app hosted on the primary domain: **xiqonline.com**
Web app hosted on a subdomain: **salesapp.xiqonline.com**

When logging in to the web app (**salesapp.xiqonline.com)**, the browser saves cookies and localStorage for the primary domain **xiqonline.com**. Subsequently, upon redirection to **salesapp.xiqonline.com** (which shares the same parent domain), the cookies and localStorage for this subdomain are correctly set.

However, when attempting to access an add-in within the Outlook app, which resides on the subdomain **xiqonline.com**, the login state is not maintained. Despite the presence of cookies for the add-in, the localStorage appears to be empty, causing issues with authentication.

I've confirmed that the add-in's domain shares the subdomain structure **(xiqonline.com)** with the authentication module and web app, yet the localStorage data seems inaccessible within the add-in context.

I've checked that:

Cookies are present for the add-in.
localStorage data is missing when accessed from the add-in inside the Outlook app.
I'm seeking guidance on why localStorage data is not persisting or accessible within the add-in despite the shared domain structure.

## Environment
* Platform:  Office on the web
* Host: Outlook
* Office version number: OWA
* Operating System: Windows, Mac
* Browser: Across all browsers
 
## Expected behavior
When I login into webApp (salesapp.xiqonline.com), and after that I open outlook addin, it should be logged in too, because both have the same authentication domain, that is xiqonline.com. Localstorage of xiqonline.com is empty for addin although it's not when i check localStorage of webApp.

## Current behavior
When attempting to access an add-in within the Outlook app, which resides on the subdomain xiqonline.com, the login state is not maintained. Despite the presence of cookies for the add-in, the localStorage appears to be empty, causing issues with authentication.

## Steps to reproduce
1.  Web App link (https://xiqonline.com/auth/login/?redirectURL=https://salesapp.xiqonline.com)
2. Manifest file link (https://drive.google.com/file/d/1dE_Gn6hIow2SyZFgYaa9CvWdWzGT0JQD/view?usp=sharing)
3. Check localStorage and cookies for both addin and webapp

# Provide additional details
1. Main issue is that localStorage of add in is empty, although cookie has all the values

# Link to issue Video
https://www.loom.com/share/30230d93e8ef491cb641f99037bdaa52?sid=cbc3141b-4e32-4bb7-9486-78c6ccbdd017

**Comment by exextoc** [comment] 2024-01-08 11:19
Is the subdomain part of the AppDomain in the manifest? If not, can you add and try? For documentation refer below:
https://learn.microsoft.com/en-us/javascript/api/manifest/appdomain?view=common-js-preview

**Comment by ZabeehUllah** [comment] 2024-01-09 11:55
@exextoc  The issue is I have removed my previous add in but it still shows in the apps. I can't upload new one, to test my changes. There's caching issue.

**Comment by ZabeehUllah** [comment] 2024-01-10 07:50
@exextoc My manifest file includes the subdomian, but it still behaves the way, not accessing local Storage
Here are details:

Add in is hosted on : **https://newapi.xiqonline.com/**
Auth module is hosted on: **https://newapi.xiqonline.com/**
Web app is hosted on : **https://qasalesapp.xiqonline.com/**

App domains in my manisfest file are:

```
 <AppDomains>
        <AppDomain>https://xiqonline.com</AppDomain>
	<AppDomain>https://salesapp.xiqonline.com</AppDomain>
	<AppDomain>https://staging.xiqonline.com</AppDomain>
	<AppDomain>https://newapi.xiqonline.com</AppDomain>
	<AppDomain>https://login.microsoftonline.com</AppDomain>
	<AppDomain>https://qasalesapp.xiqonline.com</AppDomain>
       <AppDomain>AppDomain2</AppDomain>
       <AppDomain>AppDomain3</AppDomain>
  </AppDomains>

```
Here is the video link to the issue:
https://www.loom.com/share/7172fbe1ca2744fca3d17816f883bc64?sid=986ae99f-ac3a-4729-9e3c-833e35bcb36c

**Comment by exextoc** [comment] 2024-01-11 12:36
@ZabeehUllah If you are facing any issue with the Office JS API, then we can take a look. This not something where an API is involved that is failing. Closing, reopen if this issue is caused by any API related problem.

**Closed as completed by exextoc** 2024-01-11 12:36 UTC
Labels: Area: Outlook
