### ISSUE TITLE
setSignatureAsync stopped working in Outlook for Mac: An internal error has occurred.

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js#2226] opened 2021-11-04 06:18 UTC
Calling this worked a few weeks ago everywhere:-

`Office.context.mailbox.item.body.setSignatureAsync with [ "hello", {coercionType:"html"}  ]`

However - it no longer works in the Outlook program on Mac today (it does work on the web though):-

It now always does this:-

`{"status":"failed","error":{"code":5001,"message":"An` internal error has occurred.","name":"Internal Error"}

## Your Environment

* Platform: Mac
* Host: outlook
* Office version number: 16.16.27 / 16.16.20101200 - says "Up To Date" in updates dialogue.
* Operating System: Mac
 
## Expected behavior
no error

## Current behavior
Always returns:
`{"status":"failed","error":{"code":5001,"message":"An` internal error has occurred.","name":"Internal Error"}

## Steps to reproduce
1. install something like Script Lab for Outlook.
2. Call setSignatureAsync from Outlook on the Mac. 

## Context
Broke my add-in on Mac, and probably every other Mac add-in that also uses this call.
Broke my ability to test my code for release.

**Comment by gitcnd** [comment] 2021-11-04 12:39
I just tested on Outlook version 16.54 - same problem:

1. My code fails.
2. Both of the Script Lab examples in "Work with client signatures" also fail:-

The setSignature example fails with "permission denied".
The "setSignature with inline image" fails with a different non-explained error (probably caused by the underlying Internal Error)

**Comment by exextoc** [comment] 2021-11-07 15:32
Hey @gitcnd ,

We are unable to reproduce this issue in the Outlook for Mac version that you have mentioned in the new Mac UI. If your add-in is hosted on an endpoint, could you please share a manifest for an add-in where you see this issue? Are you using the old Mac UI?

**Comment by gitcnd** [comment] 2021-11-07 23:22
Did you successfully install Script Lab ?
Which one(s) of the setSignature examples did you test and see working?
IT sounds like you did not test the right thing to me: this is still verified as not working right now, one 2 different Macs, with 2 different accounts, and 2 different Outlook's (the latest version for High Sierra, and also the latest version for Mojave).

![Screen Shot 2021-11-08 at 9 19 24 am](https://user-images.githubusercontent.com/4301826/140665696-1a57117f-7292-4d31-a7da-5003fee0c0f4.png)

Can you send a screenshot ?  What MacOS and Outlook version did you test with ?

**Comment by exextoc** [comment] 2021-11-08 12:08
@gitcnd  We have rolled out a fix for this as a part of the 1.10 API set. This is currently in [Insiders](https://insider.office.com/en-us/join/mac). Can you please check the insider build and let us know if it's working for you?

**Comment by gitcnd** [comment] 2021-11-08 12:19
Do I use Beta or Preview channel for that?
FYI - here's the errors again from Big Sur (new and old UIs):-

<img width="322" alt="Screen Shot 2021-11-08 at 10 12 06 pm" src="https://user-images.githubusercontent.com/4301826/140740830-a764ea4d-f861-4960-ba32-67544c9f5d85.png">

<img width="326" alt="Screen Shot 2021-11-08 at 10 13 20 pm" src="https://user-images.githubusercontent.com/4301826/140740857-16875da4-70d5-4b61-8bd2-6e917f25feca.png">

**Comment by gitcnd** [comment] 2021-11-08 12:43
Thanks - half way there:  That works now in Big Sur Outlook 16.56 from the beta channel in the "New Outlook" mode,
however - is is still broken if the New mode is not turned on:-

<img width="317" alt="Screen Shot 2021-11-08 at 10 40 00 pm" src="https://user-images.githubusercontent.com/4301826/140744021-634b4439-b729-4146-b838-56f497853593.png">

<img width="312" alt="Screen Shot 2021-11-08 at 10 40 24 pm" src="https://user-images.githubusercontent.com/4301826/140744049-994edbee-c50d-4e73-8866-f029db33f55d.png">

(The 2 different script-lab samples each give the different errors above)

I'll see if I can find a way to test this on older macs too.

**Comment by exextoc** [comment] 2021-11-09 07:24
@gitcnd Thanks for verifying it in the Insider build. Mailbox 1.9 and above are only supported in the new UI. And since this fix is a part of the 1.10 API set we have supported this in the new UI.

**Comment by gitcnd** [comment] 2021-11-10 00:58
I don't quite understand - why are you not fixing this bug properly ?

Are you not allowed to go back and fix bugs in 1.9 or earlier ?

How are we supposed to ship products when they "sometimes will not work" because broken things are left in the API ?

**Comment by exextoc** [comment] 2021-11-11 08:00
We support API requirement sets 1.9 and above only on the New Outlook for Mac as captured in the documentation (screenshot below). We are no longer adding new Add-in capabilities to the old UI.




![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/28549921/141260392-62377e1b-c200-4676-ad67-a2f1bd01deff.png)

**Closed as completed** 2021-11-19 11:00 UTC
Labels: Area: Outlook, Needs: author feedback, Status: no recent activity
