### ISSUE TITLE
onActivated Event Handler does not appear to work in Office 365

### ISSUE THREAD

**Issue by misaunde** [OfficeDev/office-js#421] opened 2019-03-12 16:37 UTC
onActivated Event Handler does not appear to work in Office 365.

I recently updated to Office 365 and some of my newer code that took advantage of the onActivated Event listener for sheet changes started throwing an "AccessDenied" error with a message of "You cannot perform the requested operation."
![image](https://user-images.githubusercontent.com/10051350/54217442-3c1dd900-44b1-11e9-9ed6-a568f623711f.png)

However, this works as expected using Excel 2016 (which is what I was using before).

## Expected Behavior

I would expect it to apply the listener and send an event when sheets are changed in Excel

## Current Behavior

It's failing to setup and apply the onActivated event listener. Instead I get an error message.

## Steps to Reproduce, or Live Example

I was able to reproduce this on 2 different machines (Office 365 and Excel 2016) using the code in Script Lab for "Workbook and worksheet collection events":
![image](https://user-images.githubusercontent.com/10051350/54217587-8737ec00-44b1-11e9-805d-3e3300e77142.png)
Using Excel 2016, this snippet works as expected. Using Office 365, I'm getting the error message.

Steps to Reproduce:
- Add a worksheet
- Register onAdded event handler
- Add another worksheet
- Register onActivated event handler to view the error message on Office 365

## Context

I'd like to be able to listen to sheet change events in Excel similiar to the behavior when using Excel 2016.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1808 (Build 10730.20280)
* Operating System: Windows 10
* Browser (if using Office Online): n/a

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by Biktop** [comment] 2019-03-12 17:42
I also confirm that onActivated event stopped to work under Microsoft Excel for Mac (16.19 (181109)). But it still works for Excel Online.

I've tried different versions of office.js and found next:

1. Version: 16.0.11328.10000 (Current CDN version https://appsforoffice.microsoft.com/lib/1/hosted/office.js) doesn't work under Microsoft Excel for Mac but works for Excel Online.

1. Version: 16.0.11215.10000 (https://unpkg.com/@microsoft/office-js@1.1.11-operational.1/dist/office.js) works as expected for both platforms.

**Comment by weshi** [comment] 2019-03-15 05:41
I cannot reproduce this issue. My build is Version 1902 (Build 11328.20146 Click-to-Run).

Could you share the script you used?

**Comment by misaunde** [comment] 2019-03-15 16:02
Hi @weshi,
Just to clarify, you have [Script Lab](https://www.microsoft.com/en-us/garage/profiles/script-lab/), right?

In Script Lab, I went to to Samples -> Events -> "Workbook and worksheet collection events":
![image](https://user-images.githubusercontent.com/10051350/54444092-a8921580-4707-11e9-9dd2-9394faa55253.png)
and clicked on the buttons outlined in my steps above, I get this error every time (in Office 365 Excel Version 1808 (Build 10730.20280)).

As far as I can tell this is happening on all of the computers we've updated to Office 365 in our Office, all of which are stuck on Version 1808 (while it still works as expected on our old Excel 2016 installs).

Perhaps this issue gets fixed by Version 1902?

**Comment by weshi** [comment] 2019-03-17 04:35
@misaunde Yes, I tried the same sample from Script Lab on Excel Mac/Win32/Online, and didn't reproduce this issue. Could you give it a try on Excel Online?

**Comment by misaunde** [comment] 2019-03-18 16:11
Sorry, I don't have Excel Online :(

But according to @Biktop, it still works for Excel Online, so that wouldn't surprise me. It also worked for me using Excel 2016 Desktop 64-bit on Windows 10. 

I'm only seeing it not work on Excel 365 desktop 64-bit Windows 10, and I'm seeing this on more than one computer, but again, this is on Version 1808.

**Comment by jcjolley** [comment] 2019-06-19 16:36
FWIW, I am seeing this on Excel 365 1808 as well.

**Comment by dmahugh** [comment] 2019-06-19 17:05
Thanks for confirming, @jcjolley 

@lumine2008, could you take a look at this one? Thanks!

**Comment by taralex77** [comment] 2019-06-25 13:53
We were having the same issue so we used an older version of office.js in our add-in. 
Guess what, today we can't find our add-in in the Office Store and we received an email that it was unpublished because we use a non-CDN version of office.js!
So it's like use the buggy version or nothing at all. And hey, we're not going to even acknowledge that there is a bug.

**Comment by kbrandl** [comment] 2019-06-25 16:49
Assigning to @lumine2008 (per @dmahugh's previous comment).

**Comment by lumine2008** [comment] 2021-03-17 05:51
Hi @misaunde , do you still repro this issue?

**Comment by lumine2008** [comment] 2021-03-20 13:25
I'm going to close this issue for now, please reactivate if you're still seeing this.

**Closed as completed by lumine2008** 2021-03-20 13:25 UTC
Labels: Area: Excel, Resolution: cannot repro
