### ISSUE TITLE
Excel Insert Function button not showing function and arguments description for custom functions when looking at an existing formula

### ISSUE THREAD

**Issue by gmichaud** [OfficeDev/office-js#3409] opened 2023-06-07 21:27 UTC
# Excel Insert Function button not showing function and arguments description for custom functions when looking at an existing formula

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2306 (Build 16529.2000)
* Operating System: Windows 11

## Expected behavior
When clicking on a cell with an existing formula, Insert Function button should show us the function information the same way as when we were inserting the function originally. This works fine on standard Excel functions as well as XLL-based custom functions.

## Current behavior
Insert function window shows "Undefined", no argument name or documentation

To replicate, simply use the insert function window on a blank cell, select a custom Excel function, click OK, and then click Insert Function button again on same cell

On a new cell:
<img width="603" alt="Function on a new cell" src="https://github.com/OfficeDev/office-js/assets/9433888/84730f18-3966-4dc5-8d76-a7d8e897391a">

When reopening Insert function on a cell using same function:
<img width="509" alt="Function on existing cell" src="https://github.com/OfficeDev/office-js/assets/9433888/97b3d3a1-fb01-42a9-a71b-68b3d8dcf5e2">

**Comment by wh1t3cAt1k** [comment] 2023-06-29 13:07
@JinghuiMS did you have a chance to take a look at this?

**Comment by JinghuiMS** [comment] 2023-06-30 03:40
Thanks for reaching us. Sorry for late response.
We currently don't support it after I confirm with area expert. For new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

**Comment by gmichaud** [comment] 2023-06-30 13:15
@JinghuiMS it works fine in a blank cell but not in an existing cell -- this looks like a bug, I don't understand why it should be considered a feature request...

**Comment by wh1t3cAt1k** [comment] 2023-07-03 18:37
@JinghuiMS this is certainly a bug since it **does** work in one scenario but doesn't work in another scenario, see @gmichaud 's original post. It works fine when you do it on a blank cell.

Furthermore, in the scenario where it doesn't work, it doesn't work in such an ugly way that no one can consider this acceptable UX in good conscience, and it reflects badly on our product, too because people think it's an error on our side...

@Wenjun-Gong calling this item to your attention too...

**Comment by JinghuiMS** [comment] 2023-07-04 02:26
Involve area expert @rundongmsft into this thread.

**Comment by wh1t3cAt1k** [comment] 2023-07-12 16:54
@rundongmsft @JinghuiMS @Wenjun-Gong would you be able to provide an update on this ticket for us?

It truly bothers us and the users because the dialog UX looks half-finished.

We firmly believe custom functions should be a first-class experience with Excel.

**Comment by JEGUOCEAN** [comment] 2023-09-28 12:02
Hi,

We are Facing the same kind if issue with our JavaScript Add-in having custom functions:

Launch Excel from scratch add a custom formula in a cell: sap.getdata(“Table1”) => all is working as expected: function argument wizard can be used and all arguments are handled correctly

Press ctrl+N to create a new workbook and do the same => function argument wizard is having issues. All arguments are accepted if you set number values even if they are of type string. If you set string value for an argument you get #Value error for it. Everything is still ok on first workbook.

Close first workbook => no more issue on second workbook.

At any time, inserting a new formula using the formula wizard is working correctly.

If you have xlb files in xlstart error is always present as there is at least 2 opened workbook.

This is not acceptable for our end users.

**Comment by MiaofeiWang** [comment] 2023-10-08 09:17
Hi @JEGUOCEAN , unfortunately we are not able to reproduce this issue with ScriptLab or my add-in on Excel Win32. To confirm if this is related to specific add-in or specific function, would you please help check if you can repro it with the custom function samples of ScriptLab? If yes, a more detailed repro steps and the Excel build version would be much appreciated.

**Comment by MiaofeiWang** [comment] 2023-10-09 09:12
@JEGUOCEAN , Seems the issue in your case is different with the issue in the initial post. The issue in initial post is that the definitions of both function and arguments are lost and shown as "undefined". While yours is string arguments showing error as "#VALUE". 

Could you please confirm if yours is same with https://github.com/OfficeDev/office-js/issues/2977? If yes, we are able to repro this and it is a known issue and being tracked internally.

**Comment by gmichaud** [comment] 2024-02-29 00:45
Is there any update on this? There’s another issue in GitHub also related to Insert Function with custom functions #3916 that is still open. We truly wished custom functions were on par with native functions when it comes with user-experience; we don’t have such issues with our XLL-based functions and this is a blocker for us…

**Comment by gmichaud** [comment] 2024-03-20 19:46
I would also like to note that this issue also affects Excel for Mac, but in a slightly different way. On Mac, you see the Insert Function panel as if your cell was completely blank: https://www.loom.com/share/c5fde8a5541a4ab8bd7d6063fda64222

On Windows, the issue described originally still applies: https://www.loom.com/share/edeb2f5df741478bb21cbdc2b688b1e5

**Comment by Wenjun-Gong** [comment] 2024-03-21 16:50
Thanks for your additional videos @gmichaud and sharing the problem on Mac. 
We haven't fixed this issue yet. But we do have people are looking at the root reason. We will let you know once we have any update.

**Comment by penglongzhaochina** [comment] 2024-03-21 16:52
[like]  Penglong Zhao reacted to your message:
________________________________

**Comment by wh1t3cAt1k** [comment] 2024-08-02 05:55
Dear MSFT,

You mentioned on another occasion that the fix was checked in for the July fork, and out of curiosity, I decided to test things out on the **beta channel**: Microsoft® Excel® for Microsoft 365 MSO (Version 2408 Build 16.0.17925.20000) 64-bit 

Looks like the issue is **gone**!

<img width="766" alt="image" src="https://github.com/user-attachments/assets/f93a5d52-ddea-4ad0-a5ed-79c9ec04d9da">

==

Could you confirm the build version please?

[Velixo internal tracking item](https://3.basecamp.com/3496385/buckets/16689259/card_tables/cards/6462476984)

**Comment by XuanZhouMSFT** [comment] 2024-08-02 07:33
@wh1t3cAt1k You are right, the fix for this issue is already reached to BETA channel. For production channel, it should be version after 16.0.17928.XXXXX and it will reach around the end of this month or the start of next month.

**Comment by wh1t3cAt1k** [comment] 2024-08-02 07:43
@XuanZhouMSFT thank you for the confirmation!

One thing I noticed is that the "Formula result" at the bottom is always empty and does not display anything.

Would this be addressed separately?

**Comment by wh1t3cAt1k** [comment] 2024-08-02 11:13
Verified by Velixo, we can close this item!

For "Formula result" being empty, a separate item will be created since the root cause is different.

**Closed as completed** 2024-08-05 01:59 UTC
Labels: Needs: attention :wave:, Area: Excel
