### ISSUE TITLE
Add in is not loading in excel online

### ISSUE THREAD

**Issue by BIPLAB82** [OfficeDev/office-js#4849] opened 2024-09-02 22:13 UTC
When the excel loads we are getting the error in the browser console as shown below,

Can't find Office Add-in from Microsoft AppSource given addin ID: WA200002270 (content market: en-US). Exception details: {}

Platform [PC desktop, Mac, iOS, Office on the web]: web
Host [Excel, Word, PowerPoint, etc.]: Excel
Expected behavior
Addin should auto load when the excel online loads.

Current behavior
Addin is not auto loading. Getting the below error message.
Can't find Office Add-in from Microsoft AppSource given addin ID: WA200002270 (content market: en-US). Exception details: {}

Provide additional details
Session ID: 90596c32-e4ec-4757-bf09-4649da5eb602
Build: 16.0.16717.42308

Context
The addin is used for student assignments. This is a P1 issue for us.
<img width="1664" alt="image" src="https://github.com/user-attachments/assets/7d4740c1-df95-4399-98d4-7048f6622517">

This is similar to https://github.com/OfficeDev/office-js/issues/3532

**Comment by BIPLAB82** [comment] 2024-09-02 22:15
Thanks for looking into it we are looking for a resolution.

**Comment by SiruiSun-MSFT** [comment] 2024-09-03 09:14
Hi @BIPLAB82, Thanks for your waiting here! We are actively working on the investigation and have already consulted the owner team. However, our current analysis can only start from the log level, which is mixed with many other issues and normal loading cases, so it will take some time. To help us quickly find the root cause, we would like to confirm the impacted users scale of your Add-in? Are all users of your Add-in affected? Any other information to add?
Thanks in advance for your patience!

**Comment by vinay-sattur** [comment] 2024-09-03 10:10
Hi @SiruiSun-MSFT , the impact is widespread impacting multiple browsers and students are unable to complete their assignments. Here is one of the impacted user session id "231f3810-9c34-4c59-b5d0-48bc1e6dd91f".

**Comment by JessieChenMS** [comment] 2024-09-04 07:01
Hi @vinay-sattur, so sorry for the issue here. We are actively checking the error logs and identifying the issue. To help on the trouble shooting, if there is any test environment you can share with us to repro the issue that will be much helpful.

**Comment by shanshanzheng-dev** [comment] 2024-10-17 08:21
Hi, This issue has been fix, so I'll close it. Please contact us when you need some helps. We value your feedback. Thanks.

**Closed as completed by shanshanzheng-dev** 2024-10-17 08:21 UTC
Labels: Needs: attention :wave:, Area: Excel
