### ISSUE TITLE
getItemsSelectedAsync is not working properly in web browser .

### ISSUE THREAD

**Issue by codenovous-harsh** [OfficeDev/office-js#4480] opened 2024-05-21 06:12 UTC
Steps To Reproduce :

Select Multiple Items in uninterrupted order in outlook web version and try to open add in
Some times the getItemsSelectedAsync will give result as failed.

But in Desktop Version the function is working fine even if we select multiple items in uninterrupted order or consecutive order

can you please look into this issue ?

Also is there any function so that we can get full email details and its attachments when we select multiple items similar to Office.context.mailbox.item ?
![Screenshot 2024-05-21 113900](https://github.com/OfficeDev/office-js/assets/72404148/16d1323d-d114-465c-8c3f-a9251dd81027)

**Comment by rajjha-msft** [comment] 2024-05-22 04:03
Duplicate of this issue : #4481 
Please follow this issue for more updates.

**Closed as completed by rajjha-msft** 2024-05-22 04:03 UTC
Labels: Area: Outlook, Resolution: duplicate
