### ISSUE TITLE
Setting the fill of one ChartSeries item sets the fill of all the ChartSeries items

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/office-js#570] opened 2019-06-24 14:49 UTC
## Expected Behavior
Setting the color of one item in a ChartSeries sets color of only that single item.

## Current Behavior
Setting the color of one item in a ChartSeries sets the color of every item.

## Steps to Reproduce, or Live Example
https://gist.github.com/AlexJerabek/88584a1296c9bc0e33a9406cc32522ab

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1906
* Operating System: Windows 10
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lumine2008** [comment] 2019-06-25 02:34
Thanks @AlexJerabek, for reporting this issue. 
I just tried your gist in my side. looks like the the code run as expected. it changed 1st pie color. 
i am using Build 1906(11727.20210). what's your build version?

**Comment by Zlatkovsky** [comment] 2019-06-25 16:34
@lumine2008 , I am able to repro Alex's issue as well.

My build info:
![image](https://user-images.githubusercontent.com/2230453/60116157-5ca23400-972c-11e9-8eda-34ccd354493a.png)

Repro screenshot:
![image](https://user-images.githubusercontent.com/2230453/60116101-409e9280-972c-11e9-99ab-f93bb3ffc638.png)

**Comment by lumine2008** [comment] 2019-06-27 02:38
Communicated with Chart API team, we learn this is a known issue and a bug 3437961 track the issue. The root cause is due to a regression in chart uniform object model internal. And chart team already sent out a code review and we could expect it be fixed soon. Thanks.

**Comment by kbrandl** [comment] 2019-08-29 19:07
@lumine2008 if this issue has been fixed, can you please comment here to indicate such, and close this issue? Thanks!

**Comment by lumine2008** [comment] 2021-03-17 06:44
This issue was fixed, please verify, thanks

**Closed as completed by lumine2008** 2021-03-17 06:44 UTC
Labels: Area: Excel, Type: product bug, Status: under investigation
