### ISSUE TITLE
displayDialogAsync() on IE11 Word Online returns error 12004 'The domain of the URL is not included in the AppDomains element in the manifest'

### ISSUE THREAD

**Issue by JamesBigChange** [OfficeDev/office-js#1578] opened 2021-01-07 16:16 UTC
## Expected Behavior
displayDialogAsync() with the setting displayInIframe: true, on IE11 Word Online should successfully open a dialog window just like it does on all other browsers including Chrome and Edge.

## Current Behavior
On IE11, displayDialogAsync() returns a failed status with the error message:
"The domain of the URL is not included in the AppDomains element in the manifest, and is not subdomain of source location"

This happens after the domain of the URL passed to displayDialogAsync() is added as an AppDomain element in the manifest file. 

Additional notes:
1. Our add-in and the website, to be opened in a dialog, are hosted on different domains
2. The identical code and AppDomains manifest element is working successfully for an Outlook Add-in when running in IE11

## Context
This is blocking our Office Store Add-in submission.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Office 365
* Operating System: Windows
* Browser (if using Office on the web): IE11

**Comment by KelBowen** [comment] 2021-01-08 18:16
@qinliuMSFT - I can't seem to find you in the list of assignees.

**Comment by qinliuMSFT** [comment] 2021-01-11 08:29
The issue related to Dialog API, @lliu113 will help take a look.

**Comment by lliu113** [comment] 2021-01-13 16:53
@JamesBigChange - thanks for reporting this! Are you able to provide the manifest for your add-in? We have restrictions around the domain that can be opened in the dialog, and it's possible it's throwing an error from a false positive. The manifest will help us repro the issue. 

Thanks!
Lillian

**Comment by JamesBigChange** [comment] 2021-01-13 17:15
Hi Lillian

Thanks for looking into this issue - our manifest file is attached.



​All the best,
​
James Brown
Products Integration Developer
3150 Century Way
Thorpe Park
LS15 8ZB
T
E
W
+44113 457 1000
james.brown@bigchange.com
www.bigchange.com
Legal Disclaimer: BigChange Limited is a provider of mobile workforce management technology.  If the recipient of this email is not the addressee, such recipient is strictly prohibited from reading, copying, distribution or otherwise using this email or its contents in any way. Unless we agree otherwise in writing anything we buy or sell will be governed by our BigChange terms and conditions for the purchase of goods and services, or Customer Terms of Trade.  Our website includes our Privacy Policy which describes how we will process your data

**Comment by JamesBigChange** [comment] 2021-01-14 10:20
> @JamesBigChange - thanks for reporting this! Are you able to provide the manifest for your add-in? We have restrictions around the domain that can be opened in the dialog, and it's possible it's throwing an error from a false positive. The manifest will help us repro the issue.
> 
> Thanks!
> Lillian

Thanks @lliu113, I have emailed you our manifest. Please confirm that it was received.

**Comment by lliu113** [comment] 2021-01-14 17:44
@JamesBigChange - manifest was received, thank you! What's the domain of the dialog you're trying to launch? And this is occurring just in IE11, correct? All the other browsers are working correctly?

**Comment by JamesBigChange** [comment] 2021-01-14 17:52
@lliu113 thank you. The domain for the dialog is: https://clients.bigchange.com
Yes that's correct - it works in all browsers except IE11.

**Comment by lliu113** [comment] 2021-01-14 17:56
@JamesBigChange - Unfortunately I can't seem to get your add-in to side-load (it's giving me a blank page in the taskpane), and I'm unable to repro this with another add-in. The dialog is launching correctly in IE11 for me, when the domain is one specified under AppDomain. 

Let me circle this internally and see if this is a known bug. Will revert back soon - thanks!

**Comment by lliu113** [comment] 2021-01-14 23:44
@JamesBigChange - quick update, we were able to repro this issue successfully. The manifest was a huge help, thank you for providing that! We are currently investigating the root cause, which may take some time. Will update when we know more, thanks!

**Comment by lliu113** [comment] 2021-01-28 22:18
@JamesBigChange - the fix is checked in, and starting to roll out

**Comment by JamesBigChange** [comment] 2021-01-29 13:55
@lliu113 thank you. Do you have an estimate for the rollout time?

**Comment by lliu113** [comment] 2021-01-30 00:42
@JamesBigChange - unfortunately no estimate as of yet, but will update next week on status. Thanks for your patience!

**Comment by lliu113** [comment] 2021-02-04 23:02
@JamesBigChange - good news, this is now in production! Please test and let us know whether this is working for you.

**Comment by JamesBigChange** [comment] 2021-02-15 09:34
@lliu113 I am unable to load Word Online in IE11 to check this. The following page is displayed:
https://support.microsoft.com/en-us/office/we-recommend-viewing-this-website-in-microsoft-edge-160fa918-d581-4932-9e4e-1075c4713595?ui=en-us&rs=en-us&ad=us

The issue with displayDialogAsync() was flagged during a Microsoft review of our add-in prior to it being updated in MS AppSource. Please can you confirm with your colleagues whether or not add-ins are still tested against IE11 internally?

**Comment by lliu113** [comment] 2021-05-19 20:41
@JamesBigChange - add-ins are still being test against IE11. Are you able to provide a video of the error you're seeing? Doesn't look like I'm able to repro

**Closed as completed** 2021-07-07 23:00 UTC
Labels: Type: product bug, Needs: author feedback, Area: add-in UI, Status: fix pending, Status: no recent activity
