### ISSUE TITLE
Desktop Outlook taskpane doesn't stay pinned after some time 

### ISSUE THREAD

**Issue by Aidam1** [OfficeDev/office-js#4777] opened 2024-08-12 07:25 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Classic Outlook
* Operating System: Windows 10 Pro
 
## Expected behavior

I expect the taskpane to stay pinned until user unpins it.

## Current behavior
The taskpane is pinned for some time, but then it gets unpinned. I don't know the exact reason why, maybe when the session expires?
This has been reported by mutliple of our customers and is blocking them from seamlessly using our addin.

## Steps to reproduce

1. Pin taskpane
2. Wait few hours/days
3. Taskpane is unpinned

**Comment by sivachandran-msft** [comment] 2024-08-12 10:05
Hi @Aidam1, we would need the following details to get some more clarity on this observation:

1. Is this issue being observed in Classic Outlook or New Outlook
2. Could you please share the Addin name or manifest file of the Addin to check the behavior
3. Are there any specific operations after which this behavior is observed?
     - Like after closing the outlook and opening it for the second time?
     - Like when moving between different surfaces like between mail & calendar
     - Like after restarting the PC?

**Comment by Aidam1** [comment] 2024-08-12 11:27
> 1. Is this issue being observed in Classic Outlook or New Outlook

This is in Classic Outlook

> 2. Could you please share the Addin name or manifest file of the Addin to check the behavior

Addin is called eWay-CRM Online, but I don't think it has anything to do with the manifest

> 3. Are there any specific operations after which this behavior is observed?

I haven't noticed any particular scenario when I can simulate this behavior yet. But closing and opening of Outlook doesn't trigger this bug. It seems to me that it happens after a longer time of running Outlook, maybe even after waking the PC from sleep mode.

**Comment by zhngx1** [comment] 2024-09-09 20:38
@Aidam1, do you have more customers reporting this issue? If yes, do you know what build number they have for their classic Outlook?

**Comment by Aidam1** [comment] 2024-09-16 13:53
I'm still waiting for a customer response, so please keep the issue open for now.

**Comment by Aidam1** [comment] 2024-09-19 11:51
Desktop Classic build number with this issue is:
Microsoft® Outlook® for Microsoft 365 MSO (Version 2408 Build 16.0.17928.20114) 64-bit

The same issue also occurs for other customers in Outlook Online. It seems that it happens regularly every few days, and they notice it in the morning, when they open Outlook.

This is a high priority issue for us, because users work with our addin every day, and when the addin disappears so often, they gradually stop using it.

**Comment by Aidam1** [comment] 2024-10-14 08:28
Hello, any update about this issue? Some customers have already stopped using the addin because of this.

**Comment by zhngx1** [comment] 2024-10-23 00:04
Hi @Aidam1, I have tried various ways to repro it, but I do not have a repro for the issue. Can you help provide a solid repro for the issue, it will help us to root the cause for the issue?

**Comment by Aidam1** [comment] 2024-10-29 10:47
Hello, I will try to reproduce it and will let you know

**Comment by Oleg-O** [comment] 2024-12-02 17:58
Please re-activate if you're able to reproduce.

**Closed as completed by Oleg-O** 2024-12-02 17:58 UTC
Labels: Area: Outlook, Resolution: cannot repro

**Comment by Aidam1** [comment] 2025-04-08 07:01
Hello, another client has came to us with same issue. He pins the addin, then closes the laptop and when he opens it again, the addin is not pinned anymore.

Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
Host [Excel, Word, PowerPoint, etc.]: Classic Outlook
Office version number: Microsoft® Outlook® pro Microsoft 365 MSO (Version 2501 Build 16.0.18429.20132) 64 bit
Operating System: Windows 11

@Oleg-O Can you reactivate the issue? I don't have permissions to do so.
