### ISSUE TITLE
When I load the document using Office.js, a general exception is thrown. However, it works properly when I reopen Word.

### ISSUE THREAD

**Issue by RajChauhan-Dev** [OfficeDev/office-js#4509] opened 2024-05-28 08:54 UTC
* My Environment
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20152) 64-bit 
Operating System: Microsoft Windows 11 pro
 
Hello Team,
When I load the document using Office.js, a general exception is thrown. However, it works properly when I reopen Word.

Here is my code snippet:
```
var bcontent = base64ToArrayBuffer(response); // Here response is my base64 string
var blob = new Blob([bcontent], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
var file = new File([blob], 'test', { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });

var fr = new FileReader();
fr.onload = LoadWordDocument;
fr.readAsDataURL(file);

async function LoadWordDocument() {
    if ((this && this.result)) {
        var startIndex = -1;
        var mybase64 = "";
        var data = this.result;
        startIndex = data.indexOf("base64,");
        mybase64 = data.substr(startIndex + 7, data.length);

        await ClearWordDocument();
        await Word.run(async function (context) {
            context.document.insertFileFromBase64(mybase64, "Replace", {
                importTheme: true,
                importStyles: true,
                importParagraphSpacing: true,
                importPageColor: true,
                importChangeTrackingMode: true
            });
            await context.sync();
        }).catch(function (error) {
            console.log('Error: ' + JSON.stringify(error));
            if (error instanceof OfficeExtension.Error) {
                console.log('Debug info: ' + JSON.stringify(error.debugInfo));
            }
        });
    }
}

async function ClearWordDocument() {
    try {
        await Word.run(async (context) => {
            // Clear the body content
            context.document.body.clear();

            // Clear all headers
            const sections = context.document.sections.load('items');
            await context.sync();

            sections.items.forEach(section => {
                section.getHeader("primary").clear();
                section.getHeader("firstPage").clear();
                section.getHeader("evenPages").clear();
            });

            // Clear all footers
            sections.items.forEach(section => {
                section.getFooter("primary").clear();
                section.getFooter("firstPage").clear();
                section.getFooter("evenPages").clear();
            });

            await context.sync();
            console.log('Document content, headers, and footers cleared successfully');
        });
    } catch (error) {
        console.error('Error clearing document content:', error);
        console.log('Error clearing document content: ' + JSON.stringify(error));
    }
}
```

Here is a video showing the issue: when I try to preview the document, it throws a general exception. However, if I reopen Word and load the same document, it opens without any exceptions.

https://github.com/OfficeDev/office-js/assets/171012090/9167cdb9-87c2-42ee-8e37-3d1e13871a7a

**Comment by shanshanzheng-dev** [comment] 2024-05-28 09:33
Hi @Raj-Dev1 Thanks for reporting this issue. Could you please provide us more detail information? such as the whole snippet and your response, because when I import this snippet and there are some errors?

**Comment by RajChauhan-Dev** [comment] 2024-05-28 10:17
@shanshanzheng-dev I'm giving you one of my document's Base64 string in attachment.

```
function GetMainDocBytesForPreview(){
  var bcontent = base64ToArrayBuffer(response); // Here response is my base64 string which you can see in attachment.
  var blob = new Blob([bcontent], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
  var file = new File([blob], 'test', { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
  
  var fr = new FileReader();
  fr.onload = LoadWordDocument;
  fr.readAsDataURL(file);
}
```
Here are screenshots:
![image](https://github.com/OfficeDev/office-js/assets/171012090/aaaa7f1e-8c90-4329-bbf9-c30db510a969)
![image](https://github.com/OfficeDev/office-js/assets/171012090/6dceb67e-3866-4d09-9002-a988e474162f)
![image](https://github.com/OfficeDev/office-js/assets/171012090/3077abb6-1673-4a1a-b45c-68cac7f7c7e6)
![image](https://github.com/OfficeDev/office-js/assets/171012090/b79f7681-0f33-4922-9e88-c452231083f0)
![image](https://github.com/OfficeDev/office-js/assets/171012090/0a37f375-911d-4e0f-823f-8a4de3011410)

Here is Base64 string file:
[Base64 string.txt](https://github.com/OfficeDev/office-js/files/15467691/Base64.string.txt)

**Comment by jipyua** [comment] 2024-05-29 02:47
Thanks @Raj-Dev1 for providing the base64 string of your document. We tried directly the following code in the ScriptLab addin with your provided base64 and it's working fine to import it to current document. Can you try whether it's the same behavior for you in ScriptLab? thanks.

    context.document.insertFileFromBase64(base64, "Replace", {
      importTheme: true,
      importStyles: true,
      importParagraphSpacing: true,
      importPageColor: true,
      importChangeTrackingMode: true
    });
    await context.sync();

**Comment by RajChauhan-Dev** [comment] 2024-05-29 09:25
Thanks @jipyua & @shanshanzheng-dev for quick responses. 
Randomly, after loading different documents, I encounter a general exception issue. I have a video showing that some documents open, but after a while, a general exception occurs. However, when I reopen the Word document, it loads normally.

Here is the video:
https://irisindiacloud-my.sharepoint.com/:v:/g/personal/raj_chauhan_irisbusiness_com/Eay8neSVJ6VLhXfRce4Z2bkBfvaSl61N9mtNBdo-1nlQ-w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=llaehD

**Comment by jipyua** [comment] 2024-05-29 10:50
@Raj-Dev1 thanks for the confirm, this sounds like a random issue. It's better to provide us a stable repro steps or document that can reproduce this case. Feel free to let us know if you have some new findings. thanks.

**Comment by RajChauhan-Dev** [comment] 2024-05-30 08:01
Hello @jipyua,
We encountered the same issue on different PCs and various Word versions using the provided code. Can we schedule a call to discuss this?

**Comment by jipyua** [comment] 2024-05-31 01:58
hi @Raj-Dev1, that looks great. Please fill out this form with additional information that can help us investigate this issue:
https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR9NvrlmrippKsMvh4kTM325URVZMWjYyQTVOTVNLTUo5VzFRTTcyNU1RSy4u
you may also leave your contact information as a means for us to further discuss.

**Comment by RajChauhan-Dev** [comment] 2024-05-31 04:49
Hi @jipyua, Thanks for sharing this form. I provided email addresses as contact information.

**Comment by jipyua** [comment] 2024-07-11 02:21
hi @Raj-Dev1 sorry for the late response, it took us quite some time to figure out what's wrong with the doucments you provided. Basically the document 4 you provided is corrupted with styles exceeds the limitation (as you may notice, the styles actually can’t be deleted at all from UI). You can see the limitation numbers here: https://learn.microsoft.com/en-us/office/troubleshoot/word/operating-parameter-limitation  

(Style Definition) maximum number of styles	4,079
Maximum number of lists	2,047

We suggest you inspect how this document is generated and make sure this kind of document doesn't be generated again. Thanks.

**Comment by RajChauhan-Dev** [comment] 2024-07-19 05:39
@jipyua Sorry for the delayed response, We will share the others documents in which we are facing same problem.

**Comment by jipyua** [comment] 2024-07-23 03:29
@Raj-Dev1 as we discussed, the other documents are with the same isse that styles exceeds the limitation. Feel free to close this post as root causes and solutions have been discussed thoroughly.

**Comment by RajChauhan-Dev** [comment] 2024-07-29 05:48
Thanks @jipyua @shanshanzheng-dev for quick support.
Can you let us know if this style issue is resolved in the future or if there are any updates related to style issues?

**Comment by jipyua** [comment] 2024-07-30 12:38
hi @Raj-Dev1, As mentioned earlier, If style count passes the limit https://learn.microsoft.com/en-us/office/troubleshoot/word/operating-parameter-limitation, Word simply does not gracefully handle the scenario - you end up in a world of undefined behavior. The user should avoid this. We will let you know if Word side improves the experience. Thanks.

**Comment by RajChauhan-Dev** [comment] 2024-07-30 13:24
Hello @jipyua Thanks for letting us know. I have a query about removing styles. When we use the code below to remove styles, Word gets stuck after context.sync().

```
const styles = context.document.getStyles();
    styles.load();
    await context.sync();
    styles.items.forEach((style) => {
      if (!style.builtIn) {
        style.delete();
      }
    });
```

**Comment by jipyua** [comment] 2024-07-31 02:03
hi @Raj-Dev1 I see there is a similar case #4732, let's talk this separate issue in that thread. Thanks.

**Closed as completed** 2024-08-02 02:03 UTC
Labels: Needs: author feedback, Area: Word
