### ISSUE TITLE
Windows Outlook native app is not announcing anchor href links as links while using NVDA screen reader

### ISSUE THREAD

**Issue by pavig30** [OfficeDev/office-js#2728] opened 2022-07-26 18:44 UTC
# Provide required information needed to triage your issue
Windows Outlook native app is not announcing anchor href links as links while using NVDA screen reader
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows Laptop
* Host [Excel, Word, PowerPoint, etc.]: Microsoft Outlook Native app
* Office version number: Version 2206 (Build 15330.20266 Click-to-Run)
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome Browser
 
## Expected behavior

NVDA screen reader should read anchor href links as links, but it is announcing it as normal text. We could see the web version is working fine but the issue exists in Windows Outlook native app.
link Link A
link Link B
link Link C
## Steps to reproduce

1. Create a simple plain barebones table structure like below.   
2. Save it to a file with .html extension. Send email to Windows Outlook App. Open the NVDA screen reader and tab to the email body. NVDA screen reader reads the first link in the email body as a link and remaining as text. If you navigate back to the link which was read as a link earlier, it will be read as a text the second time.
 
## Link to live example(s)

NA
# Provide additional details

NA
## Context

This issue is a WCAG Accessibility issue. 

## Useful logs

- [ ] Console errors
- [ ] Screenshots - Pasted above
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on week

**Comment by exextoc** [comment] 2022-08-08 20:23
@pavig30 based on your description, it is unclear whether this is an OfficeJs issue or not. Are you using an Office web add-in to insert the table to reproduce this bug, however, this doesn't reproduce without using the add-in?

**Comment by pavig30** [comment] 2022-08-08 22:43
> @pavig30 based on your description, it is unclear whether this is an OfficeJs issue or not. Are you using an Office web add-in to insert the table to reproduce this bug, however, this doesn't reproduce without using the add-in?

I observed this issue in Microsoft Outlook app in Windows. This issue is not in OfficeJS. No I am not using Office web.

**Comment by exextoc** [comment] 2022-08-09 19:35
@pavig30 Thanks for confirming. This repo is for [Office Add-Ins](https://docs.microsoft.com/en-us/office/dev/add-ins/) hence closing this post since it is not applicable here.

**Closed as completed by exextoc** 2022-08-09 19:35 UTC
Labels: Needs: attention :wave:, Area: Outlook

**Comment by pavig30** [comment] 2022-08-09 21:45
> @pavig30 Thanks for confirming. This repo is for [Office Add-Ins](https://docs.microsoft.com/en-us/office/dev/add-ins/) hence closing this post since it is not applicable here.

Could you please share me the link for raising issue with Microsoft outlook app?
