### ISSUE TITLE
`RequestAborted: The request has been aborted.` when trying to save a new workbook in Excel Desktop on macOS Sonoma

### ISSUE THREAD

**Issue by damacisaac** [OfficeDev/office-js#3875] opened 2023-11-29 15:10 UTC
# Provide required information needed to triage your issue
`Excel.Workbook.save()` function fails when trying to save a newly created workbook in Excel Desktop on macOS Sonoma. The issue does not occur on older versions of macOS and only occurs on Excel Desktop. Once the workbook has been saved manually by the user, future calls to `Excel.Workbook.save()` succeed, so it's likely something about creating a new file on the local file system.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.79.2 (23112723)
* Operating System: macOS Sonoma 14.1.1
* Browser (if using Office on the web): ______
 
## Expected behavior

The workbook saves successfully on to the local file system.

## Current behavior

The call to `workbook.save()` fails with error message `RequestAborted: The request has been aborted.`

## Steps to reproduce

1. Create a new workbook, don't save it anywhere
2. Execute the following:
```
Excel.run(context => {
  context.workbook.save();
})
```
3. It will fail with the error message `RequestAborted: The request has been aborted.`

## Context

Our Excel Addin needs to create new worksheets and save them. Cannot do this without being able to save the workbook.

## Script lab example
<img width="1728" alt="Screenshot 2023-11-29 at 11 09 36" src="https://github.com/OfficeDev/office-js/assets/3689921/9f8e1563-9925-40f3-94db-bd71d50790aa">
<img width="1725" alt="Screenshot 2023-11-29 at 11 09 29" src="https://github.com/OfficeDev/office-js/assets/3689921/3ccb50f8-eff3-4660-a558-f1b0e52c42e0">

## Useful logs

<img width="1728" alt="Screenshot 2023-11-29 at 10 49 33" src="https://github.com/OfficeDev/office-js/assets/3689921/779a3f4c-811f-47b9-97f1-4fa781373855">
<img width="1724" alt="Screenshot 2023-11-29 at 10 49 24" src="https://github.com/OfficeDev/office-js/assets/3689921/dc67ab2a-4412-4d85-9eef-7fa46254a9c9">
<img width="1724" alt="Screenshot 2023-11-29 at 10 47 23" src="https://github.com/OfficeDev/office-js/assets/3689921/cb58d2d8-fd52-49a6-8554-166580159e2f">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by manuelsidler** [comment] 2023-12-07 15:37
I can reproduce the issue on my machine:

- Platform [PC desktop, Mac, iOS, Office on the web]: Mac
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: 16.79.2 (23112723)
- Operating System: macOS Sonoma 14.1.2
- Browser (if using Office on the web): ______

**Comment by donlvMSFT** [comment] 2023-12-11 09:28
Hi, thanks for reporting this issue, created internal task 8589782 to track this thread. 

Will update once got any progress, thanks.

**Comment by XuanZhouMSFT** [comment] 2023-12-19 07:02
Hi, thanks for your kindly waiting.
The bug will be fixed in next version 16.81. Please retry it later and let us know if it still exists in your place.
Thanks again.

**Comment by damacisaac** [comment] 2023-12-19 17:02
Thank you for the fix!

**Comment by manuelsidler** [comment] 2023-12-20 08:01
> Hi, thanks for your kindly waiting. The bug will be fixed in next version 16.81. Please retry it later and let us know if it still exists in your place. Thanks again.

I'll let you know as soon as I get the 16.81 update. Thanks!

**Comment by manuelsidler** [comment] 2024-01-17 05:58
@XuanZhouMSFT I got the 16.81 update today. Unfortunately, I still run into the "Request aborted" error when trying to save a new Excel workbook:
```typescript
try {
    context.workbook.save(Excel.SaveBehavior.save)
    await context.sync() // throws error
} catch (error) {
    console.log('error workbook save', error)
}
```

_RequestAborted: The request has been aborted.
n — excel-mac-16.00.js:25:276747
(anonymous function) — excel-mac-16.00.js:25:341207
(anonymous function) — excel-mac-16.00.js:25:339289_

**Comment by manuelsidler** [comment] 2024-01-18 15:12
@XuanZhouMSFT My colleague and I tested the bug again today. Now it seems to work with 16.81. I have no idea why it didn't yesterday.

**Comment by manuelsidler** [comment] 2024-01-24 09:34
@XuanZhouMSFT Today the bug appeared again in Mac Excel 16.81. I can also reproduce it with ScriptLab:
1. Open a new Excel file
2. Open ScriptLab Add-In
3. Run the code (see comment above)
4. Officejs doesn't save the Excel workbook. Console log:
```
{name: "RichApi.Error", code: "RequestAborted", traceMessages: Array[0], innerError: null, debugInfo: Object…}
name: "RichApi.Error"
code: "RequestAborted"
traceMessages: Array[0]
innerError: null
debugInfo: Object
code: "RequestAborted"
message: "The request has been aborted."
toString: function toString()
errorLocation: "Workbook.save"
statement: "workbook.save(...);"
surroundingStatements: Array[4]
0: "var workbook = context.workbook;"
1: "// >>>>>"
2: "workbook.save(...);"
3: "// <<<<<"
fullStatements: Array[1]
httpStatusCode: 500
data: undefined
```

Could you verify that on your side?

**Comment by manuelsidler** [comment] 2024-02-07 08:24
@damacisaac can you reproduce the bug with 16.81 on your side as well?

**Comment by manuelsidler** [comment] 2024-03-13 07:08
@XuanZhouMSFT @donlvMSFT I got the 16.83 update today. Unfortunately, the issue still exists.

**Comment by XuanZhouMSFT** [comment] 2024-05-13 11:07
@manuelsidler Thanks for the waiting.
The reproduce in our side is hard so it takes a long time for us to investigation. We had a guessing in our side and want to double confirm with you.

The design of the API is: If we passing nothing in the save API and just directly using "context.workbook.save();", the behavior is the same as passing "Save" as the parameter. It's to save the workbook without prompting the user. And if file is not saved, it will save it with default name in the default location.

The only repro steps in our side is: there's already a file with the same default name in the default location(Like Book1.xlsx), then the save action will fail because of conflict. Could you help to double check if there's already a same filename file there. The default location is like: /Users/XXX/Library/Containers/com.microsoft.Excel/Data/Documents. It should be a by-design behavior and we suggest you using the "Prompt" as the parameter, then you will have the chance to select the location and change the name.

**Comment by manuelsidler** [comment] 2024-05-13 11:23
@XuanZhouMSFT I was able to reproduce it based on your provided steps. Thanks for your detailed explanation!

**Comment by XuanZhouMSFT** [comment] 2024-05-14 02:27
Thanks for the confirmation. I will close the issue first as it's a by design behavior.
Please feel free to let us know if you still have concerns with it, we will still keep eyes on it.

**Closed as not planned by XuanZhouMSFT** 2024-05-14 02:27 UTC
Labels: Needs: attention :wave:, Area: Excel
