### ISSUE TITLE
The displayDialogAsync method becomes unresponsive.

### ISSUE THREAD

**Issue by t-ariyoshi30907** [OfficeDev/office-js#3297] opened 2023-04-14 09:53 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2302 (build 16.0.16130.20378)
* Operating System: Windows OS
* Browser (if using Office on the web): Google Chrome
 
## Expected behavior

Execute the "DisplayDialogAsync" method in index.js.
Load popup.html and popup.js.
Trigger a click event in popup.html.
Execute "Office.context.ui.messageParent(val)" in popup.js.
Execute "asyncResult.valueaddEventHandler()" in index.js.
Execute "closeDialog()" within the callback function to close the dialog.
Complete the event processing with "event.completed({ allowEvent: true })".

## Current behavior

1. Execute the "DisplayDialogAsync" method in index.js.
2. Load popup.html and popup.js.
3. Trigger a click event in popup.html.
4. Execute "Office.context.ui.messageParent(val)" in popup.js.
5. The processing inside "asyncResult.valueaddEventHandler()" is not executed.
6. The dialog operation stops, and the email cannot be sent.

## Steps to reproduce

1. Access the following URL.
2. Download "sample.zip" and place it in your desired location.
3. Launch the command prompt and navigate to the corresponding directory.
4. Run "npm install".
5. Run "npm run dev-server".
6. Upload "manifest.xml" in Outlook on the web to install the add-in. (The XML file is stored in sample.zip)
7. Create and send an email.
8. Click the "close(true)" button on the dialog.
9. Note: It does not occur every time, so repeat steps 7-8 approximately 10-20 times.

## Link to live example(s)

I am storing the sample add-in and related videos at the following URL.

- sample add-in program
https://drive.google.com/file/d/1Xrc-HuBLSjBAwDmU7y7Pbi7amwegbPDY/view?usp=share_link

- related videos
https://drive.google.com/file/d/1_p_jY7G5GMOgDcQM81Os5r0tL6faFP1C/view?usp=share_link

We have received feedback from customer requesting improvements.
Please investigate and make necessary improvements.

**Comment by t-ariyoshi30907** [comment] 2023-04-19 22:41
@slabereemsft @exextoc 

Hi,

We have received inquiries from multiple customers who are using the add-in and are having difficulties. Could you please help us confirm if the issue can be replicated?
If there is any information needed for the investigation, we will provide it.

**Comment by slabereemsft** [comment] 2023-04-20 05:04
Hi @t-ariyoshi30907 - It looks like its near the top of the queue to be looked at by the dev team. Hopefully we'll know more tomorrow.

**Comment by exextoc** [comment] 2023-04-20 05:51
Hey @t-ariyoshi30907 

It is not reproducible from our end, but we can see the issue in the video attached. 
While we try to reproduce the issue from our end, please help us with the questions below

- Since when did you see the issue, was it working fine before?
- What happens when dialog doesn't close, how do you close it?
- After the first repro, does it happen every time?
- Do you have to reload Outlook, every time the issue happens?

**Comment by t-ariyoshi30907** [comment] 2023-04-20 11:33
@slabereemsft @exextoc 

Thank you.

About one weeks ago, we discovered this issue when a customer contacted us with an inquiry. We do not know the exact date when it started occurring.

If the problem occurs, you can close the dialog by clicking the "X" button. However, if you reopen the dialog, the same problem will occur again.

There are times when the issue occurs repeatedly, but it does not happen with a 100% certainty.

Yes, as far as I have confirmed, the issue can be resolved by clicking the "F5" key and "Ctrl" key to reload. However, if you repeatedly send emails, the problem will occur again.

**Comment by t-ariyoshi30907** [comment] 2023-04-24 05:59
@slabereemsft @exextoc 

Have you been able to identify the cause of this issue? 
If there is any information needed for the investigation, we will provide it. 
Could you please reply and let us know about the progress of the investigation?

**Comment by exextoc** [comment] 2023-04-26 12:22
Thanks for reporting this issue. We are able to repro it. It has been put on our backlog. We unfortunately have no timelines to share at this point. We will update the thread once we have more updates on the fix. 

Internal tracking id: 3552622

**Comment by t-ariyoshi30907** [comment] 2023-08-24 09:16
@exextoc 

This issue is still ongoing. It has been a long time since we requested improvements. Could you please provide an update on the current status of the response?

**Comment by t-ariyoshi30907** [comment] 2024-03-07 08:01
@exextoc 
 It has been a long time since we requested improvements. 
This issue continues to persist, and because of it, we have received a request for service cancellation from a certain customer. 
This is a significant issue that is causing considerable damage to our business.
Could you please let me know the current status of the situation? Additionally, could you take actions for improvement?

**Comment by gapat-gh-msft** [comment] 2024-08-13 04:22
The provided add-in breaks 

![image](https://github.com/user-attachments/assets/7da63d1d-da8d-4d70-ba49-7e9a5a576d84)

Can someone provide the add-in that works so that the issue can be investigated further?

**Comment by gapat-gh-msft** [comment] 2024-08-27 10:56
I tried it for at least 20 times, and I did not see that it got stuck.
Looks like recently the issue is not reproducible. 
Could you pl confirm and close the issue @t-ariyoshi30907

**Comment by gapat-gh-msft** [comment] 2024-09-08 04:10
Will be closing the issue on 9th Sept as the issue is not reproducible and there is no further update from the OP.

**Comment by mailchecktool-admin** [comment] 2024-09-12 09:15
@gapat-gh-msft @exextoc 
Please do not close the issue as this problem is still occurring!
It seems that there was a problem with the add-in we provided, so we will prepare a new environment. Please wait a little.

**Comment by mailchecktool-admin** [comment] 2024-09-13 02:26
@gapat-gh-msft @exextoc 
Were you able to launch the attached sample add-in?
I checked and the add-in seemed to work fine.

I had tested it by sending it to myself, but it seems more likely to occur when sending to someone else, sensibly.
Can you try again as this glitch is still occurring?

**Closed as completed** 2024-09-20 04:49 UTC
Labels: Type: product bug, Needs: author feedback, Area: add-in UI

**Comment by gapat-gh-msft** [comment] 2024-09-23 03:43
> @gapat-gh-msft @exextoc Please do not close the issue as this problem is still occurring! It seems that there was a problem with the add-in we provided, so we will prepare a new environment. Please wait a little.

Sure, I am checking with the provided add-in.

**Comment by gapat-gh-msft** [comment] 2024-10-01 11:55
@t-ariyoshi30907 / @mailchecktool-admin 

Could you pl help me understand what is the use case here?
In a regular scenario, users will not be clicking on send buttons in succession so many times. 
It looks really like an edge case.

**Comment by mailchecktool-admin** [comment] 2024-10-03 04:20
@gapat-gh-msft 
If you are a user who frequently performs e-mail work, you may send e-mails in a short period of time.
In fact, we have received inquiries about this problem from add-in users, and we believe that such cases are not uncommon.

**Comment by gapat-gh-msft** [comment] 2024-10-10 06:41
@t-ariyoshi30907 
The add-in provided in this: https://drive.google.com/file/d/1Xrc-HuBLSjBAwDmU7y7Pbi7amwegbPDY/view?usp=share_link
is not displaying buttons that are shown in the video. 
I remember last time they appeared. 
Can you pl check once and provide the updated add-in?

**Comment by mailchecktool-admin** [comment] 2024-11-26 01:13
@gapat-gh-msft 
A sample add-in is stored below.
Please use this program to check it.
https://github.com/mailchecktool-admin/Office-addin-sample/tree/main
