### ISSUE TITLE
Unable to run the contextual add-in provided by outlook

### ISSUE THREAD

**Issue by g138** [OfficeDev/office-js#2319] opened 2021-12-20 18:12 UTC
I am following the example from this link https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex

Note: I am running the application locally.

So, on uploading the manifest.xml file on the outlook it highlights the regex text, but clicking it, doesn’t work. Seems like `index.js` is working.

getting this error below:

```
logAddinUsage.ts:105 Uncaught (in promise) TypeError: t.get_Type is not a function
    at logAddinUsage.ts:105
    at d (logAddinUsage.ts:30)
    at H.notifyHostError (OsfControlAdapter.ts:164)
    at H.notifyHostActions.<computed> (OsfControlAdapter.ts:79)
    at u.ContextActivationManager.H.notifyHost (OsfControlAdapter.ts:158)
    at u.ContextActivationManager.displayNotification (osfruntime.js:19)
    at u.OsfControl._showActivationError (osfruntime.js:19)
    at osfruntime.js:19
    at osfruntime.js:19
```

**Comment by exextoc** [comment] 2021-12-21 16:35
@g138 On which client are you trying to run your add-in? Also please share your code snippet.

**Comment by g138** [comment] 2021-12-22 11:14
@exextoc 

I am running the add-in in Outlook Web.

The code motivation is taken from   https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex

`Index.js: `
```
"use strict";

Office.initialize = function(reason) {
  $(document).ready(function(){
    loadEntities();
  });
}

function loadEntities() {
  // getSelectedRegExMatches is in preview, so need to test for it
  if (Office.context.mailbox.item.getSelectedRegExMatches !== undefined) {
    var selectedMatches = Office.context.mailbox.item.getSelectedRegExMatches();
    if (selectedMatches) {
      // Note that the use of selectedMatches.OrderNumber, where
      // OrderNumber corresponds to the RegExName attribute of the Rule element
      // in the manifest
      $("#selected-match").text(JSON.stringify(selectedMatches.OrderNumber, null, 2));
    } else {
      $("#selected-match").text("Selected matches was null");
    }
  } else {
    $("#selected-match").text("Method not supported on your client");
  }

  // Get all matches
  var allMatches = Office.context.mailbox.item.getRegExMatches();
  if (allMatches) {
    // Note that the use of selectedMatches.OrderNumber, where
    // OrderNumber corresponds to the RegExName attribute of the Rule element
    // in the manifest
    $("#all-matches").text(JSON.stringify(allMatches.OrderNumber, null, 2));
  } else {
    $("#all-matches").text("All matches was null");
  }
}

function showError(message) {
  $("#error-msg").text(message);
  $("#error").show();
}
```

`Index.html`

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Contoso Order Number Add-in</title>
  <link href="//static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.0.0/css/fabric.min.css" rel="stylesheet">
  <link href="index.css" rel="stylesheet" type="text/css" />

  <script src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
  <script src="//appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
  <script src="index.js"></script>
</head>

<body>
  <div id="content-main" class="ms-Fabric">
    <div id="error" class="ms-font-m ms-borderBase ms-borderColor-neutralTertiaryAlt ms-bgColor-error ms-fontColor-error">
      <span class="icon ms-font-l"><i class="ms-Icon ms-Icon--Error" aria-hidden="true"></i></span>
      <span class="ms-font-l ms-fontWeight-semibold">Error</span>
      <pre><code id="error-msg"></code></pre>
    </div>
    <div id="entity-display">
        <h2 class="ms-font-l">Selected match</h2>
        <pre><code id="selected-match"></code></pre>
        <h2 class="ms-font-l">All detected matches</h2>
        <pre><code id="all-matches"></code></pre>
    </div>
  </div>
</body>
</html>

```

**Comment by exextoc** [comment] 2021-12-23 11:01
@g138 Thanks for reporting this issue. We had fixed this issue recently and is pending for rollout. We will notify here once the fix is available worldwide.

**Comment by exextoc** [comment] 2022-01-10 10:02
@g138 The fix has been rolled out worldwide. Could you please verify if the issue is fixed on your end?

**Comment by g138** [comment] 2022-01-17 13:58
Thanks for the role out.

But following the example from the https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex

On running the app I am getting nothing.

See the image below. 

Code base is exactly taken from https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex

![image](https://user-images.githubusercontent.com/36992519/149782456-af81cac9-e931-419a-9784-976ad31d7e1e.png)

**Comment by paul-schroeder-msft** [comment] 2023-02-14 23:22
I am having a similar experience as Gaurav...it does not work in Outlook web, but it is kind of working in Outlook desktop (screenshot attached).  In the desktop flavor, one of what I think should be several matches works.  However, I do not see any updates in the web page that contains the "selected-match" and "all-matches".

I am running locally at https://localhost:8080/ and used Outlook Web to side-load the manifest.  Perhaps I need to use ngrok or  Visual Studio Dev tunnels to access the localhost, but there's no mention in the instructions for doing so, as far as I saw.  Below is a screenshot of multiple email tests sent to myself with various test strings.

![image](https://user-images.githubusercontent.com/107234768/218883072-0823a762-25fb-4417-bcfa-ff430165153c.png)

**Comment by exextoc** [comment] 2023-02-21 16:10
@g138 Following the instructions mentioned under: https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex, we tried to repro this, but we could not, and the "locally hosted" add-in works. 
Can you please confirm following the instructions mentioned under Pre-requisites:
![image](https://user-images.githubusercontent.com/28549921/220397337-cac7a686-c2a7-47d6-bb91-a76bec28bfdc.png)
Since you are trying to host the add-in locally, please follow: [Running the add-in Locally](https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex/blob/master/running-locally.md), specially [Installing the self-signed certificate](https://github.com/OfficeDev/generator-office/blob/master/src/docs/ssl.md) part. 

Also please verify that the local server is running after going through above mentioned steps and you can browse to the URLs mentioned in the manifest from your client using browser. For example, you should be able to browse to the URL in the <bt:Url id="detectedEntityURL"> element in manifest (Should be:  "https://localhost:8080/index.html" If you did not change the manifest).

**Comment by exextoc** [comment] 2023-02-28 12:11
@paul-schroeder-msft If you see the reg-ex for test addin the format used is [ CO- followed by 9 digits](https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex/blob/master/contoso-order-number-manifest.xml#:~:text=RegExValue%3D%22CO%2D%5Cd%7B9%7D). I can see in the snapshot shared by you, strings qualifying this format are highlighted. If this does not answer your question, can you create a separate github issue?

**Comment by paul-schroeder-msft** [comment] 2023-02-28 16:25
@exextoc - I think that you are correct on the regex matches.  I was seeing this rule in the manifest.xml file 

![image](https://user-images.githubusercontent.com/107234768/221914661-5d965833-4a52-40d7-9c73-0f905d84f80b.png)

and not this one:

![image](https://user-images.githubusercontent.com/107234768/221914736-8da3d894-ba7b-4e00-bc54-806b38bd27db.png)

Which leads me to two more questions:
1) Why are there two places the rule gets defined.
2) I now see <DesktopFormFactor> as a qualifier / outer XML element.  Could this be why it isn't working on the web?

**Comment by exextoc** [comment] 2023-03-08 11:29
@paul-schroeder-msft   The first Rule elements are for legacy clients that do not understand the VersionOverrides schema. These values will be ignored by clients that do understand VersionOverrides, with the exception of Permissions.
So the Rule elements here should match the Rule Element inside Detected Entity so that the add-in will be able to highlight the matches.
Do let us know what is the issue you are currently facing on Outlook on the Web. If it is different from the one mentioned by @g138 , we suggest you create a separate issue for the same.

**Closed as completed** 2023-03-20 08:01 UTC
Labels: Area: Outlook, Needs: author feedback, Type: programming question, Status: no recent activity
