### ISSUE TITLE
Excel: Double click on Ribbon item opens two taskpanes

### ISSUE THREAD

**Issue by ppagadala** [OfficeDev/office-js#1278] opened 2020-07-13 06:53 UTC
## Expected Behavior
One instance of the Task pane should be opened.

## Current Behavior
Two panes are opened.
Should not open two taskpanes or should give config param in manifest to disable the double click on Ribbon item.

## Steps to Reproduce, or Live Example
1. Have a plain manifest with a button in ribbon which opens a taskpane
2. Upload the manifest in Excel.
3. Double click on the Ribbon item
4. Then it opens two taskpanes.
5. if you click Ribbon item **n** number of times **n** number of taskpanes will open.

## Context
Expecting it to open only one taskpane but opens two.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
![Multiple_Taskpane_issue](https://user-images.githubusercontent.com/11500788/87278870-26844d80-c503-11ea-85b2-7423d8994a2a.gif)

- [ ] Test file (if only happens on a particular file)

**Comment by lindalu-MSFT** [comment] 2020-07-14 01:52
@lliu113 @sohailzafar Hi! This issue is a UI issue, not a JS issue. Can you please have a look? Thanks!

**Comment by keyur32** [comment] 2020-07-29 22:51
@ppagadala  - hey there, can you share an example manifest so the team can reproduce this issue?  Does it happens with other add-ins?

**Comment by ppagadala** [comment] 2020-08-03 05:41
@keyur32 Here is the example manifest to reproduce the issue.
[Test Manifest.zip](https://github.com/OfficeDev/office-js/files/5014103/Test.Manifest.zip)

**Comment by lliu113** [comment] 2020-09-14 20:27
@ppagadala sorry for the late response to this! Clicking on the ribbon button should refresh the existing taskpane, not launch a new one (as pictured) so this behaviour is definitely a bug. 

Unfortunately, I'm unable to repro this with our test add-ins and I'm running into some issues with the manifest you provided. Are you still seeing this on your end? Is this just for Excel Online, or are you seeing this replicated on desktop?

**Comment by ppagadala** [comment] 2020-09-16 11:45
@lliu113  I am still able to reproduce the issue. The issue is occurring in the Excel Online only. Once the user **Double-Click**  the ribbon item then two taskpane windows of same application will open. This issue can be reproducible with any manifest I guess. As a matter of fact how many clicks (don't pause in between) that you do on the Ribbon item that many taskpanes would open.

**Comment by lliu113** [comment] 2021-03-19 21:19
@ppagadala - Unfortunately I'm still unable to repro this on Excel, using Chrome. I tried with the Scriptlab add-in, double-clicking the 'Code' ribbon button launches a single taskpane. Additional clicks refresh the taskpane. 

I'm going to close this issue for now, please reactivate if you're still seeing this. If you can provide another manifest to help us test that would be extremely helpful. Thanks!

**Comment by wh1t3cAt1k** [comment] 2022-08-18 21:55
![image](https://user-images.githubusercontent.com/5159662/185502011-3975b605-8eb5-4a71-a5f6-2a5e5301b5ac.png)

@lliu113 I am still seeing this in Excel Online on very large files (>40k custom functions) with our add-in by clicking on the ribbon button multiple times during the load process.

**Comment by wh1t3cAt1k** [comment] 2022-08-18 21:56
@keyur32 @lindalu-MSFT I suggest to reopen this and investigate in more depth, this has been sporadically affecting us for over a year and the clients are really unhappy.

**Comment by lindalu-MSFT** [comment] 2022-08-19 03:32
Hi @wh1t3cAt1k Pavel, I'm "just" the editor and not the subject matter expert. I can, however, reopen this and ping @keyur32 as well as other Excel people who might be able to help. @yaweizhu-henson @JinghuiMS

**Comment by lindalu-MSFT** [comment] 2022-08-19 03:40
@wh1t3cAt1k Pavel, have you created a bug report from within the Excel application you're using? For example, in Excel on the web, go to Help > Feedback > I don't like something (aka "send a frown")
<img width="163" alt="image" src="https://user-images.githubusercontent.com/30682803/185537904-ad6ed7b6-d3b0-4b68-aa3b-99a2d1d5239e.png">

**Comment by wh1t3cAt1k** [comment] 2022-08-19 11:05
@lindalu-MSFT I believe I did, but not sure anymore :)

Yes please reopen since it's reproducible and has severity, at the same time it's a heisenbug which we see only sporadically and more rare than in the past.

Can you guys do a code review to understand the code paths where this can happen?

We also use auto open behaviour, most of the time we see two taskpane threads when the file is huge and we click on add-in icon in the ribbon while the file is still loading.

The problem for us is that function calculation gets messed up and we see no status reporting in our task pane, it goes to the "wrong" one.

**Comment by wh1t3cAt1k** [comment] 2022-10-14 15:12
Again received it during session 943c279b-6c2c-4692-854a-09095dcc23af on build 16.0.15809.35901 in Edge.

![image](https://user-images.githubusercontent.com/5159662/195879754-e27d59c6-651e-4bf8-9c93-c6b8e001e746.png)

[manifest.zip](https://github.com/OfficeDev/office-js/files/9787608/manifest.zip)

Points of interest from the manifest:

![image](https://user-images.githubusercontent.com/5159662/195880061-76fb02b7-f7ee-4c7d-a4fc-948fb4ca086e.png)
![image](https://user-images.githubusercontent.com/5159662/195880108-0bfef965-8143-42ef-a316-8cb7dc9eefa2.png)

Note that it uses shared runtime and the taskpane is configured to load on open.

I reproduced it (I think) while, at first, my Docker wasn't running, so the taskpane could not load, I launched Docker and clicked the ribbon button to launch the add-in. 

When it started calculating, I noticed that the UI wasn't displaying the active functions (which in our case it should), then I noticed there were two VX side panels and in dev tools I saw two task pane threads.

**Comment by sshukurov** [comment] 2022-10-14 16:47
Seems like this issue is very similar to this one I reported here: https://github.com/OfficeDev/office-js/issues/2096. Instead of 2 taskpanes, though, we get 2 taskpane **threads**. I provided a minimal repro with easy steps.

**Comment by wh1t3cAt1k** [comment] 2022-10-14 22:28
Thanks @sshukurov 🙏 
I feel this definitely deserves the attention of the engineering team at MSFT, it's a long-standing issue with ugly symptoms.

**Comment by Wenjun-Gong** [comment] 2022-10-26 15:44
Ruizhi, could you help to take a look? @ RuizhiSunMS

**Comment by RuizhiSunMS** [comment] 2022-12-02 03:04
@ RuizhiSunMS

**Comment by RuizhiSunMS** [comment] 2022-12-02 03:04
@RuizhiSunMS

**Comment by SiruiSun-MSFT** [comment] 2023-06-15 03:04
Hi @wh1t3cAt1k, sorry for the late response. We noticed that the frequency of this problem is very low, and a poor network environment will cause more obvious errors. Does this problem still occur now? If it still occurs, we will open an internal bug to track this issue. Or you can provide the scale of affected users, it will help us re-prioritize this problem. Thanks for your patience!

**Closed as not planned** 2024-04-11 02:59 UTC
Labels: Needs: attention :wave:, Area: Excel, Type: product bug, Area: add-in UI

**Comment by XuanZhouMSFT** [comment] 2024-04-11 03:23
Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.

**Comment by wh1t3cAt1k** [comment] 2024-04-15 12:43
I don't necessarily agree on reporting bugs through the ideas forum. That being said, I have not recently observed the issue of double task panes.
