### ISSUE TITLE
ConversationId is 'null' in new OWA on Forward

### ISSUE THREAD

**Issue by mpetro-t** [OfficeDev/office-js#679] opened 2019-08-19 15:44 UTC
Office.context.mailbox.item.conversationId is returning null when we are forwarding email in Outlook UI for web. It works properly in Outlook for Desktop and it was working propertly in old OWA.

Almost exact issue was already reported for Reply functionality (#636) and it was fixed, but for Forward it doesn't work.

## Steps to Reproduce, or Live Example
Steps are identical to linked issue (#636) but instead of clicking on Reply, we click on Forward.

**Comment by exextoc** [comment] 2019-08-19 17:07
Closing this as a duplicate. It appears to be due to the same root cause as the following issue:
https://github.com/OfficeDev/office-js/issues/636

**Comment by mpetro-t** [comment] 2019-08-19 17:11
Why is this closed? Issue #636 is fixed and now it is live - as it was stated in it's comments. This issue was not fixed by #636 fix?

**Comment by mpetro-t** [comment] 2019-08-19 19:12
Based on this comment https://github.com/OfficeDev/office-js/issues/636#issuecomment-517650107 I would think that this "Forward" bug is not a duplicate. Fix for #636 was rolled out today to Production but #679 behavior happens. Can you please re-open this?

**Comment by exextoc** [comment] 2019-08-20 08:00
Thanks for reporting this issue regarding conversation Id being null in case of message forwarding scenario. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment] 2019-10-09 10:32
We have fixed this bug and it is available in production now.

**Closed as completed by exextoc** 2019-10-09 10:32 UTC
Labels: Area: Outlook, Type: product bug, Status: fixed
