### ISSUE TITLE
Outlook api Office.context.mailbox.item.body.getAsync("html") sometimes brings error object

### ISSUE THREAD

**Issue by ndvbd** [OfficeDev/office-js#1842] opened 2021-05-03 21:26 UTC
On Mac, Outlook 16.48.411.0, sometimes (30% of the times, usually after a restart of the outlook), the Office.context.mailbox.item.body.getAsync("html") returns an error object instead of an object who's value is the actual html text.
The object contains code: 5001, and a message "An internal eror has occured", status: "failed".
This unexpected behaviour is very annoying. I don't have time to create a standalone code to reproduce the problem.

**Comment by nancy-wang** [comment] 2021-05-06 23:13
Thanks for sharing this feedback with us @ndvbd - I've tagged @macOutlookExtensibility to investigate this further.

**Comment by exextoc** [comment] 2021-05-09 20:42
When the issue reproduces does that happen only on a particular mail or all the mails? If there is a particular mail can you send that to us on admin@M365x010952.onmicrosoft.com.
If this is a generic failure then can you share your code snippet?

**Comment by exextoc** [comment] 2021-05-12 06:16
Thanks for reporting this issue regarding body.getAsync() API. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 5105135

**Comment by ndvbd** [comment] 2021-05-13 08:22
"When the issue reproduces does that happen only on a particular mail or all the mails? "->  I don't know, haven't tested it with multiple emails, because I don't have multiple 365 subscriptions (it cost money, you don't give developer accounts for free :(. You should. ). If you give me multiple email accounts, I can test it.

**Comment by exextoc** [comment] 2023-02-07 17:59
Hi @ndvbd, the issue is now fixed for Mac Outlook.

**Comment by ndvbd** [comment] 2023-02-07 19:57
Thank you!

**Closed as completed** 2023-02-07 19:58 UTC
Labels: Area: Outlook, Type: product bug, Status: in backlog
