### ISSUE TITLE
[Outlook add-in] Outlook 2013 cannot run any add-in app error: outlook.15.01.js access denied

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#918] opened 2019-12-29 07:09 UTC
Outlook 2013 cannot run any add-in app. All ad-in was show in error: outlook.15.01.js access denied.
We have tried many add-ins include 'My-template' . All add-in show in 'Office applications' and if I try to start any add-in will show error. I open the developer tool can see error:  "outlook.15.01.js access denied"
PS: This probelm happened on Outlook 2013 onpremise environment.
## Expected Behavior

add-in load normal.

## Current Behavior

Install add-in from application store. Then try to start this add-in.
And I have tried some way to resolve this problem:
1. Check manifest to delete unsupported tag on Outlook 2013.
2. we can access microsoft site.
3. reset IE 'Security' configuration to default
And I will try command:"icacls %userprofile%\Appdata\LocalLow /t /setintegritylevel (OI)(CI)L" ,But I don't think this will solve this problem. 

## Steps to Reproduce, or Live Example
Just load add-in on Outlook 2013 Windows 10(CitriX)

## Context

As a result , we can't use add-in on Outlook 2013

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook 2013
* Operating System: Windows 10 (On CitriX)
* Browser (if using Office Online): NA

## Useful logs
![image](https://user-images.githubusercontent.com/15980696/71553582-fdabd780-2a4c-11ea-9b94-394f07e8d42d.png)

By the way, I always meet this kind of issue about add-in can't load. Do microsoft have any wiki about how to check this kind of issues?

**Comment by lindalu-MSFT** [comment] 2019-12-30 07:38
@SWei1234 Thank you for bringing this to our attention! I assigned this to the @exextoc , the Outlook Add-ins team. Please note that many people are on vacation this week due to the Holidays so please be patient. It might be a few days before they have a chance to address this issue. I will check back in a couple days! Thanks, lindalu

**Comment by exextoc** [comment] 2019-12-30 19:50
@SWei1234, have you tried accessing [that url](https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-15.01.js) via a regular web browser? It may be that for whatever reason, your company firewall is preventing access to this file. I just tested the file and it seems to be working as intended.

**Comment by SWei1234** [comment] 2019-12-31 01:24
> @SWei1234, have you tried accessing [that url](https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-15.01.js) via a regular web browser? It may be that for whatever reason, your company firewall is preventing access to this file. I just tested the file and it seems to be working as intended.

Yes, I have already tried this and can access this file. Actually I see the .har file outlook.15.01.js show http 304. That means this file has already been cached but I just can't access this file.
By the way this only happened on some Outlook 2013 under the same network. It works fine on Outlook 2016/2019 and some other outlook 2013.

**Comment by exextoc** [comment] 2020-01-08 00:14
What versions of Outlook 2013 are not working? And which versions ARE working?
 Outlook-15.01.js is actually a very old version of the file, and you may be on versions of Outlook 2013 that are no longer under support. (outlook-15.04.js) is currently the latest. 

What I suspect is happening is that the versions of Outlook 2013 that aren't working aren't on the latest Outlook 2013. After automatic updates happen then those versions become fixed. If machines/orgs have blocked updates then they may not be getting the latest updates.  

See: https://docs.microsoft.com/en-us/officeupdates/update-history-office-2013

for current version of Office 2013. (which as of now is 15.0.5197.1000), but it looks like OUtlook was last updated in Oct (https://support.microsoft.com/en-us/help/4484096/october-1-2019-update-for-outlook-2013-kb4484096) and outlook.exe is at: 15.0.5172.1000

**Comment by SWei1234** [comment] 2020-01-09 06:55
Hi @exextoc 
Outlook MSO(15.0.5172.1000) 64 bit is work. And on this version outlook.js version is 15.04.
Outlook 2013 version which not working will reply you later. 
By the way, I have a question , we all use outlook 2013 why I get outlook_15.04.js but other one get outlook_15.01.js.
what cause this difference? I wonder maybe it's not caused by outlook client version, because our version is close but we are in different environment. 
I'm use office 365 account in outlook 2013. But he use outlook 2013 in on-Prem environment.

**Comment by timwan03** [comment] 2020-01-10 01:20
There are very many different versions of Outlook 2013. It is likely that the users experiencing the error are on versions that are old or not supported anymore. (note that It is best to update all of Office and not Outlook). Being on-prem vs office 365, should not affect the outlook.js version loaded. It may however affect which add-ins are supported. As some APIs are not supported by On Prem, and it will not load Add-ins that depend on them.

**Comment by exextoc** [comment] 2020-01-10 01:23
There are very many different versions of Outlook 2013. It is likely that the users experiencing the error are on versions that are old or not supported anymore. (note that It is best to update all of Office and not Outlook). Being on-prem vs office 365, should not affect the outlook.js version loaded. It may however affect which add-ins are supported. As some APIs are not supported by On Prem, and it will not load Add-ins that depend on them.

**Comment by SWei1234** [comment] 2020-01-10 06:13
Hi @exextoc  Can you show me the minimum version number that support add-in ?  I want to make sure if this problem is caused by Outlook version.

**Comment by exextoc** [comment] 2020-01-10 19:31
All versions of Outlook 2013 should support Add-ins in some state. But different features were enabled at different times. There is no table that associates certain versions with features, as if you have components that are different versions. (i.e. you upgraded Outlook, but not MSO or Word), then those features are also not enabled. For example, Outlook 2013 15.0.4805.1000 is the first version that supports App Commands. But you must also take the corresponding patches to osfclient.dll and mso.dll to enable them. Outlook reporting 4805 is not enough to ensure that that feature works.

**Comment by lindalu-MSFT** [comment] 2020-01-18 00:36
@exextoc Can we close this issue? If I closed it too soon, feel free to reopen!

**Closed as completed by lindalu-MSFT** 2020-01-18 00:36 UTC
Labels: Area: Outlook, Needs: author feedback, Type: product question, Resolution: question answered
