### ISSUE TITLE
Excel.WorksheetProtectionOptions loaded from worksheet is invalid

### ISSUE THREAD

**Issue by jwhite-venacorp** [OfficeDev/office-js#1931] opened 2021-06-17 00:30 UTC
# Provide required information needed to triage your issue

We unprotect the worksheet so that we may manipulate them, and then reapply the protection options when we return control to the user. On the "InsiderPreview" build, we have to modify the `Excel.WorksheetProtectionOptions` object to re-apply the protection options.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.14210.20004
* Operating System: Windows 10, OS build 19042.1052
* Browser (if using Office on the web): N/A
 
## Expected behavior

I expect the `Excel.WorksheetProtectionOptions` object returned by `sheet.protection.options` is a valid object to pass to `sheet.protection.protect()`.

## Current behavior

For the Excel "InsiderPreview" channel release the object returned by `sheet.protection.options` is not a valid object to be applied by `sheet.protection.protect()`. The console displays a `RichAPI.Error` with the message `There was an internal error while processing the request.` It appears the `Excel.WorksheetProtectionOptions` returned by `sheet.protection.options` has some null properties; removing these null properties creates a valid object for the `sheet.protection.protect()` function.

I tested in the "Current" channel release and could not reproduce this issue.

## Steps to reproduce

1. Unprotect the worksheet, if it is protected.
2. Get the `Excel.WorksheetProtectionOptions` from `sheet.protection.options`
3. Call `sheet.protection.protect` and pass the `Excel.WorksheetProtectionOptions` returned above.

## Link to live example(s)

1. [Script Lab gist](https://gist.github.com/jwhite-venacorp/06f28107ac47da60993144c0c091906f)

# Provide additional details

## Context

We unprotect the worksheet so that we may manipulate them, and then reapply the protection options when we return control to the user.

## Useful logs

- [x] Console errors
```
[ERROR]: Error:
{
    "stack": "RichApi.Error: There was an internal error while processing the request.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:235644)\n    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:297462)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:295567",
    "message": "There was an internal error while processing the request.",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "There was an internal error while processing the request.",
        "errorLocation": "WorksheetProtectionOptions.allowTableColumnDelete",
        "statement": "protection.protect(...);",
        "surroundingStatements": [
            "var workbook = context.workbook;",
            "var worksheets = workbook.worksheets;",
            "var worksheet = worksheets.getItem(...);",
            "var protection = worksheet.protection;",
            "// >>>>>",
            "protection.protect(...);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}
```
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by alison-mk** [comment] 2021-06-17 20:36
Hi @jwhite-venacorp, thank you for submitting this issue! We've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by gingerjia** [comment] 2021-10-12 13:23
The issue has been fixed and just as @jwhite-venacorp said "I tested in the "Current" channel release and could not reproduce this issue.". 
I will close it now and if have any new issues please feel free to let us know. Thanks!

**Closed as completed by gingerjia** 2021-10-12 13:23 UTC
Labels: Needs: attention :wave:, Area: Excel, Type: product bug
