### ISSUE TITLE
horizontalFitToPages does not set if Page Layout tab is not selected

### ISSUE THREAD

**Issue by CTDProgrammer** [OfficeDev/office-js#1860] opened 2021-05-12 16:19 UTC
I have the following code that runs on a button click:
```TypeScript
const currentWorksheet = context.workbook.worksheets.getActiveWorksheet();
currentWorksheet.pageLayout.printGridlines = true;
currentWorksheet.pageLayout.orientation = "Landscape";
currentWorksheet.pageLayout.zoom = { horizontalFitToPages: 1 };
```

## Expected Behavior
I wish for the Scale to Fit > Width to be set even when I don't have the Page Layout tab open.

## Current Behavior
If I am not on the Page Layout tab, then Scale to Fit > Width does not get set. However the printGridlines and orientation do get set. The same thing happens if the last line is
```TypeScript
currentWorksheet.pageLayout.zoom = { verticalFitToPages: 1 };
```

but does *not* happen when
```TypeScript
currentWorksheet.pageLayout.zoom = { scale: 200 };
```

## Context
I wish for all the populated columns to fit on one page

## Your Environment
I started the project with the regular option in the yeoman generator.

**Comment by jipinshi** [comment] 2021-05-13 05:49
@CTDProgrammer , thanks for reaching us to report the issue. Can you show us with one video and let us know the Platform you are running win32/MAC/Excel online? and also help check the build version you are running your excel. Check from File->Account to get the excel build version if it is win32/MAC. I tried with the steps mentioned here cannot repro on windows 64 bits.

**Comment by CTDProgrammer** [comment] 2021-05-13 13:36
@jipinshi 
I am on Excel on Windows 10, Microsoft 365 Apps for enterprise Version 2104 (Build 13929.20296 Click-to-Run)

https://user-images.githubusercontent.com/84091612/118133127-74d9d580-b3ce-11eb-9f18-394bf82bde86.mp4

In the above video, on try 1, somehow the width got updated as I was clicking around on the ribbon, and I haven't observed that before. On try 2, I had to click on a cell for it to update, but I didn't have to do that before. The reason might be because with the full logic I update cells. Try 3 is what is closest to when I have other things put together. The important part is the behavior is hard to pin down, and is not what I expect.

**Comment by jipinshi** [comment] 2021-05-14 03:54
@CTDProgrammer, now I can repro the issue, will continue investigate the root cause, thanks for reporting, 5111634 is used internal track.

**Comment by jipinshi** [comment] 2021-05-14 03:58
@CTDProgrammer,  when the pagelayout was ever clicked before, even go to home tab, the script also still can work, so one way to unblock you is try to switch to pagelayout first and then run the script, hope it can unblock you first.

**Comment by jipinshi** [comment] 2021-05-19 09:10
@CTDProgrammer , you could try below code to unblock you either.
currentWorksheet.pageLayout.zoom = { scale: 100 };
currentWorksheet.pageLayout.zoom = { horizontalFitToPages: 2 };

**Comment by CTDProgrammer** [comment] 2021-05-19 12:45
@jipinshi Thank you for the workaround. If I try it in the context of my full code it seems to work.

If I try the workaround on the reproduction code and I have opened the page layout tab before I programmatically adjust the zoom, then I have to click on a cell for the scale to fit information to update.

**Comment by jipinshi** [comment] 2021-05-20 02:42
@CTDProgrammer, glad to hear it can unblock your work first. We are actively working on the investigation, will let you know when the fix is ready.

**Comment by dingjin-ms** [comment] 2021-09-15 06:25
Hi @CTDProgrammer , we have fixed the problem and the fix has been rolled out to current channel, builds above 16.0.14427.10000. Thank you for your report!

**Closed as completed** 2022-11-16 12:05 UTC
Labels: Area: Excel, Status: in backlog
