### ISSUE TITLE
Error when loading an Add In 

### ISSUE THREAD

**Issue by hansdaume** [OfficeDev/office-js#1620] opened 2021-01-28 07:59 UTC
Hello all,

unfortunately some employees in our company have the problem that an Add In cannot be loaded. The following error message appears:
![image](https://user-images.githubusercontent.com/78138374/106106343-b0b19d80-6145-11eb-973b-f9defa151310.png)

## Expected Behavior

Normally, the add-in should load and be used after a few moments. This is also the case for some employees in our company.
![image](https://user-images.githubusercontent.com/78138374/106107340-1bafa400-6147-11eb-9c03-a23533cd16ff.png)

## Current Behavior

For some employees, the add-in does not load and the following error message appears.
![image](https://user-images.githubusercontent.com/78138374/106106555-0128fb00-6146-11eb-81dd-4c045c3f670a.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel, Word, PowerPoint
* Office version number: 
![image](https://user-images.githubusercontent.com/78138374/106107243-ff136c00-6146-11eb-88ba-bde7cc50acb8.png)

* Operating System: Windows
* Browser (if using Office on the web): via the browser and the Word application the add-in works

## Useful logs

![image](https://user-images.githubusercontent.com/78138374/106106720-41887900-6146-11eb-99e3-946a544802ba.png)
Screenshot of the error message

**Comment by AbidRahman-MSFT** [comment] 2021-01-28 21:49
Thanks for reporting the issue, @hansdaume. We are aware of this bug and are currently investigating it. (#4757066 for internal tracking).

We will give an update here as soon as we know more.

**Comment by AbidRahman-MSFT** [comment] 2021-01-29 00:36
@hansdaume, are you able to verify the Windows and Office version that the error is occurring on? 

This bug may be related to an issue only seen on IE 11, please help us verify if that is the case, you can find the list of Office and Windows versions that still use IE as the browser host for the add-in: [Browsers used by office add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)

As a workaround, please try updating the Windows and/or Office versions to use the Microsoft Edge browser. Please let us know if the issue is still occurring.

**Comment by atsopuronen** [comment] 2021-02-04 16:02
We have few customers with this issue. All settings related to ADD-IN ERRORs have been triple-checked (Protected Mode, TabProcGrowth, firewall, anti-virus, etc.), also in GPO and registry level. Their issue is caused by **something else**.

It **seems** to have started after they installed Edge Chromium to replace EdgeHTML. There's a crash event in Event Viewer for Win32WebViewHost.exe and edgemanager.dll. 

We have a **theory** why the crash occurs:
- User has Office version that uses EdgeHTML for add-ins
- User installs Edge Chromium which corrupts edgemanager.dll
- All Office add-ins cause ADD-IN ERROR as edgemanager.dll causes Win32WebViewHost.exe to crash.

**WORKAROUND:**
As of now, the only viable fix has been to rebuild user's Windows profile. 
However, this only works temporarily (hypothesis: until Edge Chromium updates itself again).

In this article, the person tried to replace the corrupt files from a working instance, to no avail:
https://windows-hexerror.linestarve.com/q/so63090339-Office-apps-is-unable-to-show-Web-Add-ins-taskpane-due-to-a-Win32WebViewHostexe-issue

**UPGRADING OFFICE:**
NOTE: Our customers are unable to upgrade their Office to a version that uses Edge Chromium instead (16.0.13530.20424) because they are on an Update Channel (Semi-Annual Enterprise) that doesn't have the version available.

Latests version at the time of writing:
- Current channel: Version 2101 (Build 13628.20274)
- Monthly Enterprise channel: Version 2011 (Build 13426.20526)
- Semi-Annual Enterprise channel: Version 2008 (Build 13127.21064)

-> Current Channel is the only non-Preview channel to activate WebView2 (Edge Chromium).

**Comment by hansdaume** [comment] 2021-02-05 07:16
Thanks for the answers. We have updated the Windows version of a user who experienced this problem. After that, the add-in could be loaded. We are now trying it on other users to see if it really is the solution to the problem.

**Comment by atsopuronen** [comment] 2021-02-05 12:12
> Thanks for the answers. We have updated the Windows version of a user who experienced this problem. After that, the add-in could be loaded. We are now trying it on other users to see if it really is the solution to the problem.

**From** which version and **to** which version did you update Windows? Do you know under what process does the add-in now run on? WebView (EdgeHTML), WebView2 (EdgeChromium)?

**Comment by atsopuronen** [comment] 2021-02-18 12:52
My team has set up a dedicated site about our findings into our knowledge base: 
https://support.hoxhunt.com/hc/en-us/articles/360019436319

Please let us know of your troubleshooting efforts, they are highly appreciated!

**Comment by AbidRahman-MSFT** [comment] 2021-04-01 19:55
Hey @atsopuronen, the general guidance around this issue is to upgrade the user's Office version to use WebView2 as the browser hosting the add-in.

The versions that use WebView2 can be found here: [Browsers used by Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)

I understand that there are some of your users that are on the Semi Annual Channel and are unable to update their Office versions. Is this issue still occuring with these users and is it a high priority issue for you?

Thanks,
Abid

**Comment by atsopuronen** [comment] 2021-04-14 18:35
Hello Abid,

Yes, we have users at one of our customers who are experiencing ADD-IN ERROR even after upgrading to the latest and greatest Office version and Windows 10 version. The only thing they haven't tried yet is Windows user profile reset. 

Because of the error, they are unable to use our Outlook add-in.

**Comment by DB-ADM** [comment] 2021-05-11 13:43
Hi @atsopuronen - This issue has come up over the past year for a few of my clients as well and typically the resolution is to just have them use the add-in through the OWA until we can get them on a version of Office that supports Edge Chromium.  However, this came up for another client recently that for one reason or another, is unable to upgrade their version of Office.  After a bit of time troubleshooting, I was able to figure out how to fix this.

They were experiencing the same symptoms:
-Add-In error in the Outlook desktop client when trying to start a web add-in
-Crashes recorded in event viewer relating to Win32WebViewHost and edgemanager.dll

What I found is that the permissions for WebView's AppData folder had gotten corrupted or overwritten.  Not sure if this is the same reason your users are experiencing this, but here's how to tell:
-Navigate to %localappdata%\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\
-In that directory, grant "ALL APPLICATION PACKAGES" full control of that folder, subfolders, and files (If domain-joined, make sure the local machine is selected for the location when searching for the group)

Now try launching the add-in.  If it works, great!  You'll want to apply the correct permissions now.  I reviewed a known working system to determine what the correct permissions should be.  To do this:
-Remove the permissions that were given above
-Run the following from an elevated command prompt:
```
icacls "%localappdata%\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\AC" /grant "*S-1-15-2-1310292540-1029022339-4008023048-2190398717-53961996-4257829345-603366646:(F)" /T
icacls "%localappdata%\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\AC\#!123" /grant "*S-1-15-2-1310292540-1029022339-4008023048-2190398717-53961996-4257829345-603366646-3829197285-1050560373-949424154-522343454:(F)" /T
icacls "%localappdata%\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\LocalCache" /grant "*S-1-15-2-1310292540-1029022339-4008023048-2190398717-53961996-4257829345-603366646:(F)" /T
icacls "%localappdata%\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\LocalState" /grant "*S-1-15-2-1310292540-1029022339-4008023048-2190398717-53961996-4257829345-603366646:(F)" /T
icacls "%localappdata%\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\RoamingState" /grant "*S-1-15-2-1310292540-1029022339-4008023048-2190398717-53961996-4257829345-603366646:(F)" /T
icacls "%localappdata%\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\Settings" /grant "*S-1-15-2-1310292540-1029022339-4008023048-2190398717-53961996-4257829345-603366646:(F)" /T
icacls "%localappdata%\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\TempState" /grant "*S-1-15-2-1310292540-1029022339-4008023048-2190398717-53961996-4257829345-603366646:(F)" /T
```
After granting those permissions, add-ins should now open.

The SID ended in 6646 is the Win32WebViewHost Application Container.  I'm not certain what the longer version of this SID belongs to, but I found it present on my test workstation so I added it in as well.  I had to go through and manually enumerate the permissions in these directories so I'm hoping I'm not missing anything.


Like I said, it's possible that this is an entirely different issue than what your users are experiencing but after researching and seeing how little info is online regarding this behavior, I figured I'd throw it out there.

**Comment by atsopuronen** [comment] 2021-05-21 14:50
Hello @DB-ADM 

I'm glad to announce that your instructions worked!! By following them our customer was able to resolve the issue after months of frustration.

Thank you!

**Comment by DB-ADM** [comment] 2021-05-21 16:54
@atsopuronen - Awesome!  I'm happy that I was able to help!

**Comment by atsopuronen** [comment] 2021-05-31 09:50
Hello again,

We had another customer with this issue but the above solution didn't work for them. They found a simple and elegant solution that worked:

1. Remove this folder:
`%userprofile%\AppData\Local\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\`

2. Execute the following Powershell:
`Get-AppxPackage "Microsoft.Win32WebViewHost" | foreach {Add-AppPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`

This recreates the corrupt folder, and now your Office add-in should work.

**Comment by grcsoftware** [comment] 2021-10-25 10:47
Hi all,

We are suddenly getting this issue across our entire estate of Windows 10 Enterprise, Intune managed devices.

Office 365 MSO Version 2109 Build 16.0.14430.20292) 64-bit. Tried the above with no luck unfortunately and not seeing much else on the internet that helps. Any help would be greatly apreciated.

Cheers,

**Comment by atsopuronen** [comment] 2021-10-25 16:53
Hi

We have today received a suspiciously high number of reports of the ADD-IN ERROR from our customers. So far only one user has confirmed their Office version: 16.0.14430.20306.

**Comment by chrisGNTC** [comment] 2021-10-26 01:39
We observed the same issue today. We uninstalled the Microsoft Edge WebView2 Runtime 95.0.1020.30 then the issue was instantly fixed with a relaunch of the Outlook Add-in.

**Comment by chrisGNTC** [comment] 2021-10-26 03:03
> We observed the same issue today. We uninstalled the Microsoft Edge WebView2 Runtime 95.0.1020.30 then the issue was instantly fixed with a relaunch of the Outlook Add-in.

See this thread for updates and workaround. https://github.com/MicrosoftEdge/WebView2Feedback/issues/1860

**Comment by ElizabethSamuel-MSFT** [comment] 2022-08-09 21:27
Closing as there seems to be a workaround. Thanks.

**Closed as completed by ElizabethSamuel-MSFT** 2022-08-09 21:27 UTC
Labels: Area: add-ins platform, Resolution: has workaround
