### ISSUE TITLE
[Excel] different version of excel in Mac in appstore

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#605] opened 2019-07-09 07:52 UTC
hi

our app in windows appstore it's fine. but in mac there's some problem。
1、in the version of 19051201. in appstore search for  "pacvue". can not find.
![image](https://user-images.githubusercontent.com/3963826/60868518-cc9dd780-a25f-11e9-9d6c-055971cfbd37.png)
![image](https://user-images.githubusercontent.com/3963826/60870306-2b188500-a263-11e9-8ca1-486f0fdcc648.png)

2、in the version of 19060901. no store in excel addins.
![image](https://user-images.githubusercontent.com/3963826/60868683-1c7c9e80-a260-11e9-82cd-482ff3602634.png)
![image](https://user-images.githubusercontent.com/3963826/60868789-4df56a00-a260-11e9-863b-1dbecfa63f14.png)

**Comment by grangeryy** [comment] 2019-07-10 07:44
We've tried the scenario but can't reproduce the issue. Is this issue stable repro for you? For version 19060901, could you help to verify if it also happens for other apps like Word/Outlook? @dinglicoding

**Comment by dinglicoding** [comment] 2019-07-10 08:16
@grangeryy  thanks

you can not reporduce the issue. it means for version 19060901 in office add-ins by mac have store category? 

i don't know why in mac office add-in and store category can't find our add-ins ( pacvue ).but in web of office add-in it's fine.

could you help to verify if it also happens for other apps like Word/Outlook?
sorry our add-ins only support for excel.

**Comment by grangeryy** [comment] 2019-07-10 09:13
Thanks @dinglicoding for the quick answers. 

- For the first bullet issue, we tried the version of 19051201 and successfully find the "pacvue". 
![image](https://user-images.githubusercontent.com/50093161/60954668-f4f60680-a331-11e9-9c76-c1545d455381.png)

- For the second bullet issue, I've tried a new machine with 19060901 and I can reproduce your issue. Seems in 19060901, store is not available for all apps, not only Excel but also including word and outlook. I've created a bug to the store team for this problem:  internal 3481213

**Comment by dinglicoding** [comment] 2019-07-10 09:30
Thanks @grangeryy  for your reply.

the version of 19051201 in mac  our excel language is chinese . Is it relevant?

**Comment by grangeryy** [comment] 2019-07-15 05:40
@dinglicoding I tried in English version but still reproduce the same issue. So might not be language related:)

**Comment by niteshgolchha85** [comment] 2019-07-29 21:43
@grangeryy/ @dinglicoding  Apologies for the confusion. I wrongly marked this Github issues as 'fix-pending'. Please continue your investigation

**Comment by grangeryy** [comment] 2021-03-16 03:59
@dinglicoding does this issue still repro for you?

**Comment by grangeryy** [comment] 2021-03-17 05:28
Currently close this with no repro. Pls reopen when necessary.

**Closed as completed by grangeryy** 2021-03-17 05:28 UTC
Labels: Type: product bug, Status: under investigation, Area: add-ins platform
