### ISSUE TITLE
Add-in failed to install or load custom functions

### ISSUE THREAD

**Issue by VictorJDX** [OfficeDev/office-js#2617] opened 2022-06-07 14:12 UTC
# Excel office add-in failed to load custom functions on the browser (Excel Web) after downloading from the Microsoft store (Production version). The error message showed by Excel Web "_one or more add-ins failed to install or load custom functions. Error installing functions._"

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2204
* Operating System: Windows 10 Enterprise/21H2
* Browser (if using Office on the web): Chrome/102.0.5005.63 (64-bit)
## Expected behavior
After installing the add-in it should load without problems, currently, there's a workaround for this issue, by manually adding the add-in, for this, it is necessary to navigate to "Insert -> Office add-ins-> Selecting the Add-in-> Add" after this the Add-in works normally

## Current behavior
 The add-in should load normally after opening Excel, and not show any error, as this is in production and has already been tested by the Office team

## Steps to reproduce
1. Download the Add-in from the Microsoft store.
2. Open JOA in Excel online (Browser).
3. Go to connections and Add connection.
4. Upload the attached database.
--

## Link to live example(s)
<https://appsource.microsoft.com/en-us/product/office/WA104381848?src=financialservices&tab=Overview -->

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 
![Untitled picture](https://user-images.githubusercontent.com/91121042/172400923-4b49faab-c245-44bf-85e3-ecda5e4c4d4a.png)

**Comment by wh1t3cAt1k** [comment] 2022-06-30 14:49
We're also experiencing a similar issue with Velixo, @gmichaud just installed a production version from the store on Excel for Mac and none of the functions are recognized. We have cleared the Office cache multiple times.

https://appsource.microsoft.com/en-us/product/office/WA200002311?tab=DetailsAndSupport

@grangeryy @peronald @yaweizhu-henson could you describe the root cause / potential impact of the bug? It seems pretty scary 😬

**Comment by gmichaud** [comment] 2022-06-30 14:50
As indicated by @wh1t3cAt1k I am seeing this issue -- occuring on Excel for Mac

**Comment by yaweizhu-henson** [comment] 2022-07-04 03:09
Sorry for late response, I just read the message. I will invole our ENG to see what happened

**Comment by gmichaud** [comment] 2022-07-11 12:39
The problem is gone on my side

**Comment by VictorJDX** [comment] 2022-07-15 13:26
The issue is still appearing for me, when using Excel Web

**Comment by yaweizhu-henson** [comment] 2022-07-26 04:04
Our engineer is still try to investigate what is going wrong here, I will update when there is something new for you

**Comment by JHJ-MS** [comment] 2022-08-05 09:42
Something Update here.

We can repro it using Jedox. We found the CustomFunctions registration failed caused by a 400 invalid argument error. We are actively investigating the root cause. 
![image](https://user-images.githubusercontent.com/94002141/183049572-543095d5-a68b-4a49-99ed-7e051add2eb5.png)

Thanks.

**Comment by wh1t3cAt1k** [comment] 2022-08-15 14:52
@JHJ-MS @yaweizhu-henson good evening guys, any news on this scenario?

**Comment by yongkhor** [comment] 2023-02-28 06:44
Hi @yaweizhu-henson @JHJ-MS, 

We are having the same issue with our Forbury Add-in.
https://appsource.microsoft.com/en-us/product/office/WA200002916?tab=Overview&exp=ubp8

Any further updates on this issue?

Thanks!

**Comment by yaweizhu-henson** [comment] 2023-03-02 09:05
Hi @wh1t3cAt1k @yongkhor-forbury 
We did add this issue to our bug list, but we didn't have the bandwidth to fix that yet.
But we do have a **workaround** method for this issue
Please change your version fron "xx.xx.xx" to "xx.xx.xx.xx", it should solve the issue.

**Comment by donlvMSFT** [comment] 2023-06-15 03:25
I'd like to close this issue due to current status, please raise a new one or reactive if there're further questions. Thanks!

**Closed as completed by donlvMSFT** 2023-06-15 03:25 UTC
Labels: Area: Excel, Type: product bug, Area: custom functions
