### ISSUE TITLE
[Outlook] An extra empty meeting will be generated after save meting. (Mac outlook only)

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1260] opened 2020-07-06 10:40 UTC
When I schedule an meeting on Mac outlook client by add-in. But after I update meeting time and then invite somebody click 'Send' . An empty meeting was generated at the time before update meeting.
In addition, we tried schedule meeting without add-in this problem still reproduce.
But if I only close and save this meeting this problem will not happen.

## Expected Behavior
No extra empty meeting should be generated.

## Current Behavior
When I schedule an meeting on Mac outlook client by add-in. But after I update meeting time and then invite somebody click 'Send' . An empty meeting was generated at the time before update meeting.
In addition, we tried schedule meeting without add-in this problem still reproduce.

## Context
every time update meeting will generate an empty meeting.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac 10.15.5
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number:16.37 (20051002)
* Operating System: Mac 
* Browser (if using Office Online): ______

Any idea?

**Comment by SWei1234** [comment] 2020-07-08 06:20
@exextoc attach an recording here. Hope this will be helpful.

https://bcgdv.egnyte.com/dl/NjDW7oYQOn/

**Comment by exextoc** [comment] 2020-07-08 09:22
Hi @SWei1234 this doesn't seem to be an add-in issue, so we are closing this. We also cannot reproduce the issue on our latest build. We recommend updating to the latest Outlook Mac build and check if it still happens. If it does, you can report the issue through Help -> Send a Bug Report.

**Closed as completed by exextoc** 2020-07-08 09:22 UTC
Labels: Needs: triage :mag:
