### ISSUE TITLE
Word office js search in document body {0;N} behavior difference between Office online and Desktop

### ISSUE THREAD

**Issue by tomprod** [OfficeDev/office-js#2340] opened 2022-01-03 15:44 UTC
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2111 build 14701.20262 / 16 december 2021 
* Operating System: Windows 10
 
## Expected behavior
When searching with document.body.search('A{0;1}', { matchWildcards: true}) should work on both Office Word Online and desktop (especially "zero or more")

## Current behavior
When searching with document.body.search('A{0;1}', { matchWildcards: true}) doesn't work on Office Desktop, throws GeneralException, but the same code works on office word online

## Steps to reproduce

 await Word.run(async (context) => {
    const test = context.document.body.search('#{0;1}', {matchWildcards:true});
    await context.sync();

    console.log(test.items.length);

  });

## Context
Trying to find blocs of text with variable contents, just like i would do with Regex.
Example : #DC{&7=1}@01/01/2021@31/12/2021 
Sometimes the dates part is not present and i need to detect both #DC{&7=1} and #DC{&7=1}@01/01/2021@31/12/2021 

## Useful logs
GeneralException on desktop

**Comment by tomprod** [comment] 2022-01-15 14:10
Hey, any news on this subject ? What i need to do to circumvent this limitation on word desktop is, first detect we're on desktop (because it works on word online), then perform multiple searches for every case, which is not really optimal. Thank you for you help

**Comment by AbidRahman-MSFT** [comment] 2022-01-24 20:23
Hey @tomprod - apologies for the delay in response. Could you provide a sample document that is causing the issue? Does it fail on a blank document as well?

**Comment by tomprod** [comment] 2022-01-24 22:23
Hey, yes it fails on a blank document, only in office word desktop, online works fine.
Just put "#DC{&7=1}@31/12/2020@" in a blank word document, then script lab :


```
async function run() {
  await Word.run(async (context) => {
    const test = context.document.body.search('#{0;1}', {matchWildcards:true});
    test.load(['text', 'parentContentControlOrNullObject']);
    await context.sync();


    console.log(test.items.length);

    await context.sync();
  });
}
```


output in console : 

[ERROR]: Error:
{
    "stack": "RichApi.Error: GeneralException\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:242451)\n    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:306195)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:304300",
    "message": "GeneralException",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "GeneralException",
        "errorLocation": "",
        "statement": "_Search2.load([\"text\",\"parentContentControlOrNullObject\"]);",
        "surroundingStatements": [
            "var root = context.root;",
            "var body = root.body;",
            "// Instantiate {body}",
            "var _Search2 = body._Search2(...);",
            "// Instantiate {_Search2}",
            "// >>>>>",
            "_Search2.load([\"text\",\"parentContentControlOrNullObject\"]);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}

**Comment by grangeryy** [comment] 2022-01-26 02:13
Hi @tomprod, we've created a bug to track this issue:  BUG 5750743. For the impacted user wise, is it quite common for your customers hitting the issue?

**Comment by tomprod** [comment] 2022-01-26 08:10
Hey @grangeryy, thank you for the follow up. I am developing an addin for office word for a big accounting software editor and the addin cannot work on desktop with that bug : it only works on office word online. So users will not be able to use the addin on desktop which is blocking for them.

**Comment by grangeryy** [comment] 2022-03-31 03:01
@yihuax could you help to take a look at this one, and any suggestion here? Thank you!

**Comment by yihuax-msft** [comment] 2022-03-31 03:37
What are the corresponding UI behaviors in Word Desktop and Word Online? If the UIs behave differently, then, that will be the cause of the different behaviors of our API.

**Comment by jipyua** [comment] 2023-01-29 02:19
@tomprod I tried your scripts also on online, but it's also not working on online. I think this is because your regular expression '#{0;1}' is not valid for two reasons:
1. you should not use ';', but ','.
2. the number should not be started with 0.

so a valid regular expression is '#{1,2}' or '#{1}' based on your requirement.

**Comment by tomprod** [comment] 2023-01-29 11:37
> @tomprod I tried your scripts also on online, but it's also not working on online. I think this is because your regular expression '#{0;1}' is not valid for two reasons:
> 
> 1. you should not use ';', but ','.
> 2. the number should not be started with 0.
> 
> so a valid regular expression is '#{1,2}' or '#{1}' based on your requirement.

I am aware of the , or ; but in my experience, zero or more works online and not on desktop. But its been months i did not try. I think it should be great that zero or more works on desktop and online

**Comment by jipyua** [comment] 2023-02-02 02:12
@tomprod if you tried the word desktop UI search feature, you will find that zero or more is not supported, so this is a designed behavior for word. Feel free to use  '#{1,2}' or '#{1}' based on your requirement and I think we can close this discussion. Thanks.

![image](https://user-images.githubusercontent.com/22437953/216214025-9b8ed69d-16f8-4451-8296-61c6204ded1b.png)

**Closed as completed** 2023-02-02 08:29 UTC
Labels: Type: product bug, Area: Word, Status: in backlog
