### ISSUE TITLE
[Word Online] Looping when using DocumentSelectionChanged handler and  return context.sync().then(function () 

### ISSUE THREAD

**Issue by azmatzuberi** [OfficeDev/office-js#477] opened 2019-04-13 00:47 UTC
## Expected Behavior

Using DocumentSelectionChanged handler with return context.sync().then a user could type in Word online and have the contents of the document received in the code for MS Word.

## Current Behavior

What is happening now is that when a user types, the context.sync goes into an unending loop.
## Steps to Reproduce, or Live Example
In the index.js file add this code:

```
function getHTMLcontent() { 
         // Run a batch operation against the Word object model.
        Word.run(function (context) {

            // Create a proxy object for the document body.
            var body = context.document.body;

            // Queue a commmand to get the HTML contents of the body.
            var bodyHTML = body.getHtml();

            // Synchronize the document state by executing the queued commands,
            // and return a promise to indicate task completion.
            return context.sync().then(function () {              
                html = bodyHTML.value;
                console.log("Body HTML contents: " + html);
            });
        })
    return html;
} 
```

Then add this event handler in the intializer:
```
Office.initialize = (reason) => {
    $('#sideload-msg').hide();
    $('#app-body').show();
    var doc = Office.context.document;
    doc.addHandlerAsync(Office.EventType.DocumentSelectionChanged, function(eventArgs) 
   {
        getHTMLcontent();
    };
}
```
Host the add-in in Word online and start typing something and you'll see it goes into an auto loop.

## Context
This has prevented me from creating my add in for Word because of this looping. I'm extracting keywords from the text as the user is typing and am displaying them in the add-in. Note: This code works perfectly fine with OneNote.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: MacOS______
* Host [Excel, Word, PowerPoint, etc.]: Word Online______
* Office version number: _16.0.11610.32651_____
* Operating System: MacOS______
* Browser (if using Office Online): Latest Chrome______

**Comment by Rick-Kirkham** [comment] 2019-04-13 01:32
I find that the handler runs every time the user types a letter, but it doesn't go into an infinite loop.

**Comment by azmatzuberi** [comment] 2019-04-13 02:11
Are you using yo office for node?

**Comment by azmatzuberi** [comment] 2019-04-13 03:54
i've been testing this and so far it seems to be a valid issue

**Comment by Rick-Kirkham** [comment] 2019-04-15 00:42
I was testing in Script Lab. Can you try that and see if the problem is reproduced?

**Comment by azmatzuberi** [comment] 2019-04-15 01:31
`doc.addHandlerAsync(Office.EventType.DocumentSelectionChanged)` doesn't work in Script Lab. You can start a new node project and test. I've tested it on two different systems, and the result is the same: endless loop

**Comment by Rick-Kirkham** [comment] 2019-04-15 12:49
It works for me in Script Lab.

**Comment by JuaneloJuanelo** [comment] 2019-04-19 16:33
@azmatzuberi  thanks so much for reporting this i was able to repro.

@Rick-Kirkham Did you tried the code in Word Online? i think its in that platform where @azmatzuberi  is experiencing the issue, according to his description.  Here is a Script lab gist you can try https://gist.github.com/JuaneloJuanelo/89525d7ab82449db9478fa45a2ef79f8

that been said i created a bug for this. This event should only be triggered when a user makes a selection in the document, although its probably a side effect of auto saving in Word ONline.

We are tracking internally with bug 3304972, assinged to @weshi

**Comment by Rick-Kirkham** [comment] 2019-04-19 19:49
@JuaneloJuanelo Yes, I was testing it in Word Online. Maybe I'm misunderstanding the issue. I did find that the event ran (once) every time the user types a letter. I *thought* that @azmatzuberi was saying that if the user types a letter (once), then the event runs over-and-over again, endlessly. I was not able reproduce an endless loop.

**Comment by JuaneloJuanelo** [comment] 2019-04-24 17:45
@Rick-Kirkham  ok, i was able to repro and created a bug. thanks!!

**Comment by azmatzuberi** [comment] 2019-05-06 15:55
@JuaneloJuanelo Any timeframe on the bug fix?

**Comment by azmatzuberi** [comment] 2019-06-20 18:03
@weshi Any time frame for this bug fix?

**Comment by JuaneloJuanelo** [comment] 2019-07-12 16:21
The issue was fixed recently and on its way to  be rolled out to production in the next days.

**Comment by JuaneloJuanelo** [comment] 2019-07-25 19:28
@azmatzuberi : the fix seems to be live now.. please confirm...

**Comment by kbrandl** [comment] 2019-09-02 21:33
@azmatzuberi can you please confirm whether this issue has been resolved, now that the fix has been deployed? Thanks!

**Comment by azmatzuberi** [comment] 2019-09-04 02:56
Yes, I believe it has been fixed

**Closed as completed** 2019-09-04 05:34 UTC
Labels: Type: product bug, Area: Word, Status: fixed

**Comment by SirDavenport** [comment] 2024-01-18 01:01
Hey I hate to start up an old thread, but I am getting a ton of DocumentSelectionChange events in Office Online when coauthoring. Was there a regression on this?
