### ISSUE TITLE
Can't Toggle State of Checkbox Content Controls (WOPI)

### ISSUE THREAD

**Issue by aeturneus** [OfficeDev/office-js#4659] opened 2024-07-09 13:32 UTC
Checkbox content controls do not always work in Word Online in WOPI environment. Checkbox content controls should toggle state when clicked by user, but this does not always work in the WOPI editing environment. Some content controls are locked and will not change state. This persists even when the document template is edited to replace the content controls with new controls, and even though the controls work correctly in desktop Word.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Build 20240705.4
* Operating System: MacOS
* Browser (if using Office on the web): Chrome
 
## Expected behavior
The content control checkbox should check or un-check when clicked on by the user.

## Current behavior
The content control does not change when it is checked.

## Steps to reproduce
1. Open example document in Word online
2. Try to click any of the checkboxes in paragraph 2. The checkboxes will not change state.
3. Compare to the checkboxes in paragraph 3. These checkboxes work and will change state.
[Notice of Family Claim(2024-07-09).docx](https://github.com/user-attachments/files/16143953/Notice.of.Family.Claim.2024-07-09.docx)
![image](https://github.com/OfficeDev/office-js/assets/877362/e43e815e-cefd-4d03-840d-b654f8fb732b)

## Context
This significantly degrades the user experience when editing documents in Word Online. Users are forced to open the document in Desktop Word in order to complete their workflows.

## Useful logs

- [ ] Console errors
- [ x] Screenshots
- [ x] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by sergiosagu** [comment] 2024-07-22 13:20
@aeturneus - Could you share some more details about the process how such a document is typically created? Is it entirely done from scratch from Word Desktop? Using templates? Any other details around it that you think could be handy.

I managed to reproduce the issue with your document. Also, I managed to "fix" the problematic checkboxes in the document by opening it with Word Desktop (I'm on Windows 11, latest Word version), checking/unchecking some checkboxes and saving back the document. Then, when I open it in Word Web, all checkboxes work as expected. It's not the actual fix but maybe you could use it as a temporary workaround, if needed. I attach my version of the document for you to check it, if you wish.

From the ongoing troubleshooting, I've just observed that in your original document, the problematic checkboxes have some extra elements/attributes in their internal XML representation, whereas the ones that work just fine do not have it. And when I open and save the document via Word Desktop, those extra elements/attributes, which seem redundant, disappear and all checkboxes work. In any case, I'll continue with the RCA and try to find a solution.

[Notice.of.Family.Claim.2024-07-09 - web.docx](https://github.com/user-attachments/files/16333750/Notice.of.Family.Claim.2024-07-09.-.web.docx)

**Comment by aeturneus** [comment] 2024-07-22 18:47
@sergiosagu hey, thanks for the response. The document is generated from a template using our template engine, a version of easy-template-x. It's unclear to us where in the process the additional attributes are being added or why they break the functionality in Word Online but are removed in desktop. Hopefully there is a solution to the underlying issue, but in the meantime we'll continue to investigate.

**Comment by sergiosagu** [comment] 2024-07-24 12:34
@aeturneus - No problem! Something else I've found, In that document, the problematic checkboxes, are stored as "checked" but the symbol that they display is the "unchecked" one. See the following screenshot (I also circled that extra element that other checkboxes do not have, in case it helps with the troubleshooting):

![Screenshot 2024-07-24 144658](https://github.com/user-attachments/assets/8944a367-0b7e-44d2-9c4f-82c0835585f2)

Whereas the checkboxes that simply work are stored as "unchecked" (as expected) and they symbol that they display is the "unchecked" one (as expected as well). See this other screenshot:

![Screenshot 2024-07-24 145113](https://github.com/user-attachments/assets/ab0054c3-7bdc-480b-baef-4b5316b26e53)

Quick question: the document that you shared, is it the one directly generated from that template that you mentioned? Or it was already opened (and maybe saved) using Word Desktop or Word Web?

In any case, both Word Desktop and Word Web (when the document starts "working") handle the check/uncheck of those checkboxes in the same way (if checked and unchecked), but be careful on your side with those cases if you rely on the internal state of the checkboxes (which is checked) instead of their visual representation (which is unchecked).

**Comment by aeturneus** [comment] 2024-07-24 13:48
@sergiosagu the document I shared would have been generated, then opened in Word Web (WOPI) and saved, and then downloaded from there. Possibly the issue occurs in WOPI environment?

**Comment by sergiosagu** [comment] 2024-07-24 14:16
@aeturneus - I don't know how your template engine works, so it's hard to say where the problem is triggered. What we've seen so far, at least around checkboxes, is that the behavior in Desktop and in Web is always equivalent, but I'll be doing some more tests. Could you share the document that it's generated from the template engine before opening/saving first? In that way we could discard any Word Web initial problem, if any.

**Comment by aeturneus** [comment] 2024-07-24 14:22
@sergiosagu here's the document straight from the template engine
[Notice of Family Claim(2024-07-24).docx](https://github.com/user-attachments/files/16363493/Notice.of.Family.Claim.2024-07-24.docx)

**Comment by sergiosagu** [comment] 2024-08-09 07:12
@aeturneus - We've found the problem and a potential fix is already in review.

The problem is that in those unresponsive checkboxes their paragraphs contain extra empty [run elements](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.linq.w.r?view=openxml-3.0.1) (without any text) like the ones mentioned in the comment above: https://github.com/OfficeDev/office-js/issues/4659#issuecomment-2247801900

I don't know how much you can control the template engine that you are using for cases like this, but if you want to do some tests or you can tweak the generation somehow, you may try removing or not generating such empty runs.

Word Desktop directly seems to completely ignore those empty runs, but Word Web, despite of ignoring them as well, was marking those paragraphs as "potentially problematic" and that was causing later on the checkboxes there to be unresponsive.

**Comment by sergiosagu** [comment] 2024-08-12 11:59
The fix has been submitted, and in few days it should reach production.

**Closed as completed by sergiosagu** 2024-08-12 11:59 UTC
Labels: Needs: attention :wave:, Area: Word

**Comment by aeturneus** [comment] 2024-08-17 20:31
@sergiosagu the fix works for some of the problem checkboxes, thanks

However, other checkboxes do not work and now throw an error ("Word experienced a problem") when clicked. This appears to be the case for any checkboxes that are in a paragraph that has numbering styles applied to it (see screenshot) 
![image](https://github.com/user-attachments/assets/419502e5-7b8c-4a1c-8329-0eb95650f724)

**Comment by sergiosagu** [comment] 2024-08-19 07:24
Thanks for the feedback!
This issue with the formatted lists has the same effect but probably it's something else (thus the error). We'll take a look at it.

**Comment by sergiosagu** [comment] 2024-08-19 08:52
@aeturneus - I can confirm that the reason for the issue was slightly different (despite of having the same visible effect). I've started working on a potential fix and now all the checkboxes from the generated document that you attached before are working as expected. But I think that your last screenshot is from a different document, isn't it? If so, could you attach that new document as well to validate that all checkboxes are actually working as expected? Thanks!

**Comment by aeturneus** [comment] 2024-08-19 16:25
@sergiosagu in the form previously provided, checkboxes with numbering styles (causing the issue described above) can be seen on page 5 and later

**Comment by aeturneus** [comment] 2024-08-31 23:56
@sergiosagu can we expect a fix for this soon? Thanks for your help with the partial fix so far!

**Comment by aeturneus** [comment] 2024-09-01 00:00
@sergiosagu the current behaviour is that the circled checkboxes in the sample document provided cannot be checked - they don't crash Word Online anymore, but they don't display as checked. 
![image](https://github.com/user-attachments/assets/7b8c13f6-97d8-4333-9a8d-34695a59b245)

**Comment by sergiosagu** [comment] 2024-09-03 08:10
@aeturneus - The fix update is already being rolled out, it should reach prod anytime these days. I'll be able to double check it and confirm it next week after my time off. Thanks for your understanding!

**Comment by aeturneus** [comment] 2024-09-06 13:06
@sergiosagu appears to be fully resolved now! Thanks.
