### ISSUE TITLE
Office.context.ui.displayDialogAsync "flash" dialog with onsend, but works if send is done from a popout window

### ISSUE THREAD

**Issue by ab1osborne** [OfficeDev/office-js#2431] opened 2022-02-16 03:47 UTC
This Addin has been working for a long time and now suddenly stopped. It is an onsend addin that presents a dialogue for message classification.

What happens now is the dialog window simply flashes and the email is not sent.

When the same email is composed and sent from a popout, it works correctly.

Here is a video of the issue  https://pecdm3.preemptive.com.au/owa/owa-issue.mp4

This happens on Chrome, Firefox, Edge and Safari

I believe the problem is in this section of code:
{
**Office.context.ui.displayDialogAsync('https://our-form-would-go-here-removed-for-this-example.html', {
                width: percentWidth,
                height: percentHeight,
		promptBeforeOpen: true,
                displayInIframe: true
            },**
            function(asyncResult) {
                dialog = asyncResult.value;
                dialog.addEventHandler(Office.EventType.DialogEventReceived, processMessage2);
                dialog.addEventHandler(Office.EventType.DialogMessageReceived, processMessage2);
            });
    }

Please private message me and I can send you a manifest

**Comment by stefanoslig** [comment] 2022-02-16 16:29
We have exactly the same issue. A lot of customers are affected. Could you let us know if you're going to work on this?  Is there any workaround in meantime?

**Comment by rickgoud** [comment] 2022-02-16 17:00
Indeed this is a very bug suddenly appearing, so must be after some MS changes. Can you please give this high prio @exextoc as this makes sending normal messages almost impossible?!

**Comment by neville-jones** [comment] 2022-02-16 20:44
Observed with our customers too, since approximately the weekend just gone.

We have found a workaround is to set the OnSendAddinsEnabled to **false** in the users' OwaMailboxPolicy which somehow seems related to changes in this setting as mentioned at end of #1484

**Comment by ab1osborne** [comment] 2022-02-16 22:00
The other interesting 'feature' we've found is the onSendEvent can fire up to three times when the send button is pressed. All activations call the Office.context.ui.displayDialogAsync function, but only one dialogue will appear, but if we change the 

promptBeforeOpen: false,
displayInIframe: false

You might see up to three dialogues appear ! Something very odd is going on.

**Comment by robino2020** [comment] 2022-02-17 08:29
Do we know when this change was introduced?

**Comment by exextoc** [comment] 2022-02-17 12:11
@ab1osborne can you send the manifest at: admin@M365x338999.onmicrosoft.com.

**Comment by exextoc** [comment] 2022-02-17 13:02
We are able to reproduce the issue and are working on a fix on a priority basis. We will patch the fix to production in a short time.

Meanwhile, as a workaround please try any of these:
1. Pop-out the window before send.
2. Disable the onSend policy

**Comment by Marcel-Balk** [comment] 2022-02-17 14:37
Or disable Reading Pane and then it is fixed to! 
To disable for all users: Get-Mailbox -ResultSize unlimited -RecipientTypeDetails UserMailbox | Set-MailboxMessageConfiguration -GlobalReadingPanePosition Off

**Comment by exextoc** [comment] 2022-02-18 07:02
The fix for this is live. Please let us know if you are still facing any issues.

**Comment by mbalk-ram** [comment] 2022-02-18 08:11
At this moment we stil see problems with customers on our end using the plugin Zivver.

**Closed as completed** 2022-02-21 04:38 UTC
Labels: Status: fixed
