### ISSUE TITLE
ConversationId is 'null' in new OWA even on reply

### ISSUE THREAD

**Issue by mpetro-t** [OfficeDev/office-js#636] opened 2019-07-24 20:22 UTC
Office.context.mailbox.item.conversationId is returning null all the time in new Outlook UI for web. It works properly in Outlook for Desktop and it was working propertly in old OWA.

## Expected Behavior
To retrieve id of conversation that message is part of.

## Current Behavior
Property (Office.context.mailbox.item.conversationId) returns null even if it is a part of conversation.

## Steps to Reproduce, or Live Example
1. Click reply on existing message in new OWA
![image](https://user-images.githubusercontent.com/53277298/61825169-c72eb880-ae2d-11e9-9e6a-b5b0de97e074.png)

2. Run office addin which will make a call Office.context.mailbox.item.conversationId

![image](https://user-images.githubusercontent.com/53277298/61825403-520fb300-ae2e-11e9-8515-1e50eee3cb2c.png)

3. Property returns null

All of this is working properly in Outlook for Windows (Desktop) and it was working ok in old OWA.

1. Reply

![image](https://user-images.githubusercontent.com/53277298/61825555-9a2ed580-ae2e-11e9-9936-8071c18f9059.png)

2. Run addin which will call  Office.context.mailbox.item.conversationId
3. Correct conversation id is returned.

![image](https://user-images.githubusercontent.com/53277298/61825713-e9750600-ae2e-11e9-8869-cc7d4128fb09.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Outlook Online (New UI)
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
- [ x ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment] 2019-07-25 09:02
[Updated comment]
Thanks @mpetro-t for reporting this issue. We are looking into this.

**Comment by exextoc** [comment] 2019-07-25 09:18
@mpetro-t We are unable to repro this issue. What outlook account you are using? What does this return for you? 

console.log(Office.context.mailbox.userProfile.accountType);

**Comment by mpetro-t** [comment] 2019-07-25 12:30
I am able to reproduce issue for all O365 accounts that I have. Please note steps:

1. Click on existing email in your inbox
2. Click on Reply
3. Now we are in Compose (Reply) mode. Try to get conversationId.
4. Null is returned

Repeating exact same steps in Outlook for Windows desktop client returns correct conversationId.

Here is the code:
![image](https://user-images.githubusercontent.com/53277298/61874310-17515d80-aeb6-11e9-8a6b-78a6ea8115ce.png)

And here is what it logs in new OWA:

![image](https://user-images.githubusercontent.com/53277298/61874347-2cc68780-aeb6-11e9-85e9-0ee0d9da4508.png)

And here is what it logs in Outlook Windows Desktop client:

![image](https://user-images.githubusercontent.com/53277298/61874451-65fef780-aeb6-11e9-98a2-790728d61c57.png)

And another note. If you run attached code in Read mode (not compose) correct conversationId will be returned. It just doesn't work in compose (while replying).

**Comment by exextoc** [comment] 2019-07-29 10:12
Thanks for reporting this issue. It has been put on our backlog. We, unfortunately, have no timelines to share at this point. As a workaround, you can try inline compose instead of pop out compose view to get conversationId.

**Comment by AnjanaValsan** [comment] 2019-08-02 10:24
This bug is resolved and the fix will be rolled out to Production in a week's time.

**Comment by exextoc** [comment] 2019-08-19 17:09
Making a note here: the referenced issue @mpetro-t opened is likely due to the same root cause.

**Comment by mpetro-t** [comment] 2019-08-19 17:22
Yes, this behavior is observed while Forwarding email too.

p.s. It seems that reading conversation Id is now ok while replying.

**Comment by kbrandl** [comment] 2019-08-28 20:53
@AnjanaValsan if the fix for this issue has been deployed, can you please comment here, update the label (status: fixed) and close the issue? Thanks!

**Comment by exextoc** [comment] 2019-08-29 04:17
This issue has been Fixed so closing it.

**Closed as completed by exextoc** 2019-08-29 04:17 UTC
Labels: Area: Outlook, Type: product bug, Status: fixed
