### ISSUE TITLE
Excel Add-in not loading after manifest update in Windows desktop

### ISSUE THREAD

**Issue by jag-cloudextend** [OfficeDev/office-js#4435] opened 2024-05-10 06:00 UTC
# Provide the required information needed to triage your issue
We are facing an issue loading the add-in on the Windows desktop from the Store after we deployed a manifest change.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.17425.20176 
* Operating System: Windows
 
## Expected behavior
The Add-in should load without any issues

## Current behavior
Its giving `We can't load this add-in because we couldn't connect to the catalog`

## Steps to reproduce

We have an email conversation going on with the team regarding Engagement Created: 107169. Please refer to it for details about the add-in

# Provide additional details

We have tried to get developer logs and this is what we see in the logs
<img width="1123" alt="image (1)" src="https://github.com/OfficeDev/office-js/assets/12657943/f8a8b954-babe-4608-b0d4-572d9be87047">
When tried to load the add-in we are seeing this screen
<img width="445" alt="image" src="https://github.com/OfficeDev/office-js/assets/12657943/d23bbc7f-84a8-4a0e-a60a-22aa2036c188">

We tried to side load the addins and here are the results
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/jagapathi/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/jagapathi/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

Approach | Result
-- | --
install   from store | Failed
Side   loaded same addin | Successful
Side   loaded manifest downloaded from store | Successful
Deployed   store app from admin managed center | Successful

</body>

</html>

**Comment by shanshanzheng-dev** [comment] 2024-05-10 07:26
Hi @jag-cloudextend Thank you for reaching out this issue. We are aware of this issue and are investigating root cause. Will update when we have any process. Thanks.

**Comment by shanshanzheng-dev** [comment] 2024-05-14 10:26
Hi @jag-cloudextend, We have fixed the bug and the fix should be available later. We'll close this issue. Thanks.

**Closed as completed by shanshanzheng-dev** 2024-05-14 10:26 UTC
Labels: Needs: attention :wave:, Area: Excel
