### ISSUE TITLE
Office.context.document.getFileAsync: Unable to get property 'Compressed'

### ISSUE THREAD

**Issue by runerback** [OfficeDev/office-js#2117] opened 2021-09-13 07:23 UTC
I want to read content of local xlsx file loaded in Excel 2013 with `Office.context.document.getFileAsync` api, but got following error:
> TypeError: Unable to get property 'Compressed' of undefined or null reference

## Your Environment

* Platform: PC
* Host: Excel
* Office version number: 15.0.4569.1504
* Operating System: Microsoft Windows 10 64bit
* Browser (if using Office on the web): None (or embedded IE11)
 
## Expected behavior

Read content of current loaded xlsx file

## Current behavior

Error: `TypeError: Unable to get property 'Compressed' of undefined or null reference`

## Steps to reproduce

1. after `Office.initialize`
2.
```typescript
Logger.info("Office.context.document.getFileAsync");
try {
  Office.context.document.getFileAsync(
    Office.FileType.Compressed,
    {
      sliceSize: 100,
    },
    (result) => {
      if (result.status == Office.AsyncResultStatus.Failed) {
        Logger.warn("[getFileAsync] Action failed. Error: " + result.error.message);
      } else {
        Logger.info("[getFileAsync] Action succeed: " + result.value.size);
      }
    }
  );
} catch (error) {
  Logger.error("Office.context.document.getFileAsync: " + error);
}
```
3. Logging
```
[error] Office.context.document.getFileAsync: TypeError: Unable to get property 'Compressed' of undefined or null reference
```

## Link to live example(s)

None

# Provide additional details

React project created by `Yo office`.
`Office.js` version: [https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js](https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js)

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shaowan-msft** [comment] 2021-10-13 03:05
Hi @runerback , thanks for reporting the issue. Excel 2013 does not support CompressedFile is by design.
For more details, you can refer https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/office-add-in-requirement-sets#compressedfile
![image](https://user-images.githubusercontent.com/76982368/137062368-5f7badf9-1dbd-4a39-b7dc-4ffceff8f424.png)

**Comment by donlvMSFT** [comment] 2022-11-17 03:18
Thanks for the discussion, I'd like to close this thread as the thread is answered.

**Closed as completed by donlvMSFT** 2022-11-17 03:18 UTC
Labels: Area: Excel, Type: programming question, Area: add-ins platform
