### ISSUE TITLE
Administrator managed Office-Add-Ins are not deployed in Word

### ISSUE THREAD

**Issue by PRIVERA-IT** [OfficeDev/office-js#2067] opened 2021-08-20 07:36 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Laptop HP ELITEBOOK 830 G5
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Version 2002 (Build 12527.21966 Click-and-go) Semi-annual enterprise channel
* Operating System: Windows 10 Version 1909 (Build 18363.1679)
* Browser (if using Office on the web): ______
 
## Expected behavior

When users go to the dialog Office-Add-Ins in Word and click to "Administrator managed", they could expect to see the list of company-wide deployed add-ins.

## Current behavior

Actually about four of over four hundred users don't receive company-wide deployed Word add-ins. Not one is displayed under "Administrator managed".

## Steps to reproduce

These users can reproduce the problem every time when they
1. start Word
2. select the "Insert" menu ribbon
3. select "My Add-Ins" from Add-Ins
4. click on "Administrator managed"

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 

![image004](https://user-images.githubusercontent.com/81476401/130197616-04964179-8bd3-4b1b-b8d9-88e3a3e6ae30.png)
![image001](https://user-images.githubusercontent.com/81476401/130197629-eb04a15f-1f81-4544-a331-54a9570423aa.png)

**Comment by Rick-Kirkham** [comment] 2021-08-20 20:52
Bhavin, can you take a look at this?

**Comment by keyur32** [comment] 2021-08-25 20:19
Hi there, thank you for the report. We're following up internally on this issue. Thanks.

**Comment by MartinSSeifert** [comment] 2021-09-01 09:07
@AkhileshShah-MS can you share any progress you have made so far? The customer is not seeing any activity - and that is a bit worrying. Looking forward to any feedback you would be able to share with us. Thank you.

**Comment by AkhileshShah-MS** [comment] 2021-09-01 11:50
Hello! 
Is this limited to Win32 Word client or happening for other platforms as well? Also, do the affected users have a mailbox assigned to them? 

For debugging further, could you please email your tenant ID, fiddler trace of when affected user refreshes admin managed tab to addin-help@outlook.com? 

Thanks!

**Comment by exextoc** [comment] 2021-09-23 14:38
@MartinSSeifert Gentle ping to provide the above (requested by AkhileshShah-MS) information. Thanks.

**Comment by MartinSSeifert** [comment] 2021-09-23 18:53
@exextoc thx. for the ping - I will ping the customer asking them to deliver the evidence you are looking for. Do you have an official guide or instructions sheet on how to collect the artifacts you described (especially the steps to produce the fiddler trace)?

**Comment by PRIVERA-IT** [comment] 2021-09-24 15:36
Hi AkhileshShah-MS

We are working with the 32-bit version of Microsoft Apps for Enterprise. We have installed around 500 clients with this version, but only a few are suffering with this problem. The fiddler trace I will supply later. Do you know, if fiddler requires local admin rights to install? If yes, we have to install it through our outsourcing partner. That takes a few days.

Regards

**Comment by exextoc** [comment] 2021-09-30 05:35
Local admin rights are not required to install fiddler. 
You can just install fiddler, start fiddler, open word, go the admin managed tab, close fiddler 
Along with fiddler send us the tenant domain and affected user.
Is this limited to word only or other apps are also not receiving any addins?

**Send those logs to addin-help@outlook.com**

**Comment by exextoc** [comment] 2021-10-18 10:06
Can we have some updates on the requested logs? If the issue is no longer reproducing then we will close the issue.

**Comment by AkhileshShah-MS** [comment] 2022-04-12 07:51
Closing this issue due to no updates for long time

**Closed as completed by AkhileshShah-MS** 2022-04-12 07:51 UTC
Labels: Type: product bug, Area: Centralized Deployment
