### ISSUE TITLE
getting blank model-popup instead of browser tab when we click on any hyper links on Task pane

### ISSUE THREAD

**Issue by kumarsai** [OfficeDev/office-js#516] opened 2019-05-16 15:12 UTC
## We are getting blank model-popup instead of browser tab when we click on download links on Task pane. And for hyper links also model popup does not have 'maximize/minimize ' options in latest version of Office/OS versions.

It was working fine in 18XXX build version of Office/OS

## Current Behavior
Here is the [link](https://microsoft-my.sharepoint.com/:i:/p/v-saarro/EcVsZybQgG5Cty20vucCxQcBGA4tInFATxyJrDCmSkBZCg?e=4QsSAA) for screen shot of issue 

@jargil : As we discussed created new post can you please look into this.
## Here is the version information where we are facing this issue:

https://i.stack.imgur.com/ks7Qp.jpg
https://i.stack.imgur.com/RHcDT.jpg

**Comment by kumarsai** [comment] 2019-05-21 13:05
@jargil : we did some analysis on this issues here are some points we observed.
1. if we use  below code ("while forcing to open link on edge") its working fine as expected.
  ` window.open("microsoft-edge:"+window.location.origin + "/test.xlsm", 'Download');  ` 
2. Created windows forms app and used webBrowser to load our site, it is also working as expected.

Can you please suggest whether using option 1 is recommended or not.

**Comment by jargil** [comment] 2019-06-06 22:20
@kumarsai - thanks.

Adding a link to the issue where this was initially reported as it contains links to repro steps:
https://github.com/OfficeDev/office-js/issues/483

**Comment by jargil** [comment] 2019-07-26 23:50
@kumarsai - links (_blank, or window.open) in the same domain open in the dialog you're seeing, this is by design with Edge WebView.
What you proposed seems ok, just make sure you call with that protocol on Windows only (you can check the user agent).

**Comment by jargil** [comment] 2019-08-05 21:54
Closing as the behavior is expected given the type of url being opened.

**Closed as completed by jargil** 2019-08-05 21:54 UTC
Labels: Area: Edge WebView
