### ISSUE TITLE
Single Sign-on in Word stopped working for latest builds from 1808

### ISSUE THREAD

**Issue by RickVanRousselt** [OfficeDev/office-js#355] opened 2019-01-04 07:44 UTC
Hi,

I implemented Single Sign-on in Word following these instructions (https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)

This is working perfectly with the current Semi-Annual channel ( Version 1803 Build 9126.2336)

But when I switch to the targeted release channel (Version 1808 Build10730.20205 or Build10730.20262)
I'm getting the following error: 
    code: 13012
    message: "API is not supported in this platform."
    name: "A connection was lost during the sign in process."

The code I execute to receive this is:
    Office.context.auth.getAccessTokenAsync(({ forceConsent: true }),
            function (result) {
                if (result.status === "succeeded") { }
This of course gives a result with the error back

I also check first if the Identity API is supported by the following code:
  if (!Office.context.requirements.isSetSupported("IdentityAPI")) {}
But this doesn't execute so it states that the IdentityAPI is supported.

When I change tot the monthly builds (Version 1812 Build 11126.20188) then it does work again.

## Steps to Reproduce, or Live Example
1. Setup single sign-on like described here: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins
2. Switch from current SEC to SECT

## Environment
Environment: 
Windows 10 64bit version 1709 (OS Build 16299.846)
Office version: 1803 (build 9126.2315); 1808 (build 10730.20.205)

**Comment by kbrandl** [comment] 2019-01-05 00:32
@RickVanRousselt thanks for reaching out and sorry to hear that you've run into this problem.

@JuaneloJuanelo are you able to provide any feedback about this issue?

**Comment by Rick-Kirkham** [comment] 2019-01-05 01:14
@niteshgolchha85 This is probably better directed to you than Juan.

**Comment by niteshgolchha85** [comment] 2019-01-08 02:56
Since this feature is not GA yet so there could be some issue with the flighting service. Can you restart your office application and try again?

**Comment by RickVanRousselt** [comment] 2019-01-08 15:17
Did that... Also rebooted my machine, and tried on another user's machine.

**Comment by RickVanRousselt** [comment] 2019-01-08 15:20
Already tried it. Also rebooted my machine. And because I'm running this directly in debug mode from VS is also tried this with another user's machine where the add-in is installed into the tenant

**Comment by RickVanRousselt** [comment] 2019-01-14 11:39
By now this issue has been pushed trough to the Semi-Annual Channel release that went live this month. Version 1808 Build 10730.20264

**Comment by niteshgolchha85** [comment] 2019-01-23 22:56
Sorry it's not working on the expected release channels. We are investigating this issue and will respond as soon as we find something. Our initial guess is that the SSO feature has not been flighted but I'll double check that.

**Comment by niteshgolchha85** [comment] 2019-01-30 02:22
It seems that the flight for SSO has been turned OFF for the semi annual channel. This is by design - supposedly, we do not ship preview features for stable versions, incl perpetual. I'll see if we can document this.

**Comment by niteshgolchha85** [comment] 2019-02-05 01:21
Thank you for bringing this up..
The documentation has been updated with this information now - https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins
Do let me know if you run into this issue for any other build. If not, please close this issue.

**Comment by RickVanRousselt** [comment] 2019-02-06 07:38
Cool, Thanks for the help

**Comment by hatsukiotowa** [comment] 2019-03-20 07:35
I have faced the same issue but with different Office Build. Could you provide help or fix on this, thank you.

Windows: 
Windows Installer Version       5.0.16299.967
OS Details                      Microsoft Windows 10 Pro, SP 0, Version: 10.0.16299, Codepage: 1252, Country Code: 1, Language: 1033, System Type: x64-based PC

Office:
BuildNumber                     16.0.11328.20158
Version                         1902
Platform                        x86

**Comment by kbrandl** [comment] 2019-03-20 13:45
@niteshgolchha85 FYI, an SSO issue with another build of Word. I'll reopen this issue so that you can engage with the customer (@hatsukiotowa).

**Comment by niteshgolchha85** [comment] 2019-03-21 16:39
DIscussed offline and asked to
1. Restart Office and try again
2. Check if the customer is on the Insider channel

**Comment by cyc4** [comment] 2019-03-22 09:17
Thanks @kbrandl and @niteshgolchha85

**Comment by niteshgolchha85** [comment] 2019-04-17 18:33
I'll be closing this issue as there hasn't been any response. Feel free to reopen if the issue persists.

**Comment by tuandomvn** [comment] 2019-05-27 08:37
I have the same issue with Version 1808. Can we reopen this ticket?

**Comment by Rick-Kirkham** [comment] 2019-05-27 17:57
@tuandomvn This is expected. SSO is a preview feature that is turned off in builds that reach the semi-annual channel.

**Comment by sergiubucur** [comment] 2019-09-16 11:53
This issue has reappeared for us in Version 1908 (Build 11929.20300) on the Monthly channel. SSO was working fine in the previous release, Version 1908 (Build 11929.20254).

Calling getAccessTokenAsync() results in error code 13012.

**Comment by sergiubucur** [comment] 2019-09-17 06:34
I can confirm it is working again now. The version is still 1908 (Build 11929.20300).

**Comment by niteshgolchha85** [comment] 2019-09-24 01:30
Closing as the API is working. Feel free to reopen if the issue persists.

**Comment by craigkeating** [comment] 2019-10-03 19:26
I am getting this now with version 1908 (Build 11929.20300). Has worked for months on the previous versions. Please let us know how sergiubucur resolved this issue.

**Comment by craigkeating** [comment] 2019-10-03 19:29
Specifically, calling Office.context.auth.getAccessTokenAsync and getting back 13012 with:
- API is not supported in this platform.
- A connection was lost during the sign in process.

Tried with options forceConsent as false and forceConsent as true.

**Comment by craigkeating** [comment] 2019-10-03 21:00
I just ran this from my Microsoft Surface Laptop with version 1909 (Build 12026.20264) and it worked.  Both using the same code in the App Service.
How can I get the version 1908 (Build 11929.20300) to work?

**Comment by sergiubucur** [comment] 2019-10-04 06:22
@craigkeating I didn't do anything. The API wasn't working one morning and then the next it started working again by itself.

**Comment by craigkeating** [comment] 2019-10-04 22:05
I just tried it now and it still isn't working for me.  Wish it was :o)

**Comment by niteshgolchha85** [comment] 2019-10-17 05:12
@craigkeating Can you go to File->Options->Experiment on you Windows machine and attach a screenshot?

**Comment by craigkeating** [comment] 2019-10-21 21:40
I didn't see Experiment listed in the set of options available in File -> Options from our Microsoft Word.

We did upgrade to version 1910 (build 12130.20184) so we could get unblocked to finish testing and releasing our Office Add-In.

**Comment by niteshgolchha85** [comment] 2019-10-24 20:19
@craigkeating Can you restart your Office application and try again? I suspect this might be an issue with flighting

**Comment by craigkeating** [comment] 2019-10-24 20:44
I have since upgrade Word and can no longer reproduce the issue.

Prior, though, I did try signing out and signing back in to Office. I did also try rebooting. None of these steps resolved the issue.

In case I can find someone still running the older version, what did you mean by restarting office, if that is different than signing out and signing back in.

**Comment by niteshgolchha85** [comment] 2019-11-20 20:29
Restart Office = close all office applications (Eg: Word, Excel, Powerpoint, Outlook, etc) and start again

**Closed as completed** 2020-06-22 22:30 UTC
Labels: Needs: attention :wave:, Type: product bug, Area: Word, Area: add-ins platform, Status: fixed
