### ISSUE TITLE
Custom Functions - help link on edit goes to incorrect COUNT document

### ISSUE THREAD

**Issue by jordandev** [OfficeDev/office-js#2487] opened 2022-03-21 16:21 UTC
When inserting a new custom function using the "Insert Function" dialog there is a "Help on this function" link in the bottom left that takes you to the link as provided by the @helpurl

This works correctly when inserting a new function. However, if you have already inserted a custom function, and you use "Insert Function" to edit that function (click the existing formula cell, then click Insert Function) this help link will instead just go to Microsoft's documentation on the COUNT formula.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2202 (build 14931.20132)
* Operating System: Windows 11
* Browser (if using Office on the web): N/A
 
## Expected behavior
Goes to the provided link in @helpurl

## Current behavior
Goes to documentation on COUNT

## Steps to reproduce

1. insert a custom function
2. click on the cell the function was inserted to
3. click on "Insert Function" ribbon button
4. click on the "Help on this function" link

**Comment by davidchesnut** [comment] 2022-03-21 23:49
Hi @jordandev,

I can't reproduce this behavior using the steps you provided. Is there a specific spot you have to locate the cursor in the function when editing to see this? Is this only occurring for a particular function name?

Thanks!
David

**Comment by davidchesnut** [comment] 2022-03-21 23:52
BTW: to test this I used Script Lab to create a basic custom function and then added the helpurl comment.

```ts
/**
 * Calculates the volume of a sphere.
 * @customfunction
 * @helpurl https://github.com/officedev
 * @param {number} radius
 * @returns The volume of the sphere.
 */
function sphereVolume(radius) {
  return (Math.pow(radius, 3) * 4 * Math.PI) / 3;
}
```

and from insert function dialog box that help url is working (both new cell, and from an existing cell with this function.)

**Comment by OfficeAddins** [comment] 2022-09-15 18:32
**_The Help link is still incorrect when you are editing an existing formula._**

The Help Link works when:
You start with an empty cell. Select **an empty cell** and select the Formulas tab, Insert Function, select your custom function and click on the "Help on this function" link - This works

The Help Link does not work when:
You select a cell that has the custom function already in it. Select **the cell containing your custom function** and select the Formulas tab, Insert Function and click on the "Help on this function" link - This does not work

Could this issue be reopened please

**Comment by davidchesnut** [comment] 2022-09-26 21:15
Hi @OfficeAddins,

Can you provide a small JavaScript sample custom function with a `@helpurl` that causes this behavior? I tried inserting a function into a cell already containing the custom function, and the help link goes to the correct url. Could be the issue occurs based on number of parameters, or some other factor. A sample would help. Also can you provide which version of Excel you are using (if newer than the original information in this thread?) Thanks!

**Comment by OfficeAddins** [comment] 2022-09-27 13:26
Hi David, Thank you for reopening this.

I will put a small sample together and then upload it for reference.
It may take me longer than 3/4 days though to get all the necessary information. I will post back to this thread when finished.
Many Thanks

**Comment by OfficeAddins** [comment] 2022-09-29 17:28
I have uploaded a sample to github and also included a few screenshots.
The manifest didn't seem to work on localhost but when uploaded to https it worked fine.

https://github.com/OfficeAddins/custom-functions

**Comment by davidchesnut** [comment] 2022-09-29 21:10
This is super helpful, thanks! I can repo the problem now. Looks like it has something to do with opening a second document. In the first document when it sideloads it works fine. When I do File New, and create a second document, that's when the issue occurs. Could be this is only something that affects sideloading during development and not when you do store or central deployment. I'll continue looking into this.

**Comment by OfficeAddins** [comment] 2022-09-30 09:49
Thats excellent news 👍 
There are so many different scenarios/possibilities.

**Another Bug I found:**
These URLs only seem to work with https.
Using http-localhost doesn't work (error message is Unexpected Resource - The resource you are trying to use does not exist).

```
<bt:Url id="Functions.Script.Url" DefaultValue="http://localhost:8080/functions-bundle.js"/> 
<bt:Url id="Functions.Page.Url" DefaultValue="http://localhost:8080/functions.html"/> 
<bt:Url id="Functions.Metadata.Url" DefaultValue="http://localhost:8080/functions.json"/> 
```

 although http-localhost does work for this URL.
```
 <DefaultSettings> 
    <SourceLocation DefaultValue="http://localhost:8080/index.html" /> 
 </DefaultSettings> 
```

**Another Bug I found:**
All the page URLs only seem to work with a ".html" file extension and not with a ".htm" file extension.

`<bt:Url id="Functions.Page.Url" DefaultValue="http://localhost:8080/functions.html"/> `

I did try a redirect from a ".html" to a ".htm" but the task pane just hangs.

**Comment by davidchesnut** [comment] 2022-09-30 23:07
In general you should use HTTPS. You can run into issues when just using HTTP. See [hosting requirements](https://learn.microsoft.com/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1#hosting-requirements). If a page isn't loading ("html" vs "htm") I try loading it in a browser directly just to be sure the url is correct. If it loads, then I run a trace like with Fiddler to see if Office is getting an error when it tries to load the page.

I tried central deployment and the bug still occurs. So I will reassign this issue to someone who can investigate more.

**Comment by davidchesnut** [comment] 2022-09-30 23:23
@yaweizhu-henson can you please take a look at this issue? You can follow the repo steps created at https://github.com/OfficeAddins/custom-functions, or you can repro this with yo office as follows:

1. run yo office and build an "Excel Custom Functions using a JavaScript-only Runtime". Use JavaScript as the language.
1. Open functions.js in VS Code.
1. Add `@helpurl https://github.com/officedev` to the **add** function comments so it appears as follows.

```csharp
 * Add two numbers
 * @customfunction
 * @param {number} first First number
 * @param {number} second Second number
 * @helpurl https://github.com/officedev
 * @returns {number} The sum of the two numbers.
```

1. `npm run build`
1. `npm start`
1. When excel starts, choose **File > New  > Blank workbook** (the bug won't occur in the first workbook.)
1. Select **Formulas > Insert Function**
1. Select **Contoso.Add** and select **OK**.
1. In the **Function Arguments** dialog box select **Help on this function**. This opens the correct help url.
1. Enter first and second parameters of 10, then select **ok**. The function will calculate in the cell.
1. Select the cell and then the inline "Fx" button to open the formula editor dialog box.
1. Select **Help on this function**. Now it goes to [COUNT help](https://support.microsoft.com/en-us/office/count-function-a59cd7fc-b623-4d93-87a4-d23bf411294c?ns=excel&version=90&syslcid=1033&uilcid=1033&appver=zxl900&helpid=xlmain11.chm60048&ui=en-us&rs=en-us&ad=us) which is incorrect.

It should still go to help url specified in the function.js comments. But for some reason it does not.
Also tested this with central deployment, and the bug still exists.

**Comment by donlvMSFT** [comment] 2023-06-15 03:31
Does this related to https://github.com/OfficeDev/office-js/issues/3078?

**Comment by OfficeAddins** [comment] 2024-06-18 10:23
I have just tested it again and it seems to have been fixed - on Excel Desktop
Both from side loading and from the Store.
Many thanks

**Closed as completed** 2024-06-27 04:34 UTC
Labels: Needs: attention :wave:, Type: product bug, Needs: author feedback, Area: custom functions, Status: no recent activity
