### ISSUE TITLE
Word: crash when insertContentControl from range with section break

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#2370] opened 2022-01-17 09:21 UTC
# Provide required information needed to triage your issue
We get an error when inserting a contentControl on a range when a non breaking space (or a section break) is in the paragreaph. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 
* Operating System: Ubuntu 
* Browser (if using Office on the web): Chrome

## Current behavior
See this script lab gist https://gist.github.com/JensMadsen/b770f551a266237dd2617f8143ad95e5 with this file 
[InsertContentControlSectionBreakBug.docx](https://github.com/OfficeDev/office-js/files/7880593/InsertContentControlSectionBreakBug.docx)

The first paragraph has a non-breaking space in the beginning. The character code is 32 (decimal) and U+00A0 (hex). 

The script demonstrates that I
1. search for a substring of first paragraph which optionally does not include the NBSP 
2. insert a contentcontrol on the range
3. Crash. Error message:
```
{name: "RichApi.Error", code: "GeneralException", traceMessages: Array[0], innerError: null, debugInfo: Object…}
name: "RichApi.Error"
code: "GeneralException"
traceMessages: Array[0]
innerError: null
debugInfo: Object
code: "GeneralException"
message: "Sorry, something went wrong. Check the OfficeExtension.Error.debugInfo for more information. "
toString: function toString()
errorLocation: "Range.insertContentControl"
statement: "var insertContentControl = v.insertContentControl();"
surroundingStatements: Array[5]
0: "var v = context.root._getObjectByReferenceId("{3b311a99-c7d8-44c8-b8c7-f0486086b880}{67}");"
1: "// >>>>>"
2: "var insertContentControl = v.insertContentControl();"
3: "// <<<<<"
4: "// Instantiate {insertContentControl}"
fullStatements: Array[1]
0: "Please enable config.extendedErrorLogging to see full statements."
httpStatusCode: 500
data: undefined
```

I have tested the same document with the same gist on Windows Desktop. Here the non-breaking whitespace is interpreted as Char code decimal 31 (????), and no crash i seen. However, if I replace the non-breaking character with a continuous section break I get a crash as well 

This could be relevant https://github.com/OfficeDev/office-js/issues/67

Note that other operations such as e.g. `.font.bold = true` (see gidt) on the range return by search do not imply an error. Only `insertContentControl`.!!

**Comment by RuizhiSunMS** [comment] 2022-01-20 03:44
Thank you for reporting this issue!
We reproduced and found it a bug. It has been put into our backlog with an id of 5732037.
We will reply in this issue if the bug was fixed since it's hard to make timeline clear for now.

**Comment by JensMadsen** [comment] 2022-01-20 07:21
@RuizhiSunMS Is there a work around? This is a problem for our users that experience this. I think it happens when users copy from HTML ; so a rather common use case.

**Comment by xiruatms** [comment] 2022-01-24 07:27
@JensMadsen , thanks for reaching us.

My investigation based on the testing document you provided showed that it seemed there're some potential format disruption happened which might caused this issue. 

I edit the content from scratch in a bank document and got the expected result as following:
![image](https://user-images.githubusercontent.com/40648203/150739009-58663fef-75e3-4b92-b28a-47792dafb40c.png)

So I'd like to confirm the following questions with you:

1. Why is there a "OBJ" mark there in your testing document (even on Desktop)? Usually it represented an unsupported object. It might cause unexpected behavior.

2. How did you generated those contents in you testing document?  If I added those contents in a blank document, the result is expected as the screenshot shown.  I'm guessing that there might be some internal format issue with your document. If you can share more information, it might be helpful to see what happened.

**Comment by JensMadsen** [comment] 2022-01-24 08:18
@xiruatms The problems only shows when there is a NBSP in the document. I think this problem could be caused by content controls. My addin inserts content controls. This works fine but I sometimes experience weird behaviour when a user: 1) uses the addin in Word Desktop (i.e. inserts a contentcontrol), 2) opens the document in Word online. 

The addin works flawless if the user only uses Word online or only uses Word Desktop. 

In any case this bug only appears when there is an NBSP

**Comment by xiruatms** [comment] 2022-01-24 09:00
@JensMadsen , thanks for your response.

Can you be more specific about your confirmation on NBSP? How did you verify that?

As I can see from your testing document, there's no such NBSP as you mentioned:
![image](https://user-images.githubusercontent.com/40648203/150751605-088d9a60-55d1-4aa2-b49d-465ba0eea08b.png)

Moreover, if opened the corresponding testing document with OpenXML reader, I noticed that in the beginning of the paragraph, there're some special lines:

<w:r><w:rPr><w:lang w:val="da-DK"/></w:rPr><w:softHyphen/></w:r><w:r w:rsidR="5A9235D5" w:rsidRPr="53A1F9E4"><w:rPr><w:lang w:val="da-DK"/></w:rPr><w:t xml:space="preserve"> </w:t></w:r>

Can you confirm how you generate this testing document? Those upper codes caused issues when parsing the document.

**Comment by JensMadsen** [comment] 2022-02-03 21:28
hi @xiruatms . Sorry about the delayed response. The error happened to me when inserting HTML  into Word online and then inserted contentcontrols. The NBSP does not show in Word Desktop. 

I have bad experiences with contentcontrols in Word online. Therefore, I have spend the last days to get rid of them in my application. I could close several weird bugs.

**Comment by RuizhiSunMS** [comment] 2024-02-05 08:26
Have discussion with @xiruatms, since this issue turns to not be a block, I'd like to close this issue on Feb 18th. Please contact us or reopen this if you still get trouble.
Thx.

**Closed as completed** 2024-05-31 04:50 UTC
Labels: Type: product bug, Needs: author feedback, Area: Word, Status: in backlog, Status: no recent activity
