### ISSUE TITLE
Facing "Select a certification for authentication" everytime outlook add-ins is clicked. No AutoSelectCertificateForUrls to set for webview2

### ISSUE THREAD

**Issue by tanjooxiang** [OfficeDev/office-js#2550] opened 2022-04-26 04:08 UTC
OS: Window Server 2019 Standard
Outlook office version: 2112 Build 14729.20322

Hi All,

We are currently developing an Outlook App Add-ins for user to easily and quickly store information of the email into our application. When we are trying to use the outlook add-ins, it is prompting the **"Select a certification for authentication" everytime** we click on the add-ins. It happened even if there is only one certification to select. This is very inconvenience to the user. 

Upon checking, the outlook is default to use webview2 and thus the group policy of AutoSelectCertificateForUrls didnt kick in for us. There is no group policy for certification for webview2 as per doc by Microsoft. 

**Is there a way or a setting in office-js for us to program to auto select the certification**
OR
**anyone know if there is a way to do retain the caching of the certification selection?**

The goal we wish to achieve are:
1. Auto select certification when only one certification is available (best case scenario)
2. User select certification only once throughout the whole outlook session. 

Thank you in advance for any input.

**Comment by ElizabethSamuel-MSFT** [comment] 2022-04-27 21:19
@tanjooxiang Thanks for raising this issue. We'll take a look.

Thanks.

**Comment by tanjooxiang** [comment] 2022-05-10 10:07
Hi Team, 

any further updates on this issue? 

thank you.

**Comment by tanyajenkin21** [comment] 2022-12-22 21:27
This is an urgent issue for us to address.  Running Office 2021, for Word and PowerPoint hosts.  WebView2 component by design pays no attention to browser policy, and Office API provides no way to control WebView2 behaviour.  This affects all kinds of problems - caching behaviour and cert selection.  We can't use group policy (at least no documented feature) to force WebView2 to pick up updated add-in code.  We have at least 4 annoying certificate selection prompts to dismiss every time the user opens the add-in.

This is going to force us to drop the Office JS API.

**Comment by tanyajenkin21** [comment] 2023-03-08 22:52
Can we add Word & PowerPoint labels to this also as that is where we see the same issue?

**Comment by Dengshan2018** [comment] 2023-04-04 00:36
The fix was in 16.0.16302.20000+. Might be available in CC in the middle of April.

**Comment by Dengshan2018** [comment] 2023-04-04 00:44
@tanyajenkin21 , Just put the doc link for Office add-in authentication: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/overview-authn-authz

Let us know if the recommendation don't work for your case.

**Comment by tanyajenkin** [comment] 2023-04-04 03:56
Thanks @Dengshan2018.  Does 16.0.16302.20000+ refer to retail volume-licenced Office 2021 patch?  Does the fix also require updated office-js API?
Regards doc link, could you clarify which recommendation you are referring to exactly?  MS identity platform? Authentication with Office dialog API? SSO?  OAuth?

**Comment by Dengshan2018** [comment] 2023-04-05 15:08
@tanyajenkin, the change is only helping on the case when there is only one certificate for the authentication. Office will automatically select the certificate without the prompt. If there are multiple certificates, the prompt is still there. The change is only available on coming CC (Monthly Release and SEC (Semi-annual release) which version is greater than 16.0.16302.*.
The change will not be backported to old version.

The message with the doc link was misplaced. I deleted that reply. Please ignore it.

**Comment by tanjooxiang** [comment] 2023-04-05 15:31
Hello @Dengshan2018. The CC is "Current Channel"? Are you also talking about the version that are list on this page: https://learn.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date

If so, this is an outlook desktop application upgrade, but the information that we understand since the beginning of the issue is that this is related to the browser that Microsoft outlook used, which is Webview2 that does not have the "AutoSelectCertificateForUrls" policy to do the auto selection. 

Hope you can clarify my above understanding is correct and how this new outlook version will fix the issue.

Many thanks!

**Comment by Dengshan2018** [comment] 2023-04-05 16:56
Yes. CC means "Current Channel".

The change is not related with the policy of "AutoSelectCertificateForUrls".

When access the website which requires the certificate from clients, Edge/webview2 will filter the certificates installed in the client. if no certificate meets the requirement, then the request fails. if there are one more certificates met the requirement, then there is a prompt, let users pick one of them.

The change I mentioned: if there is only one certificate meet the requirement, then it doesn't make sense to prompt. Just automatically select the only certificate for users.

**Comment by Dengshan2018** [comment] 2023-08-29 19:09
The fix is in Current Channel.

**Closed as completed by Dengshan2018** 2023-08-29 19:09 UTC
Labels: Needs: attention :wave:, Area: Outlook, Type: product bug, Area: Edge WebView
