### ISSUE TITLE
Pinned Taskpane is unclickable when transitioning from Inbox -> Inline Reply

### ISSUE THREAD

**Issue by gummybuns** [OfficeDev/office-js#1713] opened 2021-03-12 18:14 UTC
## Expected Behavior
When a user opens the Taskpane in Inbox Mode, pins the Taskpane, and replies to an email in Inline Reply Mode, the pinned taskpane should be responsive.

## Current Behavior
Instead, the Taskpane UI is unclickable, giving off the appearance that it is frozen.

I believe what is happening is the pinned taskpane was opened in Inbox Mode and Inline Reply requires the Compose Taskpane so Outlook does not even associate the Taskpane with the Reply.

Outlook should maybe cover the entire Taskpane with messaging to tell the user it is not available in Inline Reply Mode

## Steps to Reproduce, or Live Example
Steps to Reproduce:
1. Open taskpane in the inbox view
2. Pin taskpane
3. Click reply (which brings us to the in-line reply mode)
4. Everything in the taskpane is now unclickable

We have noticed you can do these steps starting with Inline Reply mode as well, pinning, and then going back to Inbox mode

## Context
Our customers think our Taskpane is freezing when they try to make replies.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2101 13628.20448
* Operating System: Windows 10

## Useful logs
![Kapture 2021-03-12 at 10 04 51](https://user-images.githubusercontent.com/47437711/110980463-b8ef2200-831a-11eb-9558-15bdece4515e.gif)
(sorry for the two cursors, it is a recording of a screen share. The white cursor belongs to the outlook user)

**Comment by exextoc** [comment] 2021-03-12 18:50
The problem with an unclickable pinned taskpane for an in-line reply is a known issue that we have in our backlog. We unfortunately have no timelines to share at this point regarding this issue.

**Comment by skaramchandani11** [comment] 2021-04-15 21:19
> The problem with an unclickable pinned taskpane for an in-line reply is a known issue that we have in our backlog. We unfortunately have no timelines to share at this point regarding this issue.

@exextoc Can you provide an update here please? Many of our customers who use our add-in are running into this

**Comment by exextoc** [comment] 2021-04-27 01:01
The issue is fixed in all windows builds 21340 and later. Status on backports to older versions of Windows is still being decided.

**Comment by skaramchandani11** [comment] 2021-05-03 22:37
@exextoc - thank you for the information. Looks like that Windows build is in Beta. when will that be available in GA?

**Comment by exextoc** [comment] 2021-05-14 23:14
We unfortunately have no timelines to share at this point regarding the expected release date of that Windows build.

**Comment by exextoc** [comment] 2021-10-29 20:03
This issue was fixed, and the fix should be available in Windows build 19043.1266 or later. Note that it is the Windows Build that matters, not the Office build.

**Closed as completed by exextoc** 2021-10-29 20:03 UTC
Labels: Area: Outlook, Status: fixed
