### ISSUE TITLE
Web Outlook - Empty Body with Office.context.mailbox.item.body.getAsync in reply mode

### ISSUE THREAD

**Issue by kouxing2000** [OfficeDev/office-js#4198] opened 2024-03-01 03:31 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Mac Chrome Version 122.0.6261.69
 
## Expected behavior

When in reply mode, using Office.context.mailbox.item.body.getAsync should return the body of the email being replied to.

## Current behavior

When in reply mode, Office.context.mailbox.item.body.getAsync initially returns an empty value. It only returns the body content after clicking on the body of the content of previous email.

## Steps to reproduce

Open an email in web Outlook and click reply.
Without clicking on the body of the reply content, use Office.context.mailbox.item.body.getAsync to get the body content. Observe that it returns an empty value. Tried both text and html format.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

After the above steps, click on the body of the email thread, on any text.
Use Office.context.mailbox.item.body.getAsync again to get the body content.
Observe that it now returns the typed content.

## Context

This issue affects the ability to programmatically access the body of an email being replied to, which is a common requirement in Outlook add-in development.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ajays-msft** [comment] 2024-03-01 06:37
This is a duplicate of #2317 . Closing this issue, and follow the other issue for updates.

**Closed as completed by ajays-msft** 2024-03-01 06:37 UTC
Labels: Area: Outlook, Resolution: duplicate
