### ISSUE TITLE
Certificate / Timeout error while loading files hosted on https://appsforoffice.microsoft.com/lib/1/hosted/

### ISSUE THREAD

**Issue by s-ratashnyuk** [OfficeDev/office-js#3418] opened 2023-06-09 21:35 UTC
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, Office on the Web 
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: Mac OS
* Browser (if using Office on the web): Edge
 
## Expected behavior
The script load correctly

## Current behavior
Sometimes (I suspect some CDN nodes) script loading failed with certificate/timeout errors
Scripts:
https://appsforoffice.microsoft.com/lib/beta/hosted/excel.js
https://appsforoffice.microsoft.com/lib/1/hosted/office.js

## Steps to reproduce

1. Install any Excel add-in
2. Reload few times the add-in
3. The taskpane will be blank, the dev tools window will display an error

![screen1](https://github.com/OfficeDev/office-js/assets/101244942/258ddfd2-eaaa-47bf-810d-26c4a45ca42e)
![screen2](https://github.com/OfficeDev/office-js/assets/101244942/0097fc49-ac0f-4320-875c-6619e206db88)
![screen3](https://github.com/OfficeDev/office-js/assets/101244942/978517cb-58ad-4ac9-a06b-76a983e71af1)
![screen4](https://github.com/OfficeDev/office-js/assets/101244942/1b808222-f9a6-4ab2-abbd-da43a4521db2)

## Context

It's a blocker for using add-ins at all

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by JinghuiMS** [comment] 2023-06-12 03:27
Thanks for raising this question. we can't repro locally. In order to better assist you, could you give us the steps to stabilize the repro? And the files/codes required by repro if possible.

**Comment by wh1t3cAt1k** [comment] 2023-06-12 15:35
@JinghuiMS @s-ratashnyuk it only happens sporadically and I suspect it has to do with one of the CDN servers not responding with a proper certificate. 

Can you check on your side all the IPs that can potentially load `excel.js` and whether **any** of them might have a certificate misconfigured?

**Comment by gmichaud** [comment] 2023-06-12 16:07
I created a bash script that repeatedly retrieves the office.js file, and I was able to replicate the issue after a few minutes. I have found a specific IP address that has the certificate issue -- the server certificate I receive from your CDN shows urbanoutfitters.com as common name. I re-ran it a few times, and the issue is always with the same IP address, 104.127.164.170.

I wouldn't be surprised this affects other Office functionality and would recommend escalating to your infrastructure team ASAP!

My script:

```
#!/bin/bash
$@
while [ $? -eq 0 ]; do
    sleep 1
    curl -s --verbose --fail --head -o office.js https://appsforoffice.microsoft.com/lib/1/hosted/office.js
done
```

Here's a sample invalid response, coming from IP 104.127.164.170:
```
* Connected to appsforoffice.microsoft.com (104.127.164.170) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [332 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* (304) (IN), TLS handshake, Unknown (8):
{ [35 bytes data]
* (304) (IN), TLS handshake, Certificate (11):
{ [2999 bytes data]
* (304) (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* (304) (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* (304) (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: C=US; ST=Pennsylvania; L=Philadelphia; O=Urban Outfitters Inc.; CN=*.urbanoutfitters.com
*  start date: Mar 28 00:00:00 2023 GMT
*  expire date: Mar 28 23:59:59 2024 GMT
*  subjectAltName does not match appsforoffice.microsoft.com
* SSL: no alternative certificate subject name matches target host name 'appsforoffice.microsoft.com'
* Closing connection 0

```

Here's a valid response:

```
*   Trying 23.50.75.42:443...
* Connected to appsforoffice.microsoft.com (23.50.75.42) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [332 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* (304) (IN), TLS handshake, Unknown (8):
{ [35 bytes data]
* (304) (IN), TLS handshake, Certificate (11):
{ [3704 bytes data]
* (304) (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* (304) (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* (304) (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=appsforoffice.microsoft.com
*  start date: Jan  4 21:02:02 2023 GMT
*  expire date: Dec 30 21:02:02 2023 GMT
*  subjectAltName: host "appsforoffice.microsoft.com" matched cert's "appsforoffice.microsoft.com"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure TLS Issuing CA 01
*  SSL certificate verify ok.
```

**Comment by gmichaud** [comment] 2023-06-12 16:58
Re-ran and found another IP address that points to a non-reponsive host:

```
*   Trying 23.78.192.220:443...
* connect to 23.78.192.220 port 443 failed: Operation timed out
* Failed to connect to appsforoffice.microsoft.com port 443 after 75014 ms: Couldn't connect to server
* Closing connection 0
```

To recap, there's **at least two problematic IP addresses** behind appsforoffice.microsoft.com:
- IP address pointing to server with invalid SSL certificate (104.127.164.170 - urbanoutfitters.com)
- IP address pointing to non-responsive server (23.78.192.220)

We are able to reliably replicate both issues using the script above. It usually takes a few minutes for us to hit one of the problematic IPs.

**Comment by wh1t3cAt1k** [comment] 2023-06-12 18:09
@JinghuiMS @ruijiaMS Adding to the above by @gmichaud, I think it's not enough to just fix the two problematic IP addresses, but also:

- To find, on your side, any other offending IPs.
- **Take protective measures on the CDN side**, if possible, to avoid serving from upstream IPs that do not respond with a valid SSL cert.

**Comment by gmichaud** [comment] 2023-06-14 14:54
@JinghuiMS @ruijiaMS any update on this? The issue is still replicable right now, and is certainly affecting ANY application using Office.js (and not just Excel).

**Comment by LouMM** [comment] 2023-06-14 16:11
Thank you, everyone for the info and follow-ups. **Much appreciated!** 

We are working with our Akamai partners to determine the issue here. Microsoft hosts the files on an origin server in a number of regions, and the files are then cached by Akamai for retrieval by you. We need to confirm what's going on with the Certs and whether this is a DNS issue or not. We have created an incident, and I will try and keep everyone posted when we hear back. 

https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online

**Comment by LouMM** [comment] 2023-06-14 21:04
Can others confirm the errors they are seeing? Are they unavailable errors or cert issues related to subject name?

**Comment by gmichaud** [comment] 2023-06-14 21:07
@LouMM add-in side panel is blank -- we found out it's because of certificate issues / timeouts by opening dev tools to look at console. There's screenshots in my initial post.

**Comment by gmichaud** [comment] 2023-06-14 21:08
@LouMM note that on Excel Online, it shows an error message at the top of the blank side panel:
<img width="205" alt="Screenshot 2023-06-14 at 5 07 57 PM" src="https://github.com/OfficeDev/office-js/assets/9433888/bf11397f-5288-4fe5-beb8-e2cdf5a01062">

**Comment by LouMM** [comment] 2023-06-14 21:10
@gmichaud we aren't seeing this issue be widespread, so I wanted to confirm the impact. Are you saying we can close incidents at this point?

**Comment by gmichaud** [comment] 2023-06-14 21:12
> Can others confirm the errors they are seeing? Are they unavailable errors or cert issues related to subject name?

@LouMM multiple users have reported that the add-in doesn't always load and that they have to restart Excel. The side panel is blank, that's the symptom they report. We initially thought it was a transient bug on our side and ignored it for a while, until the issue severely disrupted a sales demo we were doing. 

Issue can still be replicated very easily with the bash script I posted above, just ran it and got 23.78.192.22 IP address (the IP mentioned in original issue description that is unresponsive):
<img width="682" alt="Screenshot 2023-06-14 at 5 12 29 PM" src="https://github.com/OfficeDev/office-js/assets/9433888/e13093c1-8f73-4dc7-844d-dd272d172088">

**Comment by gmichaud** [comment] 2023-06-14 21:35
> We aren't seeing this issue be widespread, so I wanted to confirm the impact. Are you saying we can close incidents at this point?

@LouMM the issue is very much current. It has been around for weeks, maybe longer. We initially thought it was a transient bug on our side and ignored it for a while. We have a COM-based add-in that serves the bulk of our customer base but recently launched something new that works exclusively on the modern add-ins platform and we're spending a lot more time with it than before. The issue has disrupted more than one product demo in the last 2 weeks and we wanted to get to the bottom of it. 

Does Excel internally load anything from appsforoffice.microsoft.com? If so you might have telemetry about this error (assuming Office logs this and uploads it somewhere). I doubt however you can capture errors happening inside the add-ins themselves since the add-in is responsible for loading the Office.js file from your CDN.

Another hypothesis - is it possible that Akamai is serving different IP addresses depending on the region? My script currently shows the following IP addresses being used for appsforoffice.microsoft.com:
23.63.168.123
23.64.240.232
23.78.192.220 (unresponsive host)
104.127.164.170 (urbanoutfitters.com host -- just replicated a few minutes ago)

I'm using curl in the bash script and I think it caches the DNS results for 30 seconds, so it takes a bit of time to hit the faulty IPs, but I can do it reliably. I just did it to get the full list of IPs being returned and saw both the unresponsive host and the urbanoutfitters.com IP. 

If you had a QA person verify this from Microsoft Office in your network, it's also possible that you have an internal DNS that caches IP addresses for longer, making it even harder to replicate. On my side if I have someone launch Excel and open our add-in every 30 seconds, I know they will eventually replicate the error. We built the bash script to see the actual certificate error / IP address and to make it easier to test -- it's a lot easier.

Is someone from Akamai able to confirm the list of IP addresses that are used, and whether the IPs above make sense? The urbanoutfitters.com IP is the most interesting one...

**Comment by LouMM** [comment] 2023-06-14 22:02
Thanks @gmichaud. The error you posted, the IP 104.127.164.170 referenced is on different certificate slot than the one for appsforoffice.microsoft.com. Are these all internal users running into this issue? We are trying to confirm there is a DNS issue here.
Can you try to do a DNS appsforoffice.microsoft.com and report it back to us the IP’s retrieved? Maybe 50x?

**Comment by gmichaud** [comment] 2023-06-14 22:12
@LouMM I just did nslookup in a loop

23.50.75.42 (didn't see this one earlier)
23.63.168.123
23.64.240.232
23.78.192.220 (unresponsive host)
23.194.163.209 (didn't see this one earlier)
104.127.164.170 (urbanoutfitters.com host)
Screenshots of suspicious IPs being returned:

<img width="670" alt="Screenshot 2023-06-14 at 6 12 00 PM" src="https://github.com/OfficeDev/office-js/assets/9433888/720dcd66-d535-4141-b120-bb15b23690fb">

<img width="702" alt="Screenshot 2023-06-14 at 6 12 17 PM" src="https://github.com/OfficeDev/office-js/assets/9433888/59cf272e-791c-4bfa-98e2-be6d85f37dfa">

**Comment by gmichaud** [comment] 2023-06-14 22:26
Hopefully that screenshot will further prove the IP being returned was not random or caused by our network. I just used dig in Google toolbox and got another 104.127.*.* address:

![IMG_6627](https://github.com/OfficeDev/office-js/assets/9433888/f8eefe20-01f3-4d65-8294-fbf7725a82da)

Not yet 104.127.164.170 but if I try and try I know I’ll get it eventually.

**Comment by LouMM** [comment] 2023-06-14 22:29
@gmichaud Appreciate the additional data. Passing this along as we dig in more.

**Comment by gmichaud** [comment] 2023-06-14 22:59
@LouMM in case that matters, we are based in Canada - I ran nslookup from a tool that uses different name servers across the globe and noticed the IPs are vastly different based on the country.

**Comment by LouMM** [comment] 2023-06-14 23:12
Thanks @gmichaud! Apologies for all the diagnostic tries. Your dns responses are odd and problematic and we are trying to get to the bottom of it. Can you try to navigate to www.t1info.net/tyq238 a few times until you see some of the problematic IPs in your list?

**Comment by wh1t3cAt1k** [comment] 2023-06-15 11:59
@LouMM just to clarify, are you expecting to see the problematic IP in the "Edge IP" section of the diagnostic site?

**Comment by gmichaud** [comment] 2023-06-15 14:20
@LouMM I couldn't get the Edge IP addresses on the Diagnostic Information to match the IP addresses I'm seeing when doing a nslookup or curl on appsforoffice.microsoft.com. I tried it multiple times.

Here are two screenshots showing download failing, with corresponding Diagnostic Information on the right. I did click the submit button, in case that's helpful.

<img width="1683" alt="SSL Certificate Mismatch" src="https://github.com/OfficeDev/office-js/assets/9433888/d58373aa-cb45-4e40-87eb-01629d11a843">
<img width="1673" alt="Unresponsive IP" src="https://github.com/OfficeDev/office-js/assets/9433888/189dd385-86ae-4057-8b78-2e0f4a4db8e6">

**Comment by wh1t3cAt1k** [comment] 2023-06-16 12:50
@LouMM just pinging you for an update on this...

**Comment by gmichaud** [comment] 2023-06-16 15:44
@LouMM I decided to try something today -- we changed our DNS to Cloudflare (1.1.1.1) to see if it would have any impact. My understanding is that it [hides our location completely](https://community.cloudflare.com/t/1-1-1-1-prevents-geoip-based-dns-lookups-from-working/173272/3) so Akamai wouldn't be able to return geo-localized IPs for us. The bash script has been running for more than 30 minutes and I'm only getting valid IPs.

A difference that I see is that the IPs seem to be cached longer than when I use the default ISP-provided DNS.

Another test I did is to run "dig" on appsforoffice.microsoft.com from a variety of DNS servers in Canada to see if any will serve the faulty IPs -- so far only our ISP (Videotron, the largest cable internet provider in the province) seems to be returning the invalid IPs. How can we be 100% sure the issue is specific to this DNS server and not based on a precise location+Akamai returning invalid IPs?

**Comment by LouMM** [comment] 2023-06-20 01:32
Quick update from my side. Working with the CDN provider, they determined that this is most likely a local DNS issue with your ISP.  If this was an issue from the CDN side passing out incorrect IP addresses, there would be a number of other errors that came along with it.  

We have done tests in all of our regions and are able to see the resource returned signed and sourced from the correct origin. 

Are you able to open a case with your provider?

**Comment by gmichaud** [comment] 2023-06-21 15:08
Thanks for all your help Lou. That makes sense. I also started thinking it’s an ISP-specific issue after I was unsuccessfully able to replicate the issue with a script that works off a list of known public Canadian DNS servers (see my previous comment). I’m on vacation this week but have a reminder to open a ticket with them once I’m back. The good news is that the vast majority of our customers (99%+) are outside the area served by this ISP.

**Comment by LouMM** [comment] 2023-06-21 16:38
Closing this for now since it looks to be a local ISP DNS issue. However, it was refreshing to work with all of you on the issue and I learned some things along the way. Please don't hesitate to reach back out to our team in the future. Cheers!

**Closed as completed by LouMM** 2023-06-21 16:38 UTC
Labels: Area: Excel, Type: product bug, Status: under investigation
