### ISSUE TITLE
PowerPoint content add-in won't load in presentation mode (PowerPoint Online)

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/office-js#302] opened 2018-11-21 20:03 UTC
## Note
I'm opening this issue on behalf of customer @butchmarshall, per this SO question: https://stackoverflow.com/questions/53418487/powerpoint-online-office365-content-add-in-never-loads-in-slide-show-mode-off. Seems possibly related to issue #198.

## Expected Behavior
Within both PowerPoint for Windows and PowerPoint Online, a PowerPoint content add-in should render/function properly in Edit mode and in Presentation mode.

## Current Behavior
- In PowerPoint for Windows, a PowerPoint content add-in *does* render/function properly in Edit mode and in Presentation mode.
- In PowerPoint Online, a PowerPoint content add-in renders/functions properly in Edit mode, but **does not** render/function property in Presentation mode.

## Steps to Reproduce
1. Use Visual Studio to create a **content** add-in for PowerPoint.
2. After the Visual Studio solution is created, press **F5** (Start) to run the project.
3. Verify functionality in PowerPoint (Windows desktop):
    - When you run the Visual Studio project, PowerPoint (Windows desktop) launches and your content add-in is displayed in Edit mode.
    - In PowerPoint (Windows desktop) where your content add-in is running, switch to Presentation mode. You'll see that your content add-in is also rendered properly in Presentation mode (as expected).
4. Test functionality in PowerPoint Online:
    - Ensure that the Visual Studio add-in project is still running (i.e., in debug mode).
    - Open a presentation in PowerPoint Online and sideload your add-in. (_**Hint**_: The XML manifest that you need to sideload in PowerPoint Online is located within the `\bin\Debug\OfficeAppManifests\` folder under the folder location where your Visual Studio add-in project was created.)
    - After you've sideloaded your add-in in PowerPoint Online, you should see that your content add-in is rendered properly in Edit mode.
    - In PowerPoint Online, switch to Presentation mode. Instead of seeing your content add-in be successfully rendered in Presentation mode, you'll see this error:
            ![image](https://user-images.githubusercontent.com/3019529/48865228-cff15b00-ed83-11e8-85d7-47f2b48320e0.png)

## Context
Trying to build a content add-in for PowerPoint that will render/function properly in Edit mode and in Presentation mode.

## Your Environment
* Platform: Office Online
* Host: PowerPoint
* Browser: Chrome

**Comment by butchmarshall** [comment] 2018-11-21 20:36
Thank you @kbrandl!  Yes, this looks to be the same issue as #198. Presentation mode in powerpoint online for content add-ins is broken.

**Comment by kbrandl** [comment] 2018-12-05 18:52
@JuaneloJuanelo are you able to provide any update on this issue?

**Comment by JuaneloJuanelo** [comment] 2018-12-12 00:21
closing as a dupe of : https://github.com/OfficeDev/office-js/issues/302

**Comment by JuaneloJuanelo** [comment] 2018-12-12 00:23
we are able to repro tracking with 2737719 we are working on a fix ASAP. thanks! 
btw this only happens when sideloading or corp deployment. if the add-in is published to the store there is no issue.

**Comment by JuaneloJuanelo** [comment] 2019-02-27 17:42
hello all... a quick update here, we are working on a fix, the fix is a bit more costly than expected. in the meantime we have a workaround you can use.

We will update this issue when the fix is published.

 **Use legacy viewer**

1.	Change the Doc.aspx in url to wopiframe.aspx
2.	Insert all the side-loaded add-ins needed as usual
3.	Add-ins now work in presentation mode

**Comment by tutieu** [comment] 2019-04-08 04:10
The tracking bug 2737719 for this issue was fixed on 3/12.

**Closed as completed by tutieu** 2019-04-08 04:10 UTC
Labels: Type: product bug, Area: PowerPoint, Resolution: has workaround
