### ISSUE TITLE
Outlook Desktop, Office.context.roamingSettings.set does not work

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#4142] opened 2024-02-15 17:08 UTC
# Provide required information needed to triage your issue
In Outlook add-in we use the Office.context.roamingSettings interface and its methods to store and retrieve some data. After setting and saving specific data, the Office.context.roamingSettings.get method returns undefined instead of saved value.

## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: Version 2401 (Build 17231.20194)
* Operating System: Windows 10 Version 22H2 (OS Build 19045.4046)
* Browser:
 
## Expected behavior
The Office.context.roamingSettings interface and its methods shall work correctly.

## Current behavior
The Office.context.roamingSettings.get method returns undefined instead of saved value.

## Steps to reproduce
1. In the add-in pane execute the following code:
Office.context.roamingSettings.set('test-add-in-data', 'text \u204d text');
Office.context.roamingSettings.saveAsync();

2. Close the pane and open it again.

3. Execute the following code:
console.log(Office.context.roamingSettings.get('test-add-in-data'));

As you can see, undefined is returned.

# Provide additional details
At the moment, we can reproduce the bug only in Outlook Desktop.
If you remove \u204d from value, everything start working.

**Comment by ndeleuze** [comment] 2024-03-07 22:05
@DmitryKostochko I have followed your repro steps for a newer (17505.20000) and older (17126.20190) build of Outlook and I'm not able to reproduce this issue.

Would you be able to provide a video of the issue?

**Comment by DmitryKostochko** [comment] 2024-03-08 10:59
I have just reproduced the issue with Version 2402 (Build 17328.20162).
To what email address should I send the video?

**Comment by ndeleuze** [comment] 2024-03-08 16:36
@DmitryKostochko are you able to post the video on this thread?

Also, does this issue reproduce in more recent builds?

**Comment by DmitryKostochko** [comment] 2024-03-11 13:45
@ndeleuze, please have a look:

https://github.com/OfficeDev/office-js/assets/28924916/12e7c8c8-3a79-46d9-b6e2-c543c7abbb51

If you have any questions or need more information, feel free to ask me.

**Comment by ndeleuze** [comment] 2024-03-19 21:13
@DmitryKostochko thank you for the video.

I'm still unable to reproduce this issue. (I also tried to repro this on build 17328.20184 with no luck)

Just to confirm, are you able to retrieve the roaming setting when the taskpane is not first closed?

**Comment by timwan10** [comment] 2024-03-19 21:30
Hm, I'm also not able to repro. I tried the exact steps, in the inspect debugger as in your video. Is it possible there is something else your add-in is doing in OnReady/Initialize that is affecting settings? (I do know this is probably unlikely). 

can you try in Script Lab (downloadable from the store), and see if the problem repros with this add-in as well?

What happens if you immediately get the value without refreshing or saving? 

![image](https://github.com/OfficeDev/office-js/assets/17890744/90e20cdb-fb59-4c06-bfb9-c8af00a75fba)

Is it possible for you to step into roamingSettings.set ? To see if anything is failing? (it might be helpful you use office.debug.js instead of office.js)

does Save return any errors? 

```
Office.context.roamingSettings.saveAsync(function (asyncResult) {
		 if (asyncResult.status == "failed") {
			console.log("Action failed with error: " + asyncResult.error.message);
                  }
		 else {
			 console.log("Settings saved with status: " + asyncResult.status);
		 }
});
```

**Comment by DmitryKostochko** [comment] 2024-03-20 10:56
@ndeleuze, closing and opening the taskpane is required because of:

_The persisted changes will not be available until the task pane (or item in the case of UI-less add-ins) is closed and reopened._
https://learn.microsoft.com/en-us/javascript/api/outlook/office.roamingsettings?view=outlook-js-preview#remarks

**Comment by DmitryKostochko** [comment] 2024-03-20 11:39
@timwan10, 

>> Hm, I'm also not able to repro. I tried the exact steps, in the inspect debugger as in your video.

Could you please provide a video of what you are doing? This could help me spot the difference between yours steps and mine.

>> can you try in Script Lab (downloadable from the store), and see if the problem repros with this add-in as well?

The bug is reproducible with Script Lab.

>> What happens if you immediately get the value without refreshing or saving?

The get method works in this case.

>> does Save return any errors?

I don't see any errors.

If you have any questions or need more information, please let me know.

**Comment by ndeleuze** [comment] 2024-04-10 22:49
@DmitryKostochko here is my attempt at reproducing this issue:


https://github.com/OfficeDev/office-js/assets/107273303/df5b1bfb-e743-48af-9f5b-9a971cfc4325

This is with build 16.0.17328.20282, but I am still not able to reproduce your issue. Please let me know if you find any discrepancies between your repro and mine.

Are you experiencing this issue on new builds?

**Comment by DmitryKostochko** [comment] 2024-04-11 08:17
@ndeleuze, thank you for the video, your steps seem correct.

But I have just reproduced the issue with 16.0.17425.20124 32-bit version.

What Outlook bitness do you have installed?

May it be that you have another Outlook window with the "Script Lab for Outlook" pane open? Please try to restart your Outlook and then execute the Office.context.roamingSettings.get method.

**Comment by ndeleuze** [comment] 2024-04-30 22:00
@DmitryKostochko I unfortunately do not have a 32-bit version that I can test against, but I am certain that I do not have another Script Lab pane open when attempting the repro.

What is the business impact of this issue? Number of users impacted?

**Comment by DmitryKostochko** [comment] 2024-05-01 09:42
@ndeleuze I just tested the issue with the 64-bit version and can confirm that it is reproducible.
_Version 2404 (Build 17531.20120 Click-to-Run)_

>> What is the business impact of this issue? Number of users impacted?

This bug seriously affects our users.

**Comment by Oleg-O** [comment] 2024-07-10 19:02
@DmitryKostochko is this still an issue, or has it been resolved or worked around?

FWIW, I've also tried reproducing and was not able to.

When you say "the bug seriously affects our users" - is that because this specific character needs to be saved in roaming settings in many cases, or it's just an example and more characters are causing similar issue?

**Comment by DmitryKostochko** [comment] 2024-07-11 15:46
I cannot reproduce the issue today. I have Outlook version 2406 (Build 17726.20126).

>> When you say "the bug seriously affects our users" - is that because this specific character needs to be saved in roaming settings in many cases, or it's just an example and more characters are causing similar issue?

We found just one character that caused the bug, it was \u204d. I don't know if other characters could cause issues.

Thank you!

**Comment by ndeleuze** [comment] 2024-07-30 17:21
@DmitryKostochko since this no longer reproduces for you and our team has not been able to successful reproduce the issue, I will close this post. Please reopen if this issue resurfaces. Thank you.

**Closed as completed by ndeleuze** 2024-07-30 17:21 UTC
Labels: Area: Outlook
