### ISSUE TITLE
Outlook Add-in Command periodicaly opens new browser window

### ISSUE THREAD

**Issue by dmitry-semenov** [OfficeDev/office-js#1680] opened 2021-03-01 15:26 UTC
## Expected Behavior

Add-In Comman should not popup browser window with the function file URL from manifest

## Current Behavior

Our product customer reports that their extension periodically opens new window at the URL we defined as our function URL instead of executing the function itself.

## Steps to Reproduce, or Live Example
n/a

## Context
n/a

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 13127.21216
* Operating System: Windows
* Browser (if using Office on the web): -

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

![image](https://user-images.githubusercontent.com/17027799/109518319-d0284700-7ab2-11eb-82b2-f54b956e422c.png)

**Comment by exextoc** [comment] 2021-03-01 22:41
It's not clear what you are asking. If you installed the add-in "SalesLoft". and it is popping up a dialog, then you should take the issue up with the Add-in Developer. 

If you are a developer writing this add-in, then we need to know what APIs that you are calling that is causing this.

**Comment by dmitry-semenov** [comment] 2021-03-02 09:52
Hi @exextoc I'm developer of this add-in, and the issue seems to happen immediately after the ribbon button is pressed - while it should run function in the function file, the Outlook opens the function file URL in the new browser window instead.
The first API in this function we use is the notification API that should print "Lofting in progress..." and this is not happening.

**Comment by exextoc** [comment] 2021-03-02 21:09
I don't repro this issue. (your build of Outlook while not the latest seems reasonably recent).

Do you repro the issue 100% of the time with your add-in? Did it ever work? Does it work on other platforms? (OWA, Mac?)

We haven't had reports of anything similar to this before, or been able to repro, so my initial reaction is that something inside your add-in may be doing this. (are you doing any calls to window.open in your HTML somewhere?) On the other hand, maybe you've managed to find a new obscure bug. Can you whittle down your code and manifest to the smallest possible to reproduce the issue, and provide it to use for us to debug?

**Comment by dmitry-semenov** [comment] 2021-03-02 23:06
Well, the issue here is that this is our customer's report, I was not able to reproduce the issue as well. 
https://outlook-connect.salesloft.com/manifest/manifest.xml here's our manifest which works just fine for the rest of our users.
I checked the codebase for `window.open` and didn't find any calls to it at all.
The only real confirmation of the issue I've got is the screenshot from a customer (attached) which has our functions url opened when they press the button which should act as a command. 
As for the version it is latest in the `Semi-Annual Enterprise Channel` atm so we can't even suggest a customer to upgrade.

**Comment by exextoc** [comment] 2021-03-02 23:30
Do other add-ins on that customer's computer also repro the issue? For reference, they can install "Script Lab" from the Office Store under "Get Add-ins" And click the "Code" button. This is *supposed* to bring up a client dialog that lets you edit snippets. But if instead it brings up the functions file in another browser window, then obviously it's not something in your add-in. 

Can you provide me the specific build that the customer is on? To see if I can try and repro on that specific build. You mentioned that they are on the Semi-Annual Enterprise Channel, but I'm not exactly sure the specific build since this can still vary. I suspect they should be either on: 16.0.13127.XXXXX or 16.0.12527.XXXXXX but I want to make sure. 

If there is no personal information in the screenshot, if the customer could provide a full screenshot of everything that is going on that may also help.

**Comment by dmitry-semenov** [comment] 2021-03-03 10:13
Asking for additional info, this can take a while.

**Comment by dmitry-semenov** [comment] 2021-08-04 16:03
Another customer brought this to us again, they're on outlook version 16.0.13801.20442 and 16.0.13801.20772. Asked for a recording  but not sure if they can provide something due to the random nature of the issue.

**Comment by ihor-chepurnyi** [comment] 2021-08-16 14:42
Hi @exextoc, what else we can provide from our side except recording? It just randomly happens for our customers.
They still sometimes see a modal window
![image](https://user-images.githubusercontent.com/54581474/129582013-52988cc8-11a6-4428-834d-cf37c0b970bc.png)

**Comment by robert-gavrila** [comment] 2021-08-30 19:08
Does this issue happen after one click on the ribbon button or when the user double-clicks on it?

**Comment by robert-gavrila** [comment] 2021-08-30 21:27
Also, I'm interested to know the parent process of the opened browser window.

**Comment by dmitry-semenov** [comment] 2021-08-31 13:21
> Does this issue happen after one click on the ribbon button or when the user double-clicks on it?

It is single click

> Also, I'm interested to know the parent process of the opened browser window.

Need some time for this one

**Comment by dmitry-semenov** [comment] 2021-08-31 19:21
> Also, I'm interested to know the parent process of the opened browser window.

Is there any specific way to get the data you're interested in? cause it's just normal chrome window with chrome as a parent in the process list.

**Comment by dmitry-semenov** [comment] 2021-08-31 19:32
Maybe there is a way for other plugins to make such impact on the add-in? We don't have access to the customer's machines to get better understanding of their infrastructure/security software, and the issue seems to be isolated to just one customer (several users), so it seems to be a configuration thing.

**Comment by robert-gavrila** [comment] 2021-08-31 19:44
This is enough for now. I'll let you know if I need more info. Thanks

**Comment by robert-gavrila** [comment] 2021-09-02 19:27
Can you let me know which of the following processes is present on the failing customer machine when the add-in is loaded?
iexplore.exe || msedgewebview2.exe || (win32webviewhost.exe & wwahost.exe).

**Comment by dmitry-semenov** [comment] 2021-09-06 14:20
Don't have answer to the processes question yet, but we were able to capture repro video, can I get your contact to share it without posting it here as it contain our customer's data?

**Comment by robert-gavrila** [comment] 2021-09-07 22:58
> Don't have answer to the processes question yet, but we were able to capture repro video, can I get your contact to share it without posting it here as it contain our customer's data?
rgavrila@microsoft.com

**Comment by dmitry-semenov** [comment] 2021-09-15 07:29
Still an issue, sent a repro video & waiting for feedback

**Comment by exextoc** [comment] 2021-09-15 16:03
reopened the issue, bot incorrectly closed this.

**Comment by dmitry-semenov** [comment] 2021-09-22 13:51
![image](https://user-images.githubusercontent.com/17027799/134356262-e961d3e6-3e85-4622-b657-d9e76bcbf303.png)
highlighted user is the one from the video that I sent to @robert-gavrila

**Comment by robert-gavrila** [comment] 2021-10-26 19:44
I looked at the video with the repro and I saw the browser window opening. Thank you for sending it. I see that for this particular user none of the processes from the list was present, which cannot happen, is there a mistake in the highlighted line?

**Comment by dmitry-semenov** [comment] 2021-11-02 14:47
> I looked at the video with the repro and I saw the browser window opening. Thank you for sending it. I see that for this particular user none of the processes from the list was present, which cannot happen, is there a mistake in the highlighted line?

There should be no mistake here. Are these processes expected when the buggy window is open or loaded add-in is enough?

**Comment by robert-gavrila** [comment] 2021-11-02 17:31
The Add-in is loaded inside one of the processes that I mentioned. If none of them is present it means that we fail to load the add-in. It will be useful if you can provide the session Id / date of the Outlook instance when this happens.  You can find the session Id when you click on the "About Outlook" button.

**Comment by dmitry-semenov** [comment] 2021-11-18 19:31
user 1:  When she uses the Outlook Loft It button Google Chrome opens a new tab. Here is the URL that opens: https://outlook-connect.salesloft.com/functions?_host_Info=Outlook$Win32$16.02$en-US$$$$0
Session ID – E6E50636-ECE9-48F8-97F7-CED5063F6C5E
user 2
Session ID - DA2C2866-31CE-4305-804A-8721EDAD4BE5
user 3
Session ID – 6A3A8E59-0ADE-47E9-99A6-FE654D3D69E7

**Comment by robert-gavrila** [comment] 2021-12-09 03:04
We were not able to find much using the Session IDs provided, I think we will need an ULS log [Enable Microsoft 365 Apps for enterprise ULS logging for random issues - Office 365 | Microsoft Docs](https://docs.microsoft.com/en-us/office365/troubleshoot/diagnostic-logs/collect-office-diagnostic-logs) or an iDNA trace from the customer [Recording Time Travel Traces - OSG Wiki](https://www.osgwiki.com/wiki/Recording_Time_Travel_Traces)

**Comment by dmitry-semenov** [comment] 2021-12-15 09:40
@robert-gavrila can we setup a live debugging session with a customer for easier resolution?

**Closed as completed** 2022-09-30 11:06 UTC
Labels: Needs: attention :wave:, Area: Outlook
