### ISSUE TITLE
Word crashes when change hyperlink on range when track changes is enabled

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#2804] opened 2022-08-29 13:53 UTC
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop Windows
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 1908
* Operating System: Win10
* Browser (if using Office on the web): ______

## Steps to reproduce

Watch this video:  https://user-images.githubusercontent.com/6726111/187217192-bfa8fc26-6ed2-4843-b983-b1c96e94cbe2.mp4

or

1. Create a new Word document with the text "1234" as the only content
2. Run this code in scriptlab: 
``` typescript 
async function run(bold: boolean = false) {
  await Word.run(async (context) => {
    const body = context.document.body;
    await context.sync();

    const ranges = body.search("1234");
    ranges.load();
    await context.sync();

    const range = ranges.items[0];
    range.load();
    range.hyperlink = "http://penis";
    range.font.color = "red";
    await context.sync();

    console.log(JSON.stringify(range));
  });
}
```
3. Observe that the color of the text changes and an hyperlink is inserted (repeat in order to have fun)
4. Enable track changes an e.g. add some whitespace after the text 1234
5. run the code again
6. Word freezes

## Context
Our add-in crashes when our users use track changes.

**Comment by jipyua** [comment] 2022-08-30 09:31
Thanks for reporting this, we are locally investigating the root cause and will update once we have some progress.

**Comment by JensMadsen** [comment] 2022-11-10 14:24
Hi @jipyua . Any news on this one?

**Comment by jipyua** [comment] 2022-11-17 05:40
hi, this bug has been fixed internally, once the fix is deployed through the monthly update, you should be able to pick it.

**Comment by JensMadsen** [comment] 2022-12-22 14:37
@jipyua has the fix been deployed?

**Comment by jipyua** [comment] 2023-04-20 07:15
@JensMadsen yes, it has been deployed, sorry for replying late since I didn't check this post again.

**Closed as completed by jipyua** 2023-04-20 07:15 UTC
Labels: Needs: attention :wave:, Area: Word
